### ISSUE TITLE
[Bug] 2.16alpha29 crash: MyGestureDetector

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#10107]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/89c465ff-bb92-4436-bad0-1d7bd73891a4

```
java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.MotionEvent.getX()' on a null object reference
at com.ichi2.anki.AbstractFlashcardViewer$MyGestureDetector.isTouchingEdge(AbstractFlashcardViewer.java:4)
at com.ichi2.anki.AbstractFlashcardViewer$MyGestureDetector.onFling(AbstractFlashcardViewer.java:2)
at android.view.GestureDetector.onTouchEvent(GestureDetector.java:656)
at com.ichi2.anki.Reviewer.lambda$createWhiteboard$6(Reviewer.java:4)
at com.ichi2.anki.Reviewer.N(Unknown Source:0)
at com.ichi2.anki.j7.onTouch(Unknown Source:2)
at android.view.View.dispatchTouchEvent(View.java:12521)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3036)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2723)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3036)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2723)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3036)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2723)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3036)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2723)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3036)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2723)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3036)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2723)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3036)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2723)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3036)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2723)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3036)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2723)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3036)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2723)
at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:590)
at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1841)
at android.app.Activity.dispatchTouchEvent(Activity.java:3400)
at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:1)
at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:1)
at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:535)
at android.view.View.dispatchPointerEvent(View.java:12764)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5123)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4926)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4443)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4496)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4462)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4602)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4470)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4659)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4443)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4496)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4462)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4470)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4443)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7118)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7087)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7048)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7221)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:326)
at android.os.Looper.loop(Looper.java:165)
at android.app.ActivityThread.main(ActivityThread.java:6729)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by mikehardy** [comment]
Still needs triage
