### ISSUE TITLE
App get crashed in Note Editor preview when adding new note

### ISSUE THREAD

**Issue by krmanik** [ankidroid/Anki-Android#10291]
###### Reproduction Steps
1. Check out current master branch, build it
2. Add new item using Note editor
3. Click preview
4. App crashed

###### Expected Result
It should preview notes.

###### Actual Result
It gets crashed.

```
2022-01-31 02:07:17.623 20491-20491/com.ichi2.anki D/CollectionTask: enabling garbage collection of mPreviousTask...
2022-01-31 02:07:17.624 20491-23799/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: JavaBridge
    Process: com.ichi2.anki, PID: 20491
    java.lang.IllegalStateException: Should be called from the main thread, not Thread[JavaBridge,7,main]
        at curtains.internal.HandlersKt.checkMainThread(Handlers.kt:9)
        at curtains.WindowsKt.getWindowType(Windows.kt:37)
        at leakcanary.RootViewWatcher$listener$1.onRootViewAdded(RootViewWatcher.kt:44)
        at curtains.OnRootViewAddedListener$DefaultImpls.onRootViewsChanged(Listeners.kt:37)
        at leakcanary.RootViewWatcher$listener$1.onRootViewsChanged(RootViewWatcher.kt:43)
        at curtains.internal.RootViewsSpy$delegatingViewList$1.add(RootViewsSpy.kt:25)
        at curtains.internal.RootViewsSpy$delegatingViewList$1.add(RootViewsSpy.kt:23)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:454)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:114)
        at android.widget.ToastPresenter.show(ToastPresenter.java:379)
        at android.widget.Toast$TN.handleShow(Toast.java:1237)
        at android.widget.Toast$TN$1.handleMessage(Toast.java:1164)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

###### Debug info
```
AnkiDroid Version = 2.16alpha40

Android Version = 11

Manufacturer = samsung

Model = SM-M307F

Hardware = exynos9611

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-M307F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.98 Mobile Safari/537.36

ACRA UUID = 4c11fcc0-1844-43fa-a07e-0d825c5fe592

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by krmanik** [comment]
There were error in Card Template. It is working now.

**Comment by david-allison-1** [comment]
> There were error in Card Template. It is working now.

Which PR fixed this? There shouldn't be a crash from a bad template

**Comment by krmanik** [comment]
This is front side of card template. When I removed it, it works. So may be card template error.
```
{{Front}}
<div id="test"></div>

<script>

   var jsApi = {"version" : "0.0.2", "developer" : "dev@mail.com"};

  
 var apiStatus = AnkiDroidJS.init(JSON.stringify(jsApi));


AnkiDroidJS.ankiSetCardFlag(4);

document.getElementById("test").innerHTML=AnkiDroidJS.ankiGetCardFlag();
</script>

```

**Comment by krmanik** [comment]
But It works on 2.16alpha31

**Comment by krmanik** [comment]
I think I found the error. It should be in run on UI thread.
https://github.com/ankidroid/Anki-Android/blob/52ef757ef39d16c7c74c70c74ea71cf5f156f20e/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt#L137
