### ISSUE TITLE
[Bug] crash after full download

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#10307]
###### Reproduction Steps

1. Run on version c34dcdcb1a55edc042979cec62cb264b629669a2
2. do a full download

###### Expected Result
Application open

###### Actual Result
The collection is not opened

###### Debug info
I got 
```

E/FullSyncer: Failed to create temp file when downloading collection.
    java.io.FileNotFoundException: /storage/emulated/0/AnkiDroid/collection.anki2.tmp: open failed: EACCES (Permission denied)
        at libcore.io.IoBridge.open(IoBridge.java:492)
        at java.io.FileInputStream.<init>(FileInputStream.java:160)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at com.ichi2.libanki.sync.FullSyncer.download(FullSyncer.java:98)
        at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:424)
        at com.ichi2.async.Connection.doOneInBackground(Connection.java:219)
        at com.ichi2.async.Connection.doInBackground(Connection.java:209)
        at com.ichi2.async.Connection.doInBackground(Connection.java:60)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8514)
        at libcore.io.IoBridge.open(IoBridge.java:478)
        at java.io.FileInputStream.<init>(FileInputStream.java:160) 
        at java.io.FileInputStream.<init>(FileInputStream.java:115) 
        at com.ichi2.libanki.sync.FullSyncer.download(FullSyncer.java:98) 
        at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:424) 
        at com.ichi2.async.Connection.doOneInBackground(Connection.java:219) 
        at com.ichi2.async.Connection.doInBackground(Connection.java:209) 
        at com.ichi2.async.Connection.doInBackground(Connection.java:60) 
        at android.os.AsyncTask$3.call(AsyncTask.java:394) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
W/Connection: java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/AnkiDroid/collection.anki2.tmp: open failed: EACCES (Permission denied)
        at com.ichi2.libanki.sync.FullSyncer.download(FullSyncer.java:105)
        at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:424)
        at com.ichi2.async.Connection.doOneInBackground(Connection.java:219)
        at com.ichi2.async.Connection.doInBackground(Connection.java:209)
        at com.ichi2.async.Connection.doInBackground(Connection.java:60)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.io.FileNotFoundException: /storage/emulated/0/AnkiDroid/collection.anki2.tmp: open failed: EACCES (Permission denied)
        at libcore.io.IoBridge.open(IoBridge.java:492)
        at java.io.FileInputStream.<init>(FileInputStream.java:160)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at com.ichi2.libanki.sync.FullSyncer.download(FullSyncer.java:98)
        at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:424) 
        at com.ichi2.async.Connection.doOneInBackground(Connection.java:219) 
        at com.ichi2.async.Connection.doInBackground(Connection.java:209) 
        at com.ichi2.async.Connection.doInBackground(Connection.java:60) 
        at android.os.AsyncTask$3.call(AsyncTask.java:394) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8514)
        at libcore.io.IoBridge.open(IoBridge.java:478)
        at java.io.FileInputStream.<init>(FileInputStream.java:160) 
        at java.io.FileInputStream.<init>(FileInputStream.java:115) 
        at com.ichi2.libanki.sync.FullSyncer.download(FullSyncer.java:98) 
        at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:424) 
        at com.ichi2.async.Connection.doOneInBackground(Connection.java:219) 
        at com.ichi2.async.Connection.doInBackground(Connection.java:209) 
        at com.ichi2.async.Connection.doInBackground(Connection.java:60) 
        at android.os.AsyncTask$3.call(AsyncTask.java:394) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
```
and then

```
W/DatabaseErrorDialog: java.io.IOException: Cannot run program "sqlite3": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
        at java.lang.Runtime.exec(Runtime.java:699)
        at java.lang.Runtime.exec(Runtime.java:529)
        at java.lang.Runtime.exec(Runtime.java:426)
        at com.ichi2.anki.dialogs.DatabaseErrorDialog.onCreateDialog(DatabaseErrorDialog.kt:48)
        at com.ichi2.anki.dialogs.DatabaseErrorDialog.onCreateDialog(DatabaseErrorDialog.kt:36)
        at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:647)
        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:561)
        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:492)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
        at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:564)
        at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:506)
        at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:491)
        at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:487)
        at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.java:531)
        at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.java:517)
        at com.ichi2.anki.DeckPicker.showDatabaseErrorDialog(DeckPicker.java:1319)
        at com.ichi2.anki.DeckPicker.handleDbError(DeckPicker.java:1543)
        at com.ichi2.anki.DeckPicker$3.onPostExecute(DeckPicker.java:1803)
        at com.ichi2.async.Connection.onPostExecute(Connection.java:173)
        at com.ichi2.async.Connection.onPostExecute(Connection.java:60)
        at android.os.AsyncTask.finish(AsyncTask.java:771)
        at android.os.AsyncTask.access$900(AsyncTask.java:199)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:141)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at java.lang.Runtime.exec(Runtime.java:699) 
        at java.lang.Runtime.exec(Runtime.java:529) 
        at java.lang.Runtime.exec(Runtime.java:426) 
        at com.ichi2.anki.dialogs.DatabaseErrorDialog.onCreateDialog(DatabaseErrorDialog.kt:48) 
        at com.ichi2.anki.dialogs.DatabaseErrorDialog.onCreateDialog(DatabaseErrorDialog.kt:36) 
        at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:647) 
        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:561) 
        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1698) 
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:492) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701) 
        at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:564) 
        at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:506) 
        at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:491) 
        at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:487) 
        at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.java:531) 
        at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.java:517) 
        at com.ichi2.anki.DeckPicker.showDatabaseErrorDialog(DeckPicker.java:1319) 
        at com.ichi2.anki.DeckPicker.handleDbError(DeckPicker.java:1543) 
        at com.ichi2.anki.DeckPicker$3.onPostExecute(DeckPicker.java:1803) 
        at com.ichi2.async.Connection.onPostExecute(Connection.java:173) 
        at com.ichi2.async.Connection.onPostExecute(Connection.java:60) 
        at android.os.AsyncTask.finish(AsyncTask.java:771) 
        at android.os.AsyncTask.access$900(AsyncTask.java:199) 
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
```

I tried to delete /storage/emulated/0/AnkiDroid/collection.anki2.tmp and retry. But it still fails.

Also, I have largely enough storage on the device to ensure that I'm not lacking storage. 
The file is 212MO so should fit in memory anyway

**Comment by david-allison-1** [comment]
The warning about SQlite is fine and not related:

https://github.com/ankidroid/Anki-Android/blob/6fd41ae687a7dc5cd5fefee673cca38c033e378f/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt#L46-L53

**Comment by s-deepak-kumar** [comment]
Can You Please Assign This To Me?

**Comment by Arthur-Milchior** [comment]
I beg your pardon @s-deepak-kumar, no offense meant, but do you have any idea how to start investigating it?
If you can work on it, that's wonderful and I'll be delighted to assign it to you.
Right now, none of the maintainers have the slightest idea what occurred, and not even how to reproduce it. 
So if you already know what to do, then wonderful, go for it. No need to assign the issue, nobody else know what to do anyway.
Otherwise, please start by stating what you'll try, so I can at least examine whether it's worth pursuing

**Comment by s-deepak-kumar** [comment]
I tried, but i didn't get errors. Can you please tell me how to reproduce this error?

**Comment by Arthur-Milchior** [comment]
Could you please, @s-deepak-kumar, let me know if you read my last answer? I explicitly stated that we have no idea how to reproduce it. Nobody knows what to do with it right now, appart to be prepared to answer people to which this can occur.
