### ISSUE TITLE
[Bug] Impossible to list files

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#10358]
###### Reproduction Steps

1. Run on 81fcbe125c4c77d010965c0e2515952d21f2932a (HEAD, ankidroid/master)
2. Open ankidroid 
3. do "check media"

###### Expected Result
Media checking

###### Actual Result
Crash

###### Debug info

> 2022-02-18 20:30:43.696 4096-4402/com.ichi2.anki E/chromium: [ERROR:simple_version_upgrade.cc(147)] Failed to write a new fake index.
2022-02-18 20:30:44.678 4096-4427/com.ichi2.anki E/ion: ioctl c0044901 failed with code -1: Invalid argument
2022-02-18 20:32:11.109 4096-4586/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    Process: com.ichi2.anki, PID: 4096
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:415)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.NullPointerException: Attempt to get length of null array
        at com.ichi2.libanki.Media._changes(Media.java:716)
        at com.ichi2.libanki.Media._logChanges(Media.java:682)
        at com.ichi2.libanki.Media.findChanges(Media.java:636)
        at com.ichi2.async.CollectionTask$CheckMedia.task(CollectionTask.java:1463)
        at com.ichi2.async.CollectionTask$CheckMedia.task(CollectionTask.java:1451)
        at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:199)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:161)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:108)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 

Note that I can access individual media when playing cards. It's only listing files which break

AnkiDroid Version = 2.16alpha44

Android Version = 11

Manufacturer = samsung

Model = SM-A226B

Hardware = mt6833

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-A226B Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/98.0.4758.101 Mobile Safari/537.36

ACRA UUID = 2dd607ef-2035-4a30-9a76-10664a4b83aa

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

**Comment by david-allison** [comment]
What's the device info? Will check in an emulator

**Comment by Arthur-Milchior** [comment]
I don't know what you want that is not already in the debug (unless you answered before i edited the message with the debug)

**Comment by david-allison** [comment]
I added the message before you added debug info.

It would be useful to transfer the diagnostics from Discord to here, to keep a history of the problem.

**Comment by Chandra-Sekhar-Bala** [comment]
I am new to this, can anyone help to get stated ?

**Comment by Arthur-Milchior** [comment]
Sorry, but this is an issue where none of the maintainer right now have an idea abuot what to do. I really doubt it's a good issue for a beginner, unless you are already good with android file system.

Please look at issues with label "good first issue"

**Comment by Arthur-Milchior** [comment]
When I execute https://github.com/ankidroid/Anki-Android/pull/10364 and try to stream the same directory, I get > java.nio.file.AccessDeniedException: /storage/emulated/0/AnkiDroid/collection.media
        at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:434)
        at java.nio.file.Files.newDirectoryStream(Files.java:457)
        at com.ichi2.anki.servicelayer.scopedstorage.MoveDirectoryStream.<init>(MoveDirectoryStream.kt:22)
        at com.ichi2.compat.CompatV26.moveDirectory(CompatV26.java:192)

**Comment by Arthur-Milchior** [comment]
A bigger trouble is that i've no idea what to put as error message if this occur to a user. An error message is supposed to help them solve the issue. Here, the very single solution I would see for a user with this trouble is to:
* download a previous version of ankidroid,
* sync up
* download current version
* sync down

And this is clearly a solution that will be quite complex for a lot of people. Plus require to download two update and potentially two full sync, so costly in term of bandwidth.

**Comment by david-allison** [comment]
What happens if you `ls -la` to get permissions of the `collection.media` folder?

> A bigger trouble is that i've no idea what to put as error message if this occur to a user.

"Contact the developers. Do not uninstall the application" (or similar) - provide Discord and Mailing List options to get in touch

**Comment by Chandra-Sekhar-Bala** [comment]
> Sorry, but this is an issue where none of the maintainer right now have an idea abuot what to do. I really doubt it's a good issue for a beginner, unless you are already good with android file system.
> 
> Please look at issues with label "good first issue"

Thanks for providing the information. I'll start with that :-)

**Comment by Arthur-Milchior** [comment]
After installing ankidroid back from play store it works again. Then updating through android studio works too. No idea what's going on. Or even how to reproduce

**Comment by Arthur-Milchior** [comment]
@Chandra-Sekhar-Bala For your information, you can look at the number of commits and pull request we had to do to close this request. You may understand why we thought it would not be a good issue for beginners.

**Comment by mikehardy** [comment]
One of the worst ones I've seen, with regard to difficulty!
