### ISSUE TITLE
[Bug] Crashing when tapping Add note

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#10434]
###### Reproduction Steps

1. Tap `Add Note`

###### Expected Result

The add note screen should appear

###### Actual Result

It crashes

###### Debug info
```
AnkiDroid Version = 2.16alpha48

Android Version = 11

Manufacturer = samsung

Model = SM-N770F

Hardware = exynos9810

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-N770F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.58 Mobile Safari/537.36

ACRA UUID = e7a03b0c-3285-489b-8bcd-aa1e128e2eb5

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### Error log on android studio
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 23259
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.NoteEditor}: com.ichi2.utils.JSONException: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3846)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: com.ichi2.utils.JSONException: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long
        at com.ichi2.utils.JSONObject.getLong(JSONObject.java:345)
        at com.ichi2.anki.NoteEditor.setDid(NoteEditor.java:1834)
        at com.ichi2.anki.NoteEditor.onCollectionLoaded(NoteEditor.java:578)
        at com.ichi2.anki.AnkiActivity.startLoadingCollection(AnkiActivity.java:384)
        at com.ichi2.anki.NoteEditor.onCreate(NoteEditor.java:438)
        at android.app.Activity.performCreate(Activity.java:8207)
        at android.app.Activity.performCreate(Activity.java:8191)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3819)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
     Caused by: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long
        at org.json.JSON.typeMismatch(JSON.java:101)
        at org.json.JSONObject.getLong(JSONObject.java:528)
        at com.ichi2.utils.JSONObject.getLong(JSONObject.java:343)
        at com.ichi2.anki.NoteEditor.setDid(NoteEditor.java:1834) 
        at com.ichi2.anki.NoteEditor.onCollectionLoaded(NoteEditor.java:578) 
        at com.ichi2.anki.AnkiActivity.startLoadingCollection(AnkiActivity.java:384) 
        at com.ichi2.anki.NoteEditor.onCreate(NoteEditor.java:438) 
        at android.app.Activity.performCreate(Activity.java:8207) 
        at android.app.Activity.performCreate(Activity.java:8191) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3819) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
D/UsageAnalytics: sendAnalyticsException() description/fatal: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long/true
I/ACRA: ACRA is disabled for com.ichi2.anki - forwarding uncaught Exception on to default ExceptionHandler
I/Process: Sending signal. PID: 23259 SIG: 9
Disconnected from the target VM, address: 'localhost:2478', transport: 'socket'
```

For some reason, the did on my collection was null, so it crashes at `getLong()`. I'll push the fix

![2022_03_05-14_41_59](https://user-images.githubusercontent.com/69634269/156894533-6fc78651-15e4-445b-84ad-855867c69a6f.png)

**Comment by Arthur-Milchior** [comment]
Thanks for already submitting a fix. I'll comment it too.
Do you use only ankidroid, or also desktop? do you use add-ons? Because it would be useful to know where this come from and correct the source of the error too; ideally reporting it to the broken add-on or making a bug report to AnkiTekts. Unless there was a change in upstream datastructure (I hope we would have been warned, but I don't follow enough to know)

**Comment by Arthur-Milchior** [comment]
@dae I see that note type now have a configuration `target_deck_id_unused`. Is it possible that recent version of anki do not set property "did" in note type?

**Comment by BrayanDSO** [comment]
Yes, I use Anki desktop too. I guess the procedure I made was, although probably not reproducible:
1. Exporting a collection default deck with some cards using a new notetype
2. Import the deck in another collection
3. Move the notes to another deck
4. Delete the imported deck
5. Sync

**Comment by dae** [comment]
While older Anki versions set did to 1 on newly created notetypes, IIRC, there were collections floating around (probably created with third-party tools) that had a null or missing did, so it was declared as nullable in the Rust schema:
https://github.com/ankitects/anki/blob/202207b7650680ddc4cf1f6b68a4fe064760936b/rslib/src/notetype/schema11.rs#L43. A safe approach here would be to fall back on 1 if the property is null, missing, or set to an invalid deck.

Recent Anki versions no longer use that property, as we don't want to have to write out and sync the entire notetype (with potentially hundreds of templates) each time the user saves a card to a different deck. It is now stored in a config setting, and a future sync protocol change will allow syncing of individual settings instead of syncing all the config at once.

**Comment by mikehardy** [comment]
Oh interesting, I suppose we need to may attention to the nullability in the schema definitions (I mean, of course)

@BrayanDSO I'm not sure if there's a clean way to wrap the idea of Deck.getDid, but if there was, then that's the place to put this fallback, in one spot - and if not, hopefully it's possible to make one getDid spot that can do the fallback-to-1 ?

**Comment by BrayanDSO** [comment]
It seems the only nullable column on schema11 notetypes is deck id.

The most clean way would be to add a `getDid()` to `libanki/Model`, a one line method, and substitute the two only occurrences of `Model.getLong("did")` to `Model.getDid()`.

@Arthur-Milchior had suggested on the PR to add a `default did` parameter on it. I think overloading the method to fallback to 1 if no `defaultDid` was given is unnecessary, since the two uses of it would have to default to 1 too. So I prefer to always fallback to 1 if did is null.

If this is going to be the approach to go, please let me know

**Comment by mikehardy** [comment]
> The most clean way would be to add a getDid() to libanki/Model, a one line method, and substitute the two only occurrences of Model.getLong("did") to Model.getDid().

That sounds reasonable and pretty clean to me
