### ISSUE TITLE
[Bug] Test failing on running

### ISSUE THREAD

**Issue by puranjayK** [ankidroid/Anki-Android#10606]
`SLF4J: Class path contains multiple SLF4J bindings.`
```SLF4J: Found binding in [jar:file:/C:/Users/puran/.gradle/caches/transforms-3/b3596cfb48f6f73dcf3937a9123e08e4/transformed/jetified-slf4j-timber-3.1-runtime.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/puran/.gradle/caches/transforms-3/4d0f9e240a250558b371017206c22584/transformed/jetified-slf4j-timber-3.1/jars/classes.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [com.arcao.slf4j.timber.TimberLoggerFactory

C:\Users\puran\AppData\Local\Temp\rsdroid4127811485518597829.dll: Can't find dependent libraries
java.lang.UnsatisfiedLinkError: C:\Users\puran\AppData\Local\Temp\rsdroid4127811485518597829.dll: Can't find dependent libraries
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
	at java.base/java.lang.Runtime.load0(Runtime.java:746)
	at java.base/java.lang.Runtime.load(Runtime.java:733)
	at net.ankiweb.rsdroid.testing.RustBackendLoader.loadPath(RustBackendLoader.java:113)
	at net.ankiweb.rsdroid.testing.RustBackendLoader.load(RustBackendLoader.java:108)
	at net.ankiweb.rsdroid.testing.RustBackendLoader.init(RustBackendLoader.java:56)
	at com.ichi2.anki.RobolectricTest.setUp(RobolectricTest.kt:92)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
	Suppressed: org.robolectric.android.internal.AndroidTestEnvironment$UnExecutedRunnablesException: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(Looper.getMainLooper()).idle() call.


C:\Users\puran\AppData\Local\Temp\rsdroid4127811485518597829.dll: Can't find dependent libraries
java.lang.UnsatisfiedLinkError: C:\Users\puran\AppData\Local\Temp\rsdroid4127811485518597829.dll: Can't find dependent libraries
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
	at java.base/java.lang.Runtime.load0(Runtime.java:746)
	at java.base/java.lang.Runtime.load(Runtime.java:733)
	at net.ankiweb.rsdroid.testing.RustBackendLoader.loadPath(RustBackendLoader.java:113)
	at net.ankiweb.rsdroid.testing.RustBackendLoader.load(RustBackendLoader.java:108)
	at net.ankiweb.rsdroid.testing.RustBackendLoader.init(RustBackendLoader.java:56)
	at com.ichi2.anki.RobolectricTest.setUp(RobolectricTest.kt:92)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
	Suppressed: org.robolectric.android.internal.AndroidTestEnvironment$UnExecutedRunnablesException: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(Looper.getMainLooper()).idle() call.
```

### Reproduction Steps
Error Occurs on running AbstractFlashCardViewerCommandTest.kt in package com.ichi2.anki

**Comment by TheScriptan** [comment]
This is only a warning, but in my case, I have two bindings.
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/$USER/.gradle/caches/transforms-3/b3596cfb48f6f73dcf3937a9123e08e4/transformed/jetified-slf4j-timber-3.1-runtime.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/$USER/.gradle/caches/transforms-3/4d0f9e240a250558b371017206c22584/transformed/jetified-slf4j-timber-3.1/jars/classes.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [com.arcao.slf4j.timber.TimberLoggerFactory]
```

I expect `./gradlew clean` can help, but since it is only a warning, it is fine IMNSHO

**Comment by david-allison** [comment]
#8482 has potential solutions: there's a missing DLL on your computer

**Comment by mikehardy** [comment]
Yep, this is duplicate, going to resolve - the real error is:

> java.lang.UnsatisfiedLinkError: C:\Users\puran\AppData\Local\Temp\rsdroid4127811485518597829.dll: Can't find dependent libraries

and 8492 is tracking
