### ISSUE TITLE
[Bug] Emulator tests failing: TimeoutCancellationException

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#10601]
`kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 120000 ms`

```
com.google.testing.platform.api.plugin.PluginException: Exception thrown during onBeforeAll invocation of plugin com.google.testing.platform.plugin.android.AndroidDevicePlugin.
Test results saved as file:/Users/runner/work/Anki-Android/Anki-Android/AnkiDroid/build/outputs/androidTest-results/connected/flavors/play/TestingAVD(AVD)%20-%2011/test-result.pb. Inspect these results in Android Studio by selecting Run > Import Tests From File from the menu bar and importing test-result.pb.
	at com.google.testing.platform.plugin.PluginLifecycleKt.invokeOrThrow(PluginLifecycle.kt:216)
	at com.google.testing.platform.plugin.PluginLifecycleKt.invokeOrThrow$default(PluginLifecycle.kt:205)
	at com.google.testing.platform.plugin.PluginLifecycle$onBeforeAll$1.invoke(PluginLifecycle.kt:92)
	at com.google.testing.platform.plugin.PluginLifecycle$onBeforeAll$1.invoke(PluginLifecycle.kt:88)
	at com.google.testing.platform.core.telemetry.common.noop.NoopDiagnosticsScope.recordEvent(NoopDiagnosticsScope.kt:35)
	at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent(Telemetry.kt:105)
	at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent$default(Telemetry.kt:98)
	at com.google.testing.platform.plugin.PluginLifecycle.onBeforeAll(PluginLifecycle.kt:88)
	at com.google.testing.platform.executor.SingleDeviceExecutor$execute$4.invoke(SingleDeviceExecutor.kt:86)
	at com.google.testing.platform.executor.SingleDeviceExecutor$execute$4.invoke(SingleDeviceExecutor.kt:86)
	at com.google.testing.platform.executor.SingleDeviceExecutor.runUnlessCancelled(SingleDeviceExecutor.kt:105)
	at com.google.testing.platform.executor.SingleDeviceExecutor.execute(SingleDeviceExecutor.kt:86)
	at com.google.testing.platform.RunnerImpl.run(RunnerImpl.kt:108)
	at com.google.testing.platform.server.strategy.NonInteractiveServerStrategy$run$4.invoke(NonInteractiveServerStrategy.kt:80)
	at com.google.testing.platform.server.strategy.NonInteractiveServerStrategy$run$4.invoke(NonInteractiveServerStrategy.kt:79)
	at com.google.testing.platform.core.telemetry.common.noop.NoopDiagnosticsScope.recordEvent(NoopDiagnosticsScope.kt:35)
	at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent(Telemetry.kt:66)
	at com.google.testing.platform.server.strategy.NonInteractiveServerStrategy.run(NonInteractiveServerStrategy.kt:79)
	at com.google.testing.platform.main.MainKt$main$4.invokeSuspend(Main.kt:67)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.google.testing.platform.main.MainKt.main(Main.kt:66)
	at com.google.testing.platform.main.MainKt.main$default(Main.kt:34)
	at com.google.testing.platform.main.MainKt.main(Main.kt)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.google.testing.platform.launcher.Launcher.main(Launcher.java:149)
Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 120000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:158)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:128)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:68)
	at java.base/java.lang.Thread.run(Thread.java:829)

Mar 21, 2022 11:24:49 PM com.android.tools.utp.plugins.host.additionaltestoutput.AndroidAdditionalTestOutputPlugin deviceShellAndCheckSuccess
WARNING: Shell command failed (1): ls "/sdcard/Android/media/com.ichi2.anki/additional_test_output"
ls: /sdcard/Android/media/com.ichi2.anki/additional_test_output: No such file or directory

Mar 21, 2022 11:24:49 PM com.android.tools.utp.plugins.host.additionaltestoutput.AndroidAdditionalTestOutputPlugin afterAll
WARNING: Failed to retrieve additional test outputs from device.
com.android.ddmlib.SyncException: Remote object doesn't exist!
	at com.android.ddmlib.SyncService.pullFile(SyncService.java:341)
	at com.android.ddmlib.internal.DeviceImpl.pullFile(DeviceImpl.java:1083)
	at com.android.tools.utp.plugins.deviceprovider.ddmlib.DdmlibAndroidDevice.pullFile(DdmlibAndroidDevice.kt)
	at com.android.tools.utp.plugins.deviceprovider.ddmlib.DdmlibAndroidDeviceController.pull(DdmlibAndroidDeviceController.kt:254)
	at com.google.testing.platform.executor.DeviceControllerProxy$pull$2.invoke(DeviceControllerProxy.kt:82)
	at com.google.testing.platform.executor.DeviceControllerProxy$pull$2.invoke(DeviceControllerProxy.kt:82)
	at com.google.testing.platform.core.telemetry.common.noop.NoopDiagnosticsScope.recordEvent(NoopDiagnosticsScope.kt:35)
	at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent(Telemetry.kt:66)
	at com.google.testing.platform.executor.DeviceControllerProxy.pull(DeviceControllerProxy.kt:79)
	at com.android.tools.utp.plugins.host.additionaltestoutput.AndroidAdditionalTestOutputPlugin.copyAdditionalTestOutputsFromDeviceToHost(AndroidAdditionalTestOutputPlugin.kt:222)
	at com.android.tools.utp.plugins.host.additionaltestoutput.AndroidAdditionalTestOutputPlugin.afterAll(AndroidAdditionalTestOutputPlugin.kt:206)
	at com.google.testing.platform.plugin.PluginLifecycle$onAfterAll$1$2$1.invoke(PluginLifecycle.kt:180)
	at com.google.testing.platform.plugin.PluginLifecycle$onAfterAll$1$2$1.invoke(PluginLifecycle.kt:179)
	at com.google.testing.platform.plugin.PluginLifecycleKt$invokeOrThrow$1.invoke(PluginLifecycle.kt:213)
	at com.google.testing.platform.plugin.PluginLifecycleKt$invokeOrThrow$1.invoke(PluginLifecycle.kt:212)
	at com.google.testing.platform.core.telemetry.common.noop.NoopDiagnosticsScope.recordEvent(NoopDiagnosticsScope.kt:35)
	at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent(Telemetry.kt:105)
	at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent$default(Telemetry.kt:98)
	at com.google.testing.platform.plugin.PluginLifecycleKt.invokeOrThrow(PluginLifecycle.kt:212)
	at com.google.testing.platform.plugin.PluginLifecycleKt.invokeOrThrow$default(PluginLifecycle.kt:205)
	at com.google.testing.platform.plugin.PluginLifecycle$onAfterAll$1.invoke(PluginLifecycle.kt:179)
	at com.google.testing.platform.plugin.PluginLifecycle$onAfterAll$1.invoke(PluginLifecycle.kt:173)
	at com.google.testing.platform.core.telemetry.common.noop.NoopDiagnosticsScope.recordEvent(NoopDiagnosticsScope.kt:35)
	at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent(Telemetry.kt:105)
	at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent$default(Telemetry.kt:98)
	at com.google.testing.platform.plugin.PluginLifecycle.onAfterAll(PluginLifecycle.kt:173)
	at com.google.testing.platform.executor.SingleDeviceExecutor$execute$3.invoke(SingleDeviceExecutor.kt:83)
	at com.google.testing.platform.executor.SingleDeviceExecutor$execute$3.invoke(SingleDeviceExecutor.kt:82)
	at com.google.testing.platform.result.TestResultListenerManager.afterTestSuite(TestResultListenerManager.kt:[140](https://github.com/ankidroid/Anki-Android/runs/5636084762?check_suite_focus=true#step:14:140))
	at com.google.testing.platform.RunnerImpl.run(RunnerImpl.kt:118)
	at com.google.testing.platform.server.strategy.NonInteractiveServerStrategy$run$4.invoke(NonInteractiveServerStrategy.kt:80)
	at com.google.testing.platform.server.strategy.NonInteractiveServerStrategy$run$4.invoke(NonInteractiveServerStrategy.kt:79)
	at com.google.testing.platform.core.telemetry.common.noop.NoopDiagnosticsScope.recordEvent(NoopDiagnosticsScope.kt:35)
	at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent(Telemetry.kt:66)
	at com.google.testing.platform.server.strategy.NonInteractiveServerStrategy.run(NonInteractiveServerStrategy.kt:79)
	at com.google.testing.platform.main.MainKt$main$4.invokeSuspend(Main.kt:67)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.google.testing.platform.main.MainKt.main(Main.kt:66)
	at com.google.testing.platform.main.MainKt.main$default(Main.kt:34)
	at com.google.testing.platform.main.MainKt.main(Main.kt)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.google.testing.platform.launcher.Launcher.main(Launcher.java:[149](https://github.com/ankidroid/Anki-Android/runs/5636084762?check_suite_focus=true#step:14:149))


Platform error occurred when running the UTP test suite
```

StackOverflow implies that the device hasn't booted. It might be a worthwhile experiment (in a branch) to sleep for 5 minutes after `sys.boot_completed` to confirm if this diagnosis is correct.

https://stackoverflow.com/questions/71529420/android-instrumentation-test-fails-to-install-apk

**Comment by david-allison** [comment]
First failure on Jan 30

https://github.com/ankidroid/Anki-Android/runs/4997978850?check_suite_focus=true

macos-latest was upgraded on Jan 27 (not linking threads yet): `https://github.com/actions/virtual-environments/issues/4060#issuecomment-1023546603`

**Comment by mikehardy** [comment]
Yeah, there's a few things I want to try - thanks for logging this, it's been really bugging me.
One of the things I want to do is to try one of the emulator cache actions (or add it to my own emulator start up stuff, maybe making an action) that is able to do a two-stage emulator boot in a retry, one stage looks for a cached boot image, and if it doesn't find it, does a complete boot (maybe with the extra sleep you mention) then shuts it down saving the fast-boot image in a cache-able location. Second stage boots again this time from cached image, with a sleep to make sure it's up.

On future boots it should be fast. If the second stage fails it purges the cached image and tries again so it's able to clear any corrupt state. Cache key on emulator version and sdk version combo

Should work and for most non-flake startups it will be much faster

**Comment by williamdias** [comment]
Apparently, If I close the following pop-up on the emulator, timeout won't happen. 

![Screen Shot 2022-03-25 at 01 59 39](https://user-images.githubusercontent.com/686915/160059306-3a028344-ab61-464c-aba0-1ec8d37fecab.png)

**Comment by mikehardy** [comment]
@williamdias how did you determine this in the context of the Github CI environment? Are you certain you are using the same emulator image we use in CI? (it's a specific API level and flavor of the emulator) - how come it happens sometimes and not others? Which option did you choose to close it ?

In some of my e2e android setups [I capture video of the emulator](https://github.com/invertase/notifee/blob/696c9c0ff25935130ca84317a65b9996ccdbfae1/.github/workflows/tests_e2e_android.yml#L187-L190) and [upload it to the action files](https://github.com/invertase/notifee/blob/696c9c0ff25935130ca84317a65b9996ccdbfae1/.github/workflows/tests_e2e_android.yml#L231-L250) so it's possible to know more by [downloading the capture](https://github.com/invertase/notifee/actions/runs/2039938888) but I don't do that here

So I'm curious how *exactly* you know this is the issue

If we can determine this is definitely the issue then we can design either a specific x,y coordinate tap to dismiss it (pretty easy via [an adb command](https://github.com/invertase/react-native-firebase/blob/ef7895cd49eed3a4d103df624e52315250c68ab3/.github/workflows/tests_e2e_android.yml#L185) if we can nail the coordinates) or we could try something like TestButler although it does not seem to handle this

Also possible to send hardware back button prior to tests
Also possible to use uiautomater to try to match any known resource ids for system dialogs and click known resource string for bundle
Also possible (maybe? in older APIs) to send intent CLOSE_SYSTEM_DIALOGS)

**Comment by williamdias** [comment]
Hey @mikehardy! I was testing my android shared lib locally, trying to create a script to automate tests on a CI environment. I don't know which API level and flavor you are using, but the problem seems to be somewhat related.

Basically, my script does the following:

```shell
# Create AVD device
echo "no" | avdmanager create avd -n $DEVICE_NAME -k "system-images;android-25;google_apis_playstore;x86" --device "Nexus 5X" --force

# List AVD devices
avdmanager list avd

# Start emulator
emulator -avd $DEVICE_NAME &

# Wait for device to become online
adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'

# Run tests
./gradlew connectedAndroidTest
```

After the emulator is initialized, that pop-up will appear. If I do nothing and just wait for my tests to run, I get the same timeout error and the tests fail. On the other hand, if I click "Accept",  tests run smoothly. I am not sure how to close that pop-up programmatically though.

**Comment by mikehardy** [comment]
@williamdias you can consult the .github/workflow yml files to see the exact spec of everything, it's available for inspection
Similarly, I linked exactly how to close the pop up programmatically via an adb tap event as a possibility, or you can send an intent (possibly via adb also, stackoverflow can direct how to send an Intent to the system via adb, might use the monkey command I forget)

An interesting result, but not enough details to say for certain unless we do a screencap (as I showed how to do) and see the actual screen of the device I guess, since that is how you are diagnosing the issue. Odd that it happens sometimes, but not all the time though. Do you see flaky behavior, or is it every time? Because our Ci works sometimes.

**Comment by williamdias** [comment]
Thanks @mikehardy. On my local machine it's a constant behavior. My tests only work if I close the pop-up.
