### ISSUE TITLE
[Bug] Resources$NotFoundException: String resource ID #0x7f100328

### ISSUE THREAD

**Issue by Trungnguye** [ankidroid/Anki-Android#10644]
###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
AnkiDroid Version = 2.15.6  

Android Version = 12  

Manufacturer = Xiaomi  

Model = M2012K10C  

Hardware = mt6893  

Webview User Agent = Mozilla/5.0 (Linux; Android 12; M2012K10C Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.73 Mobile Safari/537.36  

ACRA UUID = f32d8676-43b9-4ac7-9e48-1656380c7f18  

Scheduler = std  

Crash Reports Enabled = true  

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
```
android.content.res.Resources$NotFoundException: String resource ID #0x7f100328
at android.content.res.Resources.getText(Resources.java:463)
at android.content.res.MiuiResources.getText(MiuiResources.java:106)
at android.content.res.Resources.getString(Resources.java:556)
at miuix.toolbar.internal.menu.MenuBuilder.add(MenuBuilder.java:453)
at com.ichi2.anki.NoteEditor$ActionModeCallback.onPrepareActionMode(NoteEditor.java:5)
at android.widget.Editor$TextActionModeCallback.onPrepareActionMode(Editor.java:4293)
at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onPrepareActionMode(DecorView.java:3041)
at miuix.toolbar.FloatingActionModeHelper$ActionModeCallback2Wrapper.onPrepareActionMode(FloatingActionModeHelper.java:44)
at miuix.toolbar.FloatingActionMode.invalidate(FloatingActionMode.java:208)
at com.android.internal.policy.DecorView.startActionMode(DecorView.java:1019)
at com.android.internal.policy.DecorView.startActionModeForChild(DecorView.java:950)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1043)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1043)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1043)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1043)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1043)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1043)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1043)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1043)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1043)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1043)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1043)
at android.view.View.startActionMode(View.java:7954)
at android.widget.Editor.startActionModeInternal(Editor.java:2479)
at android.widget.SelectionActionModeHelper.startActionMode(SelectionActionModeHelper.java:305)
at android.widget.SelectionActionModeHelper.startSelectionActionMode(SelectionActionModeHelper.java:281)
at android.widget.SelectionActionModeHelper.lambda$startSelectionActionModeWithSmartSelectAnimation$0$SelectionActionModeHelper(SelectionActionModeHelper.java:335)
at android.widget.SelectionActionModeHelper$$ExternalSyntheticLambda1.run(Unknown Source:4)
at android.widget.SelectionActionModeHelper.startSelectionActionModeWithSmartSelectAnimation(SelectionActionModeHelper.java:343)
at android.widget.SelectionActionModeHelper.$r8$lambda$mMDhXh3JQs_q5UuyTdq2CLenZJk(Unknown Source:0)
at android.widget.SelectionActionModeHelper$$ExternalSyntheticLambda5.accept(Unknown Source:4)
at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onPostExecute(SelectionActionModeHelper.java:1044)
at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onPostExecute(SelectionActionModeHelper.java:992)
at android.os.AsyncTask.finish(AsyncTask.java:771)
at android.os.AsyncTask.access$900(AsyncTask.java:199)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:210)
at android.os.Looper.loop(Looper.java:299)
at android.app.ActivityThread.main(ActivityThread.java:8256)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
```

**Comment by mikehardy** [comment]
Xioami bug. Can workaround?
https://github.com/K1rakishou/Kuroba-Experimental/issues/742
https://github.com/K1rakishou/Kuroba-Experimental/commit/bcaf2d5f55e7f3bf5f3ffc7e0148a2060c69e6c3

**Comment by david-allison** [comment]
@Trungnguye Would you be available to test this if we produced an alpha release with a possible fix?

We think we've solved it, but we don't have any testers with an appropriate device

**Comment by mikehardy** [comment]
Simply not seeing regression is good enough to merge, then yes hopefully @Trungnguye can test the next alpha, at least as a parallel build

**Comment by mikehardy** [comment]
The new alpha is out if you have a chance to test it @Trungnguye ? https://github.com/ankidroid/Anki-Android/releases/
