### ISSUE TITLE
[Bug] Crash: Can't create filtered deck

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#10661]
###### Reproduction Steps

1. Create Filtered Deck
2. Press OK
3. 

###### Expected Result

No Crash

###### Actual Result

Crash

###### Debug info
AnkiDroid Version = 2.16alpha53

Android Version = 11

Manufacturer = Google

Model = Pixel 3a

Hardware = sargo

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 3a Build/RQ3A.211001.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.88 Mobile Safari/537.36

ACRA UUID = 3e7c4ead-530d-4748-9f4f-622f9f619871

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

```
2022-03-30 18:49:03.850 21065-21065/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 21065
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.FilteredDeckOptions}: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter key
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter key
        at com.ichi2.anki.FilteredDeckOptions.onSharedPreferenceChanged(Unknown Source:11)
        at com.ichi2.anki.FilteredDeckOptions$DeckPreferenceHack$Editor.commit(FilteredDeckOptions.kt:173)
        at com.ichi2.anki.FilteredDeckOptions$DeckPreferenceHack$Editor.apply(FilteredDeckOptions.kt:211)
        at android.preference.Preference.tryCommit(Preference.java:1621)
        at android.preference.Preference.persistString(Preference.java:1657)
        at android.preference.ListPreference.setValue(ListPreference.java:157)
        at com.ichi2.anki.FilteredDeckOptions.buildLists(FilteredDeckOptions.kt:443)
        at com.ichi2.anki.FilteredDeckOptions.onCreate(FilteredDeckOptions.kt:307)
        at android.app.Activity.performCreate(Activity.java:7994)
        at android.app.Activity.performCreate(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7664) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

**Comment by BrayanDSO** [comment]
I can't reproduce. I have no problems on my daily usage of 2.1.6alpha53 on my personal collection (and I use filtered decks quite frequently)

**Comment by david-allison** [comment]
> I can't reproduce on 2.1.6alpha53 (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 30). I do not have any problems on my daily usage of 2.1.6alpha53 on my personal collection (and I use filtered decks quite frequently)
> 
> Is there a specificity of the filtered query or settings?

Not that I'd expect, I feel this crashes unconditionally, maybe we're on a different commit. I'm building from main.

I've got this fixed locally, along with a comment to add a test for this. 

We're passing a null into a callback with a non-null "key" parameter definition.

I'm off my PC, will get this resolved when I'm back

**Comment by BrayanDSO** [comment]
> I'm building from main.

Ohhh. In 0721bd5 (2.1.6alpha53 release) it works fine
