### ISSUE TITLE
'DeckPickerTest > version16CollectionOpens' is flaky on windows

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#10829]
'DeckPickerTest > version16CollectionOpens' is flaky on windows

Seen in another instance or two as well? Will re-run failed unit test once it's possible (other parts of OS matrix have to finish first)

```

com.ichi2.anki.DeckPickerTest > checkDisplayOfStudyOptionsOnTablet[0] SKIPPED
thread '<unnamed>' panicked at 'Anki already open, or media currently syncing.', src/lib.rs:251:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such table: decks\"))", kind: Other }', src/lib.rs:256:13
thread '<unnamed>' panicked at 'Anki already open, or media currently syncing.', src/lib.rs:251:25

com.ichi2.anki.DeckPickerTest > version16CollectionOpens[1] FAILED
    java.lang.AssertionError: Collection should now be open
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:26)
        at com.ichi2.anki.DeckPickerTest.version16CollectionOpens(DeckPickerTest.java:411)

```

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/10811#issuecomment-1098285999_

**Comment by mikehardy** [comment]
@gpauer I think you mentioned you saw this as well? It's not high priority but this is how I track flaky issues usually, as much detail as possible for immediate reference, try to get comment from others that may or may not have seen it, then frequently it will sit in a sort of "self-triage" where I will make comments as I see it happen again (...and again and again) and if it happens enough to justify the effort then I dig in

**Comment by mikehardy** [comment]
May re-title this to a more generic "some tests are flaky on windows" thing, it appears there is another one:

```
com.ichi2.anki.ReviewerTest > baseDeckName[SchedV2] FAILED
    java.lang.NullPointerException
        at com.ichi2.libanki.sched.SchedV2._resetLrnCount(SchedV2.java:1043)
        at com.ichi2.libanki.sched.SchedV2.resetCounts(SchedV2.java:249)
        at com.ichi2.libanki.sched.SchedV2.resetCounts(SchedV2.java:229)
        at com.ichi2.libanki.sched.SchedV2.counts(SchedV2.java:363)
        at com.ichi2.libanki.sched.SchedV2.counts(SchedV2.java:359)
        at com.ichi2.libanki.sched.SchedV2.counts(SchedV2.java:375)
        at com.ichi2.anki.Reviewer.updateScreenCounts(Reviewer.kt:972)
        at com.ichi2.anki.Reviewer.updateActionBar(Reviewer.kt:965)
        at com.ichi2.anki.AbstractFlashcardViewer.updateForNewCard(AbstractFlashcardViewer.kt:[123](https://github.com/ankidroid/Anki-Android/runs/6012729782?check_suite_focus=true#step:8:123)7)
        at com.ichi2.anki.Reviewer.updateForNewCard(Reviewer.kt:488)
        at com.ichi2.anki.AbstractFlashcardViewer.fillFlashcard(AbstractFlashcardViewer.kt:1516)
        at com.ichi2.anki.Reviewer.fillFlashcard(Reviewer.kt:997)
        at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.kt:1421)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.kt:1305)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.kt:[128](https://github.com/ankidroid/Anki-Android/runs/6012729782?check_suite_focus=true#step:8:128)4)
        at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.kt:1009)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onPostExecute(AbstractFlashcardViewer.kt:482)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onPostExecute(AbstractFlashcardViewer.kt:433)
        at com.ichi2.anki.servicelayer.TaskListenerBuilder.replaceWith$lambda-1(AsyncLayerAdapter.kt:68)
        at com.ichi2.anki.servicelayer.AsyncLayerAdapterKt$toListener$1.onPostExecute(AsyncLayerAdapter.kt:48)
        at com.ichi2.async.CollectionTask.onPostExecute(CollectionTask.java:228)
        at android.os.AsyncTask.finish(AsyncTask.java:755)
        at android.os.AsyncTask.access$900(AsyncTask.java:192)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at org.robolectric.shadows.ShadowPausedLooper$IdlingRunnable.run(ShadowPausedLooper.java:332)
        at org.robolectric.shadows.ShadowPausedLooper.executeOnLooper(ShadowPausedLooper.java:366)
        at org.robolectric.shadows.ShadowPausedLooper.idle(ShadowPausedLooper.java:92)
        at org.robolectric.shadows.ShadowPausedLooper.idleIfPaused(ShadowPausedLooper.java:163)
        at org.robolectric.android.controller.ActivityController.visible(ActivityController.java:177)
        at com.ichi2.anki.RobolectricTest$Companion.startActivityNormallyOpenCollectionWithIntent(RobolectricTest.kt:276)
        at com.ichi2.anki.RobolectricTest.startActivityNormallyOpenCollectionWithIntent(RobolectricTest.kt)
        at com.ichi2.anki.ReviewerTest.startReviewer(ReviewerTest.java:418)
        at com.ichi2.anki.ReviewerTest.startReviewer(ReviewerTest.java:410)
        at com.ichi2.anki.ReviewerTest.startReviewer(ReviewerTest.java:406)
        at com.ichi2.anki.ReviewerTest.baseDeckName(ReviewerTest.java:272)
```

**Comment by mikehardy** [comment]
Original one just showed up again:

> 'DeckPickerTest > version16CollectionOpens' is flaky on windows

**Comment by gpauer** [comment]
> @gpauer I think you mentioned you saw this as well? It's not high priority but this is how I track flaky issues usually, as much detail as possible for immediate reference, try to get comment from others that may or may not have seen it, then frequently it will sit in a sort of "self-triage" where I will make comments as I see it happen again (...and again and again) and if it happens enough to justify the effort then I dig in

Yes in this PR #10801 

The weird thing where it passed on powershell and failed on bash

**Comment by mikehardy** [comment]
> The weird thing where it passed on powershell and failed on bash

I think that's correlation not causation, in other words you were just lucky on your powershell runs and unlucky on bash. The shell involved shouldn't matter once it's running in the JDK. Of course, software never fails to surprise, but I would be surprised if the shell was the root cause

**Comment by gpauer** [comment]
Ahh okay makes sense. The reason I was so set on a possible shell issue was shell flaked on me the first 2 times I used it and powershell not once. Might let my fork run it tomorrow just to be safe and convince myself it's not the shell

**Comment by mikehardy** [comment]
Nothing beats experimental results / actual data!

**Comment by mikehardy** [comment]
I'm not seeing this currently, going to close it for now. I do still see *some* issues on windows but not sure that they are more or less prevalent on windows vs macOS+linux
