### ISSUE TITLE
AnkiDroid restarts when receiving broadcast intent android.intent.action.MEDIA_EJECT

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#1099]
Originally reported on Google Code with ID 196

```
From AnkiDroid triage, a frequent crash.

Begin Stacktrace
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.MEDIA_EJECT
dat=file:///sdcard } in com.ichi2.anki.AnkiDroid$10@4642cd18
at android.app.ActivityThread$PackageInfo$ReceiverDispatcher$Args.run(ActivityThread.java:771)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4595)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.ichi2.anki.Deck.commitToDB(Deck.java:405)
at com.ichi2.anki.Deck.closeDeck(Deck.java:348)
at com.ichi2.anki.AnkiDroid.closeExternalStorageFiles(AnkiDroid.java:1175)
at com.ichi2.anki.AnkiDroid.access$25(AnkiDroid.java:1172)
at com.ichi2.anki.AnkiDroid$10.onReceive(AnkiDroid.java:1152)
at android.app.ActivityThread$PackageInfo$ReceiverDispatcher$Args.run(ActivityThread.java:760)
... 9 more
End Stacktrace
Begin Inner exceptions
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.MEDIA_EJECT
dat=file:///sdcard } in com.ichi2.anki.AnkiDroid$10@4642cd18
at android.app.ActivityThread$PackageInfo$ReceiverDispatcher$Args.run(ActivityThread.java:771)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4595)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.ichi2.anki.Deck.commitToDB(Deck.java:405)
at com.ichi2.anki.Deck.closeDeck(Deck.java:348)
at com.ichi2.anki.AnkiDroid.closeExternalStorageFiles(AnkiDroid.java:1175)
at com.ichi2.anki.AnkiDroid.access$25(AnkiDroid.java:1172)
at com.ichi2.anki.AnkiDroid$10.onReceive(AnkiDroid.java:1152)
at android.app.ActivityThread$PackageInfo$ReceiverDispatcher$Args.run(ActivityThread.java:760)
... 9 more
java.lang.NullPointerException
at com.ichi2.anki.Deck.commitToDB(Deck.java:405)
at com.ichi2.anki.Deck.closeDeck(Deck.java:348)
at com.ichi2.anki.AnkiDroid.closeExternalStorageFiles(AnkiDroid.java:1175)
at com.ichi2.anki.AnkiDroid.access$25(AnkiDroid.java:1172)
at com.ichi2.anki.AnkiDroid$10.onReceive(AnkiDroid.java:1152)
at android.app.ActivityThread$PackageInfo$ReceiverDispatcher$Args.run(ActivityThread.java:760)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4595)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
at dalvik.system.NativeStart.main(Native Method)
End Inner exceptions--> END REPORT 1 <--
```

Reported by `inigo.aldana` on 2010-09-01 14:00:05

**Comment by mikehardy** [comment]
I am unable to reproduce this in API 26 or API 18 emulators with 
adb root
adb shell am broadcast -a android.intent.action.MEDIA_EJECT

@timrae may be closed?
