### ISSUE TITLE
Ankidroid has encountered a problem...

### ISSUE THREAD

**Issue by jimmy-j-r** [ankidroid/Anki-Android#11217]
Ankidroid won't let me add new note(card). Whenever I click 'New Note', it crashes with the message 'Ankidroid has encountered a problem...error report is being generated.' 
I've uninstalled and joined the beta version but to no avail.

**Comment by david-allison** [comment]
> Ankidroid won't let me add new note(card). Whenever I click 'New Note', it crashes with the message 'Ankidroid has encountered a problem...error report is being generated.' 
> I've uninstalled and joined the beta version but to no avail. 

Hi, could you send over your "debug information" from "settings - advanced - about ankidroid"

**Comment by jimmy-j-r** [comment]
AnkiDroid Version = 2.15.6

Android Version = 8.1.0

Manufacturer = motorola

Model = Moto G (5S) Plus

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 8.1.0; Moto G (5S) Plus Build/OPS28.65-36-14; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.73 Mobile Safari/537.36

ACRA UUID = e88a960e-09ee-4490-8594-cb6907455f2b

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by david-allison** [comment]
Thanks! Have you tried one of our alphas on the release page of our GitHub?

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.NoteEditor}: com.ichi2.utils.JSONException: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2861)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6626)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
Caused by: com.ichi2.utils.JSONException: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long
at com.ichi2.utils.JSONObject.getLong(JSONObject.java:2)
at com.ichi2.anki.NoteEditor.setDid(NoteEditor.java:10)
at com.ichi2.anki.NoteEditor.onCollectionLoaded(NoteEditor.java:51)
at com.ichi2.anki.AnkiActivity.startLoadingCollection(AnkiActivity.java:4)
at com.ichi2.anki.NoteEditor.onCreate(NoteEditor.java:19)
at android.app.Activity.performCreate(Activity.java:7032)
at android.app.Activity.performCreate(Activity.java:7023)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1236)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2814)
... 9 more
Caused by: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long
at org.json.JSON.typeMismatch(JSON.java:100)
at org.json.JSONObject.getLong(JSONObject.java:520)
at com.ichi2.utils.JSONObject.getLong(JSONObject.java:1)
... 17 more
```

**Comment by jimmy-j-r** [comment]
Nope I haven't. Although I did signup for Alpha via google groups.
