### ISSUE TITLE
[Bug] App crashes on launch on Android 5.0 & 5.1 without SD card.

### ISSUE THREAD

**Issue by n1snt** [ankidroid/Anki-Android#11235]
###### Reproduction Steps

1. Create AVD in Android Studio (API Level 21 & 22).
2. In Show Advanced Setting > SD Card > Select No SD card.
3. Run App on AVD.

###### Expected Result

The app launches successfully.

###### Actual Result

App crashes as soon as it launches.
![image](https://user-images.githubusercontent.com/46300244/166729800-eedaf6c0-59da-4c58-97af-3e602bd45ff8.png)

###### Debug info

Logcat:

`2022-05-04 21:30:30.353 3835-3835/com.ichi2.anki E/CollectionHelper: Could not initialize AnkiDroid directory
    com.ichi2.anki.exception.StorageAccessException: Failed to create AnkiDroid directory /storage/sdcard/AnkiDroid
        at com.ichi2.anki.CollectionHelper.initializeAnkiDroidDirectory(CollectionHelper.java:254)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:150)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:128)
        at com.ichi2.anki.CollectionHelper.getColSafe(CollectionHelper.java:205)
        at com.ichi2.anki.DeckPicker.onPrepareOptionsMenu(DeckPicker.kt:500)
        at android.app.Activity.onPreparePanel(Activity.java:2841)
        at androidx.fragment.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:461)
        at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:446)
        at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3149)
        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:459)
        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

If the app is launched with an SD card it does not crash.
And this error only occurs on Android 5.0 & 5.1. Android 6.0 & does not crash even without an SD card.

###### Research
*Enter an [x] character to confirm the points below:*

- [ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x ] I have searched for similar existing issues here and on the user forum
- [  ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
If this does not occur on real devices, I'm not sure what we can do here unfortunately. I recommend you add an sdcard to the AVDs until/unless proven that this is a real-world issue

**Comment by mikehardy** [comment]
I haven't seen follow up on this and I think it's a developer only thing with a workaround as mentioned. Closing
