### ISSUE TITLE
[Bug]briefly prompted the pop-up "Setting has stopped".

### ISSUE THREAD

**Issue by jyjsunny** [ankidroid/Anki-Android#11283]
###### Reproduction Steps
I don't know what triggered this bug, which briefly prompted the pop-up "Setting has stopped".

###### Actual Result

https://user-images.githubusercontent.com/92309998/167421647-7eca02a3-f5b4-4655-baa2-83e258fcdc8e.mov

**Comment by jyjsunny** [comment]
> I'm not sure either - Settings is not an app under our control. It's entirely possible that the app (Settings, your system preferences built-in app) crashed independent of AnkiDroid, and you just happened to be using AnkiDroid at the time 🤔

I probably understand what you mean, but I'm not sure what caused the "settings" crash, and I'm still trying to find a way to reproduce the crash. Thank you for your reply.

**Comment by jyjsunny** [comment]
Hello, here is the stack trace I got, I can confirm that it crashes on the setting side, but I want to know what causes it to crash?

: java.lang.RuntimeException: Unable to resume activity {com.android.settings/com.android.settings.applications.InstalledAppDetails}: java.lang.IllegalArgumentException
: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3645)
: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3685)
: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1643)
: 	at android.os.Handler.dispatchMessage(Handler.java:105)
: 	at android.os.Looper.loop(Looper.java:164)
: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
: 	at java.lang.reflect.Method.invoke(Native Method)
: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
: Caused by: java.lang.IllegalArgumentException
: 	at android.os.Parcel.readException(Parcel.java:1947)
: 	at android.os.Parcel.readException(Parcel.java:1889)
: 	at android.app.IActivityManager$Stub$Proxy.isTopOfTask(IActivityManager.java:8384)
: 	at android.app.Activity.isTopOfTask(Activity.java:6264)
: 	at android.app.Activity.onResume(Activity.java:1313)
: 	at com.android.settingslib.drawer.SettingsDrawerActivity.onResume(SettingsDrawerActivity.java:98)
: 	at com.android.settings.SettingsActivity.onResume(SettingsActivity.java:546)
: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1354)
: 	at android.app.Activity.performResume(Activity.java:7079)
: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3620)
: 	... 8 more
