### ISSUE TITLE
[Bug] Crash if Suspend or Bury is on the app bar

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#11586]
###### Reproduction Steps

1. Have `Suspend` or `Bury` as `Always show`
2. Start reviewing cards

###### Expected Result

Review cards as always

###### Actual Result

App crashes

###### Debug info
2.16alpha67 released on GitHub
```
AnkiDroid Version = 2.16alpha67

Android Version = 12

Manufacturer = samsung

Model = SM-N770F

Hardware = exynos9810

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-N770F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/102.0.5005.78 Mobile Safari/537.36

ACRA UUID = a46567c5-3379-4ff0-a3a9-2d376ea138cf

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Haven't tested with another app bar options. 

Here's the stacktrace I've got:
```
2022-06-10 18:47:54.722 8139-8139/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 8139
    java.lang.UnsupportedOperationException: This should no longer be called. onCreateActionView(MenuItem) should be used
        at com.ichi2.anki.ActionProviderCompat.onCreateActionView(ActionProviderCompat.kt:35)
        at androidx.core.view.ActionProvider.onCreateActionView(ActionProvider.java:170)
        at androidx.appcompat.view.menu.MenuItemImpl.getActionView(MenuItemImpl.java:773)
        at androidx.appcompat.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:191)
        at androidx.appcompat.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:469)
        at androidx.appcompat.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1176)
        at androidx.appcompat.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:96)
        at androidx.appcompat.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:226)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:292)
        at androidx.appcompat.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1063)
        at androidx.appcompat.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:1090)
        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:464)
        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by BrayanDSO** [comment]
b0a2bdcdc7f2d834ea936e7660075105fac1038b seems to be the cause
