### ISSUE TITLE
[Bug] The long press menu of decks is broken - Custom study

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#11801]
###### Reproduction Steps

1. Long Press on a deck
2. Press Custom study
3. Press anything from the menu

###### Expected Result
Choosen action is performed.

###### Actual Result
Ankidroid crash.

###### Debug info
AnkiDroid Version = 2.16alpha72

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.70 Mobile Safari/537.36

ACRA UUID = 49704c83-4498-4347-84c4-2988936a699f

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
From my logcat
```
    java.util.NoSuchElementException: Array contains no element matching the predicate.
        at com.ichi2.anki.dialogs.customstudy.CustomStudyDialog$ContextMenuOption$Companion.fromInt(CustomStudyDialog.kt:546)
        at com.ichi2.anki.dialogs.customstudy.CustomStudyDialog$buildContextMenu$2.invoke(CustomStudyDialog.kt:147)
        at com.ichi2.anki.dialogs.customstudy.CustomStudyDialog$buildContextMenu$2.invoke(CustomStudyDialog.kt:109)
        at com.afollestad.materialdialogs.internal.list.PlainListDialogAdapter.itemClicked(PlainListDialogAdapter.kt:76)
        at com.afollestad.materialdialogs.internal.list.PlainListViewHolder.onClick(PlainListDialogAdapter.kt:46)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22429)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
