### ISSUE TITLE
[Bug] Full sync from ankiweb fail

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#11891]
###### Reproduction Steps

1. Do some change requiring a full sync.
2. sync
3. when warned about conflict, select ankiweb
4. accept

###### Expected Result

Full sync

###### Actual Result

Collection can't be opened

###### Debug info

Running PlayDebug from 27ffca5a553d1c79fb94407cd912c7a032d04909

2022-07-19 20:01:25.597 2378-9532/com.ichi2.anki W/Connection: java.lang.NullPointerException
        at com.ichi2.libanki.sync.FullSyncer.download(FullSyncer.kt:110)
        at com.ichi2.async.Connection.doInBackgroundSync(Connection.kt:322)
        at com.ichi2.async.Connection.doOneInBackground(Connection.kt:131)
        at com.ichi2.async.Connection.doInBackground(Connection.kt:125)
        at com.ichi2.async.Connection.doInBackground(Connection.kt:55)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2022-07-19 20:01:25.739 2378-2378/com.ichi2.anki W/DatabaseErrorDialog: java.io.IOException: Cannot run program "sqlite3": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
        at java.lang.Runtime.exec(Runtime.java:699)
        at java.lang.Runtime.exec(Runtime.java:529)
        at java.lang.Runtime.exec(Runtime.java:426)
        at com.ichi2.anki.dialogs.DatabaseErrorDialog.onCreateDialog(DatabaseErrorDialog.kt:61)
        at com.ichi2.anki.dialogs.DatabaseErrorDialog.onCreateDialog(DatabaseErrorDialog.kt:45)
        at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:665)
        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:579)
        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1752)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1808)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751)
        at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:614)
        at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:534)
        at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:519)
        at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:515)
        at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.java:559)
        at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.java:545)
        at com.ichi2.anki.DeckPicker.showDatabaseErrorDialog(DeckPicker.kt:1233)
        at com.ichi2.anki.DeckPicker.handleDbError(DeckPicker.kt:1446)
        at com.ichi2.anki.DeckPicker$mSyncListener$1.onPostExecute(DeckPicker.kt:1722)
        at com.ichi2.async.Connection.onPostExecute(Connection.kt:108)
        at com.ichi2.async.Connection.onPostExecute(Connection.kt:55)
        at android.os.AsyncTask.finish(AsyncTask.java:771)
        at android.os.AsyncTask.access$900(AsyncTask.java:199)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:141)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at java.lang.Runtime.exec(Runtime.java:699) 
        at java.lang.Runtime.exec(Runtime.java:529) 
        at java.lang.Runtime.exec(Runtime.java:426) 
        at com.ichi2.anki.dialogs.DatabaseErrorDialog.onCreateDialog(DatabaseErrorDialog.kt:61) 
        at com.ichi2.anki.dialogs.DatabaseErrorDialog.onCreateDialog(DatabaseErrorDialog.kt:45) 
        at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:665) 
        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:579) 
        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1752) 
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1808) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751) 
        at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:614) 
        at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:534) 
        at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:519) 
        at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:515) 
        at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.java:559) 
        at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.java:545) 
        at com.ichi2.anki.DeckPicker.showDatabaseErrorDialog(DeckPicker.kt:1233) 
        at com.ichi2.anki.DeckPicker.handleDbError(DeckPicker.kt:1446) 
        at com.ichi2.anki.DeckPicker$mSyncListener$1.onPostExecute(DeckPicker.kt:1722) 
        at com.ichi2.async.Connection.onPostExecute(Connection.kt:108) 
        at com.ichi2.async.Connection.onPostExecute(Connection.kt:55) 
        at android.os.AsyncTask.finish(AsyncTask.java:771) 
        at android.os.AsyncTask.access$900(AsyncTask.java:199) 
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 

Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
This may be fixed by https://github.com/ankidroid/Anki-Android/pull/11740/commits/1596e75304935fb96f3ac991db079c78b7837ca9 on https://github.com/ankidroid/Anki-Android/pull/11740 - working on that as my next task (to get it merged)

**Comment by Arthur-Milchior** [comment]
I tested on another device, that has not had updates for at least weeks if not months, and got the same issue after download (I was not connected, so can’t check if it’s the same stack trace)

**Comment by mikehardy** [comment]
@Feripe-a may I ask what version was the last version that worked for you?

**Comment by Feripe-a** [comment]
AnkiDroid Version = 2.16alpha73

Android Version = 11

Manufacturer = Xiaomi

Model = 2201117TL

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; 2201117TL Build/RKQ1.211001.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36

ACRA UUID = b444231e-17cf-4bf2-b7d3-baa13502a9d6

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by Arthur-Milchior** [comment]
Hi @Feripe-a 
Sorry we forgot to answer you. @divyansh-dxn, hopefully, fixed the issue on the 22-th of july. Did you try to update since then and was the error corrected?

**Comment by divyansh-dxn** [comment]
Waiting for a reply by @Feripe-a, once confirmed issue may be closed.
