### ISSUE TITLE
[Bug] AnkiDroid fails on crash

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#11893]
I guess I get the directory reading permission issue again. No idea what it means, but here is the stack trace

```
2022-07-19 23:59:21.042 22154-22154/com.ichi2.anki E/CollectionHelper: Could not initialize AnkiDroid directory
    com.ichi2.anki.exception.StorageAccessException: No write access to AnkiDroid directory /storage/emulated/0/AnkiDroid
        at com.ichi2.anki.CollectionHelper.initializeAnkiDroidDirectory(CollectionHelper.java:309)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:183)
        at com.ichi2.anki.CollectionHelper.getColSafe(CollectionHelper.java:239)
        at com.ichi2.anki.DeckPicker.onPrepareOptionsMenu(DeckPicker.kt:575)
        at android.app.Activity.onPreparePanel(Activity.java:4281)
        at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3148)
        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:459)
        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by mikehardy** [comment]
What have you tried? (I would try system settings / preferences / ankidroid / check the storage access; I would try uninstall reinstall)

**Comment by Arthur-Milchior** [comment]
I tried reinstalling older alphas. It did fail with same exception. 

I followed your advice, and once setting is set back, I got back to bug https://github.com/ankidroid/Anki-Android/issues/11891

**Comment by mikehardy** [comment]
I wonder if #11740 will work for you

**Comment by Arthur-Milchior** [comment]
I don't really want to close it because there is a risk it occurs again, especially once released
