### ISSUE TITLE
[Bug] crashes with new backend - v3 scheduler - during review

### ISSUE THREAD

**Issue by escape0707** [ankidroid/Anki-Android#12179]
###### Reproduction Steps

I sometimes get crashes during reviewing. After flagging / unflagging and then answering the card, the app crashes. I don't know how to stably reproduce, though.

###### Expected Result

No crash when reviewing and flagging / unflagging.

###### Actual Result

Crashes.

###### Debug info

AnkiDroid Version = 2.16alpha81

Android Version = 13

Manufacturer = Google

Model = Pixel 6a

Hardware = bluejay

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 6a Build/TP1A.220624.021.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36

ACRA UUID = 9c32ddea-ccc7-42cb-9016-62a03202d3d3

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

As requested in https://github.com/ankidroid/Anki-Android/issues/12155#issuecomment-1227817016

**Comment by mikehardy** [comment]
Thanks! 

https://ankidroid.org/acra/app/1/installation/9c32ddea-ccc7-42cb-9016-62a03202d3d3/report
https://ankidroid.org/acra/app/1/bug/11739/report/23c8c8e9-25e0-4583-a447-ff56395aef41

Also, none of this is PII, that is specifically *not* our game, it's just the sequence of steps then the code stack. Hopefully this helps

@dae :thinking: ?


```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: net.ankiweb.rsdroid.exceptions.BackendInvalidInputException: Invalid input: ⁨card was modified: Normal(
    New(
        NewState {
            position: 15918,
        },
    ),
) Normal(
    Learning(
        LearnState {
            remaining_steps: 2,
            scheduled_secs: 60,
        },
    ),
)⁩
	at net.ankiweb.rsdroid.exceptions.BackendInvalidInputException$Companion.fromInvalidInputError(BackendInvalidInputException.kt:4)
	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:12)
	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:6)
	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Unknown Source:0)
	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:2)
	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:1)
	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:3)
	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:2)
	at anki.backend.GeneratedBackend.answerCardRaw(Unknown Source:7)
	at anki.backend.GeneratedBackend.answerCard(GeneratedBackend.kt:1)
	at com.ichi2.libanki.sched.SchedV3.answerCard(SchedV3.kt:3)
	at com.ichi2.anki.servicelayer.SchedulerService$AnswerAndGetCard.execute(SchedulerService.kt:3)
	at com.ichi2.anki.servicelayer.SchedulerService$AnswerAndGetCard.execute(SchedulerService.kt:1)
	at com.ichi2.anki.servicelayer.AnkiTask.execute(AsyncLayer.kt:2)
	at com.ichi2.anki.servicelayer.AsyncLayerAdapterKt$asDelegate$1.task(AsyncLayerAdapter.kt:2)
	at com.ichi2.async.TaskDelegate.execTask(Unknown Source:10)
	at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.kt:14)
	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.kt:2)
	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.kt:1)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 4 more
```


```
--------- beginning of main
08-26 06:55:02.933 W/AnkiDroid(12098): Backend$checkMainThreadOp/ select avg(case when type = 0 then case when ease > 1 then 1.0 else 0.0 end else null end) as newRate, avg(case when type = 0 then time else null end) as newTime, avg(case when type in (1, 3) then case when ease > 1 then 1.0 else 0.0 end else null end) as revRate, avg(case when type in (1, 3) then time else null end) as revTime, avg(case when type = 2 then case when ease > 1 then 1.0 else 0.0 end else null end) as relrnRate, avg(case when type = 2 then time else null end) as relrnTime from revlog where id > ?
08-26 06:55:02.933 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.widgets.DeckAdapter.getEta(DeckAdapter.kt:2)
08-26 06:55:02.934 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.widgets.DeckAdapter.getEta(DeckAdapter.kt:2)
08-26 06:55:02.934 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: kotlin.io.CloseableKt.closeFinally(Closeable.kt:1)
08-26 06:55:02.936 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.DeckPicker.renderPage(DeckPicker.kt:24)
08-26 06:55:02.936 W/AnkiDroid(12098): Backend$checkMainThreadOp/ SELECT count() FROM cards
08-26 06:55:02.936 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.DeckPicker.renderPage(DeckPicker.kt:24)
08-26 06:55:02.936 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.DeckPicker.renderPage(DeckPicker.kt:24)
08-26 06:55:02.937 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.DeckPicker.renderPage(DeckPicker.kt:35)
08-26 06:55:02.937 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.DeckPicker.renderPage(DeckPicker.kt:35)
08-26 06:55:02.942 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.cardviewer.SoundPlayer$CardSoundConfig$Companion.create(SoundPlayer.kt:1)
08-26 06:55:02.943 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.cardviewer.SoundPlayer$CardSoundConfig$Companion.create(SoundPlayer.kt:1)
08-26 06:55:02.943 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.reviewer.AnswerTimer.setupForCard(AnswerTimer.kt:2)
08-26 06:55:02.944 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.reviewer.AnswerTimer.setupForCard(AnswerTimer.kt:2)
08-26 06:55:02.944 I/AnkiDroid(12098): ViewGroupUtils::setRenderWorkaround - using default / hardware rendering
08-26 06:55:02.945 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.AbstractFlashcardViewer.updateDeckName(AbstractFlashcardViewer.kt:3)
08-26 06:55:02.946 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.AbstractFlashcardViewer.updateDeckName(AbstractFlashcardViewer.kt:3)
08-26 06:55:02.947 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.updateScreenCounts(Reviewer.kt:4)
08-26 06:55:02.947 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.updateScreenCounts(Reviewer.kt:13)
08-26 06:55:02.948 I/AnkiDroid(12098): AbstractFlashcardViewer:: Question successfully shown for card id 1661133909049
08-26 06:55:02.953 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.kt:26)
08-26 06:55:02.953 I/AnkiDroid(12098): undo: UndoStatus(undo=Update Note, redo=Answer Card, lastStep=25), false
08-26 06:55:02.954 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.kt:33)
08-26 06:55:02.954 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.AbstractFlashcardViewer.getParentDid(Unknown Source:8)
08-26 06:55:02.955 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.kt:65)
08-26 06:55:02.956 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.suspendNoteAvailable(Reviewer.kt:4)
08-26 06:55:02.956 W/AnkiDroid(12098): Backend$checkMainThreadOp/ select 1 from cards where nid = ? and id != ? and queue != -1 limit 1
08-26 06:55:02.956 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.suspendNoteAvailable(Reviewer.kt:4)
08-26 06:55:02.957 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.suspendNoteAvailable(Reviewer.kt:4)
08-26 06:55:02.957 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.buryNoteAvailable(Reviewer.kt:4)
08-26 06:55:02.957 W/AnkiDroid(12098): Backend$checkMainThreadOp/ select 1 from cards where nid = ? and id != ? and queue >=  0 limit 1
08-26 06:55:02.957 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.buryNoteAvailable(Reviewer.kt:4)
08-26 06:55:02.958 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.buryNoteAvailable(Reviewer.kt:4)
08-26 06:55:06.107 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.kt:26)
08-26 06:55:06.107 I/AnkiDroid(12098): undo: UndoStatus(undo=Update Note, redo=Answer Card, lastStep=25), false
08-26 06:55:06.108 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.kt:33)
08-26 06:55:06.109 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.AbstractFlashcardViewer.getParentDid(Unknown Source:8)
08-26 06:55:06.109 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.kt:65)
08-26 06:55:06.110 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.suspendNoteAvailable(Reviewer.kt:4)
08-26 06:55:06.110 W/AnkiDroid(12098): Backend$checkMainThreadOp/ select 1 from cards where nid = ? and id != ? and queue != -1 limit 1
08-26 06:55:06.110 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.suspendNoteAvailable(Reviewer.kt:4)
08-26 06:55:06.111 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.suspendNoteAvailable(Reviewer.kt:4)
08-26 06:55:06.112 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.buryNoteAvailable(Reviewer.kt:4)
08-26 06:55:06.112 W/AnkiDroid(12098): Backend$checkMainThreadOp/ select 1 from cards where nid = ? and id != ? and queue >=  0 limit 1
08-26 06:55:06.112 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.buryNoteAvailable(Reviewer.kt:4)
08-26 06:55:06.112 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.buryNoteAvailable(Reviewer.kt:4)
08-26 06:55:06.699 I/AnkiDroid(12098): Reviewer:: No flag
08-26 06:55:06.700 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onFlag(Reviewer.kt:2)
08-26 06:55:06.700 W/AnkiDroid(12098): Backend$checkMainThreadOp/ insert or replace into cards values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
08-26 06:55:06.701 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onFlag(Reviewer.kt:2)
08-26 06:55:06.705 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onFlag(Reviewer.kt:2)
08-26 06:55:06.711 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.kt:26)
08-26 06:55:06.711 I/AnkiDroid(12098): undo: UndoStatus(undo=null, redo=null, lastStep=25), false
08-26 06:55:06.712 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.kt:33)
08-26 06:55:06.713 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.AbstractFlashcardViewer.getParentDid(Unknown Source:8)
08-26 06:55:06.713 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.kt:65)
08-26 06:55:06.715 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.suspendNoteAvailable(Reviewer.kt:4)
08-26 06:55:06.715 W/AnkiDroid(12098): Backend$checkMainThreadOp/ select 1 from cards where nid = ? and id != ? and queue != -1 limit 1
08-26 06:55:06.715 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.suspendNoteAvailable(Reviewer.kt:4)
08-26 06:55:06.716 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.suspendNoteAvailable(Reviewer.kt:4)
08-26 06:55:06.716 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.buryNoteAvailable(Reviewer.kt:4)
08-26 06:55:06.717 W/AnkiDroid(12098): Backend$checkMainThreadOp/ select 1 from cards where nid = ? and id != ? and queue >=  0 limit 1
08-26 06:55:06.717 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.buryNoteAvailable(Reviewer.kt:4)
08-26 06:55:06.717 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.buryNoteAvailable(Reviewer.kt:4)
08-26 06:55:06.813 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.kt:26)
08-26 06:55:06.813 I/AnkiDroid(12098): undo: UndoStatus(undo=null, redo=null, lastStep=25), false
08-26 06:55:06.816 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.kt:33)
08-26 06:55:06.819 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.AbstractFlashcardViewer.getParentDid(Unknown Source:8)
08-26 06:55:06.820 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.kt:65)
08-26 06:55:06.823 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.suspendNoteAvailable(Reviewer.kt:4)
08-26 06:55:06.823 W/AnkiDroid(12098): Backend$checkMainThreadOp/ select 1 from cards where nid = ? and id != ? and queue != -1 limit 1
08-26 06:55:06.824 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.suspendNoteAvailable(Reviewer.kt:4)
08-26 06:55:06.824 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.suspendNoteAvailable(Reviewer.kt:4)
08-26 06:55:06.826 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.buryNoteAvailable(Reviewer.kt:4)
08-26 06:55:06.826 W/AnkiDroid(12098): Backend$checkMainThreadOp/ select 1 from cards where nid = ? and id != ? and queue >=  0 limit 1
08-26 06:55:06.826 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.buryNoteAvailable(Reviewer.kt:4)
08-26 06:55:06.826 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.buryNoteAvailable(Reviewer.kt:4)
08-26 06:55:08.698 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.displayAnswerBottomBar$nextIvlStr(Unknown Source:12)
08-26 06:55:08.699 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.displayAnswerBottomBar$nextIvlStr(Unknown Source:12)
08-26 06:55:08.700 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.displayAnswerBottomBar$nextIvlStr(Unknown Source:12)
08-26 06:55:08.700 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.displayAnswerBottomBar$nextIvlStr(Unknown Source:12)
08-26 06:55:08.701 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.displayAnswerBottomBar$nextIvlStr(Unknown Source:12)
08-26 06:55:08.701 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.displayAnswerBottomBar$nextIvlStr(Unknown Source:12)
08-26 06:55:08.701 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.displayAnswerBottomBar$nextIvlStr(Unknown Source:12)
08-26 06:55:08.702 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.displayAnswerBottomBar$nextIvlStr(Unknown Source:12)
08-26 06:55:09.437 I/AnkiDroid(12098): stop: automatically show question
08-26 06:55:09.437 I/AnkiDroid(12098): AbstractFlashcardViewer:: EASE_1 pressed
08-26 06:55:09.439 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.dealWithTimeBox(AbstractFlashcardViewer.kt:2)
08-26 06:55:09.441 I/AnkiDroid(12098): Answering card 1661133909049
08-26 06:55:09.445 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.kt:26)
08-26 06:55:09.445 I/AnkiDroid(12098): undo: UndoStatus(undo=null, redo=null, lastStep=26), false
08-26 06:55:09.446 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.kt:33)
08-26 06:55:09.447 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.AbstractFlashcardViewer.getParentDid(Unknown Source:8)
08-26 06:55:09.447 W/AnkiDroid(12098): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.kt:65)
```
