### ISSUE TITLE
[Bug] no feedback when search an invalid parameter

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#12223]
###### Reproduction Steps
1. search an invalid parameter e.g. "is:bury" or "flag:8" in Card browser

###### Expected Result
A toast/snackbar appears

###### Actual Result
A crash report appears

###### Debug info
AnkiDroid Version = 2.16alpha82

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36

ACRA UUID = 5df52f79-f5cd-436f-8b15-11830f324973

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
I see a couple issues from your installation of `2.16alpha82`

1. https://ankidroid.org/acra/app/1/bug/11975/report/7e81c5a7-a99e-4af4-bbc4-e95835464db2
-   UI path of card browser, note editor, save (to card browser), note editor, undo?, to card browser, back button, to reviewer (not exactly sure how to reviewer?), crash

```
08-29 11:45:03.406 I/AnkiDroid(28308): NoteEditor:: Save note button pressed
08-29 11:45:03.413 I/AnkiDroid(28308): finishWithAnimation END
08-29 11:45:03.417 I/AnkiDroid(28308): AnkiActivity::onPause - NoteEditor
08-29 11:45:03.435 I/AnkiDroid(28308): AnkiActivity::onStart - CardBrowser
08-29 11:45:03.439 I/AnkiDroid(28308): CardBrowser:: CardBrowser: Saving card...
08-29 11:45:03.446 I/AnkiDroid(28308): AnkiActivity::onResume - CardBrowser
08-29 11:45:03.465 W/AnkiDroid(28308): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.CardBrowser.onCreateOptionsMenu(CardBrowser.kt:9)
08-29 11:45:03.471 W/AnkiDroid(28308): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.CardBrowser.onCreateOptionsMenu(CardBrowser.kt:9)
08-29 11:45:03.472 W/AnkiDroid(28308): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.CardBrowser.onCreateOptionsMenu(CardBrowser.kt:24)
08-29 11:45:03.473 I/AnkiDroid(28308): undo: UndoStatus(undo=null, redo=null, lastStep=2), false
08-29 11:45:03.474 W/AnkiDroid(28308): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.CardBrowser.onCreateOptionsMenu(CardBrowser.kt:25)
08-29 11:45:03.594 I/AnkiDroid(28308): CardBrowser:: Completed doInBackgroundSearchCards Successfully
08-29 11:45:03.604 W/AnkiDroid(28308): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.CardBrowser$CardCache.getColumnHeaderText(CardBrowser.kt:22)
08-29 11:45:03.607 W/AnkiDroid(28308): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.CardBrowser$CardCache.getColumnHeaderText(CardBrowser.kt:22)
08-29 11:45:03.611 W/AnkiDroid(28308): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.CardBrowser$CardCache.getColumnHeaderText(CardBrowser.kt:22)
08-29 11:45:03.613 W/AnkiDroid(28308): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.CardBrowser$CardCache.getColumnHeaderText(CardBrowser.kt:22)
08-29 11:45:03.616 W/AnkiDroid(28308): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.CardBrowser$CardCache.getColumnHeaderText(CardBrowser.kt:22)
08-29 11:45:03.747 I/AnkiDroid(28308): AnkiActivity::onStop - NoteEditor
08-29 11:45:03.753 I/AnkiDroid(28308): AnkiActivity::onDestroy - NoteEditor
08-29 11:45:08.382 I/AnkiDroid(28308): Back key pressed
08-29 11:45:08.382 I/AnkiDroid(28308): finishWithAnimation END
08-29 11:45:08.387 I/AnkiDroid(28308): AnkiActivity::onPause - CardBrowser
08-29 11:45:08.405 I/AnkiDroid(28308): AnkiActivity::onStart - Reviewer
08-29 11:45:08.417 I/AnkiDroid(28308): AnkiActivity::onResume - Reviewer
08-29 11:45:08.419 W/AnkiDroid(28308): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.setTitle(Reviewer.kt:2)
08-29 11:45:08.420 W/AnkiDroid(28308): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.setTitle(Reviewer.kt:2)
08-29 11:45:08.422 W/AnkiDroid(28308): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.AbstractFlashcardViewer.updateDeckName(AbstractFlashcardViewer.kt:3)
08-29 11:45:08.422 W/AnkiDroid(28308): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.AbstractFlashcardViewer.updateDeckName(AbstractFlashcardViewer.kt:3)
08-29 11:45:08.424 W/AnkiDroid(28308): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.updateScreenCounts(Reviewer.kt:4)
```

```
java.lang.RuntimeException: Unable to resume activity {com.ichi2.anki.a/com.ichi2.anki.Reviewer}: net.ankiweb.rsdroid.BackendException: Backend has been closed
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5230)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5269)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: net.ankiweb.rsdroid.BackendException: Backend has been closed
	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:4)
	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:2)
	at anki.backend.GeneratedBackend.getQueuedCardsRaw(Unknown Source:6)
	at anki.backend.GeneratedBackend.getQueuedCards(GeneratedBackend.kt:5)
	at com.ichi2.libanki.sched.SchedV3.getQueuedCards(Unknown Source:10)
	at com.ichi2.libanki.sched.SchedV3.counts(SchedV3.kt:1)
	at com.ichi2.libanki.sched.SchedV3.counts(SchedV3.kt:3)
	at com.ichi2.anki.Reviewer.updateScreenCounts(Reviewer.kt:4)
	at com.ichi2.anki.Reviewer.updateActionBar(Reviewer.kt:2)
	at com.ichi2.anki.AbstractFlashcardViewer.onResume(AbstractFlashcardViewer.kt:5)
	at com.ichi2.anki.Reviewer.onResume(Reviewer.kt:2)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1476)
	at android.app.Activity.performResume(Activity.java:8441)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5200)
```

That may be unrelated

This is the one I think you mention here

https://ankidroid.org/acra/app/1/bug/11681/report/7ace815f-c217-4806-8afb-c0ddbdc6d60e

exception actually in logcat

```
--------- beginning of main
08-29 20:53:23.867 W/AnkiDroid(11706): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.CardBrowser.onCreateOptionsMenu(CardBrowser.kt:9)
08-29 20:53:23.867 W/AnkiDroid(11706): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.CardBrowser.onCreateOptionsMenu(CardBrowser.kt:9)
08-29 20:53:23.870 W/AnkiDroid(11706): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.CardBrowser.onCreateOptionsMenu(CardBrowser.kt:24)
08-29 20:53:23.870 I/AnkiDroid(11706): undo: UndoStatus(undo=null, redo=null, lastStep=2), false
08-29 20:53:23.872 W/AnkiDroid(11706): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.CardBrowser.onCreateOptionsMenu(CardBrowser.kt:25)
08-29 20:53:32.009 W/AnkiDroid(11706): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.FilterSheetBottomFragment.createQuery(FilterSheetBottomFragment.kt:15)
08-29 20:53:32.012 I/AnkiDroid(11706): Cancelled 1 instances of task class com.ichi2.async.CollectionTask$SearchCards
08-29 20:53:32.014 W/AnkiDroid(11706): CollectionHelper/ java.lang.InterruptedException
08-29 20:53:32.014 W/AnkiDroid(11706): 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:11)
08-29 20:53:32.014 W/AnkiDroid(11706): 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:10)
08-29 20:53:32.014 W/AnkiDroid(11706): 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
08-29 20:53:32.014 W/AnkiDroid(11706): 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:2)
08-29 20:53:32.014 W/AnkiDroid(11706): 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
08-29 20:53:32.014 W/AnkiDroid(11706): 	at com.ichi2.anki.CollectionManager$getColUnsafe$1.invoke(CollectionManager.kt:1)
08-29 20:53:32.014 W/AnkiDroid(11706): 	at com.ichi2.anki.CollectionManager$getColUnsafe$1.invoke(CollectionManager.kt:2)
08-29 20:53:32.014 W/AnkiDroid(11706): 	at com.ichi2.anki.CollectionManager.logUIHangs(CollectionManager.kt:2)
08-29 20:53:32.014 W/AnkiDroid(11706): 	at com.ichi2.anki.CollectionManager.getColUnsafe(Unknown Source:4)
08-29 20:53:32.014 W/AnkiDroid(11706): 	at com.ichi2.anki.CollectionHelper.getCol(Unknown Source:1)
08-29 20:53:32.014 W/AnkiDroid(11706): 	at com.ichi2.anki.CollectionHelper.getColSafe(CollectionHelper.java:2)
08-29 20:53:32.014 W/AnkiDroid(11706): 	at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.kt:12)
08-29 20:53:32.014 W/AnkiDroid(11706): 	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.kt:2)
08-29 20:53:32.014 W/AnkiDroid(11706): 	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.kt:1)
08-29 20:53:32.014 W/AnkiDroid(11706): 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
08-29 20:53:32.014 W/AnkiDroid(11706): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
08-29 20:53:32.014 W/AnkiDroid(11706): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
08-29 20:53:32.014 W/AnkiDroid(11706): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
08-29 20:53:32.014 W/AnkiDroid(11706): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
08-29 20:53:32.014 W/AnkiDroid(11706): 	at java.lang.Thread.run(Thread.java:1012)

```

@dae not sure if this is in the batch of commits you have queued in #12226
