### ISSUE TITLE
[Bug] Latest Alpha build force quit on long pressing when editing

### ISSUE THREAD

**Issue by escape0707** [ankidroid/Anki-Android#12316]
###### Reproduction Steps

1. Select a deck to learn.
2. Edit it.
3. Long press on a field.

###### Actual Result

The app crashes and sent a crash report 

###### Debug info
AnkiDroid Version = 2.16alpha83

Android Version = 13

Manufacturer = Google

Model = Pixel 6a

Hardware = bluejay

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 6a Build/TP1A.220624.021.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36

ACRA UUID = 9c32ddea-ccc7-42cb-9016-62a03202d3d3

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by escape0707** [comment]
I can't easily revert to the previous alpha without wiping app data. This breaks my current study flow

**Comment by mikehardy** [comment]
@escape0707 super resourceful on the adb force downgrade switch! Sorry this broke for you



```
java.lang.NullPointerException: menu.findItem(android.R.id.pasteAsPlainText) must not be null
	at com.ichi2.anki.NoteEditor$ActionModeCallback.onPrepareActionMode(NoteEditor.kt:3)
	at android.widget.Editor$TextActionModeCallback.onPrepareActionMode(Editor.java:4347)
	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onPrepareActionMode(DecorView.java:2733)
	at com.android.internal.view.FloatingActionMode.invalidate(FloatingActionMode.java:144)
	at com.android.internal.policy.DecorView.setHandledFloatingActionMode(DecorView.java:2097)
	at com.android.internal.policy.DecorView.setHandledActionMode(DecorView.java:1937)
	at com.android.internal.policy.DecorView.startActionMode(DecorView.java:927)
	at com.android.internal.policy.DecorView.startActionModeForChild(DecorView.java:882)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1036)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1036)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1036)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1036)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1036)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1036)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1036)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1036)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1036)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1036)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1036)
	at android.view.View.startActionMode(View.java:7705)
	at android.widget.Editor.startActionModeInternal(Editor.java:2524)
	at android.widget.SelectionActionModeHelper.startActionMode(SelectionActionModeHelper.java:300)
	at android.widget.SelectionActionModeHelper.startSelectionActionMode(SelectionActionModeHelper.java:281)
	at android.widget.SelectionActionModeHelper.lambda$startSelectionActionModeWithSmartSelectAnimation$0$android-widget-SelectionActionModeHelper(SelectionActionModeHelper.java:335)
	at android.widget.SelectionActionModeHelper$$ExternalSyntheticLambda9.run(Unknown Source:4)
	at android.widget.SelectionActionModeHelper.startSelectionActionModeWithSmartSelectAnimation(SelectionActionModeHelper.java:343)
	at android.widget.SelectionActionModeHelper.$r8$lambda$mMDhXh3JQs_q5UuyTdq2CLenZJk(Unknown Source:0)
	at android.widget.SelectionActionModeHelper$$ExternalSyntheticLambda11.accept(Unknown Source:4)
	at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onPostExecute(SelectionActionModeHelper.java:1044)
	at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onTimeOut(SelectionActionModeHelper.java:1050)
	at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.$r8$lambda$hPa951VBVINLDsSAuruPyVIydiY(Unknown Source:0)
	at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

logcat 

```
--------- beginning of main
09-05 07:37:24.148 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.reviewer.AutomaticAnswerSettings$Companion.getAction(AutomaticAnswer.kt:1)
09-05 07:37:24.150 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.reviewer.AutomaticAnswerSettings$Companion.createInstance(AutomaticAnswer.kt:2)
09-05 07:37:24.150 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.reviewer.AutomaticAnswerSettings$Companion.queryDeckSpecificOptions(AutomaticAnswer.kt:1)
09-05 07:37:24.150 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.reviewer.AutomaticAnswerSettings$Companion.queryDeckSpecificOptions(AutomaticAnswer.kt:2)
09-05 07:37:24.151 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.reviewer.AutomaticAnswerSettings$Companion.queryDeckSpecificOptions(AutomaticAnswer.kt:2)
09-05 07:37:24.151 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.restoreCollectionPreferences(Reviewer.kt:2)
09-05 07:37:24.153 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.setTitle(Reviewer.kt:2)
09-05 07:37:24.153 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.setTitle(Reviewer.kt:2)
09-05 07:37:24.172 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.AbstractFlashcardViewer.getParentDid(Unknown Source:8)
09-05 07:37:24.179 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.dealWithTimeBox(AbstractFlashcardViewer.kt:2)
09-05 07:37:24.180 I/AnkiDroid( 4269): ViewGroupUtils::setRenderWorkaround - using default / hardware rendering
09-05 07:37:24.181 I/AnkiDroid( 4269): AnkiActivity::onStart - Reviewer
09-05 07:37:24.182 I/AnkiDroid( 4269): Obtaining card
09-05 07:37:24.189 I/AnkiDroid( 4269): AnkiActivity::onResume - Reviewer
09-05 07:37:24.191 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.setTitle(Reviewer.kt:2)
09-05 07:37:24.191 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.setTitle(Reviewer.kt:2)
09-05 07:37:24.225 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.kt:26)
09-05 07:37:24.225 I/AnkiDroid( 4269): undo: UndoStatus(undo=null, redo=null, lastStep=3), false
09-05 07:37:24.226 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.kt:33)
09-05 07:37:24.227 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.AbstractFlashcardViewer.getParentDid(Unknown Source:8)
09-05 07:37:24.227 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.kt:65)
09-05 07:37:24.233 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.cardviewer.SoundPlayer$CardSoundConfig$Companion.create(SoundPlayer.kt:1)
09-05 07:37:24.234 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.cardviewer.SoundPlayer$CardSoundConfig$Companion.create(SoundPlayer.kt:1)
09-05 07:37:24.234 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.reviewer.AnswerTimer.setupForCard(AnswerTimer.kt:2)
09-05 07:37:24.235 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.reviewer.AnswerTimer.setupForCard(AnswerTimer.kt:2)
09-05 07:37:24.272 I/AnkiDroid( 4269): ViewGroupUtils::setRenderWorkaround - using default / hardware rendering
09-05 07:37:24.286 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.AbstractFlashcardViewer.updateDeckName(AbstractFlashcardViewer.kt:3)
09-05 07:37:24.287 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.AbstractFlashcardViewer.updateDeckName(AbstractFlashcardViewer.kt:3)
09-05 07:37:24.288 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.updateScreenCounts(Reviewer.kt:4)
09-05 07:37:24.289 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.updateScreenCounts(Reviewer.kt:13)
09-05 07:37:24.289 I/AnkiDroid( 4269): AbstractFlashcardViewer:: Question successfully shown for card id 1662314833563
09-05 07:37:24.296 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.kt:26)
09-05 07:37:24.296 I/AnkiDroid( 4269): undo: UndoStatus(undo=null, redo=null, lastStep=3), false
09-05 07:37:24.297 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.kt:33)
09-05 07:37:24.299 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.AbstractFlashcardViewer.getParentDid(Unknown Source:8)
09-05 07:37:24.299 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.kt:65)
09-05 07:37:24.301 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.suspendNoteAvailable(Reviewer.kt:4)
09-05 07:37:24.301 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ select 1 from cards where nid = ? and id != ? and queue != -1 limit 1
09-05 07:37:24.301 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.suspendNoteAvailable(Reviewer.kt:4)
09-05 07:37:24.301 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.suspendNoteAvailable(Reviewer.kt:4)
09-05 07:37:24.302 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.buryNoteAvailable(Reviewer.kt:4)
09-05 07:37:24.302 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ select 1 from cards where nid = ? and id != ? and queue >=  0 limit 1
09-05 07:37:24.302 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.buryNoteAvailable(Reviewer.kt:4)
09-05 07:37:24.303 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.buryNoteAvailable(Reviewer.kt:4)
09-05 07:37:24.325 I/AnkiDroid( 4269): AnkiActivity::onStop - DeckPicker
09-05 07:37:26.305 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.AbstractFlashcardViewer.isUndoAvailable(Unknown Source:4)
09-05 07:37:26.305 I/AnkiDroid( 4269): undo: UndoStatus(undo=null, redo=null, lastStep=3), false
09-05 07:37:27.192 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.displayAnswerBottomBar$nextIvlStr(Unknown Source:12)
09-05 07:37:27.196 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.displayAnswerBottomBar$nextIvlStr(Unknown Source:12)
09-05 07:37:27.197 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.displayAnswerBottomBar$nextIvlStr(Unknown Source:12)
09-05 07:37:27.198 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.displayAnswerBottomBar$nextIvlStr(Unknown Source:12)
09-05 07:37:27.200 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.displayAnswerBottomBar$nextIvlStr(Unknown Source:12)
09-05 07:37:27.201 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.displayAnswerBottomBar$nextIvlStr(Unknown Source:12)
09-05 07:37:27.202 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.displayAnswerBottomBar$nextIvlStr(Unknown Source:12)
09-05 07:37:27.204 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.displayAnswerBottomBar$nextIvlStr(Unknown Source:12)
09-05 07:37:28.385 I/AnkiDroid( 4269): AnkiActivity::onPause - Reviewer
09-05 07:37:28.385 I/AnkiDroid( 4269): stop: automatically show answer
09-05 07:37:28.385 I/AnkiDroid( 4269): stop: automatically show question
09-05 07:37:28.412 I/AnkiDroid( 4269): AnkiActivity::onCreate - NoteEditor
09-05 07:37:28.428 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.ui.NoteTypeSpinnerUtils.setupNoteTypeSpinner(NoteTypeSpinnerUtils.kt:1)
09-05 07:37:28.430 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: kotlin.sequences.TransformingSequence$iterator$1.next(Unknown Source:12)
09-05 07:37:28.431 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: kotlin.sequences.TransformingSequence$iterator$1.next(Unknown Source:12)
09-05 07:37:28.432 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: kotlin.sequences.TransformingSequence$iterator$1.next(Unknown Source:12)
09-05 07:37:28.432 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: kotlin.sequences.TransformingSequence$iterator$1.next(Unknown Source:12)
09-05 07:37:28.433 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: kotlin.sequences.TransformingSequence$iterator$1.next(Unknown Source:12)
09-05 07:37:28.433 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: kotlin.sequences.TransformingSequence$iterator$1.next(Unknown Source:12)
09-05 07:37:28.433 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: kotlin.sequences.TransformingSequence$iterator$1.next(Unknown Source:12)
09-05 07:37:28.434 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: kotlin.sequences.TransformingSequence$iterator$1.next(Unknown Source:12)
09-05 07:37:28.434 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: kotlin.sequences.TransformingSequence$iterator$1.next(Unknown Source:12)
09-05 07:37:28.434 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: kotlin.sequences.TransformingSequence$iterator$1.next(Unknown Source:12)
09-05 07:37:28.435 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: kotlin.sequences.TransformingSequence$iterator$1.next(Unknown Source:12)
09-05 07:37:28.436 W/AnkiDroid( 4269): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.DeckSpinnerSelection.computeDropDownDecks(DeckSpinnerSelection.kt:1)
09-05 07:37:28.462 I/AnkiDroid( 4269): onCollectionLoaded() Edit note activity successfully started with card id 1662314833563
09-05 07:37:28.463 I/AnkiDroid( 4269): AnkiActivity::onStart - NoteEditor
09-05 07:37:28.465 I/AnkiDroid( 4269): AnkiActivity::onResume - NoteEditor
09-05 07:37:28.557 I/AnkiDroid( 4269): AnkiActivity::onStop - Reviewer

```

**Comment by mikehardy** [comment]
I see 14 total crashes from you, 5 independent mechanisms, over course of 3 weeks. You are a warrior for helping us test through all this stuff, really appreciated

**Comment by escape0707** [comment]
> I see 14 total crashes from you, 5 independent mechanisms, over course of 3 weeks. You are a warrior for helping us test through all this stuff, really appreciated

Trying to be more useful by learning the Android Kotlin & Compose course. Gotta give as you take. :wink:

**Comment by escape0707** [comment]
Can we publish another alpha release so that people who want to try them out won't face this issue?

**Comment by mikehardy** [comment]
@escape0707 - yep, working through the process now (translations sync + dependencies updates + merging rest of the things that look good for the release). Should release a new alpha in next 12-36hrs
