### ISSUE TITLE
Crash - 2.16alpha83 - coroutines interruptedexception return to deck list from settings + auto-sync

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#12370]
###### Reproduction Steps

1. get latest alpha (2.16alpha83 shows this, at least)
2. enable automatic synchronization (so: when you go back to your deck list, it should synchronize...)
3. enable new backend and v3 scheduler
4. go to settings -> accessibility
5. maybe wait 10minutes? such that there is something to sync? mine syncs every time though

###### Expected Result

deck list return after settings plus auto sync says it should sync, then show deck list

###### Actual Result

sometimes, almost never (I tried a lot to reproduce it), it will crash.

I sent an error report and will paste logcat and stack in below

###### Debug info

https://ankidroid.org/acra/app/1/bug/13053/report/4b0afc20-91a9-4596-b95f-a4a69fd1edbd

```
crashed while hitting back button from settings
Stacktrace (No mapping found)
java.lang.InterruptedException
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:11)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:10)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:2)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at com.ichi2.anki.CollectionManager.blockForQueue(CollectionManager.kt:3)
	at com.ichi2.anki.CollectionManager.access$blockForQueue(Unknown Source:0)
	at com.ichi2.anki.CollectionManager$getColUnsafe$1.invoke(CollectionManager.kt:2)
	at com.ichi2.anki.CollectionManager$getColUnsafe$1.invoke(CollectionManager.kt:1)
	at com.ichi2.anki.CollectionManager.logUIHangs(CollectionManager.kt:2)
	at com.ichi2.anki.CollectionManager.getColUnsafe(Unknown Source:4)
	at com.ichi2.anki.CollectionHelper.getCol(Unknown Source:1)
	at com.ichi2.anki.CollectionHelper.getColSafe(CollectionHelper.java:2)
	at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.kt:12)
	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.kt:2)
	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.kt:1)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```

logcat

```
--------- beginning of main
09-10 08:34:45.145 I/AnkiDroid(10322): initialize()
09-10 08:34:45.571 I/AnkiDroid(10322): Not participating in analytics sample (sample percentage vs random: 10 58)
09-10 08:34:45.571 I/AnkiDroid(10322): setOptIn(): from false to true
09-10 08:34:45.571 I/AnkiDroid(10322): Not participating in analytics sample (sample percentage vs random: 10 57)
09-10 08:34:45.574 I/AnkiDroid(10322): Creating notification channel with id/name: General Notifications/AnkiDroid
09-10 08:34:45.575 I/AnkiDroid(10322): Creating notification channel with id/name: Synchronization/Synchronization
09-10 08:34:45.576 I/AnkiDroid(10322): Creating notification channel with id/name: Global Reminders/Cards due
09-10 08:34:45.576 I/AnkiDroid(10322): Creating notification channel with id/name: Deck Reminders/Reminders
09-10 08:34:45.597 I/AnkiDroid(10322): AnkiDroidApp: Starting Services
09-10 08:34:45.682 I/AnkiDroid(10322): (Re)opening Database: /storage/emulated/0/AnkiDroid/collection.anki2
09-10 08:34:45.703 I/AnkiDroid(10322): Opening Collection Log
09-10 08:34:45.720 E/AnkiDroid(10322): CollectionManager/ blocked main thread for 121ms:
09-10 08:34:45.720 E/AnkiDroid(10322): com.ichi2.anki.services.BootService.getColSafe(BootService.kt:1)
09-10 08:34:45.720 I/AnkiDroid(10322): Executing Boot Service
09-10 08:34:45.722 W/AnkiDroid(10322): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.services.BootService.scheduleDeckReminder(BootService.kt:2)
09-10 08:34:45.735 W/AnkiDroid(10322): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.services.BootService$Companion.getRolloverHourOfDay(BootService.kt:2)
09-10 08:34:45.736 W/AnkiDroid(10322): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.services.BootService$Companion.getRolloverHourOfDay(BootService.kt:2)
09-10 08:34:45.737 W/AnkiDroid(10322): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.services.BootService$Companion.getRolloverHourOfDay(BootService.kt:5)
09-10 08:34:45.737 W/AnkiDroid(10322): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.services.BootService$Companion.getRolloverHourOfDay(BootService.kt:5)
09-10 08:34:45.777 I/AnkiDroid(10322): AnkiActivity::onCreate - Preferences
09-10 08:34:45.853 I/AnkiDroid(10322): AnkiActivity::onStart - Preferences
09-10 08:34:45.889 I/AnkiDroid(10322): AnkiActivity::onResume - Preferences
--------- beginning of system
09-10 08:34:47.957 I/AnkiDroid(10322): finishWithAnimation DEFAULT
09-10 08:34:47.987 I/AnkiDroid(10322): AnkiActivity::onPause - Preferences
09-10 08:34:48.039 I/AnkiDroid(10322): AnkiActivity::onCreate - DeckPicker
09-10 08:34:48.128 I/AnkiDroid(10322): No startup screens required
09-10 08:34:48.129 I/AnkiDroid(10322): Triggering Automatic Sync
09-10 08:34:48.147 I/AnkiDroid(10322): AnkiActivity::onStart - DeckPicker
09-10 08:34:48.153 I/AnkiDroid(10322): Handling Activity Result: 100. Result: 0
09-10 08:34:48.153 I/AnkiDroid(10322): Creating notification channel with id/name: General Notifications/AnkiDroid
09-10 08:34:48.154 I/AnkiDroid(10322): Creating notification channel with id/name: Synchronization/Synchronization
09-10 08:34:48.154 I/AnkiDroid(10322): Creating notification channel with id/name: Global Reminders/Cards due
09-10 08:34:48.154 I/AnkiDroid(10322): Creating notification channel with id/name: Deck Reminders/Reminders
09-10 08:34:48.155 I/AnkiDroid(10322): AnkiActivity -- restartActivity()
09-10 08:34:48.163 I/AnkiDroid(10322): finishWithoutAnimation
09-10 08:34:48.164 I/AnkiDroid(10322): AnkiActivity::onResume - DeckPicker
09-10 08:34:48.175 I/AnkiDroid(10322): Cancelled 1 instances of task class com.ichi2.async.CollectionTask$LoadDeckCounts
09-10 08:34:48.175 I/AnkiDroid(10322): AnkiActivity::onPause - DeckPicker
09-10 08:34:48.176 W/AnkiDroid(10322): CollectionHelper/ java.lang.InterruptedException
09-10 08:34:48.176 W/AnkiDroid(10322): 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:11)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:10)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:2)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.anki.CollectionManager.blockForQueue(CollectionManager.kt:3)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.anki.CollectionManager.access$blockForQueue(Unknown Source:0)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.anki.CollectionManager$getColUnsafe$1.invoke(CollectionManager.kt:2)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.anki.CollectionManager$getColUnsafe$1.invoke(CollectionManager.kt:1)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.anki.CollectionManager.logUIHangs(CollectionManager.kt:2)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.anki.CollectionManager.getColUnsafe(Unknown Source:4)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.anki.CollectionHelper.getCol(Unknown Source:1)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.anki.CollectionHelper.getColSafe(CollectionHelper.java:2)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.kt:12)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.kt:2)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.kt:1)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at java.lang.Thread.run(Thread.java:923)
09-10 08:34:48.176 W/AnkiDroid(10322): 
09-10 08:34:48.176 W/AnkiDroid(10322): java.lang.InterruptedException
09-10 08:34:48.176 W/AnkiDroid(10322): 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:11)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:10)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:2)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.anki.CollectionManager.blockForQueue(CollectionManager.kt:3)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.anki.CollectionManager.access$blockForQueue(Unknown Source:0)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.anki.CollectionManager$getColUnsafe$1.invoke(CollectionManager.kt:2)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.anki.CollectionManager$getColUnsafe$1.invoke(CollectionManager.kt:1)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.anki.CollectionManager.logUIHangs(CollectionManager.kt:2)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.anki.CollectionManager.getColUnsafe(Unknown Source:4)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.anki.CollectionHelper.getCol(Unknown Source:1)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.anki.CollectionHelper.getColSafe(CollectionHelper.java:2)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.kt:12)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.kt:2)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.kt:1)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-10 08:34:48.176 W/AnkiDroid(10322): 	at java.lang.Thread.run(Thread.java:923)
09-10 08:34:48.189 I/AnkiDroid(10322): Updating deck list UI
```

I don't have a feel for exactly when kotlin coroutines crash but this seems like it may become a new "type" of bug indicating some sort of multi-threaded programming difficulty :thinking:

**Comment by dae** [comment]
I'm guessing this will be resolved when LoadDeckCounts is migrated to coroutines. My guess it is triggered when a call to getColUnsafe in a legacy CollectionTask is aborted by the task being cancelled.

**Comment by mikehardy** [comment]
good idea - I went through the Rust tag, and tagged a couple others that *may* fit, I will try to keep the tags lined up with this one going forward

**Comment by mikehardy** [comment]
Crash - stay open
