### ISSUE TITLE
[Bug] Not able to edit with press and hold on mobile.

### ISSUE THREAD

**Issue by cindynap** [ankidroid/Anki-Android#12420]
When editing, Anki is forced to quit once a press and hold to select the text is attempted. 

###### Debug info
AnkiDroid Version = 2.16alpha83

Android Version = 10

Manufacturer = HUAWEI

Model = MAR-LX1A

Hardware = kirin710

Webview User Agent = Mozilla/5.0 (Linux; Android 10; MAR-LX1A Build/HUAWEIMAR-L21A; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.79 Mobile Safari/537.36

ACRA UUID = 315958ca-0a8d-4259-8a96-e20de4c71bb3

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Thank you so much for opening the issue with your crash ID - here's what I pulled from our crash trace database:

```

09-15 20:50:12.406 E/AnkiDroid(15559): BaseAsyncTask/ must be called on the main thread instead of Thread[AsyncTask #3,5,main]
09-15 20:50:12.406 E/AnkiDroid(15559): BaseAsyncTask/ must be called on the main thread instead of Thread[AsyncTask #3,5,main]
09-15 20:59:46.216 E/AnkiDroid(15559): BaseAsyncTask/ must be called on the main thread instead of Thread[AsyncTask #5,5,main]
09-15 20:59:46.216 E/AnkiDroid(15559): BaseAsyncTask/ must be called on the main thread instead of Thread[AsyncTask #5,5,main]
09-15 21:22:40.741 E/AnkiDroid(15559): CoroutineHelpersKt$runCatchingTask/ java.lang.NullPointerException
09-15 21:22:40.741 E/AnkiDroid(15559): 	at com.ichi2.async.CollectionOperationsKt.updateCard(CollectionOperations.kt:7)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at com.ichi2.anki.AbstractFlashcardViewer$saveEditedCard$updatedCard$1$1.invoke(AbstractFlashcardViewer.kt:2)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at com.ichi2.anki.AbstractFlashcardViewer$saveEditedCard$updatedCard$1$1.invoke(AbstractFlashcardViewer.kt:1)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:3)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:1)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:2)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)
09-15 21:22:40.741 E/AnkiDroid(15559): 
09-15 21:22:40.741 E/AnkiDroid(15559): java.lang.NullPointerException
09-15 21:22:40.741 E/AnkiDroid(15559): 	at com.ichi2.async.CollectionOperationsKt.updateCard(CollectionOperations.kt:7)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at com.ichi2.anki.AbstractFlashcardViewer$saveEditedCard$updatedCard$1$1.invoke(AbstractFlashcardViewer.kt:2)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at com.ichi2.anki.AbstractFlashcardViewer$saveEditedCard$updatedCard$1$1.invoke(AbstractFlashcardViewer.kt:1)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:3)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:1)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:2)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
09-15 21:22:40.741 E/AnkiDroid(15559): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)
```

This is related to #12316  (and #12381) - and it appears that one affected you as well but the supposed fix to that was released in 2.16alpha83

When we discussed this on the mailing list, I was under the impression you were on 2.16alpha84 (note 84!) but it appears the crash is from 2.16alpha83, so it might just be that you need to update then paste will work?

Can you make sure you have installed 2.16alpha84 then hopefully you've got this fixed and everything is working for you

https://github.com/ankidroid/Anki-Android/releases/tag/v2.16alpha84

**Comment by cindynap** [comment]
Hi guys, I went to check the version and it was alpha 3. So I just upgrade
to 4 and no problem now, Thank you so much.

I am so sorry to waste your time.

Mike Hardy ***@***.***> 于 2022年9月16日周五 下午2:26写道：

**Comment by david-allison** [comment]
Thanks for alpha testing regardless!

**Comment by mikehardy** [comment]
@cindynap echoing David - no problem at all! We're really happy to another tester, and one willing to log issues is even better :-). If you see anything else please let us know. Happy reviewing
