### ISSUE TITLE
Failing unit test in local testing - AnkiStatsTaskHandlerTest > testCreateReviewSummaryStatistics AnkiStatsTaskHandlerTest > testCreateReviewSummaryStatistics 

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#12437]
###### Reproduction Steps

1. checkout main (test environment is Ubuntu current, with JDK11)
2. run `./gradlew jacocoUnitTestReport`
3. 

###### Expected Result

clean run

###### Actual Result

one test failure, why is there a hanging coroutine?

```
AnkiStatsTaskHandlerTest > testCreateReviewSummaryStatistics FAILED
    kotlinx.coroutines.test.UncompletedCoroutinesError: After waiting for 60000 ms, the test coroutine is not completing
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTestCoroutine$3$3.invokeSuspend(TestBuilders.kt:342)
        (Coroutine boundary)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTestCoroutine(TestBuilders.kt:326)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$1$1.invokeSuspend(TestBuilders.kt:167)
        at kotlinx.coroutines.test.TestBuildersJvmKt$createTestResult$1.invokeSuspend(TestBuildersJvm.kt:13)

        Caused by:
        kotlinx.coroutines.test.UncompletedCoroutinesError: After waiting for 60000 ms, the test coroutine is not completing
            at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTestCoroutine$3$3.invokeSuspend(TestBuilders.kt:342)
            at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
            at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
            at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
            at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
            at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
            at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
            at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
            at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
            at kotlinx.coroutines.test.TestBuildersJvmKt.createTestResult(TestBuildersJvm.kt:12)
            at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest(TestBuilders.kt:166)
            at kotlinx.coroutines.test.TestBuildersKt.runTest(Unknown Source)
            at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest(TestBuilders.kt:154)
            at kotlinx.coroutines.test.TestBuildersKt.runTest(Unknown Source)
            at com.ichi2.anki.RobolectricTest.runTest(RobolectricTest.kt:648)
            at com.ichi2.anki.RobolectricTest.runTest$default(RobolectricTest.kt:643)
            at com.ichi2.anki.stats.AnkiStatsTaskHandlerTest.testCreateReviewSummaryStatistics(AnkiStatsTaskHandlerTest.kt:59)

```

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by ShridharGoel** [comment]
@divyansh-dxn

**Comment by dae** [comment]
Here's a patch that I started on a while back and forgot about. It switches the custom dispatcher usage in that routine to withCol, and converts the test to check the success path instead of the failure path, since that seems more useful. I can't reproduce the test hang here - does this fix it for you Mike?

```diff
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
index 40c00ff3f..c412801fc 100644
--- a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
@@ -2223,7 +2223,12 @@ open class DeckPicker :
         renderPage()
         // Update the mini statistics bar as well
         launchCatchingTask {
-            AnkiStatsTaskHandler.createReviewSummaryStatistics(col, mReviewSummaryTextView)
+            val text = AnkiStatsTaskHandler.createReviewSummaryStatistics(this@DeckPicker)
+            mReviewSummaryTextView.apply {
+                this.text = text ?: ""
+                visibility = View.VISIBLE
+                invalidate()
+            }
         }
         Timber.d("Startup - Deck List UI Completed")
     }
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt b/AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
index d6230015f..5c9b6994b 100644
--- a/AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
@@ -16,10 +16,13 @@
 package com.ichi2.anki.stats
 
 import android.R
+import android.content.Context
 import android.view.View
 import android.webkit.WebView
 import android.widget.ProgressBar
 import android.widget.TextView
+import com.ichi2.anki.CollectionManager.withCol
+import com.ichi2.anki.CollectionManager.withOpenColOrNull
 import com.ichi2.libanki.Collection
 import com.ichi2.libanki.DeckId
 import com.ichi2.libanki.stats.Stats
@@ -126,43 +129,32 @@ class AnkiStatsTaskHandler private constructor(
         }
 
         suspend fun createReviewSummaryStatistics(
-            col: Collection,
-            view: TextView,
-            mainDispatcher: CoroutineDispatcher = Dispatchers.Main,
-            defaultDispatcher: CoroutineDispatcher = Dispatchers.IO
-        ): Unit = mutex.withLock {
-            withContext(defaultDispatcher) {
-                val todayStatString = if (!isActive || col.dbClosed) {
-                    Timber.d("Quitting DeckPreviewStatistics before execution")
-                    null
-                } else {
-                    Timber.d("Starting DeckPreviewStatistics")
-                    // eventually put this in Stats (in desktop it is not though)
-                    var cards: Int
-                    var minutes: Int
-                    /* cards, excludes rescheduled cards https://github.com/ankidroid/Anki-Android/issues/8592 */
-                    val query = "select sum(case when ease > 0 then 1 else 0 end), " +
-                        "sum(time)/1000 from revlog where id > " + (col.sched.dayCutoff - Stats.SECONDS_PER_DAY) * 1000
-                    Timber.d("DeckPreviewStatistics query: %s", query)
-                    col.db
-                        .query(query).use { cur ->
-                            cur.moveToFirst()
-                            cards = cur.getInt(0)
-                            minutes = (cur.getInt(1) / 60.0).roundToInt()
-                        }
-                    val res = view.resources
-                    val span = res.getQuantityString(com.ichi2.anki.R.plurals.in_minutes, minutes, minutes)
-                    res.getQuantityString(com.ichi2.anki.R.plurals.studied_cards_today, cards, cards, span)
-                }
-                todayStatString?.let {
-                    withContext(mainDispatcher) {
-                        view.apply {
-                            text = it
-                            visibility = View.VISIBLE
-                            invalidate()
-                        }
+            context: Context,
+        ): String? {
+            return withOpenColOrNull {
+                Timber.d("Starting DeckPreviewStatistics")
+                // eventually put this in Stats (in desktop it is not though)
+                var cards: Int
+                var minutes: Int
+                /* cards, excludes rescheduled cards https://github.com/ankidroid/Anki-Android/issues/8592 */
+                val query = "select sum(case when ease > 0 then 1 else 0 end), " +
+                        "sum(time)/1000 from revlog where id > " + (sched.dayCutoff - Stats.SECONDS_PER_DAY) * 1000
+                Timber.d("DeckPreviewStatistics query: %s", query)
+                db
+                    .query(query).use { cur ->
+                        cur.moveToFirst()
+                        cards = cur.getInt(0)
+                        minutes = (cur.getInt(1) / 60.0).roundToInt()
                     }
-                }
+                val res = context.resources
+                val span =
+                    res.getQuantityString(com.ichi2.anki.R.plurals.in_minutes, minutes, minutes)
+                res.getQuantityString(
+                    com.ichi2.anki.R.plurals.studied_cards_today,
+                    cards,
+                    cards,
+                    span
+                )
             }
         }
     }
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/stats/AnkiStatsTaskHandlerTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/stats/AnkiStatsTaskHandlerTest.kt
index 63e3e6b8a..d83a5ecb0 100644
--- a/AnkiDroid/src/test/java/com/ichi2/anki/stats/AnkiStatsTaskHandlerTest.kt
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/stats/AnkiStatsTaskHandlerTest.kt
@@ -15,8 +15,11 @@
  ****************************************************************************************/
 package com.ichi2.anki.stats
 
+import android.content.Intent
 import android.widget.TextView
+import androidx.test.core.app.ActivityScenario
 import androidx.test.ext.junit.runners.AndroidJUnit4
+import com.ichi2.anki.DeckPicker
 import com.ichi2.anki.RobolectricTest
 import com.ichi2.anki.stats.AnkiStatsTaskHandler.Companion.createReviewSummaryStatistics
 import com.ichi2.annotations.NeedsTest
@@ -33,35 +36,18 @@ import org.mockito.Mockito.*
 import org.mockito.MockitoAnnotations
 import org.mockito.kotlin.whenever
 import java.util.concurrent.ExecutionException
+import kotlin.coroutines.resume
+import kotlin.coroutines.suspendCoroutine
+import kotlin.test.assertEquals
 
 @OptIn(ExperimentalCoroutinesApi::class)
 @RunWith(AndroidJUnit4::class)
 class AnkiStatsTaskHandlerTest : RobolectricTest() {
-    @Mock
-    private lateinit var mCol: Collection
-
-    @Mock
-    private lateinit var mView: TextView
-
-    private val testDispatcher = StandardTestDispatcher()
-
-    @Before
-    override fun setUp() {
-        super.setUp()
-        MockitoAnnotations.openMocks(this)
-        whenever(mCol.db).thenReturn(null)
-        whenever(mCol.dbClosed).thenReturn(true)
-    }
-
     @Test
-    @Throws(ExecutionException::class, InterruptedException::class)
-    @NeedsTest("explain this test")
-    @Ignore("failing in local test runs - https://github.com/ankidroid/Anki-Android/issues/12437")
-    fun testCreateReviewSummaryStatistics() = runTest(testDispatcher) {
-        verify(mCol, atMost(0))!!.db
-        createReviewSummaryStatistics(mCol, mView, testDispatcher, testDispatcher)
-        advanceUntilIdle()
-        verify(mCol, atLeast(0))!!.db
-        verify(mCol, atLeast(1))!!.dbClosed
+    fun testCreateReviewSummaryStatistics() = runTest {
+        val deckPicker = startActivityNormallyOpenCollectionWithIntent(
+            DeckPicker::class.java, Intent()
+        )
+        assertEquals(createReviewSummaryStatistics(deckPicker), "Studied 0 cards in 0 minutes today")
     }
 }
```

**Comment by divyansh-dxn** [comment]
@dae I din't got why we are asserting null, actually It is passing so that implies I didn't understood. 

From my understanding, first we're creating an instance of deckpicker with open collection. From the function definition, if collection is closed the it should return null else a non-null string.

Now my question is what did I miss here? From this perspective we should be asserting non-null with open collection.

**Comment by divyansh-dxn** [comment]
@mikehardy can you checkout https://github.com/ankidroid/Anki-Android/pull/12457/commits/1a0685155cd3fd0b2bed83cf84a28ef47cfeec17 and let know if it works or not?

**Comment by mikehardy** [comment]
It appears to work!

```
BUILD SUCCESSFUL in 13m 7s
47 actionable tasks: 47 executed
```

**Comment by dae** [comment]
@divyansh-dxn I think the name startActivityNormallyOpenCollectionWithIntent() is probably a bit misleading here - the collection is lazily loaded on first access, and this code seems to run before the deck picker has a chance to load the collection.
