### ISSUE TITLE
[Crash] Selecting the tags option in Note Editor causes a crash.

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#12471]
###### Reproduction Steps

1. Click on + icon to create a new note (or open an existing note from card browser).
2. Select the tags option in the note editor.

###### Expected Result
The user is shown a list of existing tags to choose from and an option to create a new tag.

###### Actual Result
The AnkiDroid app crashes.

###### Debug info
AnkiDroid Version = 2.16alpha85

Android Version = 7.0

Manufacturer = motorola

Model = Moto C Plus

Hardware = mt6735

Webview User Agent = Mozilla/5.0 (Linux; Android 7.0; Moto C Plus Build/NRD90M.03.045; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36

ACRA UUID = c6a580cb-02cc-4970-b7a5-24615e6542e1

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by user1823** [comment]
May be related to #12472

**Comment by mikehardy** [comment]
Thanks for logging these! I see you are on the new schema + v3 scheduler, for people doing triage

Looks like this one from your install:
https://ankidroid.org/acra/app/1/bug/15378/report/8dc0f383-6a0e-4fab-882c-cf2ed015b1ca

I do not believe this is actually related to the new backend, this appears to be a general issue with sorting the tags

```
--------- beginning of main
09-21 11:43:02.011 E/AnkiDroid(25024): CollectionManager/ blocked main thread for 102ms:
09-21 11:43:02.011 E/AnkiDroid(25024): com.ichi2.anki.CardBrowser.onCreateOptionsMenu(CardBrowser.kt:60)
09-21 11:54:20.053 E/AnkiDroid(25024): CollectionManager/ blocked main thread for 106ms:
09-21 11:54:20.053 E/AnkiDroid(25024): com.ichi2.anki.CardBrowser.onCreateOptionsMenu(CardBrowser.kt:60)
```

```
java.lang.UnsupportedOperationException: ListIterator does not support set
	at org.apache.commons.collections4.list.SetUniqueList$SetListListIterator.set(SetUniqueList.java:5)
	at java.util.Collections.sort(Collections.java:247)
	at kotlin.collections.CollectionsKt__MutableCollectionsJVMKt.sortWith(MutableCollectionsJVM.kt:18)
	at kotlin.collections.CollectionsKt.sortWith(Unknown Source)
	at com.ichi2.anki.dialogs.tags.TagsList.sort(TagsList.kt:8)
	at com.ichi2.anki.dialogs.tags.TagsArrayAdapter.sortData(TagsArrayAdapter.kt:3)
	at com.ichi2.anki.dialogs.tags.TagsArrayAdapter.<init>(TagsArrayAdapter.kt:18)
	at com.ichi2.anki.dialogs.tags.TagsDialog.onCreateDialog(TagsDialog.kt:67)
	at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:14)
	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:17)
	at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:43)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:125)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:231)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:82)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:22)
	at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:2)
	at com.ichi2.anki.AnkiActivity$Companion.showDialogFragment(AnkiActivity.kt:7)
	at com.ichi2.anki.AnkiActivity$Companion.showDialogFragment(AnkiActivity.kt:1)
	at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.kt:8)
	at com.ichi2.anki.NoteEditor.showTagsDialog(NoteEditor.kt:55)
	at com.ichi2.anki.NoteEditor.onCollectionLoaded$lambda-4(NoteEditor.kt:16)
	at com.ichi2.anki.NoteEditor.k(NoteEditor.kt)
	at com.ichi2.anki.b6.onClick(R8$$SyntheticClass)
	at android.view.View.performClick(View.java:5675)
	at android.view.View$PerformClick.run(View.java:22646)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6251)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by mikehardy** [comment]
This is still a problem:  https://ankidroid.org/acra/app/1/bug/25509/report/c0c6d923-ee20-466a-b806-7528b6cc2755 reported by @ahmedbenarab

**Comment by user1823** [comment]
As demonstrated in #12472, the issue occurs only when the collection contains hierarchical tags (i.e., tags of the type A::B).

This information might be useful for finding the cause of the issue.

**Comment by ahmedbenarab** [comment]
@mikehardy, Like @user1823 has mentioned, using hierarchical tags in the format tag1::tag2::... Etc is what causes the crash

**Comment by user1823** [comment]
Still searching for solutions...

**Comment by ahmedbenarab** [comment]
still searching for solutions

**Comment by david-allison** [comment]
Seeing this on the legacy backend:

```

java.lang.UnsupportedOperationException: ListIterator does not support set
	at org.apache.commons.collections4.list.SetUniqueList$SetListListIterator.set(SetUniqueList.java:5)
	at java.util.Collections.sort(Collections.java:247)
	at kotlin.collections.CollectionsKt__MutableCollectionsJVMKt.sortWith(MutableCollectionsJVM.kt:18)
	at kotlin.collections.CollectionsKt.sortWith(Unknown Source)
	at com.ichi2.anki.dialogs.tags.TagsList.sort(TagsList.kt:13)
	at com.ichi2.anki.dialogs.tags.TagsArrayAdapter.sortData(TagsArrayAdapter.kt:3)
	at com.ichi2.anki.dialogs.tags.TagsArrayAdapter.<init>(TagsArrayAdapter.kt:18)
	at com.ichi2.anki.dialogs.tags.TagsDialog.onCreateDialog(TagsDialog.kt:67)
	at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:14)
	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:17)
	at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:43)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:125)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:231)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:82)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:22)
	at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:2)
	at com.ichi2.anki.AnkiActivity$Companion.showDialogFragment(AnkiActivity.kt:7)
	at com.ichi2.anki.AnkiActivity$Companion.showDialogFragment(AnkiActivity.kt:1)
	at com.ichi2.anki.AnkiActivity.showDialogFragment$lambda$1(AnkiActivity.kt:13)
	at com.ichi2.anki.AnkiActivity.h(AnkiActivity.kt:1)
	at com.ichi2.anki.t0.run(R8$$SyntheticClass:5)
	at android.app.Activity.runOnUiThread(Activity.java:5851)
	at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.kt:11)
	at com.ichi2.anki.NoteEditor.showTagsDialog(NoteEditor.kt:55)
	at com.ichi2.anki.NoteEditor.onCollectionLoaded$lambda$6(NoteEditor.kt:16)
	at com.ichi2.anki.NoteEditor.C(NoteEditor.kt:1)
	at com.ichi2.anki.f6.onClick(R8$$SyntheticClass:3)
	at android.view.View.performClick(View.java:5690)
	at android.view.View$PerformClick.run(View.java:22693)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6269)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

* https://ankidroid.org/acra/app/1/bug/46611/report/5290c283-4177-41bf-aed2-490420d01c16
* 2.16alpha98

<details><summary>Logcat</summary>

```
LOGCAT
--------- beginning of main
04-26 08:16:55.544 E/AnkiDroid(29444): CollectionManager/ blocked main thread for 891ms:
04-26 08:16:55.544 E/AnkiDroid(29444): com.ichi2.anki.services.BootService.getColSafe(BootService.kt:7)
04-26 08:16:56.758 E/AnkiDroid(29444): CollectionManager/ blocked main thread for 236ms:
04-26 08:16:56.758 E/AnkiDroid(29444): com.ichi2.anki.DeckPicker.refreshState(DeckPicker.kt:72)
04-26 08:16:58.357 E/AnkiDroid(29444): CollectionManager/ blocked main thread for 1162ms:
04-26 08:16:58.357 E/AnkiDroid(29444): com.ichi2.anki.DeckPicker.renderPage(DeckPicker.kt:344)
04-26 08:17:37.425 E/AnkiDroid(29444): CollectionManager/ blocked main thread for 141ms:
04-26 08:17:37.425 E/AnkiDroid(29444): com.ichi2.anki.DeckPicker.refreshState(DeckPicker.kt:72)
04-26 08:17:37.734 E/AnkiDroid(29444): CollectionManager/ blocked main thread for 112ms:
04-26 08:17:37.734 E/AnkiDroid(29444): com.ichi2.anki.DeckPicker.refreshState(DeckPicker.kt:72)
```
</details>

**Comment by david-allison** [comment]
Relevant:

https://github.com/ankidroid/Anki-Android/blob/a06e727f6094541b763e2dc18a300edb3e17fd26/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsListTest.kt#L489-L507

**Comment by oakkitten** [comment]
A very brief Google search points at `SetUniqueList` which is uh. Why are we using this? Can't we just use linked hash set (which Kotlin defaults to anyway)?
