### ISSUE TITLE
[Bug] Export - Select app for sharing crash

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#12675]
###### Reproduction Steps
1. Export collection - tap OK
2. Select application for sharing

###### Expected Result
An application can be choosen.

###### Actual Result
Crash

###### Debug info
AnkiDroid Version = 2.16alpha88

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36

ACRA UUID = e943bf81-2f29-4df3-9147-5126fdecc579

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by lukstbit** [comment]
Thanks for the bug report.
I've reviewed the function where this crash is most likely to happen but I don't see anything suspicious. It would be really helpful to see the exact crash report.

**Comment by dae** [comment]
```
select application for sharing
Stacktrace (No mapping found)
java.lang.SecurityException: UID 10381 does not have permission to content://com.ichi2.anki.apkgfileprovider/export-directory/Default-20221016075038.apkg [user 0]
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
	at android.os.Parcel.createException(Parcel.java:2421)
	at android.os.Parcel.readException(Parcel.java:2404)
	at android.os.Parcel.readException(Parcel.java:2346)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2897)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1743)
	at android.app.Activity.startActivityForResult(Activity.java:5473)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
	at android.app.Activity.startActivityForResult(Activity.java:5431)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:1)
	at com.ichi2.anki.AnkiActivity.startActivityForResult(AnkiActivity.kt:6)
	at android.app.Activity.startActivity(Activity.java:5817)
	at android.app.Activity.startActivity(Activity.java:5770)
	at com.ichi2.anki.AnkiActivity.startActivityWithoutAnimation(AnkiActivity.kt:9)
	at com.ichi2.anki.export.ActivityExportingDelegate.shareFile(ActivityExportingDelegate.kt:191)
	at com.ichi2.anki.dialogs.ExportCompleteDialog$onCreateDialog$1$1.invoke(ExportCompleteDialog.kt:3)
	at com.ichi2.anki.dialogs.ExportCompleteDialog$onCreateDialog$1$1.invoke(ExportCompleteDialog.kt:1)
	at com.afollestad.materialdialogs.internal.list.PlainListDialogAdapter.itemClicked(PlainListDialogAdapter.kt:76)
	at com.afollestad.materialdialogs.internal.list.PlainListViewHolder.onClick(PlainListDialogAdapter.kt:12)
	at android.view.View.performClick(View.java:7792)
	at android.view.View.performClickInternal(View.java:7769)
	at android.view.View.access$3800(View.java:910)
	at android.view.View$PerformClick.run(View.java:30218)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionUnlocked(UriGrantsManagerService.java:1295)
	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionFromIntentUnlocked(UriGrantsManagerService.java:650)
	at com.android.server.uri.UriGrantsManagerService.access$1000(UriGrantsManagerService.java:115)
	at com.android.server.uri.UriGrantsManagerService$LocalService.checkGrantUriPermissionFromIntent(UriGrantsManagerService.java:1451)
	at com.android.server.wm.ActivityStarter$Request.resolveActivity(ActivityStarter.java:659)
```

https://ankidroid.org/acra/app/1/bug/18786/report/1edad010-784e-4bfd-a0d3-81b29191da22

**Comment by mikehardy** [comment]
Oh no - this method was just changed in #12490  / #12566 (by lukstbit who is already here :-) )
This stuff is subtle though, we do have a FileProvider but why isn't it getting the permission? 
My guess is that it is something like this:

https://github.com/ankidroid/Anki-Android/blob/0cd5117cc21fc0a857dd4088ceb824f5879f8ad3/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt#L260

where you have to grant the permission transitively to the consuming application ?

**Comment by lukstbit** [comment]
@pavreh I introduced in the latest alpha some changes to try to fix this bug. Could you please test and see if the bug still exists?

If the bug still exists, could you clarify if you see the crash immediately when clicking "Select application for sharing"(so no chooser dialog is shown) or when you select an application from the chooser(like Google Drive for example).

**Comment by pavreh** [comment]
Unfortunatelly, the bug is still in alpha89. The app crashes immediately after I tap Select app for sharing so I am not able to choose an app. I sent a test report.

**Comment by pavreh** [comment]
Yes, it is my ACRA UUID. I reinstalled AnkiDroid.A recently so it may be the reason for the new UUID...

**Comment by mikehardy** [comment]
Great - good to confirm - and it took no time at all to find the new one, luckily there are not that many crashes in these alpha versions so it was literally a matter of 2 seconds either way. Cheers

**Comment by pavreh** [comment]
Well, I tried to reproduce with Ankidroid.A (parallel build) 2.16alpha91 and the bug is still there but it is not reproducible with Ankidroid (universal build) 2.16alpha91.

**Comment by mikehardy** [comment]
That's quite odd! I wonder if there is some difference in the configuration of the two apps ?

**Comment by snowtimeglass** [comment]
The crash has been reproduced on AnkiDroid 2.16alpha92 (parallel.A) on my device.
It is not reproducible with Ankidroid 2.16alpha92 (arm64-v8a). Sharing works properly.
(There was no difference in their debug info other than ACRA UUID.)

In more detail, the crash was reproduced on AnkiDroid parallel.A when Ankidroid arm64-v8a is installed. After Ankidroid arm64-v8a is uninstalled, the reproduction steps on the parallel.A produced an error toast message, "Error sharing apkg file" instead of the crash.

**Comment by mikehardy** [comment]
Interesting. Sounds like there is some tangle between the parallel and regular builds, some unexpected inter-dependency.

Somewhat related #12955 to maybe untangle them

If this cannot be reproduced on the main (non-parallel) install then this may not be actionable, though it would interesting to see why the parallel and main installs have some unexpected cross-dependency

**Comment by pavreh** [comment]
I cannot reproduce anymore in Ankidroid.A 2.17alpha1 while Ankidroid 2.16.4 is installed.
