### ISSUE TITLE
[Bug] Export - select file crash

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#12676]
###### Reproduction Steps
1. Export collection - tap OK
2. Tap Select where to save file
3. Tab back in the folder selector

###### Expected Result
Export is aborted.

###### Actual Result
Crash

###### Debug info
AnkiDroid Version = 2.16alpha88

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36

ACRA UUID = e943bf81-2f29-4df3-9147-5126fdecc579

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
```
export - save file - back
Stacktrace (No mapping found)
java.lang.NullPointerException
	at com.ichi2.anki.export.ActivityExportingDelegate.saveFileCallback(ActivityExportingDelegate.kt:5)
	at com.ichi2.anki.export.ActivityExportingDelegate._init_$lambda$5(ActivityExportingDelegate.kt:11)
	at com.ichi2.anki.export.ActivityExportingDelegate.a(Unknown Source:0)
	at com.ichi2.anki.export.a.onActivityResult(Unknown Source:4)
	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:102)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:15)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:70)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:73)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:54)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:10)
	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:6)
	at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPostStarted(ReportFragment.java:3)
	at android.app.Activity.dispatchActivityPostStarted(Activity.java:1420)
	at android.app.Activity.performStart(Activity.java:8352)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4060)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

https://ankidroid.org/acra/app/1/bug/18788/report/28d2b95e-7957-4a44-b64e-c1b1b7a08246
