### ISSUE TITLE
2.16alpha88 crashes when trying to sync

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#12711]
###### Reproduction Steps

1.  Login in Anki and let the data sync if any
2.  Turn off mobile data and wifi (Flight mode)
3.  Try syncing

###### Expected Result
Normal error dialog and then returned back to the app

###### Actual Result
app restarts

###### Debug info
AnkiDroid Version = 2.16alpha88

Android Version = 8.0.0

Manufacturer = Google

Model = Android SDK built for x86

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 8.0.0; Android SDK built for x86 Build/OSR1.180418.026; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Mobile Safari/537.36

ACRA UUID = 2adf2208-37f3-4838-84bf-7041ae68e9f9

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
https://user-images.githubusercontent.com/48384865/197037857-3fbc890b-44ed-4bff-83a7-0fff674dac2a.mp4

**Comment by criticalAY** [comment]
This issue was reported by some user and I was able to reproduce it after reading the report. I have pasted the debug info for SDK26 but this is also there in SDK 28. I have not tested further SDKs

**Comment by mikehardy** [comment]
Could you paste the stack trace of the reproduction? Most of our issues are API-independent (though of course some are subtle and only trigger on a specific API, usually an older one like 21 or 24 or the newest one like 33)

**Comment by BrayanDSO** [comment]
Hm. Why is the FAB's `+` button black?

**Comment by criticalAY** [comment]
> Could you paste the stack trace of the reproduction? Most of our issues are API-independent (though of course some are subtle and only trigger on a specific API, usually an older one like 21 or 24 or the newest one like 33)

java.net.UnknownHostException: Unable to resolve host "sync5.ankiweb.net": No address associated with hostname
                                                                                                    	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:141)
                                                                                                    	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
                                                                                                    	at java.net.InetAddress.getAllByName(InetAddress.java:787)
                                                                                                    	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
                                                                                                    	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164)
                                                                                                    	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129)
                                                                                                    	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
                                                                                                    	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
                                                                                                    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
                                                                                                    	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
                                                                                                    	at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.kt:196)
                                                                                                    	at com.ichi2.libanki.sync.HttpSyncer.req$default(HttpSyncer.kt:127)
                                                                                                    	at com.ichi2.libanki.sync.RemoteServer.meta(RemoteServer.kt:62)
                                                                                                    	at com.ichi2.libanki.sync.Syncer.sync(Syncer.kt:102)
                                                                                                    	at com.ichi2.async.Connection.doInBackgroundSync(Connection.kt:273)
                                                                                                    	at com.ichi2.async.Connection.doOneInBackground(Connection.kt:128)
                                                                                                    	at com.ichi2.async.Connection.doInBackground(Connection.kt:122)
                                                                                                    	at com.ichi2.async.Connection.doInBackground(Connection.kt:52)
                                                                                                    	at android.os.AsyncTask$2.call(AsyncTask.java:333)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                                    	at java.lang.Thread.run(Thread.java:764)
                                                                                                    Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
                                                                                                    	at libcore.io.Linux.android_getaddrinfo(Native Method)
                                                                                                    	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:58)
                                                                                                    	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:122)
                                                                                                    	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90) 
                                                                                                    	at java.net.InetAddress.getAllByName(InetAddress.java:787) 
                                                                                                    	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49) 
                                                                                                    	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164) 
                                                                                                    	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129) 
                                                                                                    	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71) 
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205) 
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) 
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) 
                                                                                                    	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) 
                                                                                                    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) 
                                                                                                    	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) 
                                                                                                    	at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.kt:196) 
                                                                                                    	at com.ichi2.libanki.sync.HttpSyncer.req$default(HttpSyncer.kt:127) 
                                                                                                    	at com.ichi2.libanki.sync.RemoteServer.meta(RemoteServer.kt:62) 
                                                                                                    	at com.ichi2.libanki.sync.Syncer.sync(Syncer.kt:102) 
                                                                                                    	at com.ichi2.async.Connection.doInBackgroundSync(Connection.kt:273) 
                                                                                                    	at com.ichi2.async.Connection.doOneInBackground(Connection.kt:128) 
                                                                                                    	at com.ichi2.async.Connection.doInBackground(Connection.kt:122) 
                                                                                                    	at com.ichi2.async.Connection.doInBackground(Connection.kt:52) 
                                                                                                    	at android.os.AsyncTask$2.call(AsyncTask.java:333) 
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
                                                                                                    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                                                    	at java.lang.Thread.run(Thread.java:764) 
2022-10-21 04:01:17.066  4814-7353  Connection              com.ichi2.anki                       E  doInBackgroundSync error
                                                                                                    java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "sync5.ankiweb.net": No address associated with hostname
                                                                                                    	at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.kt:223)
                                                                                                    	at com.ichi2.libanki.sync.HttpSyncer.req$default(HttpSyncer.kt:127)
                                                                                                    	at com.ichi2.libanki.sync.RemoteServer.meta(RemoteServer.kt:62)
                                                                                                    	at com.ichi2.libanki.sync.Syncer.sync(Syncer.kt:102)
                                                                                                    	at com.ichi2.async.Connection.doInBackgroundSync(Connection.kt:273)
                                                                                                    	at com.ichi2.async.Connection.doOneInBackground(Connection.kt:128)
                                                                                                    	at com.ichi2.async.Connection.doInBackground(Connection.kt:122)
                                                                                                    	at com.ichi2.async.Connection.doInBackground(Connection.kt:52)
                                                                                                    	at android.os.AsyncTask$2.call(AsyncTask.java:333)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                                    	at java.lang.Thread.run(Thread.java:764)
                                                                                                    Caused by: java.net.UnknownHostException: Unable to resolve host "sync5.ankiweb.net": No address associated with hostname
                                                                                                    	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:141)
                                                                                                    	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
                                                                                                    	at java.net.InetAddress.getAllByName(InetAddress.java:787)
                                                                                                    	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
                                                                                                    	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164)
                                                                                                    	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129)
                                                                                                    	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
                                                                                                    	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
                                                                                                    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
                                                                                                    	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
                                                                                                    	at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.kt:196)
                                                                                                    	at com.ichi2.libanki.sync.HttpSyncer.req$default(HttpSyncer.kt:127) 
                                                                                                    	at com.ichi2.libanki.sync.RemoteServer.meta(RemoteServer.kt:62) 
                                                                                                    	at com.ichi2.libanki.sync.Syncer.sync(Syncer.kt:102) 
                                                                                                    	at com.ichi2.async.Connection.doInBackgroundSync(Connection.kt:273) 
                                                                                                    	at com.ichi2.async.Connection.doOneInBackground(Connection.kt:128) 
                                                                                                    	at com.ichi2.async.Connection.doInBackground(Connection.kt:122) 
                                                                                                    	at com.ichi2.async.Connection.doInBackground(Connection.kt:52) 
                                                                                                    	at android.os.AsyncTask$2.call(AsyncTask.java:333) 
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
                                                                                                    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                                                    	at java.lang.Thread.run(Thread.java:764) 
                                                                                                    Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
                                                                                                    	at libcore.io.Linux.android_getaddrinfo(Native Method)
                                                                                                    	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:58)
                                                                                                    	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:122)
                                                                                                    	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90) 
                                                                                                    	at java.net.InetAddress.getAllByName(InetAddress.java:787) 
                                                                                                    	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49) 
                                                                                                    	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164) 
                                                                                                    	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129) 
                                                                                                    	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71) 
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205) 
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) 
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) 
                                                                                                    	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) 
                                                                                                    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) 
                                                                                                    	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) 
                                                                                                    	at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.kt:196) 
                                                                                                    	at com.ichi2.libanki.sync.HttpSyncer.req$default(HttpSyncer.kt:127) 
                                                                                                    	at com.ichi2.libanki.sync.RemoteServer.meta(RemoteServer.kt:62) 
                                                                                                    	at com.ichi2.libanki.sync.Syncer.sync(Syncer.kt:102) 
                                                                                                    	at com.ichi2.async.Connection.doInBackgroundSync(Connection.kt:273) 
                                                                                                    	at com.ichi2.async.Connection.doOneInBackground(Connection.kt:128) 
                                                                                                    	at com.ichi2.async.Connection.doInBackground(Connection.kt:122) 
                                                                                                    	at com.ichi2.async.Connection.doInBackground(Connection.kt:52) 
                                                                                                    	at android.os.AsyncTask$2.call(AsyncTask.java:333) 
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
                                                                                                    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                                                    	at java.lang.Thread.run(Thread.java:764)

**Comment by criticalAY** [comment]
> Hm. Why is the FAB's `+` button black?

I also payed attention to it after your comment

**Comment by criticalAY** [comment]
And yes it's API independent I have confirmed it

**Comment by mikehardy** [comment]
Very odd, I guess it is easy to reproduce app restart by just putting a bogus sync URL in (any name that passes OkHTTP URL validation, but is otherwise NXDOMAIN in DNS system). Should catch the error and just inform the user instead of crashing of course :-)

**Comment by criticalAY** [comment]
Yup! but not behaving as such

**Comment by pavreh** [comment]
> > Hm. Why is the FAB's `+` button black?
> 
> I also payed attention to it after your comment. Maybe there is some issue with the emulator works fine on other devices

I have sometimes + buttons black too on my real device. It is not only FAB but it is also + button in Card Browser or Edit Tags. It happens accidentally. I cannot reproduce on purpose.

**Comment by criticalAY** [comment]
> > > Hm. Why is the FAB's `+` button black?
> > 
> > 
> > I also payed attention to it after your comment. Maybe there is some issue with the emulator works fine on other devices
> 
> I have sometimes + buttons black too on my real device. It is not only FAB but it is also + button in Card Browser or Edit Tags. It happens accidentally. I cannot reproduce on purpose.

Seems like an issue then

**Comment by mikehardy** [comment]
As reported on discord: I just opened 2.16alpha88, synced, turned on airplane mode, synced, crashed, and sent the error report. I left details in the comment and I'm a OnePlus6T so probably easy to spot. I reproduce on my device at least. I'm new schema / v3 scheduler

**Comment by criticalAY** [comment]
Logcat crash report 
```
net.ankiweb.rsdroid.exceptions.BackendNetworkException: Please check your internet connection.
                                                                                                    
                                                                                                    Error details: ⁨error sending request for url (): error trying to connect: dns error: failed to lookup address information: No address associated with hostname⁩
                                                                                                    	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:115)
                                                                                                    	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:323)
                                                                                                    	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
                                                                                                    	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:130)
                                                                                                    	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:129)
                                                                                                    	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:157)
                                                                                                    	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:129)
                                                                                                    	at anki.backend.GeneratedBackend.syncStatusRaw(GeneratedBackend.kt:3641)
                                                                                                    	at anki.backend.GeneratedBackend.syncStatus(GeneratedBackend.kt:3648)
                                                                                                    	at com.ichi2.utils.SyncStatus$Companion.getSyncStatus(SyncStatus.kt:50)
                                                                                                    	at com.ichi2.anki.DeckPicker.fetchSyncStatus(DeckPicker.kt:732)
                                                                                                    	at com.ichi2.anki.DeckPicker.access$fetchSyncStatus(DeckPicker.kt:153)
                                                                                                    	at com.ichi2.anki.DeckPicker$updateMenuState$2.invoke(DeckPicker.kt:725)
                                                                                                    	at com.ichi2.anki.DeckPicker$updateMenuState$2.invoke(DeckPicker.kt:716)
                                                                                                    	at com.ichi2.anki.CollectionManager$withOpenColOrNull$2.invoke(CollectionManager.kt:97)
                                                                                                    	at com.ichi2.anki.CollectionManager$withOpenColOrNull$2.invoke(CollectionManager.kt:95)
                                                                                                    	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:69)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by criticalAY** [comment]
This exception is caused due to the network loss which I tried fixing by putting a check but @BrayanDSO is right if we do so then the whole purpose of the "Try anyway" button fails

**Comment by BrayanDSO** [comment]
My suggestion is catching `UnknownHostException` and `BackendNetworkException` exceptions and dealing with them

**Comment by criticalAY** [comment]
`null -> handleNormalSync(deckPicker, auth, syncMedia)`
The error/ exception arises from here so how about putting this in the `try-catch` ?

**Comment by criticalAY** [comment]
Have made a PR to fix it
