### ISSUE TITLE
[Bug] NullPointerException when adding notes with API

### ISSUE THREAD

**Issue by aap007freak** [ankidroid/Anki-Android#12756]
###### Reproduction Steps

1.  call the api.addNote function with some dummy values

```kotlin
val api = AddContentApi(applicationContext)

// these are both correct Longs (not null)
val modelId = api.modelList.entries.firstOrNull { m -> m.value == "Basic" }?.key
val deckId = api.deckList.entries.firstOrNull {d -> d.value == "testdeck"}?.key

val res = api.addNote(deckId!!, modelId!!, listOf("this is a test card", "this is a test answer").toTypedArray(), null)
```
###### Expected Result

Note added to Anki Droid

###### Actual Result

Error `java.lang.NullPointerException: Attempt to invoke virtual method 'long com.ichi2.utils.JSONObject.getLong(java.lang.String)' on a null object reference`

Here's the stacktrace:
```
 java.lang.NullPointerException: Attempt to invoke virtual method 'long com.ichi2.utils.JSONObject.getLong(java.lang.String)' on a null object reference
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2379)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.insert(ContentProviderNative.java:549)
        at android.content.ContentResolver.insert(ContentResolver.java:2149)
        at android.content.ContentResolver.insert(ContentResolver.java:2111)
        at com.ichi2.anki.api.AddContentApi.addNoteForContentValues(AddContentApi.java:110)
        at com.ichi2.anki.api.AddContentApi.addNoteInternal(AddContentApi.java:106)
        at com.ichi2.anki.api.AddContentApi.addNote(AddContentApi.java:92)
        at com.xxx.jishoyomiplayground.MainActivity$onCreate$1$1$1$1$1.invoke(MainActivity.kt:31)
        at com.xxx.jishoyomiplayground.MainActivity$onCreate$1$1$1$1$1.invoke(MainActivity.kt:25)
        at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke-k-4lQ0M(Clickable.kt:139)
        at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke(Clickable.kt:133)
        at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1$1.invokeSuspend(TapGestureDetector.kt:223)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:511)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:407)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:420)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:284)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:271)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:271)
        at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:151)
        at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:88)
        at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:80)
        at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:961)
        at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:934)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
2022-10-30 17:27:15.614 23651-23651/com.xxx.jishoyomiplayground E/AndroidRuntime:     at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4125)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
        at android.view.View.dispatchPointerEvent(View.java:14568)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6016)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5819)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5310)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5485)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5542)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8080)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8031)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7992)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8203)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:183)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

###### Debug info
(Running on an emulator so this might not be relevant)
AnkiDroid Version = 2.15.6
Android Version = 11
Manufacturer = Google
Model = sdk_gphone_x86
Hardware = ranchu
Webview User Agent = Mozilla/5.0 (Linux; Android 11; sdk_gphone_x86 Build/RSR1.201013.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36
ACRA UUID = b39b466f-df95-45fa-b57f-d4c6caf0cbeb
Scheduler = std2
Crash Reports Enabled = true
DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
did you encounter this in the app ?

**Comment by aap007freak** [comment]
> did you encounter this in the app ?

No this is while developping. I need to create cards from another app. Am I in the wrong place?

**Comment by mikehardy** [comment]
It's the correct place, but we do not often get API users, so many here are not familiar with what issues reported against the API look like, totally normal

You may need to use either an older version of the API or restrict to only newer versions of AnkiDroid (our 2.16alpha series) - https://github.com/ankidroid/Anki-Android/releases as there have been an incredible number of changes

In that direction: it would help to know exactly how you are including the API in your app, that is, something that would help us determine what version of the API code is executing, as it is probably a compatibility issue across the kotlin conversion that happened there - 

https://github.com/ankidroid/Anki-Android/commits/main/api

My guess is somewhere around this commit might work https://github.com/ankidroid/Anki-Android/commit/8f9f8c2261e8f503f47795601d1eab88c7140a50 with AnkiDroid 2.15.x

**Comment by aap007freak** [comment]
Thanks for the quick replies, I'll give some more context.

I'm working on a fork of the video player app [Aniyomi](https://github.com/jmir1/aniyomi) that adds some language learning features. One of those new features is to automatically add anki cards from an in-app dictionary, for which I want to use the API.

> You may need to use either an older version of the API or restrict to only newer versions of AnkiDroid (our 2.16alpha series) - https://github.com/ankidroid/Anki-Android/releases as there have been an incredible number of changes

I'd like to avoid having to force users to be on a specific version of Ankidroid wherever possible, downgrading the API is not that big of a deal I imagine.

> In that direction: it would help to know exactly how you are including the API in your app, that is, something that would help us determine what version of the API code is executing, as it is probably a compatibility issue across the kotlin conversion that happened there https://github.com/ankidroid/Anki-Android/commits/main/api
>  My guess is somewhere around this commit might work [8f9f8c2](https://github.com/ankidroid/Anki-Android/commit/8f9f8c2261e8f503f47795601d1eab88c7140a50) with AnkiDroid 2.15.x

I'm using Ankidroid v2.15.6 and the release of the API that is given in the github wiki:
```
 implementation 'com.github.ankidroid:Anki-Android:api-v1.1.0'
```
Is this the most recent version? Or do the API versions follow the main releases, in which case I might be 5 years out of date...? 😄

**Comment by mikehardy** [comment]
Well, the naming does not follow exactly, but you might try the current v2 - https://github.com/ankidroid/Anki-Android/blame/main/api/build.gradle#L8

If that does not work, I'm not sure the best way to get the API in fact - you might try using jitpack via the commit hash I mentioned - jitpack documents that using a commit hash as a version should result in a build that is usable (though it may timeout the first time, while building, before resolving after jitpack has finished building it) https://docs.jitpack.io/intro/#publishing-on-jitpack

**Comment by aap007freak** [comment]
Tried jitpack, the builds don't compile anymore because jitpack is still on java 8.0 and AnkiDroid requires at least 11 to build as far as I can see.

Then I cloned and built (using the :api:publishToMavenLocal gradle task) both [8f9f8c2](https://github.com/ankidroid/Anki-Android/commit/8f9f8c2261e8f503f47795601d1eab88c7140a50) and [6957e56](https://github.com/ankidroid/Anki-Android/commit/6957e562fc982954c095f60f0dd29fdf83496eeb) manually. 

I'm pretty sure I got everything set up as required but I still have the same NullPointerException as in the OP with these versions...
