### ISSUE TITLE
[Bug] No sync button badge on Android 6

### ISSUE THREAD

**Issue by oakkitten** [ankidroid/Anki-Android#12825]
###### Reproduction Steps

1. Open AnkiDroid on Android 6

###### Expected Result

I see a need to login badge

###### Actual Result

No badge, logcat is full of

```
D  Adding badge
E  parser error
   org.xmlpull.v1.XmlPullParserException: Binary XML file line #4<vector> tag requires viewportWidth > 0
      at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:783)
      at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:719)
      at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:682)
      at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:664)
      at com.ichi2.ui.BadgeDrawableBuilder.replaceBadge(BadgeDrawableBuilder.kt:54)
      at com.ichi2.anki.DeckPicker.updateSyncIconFromState(DeckPicker.kt:705)
      at com.ichi2.anki.DeckPicker.updateMenuFromState(DeckPicker.kt:667)
      at com.ichi2.anki.DeckPicker.access$updateMenuFromState(DeckPicker.kt:153)
      at com.ichi2.anki.DeckPicker$onCreateOptionsMenu$1.invokeSuspend(DeckPicker.kt:620)
      at com.ichi2.anki.DeckPicker$onCreateOptionsMenu$1.invoke(DeckPicker.kt)
      at com.ichi2.anki.DeckPicker$onCreateOptionsMenu$1.invoke(DeckPicker.kt)
      at com.ichi2.anki.CoroutineHelpersKt$launchCatchingTask$1$1.invokeSuspend(CoroutineHelpers.kt:127)
      at com.ichi2.anki.CoroutineHelpersKt$launchCatchingTask$1$1.invoke(CoroutineHelpers.kt)
      at com.ichi2.anki.CoroutineHelpersKt$launchCatchingTask$1$1.invoke(CoroutineHelpers.kt)
      at com.ichi2.anki.CoroutineHelpersKt.runCatchingTask(CoroutineHelpers.kt:56)
      at com.ichi2.anki.CoroutineHelpersKt$launchCatchingTask$1.invokeSuspend(CoroutineHelpers.kt:127)
      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
      at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
      at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
      at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
      at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
      at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
      at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
      at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
      at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
      at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
      at com.ichi2.anki.CoroutineHelpersKt.launchCatchingTask(CoroutineHelpers.kt:126)
      at com.ichi2.anki.CoroutineHelpersKt.launchCatchingTask$default(CoroutineHelpers.kt:122)
      at com.ichi2.anki.DeckPicker.onCreateOptionsMenu(DeckPicker.kt:618)
      at android.app.Activity.onCreatePanelMenu(Activity.java:2852)
      at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:521)
      at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:95)
      at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3429)
      at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
      at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
      at android.view.Choreographer.doCallbacks(Choreographer.java:670)
      at android.view.Choreographer.doFrame(Choreographer.java:603)
      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
      at android.os.Handler.handleCallback(Handler.java:739)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:148)
      at android.app.ActivityThread.main(ActivityThread.java:5461)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

###### Debug info
AnkiDroid Version = 2.16alpha88
Android Version = 6.0.1
Manufacturer = motorola
Model = Moto G
Hardware = qcom
Webview User Agent = Mozilla/5.0 (Linux; Android 6.0.1; Moto G Build/MOB30Z; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.106 Mobile Safari/537.36
ACRA UUID = 83fb2252-dcc0-4a3a-9e8f-888949f90ac0
New schema = false
Scheduler = std2
Crash Reports Enabled = false
DatabaseV2 Enabled = true
###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Even worse, with current main as of 20221114 at least, on a fresh install on Android 6 emulator it just crashed for me with a problem doing a linear gradient in the view XML

**Comment by oakkitten** [comment]
For the record, I updated to alpha89 and got a startup crash too. 88 doesn't seem to have this issue

```
ACRA caught a IllegalArgumentException for com.ichi2.anki
java.lang.IllegalArgumentException: color and position arrays must be of equal length
  at android.graphics.LinearGradient.<init>(LinearGradient.java:58)
  at android.graphics.drawable.GradientDrawable.ensureValidRect(GradientDrawable.java:942)
  at android.graphics.drawable.GradientDrawable.draw(GradientDrawable.java:516)
  at android.view.View.getDrawableRenderNode(View.java:16430)
  at android.view.View.drawBackground(View.java:16366)
  at android.view.View.draw(View.java:16178)
  at android.view.View.updateDisplayListIfDirty(View.java:15184)
  at android.view.View.draw(View.java:15957)
  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
  at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
  at android.view.View.draw(View.java:16190)
  at android.view.View.updateDisplayListIfDirty(View.java:15184)
  at android.view.View.draw(View.java:15957)
  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
  at android.view.View.draw(View.java:16190)
  at androidx.viewpager.widget.ViewPager.draw(ViewPager.java:2426)
  at android.view.View.updateDisplayListIfDirty(View.java:15184)
  at android.view.View.draw(View.java:15957)
  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
  at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
  at android.view.View.updateDisplayListIfDirty(View.java:15179)
  at android.view.View.draw(View.java:15957)
  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
  at android.view.View.updateDisplayListIfDirty(View.java:15179)
  at android.view.View.draw(View.java:15957)
  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
  at android.view.View.updateDisplayListIfDirty(View.java:15179)
  at android.view.View.draw(View.java:15957)
  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
  at android.view.View.updateDisplayListIfDirty(View.java:15179)
  at android.view.View.draw(View.java:15957)
  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
  at android.view.View.updateDisplayListIfDirty(View.java:15179)
  at android.view.View.draw(View.java:15957)
  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
  at android.view.View.draw(View.java:16190)
  at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2946)
  at android.view.View.updateDisplayListIfDirty(View.java:15184)
  at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:282)
  at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:288)
  at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
  at android.view.ViewRootImpl.draw(ViewRootImpl.java:2623)
  at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2442)
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2075)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
  at android.view.Choreographer.doFrame(Choreographer.java:606)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5461)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAn
```
