### ISSUE TITLE
[Bug] New backend: error when deleting unused media files on Android 6

### ISSUE THREAD

**Issue by oakkitten** [ankidroid/Anki-Android#12827]
###### Reproduction Steps

1. Have unused media
2. Tap on Check media, Ok
3. Tap on Delete unused

###### Expected Result

Files are deleted, no error

###### Actual Result

Only the first file is actually deleted; an error dialog pops up and logcat says:

```
net.ankiweb.rsdroid.exceptions.BackendIoException: IoError("Os { code: 1, kind: PermissionDenied, message: \"Operation not permitted\" }")
	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:117)
	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:323)
	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:130)
	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:129)
	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:157)
	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:129)
	at anki.backend.GeneratedBackend.trashMediaFilesRaw(GeneratedBackend.kt:3200)
	at anki.backend.GeneratedBackend.trashMediaFiles(GeneratedBackend.kt:3210)
	at com.ichi2.libanki.BackendMedia.removeFiles(BackendMedia.kt:59)
	at com.ichi2.async.CollectionOperationsKt.deleteMedia(CollectionOperations.kt:110)
	at com.ichi2.anki.DeckPicker$deleteUnused$1$noOfDeletedFiles$1$1.invoke(DeckPicker.kt:1495)
	at com.ichi2.anki.DeckPicker$deleteUnused$1$noOfDeletedFiles$1$1.invoke(DeckPicker.kt:1495)
	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:99)
	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:97)
	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:85)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

###### Debug info
AnkiDroid Version = 2.16alpha88
Android Version = 6.0.1
Manufacturer = motorola
Model = Moto G
Hardware = qcom
Webview User Agent = Mozilla/5.0 (Linux; Android 6.0.1; Moto G Build/MOB30Z; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.106 Mobile Safari/537.36
ACRA UUID = 83fb2252-dcc0-4a3a-9e8f-888949f90ac0
New schema = false
Scheduler = std2
Crash Reports Enabled = false
DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
Debugging this will require adding some println!() statements into the backend code to figure out which system call is failing and why. build_current.sh can't be used here since a cross-compilation toolchain is required, so probably easiest to make the changes and then build the library via github actions. The problem is probably in files.rs:remove_files().

**Comment by dae** [comment]
(if I had to guess at the problem, I suspect it's the set_file_times() call that calls utimes() in libc - it may be a similar issue to https://github.com/termux/termux-app/issues/240)

**Comment by oakkitten** [comment]
Note that one does get deleted, but not the rest of the bunch, might help narrow down the cause

**Comment by dae** [comment]
Based on the described behaviour, it appears that utimes() is not supported on (some?) Android devices. I'll change the code to swallow the error, as we don't actually need to be calling it at the moment.
