### ISSUE TITLE
[Bug]2.16alpha89 crashes after changing App Bar Options settings for Reschedule & Flag

### ISSUE THREAD

**Issue by LBX1002** [ankidroid/Anki-Android#12843]
###### Reproduction Steps

1. Change options in App Bar Buttons 
2.  Reschedule to Always Show or
3. Flag to Show if room.

###### Expected Result
New button arrangement

###### Actual Result
App crashes - cannot review cards

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by LBX1002** [comment]
Z Fold 3 Android v12

**Comment by mikehardy** [comment]
Hey @LBX1002 :wave: - we really need this to see the crash if possible:

> Debug info
> Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by LBX1002** [comment]
> Hey @LBX1002 👋 - we really need this to see the crash if possible:
> 
> > Debug info
> > Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.16alpha89

Android Version = 12

Manufacturer = samsung

Model = SM-F926U1

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-F926U1 Build/SP2A.220305.013; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.91 Safari/537.36

ACRA UUID = 6ac3160d-f3be-4ce9-b008-02a138953a8a

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by LBX1002** [comment]
Also, yesterday I sent a crash report from ankidroid itself.

**Comment by mikehardy** [comment]
@LBX1002 thanks for that!

```
java.lang.UnsupportedOperationException: This should no longer be called. onCreateActionView(MenuItem) should be used
	at com.ichi2.anki.ActionProviderCompat.onCreateActionView(ActionProviderCompat.kt:5)
	at androidx.core.view.ActionProvider.onCreateActionView(ActionProvider.java:1)
	at androidx.appcompat.view.menu.MenuItemImpl.getActionView(MenuItemImpl.java:10)
	at androidx.appcompat.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:1)
	at androidx.appcompat.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:204)
	at androidx.appcompat.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:44)
	at androidx.appcompat.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:13)
	at androidx.appcompat.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:1)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:45)
	at androidx.appcompat.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:12)
	at androidx.appcompat.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:12)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:52)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:3)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1111)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:792)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1095)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8855)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

logcat

```
--------- beginning of main
11-17 21:44:59.057 I/AnkiDroid( 7470): ViewGroupUtils::setRenderWorkaround - using default / hardware rendering
11-17 21:44:59.057 I/AnkiDroid( 7470): Obtaining card
11-17 21:44:59.057 I/AnkiDroid( 7470): AnkiActivity::onStart - Reviewer
11-17 21:44:59.059 I/AnkiDroid( 7470): AnkiActivity::onResume - Reviewer
11-17 21:44:59.060 E/AnkiDroid( 7470): BaseAsyncTask/ must be called on the main thread instead of Thread[AsyncTask #1,5,main]
11-17 21:44:59.060 E/AnkiDroid( 7470): BaseAsyncTask/ must be called on the main thread instead of Thread[AsyncTask #1,5,main]
11-17 21:44:59.160 I/AnkiDroid( 7470): ViewGroupUtils::setRenderWorkaround - using default / hardware rendering
11-17 21:44:59.169 I/AnkiDroid( 7470): AbstractFlashcardViewer:: Question successfully shown for card id 1639651509487
11-17 21:44:59.178 W/AnkiDroid( 7470): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.suspendNoteAvailable(Reviewer.kt:63)
11-17 21:44:59.178 W/AnkiDroid( 7470): Backend$checkMainThreadOp/ select 1 from cards where nid = ? and id != ? and queue != -1 limit 1
11-17 21:44:59.179 W/AnkiDroid( 7470): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.suspendNoteAvailable(Reviewer.kt:63)
11-17 21:44:59.179 W/AnkiDroid( 7470): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.suspendNoteAvailable(Reviewer.kt:63)
11-17 21:44:59.179 W/AnkiDroid( 7470): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.buryNoteAvailable(Reviewer.kt:63)
11-17 21:44:59.180 W/AnkiDroid( 7470): Backend$checkMainThreadOp/ select 1 from cards where nid = ? and id != ? and queue >=  0 limit 1
11-17 21:44:59.180 W/AnkiDroid( 7470): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.buryNoteAvailable(Reviewer.kt:63)
11-17 21:44:59.180 W/AnkiDroid( 7470): Backend$checkMainThreadOp/ Op on UI thread: com.ichi2.anki.Reviewer.buryNoteAvailable(Reviewer.kt:63)
```

https://ankidroid.org/acra/app/1/bug/25391/report/c69bb399-8be2-4f95-80b6-44d614d6e1eb

I see your comment on one of them:

> App crashes after I change reschedule button to "always show" on menu bar

**Comment by LBX1002** [comment]
2.16alpha90 works great. Much appreciated for all the great.work.

**Comment by mikehardy** [comment]
All hail @lukstbit on this one :-), and I'll take the opportunity to say I/we really appreciate the testing on the alpha releases, the 2.16 release contains so much change vs 2.15 it is a bit scary (as a release manager...) but knowing there are people using it regularly gives me some confidence! Cheers
