### ISSUE TITLE
Ankidroid alpha90, crash after trying to edit tags

### ISSUE THREAD

**Issue by ahmedbenarab** [ankidroid/Anki-Android#12858]
###### Reproduction Steps

1. Open. Ankidroid
2. Sync ur collection
3. Try to add a note
4. Just pressing tags field

###### Expected Result

Editing tags 

###### Actual Result

Ankidroid breaks down

###### Debug info
AnkiDroid Version = 2.16alpha90

Android Version = 7.0

Manufacturer = SPA Condor Electronics

Model = PGN611

Hardware = mt6735

Webview User Agent = Mozilla/5.0 (Linux; Android 7.0; PGN611 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.105 Mobile Safari/537.36

ACRA UUID = a54b0669-a918-4964-a718-1c3403f95912

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

NB : if I just use it without loading my own collection it doesn't crush
NB2 : after it breakdown it make a crash report 

https://user-images.githubusercontent.com/21174375/202903076-f1cffe7c-533f-43b6-9b75-af31480d4981.mp4

**Comment by mikehardy** [comment]
Thanks for the report!

:thinking: 

```
java.lang.UnsupportedOperationException: ListIterator does not support set
	at org.apache.commons.collections4.list.SetUniqueList$SetListListIterator.set(SetUniqueList.java:5)
	at java.util.Collections.sort(Collections.java:247)
	at kotlin.collections.CollectionsKt__MutableCollectionsJVMKt.sortWith(MutableCollectionsJVM.kt:18)
	at kotlin.collections.CollectionsKt.sortWith(Unknown Source)
	at com.ichi2.anki.dialogs.tags.TagsList.sort(TagsList.kt:8)
	at com.ichi2.anki.dialogs.tags.TagsArrayAdapter.sortData(TagsArrayAdapter.kt:3)
	at com.ichi2.anki.dialogs.tags.TagsArrayAdapter.<init>(TagsArrayAdapter.kt:18)
	at com.ichi2.anki.dialogs.tags.TagsDialog.onCreateDialog(TagsDialog.kt:67)
	at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:14)
	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:17)
	at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:43)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:125)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:231)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:82)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:22)
	at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:2)
	at com.ichi2.anki.AnkiActivity$Companion.showDialogFragment(AnkiActivity.kt:7)
	at com.ichi2.anki.AnkiActivity$Companion.showDialogFragment(AnkiActivity.kt:1)
	at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.kt:8)
	at com.ichi2.anki.NoteEditor.showTagsDialog(NoteEditor.kt:55)
	at com.ichi2.anki.NoteEditor.onCollectionLoaded$lambda$6(NoteEditor.kt:16)
	at com.ichi2.anki.NoteEditor.A(NoteEditor.kt)
	at com.ichi2.anki.d6.onClick(R8$$SyntheticClass)
	at android.view.View.performClick(View.java:5690)
	at android.view.View$PerformClick.run(View.java:22693)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6269)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

```
--------- beginning of main
11-19 23:42:44.581 E/AnkiDroid( 3259): CollectionManager/ blocked main thread for 2612ms:
11-19 23:42:44.581 E/AnkiDroid( 3259): com.ichi2.anki.services.BootService.getColSafe(BootService.kt:7)
11-19 23:42:47.458 E/AnkiDroid( 3259): CollectionManager/ blocked main thread for 1570ms:
11-19 23:42:47.458 E/AnkiDroid( 3259): com.ichi2.anki.DeckPicker.renderPage(DeckPicker.kt:352)
```

from https://ankidroid.org/acra/app/1/bug/25509/report/c0c6d923-ee20-466a-b806-7528b6cc2755

Looks like #12471 - so I will close this as a duplicate but tag you there and note it is still happening
