### ISSUE TITLE
[Bug] Crash when click the back button from the "SAVE TO FILE" page

### ISSUE THREAD

**Issue by Terrible-Tornado** [ankidroid/Anki-Android#12936]
**Android Version:** 9.0
**Device:** Google Pixel 2
**App Version:** 2.16alpha83

###### Reproduction Steps
1. Long click one of your deck
2. Click "Export deck"
3. Click "OK"
4. Click "SAVE TO FILE"
5. Click the back button on the phone
Then the app crashes.

Here is a short screen record video: 
https://user-images.githubusercontent.com/45310536/206442431-4d1e499a-b1e9-4e7a-83b3-584f9e345f84.mp4

###### Expected Result
Go back to the last page.

###### Actual Result
The app crashed.

###### Debug info
FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 24854
    java.lang.NullPointerException
        at com.ichi2.anki.export.ActivityExportingDelegate.saveFileCallback(ActivityExportingDelegate.kt:173)
        at com.ichi2.anki.export.ActivityExportingDelegate._init_$lambda-1(ActivityExportingDelegate.kt:218)
        at com.ichi2.anki.export.ActivityExportingDelegate.$r8$lambda$5wJEn7giKMDH6BaoHTtKNVhgGBw(Unknown Source:0)
        at com.ichi2.anki.export.ActivityExportingDelegate$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:4)
        at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:149)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:271)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:313)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:151)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:144)
        at androidx.lifecycle.ReportFragment.onStart(ReportFragment.java:109)
        at android.app.Fragment.performStart(Fragment.java:2548)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1334)
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1576)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1637)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3046)
        at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3003)
        at android.app.FragmentController.dispatchStart(FragmentController.java:193)
        at android.app.Activity.performStart(Activity.java:7165)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Yes - I think alpha83 is pretty old at this point and I *hope* this is fixed. We can always reopen if you reproduce on the current alpha. Thanks in general for alpha testing! We really appreciate it
