### ISSUE TITLE
[Bug] Cannot load deck from Ankiweb

### ISSUE THREAD

**Issue by gaul** [ankidroid/Anki-Android#13003]
###### Reproduction Steps

0. Clone and build Anki-Android using commit eec41075c0d6fa86a130559817d4d731af73de50
1. Start Android emulator
2. Sign in to Ankiweb and sync decks
3. Study deck

###### Expected Result

Deck loads and I can answer cards.

###### Actual Result

Deck does not load:

```
2022-12-18 20:14:08.786  6747-6747  DeckPicker              com.ichi2.anki                       I  DeckPicker:: Selected deck with id 1644669732957
2022-12-18 20:14:08.795  6747-6747  DeckPicker              com.ichi2.anki                       W  org.json.JSONException: No value for schedVer
                                                                                                    	at org.json.JSONObject.get(JSONObject.java:392)
                                                                                                    	at org.json.JSONObject.getInt(JSONObject.java:481)
                                                                                                    	at com.ichi2.libanki.Config.getInt(Config.kt:30)
                                                                                                    	at com.ichi2.libanki.Collection.get_config_int(Collection.kt:2291)
                                                                                                    	at com.ichi2.anki.DeckPicker.handleDeckSelection(DeckPicker.kt:2053)
                                                                                                    	at com.ichi2.anki.DeckPicker.onDeckClick(DeckPicker.kt:257)
                                                                                                    	at com.ichi2.anki.DeckPicker.mDeckClickListener$lambda$1(DeckPicker.kt:249)
                                                                                                    	at com.ichi2.anki.DeckPicker.$r8$lambda$92jiREjQw-Wv6zXMe3_aMT7flsk(Unknown Source:0)
                                                                                                    	at com.ichi2.anki.DeckPicker$$ExternalSyntheticLambda7.onClick(Unknown Source:2)
                                                                                                    	at android.view.View.performClick(View.java:6597)
                                                                                                    	at android.view.View.performClickInternal(View.java:6574)
                                                                                                    	at android.view.View.access$3100(View.java:778)
                                                                                                    	at android.view.View$PerformClick.run(View.java:25885)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6669)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2022-12-18 20:14:08.796  6747-6747  UsageAnalytics          com.ichi2.anki                       D  sendAnalyticsException() description/fatal: org.json.JSONException: No value for schedVer/false
2022-12-18 20:14:08.811  6747-6747  DeckPicker              com.ichi2.anki                       W  Failed to load deck ‘1644669732957’
```

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
Hey! Please provide us with the debug info as I am not able to reproduce the issue

**Comment by mikehardy** [comment]
Probably something to do with new backend stuff if there are JSON exceptions. You might see if you can reproduce on the latest code - you can get alpha builds here: https://github.com/ankidroid/Anki-Android/releases

**Comment by gaul** [comment]
This works on the latest release version in the Play store and fails with the latest master compiled locally.  I shared the backtrace from Android Studio but here are the missing debug log line:

```
2022-12-19 21:22:18.842  6747-6747  DeckPicker              com.ichi2.anki                       I  DeckPicker:: Selected deck with id 1663457569505
...
2022-12-19 21:22:18.858  6747-6747  UsageAnalytics          com.ichi2.anki                       D  sendAnalyticsException() description/fatal: org.json.JSONException: No value for schedVer/false
2022-12-19 21:22:18.871  6747-6747  DeckPicker              com.ichi2.anki                       W  Failed to load deck ‘1663457569505’
```

Let me know if I can help debug this further.  I use Ankiweb to sync my decks between multiple devices including this VM.  I cannot open any deck that was synced.

**Comment by criticalAY** [comment]
I meant your device debug from the settings tab in Ankidroid. I am having the latest built.

**Comment by gaul** [comment]
Here is the device debug info:

AnkiDroid Version = 2.16alpha91

Android Version = 9

Manufacturer = Google

Model = AOSP on IA Emulator

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 9; AOSP on IA Emulator Build/PSR1.180720.117; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Mobile Safari/537.36

ACRA UUID = 6d93074f-e103-4cd0-8e21-ea7b1620956f

New schema = false

Scheduler = std

Crash Reports Enabled = false

DatabaseV2 Enabled = true

**Comment by criticalAY** [comment]
I tried this on SDK28 but I could not reproduce it like you mentioned works fine for me

**Comment by mikehardy** [comment]
I wonder if going to settings advanced and turning on new schema / backend support and v3 scheduler it would work. That's a source of reproduction skew perhaps between you two

**Comment by gaul** [comment]
I checked the settings and "Use the new backend" is disabled.  I don't want to enable this since it warns that corruption could spread to AnkiWeb.

**Comment by gaul** [comment]
I am using these decks which seem to stress AnkiDroid (~100 MB each including sounds):

* https://ankiweb.net/shared/info/1585001017
* https://ankiweb.net/shared/info/1679429599

**Comment by david-allison** [comment]
Seeing this on 2.16alpha98: https://ankidroid.org/acra/app/1/bug/46248/report/6306a53a-0c22-41df-bd03-a95abeb8cb33

**Comment by david-allison** [comment]
@gaul Do you have reproduction steps which can be followed? (for example: a deck on AnkiWeb which will reproduce this). 

The links which you provided are inactive.

**Comment by david-allison** [comment]
I have been provided a copy of the collection privately. 

All decks fail with `Failed to load deck '<DeckId>'` when checked

`conf` JSON (prettified)
```json
{
  "dueCounts": true,
  "savedFilters": {},
  "activeCols": [
    "noteFld",
    "template",
    "cardDue",
    "deck"
  ],
  "activeDecks": [
    1450120394575
  ],
  "newSpread": 0,
  "newBury": true,
  "sortBackwards": false,
  "nightMode": false,
  "dayLearnFirst": false,
  "sortType": "cardReps",
  "timeLim": 0,
  "lastUnburied": 3542,
  "curDeck": 1450120394575,
  "localOffset": -120,
  "nextPOS": 3317,
  "collapseTime": 600,
  "curModel": 1376350068475,
  "estTimes": true,
  "nextPos": 993036,
  "AnkiDroidVersion": 20900177,
  "addToCur": true
}
```

**Comment by david-allison** [comment]
Likely cause: collection is still using SchedV1

https://github.com/ankidroid/Anki-Android/blob/a06e727f6094541b763e2dc18a300edb3e17fd26/AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedUpgradeTest.kt#L49-L51
