### ISSUE TITLE
[Bug] Crash: Downloading deck in background

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13085]
###### Reproduction Steps

1. Download Deck
2. Move App to Background
3. Unknown about anything more - **can't reproduce**

###### Expected Result

* no crash, some UI to show the download is finished, and I should switch back to the app

###### Actual Result

Logcat attached

```
2023-01-09 02:21:11.430 18201-18201 AndroidRuntime          com.ichi2.anki.debug                 E  FATAL EXCEPTION: main
                                                                                                    Process: com.ichi2.anki.debug, PID: 18201
                                                                                                    java.lang.IllegalStateException: Fragment ImportDialog{ea321ae} (722f8382-52c8-40f1-ba40-a1cafea7c624 tag=dialog) not attached to a context.
                                                                                                    	at androidx.fragment.app.Fragment.requireContext(Fragment.java:967)
                                                                                                    	at androidx.fragment.app.Fragment.getResources(Fragment.java:1031)
                                                                                                    	at com.ichi2.anki.dialogs.ImportDialog.getNotificationTitle(ImportDialog.kt:86)
                                                                                                    	at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.kt:510)
                                                                                                    	at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.kt:488)
                                                                                                    	at com.ichi2.anki.DeckPicker.showImportDialog(DeckPicker.kt:1413)
                                                                                                    	at com.ichi2.anki.dialogs.DialogHandler.handleMessage(DialogHandler.kt:56)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8741)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
2023-01-09 02:21:11.437 18201-18201 ACRA                    com.ichi2.anki.debug                 E  ACRA caught a IllegalStateException for com.ichi2.anki.debug
                                                                                                    java.lang.IllegalStateException: Fragment ImportDialog{ea321ae} (722f8382-52c8-40f1-ba40-a1cafea7c624 tag=dialog) not attached to a context.
                                                                                                    	at androidx.fragment.app.Fragment.requireContext(Fragment.java:967)
                                                                                                    	at androidx.fragment.app.Fragment.getResources(Fragment.java:1031)
                                                                                                    	at com.ichi2.anki.dialogs.ImportDialog.getNotificationTitle(ImportDialog.kt:86)
                                                                                                    	at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.kt:510)
                                                                                                    	at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.kt:488)
                                                                                                    	at com.ichi2.anki.DeckPicker.showImportDialog(DeckPicker.kt:1413)
                                                                                                    	at com.ichi2.anki.dialogs.DialogHandler.handleMessage(DialogHandler.kt:56)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8741)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

###### Debug info

AnkiDroid Version = 2.16alpha92

Android Version = 13

Manufacturer = samsung

Model = SM-G991B

Hardware = exynos2100

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-G991B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36

ACRA UUID = 0d021d4a-396d-41dc-bcf1-5f5ab3cda22a

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
I reproduced this issue and its coz of the fragment not being able to attach to the activity but it is not happening every time

**Comment by pratyaksh1610** [comment]
I am able to reproduce the issue, On my end it is happening each time we are switching to one or two apps and coming back to Ankidroid.
