### ISSUE TITLE
[Bug] 2.16 - "Disk Full" does not result in human-readable error

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13168]
###### Reproduction Steps

1. Fill up the Disk
2. Open AnkiDroid

###### Expected Result

A message informing the user of the problem

###### Actual Result

![Screenshot 2023-01-30 at 21 47 37](https://user-images.githubusercontent.com/62114487/215602695-2580d298-c20e-4526-935f-3c8f89eb65d1.png)

```
2023-01-30 21:45:37.094  3161-3161  CollectionHelper        com.ichi2.anki                       W  android.database.sqlite.SQLiteFullException: DbError { info: "SqliteFailure(Error { code: DiskFull, extended_code: 13 }, Some(\"database or disk is full\"))", kind: Other }
                                                                                                    	at net.ankiweb.rsdroid.Backend.openCollection(Backend.kt:111)
                                                                                                    	at net.ankiweb.rsdroid.Backend.openCollection(Backend.kt:61)
                                                                                                    	at com.ichi2.libanki.Storage.openDB$AnkiDroid_amazonDebug(Storage.kt:106)
                                                                                                    	at com.ichi2.libanki.Collection.reopen(Collection.kt:458)
                                                                                                    	at com.ichi2.libanki.Collection.reopen$default(Collection.kt:455)
                                                                                                    	at com.ichi2.libanki.Collection.<init>(Collection.kt:188)
                                                                                                    	at com.ichi2.libanki.Storage.collection(Storage.kt:88)
                                                                                                    	at com.ichi2.anki.CollectionManager.ensureOpenInner(CollectionManager.kt:225)
                                                                                                    	at com.ichi2.anki.CollectionManager.access$ensureOpenInner(CollectionManager.kt:36)
                                                                                                    	at com.ichi2.anki.CollectionManager$getColUnsafe$1$1.invoke(CollectionManager.kt:278)
                                                                                                    	at com.ichi2.anki.CollectionManager$getColUnsafe$1$1.invoke(CollectionManager.kt:277)
                                                                                                    	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:85)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

###### Debug info

Unable to obtain

Around `90810076313181dacd5f2fac84d9d84bc660f3c3`

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
I think this can be marked as a good first issue.

**Comment by david-allison** [comment]
Thanks! I believe we already have functionality for this, it's just no longer showing.
