### ISSUE TITLE
[Bug] AnkiDroid fails to start if external storage does not exist

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#13207]
###### Reproduction Steps

1. fire up a windows machine (windows 11 VM, Android 12 emulator, verified that `/sdcard/AnkiDroid` did not exist - that is, it is a clean install)
2. `gradlew.bat installPlayDebug`
3. attempt to start the app after install

###### Expected Result

App starts up

###### Actual Result

NullPointerException, the wicked `!!` strikes again...

Sincere apologies for the screenshot of the stacktrace, it's on a VM where I can't copy/paste the text for "reasons"

![image](https://user-images.githubusercontent.com/782704/217049538-444a9a17-bdd2-47cf-8d10-af4a7a7ef837.png)

But here's a link to the offender in attempt to make up for it: https://github.com/ankidroid/Anki-Android/blob/bc6caf9d9e199e8f295d49c27bbb4fbfd859f183/AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt#L492

I did get a toast saying "Device Storage Not Mounted" and the app quit, after uninstalling / reinstalling / granting storage permission

What if there is no external storage though? Should I be able to use AnkiDroid on only internal storage? That could be a valid device configuration ?

Storage config looks like this:

![image](https://user-images.githubusercontent.com/782704/217051806-13e4b041-0cda-4a42-bd88-3b61e82527bc.png)

There is supposed to be a 768MB sdcard in the AVD definition but it appears it is not mounted, this shows up in logs:

> StorageManagerService  system_process  W No primary storage defined yet; hacking together a stub

It is possible this configuration is simply invalid (are there any android devices that have no "external" storage?) as I am unable to run the storage system preferences app either (`Volume external_primary not found`)

But might be worth a look / some better messaging in case something like this is out in the wild.

I'll purge this AVD and try a different one

###### Debug info

Just one commit back on main at the moment - was built from this commit sha https://github.com/ankidroid/Anki-Android/commit/4cb853c1e10cd95669f810e5987c6ef7a7cf1918

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
After wiping the AVD and associated external storage, then recreating it, things appeared to work and `df -kh` shows the external storage mounted.

So it is likely possible to reproduce this on any emulator where you  have no external storage configured.

There is the open question: Is this a valid configuration? Is external storage *always* there or is it possible some devices have no external storage and AnkiDroid should "just work" anyway?

If it is valid to have a device with no external storage then we should have a fallback directory. If it is not valid, then we should have better user messaging perhaps?

**Comment by n1snt** [comment]
I reported a similar issue a while back, but this bug only occurred on Android 5.0.
https://github.com/ankidroid/Anki-Android/issues/11235

**Comment by mikehardy** [comment]
@n1snt indeed! Forgot about that one. This is still in an AVD so I guess to start it is a research question -

> There is the open question: Is this a valid configuration? Is external storage always there or is it possible some devices have no external storage and AnkiDroid should "just work" anyway?

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/issues/13705 opens a concern that /some/ of the elements may be null.

I vote that we handle and fix this.

**Comment by david-allison** [comment]
Still an issue in 2.21

https://ankidroid.org/acra/app/1/bug/313305/report/dfd598d6-b1b2-4838-a728-24ce27c23845

```
java.lang.RuntimeException: Unable to create application com.ichi2.anki.AnkiDroidApp: java.lang.IllegalStateException: getExternalFilesDir unexpectedly returned null. Media state: removed
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:8269)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2649)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loopOnce(Looper.java:288)
	at android.os.Looper.loop(Looper.java:393)
	at android.app.ActivityThread.main(ActivityThread.java:9549)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1005)
Caused by: java.lang.IllegalStateException: getExternalFilesDir unexpectedly returned null. Media state: removed
	at com.ichi2.anki.Channel.o(NotificationChannels.kt:59)
	at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.kt:203)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1404)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:8261)
	... 9 more

```

**Comment by david-allison** [comment]
`OnePlus 13`

```
ENVIRONMENT
getDataDirectory
/data
getDataSystemDirectory
/data/system
getDownloadCacheDirectory
/data/cache
getExternalStorageDirectory
/sdcard
getExternalStorageState
removed
getInternalMediaDirectories
[/system/media, /oem/media, /product/media, /system_ext/media/audio/dynamic/notifications, /system_ext/media/audio/ui, /system_ext/media/audio/alarms, /my_stock/media/audio/dynamic/notifications, /my_stock/media/audio/ui/Usb.ogg, /my_stock/media/audio/ui/VolumePanelSound.ogg, /my_stock/media/audio/ui/WheelPicker.ogg, /my_stock/media/audio/ui/camera_click.wav, /my_stock/media/audio/ui/charge.mp3, /my_stock/media/audio/ui/cover.mp3, /my_stock/media/audio/ui/critical_lowbattery.ogg, /my_stock/media/audio/ui/delete.mp3, /my_stock/media/audio/ui/delete3.mp3, /my_stock/media/audio/ui/dew.wav, /my_stock/media/audio/ui/ebook_open.mp3, /my_stock/media/audio/ui/ebook_open2.mp3, /my_stock/media/audio/ui/ebook_page1.mp3, /my_stock/media/audio/ui/ebook_page3.mp3, /my_stock/media/audio/ui/error.mp3, /my_stock/media/audio/ui/extended_effect_a.ogg, /my_stock/media/audio/ui/extended_effect_b.ogg, /my_stock/media/audio/ui/extended_effect_c.ogg, /my_stock/media/audio/ui/extended_effect_d.ogg, /my_stock/media/audio/ui/extended_effect_e.ogg, /my_stock/media/audio/ui/full_battery.ogg, /my_stock/media/audio/ui/global_delete.ogg, /my_stock/media/audio/ui/inefficacy.mp3, /my_stock/media/audio/ui/lomo_click.mp3, /my_stock/media/audio/ui/lowbattery.mp3, /my_stock/media/audio/ui/machine.mp3, /my_stock/media/audio/ui/mechanism_down.ogg, /my_stock/media/audio/ui/mechanism_up.ogg, /my_stock/media/audio/ui/normal_lowbattery.ogg, /my_stock/media/audio/ui/numberpicker_click.ogg, /my_stock/media/audio/ui/powerlow.mp3, /my_stock/media/audio/ui/poweroff.mp3, /my_stock/media/audio/ui/poweron.mp3, /my_stock/media/audio/ui/pure_music_down.ogg, /my_stock/media/audio/ui/pure_music_up.ogg, /my_stock/media/audio/ui/slight_feedback.ogg, /my_stock/media/audio/ui/sound_10s.mp3, /my_stock/media/audio/ui/sound_5s.mp3, /my_stock/media/audio/ui/technology_down.ogg, /my_stock/media/audio/ui/technology_up.ogg, /my_stock/media/audio/ui/touch.mp3, /my_stock/media/audio/ui/touch2.mp3, /my_stock/media/audio/ui/touch3.mp3, /my_stock/media/audio/ui/uncover.mp3, /my_stock/media/audio/ui/warning3.mp3, /my_stock/media/audio/ui/warrning.mp3, /my_stock/media/audio/alarms, /my_product/media, /my_region/media, /my_carrier/media, /my_company/media, /my_bigball/media, /data/theme/ring, /data/theme/audio, /data/theme/applying, /data/oplus/multimedia/ringtones, /data/oplus/multimedia/notifications, /data/oplus/multimedia/ui, /data/oppo/multimedia/ringtones, /data/oppo/multimedia/notifications, /data/oppo/multimedia/ui]
getLegacyExternalStorageDirectory
/sdcard
getMyBigballDirectory
/my_bigball
getMyCarrierDirectory
/my_carrier
getMyCompanyDirectory
/my_company
getMyCountryDirectory
/my_region
getMyEngineeringDirectory
/my_engineering
getMyHeytapDirectory
/my_heytap
getMyOperatorDirectory
/my_carrier
getMyPreloadDirectory
/my_preload
getMyProductDirectory
/my_product
getMyRegionDirectory
/my_region
getMyStockDirectory
/my_stock
getOdmDirectory
/odm
getOemDirectory
/oem
getOplusCotaDirectory
/my_carrier
getOplusCustomDirectory
/my_company
getOplusEngineerDirectory
/my_engineering
getOplusProductDirectory
/my_product
getOplusVersionDirectory
/oplus_version
getProductDirectory
/product
getProductServicesDirectory
/product_services
getReserveDirectory
/mnt/vendor/oplusreserve
getResourceDirectory
/my_company
getRootDirectory
/system
getStorageDirectory
/storage
getSystemExtDirectory
/system_ext
getVendorDirectory
/vendor
isExternalStorageEmulated
true
isExternalStorageLegacy
false
isExternalStorageManager
false
isExternalStorageRemovable
false
isOplusCotaDirectoryEmpty
false
isOplusCustomDirectoryEmpty
false
isWhiteListMcp
false
FILE_PATH
/data/user/0/com.ichi2.anki/files
INSTALLATION_ID
ff758040-1afd-482d-b874-d557313fcf33
IS_SILENT
false
LOGCAT
--------- beginning of main
06-22 13:56:48.706 I/AnkiDroid(22307): Reviewer::onPause
06-22 13:56:48.706 I/AnkiDroid(22307): stop: automatically show answer
06-22 13:56:48.706 I/AnkiDroid(22307): stop: automatically show question
06-22 13:56:48.722 I/AnkiDroid(22307): Reviewer::onStop
06-22 13:56:48.725 I/AnkiDroid(22307): Reviewer::onSaveInstanceState
06-22 13:56:50.369 I/AnkiDroid(23020): Timber config: PRODUCTION
06-22 13:56:50.369 I/AnkiDroid(23020): initialize()
06-22 13:56:50.418 I/AnkiDroid(23020): Not participating in analytics sample (sample percentage vs random: 10 96)
06-22 13:56:50.418 I/AnkiDroid(23020): setOptIn(): from false to false
06-22 13:56:50.418 I/AnkiDroid(23020): Not participating in analytics sample (sample percentage vs random: 10 86)
06-22 13:56:50.418 I/AnkiDroid(23020): initialize()
06-22 13:56:50.420 I/AnkiDroid(23020): Creating notification channel with id/name: General Notifications/AnkiDroid
06-22 13:56:50.420 I/AnkiDroid(23020): Creating notification channel with id/name: Synchronization/Synchronization
06-22 13:56:50.420 I/AnkiDroid(23020): Creating notification channel with id/name: Global Reminders/Cards due
06-22 13:56:50.420 I/AnkiDroid(23020): Creating notification channel with id/name: Deck Reminders/Reminders
06-22 13:56:50.422 E/AnkiDroid(23020): Instrumentation/ Could not initialize AnkiDroid directory
06-22 13:56:50.422 E/AnkiDroid(23020): d4.a: Failed to create AnkiDroid directory /storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid
06-22 13:56:50.422 E/AnkiDroid(23020): 	at M3.f3.r(SourceFile:34)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at com.ichi2.anki.AnkiDroidApp.onCreate(SourceFile:629)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1404)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:8261)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2649)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at android.os.Handler.dispatchMessage(Handler.java:112)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at android.os.Looper.loopOnce(Looper.java:288)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at android.os.Looper.loop(Looper.java:393)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at android.app.ActivityThread.main(ActivityThread.java:9549)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at java.lang.reflect.Method.invoke(Native Method)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1005)
06-22 13:56:50.422 E/AnkiDroid(23020): 
06-22 13:56:50.422 E/AnkiDroid(23020): d4.a: Failed to create AnkiDroid directory /storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid
06-22 13:56:50.422 E/AnkiDroid(23020): 	at M3.f3.r(SourceFile:34)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at com.ichi2.anki.AnkiDroidApp.onCreate(SourceFile:629)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1404)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:8261)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2649)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at android.os.Handler.dispatchMessage(Handler.java:112)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at android.os.Looper.loopOnce(Looper.java:288)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at android.os.Looper.loop(Looper.java:393)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at android.app.ActivityThread.main(ActivityThread.java:9549)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at java.lang.reflect.Method.invoke(Native Method)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
06-22 13:56:50.422 E/AnkiDroid(23020): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1005)
06-22 13:56:50.424 E/AnkiDroid(23020): AnkiDroidApp/ Attempting to determine collection path, but no valid external storage?
```

```
MANUFACTURER OnePlus
MODEL CPH2653
```

**Comment by sujjethog-ops** [comment]
@criticalAY can I take this issue

**Comment by david-allison** [comment]
Report on Reddit: https://www.reddit.com/r/Anki/comments/1opccqk/unable_to_run_ankidroid_or_clear_storage_on_a_new/

----

I suspect this is related to the following, given similar activity on ACRA:

> Android/data directory corrupted after Pixel-to-Pixel migration (Android 16) — apps cannot create external private storage directories

https://issuetracker.google.com/issues/460912704

**Comment by mikehardy** [comment]
AnkiDroid not starting is a problem, but I'm not sure how we can start in this case unless we decide to use another directory as a workaround (where that location will be a workaround for a likely temporary issue but will become a permanent location for that device...)

Is that something we want to pursue?

I've added my voice to that issue though, I believe that issuetracker issue you linked is a great representation of the problem

**Comment by david-allison** [comment]
Biggest crasher on Pixel devices.

I'd use the same flow as we do with the 'WebView inaccessible' issue.

* Add a test to be sure the app starts with `getExternalFilesDir => null`
* Inform the user their phone is in a bad state
  *  Maybe special-case Pixels, as this is a known cause of the bug, possibly linking this issue with workarounds
      * If it's only AnkiDroid, I believe they can install `Parallel.A` - one user said that installing an alpha worked (?)
         * EDIT: since `getExternalStorageDirectory` still works, some of the app would work here 
      * If they can wait, hopefully Google will take the bug report seriously
      * If not, it's likely a newly bought phone and "factory reset + don't restore from the old phone" is the only reasonable option

If I were a user, I'd want to know that it's my phone being buggy, and not AnkiDroid

**Comment by mikehardy** [comment]
agreed on all that in particular the quick special case for it - if this is going to require a factory reset (and I bet it will even for a google fix, for phones already affected!) - pointer to upstream issue and user education is the only bet that seems like it will have a payoff, with the cost of "only" some dialog coding here

**Comment by david-allison** [comment]
In the following examples, and in all crash reports I checked, AnkiDroid Directory is not defined

I will defer handling the case where `getExternalFilesDir` now returns `null`, but AnkiDroid Directory is valid

----

https://ankidroid.org/acra/app/1/bug/338919/report/d5d277b5-8fdb-4f04-b8ed-6d28b287056b

```
java.lang.RuntimeException: Unable to start receiver com.ichi2.anki.services.BootService
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:5097)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2584)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.dispatchMessage(Looper.java:315)
	at android.os.Looper.loopOnce(Looper.java:251)
	at android.os.Looper.loop(Looper.java:349)
	at android.app.ActivityThread.main(ActivityThread.java:9041)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:929)
Caused by: java.lang.IllegalStateException: getExternalFilesDir unexpectedly returned null. Media state: mounted
	at O3.X2.m(SourceFile:59)
	at O3.W2.get(SourceFile:26)
	at x8.e.u(SourceFile:19)
	at O3.x1.w(SourceFile:26)
	at com.ichi2.anki.services.BootService.onReceive(SourceFile:56)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:5090)
	... 10 more
```

https://ankidroid.org/acra/app/1/bug/325452/report/cfd04e0e-1073-4042-8707-3916f2059d43

```
java.lang.IllegalStateException: getExternalFilesDir unexpectedly returned null. Media state: mounted
	at com.ichi2.anki.CollectionHelper.getAppSpecificExternalAnkiDroidDirectory(CollectionHelper.kt:227)
	at com.ichi2.anki.CollectionHelper.getDefaultAnkiDroidDirectory(CollectionHelper.kt:184)
	at com.ichi2.anki.CollectionHelper.getCurrentAnkiDroidDirectoryOptionalContext$lambda$2(CollectionHelper.kt:301)
	at com.ichi2.preferences.PreferenceExtensionsKt.getOrSetString(PreferenceExtensions.kt:39)
	at com.ichi2.anki.CollectionHelper.getCurrentAnkiDroidDirectoryOptionalContext$AnkiDroid_fullRelease(CollectionHelper.kt:300)
	at com.ichi2.anki.CollectionManager.getCollectionDirectory(CollectionManager.kt:292)
	at com.ichi2.anki.CollectionManager.collectionPathInValidFolder(CollectionManager.kt:297)
	at com.ichi2.anki.CollectionManager.ensureOpenInner(CollectionManager.kt:273)
	at com.ichi2.anki.CollectionManager.getColUnsafe$lambda$12$lambda$11(CollectionManager.kt:332)
	at com.ichi2.anki.CollectionManager$withQueue$3.invokeSuspend(CollectionManager.kt:128)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
```
