### ISSUE TITLE
[Bug] IllegalStateException when opening settings after migration

### ISSUE THREAD

**Issue by doozan** [ankidroid/Anki-Android#13216]
###### Reproduction Steps

1. Click Migrate
2. Wait for migration to complete (no notification, but the sync icon disappears)
3. Open settings | Advanced (to see if the path has indeed changed)

###### Expected Result

Settings page opens

###### Actual Result
![Screenshot_20230207-084825_AnkiDroidB](https://user-images.githubusercontent.com/409080/217316593-a005562d-6d39-4593-bb3e-145f251c320c.jpg)

###### Debug info
```

AnkiDroid Version = 2.16alpha93

Android Version = 12

Manufacturer = samsung

Model = SM-G970U

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-G970U Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = f9d003f3-ae34-4529-8cd5-ed8aff42fa30

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
This isn't happening in my case, have tested it out multiples times :)

**Comment by BrayanDSO** [comment]
```
java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{7fdb239 VFED.V... ......ID 0,0-1080,2005 #7f090358 app:id/recycler_view}, adapter:androidx.preference.PreferenceGroupAdapter@23279df, layout:androidx.recyclerview.widget.LinearLayoutManager@21a062c, context:com.ichi2.anki.preferences.Preferences@e3fbb17
	at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:32)
	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeChanged(RecyclerView.java:4)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:3)
	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemChanged(RecyclerView.java:2)
	at androidx.preference.PreferenceGroupAdapter.onPreferenceChange(PreferenceGroupAdapter.java:10)
	at androidx.preference.Preference.notifyChanged(Preference.java:5)
	at androidx.preference.TwoStatePreference.setChecked(TwoStatePreference.java:31)
	at com.ichi2.anki.preferences.AdvancedSettingsFragment$initSubscreen$v3schedPref$1$1$1.invoke(AdvancedSettingsFragment.kt:2)
	at com.ichi2.anki.preferences.AdvancedSettingsFragment$initSubscreen$v3schedPref$1$1$1.invoke(AdvancedSettingsFragment.kt:1)
	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:3)
	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:1)
	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
```

**Comment by BrayanDSO** [comment]
Not a crash and doesn't impedes anything, just a warning, so I'll remove the high priority
