### ISSUE TITLE
[Bug] MigrationService: ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground() 

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13299]
Bug occurred after migration

###### Reproduction Steps

1. Migration Completed
2. ???
3. Open Deck Picker

###### Expected Result

No Crash

###### Actual Result

Crash dialog shown

```
2023-02-19 00:09:30.499 15853-15853 AndroidRuntime          com.ichi2.anki.debug                 E  FATAL EXCEPTION: main
                                                                                                    Process: com.ichi2.anki.debug, PID: 15853
                                                                                                    android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{3504704 u0 com.ichi2.anki.debug/com.ichi2.anki.services.MigrationService}
                                                                                                    	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1923)
                                                                                                    	at android.app.ActivityThread.access$2700(ActivityThread.java:247)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2148)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2023-02-19 00:09:30.500 15853-15853 UsageAnalytics          com.ichi2.anki.debug                 D  sendAnalyticsException() description/fatal: android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{3504704 u0 com.ichi2.anki.debug/com.ichi2.anki.services.MigrationService}/true
2023-02-19 00:09:30.503 15853-15853 ACRA                    com.ichi2.anki.debug                 E  ACRA caught a ForegroundServiceDidNotStartInTimeException for com.ichi2.anki.debug
                                                                                                    android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{3504704 u0 com.ichi2.anki.debug/com.ichi2.anki.services.MigrationService}
                                                                                                    	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1923)
                                                                                                    	at android.app.ActivityThread.access$2700(ActivityThread.java:247)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2148)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

###### Debug info
```
AnkiDroid Version = 2.16alpha93-debug

Android Version = 12

Manufacturer = unknown

Model = Android SDK built for arm64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 12; Android SDK built for arm64 Build/SE1A.220621.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.114 Mobile Safari/537.36

ACRA UUID = deec9d9f-4987-4118-b2ba-a8b63350092f

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

```

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
[13299.txt](https://github.com/ankidroid/Anki-Android/files/10775440/13299.txt)

**Comment by rishujam** [comment]
What does migration mean here. Update?

**Comment by david-allison** [comment]
Moving the user collection from `/AnkiDroid` to `/Android/data/com.ichi2.anki/files/AnkiDroid[1]`

**Comment by rishujam** [comment]
Thankyou very much

**Comment by oakkitten** [comment]
Probable solution in https://github.com/ankidroid/Anki-Android/pull/13219#issuecomment-1445148379
