### ISSUE TITLE
[BUG]: automated sync lead to "collection not open"

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13429]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

* Install a recent issue
* have an account connected to ankiweb
* enable automated sync
* close the app
* wait enough to trigger a sync on start (I think it's 10 minutes)
* open the app

### Expected behaviour

Sync, then a usable app. Or at least in case of error, just a forced restart and a working app.

### Actual behaviour

"Collection not opened" appear while the sync occur.

Sometime instead, I got a SQL error message before the Collection not opened.

Also, if I just press okay, I get the warning message every 20 seconds or so the the app is not responding, while the app actually works perfectly as long as I press on the "wait" button.

### Debug info

```text
AnkiDroid Version = 2.16alpha93-debug

Android Version = 13

Manufacturer = samsung

Model = SM-A226B

Hardware = mt6833

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A226B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/110.0.5481.65 Mobile Safari/537.36

ACRA UUID = a2af6a9d-da31-4e59-bb5d-ff252cd2826d

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

If I accept the android message to force quit the app and restart it it works as expected. If I stop the automated sync, it works correctly.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
Ehh debug alpha93 we are on 94 no?

**Comment by criticalAY** [comment]
I have reproduced this and found the cause I am testing it and will push the code after that

**Comment by Arthur-Milchior** [comment]
Actually, it’s still occurring. I thought it was resolved, but after closing, waiting and reopening the app, I’ve got it again.

**Comment by criticalAY** [comment]
That shouldn't have happened even though I tested it out multiple times could you share the logcat if possible

**Comment by Arthur-Milchior** [comment]
I'll try if I get it.
I'm on phone right now

One big difference,: I only get the collection not opened error message once.
I don't get the warning that ankidroid is not responding anymore, I'm not getting asked to close it every five seconds. So Ankidroid is usable at least

**Comment by criticalAY** [comment]
I have also set the auto sync on and will see if it can be reproduced though I tried it even after you reported that it is still there but the collection get synced perfectly on my end

**Comment by Arthur-Milchior** [comment]
I suspect it might be related. Looking at logcat, I got thousands of lines of the kind
> 
W/Backend$checkMainThreadOp: SELECT count() FROM (SELECT 1 FROM cards WHERE did = ? AND queue = 0 LIMIT ?)
W/Backend$checkMainThreadOp: Op on UI thread: com.ichi2.anki.services.ReminderService.getDeckOptionDue(ReminderService.kt:144)
W/Backend$checkMainThreadOp: Op on UI thread: com.ichi2.anki.services.ReminderService.getDeckOptionDue(ReminderService.kt:144)
W/Backend$checkMainThreadOp: Op on UI thread: com.ichi2.anki.services.ReminderService.getDeckOptionDue(ReminderService.kt:144)
W/Backend$checkMainThreadOp: SELECT count() FROM (SELECT null FROM cards WHERE did = ? AND queue = 1 AND due < ? LIMIT ?)
W/Backend$checkMainThreadOp: Op on UI thread: com.ichi2.anki.services.ReminderService.getDeckOptionDue(ReminderService.kt:144)
W/Backend$checkMainThreadOp: Op on UI thread: com.ichi2.anki.services.ReminderService.getDeckOptionDue(ReminderService.kt:144)
W/Backend$checkMainThreadOp: Op on UI thread: com.ichi2.anki.services.ReminderService.getDeckOptionDue(ReminderService.kt:144)
W/Backend$checkMainThreadOp: SELECT count() FROM (SELECT null FROM cards WHERE did = ? AND queue = 3 AND due <= ? LIMIT ?)
W/Backend$checkMainThreadOp: Op on UI thread: com.ichi2.anki.services.ReminderService.getDeckOptionDue(ReminderService.kt:144)
W/Backend$checkMainThreadOp: Op on UI thread: com.ichi2.anki.services.ReminderService.getDeckOptionDue(ReminderService.kt:144)
W/Backend$checkMainThreadOp: Op on UI thread: com.ichi2.anki.services.ReminderService.getDeckOptionDue(ReminderService.kt:144)
W/Backend$checkMainThreadOp: SELECT count() FROM (SELECT 1 FROM cards WHERE did in (1634515539707) AND queue = 2 AND due <= ? LIMIT ?)
W/Backend$checkMainThreadOp: Op on UI thread: com.ichi2.anki.services.ReminderService.getDeckOptionDue(ReminderService.kt:144)
W/Backend$checkMainThreadOp: Op on UI thread: com.ichi2.anki.services.ReminderService.getDeckOptionDue(ReminderService.kt:144)

**Comment by Arthur-Milchior** [comment]
Yeah, after a third try, I got the exception

```
2023-03-20 23:19:41.965 25380-25380 CoroutineHelpersKt      com.ichi2.anki.debug                 E  java.lang.RuntimeException: android.database.sqlite.SQLiteException: error while compiling: "SELECT count() FROM (SELECT null FROM cards WHERE did = ? AND queue = 1 AND due < ? LIMIT ?)": CollectionNotOpen
                                                                                                    	at com.ichi2.libanki.sched.SchedV2._lrnForDeck(SchedV2.kt:1444)
                                                                                                    	at com.ichi2.libanki.sched.SchedV2.deckDueList(SchedV2.kt:479)
                                                                                                    	at com.ichi2.libanki.sched.SchedV2.deckDueTree(SchedV2.kt:530)
                                                                                                    	at com.ichi2.anki.DeckPicker$updateDeckList$2$1$deckData$1.invoke(DeckPicker.kt:1837)
                                                                                                    	at com.ichi2.anki.DeckPicker$updateDeckList$2$1$deckData$1.invoke(DeckPicker.kt:1837)
                                                                                                    	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:97)
                                                                                                    	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:95)
                                                                                                    	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:83)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    Caused by: android.database.sqlite.SQLiteException: error while compiling: "SELECT count() FROM (SELECT null FROM cards WHERE did = ? AND queue = 1 AND due < ? LIMIT ?)": CollectionNotOpen
                                                                                                    	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.kt:259)
                                                                                                    	at net.ankiweb.rsdroid.database.RustSupportSQLiteDatabase.query(RustSupportSQLiteDatabase.kt:103)
                                                                                                    	at com.ichi2.utils.DatabaseChangeDecorator.query(Unknown Source:16)
                                                                                                    	at com.ichi2.libanki.DB.queryScalar(DB.kt:122)
                                                                                                    	at com.ichi2.libanki.sched.SchedV2._lrnForDeck(SchedV2.kt:1427)
                                                                                                    	at com.ichi2.libanki.sched.SchedV2.deckDueList(SchedV2.kt:479) 
                                                                                                    	at com.ichi2.libanki.sched.SchedV2.deckDueTree(SchedV2.kt:530) 
                                                                                                    	at com.ichi2.anki.DeckPicker$updateDeckList$2$1$deckData$1.invoke(DeckPicker.kt:1837) 
                                                                                                    	at com.ichi2.anki.DeckPicker$updateDeckList$2$1$deckData$1.invoke(DeckPicker.kt:1837) 
                                                                                                    	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:97) 
                                                                                                    	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:95) 
                                                                                                    	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:83) 
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) 
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) 
                                                                                                    Caused by: net.ankiweb.rsdroid.exceptions.BackendInvalidInputException$BackendCollectionNotOpenException: CollectionNotOpen
                                                                                                    	at net.ankiweb.rsdroid.exceptions.BackendInvalidInputException$Companion.fromInvalidInputError(BackendInvalidInputException.kt:35)
                                                                                                    	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:114)
                                                                                                    	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:323)
                                                                                                    	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
                                                                                                    	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:130)
                                                                                                    	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:129)
                                                                                                    	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:157)
                                                                                                    	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:129)
                                                                                                    	at anki.backend.GeneratedBackend.runDbCommandProtoRaw(GeneratedBackend.kt:1699)
                                                                                                    	at anki.backend.GeneratedBackend.runDbCommandProto(GeneratedBackend.kt:1709)
                                                                                                    	at net.ankiweb.rsdroid.Backend.fullQueryProto(Backend.kt:223)
                                                                                                    	at net.ankiweb.rsdroid.database.Session.fullQueryProto(Session.kt:79)
                                                                                                    	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.kt:255)
                                                                                                    	at net.ankiweb.rsdroid.database.RustSupportSQLiteDatabase.query(RustSupportSQLiteDatabase.kt:103) 
                                                                                                    	at com.ichi2.utils.DatabaseChangeDecorator.query(Unknown Source:16) 
                                                                                                    	at com.ichi2.libanki.DB.queryScalar(DB.kt:122) 
                                                                                                    	at com.ichi2.libanki.sched.SchedV2._lrnForDeck(SchedV2.kt:1427) 
                                                                                                    	at com.ichi2.libanki.sched.SchedV2.deckDueList(SchedV2.kt:479) 
                                                                                                    	at com.ichi2.libanki.sched.SchedV2.deckDueTree(SchedV2.kt:530) 
                                                                                                    	at com.ichi2.anki.DeckPicker$updateDeckList$2$1$deckData$1.invoke(DeckPicker.kt:1837) 
                                                                                                    	at com.ichi2.anki.DeckPicker$updateDeckList$2$1$deckData$1.invoke(DeckPicker.kt:1837) 
                                                                                                    	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:97) 
                                                                                                    	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:95) 
                                                                                                    	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:83) 
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) 
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) 
```

**Comment by Arthur-Milchior** [comment]
```
2023-03-28 07:55:26.240 15616-15616 CoroutineHelpersKt      com.ichi2.anki.debug                 E  net.ankiweb.rsdroid.exceptions.BackendInvalidInputException$BackendCollectionNotOpenException: CollectionNotOpen
    at net.ankiweb.rsdroid.exceptions.BackendInvalidInputException$Companion.fromInvalidInputError(BackendInvalidInputException.kt:35)
    at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:114)
    at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:323)
    at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
    at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:130)
    at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:129)
    at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:157)
    at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:129)
    at anki.backend.GeneratedBackend.flushQueryRaw(GeneratedBackend.kt:1780)
    at anki.backend.GeneratedBackend.flushQuery(GeneratedBackend.kt:1790)
    at net.ankiweb.rsdroid.Backend.cancelCurrentProtoQuery(Backend.kt:231)
    at net.ankiweb.rsdroid.database.Session.cancelCurrentProtoQuery(Session.kt:83)
    at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.close(StreamingProtobufSQLiteCursor.kt:201)
    at com.ichi2.libanki.DB.queryScalar(DB.kt:128)
    at com.ichi2.libanki.sched.SchedV2._lrnForDeck(SchedV2.kt:1427)
    at com.ichi2.libanki.sched.SchedV2.deckDueList(SchedV2.kt:479)
    at com.ichi2.libanki.sched.SchedV2.deckDueTree(SchedV2.kt:530)
    at com.ichi2.anki.DeckPicker$updateDeckList$2$1$deckData$1.invoke(DeckPicker.kt:1824)
    at com.ichi2.anki.DeckPicker$updateDeckList$2$1$deckData$1.invoke(DeckPicker.kt:1823)
    at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:97)
    at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:95)
    at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:83)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```


Sorry, just updated to main, and still got a CollectionNotOpen error message on start when it syncs

**Comment by Arthur-Milchior** [comment]
The crash I just had, on startup after autosync, seems similar

```
net.ankiweb.rsdroid.exceptions.BackendInvalidInputException$BackendCollectionNotOpenException: CollectionNotOpen
                                                                                                    	at net.ankiweb.rsdroid.exceptions.BackendInvalidInputException$Companion.fromInvalidInputError(BackendInvalidInputException.kt:35)
                                                                                                    	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:114)
                                                                                                    	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:323)
                                                                                                    	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
                                                                                                    	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:130)
                                                                                                    	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:129)
                                                                                                    	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:157)
                                                                                                    	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:129)
                                                                                                    	at anki.backend.GeneratedBackend.flushQueryRaw(GeneratedBackend.kt:1780)
                                                                                                    	at anki.backend.GeneratedBackend.flushQuery(GeneratedBackend.kt:1790)
                                                                                                    	at net.ankiweb.rsdroid.Backend.cancelCurrentProtoQuery(Backend.kt:231)
                                                                                                    	at net.ankiweb.rsdroid.database.Session.cancelCurrentProtoQuery(Session.kt:83)
                                                                                                    	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.close(StreamingProtobufSQLiteCursor.kt:201)
                                                                                                    	at kotlin.io.CloseableKt.closeFinally(Closeable.kt:56)
                                                                                                    	at com.ichi2.libanki.Collection.loadColumn(Collection.kt:346)
                                                                                                    	at com.ichi2.libanki.Collection.initModels(Collection.kt:236)
                                                                                                    	at com.ichi2.libanki.Collection.getModels(Collection.kt:2247)
                                                                                                    	at com.ichi2.anki.CollectionHelper$Companion.loadCollectionComplete(CollectionHelper.kt:577)
                                                                                                    	at com.ichi2.anki.DeckPicker$refreshState$1$1.invoke(DeckPicker.kt:964)
                                                                                                    	at com.ichi2.anki.DeckPicker$refreshState$1$1.invoke(DeckPicker.kt:964)
                                                                                                    	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:97)
                                                                                                    	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:95)
                                                                                                    	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:83)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by Arthur-Milchior** [comment]
Currently, my best guess is that we should ensure that, while a cursor is active, we can't close the collection. Same as when a coroutine is executed `withCol`.
The trouble is that cursor are known on the back-end, so I guess it is the back-end that must deal with ensuring the col is not closed. I'm currently trying to learn how to compile with back-end, so that I can test. But I don't think we should try to do this before release. As I'm the only one with the collection with a bug, that the fix is easy (don't auto sync), I guess we can temporarily ship with such a bug. It's better than try to fix in emergency and risk crashing every device that uses cursor (that is, all devices)

**Comment by Arthur-Milchior** [comment]
Since teh problem is with `loadModel`, I suspect that you may be able to reproduce it with a `model` json that is more than 2MB long. You can easily create this by adding a string with, let's say, 4 millions character, in one template

**Comment by Arthur-Milchior** [comment]
As suggested by @david-allison 
If I do
```
diff --git a/AnkiDroid/src/main/java/com/ichi2/async/Connection.kt b/AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
index 26a8c999bb..2b227df5ef 100644
--- a/AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
+++ b/AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
@@ -24,6 +24,7 @@ import android.os.PowerManager
 import android.os.PowerManager.WakeLock
 import com.ichi2.anki.AnkiDroidApp
 import com.ichi2.anki.CollectionHelper
+import com.ichi2.anki.CollectionManager
 import com.ichi2.anki.CrashReportService
 import com.ichi2.anki.R
 import com.ichi2.anki.exception.MediaSyncException
@@ -455,7 +456,7 @@ class Connection : BaseAsyncTask<Connection.Payload, Any, Connection.Payload>()
         } finally {
             Timber.i("Sync Finished - Closing Collection")
             // don't bump mod time unless we explicitly save
-            col?.close(false)
+            CollectionManager.closeCollectionBlocking(false)
             CollectionHelper.instance.unlockCollection()
         }
```

I obtain 

> 2023-04-23 15:32:41.399 28715-28715 CoroutineHelpersKt      com.ichi2.anki.debug                 E  android.database.sqlite.SQLiteException: error while compiling: "select 1 from cards where did = 1": CollectionNotOpen
>                                                                                                     	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.kt:259)
>                                                                                                     	at net.ankiweb.rsdroid.database.RustSupportSQLiteDatabase.query(RustSupportSQLiteDatabase.kt:103)
>                                                                                                     	at com.ichi2.utils.DatabaseChangeDecorator.query(Unknown Source:16)
>                                                                                                     	at com.ichi2.libanki.DB.queryScalar(DB.kt:118)
>                                                                                                     	at com.ichi2.anki.servicelayer.DeckService.defaultDeckHasCards(DeckService.kt:34)
>                                                                                                     	at com.ichi2.anki.widgets.DeckAdapter.processNodes(DeckAdapter.kt:271)
>                                                                                                     	at com.ichi2.anki.widgets.DeckAdapter.buildDeckList(DeckAdapter.kt:137)
>                                                                                                     	at com.ichi2.anki.DeckPicker.renderPage(DeckPicker.kt:1947)
>                                                                                                     	at com.ichi2.anki.DeckPicker.onDecksLoaded(DeckPicker.kt:1885)
>                                                                                                     	at com.ichi2.anki.DeckPicker.access$onDecksLoaded(DeckPicker.kt:158)
>                                                                                                     	at com.ichi2.anki.DeckPicker$updateDeckList$1$1.invokeSuspend(DeckPicker.kt:1853)
>                                                                                                     	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>                                                                                                     	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
>                                                                                                     	at android.os.Handler.handleCallback(Handler.java:942)
>                                                                                                     	at android.os.Handler.dispatchMessage(Handler.java:99)
>                                                                                                     	at android.os.Looper.loopOnce(Looper.java:226)
>                                                                                                     	at android.os.Looper.loop(Looper.java:313)
>                                                                                                     	at android.app.ActivityThread.main(ActivityThread.java:8757)
>                                                                                                     	at java.lang.reflect.Method.invoke(Native Method)
>                                                                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
>                                                                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
>                                                                                                     Caused by: net.ankiweb.rsdroid.exceptions.BackendInvalidInputException$BackendCollectionNotOpenException: CollectionNotOpen
>                                                                                                     	at net.ankiweb.rsdroid.exceptions.BackendInvalidInputException$Companion.fromInvalidInputError(BackendInvalidInputException.kt:35)
>                                                                                                     	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:114)
>                                                                                                     	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:323)
>                                                                                                     	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
>                                                                                                     	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:130)
>                                                                                                     	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:129)
>                                                                                                     	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:157)
>                                                                                                     	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:129)
>                                                                                                     	at anki.backend.GeneratedBackend.runDbCommandProtoRaw(GeneratedBackend.kt:1699)
>                                                                                                     	at anki.backend.GeneratedBackend.runDbCommandProto(GeneratedBackend.kt:1709)
>                                                                                                     	at net.ankiweb.rsdroid.Backend.fullQueryProto(Backend.kt:223)
>                                                                                                     	at net.ankiweb.rsdroid.database.Session.fullQueryProto(Session.kt:79)
>                                                                                                     	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.kt:255)
>                                                                                                     	at net.ankiweb.rsdroid.database.RustSupportSQLiteDatabase.query(RustSupportSQLiteDatabase.kt:103) 
>                                                                                                     	at com.ichi2.utils.DatabaseChangeDecorator.query(Unknown Source:16) 
>                                                                                                     	at com.ichi2.libanki.DB.queryScalar(DB.kt:118) 
>                                                                                                     	at com.ichi2.anki.servicelayer.DeckService.defaultDeckHasCards(DeckService.kt:34) 
>                                                                                                     	at com.ichi2.anki.widgets.DeckAdapter.processNodes(DeckAdapter.kt:271) 
>                                                                                                     	at com.ichi2.anki.widgets.DeckAdapter.buildDeckList(DeckAdapter.kt:137) 
>                                                                                                     	at com.ichi2.anki.DeckPicker.renderPage(DeckPicker.kt:1947) 
>                                                                                                     	at com.ichi2.anki.DeckPicker.onDecksLoaded(DeckPicker.kt:1885) 
>                                                                                                     	at com.ichi2.anki.DeckPicker.access$onDecksLoaded(DeckPicker.kt:158) 
>                                                                                                     	at com.ichi2.anki.DeckPicker$updateDeckList$1$1.invokeSuspend(DeckPicker.kt:1853) 
>                                                                                                     	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
>                                                                                                     	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
>                                                                                                     	at android.os.Handler.handleCallback(Handler.java:942) 
>                                                                                                     	at android.os.Handler.dispatchMessage(Handler.java:99) 
>                                                                                                     	at android.os.Looper.loopOnce(Looper.java:226) 
>                                                                                                     	at android.os.Looper.loop(Looper.java:313) 
>                                                                                                     	at android.app.ActivityThread.main(ActivityThread.java:8757) 
>                                                                                                     	at java.lang.reflect.Method.invoke(Native Method) 
>                                                                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
>                                                                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
