### ISSUE TITLE
[Bug] Crash if using `Add note` widget or shortcuts before giving storage permission on `full` builds

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#13518]
###### Reproduction Steps

- tested on a `fullDebug` build
1. Don't have or remove the storage permission
2. Add the `Add note` widget to your screen
3. Tap the widget

###### Expected Result

Storage permission is asked correctly

###### Actual Result

Crashes

###### Debug info
Built with main d03d544c on SDK 33 emulator

```
ACRA caught a StorageAccessException for com.ichi2.anki.debug
                                                                                                    com.ichi2.anki.exception.StorageAccessException: No write access to AnkiDroid directory /storage/emulated/0/AnkiDroid
                                                                                                    	at com.ichi2.anki.CollectionHelper$Companion.initializeAnkiDroidDirectory(CollectionHelper.kt:369)
                                                                                                    	at com.ichi2.anki.CollectionManager.createCollectionPath(CollectionManager.kt:242)
                                                                                                    	at com.ichi2.anki.CollectionManager.ensureOpenInner(CollectionManager.kt:221)
                                                                                                    	at com.ichi2.anki.CollectionManager.access$ensureOpenInner(CollectionManager.kt:36)
                                                                                                    	at com.ichi2.anki.CollectionManager$getColUnsafe$1$1.invoke(CollectionManager.kt:276)
                                                                                                    	at com.ichi2.anki.CollectionManager$getColUnsafe$1$1.invoke(CollectionManager.kt:275)
                                                                                                    	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:83)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@93ea1b6, Dispatchers.Main.immediate]
```

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
Working on it

**Comment by criticalAY** [comment]
I remember disabling the deck shortcuts last year if no deck existed in the application this is quite a thing now

**Comment by criticalAY** [comment]
The exception is thrown from this method 
```
      @Throws(StorageAccessException::class)
        fun initializeAnkiDroidDirectory(path: String) {
            // Create specified directory if it doesn't exit
            val dir = File(path)
            if (!dir.exists() && !dir.mkdirs()) {
                throw StorageAccessException("Failed to create AnkiDroid directory $path")
            }
            if (!dir.canWrite()) {
                throw StorageAccessException("No write access to AnkiDroid directory $path")
            }
            // Add a .nomedia file to it if it doesn't exist
            val nomedia = File(dir, ".nomedia")
            if (!nomedia.exists()) {
                try {
                    nomedia.createNewFile()
                } catch (e: IOException) {
                    throw StorageAccessException("Failed to create .nomedia file", e)
                }
            }
        }
```

But if I place a try-catch block then there arises a SQL database error and if possible I would like to know from where the widgets are handled I am not able to get the widget code

**Comment by dae** [comment]
@BrayanDSO does it still happen?

**Comment by BrayanDSO** [comment]
Yes, it does.
