### ISSUE TITLE
[BUG]: Check Media causing crash

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#13527]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Deck Picker 
2. Check Media

### Expected behaviour

Media check result dialog is shown

### Actual behaviour

Crash

### Debug info

```text
Alpha95-debug
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
@david-allison I am trying to fix it though would like it to be labelled as high priority

**Comment by criticalAY** [comment]
```
ACRA caught a UninitializedPropertyAccessException for com.ichi2.anki.debug
                                                                                                    kotlin.UninitializedPropertyAccessException: lateinit property callback has not been initialized
                                                                                                    	at com.ichi2.anki.permissions.PermissionManager.launchDialogOrExecuteCallbackNow(PermissionManager.kt:119)
                                                                                                    	at com.ichi2.anki.DeckPicker.mediaCheck(DeckPicker.kt:1442)
                                                                                                    	at com.ichi2.anki.dialogs.MediaCheckDialog$onCreateDialog$1$1.invoke(MediaCheckDialog.kt:37)
                                                                                                    	at com.ichi2.anki.dialogs.MediaCheckDialog$onCreateDialog$1$1.invoke(MediaCheckDialog.kt:36)
```
