### ISSUE TITLE
[Bug] `menu/deck_picker.xml': No such file or directory`

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13665]
My steps: likely cause in bold

* API 32 emulator
* Import a large `.colpkg`
* Start running out of space
* **Minimise the app** 
* go to `Files` app + delete a `colpkg` file
* **Open the app**
* Crash dialog + import stops

```
4-22 20:21:04.950  2853-2853  chi2.anki.debu          com.ichi2.anki.debug                 E  Failed to open file '/data/data/com.ichi2.anki.debug/code_cache/.overlay/base.apk/res/menu/deck_picker.xml': No such file or directory
2023-04-22 20:21:04.958  2853-3012  Utils                   com.ichi2.anki.debug                 I  uncompress googletts-8fd60881-dec1b2c1-d61bf8bd-24489219-516c308d.mp3
2023-04-22 20:21:04.962  2853-2853  AndroidRuntime          com.ichi2.anki.debug                 E  FATAL EXCEPTION: main
                                                                                                    Process: com.ichi2.anki.debug, PID: 2853
                                                                                                    android.content.res.Resources$NotFoundException: File res/menu/deck_picker.xml from xml type layout resource ID #0x7f0e0009
                                                                                                    	at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1216)
                                                                                                    	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2472)
                                                                                                    	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2448)
                                                                                                    	at android.content.res.Resources.getLayout(Resources.java:1252)
                                                                                                    	at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:126)
                                                                                                    	at com.ichi2.anki.DeckPicker.onCreateOptionsMenu(DeckPicker.kt:578)
                                                                                                    	at android.app.Activity.onCreatePanelMenu(Activity.java:4283)
                                                                                                    	at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:542)
                                                                                                    	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:95)
                                                                                                    	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3444)
                                                                                                    	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
                                                                                                    	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:775)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7870)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    Caused by: java.io.FileNotFoundException: res/menu/deck_picker.xml
                                                                                                    	at android.content.res.AssetManager.nativeOpenXmlAsset(Native Method)
                                                                                                    	at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:1099)
                                                                                                    	at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1200)
                                                                                                    	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2472) 
                                                                                                    	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2448) 
                                                                                                    	at android.content.res.Resources.getLayout(Resources.java:1252) 
                                                                                                    	at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:126) 
                                                                                                    	at com.ichi2.anki.DeckPicker.onCreateOptionsMenu(DeckPicker.kt:578) 
                                                                                                    	at android.app.Activity.onCreatePanelMenu(Activity.java:4283) 
                                                                                                    	at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:542) 
                                                                                                    	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:95) 
                                                                                                    	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3444) 
                                                                                                    	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458) 
                                                                                                    	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58) 
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037) 
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:845) 
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:775) 
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7870) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
2023-04-22 20:21:04.982  2853-3012  Utils                   com.ichi2.anki.debug                 I  uncompress fork_and_knife.png
2023-04-22 20:21:04.988  2853-2853  ACRA                    com.ichi2.anki.debug                 E  ACRA caught a NotFoundException for com.ichi2.anki.debug
                                                                                                    android.content.res.Resources$NotFoundException: File res/menu/deck_picker.xml from xml type layout resource ID #0x7f0e0009
                                                                                                    	at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1216)
                                                                                                    	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2472)
                                                                                                    	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2448)
                                                                                                    	at android.content.res.Resources.getLayout(Resources.java:1252)
                                                                                                    	at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:126)
                                                                                                    	at com.ichi2.anki.DeckPicker.onCreateOptionsMenu(DeckPicker.kt:578)
                                                                                                    	at android.app.Activity.onCreatePanelMenu(Activity.java:4283)
                                                                                                    	at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:542)
                                                                                                    	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:95)
                                                                                                    	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3444)
                                                                                                    	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
                                                                                                    	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:775)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7870)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    Caused by: java.io.FileNotFoundException: res/menu/deck_picker.xml
                                                                                                    	at android.content.res.AssetManager.nativeOpenXmlAsset(Native Method)
                                                                                                    	at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:1099)
                                                                                                    	at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1200)
                                                                                                    	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2472) 
                                                                                                    	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2448) 
                                                                                                    	at android.content.res.Resources.getLayout(Resources.java:1252) 
                                                                                                    	at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:126) 
                                                                                                    	at com.ichi2.anki.DeckPicker.onCreateOptionsMenu(DeckPicker.kt:578) 
                                                                                                    	at android.app.Activity.onCreatePanelMenu(Activity.java:4283) 
                                                                                                    	at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:542) 
                                                                                                    	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:95) 
                                                                                                    	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3444) 
                                                                                                    	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458) 
                                                                                                    	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58) 
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037) 
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:845) 
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:775) 
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7870) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

<details><summary>Debug Info</summary>

AnkiDroid Version = 2.16alpha97-debug

Android Version = 12

ProductFlavor = amazon

Manufacturer = Google

Model = sdk_gphone64_arm64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 12; sdk_gphone64_arm64 Build/SE1B.220616.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/95.0.4638.74 Mobile Safari/537.36

ACRA UUID = ba0c0656-6559-45e4-b7a8-688f2fd3931a

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

</details>

**Comment by david-allison** [comment]
Can't reproduce

**Comment by criticalAY** [comment]
I was about to try to reproduce this one

**Comment by david-allison** [comment]
Needs fixing if reproducible! Let me know if you manage. Slight possibility this was an Android issue due to running low on space, but it seems doubtful.

**Comment by criticalAY** [comment]
I'll try to reproduce it in the morning I just closed my laptop too tired today
