### ISSUE TITLE
[Bug] DeckManager: NullPointerException on corrupt collection

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13666]
After importing Arthur's large `.colpkg` via import + replace

```
2023-04-22 20:33:32.259 17603-17603 CoroutineHelpersKt      com.ichi2.anki.debug                 E  java.lang.NullPointerException
                                                                                                    	at com.ichi2.libanki.DeckManager.get(DeckManager.kt:92)
                                                                                                    	at com.ichi2.libanki.Decks.current(Decks.kt:845)
                                                                                                    	at com.ichi2.anki.widgets.DeckAdapter.buildDeckList(DeckAdapter.kt:136)
                                                                                                    	at com.ichi2.anki.DeckPicker.renderPage(DeckPicker.kt:1948)
                                                                                                    	at com.ichi2.anki.DeckPicker.onDecksLoaded(DeckPicker.kt:1886)
                                                                                                    	at com.ichi2.anki.DeckPicker.access$onDecksLoaded(DeckPicker.kt:159)
                                                                                                    	at com.ichi2.anki.DeckPicker$updateDeckList$2$1.invokeSuspend(DeckPicker.kt:1866)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7870)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

<details><summary>Debug Info</summary>

**note: built off personal branch somewhere between alpha 97 and 98**

AnkiDroid Version = 2.16alpha97-debug

Android Version = 12

ProductFlavor = amazon

Manufacturer = Google

Model = sdk_gphone64_arm64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 12; sdk_gphone64_arm64 Build/SE1B.220616.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/95.0.4638.74 Mobile Safari/537.36

ACRA UUID = ba0c0656-6559-45e4-b7a8-688f2fd3931a

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

</details>

**Comment by david-allison** [comment]
`dconf` was `{}` - bad collection
