### ISSUE TITLE
[Bug] New Backend: BackendSyncException - HttpError (code: 308)

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13684]
https://ankidroid.org/acra/app/1/bug/46226/report/b70c2162-1220-4c7b-8aca-c03234198a22

```
net.ankiweb.rsdroid.exceptions.BackendSyncException: HttpError { code: 308, context: "https://sync16.ankiweb.net/", source: None }
	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:142)
	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:38)
	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:2)
	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:1)
	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:13)
	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:16)
	at anki.backend.GeneratedBackend.fullDownloadRaw(GeneratedBackend.kt:8)
	at anki.backend.GeneratedBackend.fullDownload(GeneratedBackend.kt:15)
	at com.ichi2.libanki.sync.BackendSyncKt.fullDownload(BackendSync.kt:15)
	at com.ichi2.anki.SyncKt$handleDownload$3$1.invoke(Sync.kt:6)
	at com.ichi2.anki.SyncKt$handleDownload$3$1.invoke(Sync.kt:1)
	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:3)
	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:1)
	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
```

2.16alpha98

**Comment by dae** [comment]
The code should be calling the meta endpoint first, which would send a 308 to the correct location, which AD should persist. A 308 on the download endpoint implies either meta was not called, or the updated location was not used.
