### ISSUE TITLE
[Bug] Shared Decks Download: Download ID does not match with the ID of the completed download

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13686]
```
com.ichi2.anki.exception.ManuallyReportedException: Download ID does not match with the ID of the completed download
	at com.ichi2.anki.CrashReportService.sendExceptionReport(CrashReportService.kt:1)
	at com.ichi2.anki.SharedDecksDownloadFragment$mOnComplete$1.onReceive$verifyDeckIsImportable(SharedDecksDownloadFragment.kt:55)
	at com.ichi2.anki.SharedDecksDownloadFragment$mOnComplete$1.onReceive(SharedDecksDownloadFragment.kt:20)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1886)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:966)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
	at android.app.ActivityThread.main(ActivityThread.java:9596)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)
```

https://ankidroid.org/acra/app/1/bug/46231/report/ae2d57ce-77bc-4558-a039-46dc89ecb3ed

* 2.16alpha98
* no logcat provided

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/blob/5b0a690790c75c6b32a6250c60beafb3733efbbd/AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt#L196-L209
