### ISSUE TITLE
[Bug] NullPointerException: isLegacyStorage - FIle.getCanonicalFile

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13705]
```

java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File java.io.File.getCanonicalFile()' on a null object reference
	at com.ichi2.anki.servicelayer.ScopedStorageService.isLegacyStorage(ScopedStorageService.kt:7)
	at com.ichi2.anki.servicelayer.ScopedStorageService.isLegacyStorage(ScopedStorageService.kt:1)
	at com.ichi2.anki.DeckPicker$updateMenuState$2.invoke(DeckPicker.kt:5)
	at com.ichi2.anki.DeckPicker$updateMenuState$2.invoke(DeckPicker.kt:1)
	at com.ichi2.anki.CollectionManager$withOpenColOrNull$2.invoke(CollectionManager.kt:3)
	at com.ichi2.anki.CollectionManager$withOpenColOrNull$2.invoke(CollectionManager.kt:1)
	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
```

* 2.16alpha92
* https://ankidroid.org/acra/app/1/bug/25784/report/4f304cea-751a-423c-852d-a5ca56942bae
* Android 13

<details><summary>Logcat</summary>

```
LOGCAT
--------- beginning of main
04-24 15:48:13.654 E/AnkiDroid(30311): CoroutineHelpersKt$runCatchingTask/ java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File java.io.File.getCanonicalFile()' on a null object reference
04-24 15:48:13.654 E/AnkiDroid(30311): 	at com.ichi2.anki.servicelayer.ScopedStorageService.isLegacyStorage(ScopedStorageService.kt:7)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at com.ichi2.anki.servicelayer.ScopedStorageService.isLegacyStorage(ScopedStorageService.kt:1)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at com.ichi2.anki.DeckPicker$updateMenuState$2.invoke(DeckPicker.kt:5)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at com.ichi2.anki.DeckPicker$updateMenuState$2.invoke(DeckPicker.kt:1)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at com.ichi2.anki.CollectionManager$withOpenColOrNull$2.invoke(CollectionManager.kt:3)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at com.ichi2.anki.CollectionManager$withOpenColOrNull$2.invoke(CollectionManager.kt:1)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:15)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
04-24 15:48:13.654 E/AnkiDroid(30311): 
04-24 15:48:13.654 E/AnkiDroid(30311): java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File java.io.File.getCanonicalFile()' on a null object reference
04-24 15:48:13.654 E/AnkiDroid(30311): 	at com.ichi2.anki.servicelayer.ScopedStorageService.isLegacyStorage(ScopedStorageService.kt:7)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at com.ichi2.anki.servicelayer.ScopedStorageService.isLegacyStorage(ScopedStorageService.kt:1)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at com.ichi2.anki.DeckPicker$updateMenuState$2.invoke(DeckPicker.kt:5)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at com.ichi2.anki.DeckPicker$updateMenuState$2.invoke(DeckPicker.kt:1)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at com.ichi2.anki.CollectionManager$withOpenColOrNull$2.invoke(CollectionManager.kt:3)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at com.ichi2.anki.CollectionManager$withOpenColOrNull$2.invoke(CollectionManager.kt:1)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:15)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
04-24 15:48:13.654 E/AnkiDroid(30311): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
04-24 15:48:13.880 I/AnkiDroid(30311): AnkiActivity::onStop - Reviewer
04-24 15:48:13.886 I/AnkiDroid(30311): AnkiActivity::onDestroy - Reviewer
```
</details>

**Comment by soCallmeAdityaKumar** [comment]
Can i Do this?

**Comment by david-allison** [comment]
@soCallmeAdityaKumar Feel free to look into it. Since it's high priority, I'll keep it open to others to solve

**Comment by david-allison** [comment]
Possibly useful:

```
ENVIRONMENT
getDataDirectory
/data
getDataSystemDirectory
/data/system
getDownloadCacheDirectory
/data/cache
getExternalStorageDirectory
/storage/emulated/0
getExternalStorageState
mounted
getInternalMediaDirectories
[/system/media, /oem/media, /product/media, /prism/media/carriers/single/KOO, /data/overlays/media]
getLegacyExternalStorageDirectory
/sdcard
getLegacyExternalStorageObbDirectory
/sdcard/Android/obb
getOdmDirectory
/odm
getOemDirectory
/oem
getProductDirectory
/product
getProductServicesDirectory
/product_services
getRootDirectory
/system
getStorageDirectory
/storage
getSystemExtDirectory
/system_ext
getVendorDirectory
/vendor
isExternalStorageEmulated
true
isExternalStorageLegacy
true
isExternalStorageManager
false
isExternalStorageRemovable
false
```

**Comment by david-allison** [comment]
Probably best to pick another issue - handled this one

**Comment by soCallmeAdityaKumar** [comment]
> Probably best to pick another issue - handled this one

Ok
