### ISSUE TITLE
[Bug] NoteEditor: saveToggleStickyMap IndexOutOfBoundsException

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13719]
```
java.lang.IndexOutOfBoundsException: Index: 4, Size: 2
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at com.ichi2.anki.NoteEditor.saveToggleStickyMap(NoteEditor.kt:44)
	at com.ichi2.anki.NoteEditor.saveNote(NoteEditor.kt:74)
	at com.ichi2.anki.NoteEditor$onOptionsItemSelected$1.invokeSuspend(NoteEditor.kt:31)
	at com.ichi2.anki.NoteEditor$onOptionsItemSelected$1.invoke(NoteEditor.kt:2)
	at com.ichi2.anki.NoteEditor$onOptionsItemSelected$1.invoke(NoteEditor.kt:1)
	at com.ichi2.anki.CoroutineHelpersKt$launchCatchingTask$1$1.invokeSuspend(CoroutineHelpers.kt:33)
	at com.ichi2.anki.CoroutineHelpersKt$launchCatchingTask$1$1.invoke(CoroutineHelpers.kt:2)
	at com.ichi2.anki.CoroutineHelpersKt$launchCatchingTask$1$1.invoke(CoroutineHelpers.kt:1)
	at com.ichi2.anki.CoroutineHelpersKt.runCatchingTask(CoroutineHelpers.kt:69)
	at com.ichi2.anki.CoroutineHelpersKt$launchCatchingTask$1.invokeSuspend(CoroutineHelpers.kt:45)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:133)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:3)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:6)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:10)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:23)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:13)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at com.ichi2.anki.CoroutineHelpersKt.launchCatchingTask(CoroutineHelpers.kt:1)
	at com.ichi2.anki.CoroutineHelpersKt.launchCatchingTask$default(CoroutineHelpers.kt:1)
	at com.ichi2.anki.NoteEditor.onOptionsItemSelected(NoteEditor.kt:110)
	at android.app.Activity.onMenuItemSelected(Activity.java:4269)
	at androidx.activity.ComponentActivity.onMenuItemSelected(ComponentActivity.java:1)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:1)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:1)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:3)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:6)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:19)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:7)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:5)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:15)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:4)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:1)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:4)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:7)
	at android.view.View.performClick(View.java:7448)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28305)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

* https://ankidroid.org/acra/app/1/bug/46189/report/4f40443c-25b6-419b-b113-445c19a048c2
* Legacy Backend
* Android 11

<details><summary>Logcat</summary>

```
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.NoteEditor.saveNote(NoteEditor.kt:74)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.NoteEditor$onOptionsItemSelected$1.invokeSuspend(NoteEditor.kt:31)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.NoteEditor$onOptionsItemSelected$1.invoke(NoteEditor.kt:2)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.NoteEditor$onOptionsItemSelected$1.invoke(NoteEditor.kt:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.CoroutineHelpersKt$launchCatchingTask$1$1.invokeSuspend(CoroutineHelpers.kt:33)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.CoroutineHelpersKt$launchCatchingTask$1$1.invoke(CoroutineHelpers.kt:2)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.CoroutineHelpersKt$launchCatchingTask$1$1.invoke(CoroutineHelpers.kt:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.CoroutineHelpersKt.runCatchingTask(CoroutineHelpers.kt:69)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.CoroutineHelpersKt$launchCatchingTask$1.invokeSuspend(CoroutineHelpers.kt:45)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:133)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:3)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:6)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:10)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:23)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:13)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.CoroutineHelpersKt.launchCatchingTask(CoroutineHelpers.kt:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.CoroutineHelpersKt.launchCatchingTask$default(CoroutineHelpers.kt:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.NoteEditor.onOptionsItemSelected(NoteEditor.kt:110)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at android.app.Activity.onMenuItemSelected(Activity.java:4269)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.activity.ComponentActivity.onMenuItemSelected(ComponentActivity.java:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:3)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:6)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:19)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:7)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:5)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:15)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:4)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:4)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:7)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at android.view.View.performClick(View.java:7448)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at android.view.View.performClickInternal(View.java:7425)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at android.view.View.access$3600(View.java:810)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at android.view.View$PerformClick.run(View.java:28305)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at android.os.Handler.handleCallback(Handler.java:938)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at android.os.Looper.loop(Looper.java:223)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at android.app.ActivityThread.main(ActivityThread.java:7660)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at java.lang.reflect.Method.invoke(Native Method)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
04-23 23:28:35.177 E/AnkiDroid( 4969): 
04-23 23:28:35.177 E/AnkiDroid( 4969): java.lang.IndexOutOfBoundsException: Index: 4, Size: 2
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at java.util.LinkedList.get(LinkedList.java:476)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.NoteEditor.saveToggleStickyMap(NoteEditor.kt:44)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.NoteEditor.saveNote(NoteEditor.kt:74)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.NoteEditor$onOptionsItemSelected$1.invokeSuspend(NoteEditor.kt:31)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.NoteEditor$onOptionsItemSelected$1.invoke(NoteEditor.kt:2)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.NoteEditor$onOptionsItemSelected$1.invoke(NoteEditor.kt:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.CoroutineHelpersKt$launchCatchingTask$1$1.invokeSuspend(CoroutineHelpers.kt:33)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.CoroutineHelpersKt$launchCatchingTask$1$1.invoke(CoroutineHelpers.kt:2)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.CoroutineHelpersKt$launchCatchingTask$1$1.invoke(CoroutineHelpers.kt:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.CoroutineHelpersKt.runCatchingTask(CoroutineHelpers.kt:69)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.CoroutineHelpersKt$launchCatchingTask$1.invokeSuspend(CoroutineHelpers.kt:45)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:133)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:3)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:6)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:10)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:23)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:13)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.CoroutineHelpersKt.launchCatchingTask(CoroutineHelpers.kt:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.CoroutineHelpersKt.launchCatchingTask$default(CoroutineHelpers.kt:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.ichi2.anki.NoteEditor.onOptionsItemSelected(NoteEditor.kt:110)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at android.app.Activity.onMenuItemSelected(Activity.java:4269)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.activity.ComponentActivity.onMenuItemSelected(ComponentActivity.java:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:3)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:6)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:19)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:7)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:5)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:15)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:4)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:1)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:4)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:7)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at android.view.View.performClick(View.java:7448)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at android.view.View.performClickInternal(View.java:7425)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at android.view.View.access$3600(View.java:810)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at android.view.View$PerformClick.run(View.java:28305)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at android.os.Handler.handleCallback(Handler.java:938)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at android.os.Looper.loop(Looper.java:223)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at android.app.ActivityThread.main(ActivityThread.java:7660)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at java.lang.reflect.Method.invoke(Native Method)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
04-23 23:28:35.177 E/AnkiDroid( 4969): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
</details>

**Comment by david-allison** [comment]
Reproduction steps:

* Select "Basic (and optional reversed)
* Tap all 3 sticky note fields
* Change to "Basic"
* Save
