### ISSUE TITLE
Flaky test CI failure  `SchedV2Test > test_learnV2 FAILED`

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#13745]
Flaky test CI failure  `SchedV2Test > test_learnV2 FAILED`

I'm just collecting CI flakes now I suppose, re-running but this is good to go as far as I can tell

```
    java.lang.AssertionError: expected:<3> but was:<1>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at com.ichi2.libanki.sched.SchedV2Test$test_learnV2$2.invoke(SchedV2Test.kt:478)
        at com.ichi2.libanki.sched.SchedV2Test$test_learnV2$2.invoke(SchedV2Test.kt:478)
        at com.ichi2.libanki.sched.SchedV2Test.ifV2(SchedV2Test.kt:82)
        at com.ichi2.libanki.sched.SchedV2Test.test_learnV2(SchedV2Test.kt:478)
```

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/13735#issuecomment-1525641960_

**Comment by mikehardy** [comment]
Not sure what the best solution here is, we have a relatively new `@FlakyTest` annotation which may be be put to use, or it may be a subtle race condition that really needs to  be fixed but may be *hard* to diagnose and fix 🤷  - thus creating an issue to track
