### ISSUE TITLE
2.16 Bug: crash on Async dialog not being attached to a context

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#13795]
Similar to #13085 

Cause: https://github.com/ankidroid/Anki-Android/commit/6ea36860a8e9fddadff0bf484746248fd843eb53

```
java.lang.IllegalStateException: Fragment SyncErrorDialog{31dcea2} (bfb1ab5d-fa6d-4d4b-9fe6-9bf9ea0489c8 tag=dialog) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:32)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:1)
	at com.ichi2.anki.dialogs.SyncErrorDialog.getTitle(SyncErrorDialog.kt:56)
	at com.ichi2.anki.dialogs.SyncErrorDialog.getNotificationTitle(SyncErrorDialog.kt:30)
	at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.kt:5)
	at com.ichi2.anki.DeckPicker.showSyncErrorDialog(DeckPicker.kt:3)
	at com.ichi2.anki.DeckPicker.showSyncErrorDialog(DeckPicker.kt:1)
	at com.ichi2.anki.SyncKt$createSyncListener$1.onPostExecute(Sync.kt:522)
	at com.ichi2.async.Connection.onPostExecute(Connection.kt:6)
	at com.ichi2.async.Connection.onPostExecute(Connection.kt:1)
	at android.os.AsyncTask.finish(AsyncTask.java:755)
	at android.os.AsyncTask.access$900(AsyncTask.java:192)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```
Samsung 
Android 13
2.16beta01
https://ankidroid.org/acra/app/1/bug/47861/report/e4d607bb-64a5-42a9-ac71-e4a75d17b2b0

**Comment by BrayanDSO** [comment]
Should need some work on the async dialogs code, as reverting https://github.com/ankidroid/Anki-Android/commit/6ea36860a8e9fddadff0bf484746248fd843eb53 will cause #12448 again. IMO the revert is acceptable because not crashing is more important, but fixes are preferred over reverts if time allows.

**Comment by BrayanDSO** [comment]
Perhaps MediaCheckDialog too
```
java.lang.NullPointerException
	at com.ichi2.anki.dialogs.MediaCheckDialog$MediaCheckCompleteDialog.handleAsyncMessage(MediaCheckDialog.kt:14)
	at com.ichi2.anki.dialogs.DialogHandler.handleMessage(DialogHandler.kt:51)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by mikehardy** [comment]
This seems pretty widespread and crashes are the worst.

I think I'd prefer a revert here and go with a UI language-change-delay vs crashes, then queue this for investigation after 2.16 release

**Comment by lukstbit** [comment]
A revert is the best option in the short term, properly fixing this would require quite a good amount of refactoring of the dialogs under `AsyncDialogFragment`.

**Comment by david-allison** [comment]
Also related (and should be reverted so we can do this properly): 385afba7a5242dd3195554845a1e9e764697cd7c (#13086)

**Comment by matejdro** [comment]
This is sort of still happening in 2.17alpha9, albeit not a full crash:

![image](https://github.com/ankidroid/Anki-Android/assets/507922/b4933c28-1493-485b-bfac-3206b7af726d)

**Comment by matejdro** [comment]
This is how I managed to reproduce it, not sure if its reliably or not:

1. Change card type on desktop Anki. This will trigger a full resync
2. Sync AnkiDroid
3. Select to replace AnkiDroid DB from AnkiWeb
4. Confirm replacement
5. Boom, this error showed up

**Comment by mikehardy** [comment]
I saw these in the crash report database when I was trawling through there for #14936 - had no idea how to reproduce it, thank you

**Comment by david-allison** [comment]
I believe:

* 04408c1329c349d68bc3b6d63fab760f9767a7d6

1) we should use `res()`
* `notificationMessage` and `notificationTitle` can be called when the dialog is not attached to a context
2)
* prefer `resources` to ensure that the correct language is selected
