### ISSUE TITLE
[2.16beta01 Bug]: IndexOutOfBoundsException on DeckAdapter

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#13794]
```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 8(offset:8).state:29 androidx.recyclerview.widget.RecyclerView{b2ffdd6 VFED.V... ......ID 0,0-1440,2673 #7f0901d1 app:id/files}, adapter:com.ichi2.anki.widgets.DeckAdapter@1000a4d, layout:androidx.recyclerview.widget.LinearLayoutManager@ae0eb86, context:com.ichi2.anki.DeckPicker@c21356d
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:382)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:2)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:39)
	at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:35)
	at androidx.recyclerview.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:7)
	at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:40)
	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:116)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:847)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

https://ankidroid.org/acra/app/1/bug/47707/report/3482ece4-f673-4242-9af7-5fdeb6368cf3
Android 13
Samsung phone

@david-allison said on Discord:
> * DeckAdapter issue (I suspect on Samsung phones): https://ankidroid.org/acra/app/1/bug/47707/report/3482ece4-f673-4242-9af7-5fdeb6368cf3
  * Likely a very simple fix, judging from StackOverflow

**Comment by BrayanDSO** [comment]
Similar trace on an Android 13 Sony Xperia https://ankidroid.org/acra/app/1/bug/47971/report/5c98d25e-21ff-406a-953a-4a0b6b58e441

```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{9cf222f position=18 id=-1, oldPos=-1, pLpos:-1 no parent} androidx.recyclerview.widget.RecyclerView{d83c4d4 VFED.V... ......ID 0,0-1080,2014 #7f0901d1 app:id/files}, adapter:com.ichi2.anki.widgets.DeckAdapter@2efdfde, layout:androidx.recyclerview.widget.LinearLayoutManager@7c2577, context:com.ichi2.anki.DeckPicker@3de5e47
	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:50)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:2)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:39)
	at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:35)
	at androidx.recyclerview.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:7)
	at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:40)
	at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:24)
	at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:364)
	at android.view.View.dispatchTouchEvent(View.java:15010)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3115)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2788)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1905)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4298)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:3)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
	at android.view.View.dispatchPointerEvent(View.java:15269)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6757)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6557)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6013)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6070)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6036)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6201)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6044)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6258)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6017)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6070)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6036)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6044)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6017)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9103)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9054)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9023)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9226)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:247)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9183)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9317)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:824)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by lonewolf2208** [comment]
I would like to work on this issue

**Comment by BrayanDSO** [comment]
Go for it

**Comment by david-allison** [comment]
Haven't been able to reproduce this on my S21. Reproduction steps would be fantastic here. 

1 logcat: appears to be on opening the Deck Picker. One from moving from the Reviewer to the DeckPicker

**Logcats from ACRA**

<details><summary>Logcat</summary>

https://ankidroid.org/acra/app/1/bug/47707/report/3482ece4-f673-4242-9af7-5fdeb6368cf3

```
--------- beginning of main
05-03 16:08:23.651 I/AnkiDroid( 5918): AnkiActivity::onStart - DeckPicker
05-03 16:08:23.687 I/AnkiDroid( 5918): AnkiActivity::onResume - DeckPicker
05-03 16:08:23.877 E/AnkiDroid( 5918): CollectionManager/ blocked main thread for 169ms:
05-03 16:08:23.877 E/AnkiDroid( 5918): com.ichi2.anki.DeckPicker.refreshState(DeckPicker.kt:72)
05-03 16:08:23.947 I/AnkiDroid( 5918): Updating deck list UI
```

https://ankidroid.org/acra/app/1/bug/47971/report/5c98d25e-21ff-406a-953a-4a0b6b58e441

```
--------- beginning of main
05-04 17:19:45.949 I/AnkiDroid(17281): stop: automatically show question
05-04 17:19:45.949 I/AnkiDroid(17281): AbstractFlashcardViewer:: EASE_1 pressed
05-04 17:19:45.995 I/AnkiDroid(17281): Answering card 1628076348546
05-04 17:19:46.006 I/AnkiDroid(17281): Obtaining next card
05-04 17:19:46.013 I/AnkiDroid(17281): ViewGroupUtils::setRenderWorkaround - using default / hardware rendering
05-04 17:19:46.015 I/AnkiDroid(17281): AbstractFlashcardViewer:: Question successfully shown for card id 1663353136117

05-04 17:19:48.387 I/AnkiDroid(17281): AbstractFlashcardViewer:: Show answer button pressed
05-04 17:19:48.387 I/AnkiDroid(17281): stop: automatically show answer
05-04 17:19:49.488 I/AnkiDroid(17281): stop: automatically show question
05-04 17:19:49.488 I/AnkiDroid(17281): AbstractFlashcardViewer:: EASE_1 pressed
05-04 17:19:49.500 I/AnkiDroid(17281): Answering card 1663353136117
05-04 17:19:49.511 I/AnkiDroid(17281): Obtaining next card
05-04 17:19:49.518 I/AnkiDroid(17281): ViewGroupUtils::setRenderWorkaround - using default / hardware rendering
05-04 17:19:49.523 I/AnkiDroid(17281): AbstractFlashcardViewer:: Question successfully shown for card id 1628076348546
[snip]
05-04 17:19:52.144 I/AnkiDroid(17281): AbstractFlashcardViewer:: Show answer button pressed
05-04 17:19:52.144 I/AnkiDroid(17281): stop: automatically show answer
05-04 17:19:53.719 I/AnkiDroid(17281): stop: automatically show question
05-04 17:19:53.719 I/AnkiDroid(17281): AbstractFlashcardViewer:: EASE_2 pressed
05-04 17:19:53.754 I/AnkiDroid(17281): Answering card 1628076348546
05-04 17:19:53.766 I/AnkiDroid(17281): Obtaining next card
05-04 17:19:53.773 I/AnkiDroid(17281): ViewGroupUtils::setRenderWorkaround - using default / hardware rendering
05-04 17:19:53.777 I/AnkiDroid(17281): AbstractFlashcardViewer:: Question successfully shown for card id 1663353136117
[snip]
05-04 17:19:54.410 I/AnkiDroid(17281): AbstractFlashcardViewer:: Show answer button pressed
05-04 17:19:54.411 I/AnkiDroid(17281): stop: automatically show answer
05-04 17:19:55.861 I/AnkiDroid(17281): Play all: Completed - releasing sound
[snip]
05-04 17:19:56.709 I/AnkiDroid(17281): Navigating to decks
05-04 17:19:56.738 I/AnkiDroid(17281): AnkiActivity::onPause - Reviewer
05-04 17:19:56.744 I/AnkiDroid(17281): stop: automatically show answer
05-04 17:19:56.744 I/AnkiDroid(17281): stop: automatically show question
05-04 17:19:56.753 I/AnkiDroid(17281): AnkiActivity::onStart - DeckPicker
05-04 17:19:56.757 I/AnkiDroid(17281): AnkiActivity::onResume - DeckPicker
05-04 17:19:56.957 E/AnkiDroid(17281): CollectionManager/ blocked main thread for 198ms:
05-04 17:19:56.957 E/AnkiDroid(17281): com.ichi2.anki.DeckPicker.refreshState(DeckPicker.kt:72)
05-04 17:19:57.004 I/AnkiDroid(17281): Updating deck list UI
05-04 17:19:57.036 I/AnkiDroid(17281): AnkiActivity::onStop - Reviewer
05-04 17:19:57.249 E/AnkiDroid(17281): CollectionManager/ blocked main thread for 209ms:
05-04 17:19:57.249 E/AnkiDroid(17281): com.ichi2.anki.Reviewer.onStop(Reviewer.kt:30)
05-04 17:19:57.250 I/AnkiDroid(17281): AnkiActivity::onDestroy - Reviewer
05-04 17:19:57.328 I/AnkiDroid(17281): flush - Saving information to DB...
```


</details>

**Comment by lonewolf2208** [comment]
I was unable to reproduce the bug, but I was able to find a fix in an article. Should I raise My PR on This? 
Article Link - [Article](https://nhancv.medium.com/android-fix-java-lang-indexoutofboundsexception-inconsistency-detected-invalid-item-70e9b3b489a2)
