### ISSUE TITLE
[Bug] 2.16.0beta1: IllegalStateException: files not equal: `.nomedia`

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13807]
https://ankidroid.org/acra/app/1/bug/47516/report/1b15fb2e-ff21-4310-9422-9d4d25dc7b4d

```

java.lang.IllegalStateException: files not equal: /storage/emulated/0/AnkiDroid/.nomedia, /storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid1/.nomedia
	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles.throwIfEssentialFilesAreMutated(MigrateEssentialFiles.kt:81)
	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles.execute(MigrateEssentialFiles.kt:88)
	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles$Companion$migrateEssentialFiles$2.invoke(MigrateEssentialFiles.kt:2)
	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles$Companion$migrateEssentialFiles$2.invoke(MigrateEssentialFiles.kt:1)
	at com.ichi2.anki.exception.RetryableException$Companion.retryOnce(RetryableException.kt:6)
	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles$Companion.migrateEssentialFiles$AnkiDroid_playRelease(MigrateEssentialFiles.kt:164)
	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles$Companion.migrateEssentialFiles$AnkiDroid_playRelease$default(MigrateEssentialFiles.kt:6)
	at com.ichi2.anki.servicelayer.ScopedStorageService.migrateEssentialFiles(ScopedStorageService.kt:82)
	at com.ichi2.anki.DeckPicker$migrate$1$elapsedMillisDuringEssentialFilesMigration$1$1$1.invokeSuspend(DeckPicker.kt:49)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
```

* Samsung Galaxy S23 Ultra

<details><summary>Logcat</summary>

```
05-02 12:02:45.552 I/AnkiDroid(14945): Opening Collection Log
05-02 12:02:45.556 I/AnkiDroid(14945): closeCollection: migration to scoped storage
05-02 12:02:45.562 W/AnkiDroid(14945): Collection/ Not in a transaction. Cannot end transaction.
05-02 12:02:45.565 I/AnkiDroid(14945): Closing Collection Log
05-02 12:02:45.566 I/AnkiDroid(14945): Collection closed
05-02 12:02:45.568 I/AnkiDroid(14945): (Re)opening Database: /storage/emulated/0/AnkiDroid/collection.anki2
05-02 12:02:45.571 I/AnkiDroid(14945): NotificationService: OnStartCommand
05-02 12:02:45.621 I/AnkiDroid(14945): Opening Collection Log
05-02 12:02:45.623 I/AnkiDroid(14945): isLegacyStorage(): current dir: /storage/emulated/0/AnkiDroid
05-02 12:02:45.623 I/AnkiDroid(14945): scoped external dirs: /storage/emulated/0/Android/data/com.ichi2.anki/files
05-02 12:02:45.623 I/AnkiDroid(14945): scoped internal dir: /data/user/0/com.ichi2.anki/files
05-02 12:02:45.630 I/AnkiDroid(14945): isLegacyStorage(): current dir: /storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid1
05-02 12:02:45.630 I/AnkiDroid(14945): scoped external dirs: /storage/emulated/0/Android/data/com.ichi2.anki/files
05-02 12:02:45.630 I/AnkiDroid(14945): scoped internal dir: /data/user/0/com.ichi2.anki/files
05-02 12:02:45.634 I/AnkiDroid(14945): flush - Saving information to DB...
05-02 12:02:45.644 I/AnkiDroid(14945): Closing Collection Log
05-02 12:02:45.645 I/AnkiDroid(14945): Collection closed
05-02 12:02:45.646 I/AnkiDroid(14945): Begin openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
05-02 12:02:45.649 I/AnkiDroid(14945): (Re)opening Database: /storage/emulated/0/AnkiDroid/collection.anki2
05-02 12:02:45.689 I/AnkiDroid(14945): Opening Collection Log
05-02 12:02:45.690 I/AnkiDroid(14945): End openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
05-02 12:02:45.695 I/AnkiDroid(14945): flush - Saving information to DB...
05-02 12:02:45.702 I/AnkiDroid(14945): Closing Collection Log
05-02 12:02:45.702 I/AnkiDroid(14945): Collection closed
05-02 12:02:45.702 I/AnkiDroid(14945): locked collection. Opening will throw SQLiteDatabaseLockedException
05-02 12:02:45.703 I/AnkiDroid(14945): (Re)opening Database: /storage/emulated/0/AnkiDroid/collection.anki2
05-02 12:02:45.703 I/AnkiDroid(14945): Expected exception thrown: 
05-02 12:02:45.704 I/AnkiDroid(14945): Migrating essential file: 'collection.anki2'
05-02 12:02:45.722 I/AnkiDroid(14945): Migrating essential file: 'collection.anki2-journal'
05-02 12:02:45.723 I/AnkiDroid(14945): Migrating essential file: 'collection.media.ad.db2'
05-02 12:02:45.724 I/AnkiDroid(14945): Migrating essential file: 'collection.media.ad.db2-journal'
05-02 12:02:45.725 I/AnkiDroid(14945): Migrating essential file: '.nomedia'
05-02 12:02:45.727 I/AnkiDroid(14945): Migrating essential file: 'collection.log'
05-02 12:02:45.728 I/AnkiDroid(14945): unlocked collection
05-02 12:02:45.810 E/AnkiDroid(14945): CoroutineHelpersKt$runCatchingTask/ java.lang.IllegalStateException: files not equal: /storage/emulated/0/AnkiDroid/.nomedia, /storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid1/.nomedia
05-02 12:02:45.810 E/AnkiDroid(14945): 	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles.throwIfEssentialFilesAreMutated(MigrateEssentialFiles.kt:81)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles.execute(MigrateEssentialFiles.kt:88)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles$Companion$migrateEssentialFiles$2.invoke(MigrateEssentialFiles.kt:2)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles$Companion$migrateEssentialFiles$2.invoke(MigrateEssentialFiles.kt:1)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at com.ichi2.anki.exception.RetryableException$Companion.retryOnce(RetryableException.kt:6)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles$Companion.migrateEssentialFiles$AnkiDroid_playRelease(MigrateEssentialFiles.kt:164)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles$Companion.migrateEssentialFiles$AnkiDroid_playRelease$default(MigrateEssentialFiles.kt:6)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at com.ichi2.anki.servicelayer.ScopedStorageService.migrateEssentialFiles(ScopedStorageService.kt:82)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at com.ichi2.anki.DeckPicker$migrate$1$elapsedMillisDuringEssentialFilesMigration$1$1$1.invokeSuspend(DeckPicker.kt:49)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
05-02 12:02:45.810 E/AnkiDroid(14945): 
05-02 12:02:45.810 E/AnkiDroid(14945): java.lang.IllegalStateException: files not equal: /storage/emulated/0/AnkiDroid/.nomedia, /storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid1/.nomedia
05-02 12:02:45.810 E/AnkiDroid(14945): 	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles.throwIfEssentialFilesAreMutated(MigrateEssentialFiles.kt:81)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles.execute(MigrateEssentialFiles.kt:88)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles$Companion$migrateEssentialFiles$2.invoke(MigrateEssentialFiles.kt:2)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles$Companion$migrateEssentialFiles$2.invoke(MigrateEssentialFiles.kt:1)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at com.ichi2.anki.exception.RetryableException$Companion.retryOnce(RetryableException.kt:6)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles$Companion.migrateEssentialFiles$AnkiDroid_playRelease(MigrateEssentialFiles.kt:164)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles$Companion.migrateEssentialFiles$AnkiDroid_playRelease$default(MigrateEssentialFiles.kt:6)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at com.ichi2.anki.servicelayer.ScopedStorageService.migrateEssentialFiles(ScopedStorageService.kt:82)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at com.ichi2.anki.DeckPicker$migrate$1$elapsedMillisDuringEssentialFilesMigration$1$1$1.invokeSuspend(DeckPicker.kt:49)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
05-02 12:02:45.810 E/AnkiDroid(14945): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
```
</details>

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/blob/c0d004b511332e3c755aabcc6a0d435296fd66a6/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFiles.kt#L167-L175

This means that [FileUtils.contentEquals](https://commons.apache.org/proper/commons-io/javadocs/api-2.4/org/apache/commons/io/FileUtils.html#contentEquals(java.io.File,%20java.io.File)) returns false.

I would have expected that a `.nomedia` file is a zero length file. Especially as we performed the copy operation ourselves.

**Comment by mikehardy** [comment]
verified that file contents on `.nomedia` file are unimportant. So if this keeps popping up for some reason, perhaps we could parameterize the checks we wanted on file equality and turn off the check for contents / length. As long as the file either exists in both places or does not exist in both places, and is a file, it is equivalent in the eyes of android system as far as I can tell

**Comment by oakkitten** [comment]
That one user who keeps the work of their life in a `.nomedia` file is going to be get a bitter surprise 😔

**Comment by david-allison** [comment]
No reproduction on beta 2 yet.
