### ISSUE TITLE
Full sync lost internet connection has a wrong error message

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13867]
Running on 3fe7c1a2b3c7ed88747f82d2eac425fe252b5198

How to reproduce:
* force full sync
* start full sync
* stop internet on your device

Expected result:
* lost internet connection message

Actual result:
* The downloaded file couldn't be saved to your storage. Either the storage is read-only or there isn't enough space.

```
2023-05-16 04:41:34.900 28683-1018  FullSyncer              com.ichi2.anki.debug                 E  Full sync failed to download collection.
  java.net.SocketException: Software caused connection abort
  at java.net.SocketInputStream.socketRead0(Native Method)
  at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
  at java.net.SocketInputStream.read(SocketInputStream.java:173)
  at java.net.SocketInputStream.read(SocketInputStream.java:143)
  at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
  at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
  at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
  at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
  at okio.InputStreamSource.read(JvmOkio.kt:94)
  at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
  at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
  at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
  at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:89)
  at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:618)
  at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
  at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
  at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
  at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
  at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
  at java.lang.Thread.run(Thread.java:1012)
```

**Comment by dae** [comment]
Not sure that's worth looking into, as the legacy sync path is slated for removal from what I gather.

**Comment by Arthur-Milchior** [comment]
I believe it may be worth. Simply because catching the exception and showing a different message is really not hard. And if we don't yet have a correct string, will need it anyway; it's not like the new back-end will keep internet connection alive
