### ISSUE TITLE
NullPointerException in StudyOptionsFragment

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13869]
https://ankidroid.org/acra/app/1/bug/47783/report/9663b7de-873b-436c-acad-b100aa7aee4b

```
java.lang.NullPointerException
	at com.ichi2.anki.StudyOptionsFragment.rebuildUi(StudyOptionsFragment.kt:41)
	at com.ichi2.anki.StudyOptionsFragment.access$rebuildUi(StudyOptionsFragment.kt:1)
	at com.ichi2.anki.StudyOptionsFragment$refreshInterface$1.invokeSuspend(StudyOptionsFragment.kt:51)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

Probably related with a warning at end of logcat
```

05-15 03:07:04.280 I/AnkiDroid( 2365): Starting Migrate User Data Service
05-15 03:07:04.291 I/AnkiDroid( 2365): No startup screens required
05-15 03:07:04.291 W/AnkiDroid( 2365): ActivityThread/ onStartCommand(Intent { cmp=com.ichi2.anki/.services.MigrationService }, ...)
05-15 03:07:04.294 W/AnkiDroid( 2365): BackupManager$Companion/ Collection is already open during backup... we probably shouldn't be doing this
05-15 03:07:04.294 I/AnkiDroid( 2365): Launching new thread to backup /storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid1/collection.anki2 to /storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid1/backup/collection-2023-05-15-03-07.colpkg
05-15 03:07:04.295 I/AnkiDroid( 2365): Starting Migrate User Data Service
05-15 03:07:04.298 I/AnkiDroid( 2365): Updating deck list UI
05-15 03:07:04.355 W/AnkiDroid( 2365): ActivityThread/ onStartCommand(Intent { cmp=com.ichi2.anki/.services.MigrationService }, ...)
05-15 03:07:04.355 W/AnkiDroid( 2365): ActivityThread/ MigrationService.onStartCommand has been called twice
05-15 03:07:04.377 I/AnkiDroid( 2365): Updating deck list UI
05-15 03:07:04.507 I/AnkiDroid( 2365): Backup created successfully
```

**Comment by RobozinhoD** [comment]
Ill take a look

**Comment by Arthur-Milchior** [comment]
Hi @RobozinhoD
Nice to meet you.
Let us know if you can do anything about it. As you may know, we are trying to work quickly to release on stable. So if you don't have time in the next few days, let us know
