### ISSUE TITLE
BackendCollectionAlreadyOpenException on beta 2

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13864]
On https://ankidroid.org/acra/app/1/bug/48279/report/8c861503-9bf3-4cac-9851-bdd3d9d9d835

```
net.ankiweb.rsdroid.exceptions.BackendInvalidInputException$BackendCollectionAlreadyOpenException: CollectionAlreadyOpen
	at net.ankiweb.rsdroid.exceptions.BackendInvalidInputException$Companion.fromInvalidInputError(BackendInvalidInputException.kt:20)
	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:99)
	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:38)
	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:2)
	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:1)
	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:13)
	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:16)
	at anki.backend.GeneratedBackend.openCollectionRaw(GeneratedBackend.kt:9)
	at anki.backend.GeneratedBackend.openCollection(GeneratedBackend.kt:45)
	at net.ankiweb.rsdroid.Backend.openCollection(Backend.kt:9)
	at net.ankiweb.rsdroid.Backend.openCollection(Backend.kt:8)
	at com.ichi2.libanki.Storage.openDB$AnkiDroid_playRelease(Storage.kt:36)
	at com.ichi2.libanki.Collection.reopen(Collection.kt:28)
	at com.ichi2.libanki.Collection.reopen$default(Collection.kt:8)
	at com.ichi2.async.Connection.doInBackgroundSync(Connection.kt:402)
	at com.ichi2.async.Connection.doOneInBackground(Connection.kt:12)
	at com.ichi2.async.Connection.doInBackground(Connection.kt:4)
	at com.ichi2.async.Connection.doInBackground(Connection.kt:1)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

I'm confused, as I can't find "BackendInvalidInputException" in Ankidroid, ankidroid-backend or anki code. Except once as a comment to note a test is flaky

**Comment by dae** [comment]
Anki's backend will return CollectionAlreadyOpen if backend.openCollection() is called more than once without explicitly or implictly closing the previously-opened collection first. It's mapped to Android in `BackendError.Kind.INVALID_INPUT -> return BackendInvalidInputException.fromInvalidInputError(error)`, but that's not really relevant - the important part is that the frontend code is attempting to open a collection when one is already open.
