### ISSUE TITLE
MigrateEssentialFiles lead to BackendDbLockedException

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13870]
https://ankidroid.org/acra/app/1/bug/47721/report/9c797c94-e377-447e-af9f-f0af5259ea7a

```

net.ankiweb.rsdroid.BackendException$BackendDbException$BackendDbLockedException: Anki already open, or media currently syncing.
	at net.ankiweb.rsdroid.BackendException$BackendDbException$Companion.fromDbError(BackendException.kt:87)
	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:160)
	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:38)
	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:2)
	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:1)
	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:13)
	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:16)
	at anki.backend.GeneratedBackend.openCollectionRaw(GeneratedBackend.kt:9)
	at anki.backend.GeneratedBackend.openCollection(GeneratedBackend.kt:45)
	at net.ankiweb.rsdroid.Backend.openCollection(Backend.kt:9)
	at net.ankiweb.rsdroid.Backend.openCollection(Backend.kt:8)
	at com.ichi2.libanki.Storage.openDB$AnkiDroid_playRelease(Storage.kt:36)
	at com.ichi2.libanki.Collection.reopen(Collection.kt:28)
	at com.ichi2.libanki.Collection.reopen$default(Collection.kt:8)
	at com.ichi2.libanki.Collection.<init>(Collection.kt:50)
	at com.ichi2.libanki.CollectionV16.<init>(CollectionV16.kt:16)
	at com.ichi2.libanki.Storage.collection(Storage.kt:44)
	at com.ichi2.anki.CollectionHelper.openCollection(CollectionHelper.kt:26)
	at com.ichi2.anki.CollectionHelper.getColFromPath(CollectionHelper.kt:30)
	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles.throwIfCollectionIsCorrupted(MigrateEssentialFiles.kt:15)
	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles.execute(MigrateEssentialFiles.kt:39)
	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles$Companion$migrateEssentialFiles$2.invoke(MigrateEssentialFiles.kt:2)
	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles$Companion$migrateEssentialFiles$2.invoke(MigrateEssentialFiles.kt:1)
	at com.ichi2.anki.exception.RetryableException$Companion.retryOnce(RetryableException.kt:6)
	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles$Companion.migrateEssentialFiles$AnkiDroid_playRelease(MigrateEssentialFiles.kt:164)
	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles$Companion.migrateEssentialFiles$AnkiDroid_playRelease$default(MigrateEssentialFiles.kt:6)
	at com.ichi2.anki.servicelayer.ScopedStorageService.migrateEssentialFiles(ScopedStorageService.kt:82)
	at com.ichi2.anki.DeckPicker$migrate$1$elapsedMillisDuringEssentialFilesMigration$1$1$1.invokeSuspend(DeckPicker.kt:49)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
```
What's particularly interesting is that this exception appear twice in the logcat, one just after the other. I wonder whether it mean the migration was started twice

Different stack trace in https://ankidroid.org/acra/app/1/bug/47376/report/4a468736-2b8b-48cb-93cc-7e34a5684978
```
net.ankiweb.rsdroid.BackendException$BackendDbException$BackendDbLockedException: Anki already open, or media currently syncing.
	at net.ankiweb.rsdroid.BackendException$BackendDbException$Companion.fromDbError(BackendException.kt:87)
	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:160)
	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:38)
	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:2)
	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:1)
	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:13)
	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:16)
	at anki.backend.GeneratedBackend.openCollectionRaw(GeneratedBackend.kt:9)
	at anki.backend.GeneratedBackend.openCollection(GeneratedBackend.kt:45)
	at net.ankiweb.rsdroid.Backend.openCollection(Backend.kt:9)
	at net.ankiweb.rsdroid.Backend.openCollection(Backend.kt:8)
	at com.ichi2.libanki.Storage.openDB$AnkiDroid_playRelease(Storage.kt:36)
	at com.ichi2.libanki.Collection.reopen(Collection.kt:28)
	at com.ichi2.libanki.Collection.reopen$default(Collection.kt:8)
	at com.ichi2.libanki.Collection.<init>(Collection.kt:50)
	at com.ichi2.libanki.Storage.collection(Storage.kt:33)
	at com.ichi2.anki.CollectionHelper.openCollection(CollectionHelper.kt:26)
	at com.ichi2.anki.CollectionHelper.getColFromPath(CollectionHelper.kt:30)
	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles.throwIfCollectionIsCorrupted(MigrateEssentialFiles.kt:15)
	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles.execute(MigrateEssentialFiles.kt:39)
	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles$Companion$migrateEssentialFiles$2.invoke(MigrateEssentialFiles.kt:2)
	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles$Companion$migrateEssentialFiles$2.invoke(MigrateEssentialFiles.kt:1)
	at com.ichi2.anki.exception.RetryableException$Companion.retryOnce(RetryableException.kt:6)
	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles$Companion.migrateEssentialFiles$AnkiDroid_playRelease(MigrateEssentialFiles.kt:164)
	at com.ichi2.anki.servicelayer.scopedstorage.MigrateEssentialFiles$Companion.migrateEssentialFiles$AnkiDroid_playRelease$default(MigrateEssentialFiles.kt:6)
	at com.ichi2.anki.servicelayer.ScopedStorageService.migrateEssentialFiles(ScopedStorageService.kt:82)
	at com.ichi2.anki.DeckPicker$migrate$1$elapsedMillisDuringEssentialFilesMigration$1$1$1.invokeSuspend(DeckPicker.kt:49)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
```
This time it only appears once

**Comment by dae** [comment]
My first guess would be this is caused by CollectionHelper.openCollection(), which is called by CollectionTask. When opening a collection via CollectionManager, it ensures that the same backend is reused (so you'd get an 'already open' message if the collection had previously been opened). CollectionHelper.openCollection() appears to create a new backend each time, which could lead to a locked message if the collection had already been opened by the previous backend instance.

**Comment by dae** [comment]
I misspoke - the call chain is openCollection() <- getColFromPath() <- throwIfCollectionIsCorrupted(), which is called here, and further below in that function: https://github.com/ankidroid/Anki-Android/blob/6c5c663917ef9f92ccb3d8dd83796a86a9a2ee6f/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFiles.kt#L116

If we assume it's the first call that fails immediately after a close, that does seem to imply the migration is being called twice. One possibly-related thing I noticed is that execute() checks for userMigrationIsInProgress() at the top, but that boolean is apparently set at the media file migration stage, so presumably would not prevent the essential file migration from being launched twice.
