### ISSUE TITLE
[Acra] save note: NullPointerException

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13874]
https://ankidroid.org/acra/app/1/bug/50185/report/4baff85a-5631-4b23-9525-2e7e42df88be

```

java.lang.NullPointerException
	at com.ichi2.libanki.Collection.getDb(Collection.kt:3)
	at com.ichi2.libanki.Note.dupeOrEmpty(Note.kt:104)
	at com.ichi2.anki.NoteEditor.setDuplicateFieldStyles(NoteEditor.kt:32)
	at com.ichi2.anki.NoteEditor.access$setDuplicateFieldStyles(NoteEditor.kt:1)
	at com.ichi2.anki.NoteEditor$EditFieldTextWatcher.afterTextChanged(NoteEditor.kt:18)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:11911)
	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:15283)
	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1291)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:591)
	at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:7)
	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:232)
	at androidx.emoji2.text.SpannableBuilder.delete(SpannableBuilder.java:2)
	at androidx.emoji2.text.SpannableBuilder.delete(SpannableBuilder.java:1)
	at android.text.method.BaseKeyListener.backspaceOrForwardDelete(BaseKeyListener.java:376)
	at android.text.method.BaseKeyListener.backspace(BaseKeyListener.java:71)
	at android.text.method.BaseKeyListener.onKeyDown(BaseKeyListener.java:485)
	at android.text.method.QwertyKeyListener.onKeyDown(QwertyKeyListener.java:362)
	at android.text.method.TextKeyListener.onKeyDown(TextKeyListener.java:141)
	at android.widget.TextView.doKeyDown(TextView.java:9503)
	at android.widget.TextView.onKeyDown(TextView.java:9275)
	at android.view.KeyEvent.dispatch(KeyEvent.java:3508)
	at android.view.View.dispatchKeyEvent(View.java:15395)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1978)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1978)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1978)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1978)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1978)
	at android.widget.ScrollView.dispatchKeyEvent(ScrollView.java:738)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1978)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1978)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1978)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1978)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1978)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1978)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1978)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:1105)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1961)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4342)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:1)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:11)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:19)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:23)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:3)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:22)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:929)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:8056)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7864)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7213)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7270)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7236)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7434)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7244)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7491)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7217)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7270)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7236)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7244)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7217)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10788)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10676)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10632)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl(ViewRootImpl.java:6822)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:6697)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

Interestingly enough, there is no `withCol`; so it may be relatively simple to solve if we can add it.

The logcat contains nothing appart from the stack trace and the information that the user pressed "save note". So maybe we are missing important context

Surely related because same installation:

https://ankidroid.org/acra/app/1/bug/50184/report/30ae0d98-34f8-41dc-8717-53ea17555717
```

java.lang.NullPointerException
	at com.ichi2.libanki.Collection.getDb(Collection.kt:3)
	at com.ichi2.libanki.Note.preFlush(Note.kt:3)
	at com.ichi2.libanki.Note.flush(Note.kt:6)
	at com.ichi2.libanki.Note.flush$default(Note.kt:11)
	at com.ichi2.libanki.Collection.addNote(Collection.kt:25)
	at com.ichi2.anki.NoteEditor$saveNote$noOfAddedCards$1$1$1.invoke(NoteEditor.kt:2)
	at com.ichi2.anki.NoteEditor$saveNote$noOfAddedCards$1$1$1.invoke(NoteEditor.kt:1)
	at com.ichi2.libanki.DB.executeInTransaction(DB.kt:11)
	at com.ichi2.anki.NoteEditor$saveNote$noOfAddedCards$1$1.invoke(NoteEditor.kt:4)
	at com.ichi2.anki.NoteEditor$saveNote$noOfAddedCards$1$1.invoke(NoteEditor.kt:1)
	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:3)
	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:1)
	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
```

**Comment by SanjaySargam** [comment]
Working on it

**Comment by SanjaySargam** [comment]
@Arthur-Milchior where we have to write `withCol`
Will you guide me ?
