### ISSUE TITLE
Reviewer cannot be cast to DeckPicker

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13871]
Most obvious error message ever.
Plus, verry simple stack trace.

```
java.lang.ClassCastException: com.ichi2.anki.Reviewer cannot be cast to com.ichi2.anki.DeckPicker
	at com.ichi2.anki.dialogs.DialogHandler.handleMessage(DialogHandler.kt:49)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

https://ankidroid.org/acra/app/1/bug/50029/report/907ec356-91a3-4506-8688-7acf5162905a

According to logcat it occured just after showing a question to the user and doing `DoSyncDialog` (how can sync and question be done simultaneously?)

**Comment by david-allison** [comment]
#5075
