### ISSUE TITLE
[BUG]: Crash at manage note types dialog

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#13932]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Deck picker > Three dot menu > Manage note types
2. Long tap a model
3. Select any option (e.g. Edit cards)
4. Go back to the dialog
5. Select another option

### Expected behaviour

Not crash

### Actual behaviour

Crash

### Debug info

```text
AnkiDroid Version = 2.16.0beta2-debug

Android Version = 10

ProductFlavor = play

Manufacturer = Google

Model = Android SDK built for x86

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Android SDK built for x86 Build/QSR1.190920.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.185 Mobile Safari/537.36

ACRA UUID = ea94d2f6-2d9d-4310-ad6e-75077840a7eb

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

build of 4bf20841919102d96c1370e0b29ac79eb6366b4d
```
FATAL EXCEPTION: main
                                                                                                    Process: com.ichi2.anki.debug, PID: 5674
                                                                                                    java.lang.IllegalStateException: Fragment ModelBrowserContextMenu{acb1560} (b26b7c4e-0028-456e-b78f-ef152eaf2e8e) not attached to an activity.
                                                                                                    	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:998)
                                                                                                    	at com.ichi2.anki.dialogs.ModelBrowserContextMenu.onCreateDialog$lambda$4$lambda$3(ModelBrowserContextMenu.kt:26)
                                                                                                    	at com.ichi2.anki.dialogs.ModelBrowserContextMenu.$r8$lambda$ZoWKlAGBz1UrmU-bAjxySH2Q4SY(Unknown Source:0)
                                                                                                    	at com.ichi2.anki.dialogs.ModelBrowserContextMenu$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
                                                                                                    	at androidx.appcompat.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1068)
                                                                                                    	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
                                                                                                    	at android.widget.AbsListView.performItemClick(AbsListView.java:1257)
                                                                                                    	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3270)
                                                                                                    	at android.widget.AbsListView$3.run(AbsListView.java:4236)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by RobozinhoD** [comment]
i want to work on irt

**Comment by criticalAY** [comment]
I can't reproduce it tried multiple times but didn't crash

**Comment by BrayanDSO** [comment]
wrong caching I guess. Couldn't reproduce anymore either. Closing this
