### ISSUE TITLE
2.16.0beta2: java.lang.NullPointerException: findViewById(R.id.toolbar_spinner) must not be null

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#13973]
```
java.lang.NullPointerException: findViewById(R.id.toolbar_spinner) must not be null
	at com.ichi2.anki.CardBrowser.onCollectionLoaded(CardBrowser.kt:211)
	at com.ichi2.anki.AnkiActivity.startLoadingCollection$lambda$0(AnkiActivity.kt:18)
	at com.ichi2.anki.AnkiActivity.i(AnkiActivity.kt:1)
	at com.ichi2.anki.u0.execute(R8$$SyntheticClass:3)
	at com.ichi2.async.CollectionLoader$load$1.invokeSuspend(CollectionLoader.kt:68)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@acba608, Dispatchers.Main.immediate]
```
Android 13 Pixel 4a
https://ankidroid.org/acra/app/1/bug/53957/report/59c86125-b58d-450f-b598-f380b45955fa

**Comment by BrayanDSO** [comment]
Duplicate
