### ISSUE TITLE
java.lang.Exception: invalid call to newBackend on old backend

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#13977]
Android 10, motorola, new backend, v3 scheduler
https://ankidroid.org/acra/app/1/bug/52752/report/f93cadda-e169-4fbc-af23-3c97ceac8241

```
05-31 18:35:06.838 E/AnkiDroid(15299): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
05-31 18:35:06.838 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
05-31 18:35:06.838 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
05-31 18:35:06.838 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
05-31 18:35:06.838 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
05-31 18:35:06.838 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
05-31 18:35:07.381 E/AnkiDroid(15299): CoroutineHelpersKt$runCatchingTask/ java.lang.Exception: invalid call to newBackend on old backend
05-31 18:35:07.381 E/AnkiDroid(15299): 	at com.ichi2.libanki.Collection.getNewBackend(Collection.kt:5)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at com.ichi2.anki.BackendBackupsKt$createBackup$2.invoke(BackendBackups.kt:2)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at com.ichi2.anki.BackendBackupsKt$createBackup$2.invoke(BackendBackups.kt:1)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:3)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:1)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:15)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
05-31 18:35:07.381 E/AnkiDroid(15299): 
05-31 18:35:07.381 E/AnkiDroid(15299): java.lang.Exception: invalid call to newBackend on old backend
05-31 18:35:07.381 E/AnkiDroid(15299): 	at com.ichi2.libanki.Collection.getNewBackend(Collection.kt:5)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at com.ichi2.anki.BackendBackupsKt$createBackup$2.invoke(BackendBackups.kt:2)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at com.ichi2.anki.BackendBackupsKt$createBackup$2.invoke(BackendBackups.kt:1)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:3)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:1)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:15)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
05-31 18:35:07.381 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
05-31 18:35:07.399 E/AnkiDroid(15299): CoroutineHelpersKt$runCatchingTask/ java.lang.Exception: invalid call to newBackend on old backend
05-31 18:35:07.399 E/AnkiDroid(15299): 	at com.ichi2.libanki.Collection.getNewBackend(Collection.kt:5)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at com.ichi2.anki.BackendBackupsKt$createBackup$2.invoke(BackendBackups.kt:2)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at com.ichi2.anki.BackendBackupsKt$createBackup$2.invoke(BackendBackups.kt:1)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:3)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:1)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:15)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
05-31 18:35:07.399 E/AnkiDroid(15299): 
05-31 18:35:07.399 E/AnkiDroid(15299): java.lang.Exception: invalid call to newBackend on old backend
05-31 18:35:07.399 E/AnkiDroid(15299): 	at com.ichi2.libanki.Collection.getNewBackend(Collection.kt:5)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at com.ichi2.anki.BackendBackupsKt$createBackup$2.invoke(BackendBackups.kt:2)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at com.ichi2.anki.BackendBackupsKt$createBackup$2.invoke(BackendBackups.kt:1)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:3)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:1)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:15)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
05-31 18:35:07.399 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
05-31 18:35:12.594 E/AnkiDroid(15299): CoroutineHelpersKt$runCatchingTask/ java.lang.Exception: invalid call to newBackend on old backend
05-31 18:35:12.594 E/AnkiDroid(15299): 	at com.ichi2.libanki.Collection.getNewBackend(Collection.kt:5)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at com.ichi2.libanki.ChangeManagerKt$undoableOp$2.invoke(ChangeManager.kt:2)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at com.ichi2.libanki.ChangeManagerKt$undoableOp$2.invoke(ChangeManager.kt:1)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:3)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:1)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:15)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
05-31 18:35:12.594 E/AnkiDroid(15299): 
05-31 18:35:12.594 E/AnkiDroid(15299): java.lang.Exception: invalid call to newBackend on old backend
05-31 18:35:12.594 E/AnkiDroid(15299): 	at com.ichi2.libanki.Collection.getNewBackend(Collection.kt:5)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at com.ichi2.libanki.ChangeManagerKt$undoableOp$2.invoke(ChangeManager.kt:2)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at com.ichi2.libanki.ChangeManagerKt$undoableOp$2.invoke(ChangeManager.kt:1)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:3)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:1)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:15)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
05-31 18:35:12.594 E/AnkiDroid(15299): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
```

**Comment by BrayanDSO** [comment]
new backend issue, so 2.17 problem

**Comment by dae** [comment]
legacy_schema = true in the report, but createBackup should only be called when it's false. Does the migration code force the schema to legacy? If so, perhaps this user had legacy=false, and was waiting in performBackupInBackground(), and the schema version was changed during the delay. That, or perhaps updateDeckList() was called as the user was in the preferences screen adjusting options?

**Comment by dae** [comment]
:man_facepalming: sorry, I was reading the build config instead of the preference. Not sure what's going on here then :-)

**Comment by BrayanDSO** [comment]
I'll close this since the new backend is the default now.
