### ISSUE TITLE
2.16.0beta2: java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<T of com.ichi2.utils.TypedFilter>

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#13974]
```
java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<T of com.ichi2.utils.TypedFilter>
	at com.ichi2.utils.TypedFilter.publishResults(TypedFilter.kt:8)
	at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:284)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
Android 13 sony
https://ankidroid.org/acra/app/1/bug/53861/report/6ab129d8-eccb-43a1-a82d-270eb9dbad86

**Comment by Arthur-Milchior** [comment]
Probably related to tag filter, given the last logs
