### ISSUE TITLE
2.16 java.lang.NullPointerException: findViewById(R.id.toolbar_spinner) must not be null

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14029]
```
java.lang.NullPointerException: findViewById(R.id.toolbar_spinner) must not be null
	at com.ichi2.anki.CardBrowser.onCollectionLoaded(CardBrowser.kt:211)
	at com.ichi2.anki.AnkiActivity.startLoadingCollection$lambda$0(AnkiActivity.kt:18)
	at com.ichi2.anki.AnkiActivity.i(AnkiActivity.kt:1)
	at com.ichi2.anki.u0.execute(R8$$SyntheticClass:3)
	at com.ichi2.async.CollectionLoader$load$1.invokeSuspend(CollectionLoader.kt:68)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8290)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3d80540, Dispatchers.Main.immediate]
```
https://ankidroid.org/acra/app/1/bug/55984/report/f59e998c-1c9a-42bd-b29c-d3033cf7f045

**Comment by BrayanDSO** [comment]
Duplicate
