### ISSUE TITLE
2.16beta03 java.lang.IllegalArgumentException: Invalid UUID string

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14027]
```
java.lang.IllegalArgumentException: Invalid UUID string: 0000000000000000000000000000CAFEF00D2019
	at java.util.UUID.fromString(UUID.java:194)
	at com.ichi2.anki.ui.windows.managespace.FileUtilsKt.getUserDataAndCacheSizeUsingStorageStatsManager$getValidUuid(FileUtils.kt:23)
	at com.ichi2.anki.ui.windows.managespace.FileUtilsKt.getUserDataAndCacheSizeUsingStorageStatsManager(FileUtils.kt:64)
	at com.ichi2.anki.ui.windows.managespace.FileUtilsKt.getUserDataAndCacheSize(FileUtils.kt:7)
	at com.ichi2.anki.ui.windows.managespace.ManageSpaceViewModel$launchCalculationOfSizeOfEverything$1$1.invokeSuspend(ManageSpaceFragment.kt:35)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f8adbe5, Dispatchers.Main.immediate]
```
Android 11, legacy backend
https://ankidroid.org/acra/app/1/bug/56027/report/07245a52-1d9d-4a92-83a9-a00c21f0124a

**Comment by BrayanDSO** [comment]
Pinging @oakkitten because of the work on the  manage space activity

**Comment by oakkitten** [comment]
Oh God, well, that's clearly not a valid UUID string. But what is it? Certainly isn't random and Google can find a few of those but still not clear what it is. In theory, we can try to treat this as a simple hex number since UUIDs are techinally just numbers. But who knows if this will work.
