### ISSUE TITLE
2.16.0beta4 `ConcurrentModificationExceptions`

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14066]
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.util.ConcurrentModificationException
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
	at java.util.LinkedList$ListItr.next(LinkedList.java:888)
	at j$.util.Collection$-CC.$default$removeIf(Unknown Source:27)
	at j$.util.Collection$-EL.removeIf(Unknown Source:11)
	at com.ichi2.libanki.sched.CardQueue.remove(CardQueue.kt:13)
	at com.ichi2.libanki.sched.SchedV2.setCurrentCard(SchedV2.kt:92)
	at com.ichi2.libanki.sched.SchedV2.getCard(SchedV2.kt:49)
	at com.ichi2.anki.servicelayer.SchedulerService$GetCard$Companion.getCard(SchedulerService.kt:24)
	at com.ichi2.anki.servicelayer.SchedulerService$GetCard.execute(SchedulerService.kt:2)
	at com.ichi2.anki.servicelayer.SchedulerService$GetCard.execute(SchedulerService.kt:1)
	at com.ichi2.anki.servicelayer.AnkiTask.execute(AsyncLayer.kt:8)
	at com.ichi2.anki.servicelayer.AsyncLayerAdapterKt$asDelegate$1.task(AsyncLayerAdapter.kt:18)
	at com.ichi2.async.TaskDelegate.execTask(TaskDelegate.kt:11)
	at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.kt:229)
	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.kt:2)
	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.kt:1)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
```
https://ankidroid.org/acra/app/1/bug/56734/report/14edf93f-ed84-406a-8c36-706be753c3dd

**Comment by BrayanDSO** [comment]
Based on the stacktrace and the timing that the error appeared, I'm going to point at https://github.com/ankidroid/Anki-Android/commit/614b31434e987523ae3220f409fc1b5721f8b0eb#diff-dc3d0158a31e3414efd9b630b24220cbdb75fdabd6edc1932599c172ca7a03f9R43-R45

I'll revert it, since it was supposed to be a NF change

**Comment by mikehardy** [comment]
Sounds plausible - I don't remember seeing them before, and that's new. Revert sounds good

**Comment by BrayanDSO** [comment]
Going to include https://ankidroid.org/acra/app/1/bug/52580/report/524d1cff-c798-4102-afb5-15750e03064e here since it is caused by the same method

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.util.NoSuchElementException
	at java.util.LinkedList.removeFirst(LinkedList.java:274)
	at java.util.LinkedList.remove(LinkedList.java:689)
	at com.ichi2.libanki.sched.CardQueue.removeFirstCard(CardQueue.kt:3)
	at com.ichi2.libanki.sched.SchedV2._getRevCard(SchedV2.kt:9)
	at com.ichi2.libanki.sched.SchedV2._getCard(SchedV2.kt:50)
	at com.ichi2.libanki.sched.SchedV2.getCard(SchedV2.kt:12)
	at com.ichi2.anki.servicelayer.SchedulerService$GetCard$Companion.getCard(SchedulerService.kt:24)
	at com.ichi2.anki.servicelayer.SchedulerService$GetCard.execute(SchedulerService.kt:2)
	at com.ichi2.anki.servicelayer.SchedulerService$GetCard.execute(SchedulerService.kt:1)
	at com.ichi2.anki.servicelayer.AnkiTask.execute(AsyncLayer.kt:8)
	at com.ichi2.anki.servicelayer.AsyncLayerAdapterKt$asDelegate$1.task(AsyncLayerAdapter.kt:18)
	at com.ichi2.async.TaskDelegate.execTask(TaskDelegate.kt:11)
	at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.kt:229)
	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.kt:2)
	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.kt:1)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 4 more
```
