### ISSUE TITLE
[Bug] FileNotFoundException when trying to add a image to a field

### ISSUE THREAD

**Issue by lukstbit** [ankidroid/Anki-Android#14082]
[https://ankidroid.org/acra/app/1/bug/57467/report/36dc89e9-5c2d-4fec-8589-a70cd0a336eb](https://ankidroid.org/acra/app/1/bug/57467/report/36dc89e9-5c2d-4fec-8589-a70cd0a336eb)
```

java.lang.IllegalArgumentException: java.io.FileNotFoundException: Failed to validate: content://media/external/images/media/1000001387
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
	at android.content.ContentResolver.query(ContentResolver.java:1219)
	at android.content.ContentResolver.query(ContentResolver.java:1151)
	at androidx.core.content.ContentResolverCompat$Api16Impl.query(Unknown Source:0)
	at androidx.core.content.ContentResolverCompat.query(SourceFile:20)
	at com.ichi2.anki.multimediacard.fields.BasicImageFieldController.getImageNameFromContentResolver(SourceFile:30)
	at com.ichi2.anki.multimediacard.fields.BasicImageFieldController.getImageNameFromUri(SourceFile:146)
	at com.ichi2.anki.multimediacard.fields.BasicImageFieldController.internalizeUri(SourceFile:5)
	at com.ichi2.anki.multimediacard.fields.BasicImageFieldController.handleSelectImageIntent(SourceFile:92)
	at com.ichi2.anki.multimediacard.fields.BasicImageFieldController.onActivityResult(SourceFile:88)
	at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.onActivityResult(SourceFile:18)
	at android.app.Activity.dispatchActivityResult(Activity.java:8664)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5328)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5374)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

Android 13, Pixel phone
Legacy backend

**Comment by david-allison** [comment]
Issue was on a Pixel 6 - likely not a manufacturer issue
