### ISSUE TITLE
java.lang.NumberFormatException: For input string: ""1688546411954""

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14096]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.NoteEditor}: java.lang.NumberFormatException: For input string: ""1688546411954""
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3834)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3980)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2394)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8294)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.NumberFormatException: For input string: ""1688546411954""
	at java.lang.Long.parseLong(Long.java:722)
	at java.lang.Long.parseLong(Long.java:861)
	at com.ichi2.libanki.ConfigV16.getLong(SourceFile:12)
	at com.ichi2.libanki.Collection.get_config_long(SourceFile:11)
	at com.ichi2.anki.NoteEditor.setDid(SourceFile:81)
	at com.ichi2.anki.NoteEditor.onCollectionLoaded(SourceFile:333)
	at com.ichi2.anki.AnkiActivity.startLoadingCollection(SourceFile:28)
	at com.ichi2.anki.NoteEditor.onCreate(SourceFile:253)
	at android.app.Activity.performCreate(Activity.java:8522)
	at android.app.Activity.performCreate(Activity.java:8486)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1438)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3815)
	... 12 more
```
2.16.0beta5, new backend, Android 13
https://ankidroid.org/acra/app/1/bug/57860/report/26d7efca-dc5e-4707-b740-0973589373bb

**Comment by david-allison** [comment]
Anki Desktop:

```
mw.col.conf.set("a", '"' + "1688546411954" + '"')
pp(mw.col.conf.get("a"))
pp(int(mw.col.conf.get("a")))
```

```
>>> mw.col.conf.set("a", '"' + "1688546411954" + '"')
... pp(mw.col.conf.get("a"))
... pp(int(mw.col.conf.get("a")))
'"1688546411954"'
Traceback (most recent call last):
  File "aqt.debug_console", line 294, in onDebugRet
  File "<string>", line 3, in <module>
ValueError: invalid literal for int() with base 10: '"1688546411954"'
```

----

AnkiDroid: the issue was almost certainly in a line:

```diff
- deckId = col.get_config_long(CURRENT_DECK)
+ deckId = getColUnsafe.config.get(CURRENT_DECK) ?: 1
```

Fixed in https://github.com/ankidroid/Anki-Android/pull/14171 7a65160e0e23e20080091a30abdd4c05fc610e06 (a6dce65ab5ac2c43783bfc0b96ee7ec00393121e)
