### ISSUE TITLE
[BUG]: Crash report after sync: NullPointerException: Note.load

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#14213]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

* Sync from AnkiWeb
* Stop sync during media sync
* Click a deck
  * Crash
* Reopen AnkiDroid
  * Error report  

### Expected behaviour

App functions normally

### Actual behaviour

After the sync, all review counts are set to 0

Clicking a deck crashes

Opening the app crashes

### Debug info

```text
AnkiDroid Version = 2.16.2

Android Version = 13

ProductFlavor = play

Manufacturer = samsung

Model = SM-G991B

Hardware = exynos2100

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-G991B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.138 Mobile Safari/537.36

ACRA UUID = a9e94fc5-c79e-4326-94e3-b4010c7dbe30

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

https://ankidroid.org/acra/app/1/bug/58231/report/913ecef0-1818-48b7-9096-fa89cdba153d

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException
	at com.ichi2.libanki.Note.load(SourceFile:137)
	at com.ichi2.libanki.Note.<init>(SourceFile:4)
	at com.ichi2.libanki.Collection.getNote(Unknown Source:2)
	at com.ichi2.libanki.Card.note(SourceFile:3)
	at com.ichi2.libanki.Collection.render_output_legacy(SourceFile:8)
	at com.ichi2.libanki.Collection.render_output(SourceFile:6)
	at com.ichi2.libanki.Card.render_output(SourceFile:9)
	at com.ichi2.libanki.Card.render_output$default(Unknown Source:13)
	at com.ichi2.anki.servicelayer.SchedulerService$GetCard$Companion.getCard(SourceFile:33)
	at com.ichi2.anki.servicelayer.SchedulerService$GetCard.execute(SourceFile:2)
	at com.ichi2.anki.servicelayer.SchedulerService$GetCard.execute(SourceFile:1)
	at com.ichi2.anki.servicelayer.AnkiTask.execute(SourceFile:2)
	at com.ichi2.anki.servicelayer.AsyncLayerAdapterKt$asDelegate$1.task(SourceFile:18)
	at com.ichi2.async.TaskDelegate.execTask(SourceFile:11)
	at com.ichi2.async.CollectionTask.actualDoInBackground(SourceFile:229)
	at com.ichi2.async.CollectionTask.doInBackground(SourceFile:2)
	at com.ichi2.async.CollectionTask.doInBackground(SourceFile:1)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 4 more
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
After reopening the app (third time), this no longer occurs and things seem normal

**Comment by criticalAY** [comment]
reproduced working on it

**Comment by criticalAY** [comment]
it works (crashes) only on fresh installs I am unable to see the crash once the app is reponed and sync is cancelled again
