### ISSUE TITLE
[BUG]: Ankidroid 2.17alpha3 + tts + previewer (Note Editor) + 5 seconds: crash

### ISSUE THREAD

**Issue by khonkhortisan** [ankidroid/Anki-Android#14692]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- Ankidroid 2.17alpha3
- enable config→advanced→tts
- open the previewer
  - deck list→open a deck→✏→👁 or
  - ≡→browser→select a card→👁

It's like TTS crash if TTS initialization fails #5067 but only happens during preview.
It's like Previewing a note breaks TTS #8085 but I don't have to leave the previewer and review cards and it's Anki itself that crashes instead of tts going mute. 

### Expected behaviour

previewer would show the card like the reviewer, tts would read the text like in the reviewer

### Actual behaviour

tts works in the reviewer but not the previewer
the previewer works with tts disabled but not with tts enabled
with tts enabled, the previewer crashes to the home screen within about 3-5 seconds of opening it
Preview-from-reviewer: (open ankidroid→deckname→✏→👁)
- shows ←deckname and show answer and initializing tts
- doesn't show card content
- doesn't register taps on show answer
- doesn't register taps on the back button
- crashes ankidroid

Preview-from-browser: (open ankidroid→≡→browser→select a card→👁)
- shows ←deckname and show answer and initializing tts
- shows card content
- registers taps on show answer, lighting up the button but not flipping the card
- registers the back button, pressing it early enough will go back to the editor and avoid the crash
  - If I've pressed the back button, opening the previewer a second time will not show card content, not register taps on show answer, and the back button doesn't work, like preview-from-reviewer above.
  - If I've pressed the back button, then go to the reviewer, tts works in the reviewer like normal.
  - None of these reset the previewer-from-brower back to its interactive state: pressing back to leave the previewer, back to leave the card editor, sidebar to go to the deck list, opening the reviewer, reviewing cards, opening the editor-from-reviewer
- crashes ankidroid

Preview-from-add: (open ankidroid→+→add→👁)
- on a cloze overlapper note, card content is blank then says the card is empty then crashes
- interactive the first time like preview-from-browser above
- crashes ankidroid
- I was able to press 👁←👁←👁←👁 before it crashed?
- I was able to press 👁←👁←👁←👁 and have ← light up before it crashed
- I was able to press 👁←👁←👁←👁← before it crashed on the editor screen!

Preview-from-browser-add; (open ankidroid→≡→browser→+→👁)
- interactive the first time like preview-from-browser and preview-from-add
- crashes ankidroid

interaction paths:
reviewer→preview→non-interactive→crash
[browser or +::add]→preview→interactive→crash
[browser or +::add]→preview→interactive→back→no crash
[browser or +::add]→preview→interactive→back→…→[browser or +::add or reviewer]→preview→non-interactive→crash
[browser or +::add]→spam preview back→crash in previewer
[browser or +::add]→spam preview back→light up back button→crash in previewer
[browser or +::add]→spam preview back→crash in editor

### Debug info

```text
AnkiDroid Version = 2.17alpha3 (42a8c8c55c200f372b0bd0b462e4b58554b72fe5)

Android Version = 11

ProductFlavor = play

Manufacturer = FIH

Model = EC1002

Hardware = mt6761

Webview User Agent = Mozilla/5.0 (Linux; Android 11; EC1002 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Safari/537.36

ACRA UUID = c8fe5a3e-6bce-4976-867c-42a883891f6b

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

phone: Cricket® Ovation 2, build EC1002_1580→EC1002_1590 (just upgraded while writing this), 30.06→29.52 GB of 32 GB used, physical screen resolution 720x1640, virtual resolution 1080x2460 (1.5 virtual pixels per physical pixel, 2.25 virtual pixel² per physical pixel²) (set by user) (buttons/ui/text/images render smaller and are more difficult to fat-finger, fullscreen video and games stress the gpu more but look the same)
Android System Webview 118.0.5993.111
ankidroid: installed through play store beta program, all notifications allowed, mic allowed while app in use, 5.44 GB used: 77.97 MB app, 5.25 GB user data, 115 MB cache, wifi background/unlimited, not battery optimized, open links: ask

My templates have things like
{{edit:type:cloze:Text125}}  <style/> <script>return;…</script> @import url(_global.css); <span class="hypertts">{{edit:tts en_US hypertts_preset=Back_realtime_14 voices=HyperTTS:cloze-only:Text}}</span> <tts service=Android group="en"><span class="randomLatin"><span class="tags {{Tags}} gender">{{edit:Front}}<br/></span></span></tts> <script type="text/x-mathjax-config">

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
You may want to wait just a moment for TTS testing there is a *ton* of work in progress there to get AnkiDroid TTS to conform to Anki ecosystem TTS #14597 just went in, #14625 is related and just went in, and #14628 I think will finalize it

The issue to subscribe to for final closure is #14358 

Those have not been built in to an alpha yet but I have some time this morning, let me get strings + dependency changes + any ready PRs merged and generate a new alpha, hopefully it closes out some of the issues you've found 🤞

**Comment by david-allison** [comment]
https://ankidroid.org/acra/app/1/bug/96181/report/3440c0e5-cda5-4ba6-a657-50b205e37402

`ReadText.initializeTts` => `Card.q()`

Since this was executed on a card which was previewed, the card question didn't exist

```
net.ankiweb.rsdroid.exceptions.BackendInvalidInputException: no such card
	at net.ankiweb.rsdroid.exceptions.BackendInvalidInputException$Companion.fromInvalidInputError(BackendInvalidInputException.kt:37)
	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:114)
	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:320)
	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:128)
	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:127)
	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:155)
	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:127)
	at anki.backend.GeneratedBackend.renderExistingCardRaw(GeneratedBackend.kt:1579)
	at anki.backend.GeneratedBackend.renderExistingCard(GeneratedBackend.kt:1586)
	at com.ichi2.libanki.TemplateManager$TemplateRenderContext.partiallyRender(TemplateManager.kt:243)
	at com.ichi2.libanki.TemplateManager$TemplateRenderContext.render(TemplateManager.kt:170)
	at com.ichi2.libanki.Card.renderOutput(Card.kt:250)
	at com.ichi2.libanki.Card.q(Card.kt:225)
	at com.ichi2.libanki.Card.q$default(Card.kt:224)
	at com.ichi2.anki.cardviewer.CardHtml$Companion.legacyGetTtsTags(CardHtml.kt:215)
	at com.ichi2.anki.AbstractFlashcardViewer.readCardTts(AbstractFlashcardViewer.kt:1471)
	at com.ichi2.anki.AbstractFlashcardViewer.playSounds(AbstractFlashcardViewer.kt:1458)
	at com.ichi2.anki.AbstractFlashcardViewer.ttsInitialized(AbstractFlashcardViewer.kt:2063)
	at com.ichi2.anki.ReadText.initializeTts$lambda$6(ReadText.kt:253)
	at com.ichi2.anki.ReadText.$r8$lambda$ScdnrALovrxTRF_98sj2UnyLwh8(Unknown Source:0)
	at com.ichi2.anki.ReadText$$ExternalSyntheticLambda0.onInit(Unknown Source:4)
	at android.speech.tts.TextToSpeech.lambda$dispatchOnInit$0$android-speech-tts-TextToSpeech(TextToSpeech.java:890)
	at android.speech.tts.TextToSpeech$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:899)
	at android.speech.tts.TextToSpeech.-$$Nest$mdispatchOnInit(Unknown Source:0)
	at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2280)
	at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2240)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
