### ISSUE TITLE
[Bug] NanoHTTPD: logs: "W/System: A resource failed to call end."

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#14924]
This might not easily be solvable.

<details><summary>Enable strict mode:</summary>

```kotlin
            StrictMode.setVmPolicy(
                VmPolicy.Builder()
                    .detectLeakedClosableObjects()
                    .penaltyLog()
                    .build()
            )
```

</details>

This reveals the stack trace

<details><summary>sendBodyWithCorrectEncoding -> GZIPOutputStream -> Deflater -> end() not called</summary> 

```
StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
	at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1986)
	at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:336)
	at java.util.zip.Deflater.finalize(Deflater.java:575)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:319)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:306)
	at java.lang.Daemons$Daemon.run(Daemons.java:140)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.Throwable: Explicit termination method 'end' not called
	at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:288)
	at dalvik.system.CloseGuard.open(CloseGuard.java:257)
	at java.util.zip.Deflater.<init>(Deflater.java:189)
	at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:98)
	at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:117)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1663)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1654)
	at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1624)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:957)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:1012) 
```

</details>

### NanoHTTPD: sendBodyWithCorrectEncoding

TODO: Find the correct reference, this doesn't match the source on GitHub

```kotlin
        private void sendBodyWithCorrectEncoding(OutputStream outputStream, long pending) throws IOException {
            if (encodeAsGzip) {
                GZIPOutputStream gzipOutputStream = new GZIPOutputStream(outputStream);
                sendBody(gzipOutputStream, -1);
                gzipOutputStream.finish();
            } else {
                sendBody(outputStream, pending);
            }
        }
```

### Android: Deflater

The `Deflater` defines a close guard:

```java
    public Deflater(int level, boolean nowrap) {
        this.level = level;
        this.strategy = DEFAULT_STRATEGY;
        this.zsRef = new ZStreamRef(init(level, DEFAULT_STRATEGY, nowrap));
        // Android-added: CloseGuard support.
        guard.open("end");
    }
```

This `CloseGuard` is closed in `end`, and is warned about if closed from `finalize()`

```java
    public void end() {
        synchronized (zsRef) {
            // Android-added: CloseGuard support.
            guard.close();
            long addr = zsRef.address();
            zsRef.clear();
            if (addr != 0) {
                end(addr);
                buf = null;
            }
        }
    }

    protected void finalize() {
        // Android-added: CloseGuard support.
        if (guard != null) {
            guard.warnIfOpen();
        }
        end();
    }
```

### Android: DeflaterOutputStream/GZIPOutputStream

In Android, `GZipOutputStream` only has `.close` call through to `.end`, and this is not what we want.

`close` ALSO closes the wrapped stream. We just want to 'close' the wrapper in this case, as the output stream may continue to be used

```java
    /**
     * Writes remaining compressed data to the output stream and closes the
     * underlying stream.
     * @exception IOException if an I/O error has occurred
     */
    public void close() throws IOException {
        if (!closed) {
            finish();
            if (usesDefaultDeflater)
                def.end();
            out.close();
            closed = true;
        }
    }
```

So, by using `GZIPOutputStream`, we're guaranteed a warning in `Deflater`

### Version Number
`implementation 'org.nanohttpd:nanohttpd:2.3.1'`
SDK 33/34 source code checked

**Comment by david-allison** [comment]
This is a VM policy, not a ThreadLocal policy. It doesn't seem feasible to log it: `DETECT_VM_CLOSABLE_LEAKS`

```java
            /**
             * Detect when an {@link java.io.Closeable} or other object with an explicit termination
             * method is finalized without having been closed.
             *
             * <p>You always want to explicitly close such objects to avoid unnecessary resources
             * leaks.
             */
            public @NonNull Builder detectLeakedClosableObjects() {
                return enable(DETECT_VM_CLOSABLE_LEAKS);
            }
```

`sLogger` and `ViolationLogger` are marked `@hide`

```java
    /** {@hide} */
    @TestApi
    public interface ViolationLogger {

        /** Called when penaltyLog is enabled and a violation needs logging. */
        void log(ViolationInfo info);
    }
```

**Comment by david-allison** [comment]
Workaround which I'm not going to use. For posterity

```kotlin
fun StrictMode.VmPolicy.Builder.detectAllButCloseable(): VmPolicy.Builder {
    detectLeakedSqlLiteObjects()
    detectActivityLeaks()
    detectLeakedClosableObjects()
    detectLeakedRegistrationObjects()
    detectFileUriExposure()

    // android:usesCleartextTraffic="true" 0
    // detectCleartextNetwork()

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        detectContentUriWithoutPermission()
        detectUntaggedSockets()
    }
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
        detectCredentialProtectedWhileLocked()
    }
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
        detectIncorrectContextUse()
    }
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
        detectUnsafeIntentLaunch()
    }

    return this
}

fun doIt() {
    val policy = VmPolicy.Builder().detectAllButCloseable()
    StrictMode.setVmPolicy(policy.build())
}
```
