### ISSUE TITLE
Crash after opening Statistics

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#15009]
Running 4945a96b8a5188728b9ce4a79317eae5e875313e

Reproduction steps: 
1. Open statistics
2. Crash

logcat
```text
 Caused by: java.lang.IllegalStateException: Fragment Statistics{77fad8b} (7ffc97a8-2cba-4038-8adf-c697c953ef9b id=0x7f090321) not attached to a context.
                                                                                                    	at androidx.fragment.app.Fragment.requireContext(Fragment.java:972)
                                                                                                    	at androidx.fragment.app.Fragment.getResources(Fragment.java:1036)
                                                                                                    	at com.ichi2.anki.pages.Statistics.getTitle(Statistics.kt:38)
                                                                                                    	at com.ichi2.anki.pages.PagesActivity.onCreate(PagesActivity.kt:67)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8051)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8031)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

**Comment by BrayanDSO** [comment]
Cause https://github.com/ankidroid/Anki-Android/commit/b0d66d6eab4a05c7eda11b784cd54fe2cbac417a#diff-e259b6573aa2a5189aae951bb41faf549bb39881476aa159e78ffe33b7244cd4R37-R38

**Comment by mikehardy** [comment]
Nice find @BrayanDSO - super helpful link into the diff

If I search that diff it is a generic problem - Stats is just one instance of it - the title was changed from the resource id to a string and uses the Context to resolve the same way on all the Page activities, so CardInfo, Congratulations, PackageImporter will all crash I think

I believe the correct thing is to revert just that one bit - put the type back to Int? from String and put the raw resource ids in there.

Going to try that but if you're already trying it please drop a comment here so I don't step on what you're already doing...

**Comment by mikehardy** [comment]
It is a really really big "miss" that we don't load these anki backend pages into a robolectric test or androidTest or something as I think this is the second issue we've seen where simply blind-loading them would have flagged a problem.

We need the list of PageFragment subclasses loaded up and taken through their lifecycle somehow in a test. Needs some thought...

**Comment by david-allison** [comment]
I had a look, `Statistics` is the only 'easy' one to test, the others require specific values (files for import/deck IDs etc...)

**Comment by mikehardy** [comment]
What I read is "the generic activity lifecycle test needs a setup method that creates necessary fixtures, and a way to pass things to the activities"

We are programmers I am sure we can make this happen ✊ 

I enjoy my use of "we" there, I do not have time for this 🙈

**Comment by mikehardy** [comment]
I'm on an almost-never-used development rig here and I've got some sort of total local build failure for me here that CI is obviously not seeing - can't even build main for a baseline test and I've run out of timebox as it's close to  midnight alas. This is up for grabs for anyone interested unless I comment again

For the avoidance of doubt - yes it blocks release but there is no one pressuring for an alpha release other than me because I like to get features out. But I don't like deadlines - if there's a bug there's a bug. No rush at all in any way. Cheers
