### ISSUE TITLE
Crash when sharing export collection

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#15058]
###### Reproduction Steps

1. Export Collection
2. Click on Share button

###### Expected Result
No crash when sharing 

###### Actual Result
Crashing when sharing export collection

###### Debug info

AnkiDroid Version = 2.17alpha13-debug (cb4c0c4141964dde76f395960da893dc7c4057ed)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3521

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3521 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36

ACRA UUID = 9de0c19e-e369-4b82-8bf5-41b5c4917f2d

Crash Reports Enabled = false
###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
For posterity, what's the stack trace?

**Comment by SanjaySargam** [comment]
```
FATAL EXCEPTION: main
Process: com.ichi2.anki.debug, PID: 29706
kotlin.UninitializedPropertyAccessException: lateinit property fileExportPath has not been initialized
at com.ichi2.anki.export.ActivityExportingDelegate.saveSuccessfulCollectionExportIfRelevant(ActivityExportingDelegate.kt:293)
at com.ichi2.anki.export.ActivityExportingDelegate.shareFile(ActivityExportingDelegate.kt:188)
at com.ichi2.anki.dialogs.ExportReadyDialog$onCreateDialog$2.invoke(ExportReadyDialog.kt:49)
at com.ichi2.anki.dialogs.ExportReadyDialog$onCreateDialog$2.invoke(ExportReadyDialog.kt:49)
at com.ichi2.utils.AlertDialogFacadeKt.toClickListener$lambda$0(AlertDialogFacade.kt:36)
at com.ichi2.utils.AlertDialogFacadeKt.$r8$lambda$ows5EntL7f5vvpmsfXTPM37rKuw(Unknown Source:0)
at com.ichi2.utils.AlertDialogFacadeKt$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:240)
at android.os.Looper.loop(Looper.java:351)
at android.app.ActivityThread.main(ActivityThread.java:8377)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```
