### ISSUE TITLE
[BUG]: Sound player crashes if changing cards really fast

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#15103]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Android 34 emulator, with the [🗍 1000 Basic English Words](https://ankiweb.net/shared/info/1243388349) deck:

1. Open the default previewer with many cards with audios (like the example above)
2. Change cards really fast with the slider

[big bang.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/c56c7a74-e955-4eaa-abdc-cc4a9bb21b1d)

### Expected behaviour

Nothing crashes

### Actual behaviour

Things crash

### Debug info

```text
AnkiDroid Version = 2.17alpha14-debug (e5138964c3b822c8d3dd40c81bb64c56dc5b9b17)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 14 (SDK 34)

ProductFlavor = full

Manufacturer = Google

Model = sdk_gphone64_x86_64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 14; sdk_gphone64_x86_64 Build/UE1A.230829.036; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.136 Mobile Safari/537.36

ACRA UUID = e26f3b42-5e3f-4325-9324-f5c71a9b5fda

Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

FWIW, the new previewer slider doesn't update the note until the user releases it. It probably won't take long before I push the PR making it the default

Not sure if this will happen in normal conditions (i.e. people not reviewing superfast)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
```text
ACRA caught a IllegalStateException for com.ichi2.anki.debug
                                                                                                    java.lang.IllegalStateException: Already resumed, but proposed with update CompletedExceptionally[com.ichi2.anki.cardviewer.SoundException]
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.kt:482)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:447)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
                                                                                                    	at com.ichi2.anki.cardviewer.SoundTagPlayer$play$2$1$3.onError(SoundTagPlayer.kt:79)
                                                                                                    	at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3612)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```
