### ISSUE TITLE
[flaky test]: CardBrowserTest > column spinner positions are initially set from existing preferences

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#15160]
https://github.com/ankidroid/Anki-Android/actions/runs/7408097883/job/20155634609?pr=15154

**Comment by david-allison** [comment]
```
AnkiDroidJsAPITest > ankiMarkAndFlagCardTest FAILED
    kotlinx.coroutines.test.UncompletedCoroutinesError: After waiting for 1m, the test coroutine is not completing
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$2$1.invoke(TestBuilders.kt:349)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$2$1.invoke(TestBuilders.kt:333)
        at kotlinx.coroutines.InvokeOnCancelling.invoke(JobSupport.kt:1431)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1477)
        at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:799)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:759)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:675)
        at kotlinx.coroutines.JobSupport.cancelCoroutine(JobSupport.kt:662)
        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:159)
        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:501)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:109)
        at java.base@17.0.9/java.lang.Thread.run(Thread.java:840)
```

**Comment by BrayanDSO** [comment]
I got the link wrong?

```
CardBrowserTest > column spinner positions are initially set from existing preferences FAILED
    kotlinx.coroutines.test.UncompletedCoroutinesError: After waiting for 1m, the test coroutine is not completing
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$2$1.invoke(TestBuilders.kt:349)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$2$1.invoke(TestBuilders.kt:333)
        at kotlinx.coroutines.InvokeOnCancelling.invoke(JobSupport.kt:1431)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1477)
        at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:799)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:759)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:675)
        at kotlinx.coroutines.JobSupport.cancelCoroutine(JobSupport.kt:662)
        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:159)
        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:501)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:109)
        at java.base@17.0.9/java.lang.Thread.run(Thread.java:840)
```
