### ISSUE TITLE
"deck not found in limits map"

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#15195]
Running on bdff91ce43c3280a7a88412f76cf5edca4d6e358

I just opened a deck and got this message. I believe at the very least that if we display error message, we should add some informations such as:
* use "check database"
* raise an issue here

I don't find this message in ankidroid code, so I assume it's from the backend.

**Comment by Arthur-Milchior** [comment]
Check media solved the issue. No idea what it meant

**Comment by Arthur-Milchior** [comment]
The same message appeared in anki. But it offered to read https://docs.ankiweb.net/troubleshooting.html

**Comment by david-allison** [comment]
This is also an issue in Anki Desktop

**Comment by Arthur-Milchior** [comment]
@david-allison I fear I don't understand why it's an issue.
While the message in anki desktop is, admittedly, not very clear, adding a button that open that the troubleshooting page at least ensure that the user is not 100% lost. Admittedly, this page is far far too vague, but that's the issue with unspecific error.
Implementation is 
in https://github.com/ankitects/anki/blob/5335d748cfcadb07af77bf2db6a6229efe8f36ec/qt/aqt/errors.py#L275

I'd even add that it's great that anki rust library does not provide the same link, because it would be useless for us. Changing video driver or disabling add-ons can't be done.
Instead, we should either have a way to open a troubleshooting page specific to ankidroid.

Or, simply, offering to check the database, because, honestly, there are no other advices that seems useful. (Potentially restarting ankidroid too)

**Comment by david-allison** [comment]
https://ankidroid.org/acra/app/1/bug/313402/report/59f92c16-a85b-4064-8b9d-d2e0153751eb

```
net.ankiweb.rsdroid.exceptions.BackendInvalidInputException: deck not found in limits map
	at net.ankiweb.rsdroid.exceptions.BackendInvalidInputException.<init>(BackendInvalidInputException.kt:28)
	at net.ankiweb.rsdroid.exceptions.BackendInvalidInputException$Companion.fromInvalidInputError(BackendInvalidInputException.kt:37)
	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:116)
	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:281)
	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
	at net.ankiweb.rsdroid.Backend.runMethodRaw$lambda$1(Backend.kt:118)
	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:131)
	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:117)
	at anki.backend.GeneratedBackend.getQueuedCardsRaw(GeneratedBackend.kt:851)
	at anki.backend.GeneratedBackend.getQueuedCards(GeneratedBackend.kt:859)
	at com.ichi2.libanki.sched.Scheduler.getQueuedCards(Scheduler.kt:139)
	at com.ichi2.libanki.sched.Scheduler.counts(Scheduler.kt:194)
	at com.ichi2.anki.StudyOptionsFragment.fetchStudyOptionsData(StudyOptionsFragment.kt:651)
	at com.ichi2.anki.StudyOptionsFragment.access$fetchStudyOptionsData(StudyOptionsFragment.kt:59)
	at com.ichi2.anki.StudyOptionsFragment$refreshInterface$1.invokeSuspend$lambda$0(StudyOptionsFragment.kt:460)
	at com.ichi2.anki.CollectionManager.withCol$lambda$1(CollectionManager.kt:122)
	at com.ichi2.anki.CollectionManager$withQueue$3.invokeSuspend(CollectionManager.kt:104)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
```

**Comment by david-allison** [comment]
Not translated, we can match on the string

https://github.com/ankitects/anki/blob/b250a2f7245cb41f10581bfca2f89106fc0e366c/rslib/src/decks/limits.rs#L339-L343

**Comment by david-allison** [comment]
* find a collection, or write code to trigger the issue
* Define `DeckNotFoundInLimitsMapException` & write test in the backend (to ensure we consistently map to this exception)
* Provide guidance for this exception
  * Check DB/Check Media(?)
