### ISSUE TITLE
[Bug]CalledFromWrongThreadException

### ISSUE THREAD

**Issue by xjqm-tao** [ankidroid/Anki-Android#15317]
###### Reproduction Steps

1. On the review screen
2. Press the home button, enter the desktop
3. Back to ankidroid

###### Expected Result

Nothing will happen.

###### Actual Result
A warning dialog box:
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.

###### Debug info
AnkiDroid Version = 2.17alpha16 (37daacf8e6a9642b85135ce3c00fa44cb58ea061)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = Xiaomi

Model = 22041216C

Hardware = mt6895

Webview User Agent = Mozilla/5.0 (Linux; Android 13; 22041216C Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36

ACRA UUID = 13b991d9-a0fd-4ffc-8f8b-0b5c080f71cf

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
https://ankidroid.org/acra/app/1/bug/119138/report/f4041d9e-9517-4d2e-876b-8520354e2f8b

```
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:10375)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:2121)
	at android.view.View.requestLayout(View.java:26657)
	at android.view.View.requestLayout(View.java:26657)
	at android.view.View.requestLayout(View.java:26657)
	at android.view.View.requestLayout(View.java:26657)
	at android.view.View.requestLayout(View.java:26657)
	at android.view.View.requestLayout(View.java:26657)
	at androidx.drawerlayout.widget.DrawerLayout.requestLayout(SourceFile:5)
	at android.view.View.requestLayout(View.java:26657)
	at android.view.View.requestLayout(View.java:26657)
	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:380)
	at android.view.View.requestLayout(View.java:26657)
	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:380)
	at android.view.View.requestLayout(View.java:26657)
	at android.widget.TextView.checkForRelayout(TextView.java:10105)
	at android.widget.TextView.setText(TextView.java:6642)
	at android.widget.TextView.setText(TextView.java:6462)
	at android.widget.TextView.setText(TextView.java:6414)
	at android.widget.Chronometer.updateText(Chronometer.java:322)
	at android.widget.Chronometer.setBase(Chronometer.java:181)
	at com.ichi2.anki.reviewer.AnswerTimer.resume(SourceFile:48)
	at com.ichi2.anki.reviewer.AnswerTimerKt.resume(SourceFile:11)
	at com.ichi2.anki.Reviewer$onResume$1$1.invoke(SourceFile:2)
	at com.ichi2.anki.Reviewer$onResume$1$1.invoke(SourceFile:1)
	at com.ichi2.anki.CollectionManager$withCol$2.invoke(SourceFile:3)
	at com.ichi2.anki.CollectionManager$withCol$2.invoke(SourceFile:1)
	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(SourceFile:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:124)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(SourceFile:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(SourceFile:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(SourceFile:29)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:1)
```

**Comment by david-allison** [comment]
Thanks for the report!!
