### ISSUE TITLE
[BUG]: Ankidroid Crashing when opening tts voice settings

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#15364]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Added tts sound to a card template then preview the card or save it and open it, clicking the tts voice setting link causes crash 

### Expected behaviour

No crash

### Actual behaviour

Crash

### Debug info

AnkiDroid Version = 2.17alpha17-debug (f4172d65147e2531895f0dc4c3419ebfcda0c9da)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = amazon

Manufacturer = unknown

Model = Android SDK built for x86

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Android SDK built for x86 Build/RSR1.210210.001.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36

ACRA UUID = d9a06fd6-3901-4497-a19f-ed17ad01e3b8

Crash Reports Enabled = false

### ACRA report 
https://ankidroid.org/acra/app/1/bug/121867/report/7a6635c5-5b99-41af-9969-9a88855aa8a1

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
```
kotlin.UninitializedPropertyAccessException: lateinit property availableVoices has not been initialized
	at com.ichi2.anki.TtsVoices.allTtsVoices(TtsVoices.kt:113)
	at com.ichi2.anki.dialogs.viewmodel.TtsVoicesViewModel$3.invokeSuspend(TtsVoicesViewModel.kt:145)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1d13390, Dispatchers.IO]
```

**Comment by criticalAY** [comment]
Trying to find the cause and fix it
