### ISSUE TITLE
[Crash] Crash on opening Previewer in a large deck

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#15380]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- Have a large deck (mine has 160,000+ cards, 70k cards seem to be sufficient to reproduce the issue)
- Open the Browser
- Select Preview from the menu.

### Expected behaviour

Preview appears

### Actual behaviour

App crashes

### Debug info

```text
AnkiDroid Version = 2.17alpha17 (866369337a2ee1838b2075a401029c11b0fc33e9)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = motorola

Model = moto g62 5G

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; moto g62 5G Build/T1SSIS33.1-75-7-4; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.230 Mobile Safari/537.36

ACRA UUID = d808c2e4-92ce-40db-9491-1fdcb75b1f50

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
`TransactionTooLargeException: data parcel size 1196176 bytes`

```
java.lang.RuntimeException: Failure from system
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1885)
	at android.app.Activity.startActivityForResult(Activity.java:5572)
	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:2)
	at androidx.core.app.ActivityCompat$Api16Impl.startActivityForResult(SourceFile:1)
	at androidx.core.app.ActivityCompat.startActivityForResult(SourceFile:1)
	at androidx.activity.ComponentActivity$1.onLaunch(SourceFile:169)
	at androidx.activity.result.ActivityResultRegistry$2.launch(SourceFile:32)
	at androidx.activity.result.ActivityResultLauncher.launch(SourceFile:1)
	at com.ichi2.anki.CardBrowser.onPreview(SourceFile:23)
	at com.ichi2.anki.CardBrowser.onOptionsItemSelected(SourceFile:398)
	at android.app.Activity.onMenuItemSelected(Activity.java:4508)
	at androidx.activity.ComponentActivity.onMenuItemSelected(SourceFile:1)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(SourceFile:1)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(SourceFile:1)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(SourceFile:3)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(SourceFile:6)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(SourceFile:19)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(SourceFile:7)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(SourceFile:5)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(SourceFile:15)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(SourceFile:4)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(SourceFile:28)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1197)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3236)
	at android.widget.AbsListView$3.run(AbsListView.java:4202)
	at android.os.Handler.handleCallback(Handler.java:984)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8088)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
Caused by: android.os.TransactionTooLargeException: data parcel size 1196176 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2258)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1879)
	... 33 more
```

**Comment by BrayanDSO** [comment]
saving to a file seems like the way to go

**Comment by mikehardy** [comment]
In deciding whether this should block beta or not - I think this will happen in 2.16 as well - I don't believe the way we passed the information between activities is different. I don't think this is a 2.17 blocker

It is a crash so it will get priority though

**Comment by user1823** [comment]
Fixed in beta 2. Thanks!
