### ISSUE TITLE
[Bug] Crash backgrounding Note Editor

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15406]
At 846cf2bf6d304902a32c950932da29f52efd5e06

```
                                                     java.lang.NullPointerException
                                                     	at com.ichi2.anki.NoteEditor.getCurrentlySelectedNotetype(NoteEditor.kt:2012)
                                                     	at com.ichi2.anki.NoteEditor.currentNotetypeIsImageOcclusion(NoteEditor.kt:2037)
                                                     	at com.ichi2.anki.NoteEditor.allowSaveAndPreview(NoteEditor.kt:1048)
                                                     	at com.ichi2.anki.NoteEditor.onCreateOptionsMenu(NoteEditor.kt:1016)
                                                     	at android.app.Activity.onCreatePanelMenu(Activity.java:4344)
                                                     	at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:520)
                                                     	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
                                                     	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3442)
                                                     	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
                                                     	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
                                                     	at android.os.Handler.handleCallback(Handler.java:942)
                                                     	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     	at android.os.Looper.loopOnce(Looper.java:201)
                                                     	at android.os.Looper.loop(Looper.java:288)
                                                     	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                     	at java.lang.reflect.Method.invoke(Native Method)
                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
17:32:57.860 UsageAnalytics                       D  sendAnalyticsException() description/fatal: java.lang.NullPointerException/true
17:32:57.861 ACRA                                 E  ACRA caught a NullPointerException for com.ichi2.anki.debug
                                                     java.lang.NullPointerException
                                                     	at com.ichi2.anki.NoteEditor.getCurrentlySelectedNotetype(NoteEditor.kt:2012)
                                                     	at com.ichi2.anki.NoteEditor.currentNotetypeIsImageOcclusion(NoteEditor.kt:2037)
                                                     	at com.ichi2.anki.NoteEditor.allowSaveAndPreview(NoteEditor.kt:1048)
                                                     	at com.ichi2.anki.NoteEditor.onCreateOptionsMenu(NoteEditor.kt:1016)
                                                     	at android.app.Activity.onCreatePanelMenu(Activity.java:4344)
                                                     	at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:520)
                                                     	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
                                                     	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3442)
                                                     	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
                                                     	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
                                                     	at android.os.Handler.handleCallback(Handler.java:942)
                                                     	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     	at android.os.Looper.loopOnce(Looper.java:201)
                                                     	at android.os.Looper.loop(Looper.java:288)
                                                     	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                     	at java.lang.reflect.Method.invoke(Native Method)
                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by BrayanDSO** [comment]
it should be `mNoteTypeSpinner` not being initialized yet
