### ISSUE TITLE
[Bug] In NoteEditor changing the note type to image occlusion and saving results in crash

### ISSUE THREAD

**Issue by lukstbit** [ankidroid/Anki-Android#15400]
###### Reproduction Steps

Several reports on ACRA about this:
https://ankidroid.org/acra/app/1/bug/123092/report/461dde9d-6b79-43de-a92e-bb3b7be0012a
https://ankidroid.org/acra/app/1/bug/123031/report/c03eafec-b4be-42fe-b9d0-867afbcb41c8

```
kotlin.NotImplementedError: An operation is not implemented: unhandled change type
	at com.ichi2.libanki.ChangeManager.notifySubscribers$AnkiDroid_fullRelease(SourceFile:90)
	at com.ichi2.libanki.ChangeManagerKt$undoableOp$3$1.invokeSuspend(SourceFile:17)
	at com.ichi2.libanki.ChangeManagerKt$undoableOp$3$1.invoke(SourceFile:2)
	at com.ichi2.libanki.ChangeManagerKt$undoableOp$3$1.invoke(SourceFile:1)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(SourceFile:8)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(SourceFile:50)
	at kotlinx.coroutines.BuildersKt.withContext(SourceFile:1)
	at com.ichi2.libanki.ChangeManagerKt.undoableOp(SourceFile:96)
	at com.ichi2.libanki.ChangeManagerKt$undoableOp$1.invokeSuspend(Unknown Source:10)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:124)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8377)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f545fe5, Dispatchers.Main.immediate]
```

Note that I managed to reproduce the issue:

1. I used CardBrowser to click on a card, one that is not of type _Image Occlusion_(I used the _Basic_ note type)
2. Enter NoteEditor
3. Change the _Type_ to _Image Occlusion_
4. Select _Save_ -> Crash with the above error

###### Debug info

Latest beta

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
Coming from here
```kotlin
    internal fun <T> notifySubscribers(changes: T, initiator: Any?) {
        val opChanges = when (changes) {
            is OpChanges -> changes
            is OpChangesWithCount -> changes.changes
            is OpChangesWithId -> changes.changes
            is OpChangesAfterUndo -> changes.changes
            is OpChangesOnly -> changes.changes
            is ImportResponse -> changes.changes
            else -> TODO("unhandled change type")
        }
        notifySubscribers(opChanges, initiator)
    }
}
```

**Comment by david-allison** [comment]
Sorry! Cause:

* abb6a36681a0fe0e0dca04d02468c6c40c81e9fe https://github.com/ankidroid/Anki-Android/pull/15251
