### ISSUE TITLE
[Bug] CardBrowser Scroll Issue 8821

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15441]
###### Reproduction Steps

1. Open card browser
2. Switch from follow system to "Light"

```
com.ichi2.anki.exception.ManuallyReportedException: CardBrowser Scroll Issue 8821
	at com.ichi2.anki.CrashReportService.sendExceptionReport(SourceFile:1)
	at com.ichi2.anki.CardBrowser$RenderOnScroll.onScroll(SourceFile:66)
	at android.widget.AbsListView.invokeOnItemScrollListener(AbsListView.java:1716)
	at android.widget.AbsListView.setOnScrollListener(AbsListView.java:1702)
	at com.ichi2.anki.CardBrowser.onCreate(SourceFile:258)
	at android.app.Activity.performCreate(Activity.java:8944)
	at android.app.Activity.performCreate(Activity.java:8913)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6493)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6377)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:76)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:68)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6453)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2695)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

https://ankidroid.org/acra/app/1/bug/109835/report/71092432-97df-4524-a2d3-9eb6eec6f1b5

* Related: #8821

**Comment by BrayanDSO** [comment]
Could you be more descriptive with the reproduction steps? I couldn't reproduce it with what I understood

**Comment by david-allison** [comment]
Hmm... can't reproduce any more

**Comment by david-allison** [comment]
Tried:

* Open card browser
* Scroll down
* Tap a card to edit
* Switch to night mode
* return to browser

Can only reduce some times

**Comment by david-allison** [comment]
Long-term fix: use [SavedStateHandle](https://developer.android.com/topic/libraries/architecture/viewmodel/viewmodel-savedstate) in the `ViewModel`

**Comment by CyberButton** [comment]
> Long-term fix: use [SavedStateHandle](https://developer.android.com/topic/libraries/architecture/viewmodel/viewmodel-savedstate) in the `ViewModel`

I want to try it

**Comment by CyberButton** [comment]
> Long-term fix: use [SavedStateHandle](https://developer.android.com/topic/libraries/architecture/viewmodel/viewmodel-savedstate) in the `ViewModel`

Can you please clarify what exactly to store in the SavedStateHandle ?

**Comment by david-allison** [comment]
Scroll position **may** need to be saved if we're having issues with a refresh after `onResume` (this may be necessary if a user performs actions via the API which modify cards)
