### ISSUE TITLE
[Bug] Background image crash [137MB]

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15450]
https://ankidroid.org/acra/app/1/bug/124634/report/6b2ed8ec-a8f2-406f-b4fb-6c4a9163e5a6

```
java.lang.RuntimeException: Canvas: trying to draw too large(137453372bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
	at android.widget.ImageView.onDraw(ImageView.java:1436)
	at android.view.View.draw(View.java:22518)
	at android.view.View.updateDisplayListIfDirty(View.java:21386)
	at android.view.View.draw(View.java:22246)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4540)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(SourceFile:136)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4299)
	at android.view.View.updateDisplayListIfDirty(View.java:21377)
	at android.view.View.draw(View.java:22246)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4540)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(SourceFile:96)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4299)
	at android.view.View.draw(View.java:22521)
	at android.view.View.updateDisplayListIfDirty(View.java:21386)
	at android.view.View.draw(View.java:22246)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4540)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4299)
	at android.view.View.updateDisplayListIfDirty(View.java:21377)
	at android.view.View.draw(View.java:22246)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4540)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4299)
	at android.view.View.updateDisplayListIfDirty(View.java:21377)
	at android.view.View.draw(View.java:22246)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4540)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4299)
	at android.view.View.updateDisplayListIfDirty(View.java:21377)
	at android.view.View.draw(View.java:22246)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4540)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4299)
	at android.view.View.updateDisplayListIfDirty(View.java:21377)
	at android.view.View.draw(View.java:22246)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4540)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4299)
	at android.view.View.draw(View.java:22521)
	at com.android.internal.policy.DecorView.draw(DecorView.java:826)
	at android.view.View.updateDisplayListIfDirty(View.java:21386)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4232)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3946)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3217)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2057)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8362)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
	at android.view.Choreographer.doCallbacks(Choreographer.java:880)
	at android.view.Choreographer.doFrame(Choreographer.java:813)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**Comment by david-allison** [comment]
https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/graphics/java/android/graphics/RecordingCanvas.java;l=49;drc=ed769e0aede2a840ea8cdff87ce593eb6ea8a7c6?q=%22trying%20to%20draw%20too%20large%22

https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/graphics/java/android/graphics/RecordingCanvas.java;l=49;drc=ed769e0aede2a840ea8cdff87ce593eb6ea8a7c6?q=%22trying%20to%20draw%20too%20large%22

RecordinCanvas.MAX_BITMAP_SIZE = 100MB
