### ISSUE TITLE
[Bug] API 28: Can't open Filtered Deck Options

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15536]
* make a custom study deck
* Long press - Deck Options

`android.content.res.Resources$NotFoundException: File res/color/faded_primary.xml from drawable resource ID #0x7f06007d`

`Binary XML file line #17: <item> tag requires a 'drawable' attribute or child tag defining a drawable`

```
ACRA caught a RuntimeException for com.ichi2.anki.debug
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki.debug/com.ichi2.anki.FilteredDeckOptions}: android.view.InflateException: Binary XML file line #27: Binary XML file line #27: Error inflating class androidx.appcompat.widget.ActionBarContainer
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
Caused by: android.view.InflateException: Binary XML file line #27: Binary XML file line #27: Error inflating class androidx.appcompat.widget.ActionBarContainer
Caused by: android.view.InflateException: Binary XML file line #27: Error inflating class androidx.appcompat.widget.ActionBarContainer
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:979)
	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:889)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:772)
	at com.ichi2.ui.AppCompatPreferenceActivity.setContentView(AppCompatPreferenceActivity.kt:211)
	at android.preference.PreferenceActivity.onCreate(PreferenceActivity.java:557)
	at com.ichi2.ui.AppCompatPreferenceActivity.onCreate(AppCompatPreferenceActivity.kt:185)
	at com.ichi2.anki.FilteredDeckOptions.onCreate(FilteredDeckOptions.kt:200)
	at android.app.Activity.performCreate(Activity.java:6662)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
Caused by: android.content.res.Resources$NotFoundException: Drawable com.ichi2.anki.debug:color/faded_primary with resource ID #0x7f06007d
Caused by: android.content.res.Resources$NotFoundException: File res/color/faded_primary.xml from drawable resource ID #0x7f06007d
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:725)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
	at android.content.res.Resources.loadDrawable(Resources.java:854)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
	at androidx.appcompat.widget.ActionBarContainer.<init>(ActionBarContainer.java:68)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:979)
	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:889)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:772)
	at com.ichi2.ui.AppCompatPreferenceActivity.setContentView(AppCompatPreferenceActivity.kt:211)
	at android.preference.PreferenceActivity.onCreate(PreferenceActivity.java:557)
	at com.ichi2.ui.AppCompatPreferenceActivity.onCreate(AppCompatPreferenceActivity.kt:185)
	at com.ichi2.anki.FilteredDeckOptions.onCreate(FilteredDeckOptions.kt:200)
	at android.app.Activity.performCreate(Activity.java:6662)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: <item> tag requires a 'drawable' attribute or child tag defining a drawable
	at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:183)
	at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:116)
	at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:130)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1227)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1200)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:715)
	... 33 more
```

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/blob/2d510ebd319055db4b46487e41598588425c106d/AnkiDroid/src/main/res/color/faded_primary.xml

**Comment by GautamCoder4019k** [comment]
@david-allison can i work on this issue?

**Comment by david-allison** [comment]
Anyone can.

Do expect that someone might take the work and finish it before you. It's high priority and blocks the 2.17 release

**Comment by GautamCoder4019k** [comment]
ok sure

**Comment by david-allison** [comment]
<details>

<summary>Screenshots on my S21</summary>

![image](https://github.com/ankidroid/Anki-Android/assets/62114487/14b3d856-74f1-4df4-81b2-455c6d9f34e2)

![image](https://github.com/ankidroid/Anki-Android/assets/62114487/e8ac1b4e-5ff7-4213-afbc-1289150026d3)

</details>

**Comment by david-allison** [comment]
Fails on:

* API 24
* API 25
* API 26
* API 27
* API 28

Passes:
* API 29
