### ISSUE TITLE
[Bug] Switching between `Image Occlusion` note types on Add screen causes a crash 

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#15579]
###### Reproduction Steps

1. Open App - three dots icon - `Manage note types` - `+` - `Type` - `Add: Image Occlusion` - `OK`
5.  Go back to Deck picker screen
6. `+`  - `Add`
7. `Type:` - change from the already selected `Image Occlusion-xxxxx` to the original) `Image Occlusion`, or vice versa
   - In case that the already selected note type isn't neither, select either one - do the step 2 - 3 - 4  

###### Expected Result
No crash

###### Actual Result
Crash

https://github.com/ankidroid/Anki-Android/assets/10436072/d53be7f2-4081-4d5a-8a66-a3e3375f07ed

###### Debug info
AnkiDroid Version = 2.17beta5 (a06d445bfcea3139accc30faa1b24c0fe214d2b0)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.165 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
https://ankidroid.org/acra/app/1/bug/128338/report/d29180e8-63e3-45f9-9e3c-869fa141d393

```
java.lang.NullPointerException
	at com.ichi2.anki.NoteEditor.setDuplicateFieldStyles(SourceFile:3)
	at com.ichi2.anki.NoteEditor.access$setDuplicateFieldStyles(SourceFile:1)
	at com.ichi2.anki.NoteEditor$SetNoteTypeListener.onItemSelected(SourceFile:192)
	at android.widget.AdapterView.fireOnSelected(AdapterView.java:977)
	at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:966)
	at android.widget.AdapterView.access$300(AdapterView.java:59)
	at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:930)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:263)
	at android.app.ActivityThread.main(ActivityThread.java:8266)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

**Comment by david-allison** [comment]
I don't feel this blocks 2.17, 

@snowtimeglass your opinion is always more than welcome

**Comment by snowtimeglass** [comment]
Thank you for the kind words. 

>I don't feel this blocks 2.17,

I don't either :-)
