### ISSUE TITLE
[Bug] Can't share to AnkiDroid if an image occlusion note type is selected

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15584]
###### Reproduction Steps

1. Select an image occlusion note type
2. Share an image OR share text to AnkiDroid

Image fails with:

```
FATAL EXCEPTION: main
Process: com.ichi2.anki.debug, PID: 20368
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1582825430, result=-1, data=Intent { (has extras) }} to activity {com.ichi2.anki.debug/com.ichi2.anki.NoteEditor}: java.lang.NullPointerException
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5323)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5362)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NullPointerException
	at com.ichi2.anki.NoteEditor$requestMultiMediaEditLauncher$1.invoke(NoteEditor.kt:209)
	at com.ichi2.anki.NoteEditor$requestMultiMediaEditLauncher$1.invoke(NoteEditor.kt:194)
	at com.ichi2.anki.NoteEditor$NoteEditorActivityResultCallback.onActivityResult(NoteEditor.kt:284)
	at com.ichi2.anki.NoteEditor$NoteEditorActivityResultCallback.onActivityResult(NoteEditor.kt:278)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:414)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:371)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:845)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:151)
	at android.app.Activity.dispatchActivityResult(Activity.java:8628)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5316)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5362) 
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67) 
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:201) 
	at android.os.Looper.loop(Looper.java:288) 
	at android.app.ActivityThread.main(ActivityThread.java:7872) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 

```

Text fails with:

```
05:01:31.970 ACRA                                 E  ACRA caught a NullPointerException for com.ichi2.anki.debug
                                                     java.lang.NullPointerException
                                                     	at com.ichi2.anki.NoteEditor.onCollectionLoaded(NoteEditor.kt:608)
                                                     	at com.ichi2.anki.AnkiActivity.startLoadingCollection$lambda$0(AnkiActivity.kt:287)
                                                     	at com.ichi2.anki.AnkiActivity.$r8$lambda$kj9hf0g17vxBfzngPYSgjzadw2g(Unknown Source:0)
                                                     	at com.ichi2.anki.AnkiActivity$$ExternalSyntheticLambda1.execute(Unknown Source:2)
                                                     	at com.ichi2.async.CollectionLoader$load$1.invokeSuspend(CollectionLoader.kt:52)
                                                     	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                     	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                     	at android.os.Handler.handleCallback(Handler.java:942)
                                                     	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     	at android.os.Looper.loopOnce(Looper.java:201)
                                                     	at android.os.Looper.loop(Looper.java:288)
                                                     	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                     	at java.lang.reflect.Method.invoke(Native Method)
                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                     	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@232815d, Dispatchers.Main.immediate]
```

###### Research
AnkiDroid Version = 2.17beta5-debug (89ab6369ac90daf348ac7f5e4338a5ca9880a11c)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = Google

Model = sdk_gphone64_arm64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 13; sdk_gphone64_arm64 Build/TE1A.220922.034; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36

ACRA UUID = bdcca282-35c1-4097-9b3a-5936f403928b

Crash Reports Enabled = false

**Comment by david-allison** [comment]
@criticalAY
