### ISSUE TITLE
[Bug] App hangs if there is too much work to do while checking media + crashes if another screen is opened while hanged

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#15626]
###### Reproduction Steps

emulator 31, 2.17beta6:
1. create a lot of fake media in dev options (10.000+)
2. Check media
3. try interacting with the screen → you can't
4. try opening the deck picker or note editor → it crashes

[it happened.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/b80295e2-3258-4164-8efc-a18cc1c85af6)

[bingo.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/374e7554-8498-4c8a-bedf-66a9a7ae6bbd)

###### Expected Result

A progress dialog or something like it is shown

###### Actual Result

app hangs until media is checked

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

[it happened.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/4b3ce2f2-94c9-4771-9bab-09ab80f70316)
bu

**Comment by BrayanDSO** [comment]
```text
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 876776 bytes
                                                                                                    	at android.app.ActivityClient.activityStopped(ActivityClient.java:86)
                                                                                                    	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    Caused by: android.os.TransactionTooLargeException: data parcel size 876776 bytes
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(BinderProxy.java:571)
                                                                                                    	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1297)
                                                                                                    	at android.app.ActivityClient.activityStopped(ActivityClient.java:83)
                                                                                                    	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

**Comment by mikehardy** [comment]
okay with releasing with this (so: agree on 2.17.1 milestone vs 2.17) but obviously a crash bug is higher priority than most

**Comment by Haz3-jolt** [comment]
I'd like to work on this!

**Comment by neeldoshii** [comment]
I would like to take this @BrayanDSO @david-allison

**Comment by BrayanDSO** [comment]
if nobody has asked, go for it. No need for pinging

**Comment by david-allison** [comment]
@criticalAY Is this still an issue after your fixes?

**Comment by criticalAY** [comment]
It should not be as earlier we were rendering the media using list but now we have recycler view , I will test it still and get back

**Comment by david-allison** [comment]
Cheers! Assigned for the quick check, not with the expectation that you fix the bug if it still exists

**Comment by criticalAY** [comment]
This no more happens, closing this issue
