### ISSUE TITLE
Crash when importing a file

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#15635]
Emulator 31, full build, 2.18alpha1:

[Screen_recording_20240224_071921.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/b1b98975-406c-4747-a2d1-a0ffcff2eff4)

**Comment by BrayanDSO** [comment]
```text
2024-02-24 07:19:45.868  7899-7899  ACRA                    com.ichi2.anki.debug                 E  ACRA caught a ClassCastException for com.ichi2.anki.debug
                                                                                                    java.lang.ClassCastException: com.ichi2.anki.SingleFragmentActivity cannot be cast to com.ichi2.anki.DeckPicker
                                                                                                    	at com.ichi2.anki.dialogs.DialogHandler.handleMessage(DialogHandler.kt:41)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by david-allison** [comment]
logs

```
11:54:03.777 Parcel                               W  Expecting binder but got null!
11:54:04.660 DeckPicker                           I  DeckPicker:: Import button pressed
11:54:04.663 OnBackInvokedCallback                W  OnBackInvokedCallback is not enabled for the application.
                                                     Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
11:54:04.664 FragmentLifecycleLogger              I  DeckPicker::ImportFileSelectionFragment::onAttach
11:54:04.665                                      I  DeckPicker::ImportFileSelectionFragment::onCreate
11:54:04.689                                      I  DeckPicker::ImportFileSelectionFragment::onStart
11:54:04.689                                      I  DeckPicker::ImportFileSelectionFragment::onResume
11:54:04.714 Parcel                               W  Expecting binder but got null!
11:54:06.115 ImportFileSelect...agment$Companion  D  openImportFilePicker() delegating to file picker intent
11:54:06.131 AnkiDroidApp$onCreate                I  DeckPicker::onPause
11:54:06.131 FragmentLifecycleLogger              I  DeckPicker::ImportFileSelectionFragment::onPause
11:54:06.134                                      I  DeckPicker::ImportFileSelectionFragment::onStop
11:54:06.135                                      I  DeckPicker::ImportFileSelectionFragment::onViewDestroyed
11:54:06.135                                      I  DeckPicker::ImportFileSelectionFragment::onDestroy
11:54:06.136                                      I  DeckPicker::ImportFileSelectionFragment::onDetach
11:54:06.676 AnkiDroidApp$onCreate                I  DeckPicker::onStop
11:54:06.678 WidgetStatus                         D  WidgetStatus.update(): already running or not enabled
11:54:06.679 AnkiDroidApp$onCreate                I  DeckPicker::onSaveInstanceState
11:54:07.705                                      I  DeckPicker::onStart
11:54:07.708                                      I  DeckPicker::onResume
11:54:07.710 ImportUtils$FileImporter             I  IntentHandler/ User requested to view a file
11:54:07.711                                      I  Intent: Intent { dat=content://com.android.providers.downloads.documents/... flg=0x43 }. Data: none
11:54:07.711 ImportUtils$FileImporter$Companion   I  Attempting to read data from intent.
11:54:07.715 DeckPicker                           D  updateDeckList
11:54:07.716 DeckPicker$updateDeckList            D  Refreshing deck list
11:54:07.719 DeckPicker                           D  onCreateOptionsMenu()
11:54:07.721 ImportUtils$FileImporter             D  handleFileImport() Importing from content provider: Intro to Psych-20240210062817.apkg
11:54:07.730                                      D  handleFileImport() Importing from content provider: Intro to Psych-20240210062817.apkg
11:54:07.731                                      D  No filename truncation necessary
11:54:07.749 DialogHandler$Companion              D  Storing persistent message
11:54:07.754 DeckPicker                           I  Updating deck list UI
11:54:07.754 DeckAdapter                          D  buildDeckList
11:54:07.755 DeckPicker                           D  Startup - Deck List UI Completed
11:54:07.777 DeckAdapter$DeckFilter               I  deck filter: 24
```

deck picker now shows no dialog

then import again:

```
11:54:55.514 Parcel                               W  Expecting binder but got null!
11:54:56.460 DeckPicker                           I  DeckPicker:: Import button pressed
11:54:56.460 OnBackInvokedCallback                W  OnBackInvokedCallback is not enabled for the application.
                                                     Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
11:54:56.461 FragmentLifecycleLogger              I  DeckPicker::ImportFileSelectionFragment::onAttach
11:54:56.461                                      I  DeckPicker::ImportFileSelectionFragment::onCreate
11:54:56.479                                      I  DeckPicker::ImportFileSelectionFragment::onStart
11:54:56.479                                      I  DeckPicker::ImportFileSelectionFragment::onResume
11:54:56.496 Parcel                               W  Expecting binder but got null!
11:54:57.496 ImportFileSelect...agment$Companion  D  openImportFilePicker() delegating to file picker intent
11:54:57.512 AnkiDroidApp$onCreate                I  DeckPicker::onPause
11:54:57.512 FragmentLifecycleLogger              I  DeckPicker::ImportFileSelectionFragment::onPause
11:54:57.518                                      I  DeckPicker::ImportFileSelectionFragment::onStop
11:54:57.518                                      I  DeckPicker::ImportFileSelectionFragment::onViewDestroyed
11:54:57.518                                      I  DeckPicker::ImportFileSelectionFragment::onDestroy
11:54:57.519                                      I  DeckPicker::ImportFileSelectionFragment::onDetach
11:54:58.094 AnkiDroidApp$onCreate                I  DeckPicker::onStop
11:54:58.095 WidgetStatus                         D  WidgetStatus.update(): already running or not enabled
11:54:58.096 AnkiDroidApp$onCreate                I  DeckPicker::onSaveInstanceState
11:54:58.504                                      I  DeckPicker::onStart
11:54:58.513                                      I  DeckPicker::onResume
11:54:58.513 ImportUtils$FileImporter             I  IntentHandler/ User requested to view a file
11:54:58.513                                      I  Intent: Intent { dat=content://com.android.providers.downloads.documents/... flg=0x43 }. Data: none
11:54:58.513 ImportUtils$FileImporter$Companion   I  Attempting to read data from intent.
11:54:58.516 DeckPicker                           D  updateDeckList
11:54:58.517 DeckPicker$updateDeckList            D  Refreshing deck list
11:54:58.517 ImportUtils$FileImporter             D  handleFileImport() Importing from content provider: Intro to Psych-20240210062817.apkg
11:54:58.520 DeckPicker                           I  Updating deck list UI
11:54:58.520                                      D  Startup - Deck List UI Completed
11:54:58.521 DeckAdapter                          D  buildDeckList
11:54:58.521 ImportUtils$FileImporter             D  handleFileImport() Importing from content provider: Intro to Psych-20240210062817.apkg
11:54:58.522 DialogHandler                        I  Dispatching persistent message: 2
11:54:58.522 DeckPicker                           D  onCreateOptionsMenu()
11:54:58.532 ImportUtils$FileImporter             D  No filename truncation necessary
11:54:58.543 DialogHandler$Companion              D  Storing persistent message
11:54:58.557 DialogHandler                        I  Handling Message: ImportAddDialog
11:54:58.557 ImportKt                             D  showImportDialog() delegating to ImportDialog
11:54:58.558 OnBackInvokedCallback                W  OnBackInvokedCallback is not enabled for the application.
                                                     Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
11:54:58.558 FragmentLifecycleLogger              I  DeckPicker::ImportDialog::onAttach
11:54:58.558                                      I  DeckPicker::ImportDialog::onCreate
11:54:58.559 DeckAdapter$DeckFilter               I  deck filter: 24
11:54:58.577 FragmentLifecycleLogger              I  DeckPicker::ImportDialog::onStart
11:54:58.578                                      I  DeckPicker::ImportDialog::onResume
11:54:58.612 Parcel                               W  Expecting binder but got null!
11:55:00.260 DeckPicker                           D  importAdd() for file /data/user/0/com.ichi2.anki.debug/cache/Intro%20to%20Psych-20240210062817.apkg
11:55:00.276 AnkiDroidApp$onCreate                I  DeckPicker::onPause
11:55:00.276 FragmentLifecycleLogger              I  DeckPicker::ImportDialog::onPause
11:55:00.277                                      I  DeckPicker::ImportDialog::onStop
11:55:00.277                                      I  DeckPicker::ImportDialog::onViewDestroyed
11:55:00.277                                      I  DeckPicker::ImportDialog::onDestroy
11:55:00.277                                      I  DeckPicker::ImportDialog::onDetach
11:55:00.291 Themes                               I  Setting theme to LIGHT
11:55:00.293 AnkiDroidApp$onCreate                I  SingleFragmentActivity::onCreate
11:55:00.299 TrafficStats                         D  tagSocket(165) with statsTag=0xffffffff, statsUid=-1
11:55:00.311 AnkiDroidApp$onCreate                I  SingleFragmentActivity::onStart
11:55:00.311 FragmentLifecycleLogger              I  SingleFragmentActivity::AnkiPackageImporterFragment::onAttach
11:55:00.312                                      I  SingleFragmentActivity::AnkiPackageImporterFragment::onCreate
11:55:00.346 PageFragment                         I  Loading http://127.0.0.1:43239/backend/web/import-anki-package.html
11:55:00.357 HostConnection                       D  HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_vulkan_async_qsri ANDROID_EMU_hwc_multi_configs GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
11:55:00.368 cr_media                             W  Requires BLUETOOTH permission
11:55:00.372 FragmentLifecycleLogger              I  SingleFragmentActivity::AnkiPackageImporterFragment::onViewCreated
11:55:00.374                                      I  SingleFragmentActivity::AnkiPackageImporterFragment::onStart
11:55:00.376 AnkiDroidApp$onCreate                I  SingleFragmentActivity::onResume
11:55:00.377 DialogHandler                        D  Reading persistent message
11:55:00.378                                      I  Dispatching persistent message: 2
11:55:00.378 FragmentLifecycleLogger              I  SingleFragmentActivity::AnkiPackageImporterFragment::onResume
11:55:00.428 Parcel                               W  Expecting binder but got null!
11:55:00.441 DialogHandler                        I  Handling Message: ImportAddDialog
--------- beginning of crash
11:55:00.441 AndroidRuntime                       D  Shutting down VM
11:55:00.441                                      E  FATAL EXCEPTION: main
                                                     Process: com.ichi2.anki.debug, PID: 6028
                                                     java.lang.ClassCastException: com.ichi2.anki.SingleFragmentActivity cannot be cast to com.ichi2.anki.DeckPicker
                                                     	at com.ichi2.anki.dialogs.DialogHandler.handleMessage(DialogHandler.kt:41)
                                                     	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                     	at android.os.Looper.loopOnce(Looper.java:201)
                                                     	at android.os.Looper.loop(Looper.java:288)
                                                     	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                     	at java.lang.reflect.Method.invoke(Native Method)
                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
11:55:00.443 ACRA                                 E  ACRA caught a ClassCastException for com.ichi2.anki.debug
                                                     java.lang.ClassCastException: com.ichi2.anki.SingleFragmentActivity cannot be cast to com.ichi2.anki.DeckPicker
                                                     	at com.ichi2.anki.dialogs.DialogHandler.handleMessage(DialogHandler.kt:41)
                                                     	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                     	at android.os.Looper.loopOnce(Looper.java:201)
                                                     	at android.os.Looper.loop(Looper.java:288)
                                                     	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                     	at java.lang.reflect.Method.invoke(Native Method)
                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
11:55:00.473 AnkiActivity                         I  finishWithAnimation DEFAULT
11:55:00.475                                      I  finishWithAnimation DEFAULT
---------------------------- PROCESS STARTED (6260) for package com.ichi2.anki.debug ----------------------------
11:55:01.338 NetworkSecurityConfig                D  Using Network Security Config from resource network_security_config debugBuild: true
11:55:01.339                                      D  Using Network Security Config from resource network_security_config debugBuild: true
11:55:01.380 ACRA                                 W  ErrorReporter#putCustomData called in SenderService process. THIS CALL WILL BE IGNORED!
11:55:01.380                                      W  ErrorReporter#putCustomData called in SenderService process. THIS CALL WILL BE IGNORED!
11:55:01.397 AnkiDroidApp                         I  Timber config: DEBUG
11:55:01.404 WebViewFactory                       I  Loading com.google.android.webview version 103.0.5060.71 (code 506007134)
11:55:01.420 anki.debug:acra                      W  Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (unsupported, reflection, allowed)
11:55:01.420                                      W  Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (unsupported, reflection, allowed)
11:55:01.420                                      W  Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (unsupported, reflection, allowed)
11:55:01.420                                      W  Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (unsupported, reflection, allowed)
11:55:01.420                                      W  Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (unsupported, reflection, allowed)
11:55:01.422 cr_WVCFactoryProvider                I  Loaded version=103.0.5060.71 minSdkVersion=29 isBundle=false multiprocess=true packageId=2
11:55:01.456 cr_SpareChildConn                    W  Failed to warm up the spare sandbox service
11:55:01.521 GoogleAnalyticsImpl                  I  Not participating in analytics sample (sample percentage vs random: 10 16)
11:55:01.521                                      I  Not participating in analytics sample (sample percentage vs random: 10 18)
11:55:01.522 AnkiDroidApp                         D  Skipping AnkiDroidApp.onCreate from ACRA sender process
11:55:01.539 anki.debug:acra                      E  Invalid ID 0x00000000.
11:55:01.556 ThemeUtils                           E  View class com.ichi2.ui.FixedTextView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
11:55:01.559 anki.debug:acra                      W  Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
11:55:01.583 ThemeUtils                           E  View class com.ichi2.ui.FixedTextView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
11:55:01.673 HostConnection                       D  HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_vulkan_async_qsri ANDROID_EMU_hwc_multi_configs GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
11:55:01.684 Gralloc4                             I  mapper 4.x is not supported
11:55:01.686                                      W  allocator 4.x is not supported
11:55:01.690 HostConnection                       D  HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_vulkan_async_qsri ANDROID_EMU_hwc_multi_configs GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
11:55:01.724 Parcel                               W  Expecting binder but got null!
11:55:01.739                                      W  Expecting binder but got null!
11:55:01.746                                      W  Expecting binder but got null!
11:55:03.364 anki.debug:acra                      I  Compiler allocated 4579KB to compile void android.view.ViewRootImpl.performTraversals()
---------------------------- PROCESS ENDED (6028) for package com.ichi2.anki.debug ----------------------------
11:55:04.099 Process                              I  Sending signal. PID: 6028 SIG: 9
---------------------------- PROCESS ENDED (6057) for package com.ichi2.anki.debug ----------------------------
```

**Comment by david-allison** [comment]
Issue:

https://github.com/ankidroid/Anki-Android/blob/fb7417fa1a615d6ea96e3cb1c53327836a1655c7/AnkiDroid/src/main/java/com/ichi2/anki/Import.kt#L49-L56

->

...

->

https://github.com/ankidroid/Anki-Android/blob/041f9d113ecf5046b2575ca6e72498c497a8422e/AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt#L203

->

https://github.com/ankidroid/Anki-Android/blob/041f9d113ecf5046b2575ca6e72498c497a8422e/AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt#L323-L338


The message sent by `DialogHandler.storeMessage(dialogMessage.toMessage())` is executed `onResume` 

But this no longer occurs
