### ISSUE TITLE
[Bug] `ClassCastExceptions`  some classes cannot be cast to com.ichi2.anki.DeckPicker

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#15645]
From Acra, I suspect majority or all of them point at one place-DeckPicker

```
java.lang.ClassCastException: com.ichi2.anki.Reviewer cannot be cast to com.ichi2.anki.DeckPicker
	at com.ichi2.anki.dialogs.DialogHandler.handleMessage(SourceFile:49)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7948)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```
or 

```
java.lang.ClassCastException: com.ichi2.anki.preferences.Preferences cannot be cast to com.ichi2.anki.DeckPicker
	at com.ichi2.anki.dialogs.DialogHandler.handleMessage(SourceFile:49)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8673)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

###### Debug info

`APP_VERSION_NAME 2.17.0`

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
Sorry my oversight, fixed by https://github.com/ankidroid/Anki-Android/issues/15635
