### ISSUE TITLE
Crash when sharing images to AnkiDroid

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#15651]
Steps:

[Screen_recording_20240224_200611.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/a8ef5b7c-e4e9-4833-9559-995c8f0106d3)

Debug info
```text
AnkiDroid Version = 2.18alpha1-debug (f145def4c4ee9b944bcb1df6cd04a636a5cc8bd3)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 12 (SDK 31)

ProductFlavor = full

Manufacturer = Google

Model = sdk_gphone64_x86_64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 12; sdk_gphone64_x86_64 Build/SE1A.211212.001.B1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.164 Mobile Safari/537.36

ACRA UUID = 1135e961-f358-44c5-aa32-5f3288eeaf72

Crash Reports Enabled = false
```

**Comment by BrayanDSO** [comment]
```text
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki.debug/com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity}: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/pexels-pixabay-36717.jpg"
         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
         at android.os.Handler.dispatchMessage(Handler.java:106)
         at android.os.Looper.loopOnce(Looper.java:201)
         at android.os.Looper.loop(Looper.java:288)
         at android.app.ActivityThread.main(ActivityThread.java:7839)
         at java.lang.reflect.Method.invoke(Native Method)
         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
        Caused by: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/pexels-pixabay-36717.jpg"
         at java.lang.Long.parseLong(Long.java:594)
         at java.lang.Long.parseLong(Long.java:636)
         at com.ichi2.anki.multimediacard.fields.BasicImageFieldController.getImageNameFromUri(BasicImageFieldController.kt:787)
         at com.ichi2.anki.multimediacard.fields.BasicImageFieldController.internalizeUri(BasicImageFieldController.kt:526)
         at com.ichi2.anki.multimediacard.fields.BasicImageFieldController.directImageIntent(BasicImageFieldController.kt:486)
         at com.ichi2.anki.multimediacard.fields.BasicImageFieldController.createUI(BasicImageFieldController.kt:226)
         at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.recreateEditingUi(MultimediaEditFieldActivity.kt:191)
         at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.recreateEditingUi$default(MultimediaEditFieldActivity.kt:167)
         at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.intentEditImage(MultimediaEditFieldActivity.kt:118)
         at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.onCreate(MultimediaEditFieldActivity.kt:107)
         at android.app.Activity.performCreate(Activity.java:8051)
         at android.app.Activity.performCreate(Activity.java:8031)
         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792) 
         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) 
         at android.os.Handler.dispatchMessage(Handler.java:106) 
         at android.os.Looper.loopOnce(Looper.java:201) 
         at android.os.Looper.loop(Looper.java:288) 
         at android.app.ActivityThread.main(ActivityThread.java:7839) 
         at java.lang.reflect.Method.invoke(Native Method) 
         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

**Comment by BrayanDSO** [comment]
@criticalAY, pinging you since you were in the area recently and may know how to fix it appropriately

**Comment by BrayanDSO** [comment]
crash line

https://github.com/ankidroid/Anki-Android/blob/f145def4c4ee9b944bcb1df6cd04a636a5cc8bd3/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt#L787

**Comment by BrayanDSO** [comment]
Source of the image I tested with: 

Photo by Pixabay from Pexels: https://www.pexels.com/photo/silhouette-of-tree-near-body-of-water-during-golden-hour-36717/

**Comment by criticalAY** [comment]
Will look into it asap

**Comment by david-allison** [comment]
Here's a patch for `msf:` Ids

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt b/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt	(revision cfaeba0bee93967b152abe44877a669845efc397)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt	(date 1708842232671)
@@ -784,8 +784,13 @@
                 val selection = MediaStore.Images.Media._ID + "=" + id
                 imageName = getImageNameFromContentResolver(context, MediaStore.Images.Media.EXTERNAL_CONTENT_URI, selection)
             } else if ("com.android.providers.downloads.documents" == uri.authority) {
-                val contentUri = ContentUris.withAppendedId(Uri.parse("content://downloads/public_downloads"), docId.toLong())
-                imageName = getImageNameFromContentResolver(context, contentUri, null)
+                imageName = if (!docId.startsWith("msf:")) {
+                    val contentUri = ContentUris.withAppendedId(Uri.parse("content://downloads/public_downloads"), docId.toLong())
+                    getImageNameFromContentResolver(context, contentUri, null)
+                } else {
+                    // `msf:1000034860` can be handled by using the URI
+                    getImageNameFromContentResolver(context, uri, null)
+                }
             }
         } else if ("content".equals(uri.scheme, ignoreCase = true)) {
             imageName = getImageNameFromContentResolver(context, uri, null)
```

We may want to look into https://github.com/HBiSoft/PickiT - the logic we have is already incorrect and convoluted

**Comment by david-allison** [comment]
This issue: https://cs.android.com/android/platform/superproject/+/master:packages/providers/DownloadProvider/src/com/android/providers/downloads/RawDocumentsHelper.java;l=35?q=%5C%22raw:%5C%22&ss=android%2Fplatform%2Fsuperproject
