### ISSUE TITLE
[Bug] IllegalStateException: window count is over max!!

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15658]
https://ankidroid.org/acra/app/1/bug/132331/report/268484d3-3378-44a2-a3c5-59ceac0d7a09

```
java.lang.IllegalStateException: window count is over max!!
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:450)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:148)
	at android.app.Dialog.show(Dialog.java:521)
	at androidx.appcompat.app.AlertDialog$Builder.show(SourceFile:5)
	at com.ichi2.anki.pages.PageChromeClient.onJsAlert(SourceFile:51)
	at WV.z6.run(chromium-TrichromeWebViewGoogle6432.aab-stable-616717833:138)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

Note:

```
	at androidx.appcompat.app.AlertDialog$Builder.show(SourceFile:5)
	at com.ichi2.anki.pages.PageChromeClient.onJsAlert(SourceFile:51)
```

Seen a couple of times in ACRA. Needs reproduction steps

**Comment by sanjaysargam** [comment]
still getting lots of crash reports related to this bug on ACRA. but not able to reproduce. How can I reproduce it ?
