### ISSUE TITLE
[Bug] 2.17.1 IntroductionActivity cannot be cast to DeckPicker

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15672]
Biggest crasher of 2.17.1

https://ankidroid.org/acra/app/1/bug/133757/report/03972a5c-a82c-4083-b262-1f50dbcdef83

```
java.lang.ClassCastException: com.ichi2.anki.IntroductionActivity cannot be cast to com.ichi2.anki.DeckPicker
	at com.ichi2.anki.dialogs.DialogHandler.handleMessage(SourceFile:49)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by david-allison** [comment]
I suspect this is importing a file before the `IntroductionActivity` is removed

```
02-26 07:11:51.718 I/AnkiDroid(25013): Timber config: PRODUCTION
02-26 07:11:51.718 I/AnkiDroid(25013): initialize()
02-26 07:11:51.875 I/AnkiDroid(25013): Not participating in analytics sample (sample percentage vs random: 10 23)
02-26 07:11:51.875 I/AnkiDroid(25013): setOptIn(): from false to false
02-26 07:11:51.875 I/AnkiDroid(25013): Not participating in analytics sample (sample percentage vs random: 10 38)
02-26 07:11:51.996 I/AnkiDroid(25013): AnkiDroid Version = 2.17.1 (dd2f3762fb214f9dd51162b215974b23cc809713)
02-26 07:11:51.996 I/AnkiDroid(25013): 
02-26 07:11:51.996 I/AnkiDroid(25013): Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)
02-26 07:11:51.996 I/AnkiDroid(25013): 
02-26 07:11:51.996 I/AnkiDroid(25013): Android Version = 13 (SDK 33)
02-26 07:11:51.996 I/AnkiDroid(25013): 
02-26 07:11:51.996 I/AnkiDroid(25013): ProductFlavor = play
02-26 07:11:51.996 I/AnkiDroid(25013): 
02-26 07:11:51.996 I/AnkiDroid(25013): Manufacturer = samsung
02-26 07:11:51.996 I/AnkiDroid(25013): 
02-26 07:11:51.996 I/AnkiDroid(25013): Model = SM-A235M
02-26 07:11:51.996 I/AnkiDroid(25013): 
02-26 07:11:51.996 I/AnkiDroid(25013): Hardware = qcom
02-26 07:11:51.996 I/AnkiDroid(25013): 
02-26 07:11:51.996 I/AnkiDroid(25013): Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A235M Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.178 Mobile Safari/537.36
02-26 07:11:51.996 I/AnkiDroid(25013): 
02-26 07:11:51.996 I/AnkiDroid(25013): ACRA UUID = d81ff6ea-00ac-448f-ab03-cf64ab92cbcf
02-26 07:11:51.996 I/AnkiDroid(25013): 
02-26 07:11:51.996 I/AnkiDroid(25013): Crash Reports Enabled = true
02-26 07:11:52.020 I/AnkiDroid(25013): Creating notification channel with id/name: General Notifications/AnkiDroid
02-26 07:11:52.025 I/AnkiDroid(25013): Creating notification channel with id/name: Synchronization/Sincronização
02-26 07:11:52.026 I/AnkiDroid(25013): Creating notification channel with id/name: Global Reminders/Cartões pendentes
02-26 07:11:52.026 I/AnkiDroid(25013): Creating notification channel with id/name: Deck Reminders/Lembretes
02-26 07:11:52.027 I/AnkiDroid(25013): Creating notification channel with id/name: Scoped Storage/Migração do armazenamento
02-26 07:11:52.033 I/AnkiDroid(25013): AnkiDroidApp: Starting Services
02-26 07:11:52.034 W/AnkiDroid(25013): AnkiDroidApp/ Boot Service did not execute - no permissions
02-26 07:11:52.062 I/AnkiDroid(25013): IntentHandler::onCreate
02-26 07:11:52.063 I/AnkiDroid(25013): Setting theme to BLACK
02-26 07:11:52.113 I/AnkiDroid(25013): isLegacyStorage(): current dir: /storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid
02-26 07:11:52.113 I/AnkiDroid(25013): scoped external dirs: /storage/emulated/0/Android/data/com.ichi2.anki/files
02-26 07:11:52.113 I/AnkiDroid(25013): scoped internal dir: /data/user/0/com.ichi2.anki/files
02-26 07:11:52.113 I/AnkiDroid(25013): isLegacyStorage(): false
02-26 07:11:52.113 I/AnkiDroid(25013): User has storage permissions. Running intent: android.intent.action.VIEW
02-26 07:11:52.113 I/AnkiDroid(25013): Handling file import
02-26 07:11:52.113 I/AnkiDroid(25013): IntentHandler/ User requested to view a file
02-26 07:11:52.113 I/AnkiDroid(25013): Intent: Intent { act=android.intent.action.VIEW dat=content://media/... typ=application/octet-stream flg=0x10000003 cmp=com.ichi2.anki/.IntentHandler (has extras) }. Data: android.intent.extra.REFERRER, android.intent.extra.ORIGINATING_URI
02-26 07:11:52.113 I/AnkiDroid(25013): Attempting to read data from intent.
02-26 07:11:53.125 I/AnkiDroid(25013): onCreate() import successful and downloaded file deleted
02-26 07:11:53.230 I/AnkiDroid(25013): Setting theme to BLACK
02-26 07:11:53.245 I/AnkiDroid(25013): DeckPicker::onCreate
02-26 07:11:53.247 I/AnkiDroid(25013): Displaying app intro
02-26 07:11:53.261 I/AnkiDroid(25013): finishWithAnimation DEFAULT
02-26 07:11:53.274 I/AnkiDroid(25013): IntentHandler::onDestroy
02-26 07:11:53.302 I/AnkiDroid(25013): Setting theme to BLACK
02-26 07:11:53.304 I/AnkiDroid(25013): IntroductionActivity::onCreate
02-26 07:11:53.319 I/AnkiDroid(25013): IntroductionActivity::SetupCollectionFragment::onAttach
02-26 07:11:53.319 I/AnkiDroid(25013): IntroductionActivity::SetupCollectionFragment::onCreate
02-26 07:11:53.320 I/AnkiDroid(25013): IntroductionActivity::onStart
02-26 07:11:53.362 I/AnkiDroid(25013): IntroductionActivity::SetupCollectionFragment::onViewCreated
02-26 07:11:53.363 I/AnkiDroid(25013): IntroductionActivity::SetupCollectionFragment::onStart
02-26 07:11:53.379 I/AnkiDroid(25013): IntroductionActivity::onResume
02-26 07:11:53.380 I/AnkiDroid(25013): Dispatching persistent message: 2
02-26 07:11:53.380 I/AnkiDroid(25013): IntroductionActivity::SetupCollectionFragment::onResume
02-26 07:11:53.413 I/AnkiDroid(25013): Handling Message: ImportAddDialog
02-26 07:11:54.245 I/AnkiDroid(25013): finishWithAnimation DEFAULT
02-26 07:11:54.248 I/AnkiDroid(25013): finishWithAnimation DEFAULT
02-26 07:11:54.885 I/AnkiDroid(25252): Timber config: PRODUCTION
02-26 07:11:54.887 I/AnkiDroid(25252): initialize()
02-26 07:11:55.129 I/AnkiDroid(25252): Participating in analytics sample (sample percentage vs random: 10 4)
02-26 07:11:55.129 I/AnkiDroid(25252): setOptIn(): from false to false
02-26 07:11:55.129 I/AnkiDroid(25252): Not participating in analytics sample (sample percentage vs random: 10 97)
02-26 07:11:55.216 I/AnkiDroid(25252): AnkiDroid Version = 2.17.1 (dd2f3762fb214f9dd51162b215974b23cc809713)
02-26 07:11:55.216 I/AnkiDroid(25252): 
02-26 07:11:55.216 I/AnkiDroid(25252): Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)
02-26 07:11:55.216 I/AnkiDroid(25252): 
02-26 07:11:55.216 I/AnkiDroid(25252): Android Version = 13 (SDK 33)
02-26 07:11:55.216 I/AnkiDroid(25252): 
02-26 07:11:55.216 I/AnkiDroid(25252): ProductFlavor = play
02-26 07:11:55.216 I/AnkiDroid(25252): 
02-26 07:11:55.216 I/AnkiDroid(25252): Manufacturer = samsung
02-26 07:11:55.216 I/AnkiDroid(25252): 
02-26 07:11:55.216 I/AnkiDroid(25252): Model = SM-A235M
02-26 07:11:55.216 I/AnkiDroid(25252): 
02-26 07:11:55.216 I/AnkiDroid(25252): Hardware = qcom
02-26 07:11:55.216 I/AnkiDroid(25252): 
02-26 07:11:55.216 I/AnkiDroid(25252): Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A235M Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.178 Mobile Safari/537.36
02-26 07:11:55.216 I/AnkiDroid(25252): 
02-26 07:11:55.216 I/AnkiDroid(25252): ACRA UUID = d81ff6ea-00ac-448f-ab03-cf64ab92cbcf
02-26 07:11:55.216 I/AnkiDroid(25252): 
02-26 07:11:55.216 I/AnkiDroid(25252): Crash Reports Enabled = true
02-26 07:12:05.196 I/AnkiDroid(25518): Timber config: PRODUCTION
02-26 07:12:05.197 I/AnkiDroid(25518): initialize()
02-26 07:12:05.360 I/AnkiDroid(25518): Not participating in analytics sample (sample percentage vs random: 10 42)
02-26 07:12:05.360 I/AnkiDroid(25518): setOptIn(): from false to false
02-26 07:12:05.360 I/AnkiDroid(25518): Not participating in analytics sample (sample percentage vs random: 10 97)
02-26 07:12:05.409 I/AnkiDroid(25518): AnkiDroid Version = 2.17.1 (dd2f3762fb214f9dd51162b215974b23cc809713)
02-26 07:12:05.409 I/AnkiDroid(25518): 
02-26 07:12:05.409 I/AnkiDroid(25518): Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)
02-26 07:12:05.409 I/AnkiDroid(25518): 
02-26 07:12:05.409 I/AnkiDroid(25518): Android Version = 13 (SDK 33)
02-26 07:12:05.409 I/AnkiDroid(25518): 
02-26 07:12:05.409 I/AnkiDroid(25518): ProductFlavor = play
02-26 07:12:05.409 I/AnkiDroid(25518): 
02-26 07:12:05.409 I/AnkiDroid(25518): Manufacturer = samsung
02-26 07:12:05.409 I/AnkiDroid(25518): 
02-26 07:12:05.409 I/AnkiDroid(25518): Model = SM-A235M
02-26 07:12:05.409 I/AnkiDroid(25518): 
02-26 07:12:05.409 I/AnkiDroid(25518): Hardware = qcom
02-26 07:12:05.409 I/AnkiDroid(25518): 
02-26 07:12:05.409 I/AnkiDroid(25518): Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A235M Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.178 Mobile Safari/537.36
02-26 07:12:05.409 I/AnkiDroid(25518): 
02-26 07:12:05.409 I/AnkiDroid(25518): ACRA UUID = d81ff6ea-00ac-448f-ab03-cf64ab92cbcf
02-26 07:12:05.409 I/AnkiDroid(25518): 
02-26 07:12:05.409 I/AnkiDroid(25518): Crash Reports Enabled = true
02-26 07:12:05.414 I/AnkiDroid(25518): Creating notification channel with id/name: General Notifications/AnkiDroid
02-26 07:12:05.415 I/AnkiDroid(25518): Creating notification channel with id/name: Synchronization/Sincronização
02-26 07:12:05.416 I/AnkiDroid(25518): Creating notification channel with id/name: Global Reminders/Cartões pendentes
02-26 07:12:05.416 I/AnkiDroid(25518): Creating notification channel with id/name: Deck Reminders/Lembretes
02-26 07:12:05.416 I/AnkiDroid(25518): Creating notification channel with id/name: Scoped Storage/Migração do armazenamento
02-26 07:12:05.428 I/AnkiDroid(25518): AnkiDroidApp: Starting Services
02-26 07:12:05.431 W/AnkiDroid(25518): AnkiDroidApp/ Boot Service did not execute - no permissions
02-26 07:12:05.468 I/AnkiDroid(25518): IntentHandler::onCreate
02-26 07:12:05.470 I/AnkiDroid(25518): Setting theme to BLACK
02-26 07:12:05.501 I/AnkiDroid(25518): isLegacyStorage(): current dir: /storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid
02-26 07:12:05.501 I/AnkiDroid(25518): scoped external dirs: /storage/emulated/0/Android/data/com.ichi2.anki/files
02-26 07:12:05.501 I/AnkiDroid(25518): scoped internal dir: /data/user/0/com.ichi2.anki/files
02-26 07:12:05.501 I/AnkiDroid(25518): isLegacyStorage(): false
02-26 07:12:05.501 I/AnkiDroid(25518): User has storage permissions. Running intent: android.intent.action.VIEW
02-26 07:12:05.501 I/AnkiDroid(25518): Handling file import
02-26 07:12:05.501 I/AnkiDroid(25518): IntentHandler/ User requested to view a file
02-26 07:12:05.501 I/AnkiDroid(25518): Intent: Intent { act=android.intent.action.VIEW dat=content://media/... typ=application/octet-stream flg=0x10000003 cmp=com.ichi2.anki/.IntentHandler (has extras) }. Data: android.intent.extra.REFERRER, android.intent.extra.ORIGINATING_URI
02-26 07:12:05.501 I/AnkiDroid(25518): Attempting to read data from intent.
02-26 07:12:06.562 I/AnkiDroid(25518): onCreate() import successful and downloaded file deleted
02-26 07:12:06.616 I/AnkiDroid(25518): Setting theme to BLACK
02-26 07:12:06.623 I/AnkiDroid(25518): DeckPicker::onCreate
02-26 07:12:06.625 I/AnkiDroid(25518): Displaying app intro
02-26 07:12:06.632 I/AnkiDroid(25518): finishWithAnimation DEFAULT
02-26 07:12:06.639 I/AnkiDroid(25518): IntentHandler::onDestroy
02-26 07:12:06.652 I/AnkiDroid(25518): Setting theme to BLACK
02-26 07:12:06.654 I/AnkiDroid(25518): IntroductionActivity::onCreate
02-26 07:12:06.666 I/AnkiDroid(25518): IntroductionActivity::SetupCollectionFragment::onAttach
02-26 07:12:06.667 I/AnkiDroid(25518): IntroductionActivity::SetupCollectionFragment::onCreate
02-26 07:12:06.668 I/AnkiDroid(25518): IntroductionActivity::onStart
02-26 07:12:06.698 I/AnkiDroid(25518): IntroductionActivity::SetupCollectionFragment::onViewCreated
02-26 07:12:06.699 I/AnkiDroid(25518): IntroductionActivity::SetupCollectionFragment::onStart
02-26 07:12:06.727 I/AnkiDroid(25518): IntroductionActivity::onResume
02-26 07:12:06.727 I/AnkiDroid(25518): Dispatching persistent message: 2
02-26 07:12:06.728 I/AnkiDroid(25518): IntroductionActivity::SetupCollectionFragment::onResume
02-26 07:12:06.753 I/AnkiDroid(25518): Handling Message: ImportAddDialog
```

**Comment by lukstbit** [comment]
@david-allison I've looked at this for a bit and came up with a solution, but barely tested(I don't have any more time now):

```patch
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt b/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
index 3b7028c798..22a3e56f32 100644
--- a/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
@@ -156,6 +156,11 @@ class IntentHandler : Activity() {
 
     private fun handleFileImport(intent: Intent, reloadIntent: Intent, action: String?) {
         Timber.i("Handling file import")
+        if (!this.sharedPrefs().getBoolean(IntroductionActivity.INTRODUCTION_SLIDES_SHOWN, false)) {
+            Timber.i("Asked to import when app wasn't started, aborting")
+            showThemedToast(this, "Please start the app before importing...", false)
+            return
+        }
         val importResult = handleFileImport(this, intent)
         // attempt to delete the downloaded deck if it is a shared deck download import
         if (intent.hasExtra(SharedDecksDownloadFragment.EXTRA_IS_SHARED_DOWNLOAD)) {
```
