### ISSUE TITLE
[Bug] : congrats.html: Error: 500: Fragment `CongratsPage` not attached to an activity.

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15679]
https://ankidroid.org/acra/app/1/bug/134025/report/f80a003f-bbda-4d57-8e1f-23036d59796d

```
com.ichi2.anki.exception.ManuallyReportedException: http://127.0.0.1:38927/backend/web/congrats.html#night: Error: 500: Fragment CongratsPage{537dc9d} (ea0a94d5-23b0-4aa5-8b98-c82e7dffb5fd) not attached to an activity.
	at com.ichi2.anki.CrashReportService.sendExceptionReport(SourceFile:1)
	at com.ichi2.anki.pages.PageChromeClient.onJsAlert(SourceFile:107)
	at WV.c6.run(chromium-TrichromeWebViewGoogle6432.aab-beta-631200342:138)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by david-allison** [comment]
Repro steps:

* Click a completed deck
* Click deck options
* Background the app

```
16:15:30.015 AnkiDroidApp$onCreate                I  SingleFragmentActivity::onStop
16:15:30.016 FragmentLifecycleLogger              I  SingleFragmentActivity::CongratsPage::onStop
16:15:30.017 AnkiDroidApp$onCreate                I  SingleFragmentActivity::onSaveInstanceState
16:15:30.017 FragmentLifecycleLogger              I  SingleFragmentActivity::CongratsPage::onSaveInstanceState
16:15:42.915 AnkiDroidApp$onCreate                I  SingleFragmentActivity::onPause
16:15:42.915 FragmentLifecycleLogger              I  SingleFragmentActivity::DeckOptions::onPause
16:15:43.320 AnkiDroidApp$onCreate                I  SingleFragmentActivity::onStop
16:15:43.320 FragmentLifecycleLogger              I  SingleFragmentActivity::DeckOptions::onStop
16:15:43.322 AnkiDroidApp$onCreate                I  SingleFragmentActivity::onSaveInstanceState
16:15:43.323 FragmentLifecycleLogger              I  SingleFragmentActivity::DeckOptions::onSaveInstanceState
16:15:47.262 TrafficStats                         D  tagSocket(139) with statsTag=0xffffffff, statsUid=-1
16:15:47.264 AnkiServer                           D  POST: Requested /_anki/congratsInfo
16:15:47.270 PageChromeClient                     D  JS Alert: Error: 500: Fragment CongratsPage{3fa5e9b} (39ae2a58-f3c1-4b13-ba66-8f5c9eba3c7c) not attached to an activity.
16:15:47.289                                      W  onJsAlert
16:15:47.301 cr_WebViewCallback                   W  Unable to create JsDialog. Has this WebView outlived the Activity it was created with?
16:15:47.303 chromium                             I  [INFO:CONSOLE(1)] "Uncaught (in promise) Error: 500: Fragment CongratsPage{3fa5e9b} (39ae2a58-f3c1-4b13-ba66-8f5c9eba3c7c) not attached to an activity.", source: http://127.0.0.1:42801/backend/web/congrats.js (1)
16:15:47.904 rsdroid::logging                     D  STDOUT: [INFO:CONSOLE(1)] "Uncaught (in promise) Error: 500: Fragment CongratsPage{3fa5e9b} (39ae2a58-f3c1-4b13-ba66-8f5c9eba3c7c) not attached to an activity.", source: http://127.0.0.1:42801/backend/web/congrats.js (1)
16:16:22.261 TrafficStats                         D  tagSocket(139) with statsTag=0xffffffff, statsUid=-1
16:16:22.263 AnkiServer                           D  POST: Requested /_anki/congratsInfo
16:16:47.256 TrafficStats                         D  tagSocket(139) with statsTag=0xffffffff, statsUid=-1
16:16:47.258 AnkiServer                           D  POST: Requested /_anki/congratsInfo
16:16:47.271 PageChromeClient                     D  JS Alert: Error: 500: Fragment CongratsPage{3fa5e9b} (39ae2a58-f3c1-4b13-ba66-8f5c9eba3c7c) not attached to an activity.
16:16:47.287                                      W  onJsAlert
16:16:47.300 cr_WebViewCallback                   W  Unable to create JsDialog. Has this WebView outlived the Activity it was created with?
16:16:47.302 chromium                             I  [INFO:CONSOLE(1)] "Uncaught (in promise) Error: 500: Fragment CongratsPage{3fa5e9b} (39ae2a58-f3c1-4b13-ba66-8f5c9eba3c7c) not attached to an activity.", source: http://127.0.0.1:42801/backend/web/congrats.js (1)
16:16:48.057 rsdroid::logging                     D  STDOUT: [INFO:CONSOLE(1)] "Uncaught (in promise) Error: 500: Fragment CongratsPage{3fa5e9b} (39ae2a58-f3c1-4b13-ba66-8f5c9eba3c7c) not attached to an activity.", source: http://127.0.0.1:42801/backend/web/congrats.js (1)
16:17:22.261 TrafficStats                         D  tagSocket(139) with statsTag=0xffffffff, statsUid=-1
16:17:22.263 AnkiServer                           D  POST: Requested /_anki/congratsInfo
16:17:47.260 TrafficStats                         D  tagSocket(139) with statsTag=0xffffffff, statsUid=-1
16:17:47.262 AnkiServer                           D  POST: Requested /_anki/congratsInfo
16:17:47.267 PageChromeClient                     D  JS Alert: Error: 500: Fragment CongratsPage{3fa5e9b} (39ae2a58-f3c1-4b13-ba66-8f5c9eba3c7c) not attached to an activity.
16:17:47.281                                      W  onJsAlert
16:17:47.289 cr_WebViewCallback                   W  Unable to create JsDialog. Has this WebView outlived the Activity it was created with?
16:17:47.290 chromium                             I  [INFO:CONSOLE(1)] "Uncaught (in promise) Error: 500: Fragment CongratsPage{3fa5e9b} (39ae2a58-f3c1-4b13-ba66-8f5c9eba3c7c) not attached to an activity.", source: http://127.0.0.1:42801/backend/web/congrats.js (1)
16:17:48.205 rsdroid::logging                     D  STDOUT: [INFO:CONSOLE(1)] "Uncaught (in promise) Error: 500: Fragment CongratsPage{3fa5e9b} (39ae2a58-f3c1-4b13-ba66-8f5c9eba3c7c) not attached to an activity.", source: http://127.0.0.1:42801/backend/web/congrats.js (1)

```

**Comment by criticalAY** [comment]
Probably override on resume looking into it if can fix it

**Comment by lukstbit** [comment]
I've closed the duplicate issue #15515

**Comment by david-allison** [comment]
Thanks! missed that

**Comment by BrayanDSO** [comment]
Will take a look

**Comment by BrayanDSO** [comment]
I can't reproduce in my phone right now and I'm away from my laptop.

If anyone wants to ease my life, try disabling the ChangeManager... line at `init` and tell me if they can still reproduce it

**Comment by BrayanDSO** [comment]
Still can't reproduce, so working here is hard
```text
2024-02-26 18:52:39.943  9905-9905  AnkiDroidApp$onCreate   com.ichi2.anki.debug                 I  SingleFragmentActivity::onPause
2024-02-26 18:52:39.943  9905-9905  FragmentLifecycleLogger com.ichi2.anki.debug                 I  SingleFragmentActivity::DeckOptions::onPause
2024-02-26 18:52:40.169  9905-9975  EGL_emulation           com.ichi2.anki.debug                 D  app_time_stats: avg=501.71ms min=498.21ms max=506.29ms count=3
2024-02-26 18:52:40.316  9905-9905  AnkiDroidApp$onCreate   com.ichi2.anki.debug                 I  SingleFragmentActivity::onStop
2024-02-26 18:52:40.317  9905-9905  FragmentLifecycleLogger com.ichi2.anki.debug                 I  SingleFragmentActivity::DeckOptions::onStop
2024-02-26 18:52:40.317  9905-9905  AnkiDroidApp$onCreate   com.ichi2.anki.debug                 I  SingleFragmentActivity::onSaveInstanceState
2024-02-26 18:52:40.317  9905-9905  FragmentLifecycleLogger com.ichi2.anki.debug                 I  SingleFragmentActivity::DeckOptions::onSaveInstanceState
2024-02-26 18:53:00.002  9905-9905  DayRolloverHandler      com.ichi2.anki.debug                 V  received android.intent.action.TIME_TICK
2024-02-26 18:53:25.046  9905-10506 AnkiServer              com.ichi2.anki.debug                 D  POST: Requested /_anki/congratsInfo
2024-02-26 18:54:00.001  9905-9905  DayRolloverHandler      com.ichi2.anki.debug                 V  received android.intent.action.TIME_TICK
2024-02-26 18:54:00.004  9905-9905  DayRolloverHandler      com.ichi2.anki.debug                 V  received android.intent.action.TIME_TICK
```

**Comment by david-allison** [comment]
Wait a minute with it in the background and it should appear

**Comment by criticalAY** [comment]
I can reproduce it

**Comment by BrayanDSO** [comment]
https://github.com/ankidroid/Anki-Android/assets/69634269/b4f054be-cf65-452e-b862-91ef02ded467
