### ISSUE TITLE
[Bug] CardBrowser NullPointerException

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15686]
likely due to no storage permissions

https://ankidroid.org/acra/app/1/bug/134200/report/db73fee5-8b77-4f20-bc05-a2aff3661cbf

```
java.lang.NullPointerException
	at com.ichi2.anki.CardBrowser$onCreate$11.invokeSuspend(SourceFile:117)
	at com.ichi2.anki.CardBrowser$onCreate$11.invoke(SourceFile:2)
	at com.ichi2.anki.CardBrowser$onCreate$11.invoke(SourceFile:1)
	at com.ichi2.anki.CardBrowser$launchCollectionInLifecycleScope$1$1.emit(SourceFile:3)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(SourceFile:206)
	at kotlinx.coroutines.flow.ReadonlyStateFlow.collect(Unknown Source:2)
	at com.ichi2.anki.CardBrowser$launchCollectionInLifecycleScope$1.invokeSuspend(SourceFile:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(SourceFile:131)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(SourceFile:3)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(SourceFile:6)
	at kotlinx.coroutines.CoroutineStart.invoke(SourceFile:10)
	at kotlinx.coroutines.AbstractCoroutine.start(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(SourceFile:23)
	at kotlinx.coroutines.BuildersKt.launch(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(SourceFile:13)
	at kotlinx.coroutines.BuildersKt.launch$default(SourceFile:1)
	at com.ichi2.anki.CardBrowser.launchCollectionInLifecycleScope(SourceFile:15)
	at com.ichi2.anki.CardBrowser.onCreate(SourceFile:539)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3403)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3594)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7698)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@eeda772, Dispatchers.Main.immediate]

```

**Comment by BrayanDSO** [comment]
easy way to reproduce that is using the `Browse` shortcut with the permissions disabled #13518

**Comment by criticalAY** [comment]
@david-allison I commented on #13518 but forgot to work/take it to the finish line. I will fix it in a day or so

**Comment by criticalAY** [comment]
Update: fixed it will push it after i wake up
