### ISSUE TITLE
[Bug] `getAppSpecificExternalAnkiDroidDirectory` -> `NullPointerException`

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15723]
https://ankidroid.org/acra/app/1/bug/136121/report/c6449bb2-1d25-4dcb-b0eb-10dad5b09add

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.DeckPicker}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7959)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.NullPointerException
	at com.ichi2.anki.CollectionHelper$Companion.getAppSpecificExternalAnkiDroidDirectory(SourceFile:6)
	at com.ichi2.anki.CollectionHelper$Companion.getDefaultAnkiDroidDirectory(SourceFile:22)
	at com.ichi2.anki.CollectionHelper$Companion.getCurrentAnkiDroidDirectoryOptionalContext$lambda$1(SourceFile:14)
	at com.ichi2.anki.CollectionHelper$Companion.b(SourceFile:1)
	at com.ichi2.anki.z1.get(SourceFile:1)
	at com.ichi2.preferences.PreferenceExtensionsKt.getOrSetString(SourceFile:32)
	at com.ichi2.anki.CollectionHelper$Companion.getCurrentAnkiDroidDirectoryOptionalContext$AnkiDroid_playRelease(SourceFile:64)
	at com.ichi2.anki.CollectionHelper$Companion.getCurrentAnkiDroidDirectory(SourceFile:15)
	at com.ichi2.anki.servicelayer.ScopedStorageService.isLegacyStorage(SourceFile:1)
	at com.ichi2.anki.services.MigrationServiceKt.getMediaMigrationState$collectionIsInAppPrivateDirectory(SourceFile:3)
	at com.ichi2.anki.services.MigrationServiceKt.getMediaMigrationState(SourceFile:41)
	at com.ichi2.anki.DeckPicker.startingStorageMigrationInterruptsStartup(SourceFile:1)
	at com.ichi2.anki.DeckPicker.handleStartup(SourceFile:8)
	at com.ichi2.anki.DeckPicker.onCreate(SourceFile:124)
	at android.app.Activity.performCreate(Activity.java:8348)
	at android.app.Activity.performCreate(Activity.java:8327)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1423)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
```

**Comment by mikehardy** [comment]
What !? Can't trust anything
