### ISSUE TITLE
Previewer crashes when opening a note in the 23 and 25 emulators in 2.17.5

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#15878]
in both the legacy previewer and the new one. Same cause:

```text
java.lang.NoClassDefFoundError: java.nio.file.Path
 at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
 at java.lang.Class.getDexCacheType(Class.java:476)
 at java.lang.reflect.Method.getReturnType(Method.java:183)
 at java.lang.Class.getDeclaredMethods(Class.java:672)
 at java.io.ObjectStreamClass.computeSerialVersionUID(ObjectStreamClass.java:566)
 at java.io.ObjectStreamClass.createClassDesc(ObjectStreamClass.java:279)
 at java.io.ObjectStreamClass.lookupStreamClass(ObjectStreamClass.java:1087)
 at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1554)
 at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
 at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
 at android.os.Parcel.writeSerializable(Parcel.java:1442)
 at android.os.Parcel.writeValue(Parcel.java:1395)
 at android.os.Parcel.writeArrayMapInternal(Parcel.java:665)
 at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330)
 at android.os.Bundle.writeToParcel(Bundle.java:1079)
 at android.os.Parcel.writeBundle(Parcel.java:690)
 at android.content.Intent.writeToParcel(Intent.java:7793)
 at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2639)
 at android.app.Instrumentation.execStartActivity(Instrumentation.java:1507)
 at android.app.Activity.startActivityForResult(Activity.java:3917)
 at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:780)
 at androidx.core.app.ActivityCompat$Api16Impl.startActivityForResult(ActivityCompat.java:854)
 at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:245)
 at androidx.activity.ComponentActivity$1.onLaunch(ComponentActivity.java:239)
 at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:173)
 at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
 at com.ichi2.anki.CardBrowser.onPreview(CardBrowser.kt:1219)
 at com.ichi2.anki.CardBrowser.onOptionsItemSelected(CardBrowser.kt:1095)
 at android.app.Activity.onMenuItemSelected(Activity.java:2908)
 at androidx.activity.ComponentActivity.onMenuItemSelected(ComponentActivity.java:528)
 at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:264)
 at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:269)
 at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
 at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:66)
 at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:225)
 at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:769)
 at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:833)
 at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
 at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:984)
 at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
 at android.widget.AdapterView.performItemClick(AdapterView.java:310)
 at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
 at android.widget.AbsListView$PerformClick.run(AbsListView.java:3042)
 at android.widget.AbsListView$3.run(AbsListView.java:3879)
 at android.os.Handler.handleCallback(Handler.java:739)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:148)
```

**Comment by BrayanDSO** [comment]
Making `PreviewerIdsFile` a `Parcelable` fixes it, but need investigation to see if it's the best solution

```diff
Subject: [PATCH] .
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt b/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt	(revision 3d8e8c68e5a93244e462901c0a214f0566716bc8)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt	(date 1710362064045)
@@ -19,6 +19,8 @@
 import android.content.Context
 import android.content.Intent
 import android.os.Bundle
+import android.os.Parcel
+import android.os.Parcelable
 import androidx.core.os.bundleOf
 import com.ichi2.async.saveModel
 import com.ichi2.compat.CompatHelper.Companion.compat
@@ -31,7 +33,11 @@
 import timber.log.Timber
 import java.io.ByteArrayInputStream
 import java.io.ByteArrayOutputStream
+import java.io.DataInputStream
+import java.io.DataOutputStream
 import java.io.File
+import java.io.FileInputStream
+import java.io.FileOutputStream
 import java.io.IOException
 
 /** A wrapper for a notetype in JSON format with helpers for editing the notetype. */
@@ -454,17 +460,14 @@
  * The notetype is written into a file because there is a
  * [limit of 1MB](https://developer.android.com/reference/android/os/TransactionTooLargeException.html)
  * for [Bundle] transactions, and notetypes can be bigger than that (#5600).
- *
- * @param directory parent directory of the file. Generally it should be the cache directory
- * @param notetype to be stored
- */
-class NotetypeFile(directory: File, notetype: NotetypeJson) :
-    File(createTempFile("notetype", ".tmp", directory).absolutePath) {
-
-    /** @param context for getting the cache directory */
-    constructor(context: Context, notetype: NotetypeJson) : this(context.cacheDir, notetype)
-
-    init {
+ */
+class NotetypeFile(path: String) : File(path), Parcelable {
+
+    /**
+     * @param context for getting the cache directory
+     * @param notetype to be stored
+     */
+    constructor(context: Context, notetype: NotetypeJson) : this(createTempFile("notetype", ".tmp", context.cacheDir).absolutePath) {
         try {
             ByteArrayInputStream(notetype.toString().toByteArray()).use { source ->
                 compat.copyFile(source, this.absolutePath)
@@ -485,4 +488,25 @@
             throw e
         }
     }
+
+    override fun describeContents(): Int = 0
+
+    override fun writeToParcel(dest: Parcel, flags: Int) {
+        dest.writeString(path)
+    }
+
+    companion object {
+        @JvmField
+        @Suppress("unused")
+        val CREATOR = object : Parcelable.Creator<NotetypeFile> {
+            override fun createFromParcel(source: Parcel?): NotetypeFile {
+                return NotetypeFile(source!!.readString()!!)
+            }
+
+            override fun newArray(size: Int): Array<NotetypeFile> {
+                return arrayOf()
+            }
+        }
+    }
 }
+
Index: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt b/AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt	(revision 3d8e8c68e5a93244e462901c0a214f0566716bc8)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt	(date 1710361901366)
@@ -16,6 +16,8 @@
 
 package com.ichi2.anki.browser
 
+import android.os.Parcel
+import android.os.Parcelable
 import androidx.core.content.edit
 import androidx.lifecycle.ViewModel
 import androidx.lifecycle.viewModelScope
@@ -573,13 +575,14 @@
 
 /**
  * Temporary file containing the IDs of the cards to be displayed at the previewer
- *
- * @param directory parent directory of the file. Generally it should be the cache directory
- * @param cardIds ids of the cards to be displayed
- */
-class PreviewerIdsFile(directory: File, cardIds: List<CardId>) :
-    File(createTempFile("previewerIds", ".tmp", directory).absolutePath) {
-    init {
+ */
+class PreviewerIdsFile(path: String): File(path), Parcelable {
+
+    /**
+     * @param directory parent directory of the file. Generally it should be the cache directory
+     * @param cardIds ids of the cards to be displayed
+     */
+    constructor(directory: File, cardIds: List<CardId>): this(createTempFile("previewerIds", ".tmp", directory).path) {
         DataOutputStream(FileOutputStream(this)).use { outputStream ->
             outputStream.writeInt(cardIds.size)
             for (id in cardIds) {
@@ -592,4 +595,24 @@
         val size = inputStream.readInt()
         List(size) { inputStream.readLong() }
     }
+
+    override fun describeContents(): Int = 0
+
+    override fun writeToParcel(dest: Parcel, flags: Int) {
+        dest.writeString(path)
+    }
+
+    companion object {
+        @JvmField
+        @Suppress("unused")
+        val CREATOR = object : Parcelable.Creator<PreviewerIdsFile> {
+            override fun createFromParcel(source: Parcel?): PreviewerIdsFile {
+                return PreviewerIdsFile(source!!.readString()!!)
+            }
+
+            override fun newArray(size: Int): Array<PreviewerIdsFile> {
+                return arrayOf()
+            }
+        }
+    }
 }
```

**Comment by david-allison** [comment]
Worth filing a bug on the desugaring library for this one

**Comment by BrayanDSO** [comment]
Going to close this until some actual user comes or there is a crash report

**Comment by BrayanDSO** [comment]
Real issue now:
https://ankidroid.org/acra/app/1/bug/171738/report/af826974-3767-48b7-b025-98594e106104

**Comment by mikehardy** [comment]
> Worth filing a bug on the desugaring library for this one

That's what I was thinking! java.nio.file.Path is supposed to be safe now ?
the github repo doesn't have issues on and I don't see any PR or commit activity that looks like a hit
I suppose you have to use the issuetracker website for this one but I don't see anything in there either, even with very broad searches
