### ISSUE TITLE
Reported Issue: Crash on Settings - Accessibility

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16028]
> On the latest  ankidroid 2.18 alpha 7 opening `setting->accessibility`  throws error on my part, anyone can confirm it?

https://discord.com/channels/368267295601983490/701939078786187315/1223832078660145193

Can't reproduce

**Comment by david-allison** [comment]
Likely: https://ankidroid.org/acra/app/1/bug/150408/report/acb14a12-3bc2-4cc7-ae2e-504c0737476a

```
java.lang.IllegalStateException: Value(20.0) must be equal to valueFrom(0.0) plus a multiple of stepSize(100.0) when using stepSize(100.0)
	at com.google.android.material.slider.BaseSlider.validateValues(SourceFile:98)
	at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(SourceFile:14)
	at com.google.android.material.slider.BaseSlider.maybeCalculateTicksCoordinates(SourceFile:9)
	at com.google.android.material.slider.BaseSlider.updateTrackWidth(SourceFile:13)
	at com.google.android.material.slider.BaseSlider.onSizeChanged(SourceFile:1)
	at android.view.View.sizeChange(View.java:25964)
	at android.view.View.setFrame(View.java:25897)
	at android.view.View.layout(View.java:25748)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1880)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1640)
	at android.view.View.layout(View.java:25754)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25754)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1880)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1640)
	at android.view.View.layout(View.java:25754)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(SourceFile:33)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(SourceFile:171)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:39)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:358)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:67)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:72)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:6)
	at android.view.View.layout(View.java:25754)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25754)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25754)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25754)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(SourceFile:71)
	at android.view.View.layout(View.java:25754)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(SourceFile:144)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(SourceFile:29)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:49)
	at android.view.View.layout(View.java:25754)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25754)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25754)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25754)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25754)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1094)
	at android.view.View.layout(View.java:25754)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:5236)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4502)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3275)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11269)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1650)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1659)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1129)
	at android.view.Choreographer.doFrame(Choreographer.java:1055)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1622)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8913)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by david-allison** [comment]
Cause: 0356b509065808f79d5b1c9ebc07d7a8cce8bf5b

* https://github.com/ankidroid/Anki-Android/pull/15736

**Comment by david-allison** [comment]
Yes, it's still an issue. The problem was setting a value of `20ms`, which is no longer supported with the slider
