### ISSUE TITLE
Copy debug info: WebView cannot be initialized on a thread that has no Looper.

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#16077]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Click Copy Debug Info

### Expected behaviour

No error

### Actual behaviour

Report is generated and sent

### Debug info

```text
AnkiDroid Version = 2.18alpha8 (6fc26947fd31743bc83e68f17ae7fec64bfa8e62)

Backend Version = provider(?) (24.04 429bc9e14cefb597646a0e1beac6ef140f226b6f)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = motorola

Model = moto g62 5G

Hardware = qcom

Webview User Agent = null

ACRA UUID = 70fd8e4a-1bcf-4f20-8bac-43ba9946410f

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Modified Anki-Android-Backend's build script:

```
Anki commit: fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf
Anki version: 24.04
```

```gradle
        buildConfigField "String", "ANKI_COMMIT_HASH", "\"${getAnkiCommitHash()}\""
        buildConfigField "String", "ANKI_DESKTOP_VERSION", "\"${getAnkiDesktopVersion()}\""
```

**Comment by david-allison** [comment]
Issue: https://github.com/ankidroid/Anki-Android/blob/6fc26947fd31743bc83e68f17ae7fec64bfa8e62/AnkiDroid/build.gradle#L49

Introduced in bb0c4a85bf71f442170cf7626a60bd6892c35649

* https://github.com/ankidroid/Anki-Android/pull/15966

**Comment by david-allison** [comment]
@user1823 I may have misunderstood and caught another bug

How did you get this debug info if `Copy Debug Info` is not usable?

**Comment by david-allison** [comment]
https://ankidroid.org/acra/app/1/bug/150804/report/6354100e-a5b6-4bd5-954c-e4c7c59ce274

```
java.lang.RuntimeException: WebView cannot be initialized on a thread that has no Looper.
	at android.webkit.WebView.<init>(WebView.java:435)
	at android.webkit.WebView.<init>(WebView.java:363)
	at android.webkit.WebView.<init>(WebView.java:345)
	at android.webkit.WebView.<init>(WebView.java:332)
	at android.webkit.WebView.<init>(WebView.java:322)
	at com.ichi2.anki.servicelayer.DebugInfoService.getWebviewUserAgent(SourceFile:3)
	at com.ichi2.anki.servicelayer.DebugInfoService.getDebugInfo(SourceFile:65)
	at com.ichi2.anki.preferences.AboutFragment$copyDebugInfo$1$debugInfo$1.invokeSuspend(SourceFile:42)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:129)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(SourceFile:4)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(SourceFile:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(SourceFile:29)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:1)
```

**Comment by david-allison** [comment]
Cause: 4506cb4d09376b3da5d4476e5d3cd8a6edc1dfd0
* https://github.com/ankidroid/Anki-Android/pull/15749

`getDebugInfo` was made `suspend`, which meant that `getWebviewUserAgent` could potentially be run on a different thread

**Comment by user1823** [comment]
> How did you get this debug info if Copy Debug Info is not usable?

I guess that my reply is no longer needed. Anyways, the answer is that the debug info was still copied to the clipboard even though an error appeared.
