### ISSUE TITLE
Flaky tests: `nextDueTest` and `resetDataTest`

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16129]
Note: `main` passed before I reran tests. Timing issue?

https://github.com/ankidroid/Anki-Android/actions/runs/8593334396/job/23544695906

```
CardBrowserTest > nextDueTest FAILED
    org.junit.ComparisonFailure: expected:<8/2[7]/20> but was:<8/2[8]/20>
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at com.ichi2.anki.CardBrowserTest.nextDueTest(CardBrowserTest.kt:1123)

CardBrowserTest > resetDataTest FAILED
    java.lang.AssertionError: Initial due of checked card
    Expected: "8/12/20"
         but: was "8/13/20"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at com.ichi2.anki.CardBrowserTest$resetDataTest$1.invokeSuspend(CardBrowserTest.kt:569)
        at com.ichi2.anki.CardBrowserTest$resetDataTest$1.invoke(CardBrowserTest.kt)
        at com.ichi2.anki.CardBrowserTest$resetDataTest$1.invoke(CardBrowserTest.kt)
        at com.ichi2.testutils.TestClass$runTest$1$1.invokeSuspend(TestClass.kt:236)
        at com.ichi2.testutils.TestClass$runTest$1$1.invoke(TestClass.kt)
        at com.ichi2.testutils.TestClass$runTest$1$1.invoke(TestClass.kt)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$1.invokeSuspend(TestBuilders.kt:316)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.test.TestDispatcher.processEvent$kotlinx_coroutines_test(TestDispatcher.kt:24)
        at kotlinx.coroutines.test.TestCoroutineScheduler.tryRunNextTaskUnless$kotlinx_coroutines_test(TestCoroutineScheduler.kt:99)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$workRunner$1.invokeSuspend(TestBuilders.kt:322)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at kotlinx.coroutines.test.TestBuildersJvmKt.createTestResult(TestBuildersJvm.kt:10)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:310)
        at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:[168](https://github.com/ankidroid/Anki-Android/actions/runs/8593334396/job/23544695906#step:8:170))
        at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
        at com.ichi2.testutils.TestClass.runTest(TestClass.kt:234)
        at com.ichi2.testutils.TestClass.runTest$default(TestClass.kt:223)
        at com.ichi2.anki.CardBrowserTest.resetDataTest(CardBrowserTest.kt:556)
```

**Comment by david-allison** [comment]
Likely cause: 514081050b816109f4bf2536d38c7c3ffcd5d76e
* https://github.com/ankidroid/Anki-Android/pull/16068

Seems like potential functionality deviation, so tests shouldn't be ignored

**Comment by BrayanDSO** [comment]
Happened just now, in 00:21 UTC+0

https://github.com/ankidroid/Anki-Android/actions/runs/8608288518/job/23590377837?pr=16140#step:8:178

**Comment by david-allison** [comment]
Needs a `git bisect` and a revert of the relevant PR. I'll be risk averse if it's a potential scheduling issue
