### ISSUE TITLE
[BUG]: Error on answering card

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#16217]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

- Rate a card `Good`.

### Expected behaviour

No error

### Actual behaviour

<img width=300 src="https://github.com/ankidroid/Anki-Android/assets/92206575/0d311493-7ffd-401a-bf58-0aee08c0f608">

After dismissing the error and rating the card again, the "card was modified" error appears because the card was already rated but the reviewer didn't progress to the next card.

### Debug info

```text
AnkiDroid Version = 2.18alpha9 (7da94c1238199a166310b7db63d53d5dbb40f054)

Backend Version = 0.1.36-anki24.04 (24.04 429bc9e14cefb597646a0e1beac6ef140f226b6f)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = motorola

Model = moto g62 5G

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; moto g62 5G Build/T1SSIS33.1-75-7-5; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.118 Mobile Safari/537.36

ACRA UUID = 70fd8e4a-1bcf-4f20-8bac-43ba9946410f

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Does this happen all the time, or only rarely?

**Comment by user1823** [comment]
It happens every time.

It also happens on clicking Save after changing some settings in Deck Options. Then, I have to exit by clicking Discard changes though the changes are still saved.

**Comment by david-allison** [comment]
I suspect:

```
java.lang.NullPointerException
	at com.ichi2.anki.CardBrowser$onCreate$12.invokeSuspend(SourceFile:117)
	at com.ichi2.anki.CardBrowser$onCreate$12.invoke(SourceFile:2)
	at com.ichi2.anki.CardBrowser$onCreate$12.invoke(SourceFile:1)
	at com.ichi2.anki.CardBrowser$launchCollectionInLifecycleScope$1$1.emit(SourceFile:24)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(SourceFile:210)
	at kotlinx.coroutines.flow.ReadonlyStateFlow.collect(Unknown Source:2)
	at com.ichi2.anki.CardBrowser$launchCollectionInLifecycleScope$1.invokeSuspend(SourceFile:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(SourceFile:131)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(SourceFile:3)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(SourceFile:6)
	at kotlinx.coroutines.CoroutineStart.invoke(SourceFile:10)
	at kotlinx.coroutines.AbstractCoroutine.start(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(SourceFile:23)
	at kotlinx.coroutines.BuildersKt.launch(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(SourceFile:13)
	at kotlinx.coroutines.BuildersKt.launch$default(SourceFile:1)
	at com.ichi2.anki.CardBrowser.launchCollectionInLifecycleScope(SourceFile:15)
	at com.ichi2.anki.CardBrowser.onCreate(SourceFile:517)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Activity.performCreate(Activity.java:8270)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@88bd202, Dispatchers.Main.immediate]
```

**Comment by user1823** [comment]
Also occurs on clicking `Suspend card` in the reviewer or `Toggle suspend` in the browser

**Comment by user1823** [comment]
This bug seems to affect almost every function of the app. Adding an automated test for this seems to be important.

**Comment by user1823** [comment]
A new finding: Closing the app by swiping it away from the app drawer and then relaunching the app made the issue disappear.

**Comment by david-allison** [comment]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference
	at com.ichi2.libanki.ChangeManager.notifySubscribers(SourceFile:24)
	at com.ichi2.libanki.ChangeManager.notifySubscribers$AnkiDroid_fullRelease(SourceFile:65)
	at com.ichi2.libanki.ChangeManagerKt$undoableOp$3$1.invokeSuspend(SourceFile:17)
	at com.ichi2.libanki.ChangeManagerKt$undoableOp$3$1.invoke(SourceFile:2)
	at com.ichi2.libanki.ChangeManagerKt$undoableOp$3$1.invoke(SourceFile:1)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(SourceFile:8)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(SourceFile:54)
	at kotlinx.coroutines.BuildersKt.withContext(SourceFile:1)
	at com.ichi2.libanki.ChangeManagerKt.undoableOp(SourceFile:96)
	at com.ichi2.libanki.ChangeManagerKt$undoableOp$1.invokeSuspend(Unknown Source:10)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:129)
	at android.os.Handler.handleCallback(Handler.java:984)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8088)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
```

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/blob/f4ea73aeab52962e85ad8eb6e04af4fe1932173f/AnkiDroid/src/main/java/com/ichi2/libanki/ChangeManager.kt#L59-L72

No immediate clue. I strongly suspect it's a threading issue
