### ISSUE TITLE
[BUG] 2.18 [CardTemplateFragment]: lateinit property viewPager has not been initialized 

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16301]
https://ankidroid.org/acra/app/1/bug/164453/report/436f97c8-3059-468a-a6ee-57ae6fb9feb5

```
kotlin.UninitializedPropertyAccessException: lateinit property viewPager has not been initialized
	at com.ichi2.anki.CardTemplateEditor.getViewPager(SourceFile:8)
	at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment.initTabLayoutMediator(SourceFile:40)
	at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment.onViewCreated(SourceFile:6)
	at androidx.fragment.app.Fragment.performViewCreated(SourceFile:15)
	at androidx.fragment.app.FragmentStateManager.createView(SourceFile:314)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:128)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(SourceFile:31)
	at androidx.fragment.app.FragmentManager.moveToState(SourceFile:28)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(SourceFile:10)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(SourceFile:12)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(SourceFile:5)
	at androidx.fragment.app.FragmentActivity.onStart(SourceFile:21)
	at androidx.appcompat.app.AppCompatActivity.onStart(SourceFile:1)
	at com.ichi2.anki.AnkiActivity.onStart(SourceFile:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1456)
	at android.app.Activity.performStart(Activity.java:8195)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3796)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
```

**Comment by david-allison** [comment]
Trimmed:

```
--------- beginning of main
04-30 17:48:41.491 I/AnkiDroid(  611): Timber config: PRODUCTION
04-30 17:48:41.491 I/AnkiDroid(  611): initialize()
04-30 17:48:41.640 I/AnkiDroid(  611): Not participating in analytics sample (sample percentage vs random: 10 74)
04-30 17:48:41.640 I/AnkiDroid(  611): setOptIn(): from false to false
04-30 17:48:41.640 I/AnkiDroid(  611): Participating in analytics sample (sample percentage vs random: 10 9)
04-30 17:48:41.688 I/AnkiDroid(  611): Creating notification channel with id/name: General Notifications/AnkiDroid
04-30 17:48:41.689 I/AnkiDroid(  611): Creating notification channel with id/name: Synchronization/Đồng bộ
04-30 17:48:41.689 I/AnkiDroid(  611): Creating notification channel with id/name: Global Reminders/Những thẻ tới hạn
04-30 17:48:41.690 I/AnkiDroid(  611): Creating notification channel with id/name: Deck Reminders/Nhắc nhở
04-30 17:48:41.690 I/AnkiDroid(  611): Creating notification channel with id/name: Scoped Storage/Storage migration
04-30 17:48:41.697 I/AnkiDroid(  611): AnkiDroidApp: Starting Services
04-30 17:48:41.697 W/AnkiDroid(  611): AnkiDroidApp/ Boot Service did not execute - no permissions
04-30 17:48:41.724 I/AnkiDroid(  611): Setting theme to LIGHT
04-30 17:48:41.739 I/AnkiDroid(  611): CardTemplateEditor::onCreate
04-30 17:48:41.741 I/AnkiDroid(  611): CardTemplateEditor::CardTemplateFragment::onAttach
04-30 17:48:41.742 I/AnkiDroid(  611): CardTemplateEditor::CardTemplateFragment::onCreate
04-30 17:48:41.785 I/AnkiDroid(  611): CardTemplateEditor::onStart
04-30 17:48:41.833 I/AnkiDroid(  611): CollectionLoader obtained collection
```
