### ISSUE TITLE
Previewer [Don't keep Activities]: lateinit property currentCard has not been initialized

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16322]
```
11:08:17.679 CoroutineH...chCatching com.ichi2.anki.debug                 W  kotlin.UninitializedPropertyAccessException: lateinit property currentCard has not been initialized
                                                                             	at com.ichi2.anki.previewer.TemplatePreviewerViewModel.getCurrentCard(TemplatePreviewerViewModel.kt:61)
                                                                             	at com.ichi2.anki.previewer.CardViewerViewModel.showQuestion$suspendImpl(CardViewerViewModel.kt:122)
                                                                             	at com.ichi2.anki.previewer.CardViewerViewModel.showQuestion(Unknown Source:0)
                                                                             	at com.ichi2.anki.previewer.TemplatePreviewerViewModel$onPageFinished$1.invokeSuspend(TemplatePreviewerViewModel.kt:102)
                                                                             	at com.ichi2.anki.previewer.TemplatePreviewerViewModel$onPageFinished$1.invoke(Unknown Source:8)
                                                                             	at com.ichi2.anki.previewer.TemplatePreviewerViewModel$onPageFinished$1.invoke(Unknown Source:4)
                                                                             	at com.ichi2.anki.CoroutineHelpersKt$launchCatchingIO$2.invokeSuspend(CoroutineHelpers.kt:112)
                                                                             	at com.ichi2.anki.CoroutineHelpersKt$launchCatchingIO$2.invoke(Unknown Source:8)
                                                                             	at com.ichi2.anki.CoroutineHelpersKt$launchCatchingIO$2.invoke(Unknown Source:4)
                                                                             	at com.ichi2.anki.CoroutineHelpersKt$launchCatching$1.invokeSuspend(CoroutineHelpers.kt:89)
                                                                             	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                             	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                             	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                             	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
                                                                             	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                             	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                             	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                             	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```

**Comment by Aditya13s** [comment]
What are the steps to reproduce this? @david-allison

**Comment by david-allison** [comment]
No clue
