### ISSUE TITLE
[BUG] Card Browser: "Can't sort notes by Custom"

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16514]
![image](https://github.com/ankidroid/Anki-Android/assets/62114487/5620a476-2c3d-4405-a225-482a9318580b)

**Comment by david-allison** [comment]
```
W  com.ichi2.libanki.exception.InvalidSearchException: net.ankiweb.rsdroid.exceptions.BackendInvalidInputException: Can't sort Notes by Custom.
  	at com.ichi2.libanki.Collection.findNotes(Collection.kt:398)
  	at com.ichi2.libanki.Collection.findOneCardByNote(Collection.kt:411)
  	at com.ichi2.anki.CardBrowserKt.searchForCards$lambda$0(CardBrowser.kt:2311)
  	at com.ichi2.anki.CardBrowserKt.$r8$lambda$SvxaASTuq0hKmRmVoFHOLFGl_0Y(Unknown Source:0)
  	at com.ichi2.anki.CardBrowserKt$$ExternalSyntheticLambda2.invoke(D8$$SyntheticClass:0)
  	at com.ichi2.anki.CollectionManager.withCol$lambda$1(CollectionManager.kt:116)
  	at com.ichi2.anki.CollectionManager.$r8$lambda$ffr4nUlMOyAvThaKA2WuJlnLaPU(Unknown Source:0)
  	at com.ichi2.anki.CollectionManager$$ExternalSyntheticLambda10.invoke(D8$$SyntheticClass:0)
  	at com.ichi2.anki.CollectionManager$withQueue$3.invokeSuspend(CollectionManager.kt:100)
  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
  	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
  	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
  Caused by: net.ankiweb.rsdroid.exceptions.BackendInvalidInputException: Can't sort Notes by Custom.
  	at net.ankiweb.rsdroid.exceptions.BackendInvalidInputException$Companion.fromInvalidInputError(BackendInvalidInputException.kt:37)
  	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:114)
  	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:271)
  	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
  	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:118)
  	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:117)
  	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:131)
  	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:117)
  	at anki.backend.GeneratedBackend.searchNotesRaw(GeneratedBackend.kt:1847)
  	at anki.backend.GeneratedBackend.searchNotes(GeneratedBackend.kt:1853)
  	at com.ichi2.libanki.Collection.findNotes(Collection.kt:396)
  	at com.ichi2.libanki.Collection.findOneCardByNote(Collection.kt:411) 
  	at com.ichi2.anki.CardBrowserKt.searchForCards$lambda$0(CardBrowser.kt:2311) 
  	at com.ichi2.anki.CardBrowserKt.$r8$lambda$SvxaASTuq0hKmRmVoFHOLFGl_0Y(Unknown Source:0) 
  	at com.ichi2.anki.CardBrowserKt$$ExternalSyntheticLambda2.invoke(D8$$SyntheticClass:0) 
  	at com.ichi2.anki.CollectionManager.withCol$lambda$1(CollectionManager.kt:116) 
  	at com.ichi2.anki.CollectionManager.$r8$lambda$ffr4nUlMOyAvThaKA2WuJlnLaPU(Unknown Source:0) 
  	at com.ichi2.anki.CollectionManager$$ExternalSyntheticLambda10.invoke(D8$$SyntheticClass:0) 
  	at com.ichi2.anki.CollectionManager$withQueue$3.invokeSuspend(CollectionManager.kt:100) 
  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
  	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115) 
  	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100) 
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584) 
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793) 
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697) 
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684) 
```

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/blob/f336065d12b84d82ba705f97cd2e5b9b6202cf7e/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt#L383-L401

`order: UseCollectionOrdering`
`config.get("noteSortType") = "_field_Frequency"`
