### ISSUE TITLE
[BUG]: "Reset progress" can't work in Reviewer on the spot and causes error

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#17079]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Show a review card in Reviewer
     <img src="https://github.com/user-attachments/assets/ef87ae27-ddd1-40bb-b32c-f5491b36fefc" width="320px">
     
     (counterpart screen in Desktop)
     <img src="https://github.com/user-attachments/assets/cd24695e-3b11-4675-b315-42dc5fcb1061" width="320px">

2. "Reschedule" > "Reset progress" > "OK"
     <img src="https://github.com/user-attachments/assets/91adf2ac-07fc-45df-9f0e-d101e76e9628" width="320px">

     <img src="https://github.com/user-attachments/assets/9bc06a6f-884c-4990-8342-ec37db10ee0a" width="320px">

   (then, a message, "1 card reset", is shown) 
     <img src="https://github.com/user-attachments/assets/fc9b9a83-f536-46e9-bb86-32cfb9268562" width="320px">

**Result**
- The numbers of review cards and new cards are unchanged. (Supposedly, the card is still treated as a review card.)
     <img src="https://github.com/user-attachments/assets/3d428b0a-90ce-42f1-803d-5fd734d75139" width="320px">

- Selecting an answer button causes an error
     <img src="https://github.com/user-attachments/assets/cded7c4d-cf20-4a60-a390-b46e94063180" width="320px">
     <img src="https://github.com/user-attachments/assets/8ec45157-9488-4741-88d0-39f21d4cef0a" width="320px">

https://github.com/user-attachments/assets/1547c887-ef42-4e37-b90a-835987e62e78

### Expected behaviour

The count number of review cards decreases by one, and the count number of new cards increases by one, as in the desktop version. (The cards is treated as a new card on the spot.)

![image](https://github.com/user-attachments/assets/c74940dc-09ec-4f40-950d-07a411aa98c3)

### Debug info

```text
AnkiDroid Version = 2.19beta2 (2dab92e5214d6e21ebe2dd3a05e20a04ed7a9858)

Backend Version = 0.1.40-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/128.0.6613.127 Mobile Safari/537.36

ACRA UUID = 5e59349c-ede4-4942-91b7-199dcf1342c0

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Sure

**Comment by oyeraghib** [comment]
Current error logs after reproducing the above steps :

```
  E  net.ankiweb.rsdroid.exceptions.BackendInvalidInputException: card was modified: Normal(
                                                                                                        New(
                                                                                                            NewState {
                                                                                                                position: 15,
                                                                                                            },
                                                                                                        ),
                                                                                                    ) Normal(
                                                                                                        Learning(
                                                                                                            LearnState {
                                                                                                                remaining_steps: 1,
                                                                                                                scheduled_secs: 600,
                                                                                                                elapsed_secs: 15883707,
                                                                                                                memory_state: None,
                                                                                                            },
                                                                                                        ),
                                                                                                    )
                                                                                                    	at net.ankiweb.rsdroid.exceptions.BackendInvalidInputException$Companion.fromInvalidInputError(BackendInvalidInputException.kt:37)
                                                                                                    	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:114)
                                                                                                    	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:281)
                                                                                                    	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
                                                                                                    	at net.ankiweb.rsdroid.Backend.runMethodRaw$lambda$1(Backend.kt:118)
                                                                                                    	at net.ankiweb.rsdroid.Backend.$r8$lambda$rLALQVYPlbbEmpwIB7kwMA6SO_U(Unknown Source:0)
                                                                                                    	at net.ankiweb.rsdroid.Backend$$ExternalSyntheticLambda2.invoke(D8$$SyntheticClass:0)
                                                                                                    	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:131)
                                                                                                    	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:117)
                                                                                                    	at anki.backend.GeneratedBackend.answerCardRaw(GeneratedBackend.kt:698)
                                                                                                    	at anki.backend.GeneratedBackend.answerCard(GeneratedBackend.kt:703)
                                                                                                    	at com.ichi2.libanki.sched.Scheduler.answerCard(Scheduler.kt:140)
                                                                                                    	at com.ichi2.anki.Reviewer.answerCardInner$lambda$10(Reviewer.kt:1071)
                                                                                                    	at com.ichi2.anki.Reviewer.$r8$lambda$LbgNo9oDBDuCvfjZjbS__zeJtMc(Unknown Source:0)
                                                                                                    	at com.ichi2.anki.Reviewer$$ExternalSyntheticLambda2.invoke(D8$$SyntheticClass:0)
                                                                                                    	at com.ichi2.libanki.ChangeManagerKt.undoableOp$lambda$0(ChangeManager.kt:136)
                                                                                                    	at com.ichi2.libanki.ChangeManagerKt.$r8$lambda$nfOTnN_QmO6PfFJdkZgJou8q83U(Unknown Source:0)
                                                                                                    	at com.ichi2.libanki.ChangeManagerKt$$ExternalSyntheticLambda1.invoke(D8$$SyntheticClass:0)
                                                                                                    	at com.ichi2.anki.CollectionManager.withCol$lambda$1(CollectionManager.kt:114)
                                                                                                    	at com.ichi2.anki.CollectionManager.$r8$lambda$ffr4nUlMOyAvThaKA2WuJlnLaPU(Unknown Source:0)
                                                                                                    	at com.ichi2.anki.CollectionManager$$ExternalSyntheticLambda9.invoke(D8$$SyntheticClass:0)
                                                                                                    	at com.ichi2.anki.CollectionManager$withQueue$3.invokeSuspend(CollectionManager.kt:98)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
2024-09-23 21:51:56.044  9592-9592  CoroutineHelpersKt      com.ichi2.anki.debug                 E  	at com.ichi2.anki.CoroutineHelpersKt.launchCatchingTask(CoroutineHelpers.kt:230)
                                                                                                    	at com.ichi2.anki.CoroutineHelpersKt.launchCatchingTask$default(CoroutineHelpers.kt:226)
                                                                                                    	at com.ichi2.anki.AbstractFlashcardViewer.answerCard$lambda$16(AbstractFlashcardViewer.kt:890)
                                                                                                    	at com.ichi2.anki.AbstractFlashcardViewer.$r8$lambda$cqQ2mllVMPsv5J3_TtTFKxUMg9E(Unknown Source:0)
                                                                                                    	at com.ichi2.anki.AbstractFlashcardViewer$$ExternalSyntheticLambda8.invoke(D8$$SyntheticClass:0)
                                                                                                    	at com.ichi2.anki.utils.OnlyOnce.preventSimultaneousExecutions(OnlyOnce.kt:45)
                                                                                                    	at com.ichi2.anki.AbstractFlashcardViewer.answerCard(AbstractFlashcardViewer.kt:889)
                                                                                                    	at com.ichi2.anki.AbstractFlashcardViewer$SelectEaseHandler.onClick(AbstractFlashcardViewer.kt:439)
                                                                                                    	at com.ichi2.anki.reviewer.EaseButton.setListeners$lambda$0(EaseButton.kt:70)
                                                                                                    	at com.ichi2.anki.reviewer.EaseButton.$r8$lambda$uIozAmA4u9kBcKK6Ps0s37STnQo(Unknown Source:0)
                                                                                                    	at com.ichi2.anki.reviewer.EaseButton$$ExternalSyntheticLambda1.onClick(D8$$SyntheticClass:0)
                                                                                                    	at android.view.View.performClick(View.java:7506)
                                                                                                    	at android.view.View.performClickInternal(View.java:7483)
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                                                    	at android.view.View$PerformClick.run(View.java:29357)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7884)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
