### ISSUE TITLE
[2.19beta] ACRA stack traces are partially obfuscated

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#17156]
https://ankidroid.org/acra/app/1/bug/237667/report/f132b27e-1f7b-4aeb-a223-ca1a584583f0

```
java.lang.IllegalStateException: TabLayoutMediator attached before ViewPager2 has an adapter
	at B3.l.a(SourceFile:86)
	at com.ichi2.anki.CardTemplateEditor$a.onViewCreated(SourceFile:97)
	at androidx.fragment.app.Fragment.performViewCreated(SourceFile:15)
	at androidx.fragment.app.s0.f(SourceFile:293)
	at androidx.fragment.app.s0.k(SourceFile:175)
	at androidx.fragment.app.j0.O(SourceFile:58)
	at androidx.fragment.app.j0.u(SourceFile:34)
	at androidx.fragment.app.M.onStart(SourceFile:34)
	at k.j.onStart(SourceFile:1)
	at P3.z0.onStart(SourceFile:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1582)
	at android.app.Activity.performStart(Activity.java:9008)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4198)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

Likely cause:

* https://github.com/ankidroid/Anki-Android/pull/16635

@mikehardy @voczi FYI

**Comment by voczi** [comment]
I'm pretty sure you get a mapping file or something like that in the build output folder whenever building a release. That should make it possible to decode the stacktraces.
Maybe I should write some docs about how to go on about this?

**Comment by voczi** [comment]
Some script that integrates with ACRA to decode these automatically might be a better idea..

**Comment by mikehardy** [comment]
I suppose the publish script should upload the build symbols mapping file as an artifact on release
Alternatively, I do not believe class name obfuscation (or minimization) is that big of a size difference - and the Compare APK Size workflow can validate that assertion - it might just simplify our lives to keep class / method names if the cost isn't high

We have nothing to hide unlike more commercial software

**Comment by mikehardy** [comment]
Based on some discord discussion we're going to go for the solution where the build itself just doesn't obfuscate these things.

Plan:
- get local release build going so I can do a baseline ACRA post to see the obfuscation (in progress)
- tweak the minify to leave the symbol tables alone and post to ACRA so it is visible (next step)
- run Compare APK size tool on a PR with symbol tables intact to see what the increase in size is

**Comment by mikehardy** [comment]
Okay, here's the baseline crash before I try to change things, proving I have a local dev loop for this

Won't get back to it for a few hours but I'm setup now

https://ankidroid.org/acra/app/1/bug/237978/report/26c50d8f-6bc4-41e7-8635-290cc2f873e4

```
Version
2.19beta3
Date
moments ago
Installation
c6781c8c-b2ed-4197-8535-87ecc338e55a
c6781c8c-b2ed-4197-8535-87ecc338e55a
Email
Comment
test crash in release mode - obfuscation baseline test
Stacktrace (No mapping found)
java.lang.RuntimeException: This is a test crash
	at com.ichi2.anki.preferences.DevOptionsFragment.initSubscreen$lambda$1(SourceFile:20)
	at com.ichi2.anki.preferences.DevOptionsFragment.C(SourceFile:1)
	at p4.t.i(SourceFile:1)
	at androidx.preference.Preference.u(SourceFile:19)
	at androidx.preference.l.onClick(SourceFile:3)
	at android.view.View.performClick(View.java:8028)
	at android.view.View.performClickInternal(View.java:8005)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31229)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```

**Comment by david-allison** [comment]
> proguard mappings did upload:
> 
> [proguard-mappings.tar.gz](https://github.com/ankidroid/Anki-Android/releases/download/v2.19beta4/proguard-mappings.tar.gz)
> 
> After installing the arm64-v8a build (which is "full") I was able to use the `retrace` tool as `retrace <mapping file> <file with stack>` and using the stack above of our test crash, it worked!
> 
> ```
> 09-30 17:29:20.627 10524 10524 E ACRA    : java.lang.RuntimeException: This is a test crash
> 09-30 17:29:20.627 10524 10524 E ACRA    : 	at com.ichi2.anki.preferences.DevOptionsFragment.initSubscreen$lambda$2(DevOptionsFragment.kt:71)
> 09-30 17:29:20.627 10524 10524 E ACRA    : 	at androidx.preference.Preference.performClick(Preference.java:1200)
> 09-30 17:29:20.627 10524 10524 E ACRA    : 	at androidx.preference.Preference.performClick(Preference.java:1182)
> 09-30 17:29:20.627 10524 10524 E ACRA    : 	at androidx.preference.Preference$1.onClick(Preference.java:182)
> 09-30 17:29:20.627 10524 10524 E ACRA    : 	at android.view.View.performClick(View.java:8028)
> 09-30 17:29:20.627 10524 10524 E ACRA    : 	at android.view.View.performClickInternal(View.java:8005)
> 09-30 17:29:20.627 10524 10524 E ACRA    : 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source)
> 09-30 17:29:20.627 10524 10524 E ACRA    : 	at android.view.View$PerformClick.run(View.java:31229)
> 09-30 17:29:20.627 10524 10524 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:959)
> 09-30 17:29:20.627 10524 10524 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:100)
> 09-30 17:29:20.627 10524 10524 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:232)
> 09-30 17:29:20.627 10524 10524 E ACRA    : 	at android.os.Looper.loop(Looper.java:317)
> ```
> 
> That's the correct line number.
> 
> How bout that.

https://github.com/ankidroid/Anki-Android/pull/17163#issuecomment-2384298740
