### ISSUE TITLE
[2.19] - ACRA - `Unexpected action received: null`

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#17157]
https://ankidroid.org/acra/app/1/bug/237593/report/2e85799b-a55d-43b6-8bef-851e8c09acca

```
java.lang.Exception: Unexpected action received: null
	at com.ichi2.widget.cardanalysis.CardAnalysisWidget.onReceive(SourceFile:307)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4079)
	at android.app.ActivityThread.access$1600(ActivityThread.java:244)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1974)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7723)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
```

Cause: https://github.com/ankidroid/Anki-Android/blob/5bf4326bb0c05d500ab40cacef0d3fb7f7b86a10/AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidgetConfig.kt#L243

Also exists in the `CardAnalysisWidget`

**Comment by david-allison** [comment]
https://ankidroid.org/acra/app/1/bug/241966/report/427c43e5-5591-492f-8ba1-b929787f4395

2.19beta4

```
java.lang.Exception: Unexpected action received: null
	at com.ichi2.widget.cardanalysis.CardAnalysisWidget.onReceive(SourceFile:315)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4376)
	at android.app.ActivityThread.access$1600(ActivityThread.java:257)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2103)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7911)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
```
