### ISSUE TITLE
Unexpected action received: `com.ichi2.widget.deckpicker.DeckPickerWidget.com.ichi2.widget.ACTION_UPDATE_WIDGET`

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#17151]
https://ankidroid.org/acra/app/1/bug/237536/report/5b8e1e23-6fa9-4544-a695-8e5d728d555d

```
java.lang.Exception: Unexpected action received: com.ichi2.widget.deckpicker.DeckPickerWidget.com.ichi2.widget.ACTION_UPDATE_WIDGET
	at com.ichi2.widget.deckpicker.DeckPickerWidget.onReceive(SourceFile:293)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4085)
	at android.app.ActivityThread.access$1600(ActivityThread.java:244)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1974)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7720)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
```

**Comment by david-allison** [comment]
Also: `null`, `android.appwidget.action.APPWIDGET_UPDATE_OPTIONS`

* https://github.com/ankidroid/Anki-Android/issues/20849
