### ISSUE TITLE
[BUG]: `SingleFragmentActivity`: lateinit property fragment has not been initialized

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#17246]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

Got this randomly while toggling night mode.

I can't reproduce it consistently.

But I'm 100% that `fragment` shouldn't be lateinit in `SingleFragmentActivity`

### Expected behaviour

It crashed, but shouldn't

### Debug info

Running at 17a44bc042dbddca3a839c6dc99392a743500918

```
kotlin.UninitializedPropertyAccessException: lateinit property fragment has not been initialized
 at com.ichi2.anki.SingleFragmentActivity.getFragment(SingleFragmentActivity.kt:44)
 at com.ichi2.anki.SingleFragmentActivity.getShortcuts(SingleFragmentActivity.kt:96)
 at com.ichi2.anki.AnkiActivity.onKeyUp(AnkiActivity.kt:654)
 at android.view.KeyEvent.dispatch(KeyEvent.java:2952)
 at android.app.Activity.dispatchKeyEvent(Activity.java:4340)
 at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.kt:103)
 at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
 at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.kt:117)
 at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
 at com.ichi2.anki.SingleFragmentActivity.dispatchKeyEvent(SingleFragmentActivity.kt:78)
 at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
 at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3397)
 at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:392)
 at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6945)
 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6811)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6229)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252)
 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6417)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6260)
 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6474)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6233)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6260)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6233)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252)
 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6450)
 at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6661)
 at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:4278)
 at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:3715)
 at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:3706)
 at android.view.inputmethod.InputMethodManager.-$$Nest$mfinishedInputEvent(Unknown Source:0)
 at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:4255)
 at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
 at android.os.MessageQueue.nativePollOnce(Native Method)
 at android.os.MessageQueue.next(MessageQueue.java:335)
 at android.os.Looper.loopOnce(Looper.java:162)
 at android.os.Looper.loop(Looper.java:294)
 at android.app.ActivityThread.main(ActivityThread.java:8177)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
lateinit, just as worrisome as !! 🧐 😆

**Comment by david-allison** [comment]
We should have more logs to confirm the cause of this issue.

I'm not sure about making the variable nullable. Could it be that `onKeyUp` is being called before `onCreate` has completed? I wouldn't have expected `fragment` to be uninitialized after `onCreate`

My expectation of `lateinit` is that it's designed for variables set in `onCreate`. Callers which may execute before `onCreate` should take care to handle these unusual cases

Crashes:

https://github.com/ankidroid/Anki-Android/blob/75d9e56f8d593f0d4e36e02ad64fe477f43f7d2f/AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt#L95-L96

**fragment** is set in `onCreate`

https://github.com/ankidroid/Anki-Android/blob/75d9e56f8d593f0d4e36e02ad64fe477f43f7d2f/AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt#L46-L71

Cause of the crash (AnkiActivity): access to `shortcuts`

https://github.com/ankidroid/Anki-Android/blob/75d9e56f8d593f0d4e36e02ad64fe477f43f7d2f/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt#L653-L657

**Comment by lukstbit** [comment]
This should be easy to fix by removing the fragment lateinit property and having the code go through the null path when the fragment is not available. To be honest I don't see why that property was made lateinit in the first place.

I don't think it's worth spending more time now on this issue especially that it seems it's difficult to reproduce.

**Comment by david-allison** [comment]
> I don't think it's worth spending more time now on this issue especially that it seems it's difficult to reproduce.

Bugs which we don't understand concern me

Since this blocks 2.19, let's go with a pragmatic fix

But it should have a TODO to note why the variable is nullable, and that we should figure out the issue and document it at some point in the future

**Comment by david-allison** [comment]
**Reproduction Steps**

On a Tablet (API 34):

* Open the Note Editor
* Toggle Light/Dark Mode
* Type in a field


```
AnkiDroid...onCreate  I  DeckPicker::onPause
FragmentL...leLogger  I  DeckPicker::StudyOptionsFragment::onPause
Themes                I  Setting theme to LIGHT
AnkiDroid...onCreate  I  SingleFragmentActivity::onCreate
ScopedStorageService  I  isLegacyStorage(): current dir: /storage/emulated/0/AnkiDroid
                         scoped external dirs: /storage/emulated/0/Android/data/com.ichi2.anki.debug/files
                         scoped internal dir: /data/user/0/com.ichi2.anki.debug/files
                      I  isLegacyStorage(): true
AnkiDroid...onCreate  I  SingleFragmentActivity::onStart
FragmentL...leLogger  I  SingleFragmentActivity::NoteEditor::onAttach
                      I  SingleFragmentActivity::NoteEditor::onCreate
AnkiFragment          D  AnkiFragment.startLoadingCollection()
                      D  Synchronously calling onCollectionLoaded
NoteEditor            D  NoteEditor() onCollectionLoaded: caller: 3
                      D  updateCards()
                      D  updateCards() template count is 1
                      I  onCollectionLoaded() Edit note activity successfully started in add card mode with node id 0
FragmentL...leLogger  I  SingleFragmentActivity::NoteEditor::onViewCreated
                      I  SingleFragmentActivity::NoteEditor::onStart
AnkiDroid...onCreate  I  SingleFragmentActivity::onResume
UsageAnalytics        D  sendAnalyticsScreenView(): SingleFragmentActivity
                      D  getOptIn() status: false
FragmentL...leLogger  I  SingleFragmentActivity::NoteEditor::onResume
AssistStructure       I  Flattened final assist data: 5520 bytes, containing 1 windows, 38 views
InsetsController      D  show(ime(), fromIme=true)
ImeTracker            I  com.ichi2.anki.debug:21a6d20b: onShown
AnkiDroid...onCreate  I  DeckPicker::onStop
FragmentL...leLogger  I  DeckPicker::StudyOptionsFragment::onStop
WidgetStatus          D  WidgetStatus.update(): already running or not enabled
AnkiDroid...onCreate  I  DeckPicker::onSaveInstanceState
FragmentL...leLogger  I  DeckPicker::StudyOptionsFragment::onSaveInstanceState
AnkiDroid...onCreate  I  SingleFragmentActivity::onPause
FragmentL...leLogger  I  SingleFragmentActivity::NoteEditor::onPause
AnkiDroid...onCreate  I  SingleFragmentActivity::onStop
WidgetStatus          D  WidgetStatus.update(): already running or not enabled
FragmentL...leLogger  I  SingleFragmentActivity::NoteEditor::onStop
AnkiDroid...onCreate  I  SingleFragmentActivity::onSaveInstanceState
NoteEditor            I  Saving instance
FragmentL...leLogger  I  SingleFragmentActivity::NoteEditor::onSaveInstanceState
AnkiDroid...onCreate  I  SingleFragmentActivity::onDestroy
FragmentL...leLogger  I  SingleFragmentActivity::NoteEditor::onViewDestroyed
                      I  SingleFragmentActivity::NoteEditor::onDestroy
                      I  SingleFragmentActivity::NoteEditor::onDetach
Themes                I  Setting theme to BLACK
AnkiDroid...onCreate  I  SingleFragmentActivity::onCreate
FragmentL...leLogger  I  SingleFragmentActivity::NoteEditor::onAttach
                      I  SingleFragmentActivity::NoteEditor::onCreate
ScopedStorageService  I  isLegacyStorage(): current dir: /storage/emulated/0/AnkiDroid
                         scoped external dirs: /storage/emulated/0/Android/data/com.ichi2.anki.debug/files
                         scoped internal dir: /data/user/0/com.ichi2.anki.debug/files
                      I  isLegacyStorage(): true
AnkiDroid...onCreate  I  SingleFragmentActivity::onStart
AnkiFragment          D  AnkiFragment.startLoadingCollection()
                      D  Synchronously calling onCollectionLoaded
NoteEditor            D  NoteEditor() onCollectionLoaded: caller: 3
                      D  updateCards()
                      D  updateCards() template count is 1
                      I  onCollectionLoaded() Edit note activity successfully started in add card mode with node id 0
FragmentL...leLogger  I  SingleFragmentActivity::NoteEditor::onViewCreated
                      I  SingleFragmentActivity::NoteEditor::onStart
AnkiDroid...onCreate  I  SingleFragmentActivity::onResume
UsageAnalytics        D  sendAnalyticsScreenView(): SingleFragmentActivity
                      D  getOptIn() status: false
FragmentL...leLogger  I  SingleFragmentActivity::NoteEditor::onResume
RemoteInp...tionImpl  W  getSurroundingText on inactive InputConnection
                      W  getSurroundingText on inactive InputConnection
AssistStructure       I  Flattened final assist data: 5520 bytes, containing 1 windows, 38 views
RemoteInp...tionImpl  W  getSurroundingText on inactive InputConnection
chi2.anki.debug       W  Cleared Reference was only reachable from finalizer (only reported once)
ImeBackDispatcher     E  Ime callback not found. Ignoring unregisterReceivedCallback. callbackId: 99739620
InsetsController      D  show(ime(), fromIme=true)
                      D  show(ime(), fromIme=true)
ImeTracker            I  com.ichi2.anki.debug:8302e1c1: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
                      I  com.ichi2.anki.debug:f52dc817: onShown
InputEventSender      E  Exception dispatching finished signal for seq=13
MessageQueue-JNI      E  Exception in MessageQueue callback: handleReceiveCallback
                      E  kotlin.UninitializedPropertyAccessException: lateinit property fragment has not been initialized
                         	at com.ichi2.anki.SingleFragmentActivity.getFragment(SingleFragmentActivity.kt:44)
                         	at com.ichi2.anki.SingleFragmentActivity.getShortcuts(SingleFragmentActivity.kt:96)
                         	at com.ichi2.anki.AnkiActivity.onKeyUp(AnkiActivity.kt:654)
                         	at android.view.KeyEvent.dispatch(KeyEvent.java:2952)
                         	at android.app.Activity.dispatchKeyEvent(Activity.java:4340)
                         	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.kt:103)
                         	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
                         	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.kt:117)
                         	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
                         	at com.ichi2.anki.SingleFragmentActivity.dispatchKeyEvent(SingleFragmentActivity.kt:76)
                         	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
                         	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3397)
                         	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:392)
                         	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6945)
                         	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6811)
                         	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6229)
                         	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286)
                         	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252)
                         	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6417)
                         	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6260)
                         	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6474)
                         	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6233)
                         	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286)
                         	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252)
                         	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6260)
                         	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6233)
                         	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286)
                         	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252)
                         	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6450)
                         	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6661)
                         	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:4278)
                         	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:3715)
                         	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:3706)
                         	at android.view.inputmethod.InputMethodManager.-$$Nest$mfinishedInputEvent(Unknown Source:0)
                         	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:4255)
                         	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
                         	at android.os.MessageQueue.nativePollOnce(Native Method)
                         	at android.os.MessageQueue.next(MessageQueue.java:335)
                         	at android.os.Looper.loopOnce(Looper.java:162)
                         	at android.os.Looper.loop(Looper.java:294)
                         	at android.app.ActivityThread.main(ActivityThread.java:8177)
                         	at java.lang.reflect.Method.invoke(Native Method)
                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
AndroidRuntime        D  Shutting down VM
                      E  FATAL EXCEPTION: main
                         Process: com.ichi2.anki.debug, PID: 17379
                         kotlin.UninitializedPropertyAccessException: lateinit property fragment has not been initialized
                         	at com.ichi2.anki.SingleFragmentActivity.getFragment(SingleFragmentActivity.kt:44)
                         	at com.ichi2.anki.SingleFragmentActivity.getShortcuts(SingleFragmentActivity.kt:96)
                         	at com.ichi2.anki.AnkiActivity.onKeyUp(AnkiActivity.kt:654)
                         	at android.view.KeyEvent.dispatch(KeyEvent.java:2952)
                         	at android.app.Activity.dispatchKeyEvent(Activity.java:4340)
                         	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.kt:103)
                         	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
                         	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.kt:117)
                         	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
                         	at com.ichi2.anki.SingleFragmentActivity.dispatchKeyEvent(SingleFragmentActivity.kt:76)
                         	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
                         	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3397)
                         	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:392)
                         	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6945)
                         	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6811)
                         	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6229)
                         	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286)
                         	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252)
                         	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6417)
                         	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6260)
                         	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6474)
                         	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6233)
                         	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286)
                         	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252)
                         	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6260)
                         	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6233)
                         	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286)
                         	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252)
                         	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6450)
                         	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6661)
                         	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:4278)
                         	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:3715)
                         	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:3706)
                         	at android.view.inputmethod.InputMethodManager.-$$Nest$mfinishedInputEvent(Unknown Source:0)
                         	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:4255)
                         	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
                         	at android.os.MessageQueue.nativePollOnce(Native Method)
                         	at android.os.MessageQueue.next(MessageQueue.java:335)
                         	at android.os.Looper.loopOnce(Looper.java:162)
                         	at android.os.Looper.loop(Looper.java:294)
                         	at android.app.ActivityThread.main(ActivityThread.java:8177)
                         	at java.lang.reflect.Method.invoke(Native Method)
                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
UsageAnalytics        D  sendAnalyticsException() description/fatal: kotlin.UninitializedPropertyAccessException: lateinit property fragment has not been initialized/true
ACRA                  E  ACRA caught a UninitializedPropertyAccessException for com.ichi2.anki.debug
                         kotlin.UninitializedPropertyAccessException: lateinit property fragment has not been initialized
                         	at com.ichi2.anki.SingleFragmentActivity.getFragment(SingleFragmentActivity.kt:44)
                         	at com.ichi2.anki.SingleFragmentActivity.getShortcuts(SingleFragmentActivity.kt:96)
                         	at com.ichi2.anki.AnkiActivity.onKeyUp(AnkiActivity.kt:654)
                         	at android.view.KeyEvent.dispatch(KeyEvent.java:2952)
                         	at android.app.Activity.dispatchKeyEvent(Activity.java:4340)
                         	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.kt:103)
                         	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
                         	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.kt:117)
                         	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
                         	at com.ichi2.anki.SingleFragmentActivity.dispatchKeyEvent(SingleFragmentActivity.kt:76)
                         	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
                         	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3397)
                         	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:392)
                         	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6945)
                         	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6811)
                         	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6229)
                         	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286)
                         	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252)
                         	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6417)
                         	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6260)
                         	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6474)
                         	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6233)
                         	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286)
                         	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252)
                         	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6260)
                         	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6233)
                         	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286)
                         	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252)
                         	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6450)
                         	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6661)
                         	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:4278)
                         	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:3715)
                         	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:3706)
                         	at android.view.inputmethod.InputMethodManager.-$$Nest$mfinishedInputEvent(Unknown Source:0)
                         	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:4255)
                         	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
                         	at android.os.MessageQueue.nativePollOnce(Native Method)
                         	at android.os.MessageQueue.next(MessageQueue.java:335)
                         	at android.os.Looper.loopOnce(Looper.java:162)
                         	at android.os.Looper.loop(Looper.java:294)
                         	at android.app.ActivityThread.main(ActivityThread.java:8177)
                         	at java.lang.reflect.Method.invoke(Native Method)
                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
AnkiActivity          I  finishWithAnimation DEFAULT
                      I  finishWithAnimation DEFAULT
Compatibi...Reporter  D  Compat change id reported: 147798919; UID 10195; state: ENABLED
ThemeUtils            E  View class com.ichi2.ui.FixedTextView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
                      E  View class com.ichi2.ui.FixedTextView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
Process               I  Sending signal. PID: 17379 SIG: 9
---------------------------- PROCESS ENDED (17379) for package com.ichi2.anki.debug ----------------------------


```
