### ISSUE TITLE
[BUG]: beta4, beta5 doesn't start anymore on Android 8.0.0 (SDK 26)

### ISSUE THREAD

**Issue by xiety** [ankidroid/Anki-Android#17256]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

The application doesn't start when you click on it

Latest working version is `2.19beta3`, **so I copied debug info from it**

Exception from Logcat of `beta5`:

```
FATAL EXCEPTION: main
Process: com.ichi2.anki, PID: 28636
java.lang.NoSuchMethodError: No direct method <init>(II)V in class Lorg/apache/http/protocol/HttpRequestExecutor; or its super classes (declaration of 'org.apache.http.protocol.HttpRequestExecutor' appears in /system/framework/org.apache.http.legacy.boot.jar)
    at kotlinx.coroutines.scheduling.TasksKt.<clinit>(SourceFile:95)
    at kotlinx.coroutines.scheduling.DefaultScheduler.<clinit>(SourceFile:3)
    at kotlinx.coroutines.Dispatchers.<clinit>(SourceFile:1)
    at com.ichi2.anki.AnkiDroidApp.<clinit>(SourceFile:5)
    at java.lang.Class.newInstance(Native Method)
    at android.app.Instrumentation.newApplication(Instrumentation.java:1104)
    at android.app.Instrumentation.newApplication(Instrumentation.java:1089)
    at android.app.LoadedApk.makeApplication(LoadedApk.java:1053)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6590)
    at android.app.ActivityThread.-wrap2(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
    at android.os.Handler.dispatchMessage(Handler.java:108)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7529)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

### Expected behaviour

The application starts when you click on it

### Debug info

AnkiDroid Version = 2.19beta3 (408718b5bd3e314ea9e70854abd326162596eb5d)

Backend Version = 0.1.40-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 8.0.0 (SDK 26)

ProductFlavor = full

Manufacturer = HUAWEI

Model = BAH2-L09

Hardware = hi6250

Webview User Agent = Mozilla/5.0 (Linux; Android 8.0.0; BAH2-L09 Build/HUAWEIBAH2-L09; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/129.0.6668.100 Safari/537.36

ACRA UUID = 1157195a-da38-4c18-b5d1-4abaef3721c1

FSRS Enabled = true

Crash Reports Enabled = true

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Thanks for the report - and for being a beta tester - sorry this isn't working for you!
We'll figure out what changed

**Comment by mikehardy** [comment]
@xiety is this stack trace from beta5? or is it from beta4? Thanks

**Comment by mikehardy** [comment]
For anyone looking to reproduce this, it should be possible to decode the stack using the appropriate proguard mappings (these are beta5): https://github.com/ankidroid/Anki-Android/releases/download/v2.19beta5/proguard-mappings.tar.gz

Then, with the stack trace in a text file locally and the mappings downloaded locally, you can use the `retrace` tool from the Android SDK command line tools to find the actual line numbers: 

https://developer.android.com/tools/retrace

**Comment by xiety** [comment]
@mikehardy stack trace from `beta5`

**Comment by david-allison** [comment]
Changes: https://github.com/ankidroid/Anki-Android/compare/v2.19beta3...v2.19beta4

**Comment by mikehardy** [comment]
For anyone with a minute, here's some progress to the next step, it's the decoded stack using the full mappings for beta5, which should be what applies for this stack

```

FATAL EXCEPTION: main
Process: com.ichi2.anki, PID: 28636
java.lang.NoSuchMethodError: No direct method <init>(II)V in class Lorg/apache/http/protocol/HttpRequestExecutor; or its super classes (declaration of 'org.apache.http.protocol.HttpRequestExecutor' appears in /system/framework/org.apache.http.legacy.boot.jar)
    at kotlinx.coroutines.scheduling.TasksKt.<clinit>(Tasks.kt:73)
    at kotlinx.coroutines.scheduling.DefaultScheduler.<init>(Dispatcher.kt:10)
    at kotlinx.coroutines.scheduling.DefaultScheduler.<clinit>(Dispatcher.kt)
    at kotlinx.coroutines.Dispatchers.<clinit>(Dispatchers.kt:17)
    at com.ichi2.anki.AnkiDroidApp.<clinit>(AnkiDroidApp.kt:323)
    at java.lang.Class.newInstance(Native Method)
    at android.app.Instrumentation.newApplication(Instrumentation.java:1104)
    at android.app.Instrumentation.newApplication(Instrumentation.java:1089)
    at android.app.LoadedApk.makeApplication(LoadedApk.java:1053)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6590)
    at android.app.ActivityThread.-wrap2(Unknown Source)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
    at android.os.Handler.dispatchMessage(Handler.java:108)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7529)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

```

**Comment by mikehardy** [comment]
@xiety + @fabiensdk - this may or may not work, but could you try the "nominify" version of 2.19beta6?

https://github.com/ankidroid/Anki-Android/releases/download/v2.19beta6/AnkiDroid-2.19beta6-full-universal-nominify.apk

I understand you two were both on "full" build flavors before so this should be pretty similar. It is *not* a parallel build so I don't know how easy this will be (or not be) for you to test, but hopefully you can test it and we learn something

Thanks in advance for any help, cheers

**Comment by david-allison** [comment]
@Fabiensk FYI; you should have been pinged above

**Comment by xiety** [comment]
@mikehardy Yes, `nominify` version starts normally on my device.

(and `AnkiDroid-2.19beta6-full-universal.apk` still won't start)

**Comment by mikehardy** [comment]
Okay - that isolates things down to a single one line change I believe, that test result helps a lot, thank you very much
I'm very confused *how* that line could break things, but that's on me to figure out

**Comment by Fabiensk** [comment]
@mikehardy 
* `AnkiDroid-2.19beta6-full-universal-nominify.apk` does start (I had to uninstall my current version that I got from f-droid, otherwise the installation fails)
* `AnkiDroid-2.19beta6.parallel.A.apk` still fails to start
