### ISSUE TITLE
`MultimediaActivity`: `ActivityNotFoundException`: No Activity found to handle Intent { act=android.intent.action.PICK dat=content://media/... }

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#17376]
https://ankidroid.org/acra/app/1/bug/254088/report/18ecf1e3-a890-4d69-8a7f-7d856f3261dc

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.PICK dat=content://media/... }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2430)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:2005)
	at android.app.Activity.startActivityForResult(Activity.java:5874)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.kt:704)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:244)
	at androidx.activity.ComponentActivity$activityResultRegistry$1.onLaunch(ComponentActivity.kt:225)
	at androidx.activity.result.ActivityResultRegistry$register$2.launch(ActivityResultRegistry.kt:137)
	at androidx.fragment.app.Fragment$10.launch(Fragment.java:3637)
	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.kt:37)
	at com.ichi2.anki.multimedia.MultimediaImageFragment.openGallery(MultimediaImageFragment.kt:328)
	at com.ichi2.anki.multimedia.MultimediaImageFragment.handleSelectedImageOptions(MultimediaImageFragment.kt:288)
	at com.ichi2.anki.multimedia.MultimediaImageFragment.handleImageUri(MultimediaImageFragment.kt:280)
	at com.ichi2.anki.multimedia.MultimediaImageFragment.onViewCreated(MultimediaImageFragment.kt:271)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3152)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:608)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2211)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2106)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2049)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3324)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3234)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at com.ichi2.anki.AnkiActivity.onStart(AnkiActivity.kt:128)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1701)
	at android.app.Activity.performStart(Activity.java:9045)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4073)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:270)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:250)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:222)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:107)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```

```
--------- beginning of main
11-07 11:50:17.407 I/AnkiDroid( 8483): Reviewer::onStart
11-07 11:50:17.423 I/AnkiDroid( 8483): Reviewer::onResume
11-07 11:50:21.645 I/AnkiDroid( 8483): Reviewer:: Edit note button pressed
11-07 11:50:21.692 I/AnkiDroid( 8483): Reviewer::onPause
11-07 11:50:21.692 I/AnkiDroid( 8483): stop: automatically show answer
11-07 11:50:21.692 I/AnkiDroid( 8483): stop: automatically show question
11-07 11:50:21.709 I/AnkiDroid( 8483): Setting theme to BLACK
11-07 11:50:21.711 I/AnkiDroid( 8483): SingleFragmentActivity::onCreate
11-07 11:50:21.713 I/AnkiDroid( 8483): isLegacyStorage(): current dir: /storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid
11-07 11:50:21.713 I/AnkiDroid( 8483): scoped external dirs: /storage/emulated/0/Android/data/com.ichi2.anki/files
11-07 11:50:21.713 I/AnkiDroid( 8483): scoped internal dir: /data/user/0/com.ichi2.anki/files
11-07 11:50:21.713 I/AnkiDroid( 8483): isLegacyStorage(): false
11-07 11:50:21.716 I/AnkiDroid( 8483): SingleFragmentActivity::onStart
11-07 11:50:21.717 I/AnkiDroid( 8483): SingleFragmentActivity::a7::onAttach
11-07 11:50:21.717 I/AnkiDroid( 8483): SingleFragmentActivity::a7::onCreate
11-07 11:50:21.744 I/AnkiDroid( 8483): onCollectionLoaded() Edit note activity successfully started with card id 1730960865673
11-07 11:50:21.747 I/AnkiDroid( 8483): SingleFragmentActivity::a7::onViewCreated
11-07 11:50:21.747 I/AnkiDroid( 8483): SingleFragmentActivity::a7::onStart
11-07 11:50:21.750 I/AnkiDroid( 8483): SingleFragmentActivity::onResume
11-07 11:50:21.750 I/AnkiDroid( 8483): SingleFragmentActivity::a7::onResume
11-07 11:50:22.297 I/AnkiDroid( 8483): Reviewer::onStop
11-07 11:50:22.299 I/AnkiDroid( 8483): Reviewer::onSaveInstanceState
11-07 11:50:24.482 I/AnkiDroid( 8483): SingleFragmentActivity::i::onAttach
11-07 11:50:24.483 I/AnkiDroid( 8483): SingleFragmentActivity::i::onCreate
11-07 11:50:24.503 I/AnkiDroid( 8483): SingleFragmentActivity::i::onViewCreated
11-07 11:50:24.516 I/AnkiDroid( 8483): SingleFragmentActivity::i::onStart
11-07 11:50:24.516 I/AnkiDroid( 8483): SingleFragmentActivity::i::onResume
11-07 11:50:26.580 I/AnkiDroid( 8483): Selected Image option
11-07 11:50:26.607 I/AnkiDroid( 8483): SingleFragmentActivity::onPause
11-07 11:50:26.607 I/AnkiDroid( 8483): SingleFragmentActivity::a7::onPause
11-07 11:50:26.607 I/AnkiDroid( 8483): SingleFragmentActivity::i::onPause
11-07 11:50:26.607 I/AnkiDroid( 8483): SingleFragmentActivity::i::onStop
11-07 11:50:26.607 I/AnkiDroid( 8483): SingleFragmentActivity::i::onViewDestroyed
11-07 11:50:26.607 I/AnkiDroid( 8483): SingleFragmentActivity::i::onDestroy
11-07 11:50:26.607 I/AnkiDroid( 8483): SingleFragmentActivity::i::onDetach
11-07 11:50:26.615 I/AnkiDroid( 8483): Setting theme to BLACK
11-07 11:50:26.616 I/AnkiDroid( 8483): MultimediaActivity::onCreate
11-07 11:50:26.621 I/AnkiDroid( 8483): MultimediaActivity::onStart
11-07 11:50:26.621 I/AnkiDroid( 8483): MultimediaActivity::MultimediaImageFragment::onAttach
11-07 11:50:26.623 I/AnkiDroid( 8483): MultimediaActivity::MultimediaImageFragment::onCreate
```

**Comment by david-allison** [comment]
@criticalAY FYI

**Comment by criticalAY** [comment]
Will get to it
