### ISSUE TITLE
[17 Parameters Bug] AbstractFlashcardViewer$LinkDetectingGestureDetector.executeTouchCommand: `NullPointerException`

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#17377]
https://ankidroid.org/acra/app/1/bug/254083/report/aece7bcf-982e-4b52-993a-f733b83d88fb

```
java.lang.NullPointerException
	at com.ichi2.anki.AbstractFlashcardViewer$LinkDetectingGestureDetector.executeTouchCommand$lambda$1(AbstractFlashcardViewer.kt:2153)
	at com.ichi2.anki.AbstractFlashcardViewer.processCardAction$lambda$7(AbstractFlashcardViewer.kt:475)
	at com.ichi2.anki.AbstractFlashcardViewer.processCardFunction(AbstractFlashcardViewer.kt:485)
	at com.ichi2.anki.AbstractFlashcardViewer.processCardAction(AbstractFlashcardViewer.kt:474)
	at com.ichi2.anki.AbstractFlashcardViewer$LinkDetectingGestureDetector.executeTouchCommand(AbstractFlashcardViewer.kt:2152)
	at com.ichi2.anki.AbstractFlashcardViewer$MyGestureDetector.onSingleTapConfirmed(AbstractFlashcardViewer.kt:2044)
	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:379)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8934)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by david-allison** [comment]
The user is affected by the '17 parameters' issue from Anki Beta. This should not be seen in a production release
