### ISSUE TITLE
`NoteEditor.getCurrentMultimediaEditableNote`: NullPointerException

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#17380]
https://ankidroid.org/acra/app/1/bug/253893/report/dc130d1c-77b9-464d-961f-99e3f1e75c90

```
java.lang.NullPointerException
	at com.ichi2.anki.NoteEditor.getCurrentMultimediaEditableNote(NoteEditor.kt:1583)
	at com.ichi2.anki.NoteEditor.access$getCurrentMultimediaEditableNote(NoteEditor.kt:198)
	at com.ichi2.anki.NoteEditor$addMediaFileToField$1.invokeSuspend(NoteEditor.kt:1870)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:363)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:21)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:88)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
	at kotlinx.coroutines.BuildersKt.launch(Builders.kt:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
	at kotlinx.coroutines.BuildersKt.launch$default(Builders.kt:1)
	at com.ichi2.anki.NoteEditor.addMediaFileToField(NoteEditor.kt:1869)
	at com.ichi2.anki.NoteEditor.handleMultimediaResult(NoteEditor.kt:1856)
	at com.ichi2.anki.NoteEditor.multimediaFragmentLauncher$lambda$1(NoteEditor.kt:287)
	at com.ichi2.anki.NoteEditor$NoteEditorActivityResultCallback.onActivityResult(NoteEditor.java:384)
	at com.ichi2.anki.NoteEditor$NoteEditorActivityResultCallback.onActivityResult(NoteEditor.java:378)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.kt:371)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.kt:331)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.kt:786)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:151)
	at android.app.Activity.dispatchActivityResult(Activity.java:7598)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4454)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3855)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3898)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [p0{Cancelling}@6eb7632, Dispatchers.Main.immediate]

```

**Comment by david-allison** [comment]
@criticalAY FYI
