### ISSUE TITLE
Remove ACRA Error: "Your collection needs to be upgraded to the v3 scheduler"

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#17385]
This doesn't need to be logged

https://ankidroid.org/acra/app/1/bug/253611/report/bddcf358-9c29-4931-b2db-c071a00d4da6

```
net.ankiweb.rsdroid.BackendException: Your collection needs to be upgraded to the v3 scheduler.
Please select Learn More before proceeding.
	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:127)
	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:281)
	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
	at net.ankiweb.rsdroid.Backend.runMethodRaw$lambda$1(Backend.kt:118)
	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:131)
	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:117)
	at anki.backend.GeneratedBackend.getPreferencesRaw(GeneratedBackend.kt:645)
	at anki.backend.GeneratedBackend.getPreferences(GeneratedBackend.kt:650)
	at com.ichi2.libanki.Collection.getPreferences(Collection.kt:760)
	at com.ichi2.anki.preferences.Preferences$Companion.getDayOffset$lambda$4(Preferences.kt:248)
	at com.ichi2.anki.CollectionManager.withCol$lambda$1(CollectionManager.kt:119)
	at com.ichi2.anki.CollectionManager$withQueue$3.invokeSuspend(CollectionManager.kt:103)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
```

**Comment by mikehardy** [comment]
If the strategy used in #17470 is valid (waiting on review there) then something similar could be done here I believe
