### ISSUE TITLE
MediaRegistration: File is invalid

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#17388]
https://ankidroid.org/acra/app/1/bug/253470/report/6ce47815-c82e-48f5-90c3-c6f84d992e25

* #8880

```
com.ichi2.anki.exception.UserSubmittedException: File is invalid issue:8880
	at com.ichi2.anki.exception.ManuallyReportedException.<init>(ManuallyReportedException.java:22)
	at com.ichi2.anki.CrashReportService.sendExceptionReport(CrashReportService.java:261)
	at com.ichi2.anki.MediaRegistration.onPaste(MediaRegistration.java:176)
	at com.ichi2.anki.NoteEditor.onPaste(NoteEditor.kt:1893)
	at com.ichi2.anki.NoteEditor.populateEditFields$lambda$53(NoteEditor.kt:1634)
	at com.ichi2.anki.FieldEditText.onPaste(FieldEditText.kt:174)
	at com.ichi2.anki.FieldEditText.onTextContextMenuItem(FieldEditText.kt:149)
	at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:4713)
	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2654)
	at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:98)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:787)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:151)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:934)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:924)
	at com.android.internal.view.FloatingActionMode.lambda$setFloatingToolbar$0$FloatingActionMode(FloatingActionMode.java:128)
	at com.android.internal.view.-$$Lambda$FloatingActionMode$LU5MpPuKYDtwlFAuYhXYfzgLNLE.onMenuItemClick(Unknown Source:2)
	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$2.onClick(FloatingToolbar.java:477)
	at android.view.View.performClick(View.java:7225)
	at android.view.View.performClickInternal(View.java:7202)
	at android.view.View.access$3500(View.java:805)
	at android.view.View$PerformClick.run(View.java:27682)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7438)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:989)
```

**Comment by david-allison** [comment]
@criticalAY May be something you know about
