### ISSUE TITLE
ManageSpaceActivity: NoSuchMethodException: getPackageSizeInfo

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#17387]
https://ankidroid.org/acra/app/1/bug/253484/report/1766425b-f629-44a7-83cd-c9928a3add89

```
java.lang.NoSuchMethodException: getPackageSizeInfo [class java.lang.String, interface b.a]
	at java.lang.Class.getMethod(Class.java:1981)
	at java.lang.Class.getMethod(Class.java:1637)
	at com.ichi2.anki.ui.windows.managespace.FileUtilsKt.getUserDataAndCacheSizeUsingGetPackageSizeInfo(FileUtils.kt:115)
	at com.ichi2.anki.ui.windows.managespace.FileUtilsKt.getUserDataAndCacheSize(FileUtils.kt:46)
	at com.ichi2.anki.ui.windows.managespace.ManageSpaceViewModel$launchCalculationOfSizeOfEverything$1$1.invokeSuspend(ManageSpaceFragment.kt:155)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [p0{Cancelling}@219e5c1, Dispatchers.Main.immediate]
```

**Comment by david-allison** [comment]
Samsung Galaxy S20 Ultra 5G on SDK 25 [???]

**Comment by david-allison** [comment]
@Favourjhay01 (with apologies for the unsolicited ping)

You posted about this device on https://redirect.github.com/TGX-Android/Telegram-X/issues/706 , could you spare a second to confirm what phone you were using
