### ISSUE TITLE
Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.CardBrowser}: com.ichi2.anki.exception.UserSubmittedException: Unable to instantiate fragment X3.h: could not find Fragment constructor

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#17381]
https://ankidroid.org/acra/app/1/bug/253877/report/5a4b008d-427b-4876-a085-0095795f52b8

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.CardBrowser}: com.ichi2.anki.exception.UserSubmittedException: Unable to instantiate fragment X3.h: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4014)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4167)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2628)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
Caused by: com.ichi2.anki.exception.UserSubmittedException: Unable to instantiate fragment X3.h: could not find Fragment constructor
	at androidx.fragment.app.Fragment$InstantiationException.<init>(Fragment.java:577)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:692)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:663)
	at com.ichi2.utils.ExtendedFragmentFactory.instantiate(ExtendedFragmentFactory.kt:50)
	at com.ichi2.anki.dialogs.tags.TagsDialogFactory.instantiate(TagsDialogFactory.kt:27)
	at com.ichi2.utils.ExtendedFragmentFactory.instantiate(ExtendedFragmentFactory.kt:50)
	at com.ichi2.anki.export.ExportDialogsFactory.instantiate(ExportDialogsFactory.java:32)
	at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:87)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:92)
	at androidx.fragment.app.FragmentManager.restoreSaveStateInternal(FragmentManager.java:2846)
	at androidx.fragment.app.FragmentManager.attachController(FragmentManager.java:3005)
	at androidx.fragment.app.FragmentController.attachHost(FragmentController.java:117)
	at androidx.fragment.app.FragmentActivity.lambda$init$3(FragmentActivity.java:139)
	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.kt:84)
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.kt:331)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:216)
	at com.ichi2.anki.AnkiActivity.onCreate(AnkiActivity.kt:114)
	at com.ichi2.anki.CardBrowser.onCreate(CardBrowser.kt:367)
	at android.app.Activity.performCreate(Activity.java:8886)
	at android.app.Activity.performCreate(Activity.java:8851)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1467)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3996)
	... 12 more
Caused by: java.lang.NoSuchMethodException: X3.h.<init> []
	at java.lang.Class.getConstructor0(Class.java:3395)
	at java.lang.Class.getConstructor(Class.java:2487)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:677)
	... 29 more
```

**Comment by david-allison** [comment]
@voczi FYI - could be proguard related

**Comment by mikehardy** [comment]
`X3.h` is BrowserOptionsDialog

```
mike@isabela:~/Downloads % cat "/Users/${USER}/Downloads/AnkiDroid_current_proguard/build/outputs/mapping/playRelease/mapping.txt" |grep 'X3.h'
com.ichi2.anki.dialogs.BrowserOptionsDialog -> X3.h:
      # {"id":"com.android.tools.r8.residualsignature","signature":"LX3/h;"}
      # {"id":"com.android.tools.r8.residualsignature","signature":"(LX3/h;I)V"}
com.ichi2.anki.dialogs.FlagAdapter$$ExternalSyntheticLambda0 -> X3.h0:
mike@isabela:~/Downloads % 
```

We already have a fragment factory but it is delegating to the base FragmentFactory implementation on this one which means the fragment must have a default constructor or this exception will happen

https://stackoverflow.com/questions/51831053/could-not-find-fragment-constructor

**Comment by mikehardy** [comment]
So this one is a "genre" problem, what do I mean by that?
I mean that *any* fragment - which is most of our dialogs - is susceptible to this problem.
I saw stack traces for a few other ones as well, like CustomStudyDialog

All of them need an instantiation pathway that is safe - either a factory that creates them using the correct constructor *or* a default constructor so the platform/default factory can instantiate

 steps to reproduce this specific crash every time (though this *will* happen on user devices if the app is killed in background then user opens it again):
- enable developer options
- turn on "don't keep activities"
- go to card browser
- open top right action bar menu and select options
- hit device home button so app is backgrounded
- open app again (tap app icon or use task switcher)
- crash

Looking now for all Fragments that are missing default constructors as that's a sure sign of this error
