### ISSUE TITLE
Add a specialized dialog for 'Your database appears to be in an inconsistent state.' and remove from ACRA

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#17390]
https://ankidroid.org/acra/app/1/bug/253214/report/a77db325-8df9-45cf-92a8-bab2b989cf2b

```
s7.f: Your database appears to be in an inconsistent state. Please use the Check Database action. No such notetype>: '261044405'
	at net.ankiweb.rsdroid.exceptions.BackendNotFoundException.<init>(BackendNotFoundException.kt:22)
	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:113)
	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:281)
	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
	at net.ankiweb.rsdroid.Backend.runMethodRaw$lambda$1(Backend.kt:118)
	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:131)
	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:117)
	at anki.backend.GeneratedBackend.newNoteRaw(GeneratedBackend.kt:1420)
	at anki.backend.GeneratedBackend.newNote(GeneratedBackend.kt:1425)
	at com.ichi2.libanki.Note$Companion.fromNotetypeId(Note.kt:69)
	at com.ichi2.anki.NoteEditor.setNote(NoteEditor.kt:2150)
	at com.ichi2.anki.NoteEditor.onCollectionLoaded(NoteEditor.kt:713)
	at com.ichi2.anki.AnkiFragment.startLoadingCollection(AnkiFragment.kt:173)
	at com.ichi2.anki.NoteEditor.onViewCreated(NoteEditor.kt:500)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3152)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:608)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2211)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2106)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2049)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3324)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3234)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at com.ichi2.anki.AnkiActivity.onStart(AnkiActivity.kt:128)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8151)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3537)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7969)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:956)

```

**Comment by sonalyadav1** [comment]
Hi! I was looking into this issue and had a quick question.

It seems to occur when a note references a missing notetype, causing a BackendNotFoundException when the NoteEditor loads.

Would you prefer handling this directly in the NoteEditor, or is there a preferred way to handle such backend errors more centrally?
