### ISSUE TITLE
Syncing media notification gets stuck sometimes

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#17639]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

- Sync your collection
- While the collection is being synced, minimize the app
- Sometimes, the syncing media notification gets stuck. The Abort button doesn't do anything, neither does trying to swipe it away.
- Force stopping the app is the only way to get rid of the notification.

### Expected behaviour

The notification should get automatically dismissed after the media sync is complete.

### Debug info

```text
2.21 alpha 3
I believe that this issue was present in 2.20 too.
```

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
AnkiDroid's fault? AnkiWeb's fault? Anki sync code's fault? Connection's fault?

Good luck for whoever investigates this

**Comment by criticalAY** [comment]
I can inspect it after tomorrow, and if someone else gets to it then niceee

**Comment by Rahib-Khan0** [comment]
well sometimes same thing happens in WhatsApp media backup notification 
steps to reproduce notification stuck:

- Turn media backup on daily
- when media backup notification is on then turn off the wifi/interner connection

it will get stuck till you force stop the app or restart the device
i have reported this several months before and still the issue hasn't fixed

i don't know the solution, i am a rookie trying to understand what is going on in open source world

**Comment by criticalAY** [comment]
Reproduced and got the exception 

```
02:40:09.312  I  Showing SyncMediaWorker's notification
02:40:09.314  I  Moving WorkSpec (568642fb-3092-42c2-a9cb-b2265d724cdc) to the foreground
02:40:09.322  W  android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.ichi2.anki.debug/androidx.work.impl.foreground.SystemForegroundService (Ask Gemini)
                 	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
                 	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
                 	at android.os.Parcel.readParcelableInternal(Parcel.java:5075)
                 	at android.os.Parcel.readParcelable(Parcel.java:5057)
                 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3237)
                 	at android.os.Parcel.createException(Parcel.java:3226)
                 	at android.os.Parcel.readException(Parcel.java:3209)
                 	at android.os.Parcel.readException(Parcel.java:3151)
                 	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6393)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at leakcanary.ServiceWatcher$install$4$2.invoke(ServiceWatcher.kt:93)
                 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                 	at $Proxy4.startService(Unknown Source)
                 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1960)
                 	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1935)
                 	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:832)
                 	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:1130)
                 	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:711)
                 	at androidx.work.impl.Processor.startForeground(Processor.java:205)
                 	at androidx.work.impl.utils.WorkForegroundUpdater.lambda$setForegroundAsync$0$androidx-work-impl-utils-WorkForegroundUpdater(WorkForegroundUpdater.java:94)
                 	at androidx.work.impl.utils.WorkForegroundUpdater$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
                 	at androidx.work.ListenableFutureKt.executeAsync$lambda$4$lambda$3(ListenableFuture.kt:59)
                 	at androidx.work.ListenableFutureKt.$r8$lambda$2J7WTnmfyHeSyx3GGU57K1DCNjw(Unknown Source:0)
                 	at androidx.work.ListenableFutureKt$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
                 	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by BrayanDSO** [comment]
> Showing SyncMediaWorker's notification

This seems like it was added by you, so sharing the exact point that you added it would help.

> startForegroundService() not allowed due to mAllowStartForeground false

Have you investigated why mAllowStartForeground is false here? Why `trySetForeground` doesn't catch the error? 

Why cancelling the notification in your PR is supposed to fix the issue? Is because the same ID is being used? Because of the work ExistingWorkPolicy?
