### ISSUE TITLE
android.database.sqlite.SQLiteException: no such table: col (code 1): , while compiling: SELECT ver FROM col at com.ichi2.anki.AnkiDb.queryScalar(AnkiDb.java:121)

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2822]
Originally reported on Google Code with ID 1920

```
This seems to be happening fairly frequently

Begin Stacktrace
android.database.sqlite.SQLiteException: no such table: col (code 1): , while compiling:
SELECT ver FROM col
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1012)
at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:623)
at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1253)
at com.ichi2.anki.AnkiDb.queryScalar(AnkiDb.java:121)
at com.ichi2.anki.AnkiDb.queryScalar(AnkiDb.java:113)
at com.ichi2.libanki.Storage._upgradeSchema(Storage.java:82)
at com.ichi2.libanki.Storage.Collection(Storage.java:58)
at com.ichi2.libanki.Storage.Collection(Storage.java:40)
at com.ichi2.anki.AnkiDroidApp.openCollection(AnkiDroidApp.java:391)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:677)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:277)
at com.ichi2.async.Connection.doInBackground(Connection.java:255)
at com.ichi2.async.Connection.doInBackground(Connection.java:84)
at android.os.AsyncTask$2.call(AsyncTask.java:287)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:856)

End Stacktrace

http://ankidroid-triage.appspot.com/report_crashes?bug_id=6556467024887808
```

Reported by `perceptualchaos2` on 2013-12-18 05:55:14

**Comment by tkv123** [comment]
i am also facing this type of error which crash my app. help me

E/SQLiteLog: (1) no such column: _id
E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
    Process: com.example.pets, PID: 25266
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: android.database.sqlite.SQLiteException: no such column: _id (code 1 SQLITE_ERROR[1]): , while compiling: SELECT _id, name, breed FROM pets
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1372)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:811)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1959)
        at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1806)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1677)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1845)
        at com.example.pets.data.petProvider.query(petProvider.java:80)
        at android.content.ContentProvider.query(ContentProvider.java:1235)
        at android.content.ContentProvider.query(ContentProvider.java:1328)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:267)
        at android.content.ContentResolver.query(ContentResolver.java:951)
        at android.content.ContentResolver.query(ContentResolver.java:887)
        at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:81)
        at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:63)
        at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:41)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)

**Comment by david-allison-1** [comment]
Hi @tkv123,

This doesn't appear to be an AnkiDroid issue.

Your error message states `no such column: _id`. You should ensure that you've added this column to your `pets` table in the SQL `CREATE` statement.

You'd be best to find a website designed for debugging programming issues if you require further help.

Hope this helps,

David
