### ISSUE TITLE
Crash related to mounting/unmounting

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2925]
Originally reported on Google Code with ID 2028

```
I've been mounting and unmounting my Archos 28 (connected via USB to a computer) while
AnkiDroid 2.1beta8 is running, in order to take and upload screenshots to this issue
tracker, and sometimes when I unmount and come back to AnkiDroid, it crashes. Signature:

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.ichi2.anki.action.MEDIA_MOUNT
} in com.ichi2.anki.StudyOptionsActivity$2@ at android.app.ActivityThread$PackageInfo$ReceiverDispatcher$Args.run(ActivityThread.java:905)
at com.ichi2.anki.StudyOptionsActivity$2.onReceive(StudyOptionsActivity.java:303)

from http://ankidroid-triage.appspot.com/view_bug?bug_id=5162280241070080

Archos 28 firmware 2.4.83 (Android 2.2.1)

```

Reported by `mike@mikemorr.com` on 2014-03-19 10:02:09

**Comment by dae** [comment]
If the problem still exists after 2.17 (or an alpha/beta of it) is released, please let us know.
