### ISSUE TITLE
SQLiteDatabase.openDatabase at AnkiDb.<init>: Could not open the database in read/write mode

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2969]
Originally reported on Google Code with ID 2072
```
http://ankidroid-triage.appspot.com/view_bug?bug_id=3033195
1353 occurrences, highest by count in latest AnkiDroid (2.1.3)

android.database.sqlite.SQLiteException: not an error (code 0): Could not open the
database in read/write mode.
at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:669)
at com.ichi2.anki.AnkiDb.<init>(AnkiDb.java:50)
at com.ichi2.anki.AnkiDatabaseManager.getDatabase(AnkiDatabaseManager.java:44)
at com.ichi2.libanki.Storage.Collection(Storage.java:53)
at com.ichi2.libanki.Storage.Collection(Storage.java:40)
at com.ichi2.anki.AnkiDroidApp.openCollection(AnkiDroidApp.java:422)
at com.ichi2.async.DeckTask.doInBackgroundOpenCollection(DeckTask.java:487)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:222)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:76)

Sometimes also (also in 2.1.3):
android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could
not open database
android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5):
, while compiling: PRAGMA journal_mode
```

Reported by `nicolas.raoul` on 2014-04-08 07:06:00

**Comment by timrae** [comment]
Pretty sure this is just a manifest of corrupt collections #3576
