### ISSUE TITLE
I can't use a study function with error

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2986]
Originally reported on Google Code with ID 2089
```
What steps will reproduce the problem?
Start with "study now" button on the browser with PC

What is the expected output? What do you see instead?
Error shows "your collection is in an inconsistent state.
please use tools>Check Database on the computer version."
Using Desktop tool followed as error showed, but it doesn't work


Does it happen again every time you repeat the steps above? Or did it
happen only one time?
Yes,it happens everytime,every devices

What version of AnkiDroid are you using? (Decks list > menu > About > Look
at the title)
v2.1.3
On what version of Android? (Home screen > menu > About phone > Android
version)


If it is a crash or "Force close" and you can reproduce it, the following
would help immensely: 1) Install the "SendLog" app, 2) Reproduce the crash,
3) Immediately after, launch SendLog, 4) Attach the resulting file to this
report. That will make the bug much easier to fix.


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.webview", line
21, in link
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.reviewer", line
312, in _linkHandler
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.reviewer", line
245, in _showAnswer
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.reviewer", line
611, in _showEaseButtons
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.reviewer", line
648, in _answerButtons
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.reviewer", line
631, in _defaultEase
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.sched", line 135,
in answerButtons
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.sched", line 597,
in _lrnConf
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.sched", line 1077,
in _newConf
KeyError: 'delays'
```

Reported by `bon.yoshiaki` on 2014-04-20 04:49:46

**Comment by timrae** [comment]
I think the root cause of this may have been fixed recently by @hssm. In any case we haven't seen any instances of this for a  long time
