### ISSUE TITLE
Crash when moving empty forecast chart

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3009]
Originally reported on Google Code with ID 2112
```
1. Open all-time forecast chart on recently untouched deck
2. No data appear
3. Move finger left and right fast
4. Crash

Reproduced 2 times (100%) on Samsung tablet with China-customized Android OS.
http://ankidroid-triage.appspot.com/view_bug?bug_id=4811180

java.util.NoSuchElementException
at java.util.TreeMap$BoundedMap.lastKey(TreeMap.java:1234)
at org.achartengine.chart.XYChart.draw(XYChart.java:250)
at org.achartengine.GraphicalView.onDraw(GraphicalView.java:158)
at android.view.View.draw(View.java:13776)
at android.view.View.getDisplayList(View.java:12727)
at android.view.View.getDisplayList(View.java:12771)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3205)
at android.view.View.getDisplayList(View.java:12663)
at android.view.View.getDisplayList(View.java:12771)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3205)
at android.view.View.getDisplayList(View.java:12663)
at android.view.View.getDisplayList(View.java:12771)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3205)
at android.view.View.getDisplayList(View.java:12663)
at android.view.View.getDisplayList(View.java:12771)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3205)
at android.view.View.getDisplayList(View.java:12663)
at android.view.View.getDisplayList(View.java:12771)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3205)
at android.view.View.getDisplayList(View.java:12663)
at android.view.View.getDisplayList(View.java:12771)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3205)
at android.view.View.getDisplayList(View.java:12663)
at android.view.View.getDisplayList(View.java:12771)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3205)
at android.view.View.getDisplayList(View.java:12663)
at android.view.View.getDisplayList(View.java:12771)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3205)
at android.view.View.getDisplayList(View.java:12663)
at android.view.View.getDisplayList(View.java:12771)
at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1144)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2288)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2160)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1968)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1120)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4604)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
at android.view.Choreographer.doCallbacks(Choreographer.java:555)
at android.view.Choreographer.doFrame(Choreographer.java:525)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4921)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
at dalvik.system.NativeStart.main(Native Method)
```

Reported by `nicolas.raoul` on 2014-05-07 14:21:15

**Comment by hssm** [comment]
Stats module has been replaced since then.
