### ISSUE TITLE
Null template

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3331]
Originally reported on Google Code with ID 2435

```
There seem to be a few users getting null pointer exceptions when answering cards
http://ankidroid-triage.appspot.com/report_crashes?bug_id=6161637560025088

java.lang.NullPointerException at com.ichi2.libanki.Card.template(Card.java:335) at
com.ichi2.libanki.Card.template(Card.java:335)

Begin Stacktrace
java.lang.NullPointerException
at com.ichi2.libanki.Card.template(Card.java:335)
at com.ichi2.libanki.Card._getQA(Card.java:289)
at com.ichi2.libanki.Card._getQA(Card.java:281)
at com.ichi2.async.DeckTask.doInBackgroundAnswerCard(DeckTask.java:442)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:241)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:264)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:856)

End Stacktrace
```

Reported by `perceptualchaos2` on 2014-12-09 00:46:32

**Comment by mikehardy** [comment]
I just fixed a nice crash bug here. As with other crashes, I'm watching them closely and fix any I see
