### ISSUE TITLE
java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it.

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3514]
Originally reported on Google Code with ID 2626
```
It looks like we're starting to get some multithreading issues again with the Collection.
It appears to be getting caused by the call to getCol() in DeckPicker.onCreate introduced
here:

https://github.com/ankidroid/Anki-Android/commit/94222681f4560b8981f5e3d962ff2f9eb207ad3e

I don't fully understand the problem, as the methods in the CollectionHelper class
are synchronized, but it appears that at least one issue occurs when the onCreate()
method is called while a sync is in progress, causing this error:

797899ac-9f17-4d72-85c4-6fa285f1b6aa

java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:304)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.
Make sure the Cursor is initialized correctly before accessing data from it.
at android.database.CursorWindow.nativeGetLong(Native Method)
at android.database.CursorWindow.getLong(CursorWindow.java:511)
at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
at com.ichi2.libanki.Collection.load(Collection.java:187)
at com.ichi2.libanki.Collection.<init>(Collection.java:151)
at com.ichi2.libanki.Storage.Collection(Storage.java:62)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:95)
at com.ichi2.anki.CollectionHelper.reopenCollection(CollectionHelper.java:129)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:497)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:188)
at com.ichi2.async.Connection.doInBackground(Connection.java:175)
at com.ichi2.async.Connection.doInBackground(Connection.java:61)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow. Make
sure the Cursor is initialized correctly before accessing data from it.
at android.database.CursorWindow.nativeGetLong(Native Method)
at android.database.CursorWindow.getLong(CursorWindow.java:511)
at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
at com.ichi2.libanki.Collection.load(Collection.java:187)
at com.ichi2.libanki.Collection.<init>(Collection.java:151)
at com.ichi2.libanki.Storage.Collection(Storage.java:62)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:95)
at com.ichi2.anki.CollectionHelper.reopenCollection(CollectionHelper.java:129)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:497)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:188)
at com.ichi2.async.Connection.doInBackground(Connection.java:175)
at com.ichi2.async.Connection.doInBackground(Connection.java:61)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2418)
at android.app.ActivityThread.access$900(ActivityThread.java:154)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5293)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
at android.database.CursorWindow.nativeGetLong(Native Method)
at android.database.CursorWindow.getLong(CursorWindow.java:511)
at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
at com.ichi2.libanki.Collection.load(Collection.java:187)
at com.ichi2.libanki.Collection.<init>(Collection.java:151)
at com.ichi2.libanki.Storage.Collection(Storage.java:62)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:95)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:112)
at com.ichi2.anki.AnkiActivity.getCol(AnkiActivity.java:73)
at com.ichi2.anki.DeckPicker.onCreate(DeckPicker.java:402)
at android.app.Activity.performCreate(Activity.java:5990)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2309)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2777)
at android.app.ActivityThread.access$900(ActivityThread.java:179)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5972)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
at android.database.CursorWindow.nativeGetLong(Native Method)
at android.database.CursorWindow.getLong(CursorWindow.java:524)
at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
at com.ichi2.libanki.Collection.load(Collection.java:187)
at com.ichi2.libanki.Collection.<init>(Collection.java:151)
at com.ichi2.libanki.Storage.Collection(Storage.java:62)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:95)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:112)
at com.ichi2.anki.AnkiActivity.getCol(AnkiActivity.java:73)
at com.ichi2.anki.DeckPicker.onCreate(DeckPicker.java:402)
at android.app.Activity.performCreate(Activity.java:6289)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)

I'll try changing the new adapter class to access the collection via CollectionHelper
and see if that helps at all
```

Reported by `perceptualchaos2` on 2015-05-29 03:03:31

**Comment by hssm** [comment]
Fixed by https://github.com/ankidroid/Anki-Android/pull/4033
