### ISSUE TITLE
Ankidroid cannot record audio bug

### ISSUE THREAD

**Issue by iamsunbun** [ankidroid/Anki-Android#3641]
Hello

I couldn't record audio the past few days using F5 or the record button.

thanks

Sunny

The following messages and error report:

Error running lame rec.wav.mp3--noreplaygain--quiet

Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/threading", line 551, in __bootstrap_inner
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.sound", line 255, in run
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/pyaudio", line 705, in open
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/pyaudio", line 387, in __init__
IOError: [Errno Device unavailable] -9985

**Comment by timrae** [comment]
Hi this is the AnkiDroid bug tracker. See [here](https://anki.tenderapp.com/) for the desktop site

**Comment by iamsunbun** [comment]
Hi Tim

Sorry, got my programs mixed up!

thanks

Sunny
