### ISSUE TITLE
Crash by sync error

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3697]
After the message, "Media synced", is displayed,
The message, "AnkiDroid has encountered a problem; a report is being generated…", 
is displayed.

---------------------------------------------------------------------------
AnkiDroid Version = 2.5alpha66

Android Version = 4.4.2

ACRA UUID = 773bb303-203a-46ee-899b-15ebda247a8c

---------------------------------------------------------------------------
AnkiDroid Version = 2.5alpha66

Android Version = 4.3

ACRA UUID = 2a2c4d9e-1d5c-46db-ba52-ad47b3d317a6

---------------------------------------------------------------------------

**Comment by timrae** [comment]
Hmmmm 


	
java.lang.StackOverflowError
...
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSnackbar(AnkiActivity.java:376)
at com.ichi2.anki.AnkiActivity.showSimpleSnackbar(AnkiActivity.java:363)
at com.ichi2.anki.DeckPicker.showSyncLogMessage(DeckPicker.java:1023)

**Comment by timrae** [comment]
Thanks for the nice alpha testing and bug reporting, it's extremely useful. I think I've fixed all of the bugs you've reported for v2.5 now

**Comment by snowtimeglass** [comment]
My pleasure.
Thank you always for your dedication and hard work.
