### ISSUE TITLE
Crash rescheduling card with empty value for num days

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#3772]
java.lang.NumberFormatException: Invalid int: ""
at java.lang.Integer.invalidInt(Integer.java:138)
at java.lang.Integer.parseInt(Integer.java:358)
at java.lang.Integer.parseInt(Integer.java:334)
at com.ichi2.anki.dialogs.NoteEditorRescheduleCard$1.onInput(NoteEditorRescheduleCard.java:30)
at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:353)

We can fix it by by adding `.inputRange(1, -1)` to the builder in `NoteEditorRescheduleCard.java`, but that requires us to update to a newer version of Material Dialogs, which in turn depends on appcompat 23.1, which we can't use because of #3739.

We could do some dependency forcing with Gradle if really necessary, but it might just be easier to wait for appcompat 23.1.1 to come out, which hopefully doesn't break something else. I don't remember the last time a version of appcompat was released without a major regression tbh. :-/

**Comment by hssm** [comment]
Just wait it out. We're going to upgrade to it eventually anyway, and this isn't a very commonly used feature.
