### ISSUE TITLE
NPE updating widget

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#3781]
@hssm 

I saw this in the beta3 logs

java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
at com.ichi2.libanki.Sched._groupChildrenMain(Sched.java:505)
at com.ichi2.libanki.Sched._groupChildrenMain(Sched.java:497)
at com.ichi2.libanki.Sched._groupChildren(Sched.java:449)
at com.ichi2.libanki.Sched.deckDueTree(Sched.java:437)
at com.ichi2.widget.WidgetStatus.getCounts(WidgetStatus.java:123)
at com.ichi2.widget.WidgetStatus.access$100(WidgetStatus.java:38)
at com.ichi2.widget.WidgetStatus$UpdateDeckStatusAsyncTask.doInBackground(WidgetStatus.java:92)
at com.ichi2.widget.WidgetStatus$UpdateDeckStatusAsyncTask.doInBackground(WidgetStatus.java:79)
at android.os.AsyncTask$2.call(AsyncTask.java:288)

**Comment by timrae** [comment]
I just saw this in the beta2 logs as well, not sure if they're related:

Caused by: java.lang.NullPointerException
at com.ichi2.widget.WidgetStatus$UpdateDeckStatusAsyncTask.doInBackground(WidgetStatus.java:194)
at com.ichi2.widget.WidgetStatus$UpdateDeckStatusAsyncTask.doInBackground(WidgetStatus.java:156)
at android.os.AsyncTask$2.call(AsyncTask.java:287)

**Comment by hssm** [comment]
Thanks. There is a comment on one of reports:
>See forimpost \"Problem with beta\" Sonce the beta i can not open the database

I think this a broken collection and the widget is the first thing that triggers a crash. I'm not sure if the widget itself is causing the problem. I'll find that thread and ask if removing the widget does anything.
