### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3794]
AnkiDroid Version = 2.5beta4

Android Version = 4.3

ACRA UUID = 94a9a173-2eac-44e2-aa4a-2dc2c47ab39a

**Comment by timrae** [comment]
Did it happen just once or is the error still occurring? It's just a database locked error, which we get a lot of but don't have any ideas about the cause.

android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): retrycount exceeded
at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1036)
at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
at com.ichi2.anki.AnkiDb.queryString(AnkiDb.java:159)
at com.ichi2.anki.AnkiDb.setDeleteJournalMode(AnkiDb.java:361)
at com.ichi2.anki.AnkiDb.closeDatabase(AnkiDb.java:98)
at com.ichi2.anki.AnkiDatabaseManager.closeDatabase(AnkiDatabaseManager.java:61)
at com.ichi2.libanki.Collection.close(Collection.java:323)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:457)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:189)
at com.ichi2.async.Connection.doInBackground(Connection.java:179)
at com.ichi2.async.Connection.doInBackground(Connection.java:50)
at android.os.AsyncTask$2.call(AsyncTask.java:287)

**Comment by timrae** [comment]
@snowtimeglass if you can still reproduce the issue, and if your collection is not too private, would you be able to email me the following files? (my email address is perceptualchaos2 on gmail)

collection.anki2
collection.anki2-shm
collection.anki2-wal
collection.log

**Comment by snowtimeglass** [comment]
>Did it happen just once or is the error still occurring?

It happened 4 times in ten minutes before the post, so I thought the error is permanent.
However, it doesn't happen now. I'm sorry for the bother.

**Comment by timrae** [comment]
OK let us know if it happens again
