### ISSUE TITLE
desktop anki can't import ankidroid apkg backup files due to missing media file

### ISSUE THREAD

**Issue by wchristian** [ankidroid/Anki-Android#3800]
```
Import failed.
Traceback (most recent call last):
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.importing", line 327, in importFile
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.importing.apkg", line 22, in run
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/zipfile", line 869, in read
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/zipfile", line 892, in open
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/zipfile", line 859, in getinfo
KeyError: "There is no item named 'media' in the archive"
```

**Comment by wchristian** [comment]
After adding a file called media with the contents as follows:

    {}

A new error is thrown:

    Import failed.
    Traceback (most recent call last):
      File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.importing", line 327, in importFile
      File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.importing.apkg", line 25, in run
      File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.importing.anki2", line 25, in run
      File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.importing.anki2", line 36, in _prepareFiles
      File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.storage", line 32, in Collection
      File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.storage", line 55, in _upgradeSchema
      File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.db", line 76, in scalar
      File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.db", line 43, in execute
    DatabaseError: file is encrypted or is not a database

**Comment by david-allison-1** [comment]
I'm fairly sure I came across this yesterday with our `.colpkg` exports. Needs investigation as it scared the user that their file was corrupt.

**Comment by DrewPlots** [comment]
I've managed a potential fix for what *I believe* OP *was* experiencing.
This fix _may or may not help, but at least sheds light on the ominous import error in Anki_, see here:
[https://forums.ankiweb.net/t/created-colpkg-invalid-file-format-for-import/10148/3](https://forums.ankiweb.net/t/created-colpkg-invalid-file-format-for-import/10148/3)

**Comment by mikehardy** [comment]
I'll reopen this, we have lots of new folks around and maybe someone wants to take a look?
