### ISSUE TITLE
IllegalStateException: attempt to re-open an already-closed object

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#3833]
I'm not too sure what's going on here... The `onPostExecute()` method in question gives `buildDeckList()` a fresh reference to the Collection from `CollectionHelper.getInstance().getCol(this)` so the database should be open and ready.

Direct [link to crash](https://ankidroid.org/couchdb/acralyzer/_design/acralyzer/index.html#/report-details/ankidroid/a586aca5-1d9e-4a48-85bc-41e1f56feca4)

java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /sdcard/AnkiDroid/collection.anki2
at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1436)
at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1379)
at com.ichi2.anki.AnkiDb.queryScalar(AnkiDb.java:149)
at com.ichi2.anki.widgets.DeckAdapter.processNodes(DeckAdapter.java:241)
at com.ichi2.anki.widgets.DeckAdapter.processNodes(DeckAdapter.java:232)
at com.ichi2.anki.widgets.DeckAdapter.buildDeckList(DeckAdapter.java:143)
at com.ichi2.anki.DeckPicker$21.onPostExecute(DeckPicker.java:1752)

**Comment by timrae** [comment]
Probably fixed now
