### ISSUE TITLE
Ankidroid failed cards behind my back and then crashed after syncing

### ISSUE THREAD

**Issue by ReneSac** [ankidroid/Anki-Android#4039]
At the end of my review session, or maybe earlier, ankidroid has gone crazy marking as failed cards that I have not seen, both young/mature and new. The card that was at the top of the new cards pile was marked 35 times as failed (see anexed image). The others seems to have been marked only once. 

This bug is probably related to the feature of automatically showing and answering the card after x seconds. I have it configured to show the answer after 10 seconds and answer it after 1 minute (against my will as it was the maximum I could set, see the feature request). Also, I think ankidroid was executing on the background when the 35 failures in the picture happened. But other cards failing afterwards was with it in first plane. I went reviewing one or two failed cards and when I was back in the main screen the number of new cards decreased (because they entered the failed pile). The same happened before when there was 1 review card, but when I clicked "study" it already showed zero.

I may privately share my deck at request. Ankidroid has crashed right after syncing, and I sent the crash report with a comment like "ankidroid has gone crazy". 

![ankidroidcrazy](https://cloud.githubusercontent.com/assets/6010063/12101642/fa5283dc-b31c-11e5-8a71-1683fee5a6ef.png)

**Comment by timrae** [comment]
Can you post your "debug info" please?

https://ankidroid.org/docs/help.html

**Comment by ReneSac** [comment]
I edited my post with the debug info a few minutes after I posted. It is already there at the end.

Pasting it again: 

AnkiDroid Version = 2.5.4

Android Version = 4.4.2

ACRA UUID = 68478e32-07d5-4dc8-b6c5-05bdb704bea0

**Comment by timrae** [comment]
Here's the logcat:

29	01-04 18:44:14.133 I/AnkiDroid( 9450): Sync: finishing
30	01-04 18:44:14.233 I/AnkiDroid( 9450): flush - Saving information to DB...
31	01-04 18:44:16.463 I/AnkiDroid( 9450): AbstractFlashcardViewer:: EASE_1 pressed
32	01-04 18:44:16.793 I/AnkiDroid( 9450): Collection closed
33	01-04 18:44:16.793 I/AnkiDroid( 9450): openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
34	01-04 18:44:16.903 E/AnkiDroid( 9450): DeckTask/ doInBackgroundAnswerCard - RuntimeException on answering card
35	01-04 18:44:16.903 E/AnkiDroid( 9450): java.lang.NullPointerException
36	01-04 18:44:16.903 E/AnkiDroid( 9450): at com.ichi2.libanki.Card.flushSched(Card.java:239)
37	01-04 18:44:16.903 E/AnkiDroid( 9450): at com.ichi2.libanki.Sched.answerCard(Sched.java:186)
38	01-04 18:44:16.903 E/AnkiDroid( 9450): at com.ichi2.async.DeckTask.doInBackgroundAnswerCard(DeckTask.java:448)

Probably the crash can be fixed by running "check database". I don't know what caused it to get like that in the first place, but I don't personally have time to investigate further sorry.

**Comment by ReneSac** [comment]
It seems to have crashed after it finished syncing. Indeed, the synch on my destktop worked fine after that and I didn't saw any corruption and ankidroid hasn't crashed since.

The problem is the "AbstractFlashcardViewer:: EASE_1 pressed" and "doInBackgroundAnswerCard". I didn't trigger those two things. Ankidroid was pressing EASE_1 for new cards while I was in the main screen, and even when I left it in the main screen and I was using another app in the foreground. The exception and crash is probably because it answered a card while it was flushing the DB, something that should be impossible, as the 35 consecutive failures for that one card w/o reviewing the rest of the failed cards in the mean time were also impossible but didn't trigger an exception.
