### ISSUE TITLE
NoSuchElementException performing undo 

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#4099]
Found on [Acralyzer](https://ankidroid.org/couchdb/acralyzer/_design/acralyzer/index.html#/reports-browser/ankidroid/bug/c14d1b38d203418de8fb1aa8bf47a9a3) (report instance [here](https://ankidroid.org/couchdb/acralyzer/_design/acralyzer/index.html#/report-details/ankidroid/85e8fe28-0b46-49b8-8de0-3f7a37d4be72))

java.util.NoSuchElementException
at java.util.LinkedList.removeLastImpl(LinkedList.java:713)
at java.util.LinkedList.removeLast(LinkedList.java:700)
at com.ichi2.libanki.Collection.undo(Collection.java:1196)
at com.ichi2.async.DeckTask.doInBackgroundUndo(DeckTask.java:587)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:250)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:66)

**Comment by hssm** [comment]
Two undo button presses within 10ms. Not sure how this is physically possible, even with gestures.
```
02-13 00:25:18.514 I/AnkiDroid(14500): Reviewer:: Undo button pressed
02-13 00:25:18.524 I/AnkiDroid(14500): Reviewer:: Undo button pressed
```

**Comment by mikehardy** [comment]
I have seen no crashes like this since I've been watching but I will reopen and fix if I see them
