### ISSUE TITLE
AnkiDroid Crashes on Open 

### ISSUE THREAD

**Issue by swagardson** [ankidroid/Anki-Android#4125]
I have an LG G4, Android version 6.0. 

Just got this phone--other apps load fine. Downloaded AnkiDroid and went to sync my cards only for the app to crash on startup every time without fail. 

Older versions don't work, current alphas don't work, and I can't access the debug info in the application as it just crashes. I sent some sort of crash report on my phone, but I don't know if it gets sent to Anki developers. App works fine on other devices. 

Anyways, I'm dying without my cards here! Help!

**Comment by timrae** [comment]
> current alphas don't work

That's unexpected. What happens if you rename the collection.anki2 file manually to "collection.anki2.bak" or something?

**Comment by hssm** [comment]
For reference: 
https://ankidroid.org/couchdb/acralyzer/_design/acralyzer/index.html#/reports-browser/ankidroid

```
android.database.sqlite.SQLiteException: no such table: col (code 1): , while compiling: SELECT ver FROM col
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:893)
at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:504)
at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:726)
at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1426)
at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1365)
at com.ichi2.anki.AnkiDb.queryScalar(AnkiDb.java:140)
at com.ichi2.libanki.Storage._upgradeSchema(Storage.java:84)
at com.ichi2.libanki.Storage.Collection(Storage.java:55)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:98)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:115)
at com.ichi2.anki.AnkiActivity.getCol(AnkiActivity.java:107)
```

The error generally means that the file itself isn't a valid database file. Can you navigate to the AnkiDroid directory and check two things:
1 - If `collection.anki2` exists and has a size larger than 0
2 - If you can create/modify files yourself in this directory

**Comment by swagardson** [comment]
> What happens if you rename the collection.anki2 file manually to "collection.anki2.bak" or something?

That worked! Must have been something with the way the database was being handled. I triple-checked and synced my cards from and then to the database with no issues. Killed the app, restarted it--everything works like a charm. Thanks! 

> 1 - If collection.anki2 exists and has a size larger than 0
2 - If you can create/modify files yourself in this directory

`collection.anki2` was 4.00 kB, and I was able to rename it to `collection.anki2.bak` with no issues. Thanks for the resource and help!

**Comment by hssm** [comment]
Hmm....it seems that the first attempt at creating a new database went wrong. I don't know why but we'll have to keep it in mind in case it pops up again. Glad you've got it sorted now.

**Comment by timrae** [comment]
Would you be able to send us the .bak collection file please? For example
via Google Drive or something

**Comment by swagardson** [comment]
Yeah! Here's a DropBox link to the file. Seems like it was untouched in the syncing process. 

https://www.dropbox.com/s/nly1yl6vv2spfni/collection.anki2.bak?dl=0

Let me know if the link works okay.

**Comment by hssm** [comment]
Thanks, the link is okay. It looks like the file is a valid SQLite3 file but the database itself is empty (no tables). It must have been interrupted somewhere in the creation process but there's no way to tell what went wrong.

**Comment by swagardson** [comment]
That's unfortunate, but hopefully my case is one of few rather than many. At least this thread will be here for anyone else who may have issues in the future! 

Thanks again.
