### ISSUE TITLE
"No card with id" DeckTask crash

### ISSUE THREAD

**Issue by marcardar** [ankidroid/Anki-Android#4186]
Using the latest develop build - Nexus 6P 6.0.1

Presumably this happened because the content provider was used to delete a card (and the card browser does not automatically refresh). Or maybe some inconsistency (orphaned child etc) has arisen in the database?

```
E/DeckTask: previously running task failed with exception: 37
java.util.concurrent.ExecutionException: java.lang.RuntimeException:  No card with id 1459360605341
    at java.util.concurrent.FutureTask.report(FutureTask.java:94)
    at java.util.concurrent.FutureTask.get(FutureTask.java:164)
    at android.os.AsyncTask.get(AsyncTask.java:498)
    at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:209)
    at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:66)
    at android.os.AsyncTask$2.call(AsyncTask.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
 Caused by: java.lang.RuntimeException:  No card with id 1459360605341
    at com.ichi2.libanki.Card.load(Card.java:143)
    at com.ichi2.libanki.Card.<init>(Card.java:118)
    at com.ichi2.libanki.Collection.getCard(Collection.java:418)
    at com.ichi2.async.DeckTask.doInBackgroundRenderBrowserQA(DeckTask.java:644)
    at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:301)
    at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:66) 
    at android.os.AsyncTask$2.call(AsyncTask.java:295) 
    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
    at java.lang.Thread.run(Thread.java:818) 
```

**Comment by timrae** [comment]
Closing as basically duplicate of #4214 now that #4112 is fixed

**Comment by marcardar** [comment]
Are you sure this is the same problem as #4214 ?  #4214 is not about an exception but rather a general issue regarding AsyncTask calls in onStop(). This seems to be regarding an exception in other AsyncTask calls, no?

**Comment by timrae** [comment]
The problem is changes not getting flushed to the database in general. This particular crash for you was probably fixed by #4112 and #4222. There are similar problems in the AnkiDroid app itself due to the saving taking place via the onStop() method instead of in the original AsyncTasks themselves that do work.

**Comment by marcardar** [comment]
Okay. One thing about the models flush bug was that the `save` was already being called, but not the `flush`. So it might be that `save` is not enough?

**Comment by timrae** [comment]
Yeah Models.save() doesn't flush. Collection.save() flushes everything.

**Comment by timrae** [comment]
I'm talking about adding Collection.save() everywhere.

**Comment by marcardar** [comment]
Yeah the naming is a little confusing. If Collection.save() performs a Collection.flush() then you would expect a Models.save() to perform a flush at the models level. Instead it looks like Models.save() just sets a mChanged flag which then makes Models.flush() do some actual work...  Anyway, good luck with that!
