### ISSUE TITLE
Improve handling of missing note types

### ISSUE THREAD

**Issue by marcardar** [ankidroid/Anki-Android#4201]
Because of issue #4112 it is not uncommon to come across a deck/collection with missing note types. Here is an example stacktrace:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONArray org.json.JSONObject.getJSONArray(java.lang.String)' on a null object reference
   at com.ichi2.libanki.Models.fieldMap(Models.java:477)
   at com.ichi2.libanki.Note.load(Note.java:107)
   at com.ichi2.libanki.Note.<init>(Note.java:69)
   at com.ichi2.libanki.Note.<init>(Note.java:55)
   at com.ichi2.libanki.Collection.getNote(Collection.java:432)
   at com.ichi2.libanki.Card.note(Card.java:319)
   at com.ichi2.libanki.Card._getQA(Card.java:285)
   at com.ichi2.libanki.Card._getQA(Card.java:279)
   at com.ichi2.async.DeckTask.doInBackgroundAnswerCard(DeckTask.java:455)
   at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:241)
   at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:66)
   at android.os.AsyncTask$2.call(AsyncTask.java:295)
   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
   at java.lang.Thread.run(Thread.java:818)
```

The mid is not found and this results in an NPE.

If it's possible to change libanki code, then at least a nice exception message would help here.

Long term, I wonder about the possibility of allowing the user to select an existing note type to adopt these orphaned notes. Or maybe even auto-generating a skeleton note type which the user (or client app) could then edit as appropriate.

**Comment by hssm** [comment]
Is this still an issue with #4112 closed?

Anki has a check for notes with missing note types in its integrity check (the "check database" option) which simply deletes them. The advice we generally give when things randomly break is to run a database check, so this would eventually get fixed in that fashion. In that respect the behaviour around this issue ends up being the same as the desktop client.

**Comment by marcardar** [comment]
It's true that now that #4112 is closed this is less of an issue (although I would add that #4112 is causing me loads of problems since there is no 100% reliable workaround).

I guess this is more of a feature request. Adopting/rescuing orphaned notes could save the user from losing a lot of data.  Also, I wonder if by catching the above exception AD could then at least warn the user about the specific nature of the problem (even if it just tells them to "check database").

**Comment by timrae** [comment]
I don't think it's really worth adding code for this, I think API users are just gonna have to instruct their users to upgrade to 2.6. Hopefully we can get a beta version out within the week.
