### ISSUE TITLE
Cant add cards

### ISSUE THREAD

**Issue by Iwander** [ankidroid/Anki-Android#4258]
Traceback (most recent call last):
  File "aqt\editor.py", line 1059, in dropEvent
  File "aqt\editor.py", line 1104, in _processMime
  File "aqt\editor.py", line 1122, in _processUrls
  File "aqt\editor.py", line 799, in urlToLink
  File "aqt\editor.py", line 817, in urlToFile
  File "aqt\editor.py", line 842, in _retrieveURL
  File "urllib2.py", line 126, in urlopen
  File "urllib2.py", line 400, in open
  File "urllib2.py", line 418, in _open
  File "urllib2.py", line 378, in _call_chain
  File "urllib2.py", line 1310, in file_open
  File "urllib2.py", line 1335, in open_local_file
  File "mimetypes.py", line 294, in guess_type
  File "mimetypes.py", line 355, in init
  File "mimetypes.py", line 259, in read_windows_registry
  File "mimetypes.py", line 249, in enum_types
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 0: ordinal not in range(128)

**Comment by flerda** [comment]
This is an issue with the Desktop version of Anki.
Please report the issue to http://anki.tenderapp.com.
Thanks!
