### ISSUE TITLE
Bug: App crashes when plug in/out a USB OTG cable with a wireless mouse receiver

### ISSUE THREAD

**Issue by arvinpan** [ankidroid/Anki-Android#4281]
###### Reproduction Steps

1. 2.6beta1, Nexus 6, Android 6.0.1
2. Select a deck and start review.
3. Plug in/out a USB OTG cable with a wireless mouse receiver. This will trigger the layout to refresh, and app will crash during refreshing.
4. If not crash, try step 3 once more.
5. By the way, version 2.5.4 works fine.

###### Debug info
There are two kinds of crashes:
`05-14 23:21:18.524 6742-6742/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.ichi2.anki, PID: 6742
                                                              java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setTitle(java.lang.CharSequence)' on a null object reference
                                                                  at com.ichi2.anki.AbstractFlashcardViewer.updateScreenCounts(AbstractFlashcardViewer.java:1823)
                                                                  at com.ichi2.anki.AbstractFlashcardViewer.updateForNewCard(AbstractFlashcardViewer.java:1803)
                                                                  at com.ichi2.anki.AbstractFlashcardViewer.fillFlashcard(AbstractFlashcardViewer.java:2290)
                                                                  at com.ichi2.anki.Reviewer.fillFlashcard(Reviewer.java:399)
                                                                  at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:2140)
                                                                  at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1943)
                                                                  at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:412)
                                                                  at com.ichi2.anki.AbstractFlashcardViewer$10.onProgressUpdate(AbstractFlashcardViewer.java:606)
                                                                  at com.ichi2.async.DeckTask$TaskListener.onProgressUpdate(DeckTask.java:1312)
                                                                  at com.ichi2.async.DeckTask.onProgressUpdate(DeckTask.java:354)
                                                                  at com.ichi2.async.DeckTask.onProgressUpdate(DeckTask.java:66)
                                                                  at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:671)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `

`05-14 23:29:06.935 13996-13996/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.ichi2.anki, PID: 13996
                                                                java.lang.RuntimeException: Unable to destroy activity {com.ichi2.anki/com.ichi2.anki.Reviewer}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.removeAllViews()' on a null object reference
                                                                    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3831)
                                                                    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)
                                                                    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4053)
                                                                    at android.app.ActivityThread.-wrap15(ActivityThread.java)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.removeAllViews()' on a null object reference
                                                                    at com.ichi2.anki.AbstractFlashcardViewer.onDestroy(AbstractFlashcardViewer.java:959)
                                                                    at android.app.Activity.performDestroy(Activity.java:6422)
                                                                    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1142)
                                                                    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3818)
                                                                    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849) 
                                                                    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4053) 
                                                                    at android.app.ActivityThread.-wrap15(ActivityThread.java) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `

###### My current workaround
AbstractFlashcardViewer.java
1. onDestroy(): check mCardFrame before mCardFrame.removeAllViews();
2. updateScreenCounts(): if getSupportActionBar() is null, return.
Seems fine.

**Comment by hssm** [comment]
Do you still have this problem? I have an OTG adapter now and tried to reproduce this with numerous devices. I can see the refresh happening but it doesn't crash.

**Comment by arvinpan** [comment]
I have tried on my nexus 5x & 6, ranges from 2.6beta1 to 2.6release,  and this issue cannot be reproduced either.
That's pretty weird. The only thing that has changed is the collection data. Oh, by the way I was using a nightly build of CyanogenMod. I don't know if that matters.
I'll close this issue for now and reopen it with more details if reproduced.
Sorry for the inconvenience.
