### ISSUE TITLE
IllegalStateException crash in media recording

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5002]
###### Reproduction Steps

The "pre-launch report" from google has this from the 2.9alpha37

Looks like it's something about trying to record audio to a card and either a timing issue or a more straight coding bug - video and logcat available here for reproduction:

1. https://play.google.com/apps/publish/?account=5338425030304417978#PreLaunchReportPlace:p=com.ichi2.anki&appid=4973711737547064258&plrvc=20900137&plrtab=CRASH

2. 
3. 

Note that it appears something is wrong the ACRA limiter as well, which is crucial since that was just cherry-picked onto the stable branch and seems to be good in alpha but shouldn't have exceptions - it's the second stack here

###### Actual Result

10-02 15:28:00.581: E/ACRA(10796): ACRA caught a IllegalStateException 
for com.ichi2.anki
10-02 15:28:00.581: E/ACRA(10796): java.lang.IllegalStateException
10-02 15:28:00.581: E/ACRA(10796): 	at android.media.MediaRecorder.stop(Native Method)
10-02 15:28:00.581: E/ACRA(10796): 	at com.ichi2.anki.multimediacard.AudioView.notifyStopRecord(AudioView.java:192)
10-02 15:28:00.581: E/ACRA(10796): 	at com.ichi2.anki.multimediacard.AudioView$RecordButton$1.onClick(AudioView.java:411)
10-02 15:28:00.581: E/ACRA(10796): 	at android.view.View.performClick(View.java:6256)
10-02 15:28:00.581: E/ACRA(10796): 	at android.view.View$PerformClick.run(View.java:24697)
10-02 15:28:00.581: E/ACRA(10796): 	at android.os.Handler.handleCallback(Handler.java:789)
10-02 15:28:00.581: E/ACRA(10796): 	at android.os.Handler.dispatchMessage(Handler.java:98)
10-02 15:28:00.581: E/ACRA(10796): 	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:19)
10-02 15:28:00.581: E/ACRA(10796): 	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:164)
10-02 15:28:00.581: E/ACRA(10796): 	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:156)
10-02 15:28:00.581: E/ACRA(10796): 	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:34)
10-02 15:28:00.581: E/ACRA(10796): 	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:75)
10-02 15:28:00.581: E/ACRA(10796): 	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:50)
10-02 15:28:00.581: E/ACRA(10796): 	at androidx.test.espresso.action.Tap.c(Tap.java:9)
10-02 15:28:00.581: E/ACRA(10796): 	at androidx.test.espresso.action.Tap.a(Tap.java:19)
10-02 15:28:00.581: E/ACRA(10796): 	at androidx.test.espresso.action.Tap$1.b(Tap.java:2)
10-02 15:28:00.581: E/ACRA(10796): 	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:22)
10-02 15:28:00.581: E/ACRA(10796): 	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
10-02 15:28:00.581: E/ACRA(10796): 	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:78)
10-02 15:28:00.581: E/ACRA(10796): 	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:94)
10-02 15:28:00.581: E/ACRA(10796): 	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
10-02 15:28:00.581: E/ACRA(10796): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-02 15:28:00.581: E/ACRA(10796): 	at android.os.Handler.handleCallback(Handler.java:789)
10-02 15:28:00.581: E/ACRA(10796): 	at android.os.Handler.dispatchMessage(Handler.java:98)
10-02 15:28:00.581: E/ACRA(10796): 	at android.os.Looper.loop(Looper.java:164)
10-02 15:28:00.581: E/ACRA(10796): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
10-02 15:28:00.581: E/ACRA(10796): 	at java.lang.reflect.Method.invoke(Native Method)
10-02 15:28:00.581: E/ACRA(10796): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-02 15:28:00.581: E/ACRA(10796): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-02 15:28:00.644: W/VideoCapabilities(10796): Unrecognized profile 2130706433 for video/avc
10-02 15:28:00.644: W/VideoCapabilities(10796): Unrecognized profile 2130706434 for video/avc
10-02 15:28:00.667: I/VideoCapabilities(10796): Unsupported profile 4 for video/mp4v-es
10-02 15:28:00.673: W/VideoCapabilities(10796): Unrecognized profile 2130706433 for video/avc
10-02 15:28:00.674: W/VideoCapabilities(10796): Unrecognized profile 2130706434 for video/avc
10-02 15:28:00.685: I/VideoCapabilities(10796): Unsupported profile 4 for video/mp4v-es
10-02 15:28:00.688: W/ACRA(10796): ReportingAdministrator org.acra.config.LimitingReportAdministrator threw exception
10-02 15:28:00.688: W/ACRA(10796): java.lang.StringIndexOutOfBoundsException: length=31; index=159
10-02 15:28:00.688: W/ACRA(10796): 	at java.lang.String.substring(String.java:1971)
10-02 15:28:00.688: W/ACRA(10796): 	at org.acra.config.LimiterData$ReportMetadata.<init>(LimiterData.java:84)
10-02 15:28:00.688: W/ACRA(10796): 	at org.acra.config.LimitingReportAdministrator.shouldSendReport(LimitingReportAdministrator.java:87)
10-02 15:28:00.688: W/ACRA(10796): 	at org.acra.builder.ReportExecutor.execute(ReportExecutor.java:142)
10-02 15:28:00.688: W/ACRA(10796): 	at org.acra.builder.ReportBuilder.build(ReportBuilder.java:183)
10-02 15:28:00.688: W/ACRA(10796): 	at org.acra.reporter.ErrorReporterImpl.uncaughtException(ErrorReporterImpl.java:158)
10-02 15:28:00.688: W/ACRA(10796): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
10-02 15:28:00.688: W/ACRA(10796): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
10-02 15:28:00.688: W/ACRA(10796): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:1953)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Logged an upstream issue with ACRA for the ACRA portion of the exception. Code inspection indicates that the problem in ACRA just results in exceptions of this type being un-limited which is not perfect but is just a regression to sending all reports of the type it can't handle, not a total failure.

https://github.com/ACRA/acra/issues/703

**Comment by mikehardy** [comment]
If you do a pronunciation lookup from the advanced editor, the result lands you in what looks like the audio record screen for a field, but the action bar isn't set up right. When recording audio there shouldn't be a microphone icon available, it should be text and image up there. The google pre-launch robot hit the record media player control button, the microphone action bar button, and the record media player control button in rapid succession and that was the illegal state under the covers.
