### ISSUE TITLE
Android 2.83浏览所有卡片崩溃重启

### ISSUE THREAD

**Issue by goxykzd** [ankidroid/Anki-Android#5006]
###### Reproduction Steps

1. Android8.0里Ankiroid浏览所有卡片崩溃重启；
2. 全部卡片近万张；
3. 但选择浏览子牌组（几百张卡片）没问题。

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hmm - that's unexpected, I was able to see the crash from the UUID you posted in the forum, thank you:

AnkiDroid Version = 2.8.4
Android Version = 8.1.0
ACRA UUID = 8df70c26-f47b-4a20-a387-cbf725ee760d


--------- beginning of main
--
1 | 10-03 19:32:08.321 I/AnkiDroid( 9495): openCollection: /sdcard/AnkiDroid/collection.anki2
2 | 10-03 19:32:27.115 I/AnkiDroid( 9495): Cancelled task 30
3 | 10-03 19:32:27.432 I/AnkiDroid( 9495): CardBrowser:: Completed doInBackgroundSearchCards Successfuly
4 | 10-03 19:32:27.482 I/AnkiDroid( 9495): flush - Saving information to DB...
5 | --------- beginning of crash




java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:353)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: Couldn't read row
at io.requery.android.database.CursorWindow.nativeGetString(Native Method)
at io.requery.android.database.CursorWindow.getString(CursorWindow.java:269)
at io.requery.android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:57)
at com.ichi2.libanki.Finder._findCardsForCardBrowser(Finder.java:1048)
at com.ichi2.libanki.Finder.findCardsForCardBrowser(Finder.java:1014)
at com.ichi2.libanki.Collection.findCardsForCardBrowser(Collection.java:1104)
at com.ichi2.async.DeckTask.doInBackgroundSearchCards(DeckTask.java:622)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:253)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:66)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)

**Comment by mikehardy** [comment]
Would you be able to describe your exact path from starting AnkiDroid until the crash happened? Are you able to share your exported collection anywhere (either attached here or uploaded somewhere)? If it has personal information and you don't want to share it, I understand

**Comment by mikehardy** [comment]
Also, please make sure you update to 2.8.4 and see if you can reproduce, 2.8.3 changed the database interaction just a little bit

**Comment by goxykzd** [comment]
不好意思，原来我已升级到了2.84，这是在2.84下出现的状况。

**Comment by mikehardy** [comment]
Strange. I can see you tried to run the database integrity check and that failed as well. Something appears to be wrong with your database but the integrity check is needed to fix it.

I can only think of two ways to get you working again:
- make sure you are synced with Anki web and have a good backup of /sdcard/AnkiDroid!
- completely remove the app, including /sdcard/AnkiDroid (that's where your database is)
- install the app again, re-sync from Anki web

If you did not sync with the Anki web servers so you can't do that safely, then you should try one of the new alpha builds - they have an updated version of sqlite that may help with this, though I have to admit I don't think it will fix it.

A final thing that may help is to copy /sdcard/AnkiDroid/collection.anki2 to a desktop computer, downloading a sqlite front-end, and trying to repair it that way - this is an example of a front-end that could work http://sqlitebrowser.org/

**Comment by mikehardy** [comment]
So if I understand correctly, you deleted the app and /sdcard/AnkiDroid, re-installed, then imported the apkg, and the problem still occurs?

Is it possible to delete the app and /sdcard/AnkiDroid, then instead of importing, doing a sync down from AnkiWeb to get the data to AnkiDroid?

There are only 4 ways to get data into AnkiDroid that I know of:

1- adding manually (29,000 cards? no way)
2- direct copy of known-good folder (risky, and your database appears bad)
3- import (you just tried that, no idea why it did not work, maybe corrupt earlier?)
4- sync from AnkiWeb

I think we're down to the last attempt...
