### ISSUE TITLE
Deprecation - use new ClipboardManager from android.content

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5023]
Clipboard APIs have moved from a single ASCII text item to a possible collection of localized text or binary objects, and it's complicated a bit because paths have changed to URIs backed by ContentProviders.

So this is a more involved change than it appears - especially since interop with other apps to create cards is something we support (maybe even with images or sounds). Additionally there are some bugs with various APIs that could cause crashes if not handled. So we shouldn't just try to manipulate default-charset text into the first clipboard entry even though that's the easy fix.

**Comment by mikehardy** [comment]
This is very popular - amongst the issues I closed at least one had multiple reactions which is rare for us, indicating interest.

**Comment by mikehardy** [comment]
There's a semi-frequent crash related to this, ContentProvider permissions, and modern Android (8.1 at least, maybe 7+) people sharing images that I think are copied onto Clipboard from within Anki?

android.os.FileUriExposedException: file:///storage/emulated/0/Pictures/img_201810212235177493661074244408991.jpg exposed beyond app through ClipData.Item.getUri()
at android.os.StrictMode.onFileUriExposed(StrictMode.java:1960)
at android.net.Uri.checkFileUriExposed(Uri.java:2356)
at android.content.ClipData.prepareToLeaveProcess(ClipData.java:942)
at android.content.Intent.prepareToLeaveProcess(Intent.java:9861)
at android.content.Intent.prepareToLeaveProcess(Intent.java:9846)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1612)
at android.app.Activity.startActivityForResult(Activity.java:4559)
at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
at android.app.Activity.startActivityForResult(Activity.java:4517)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
at com.ichi2.anki.AnkiActivity.startActivityForResult(AnkiActivity.java:175)
at com.ichi2.anki.multimediacard.fields.BasicImageFieldController$2.onClick(BasicImageFieldController.java:125)
at android.view.View.performClick(View.java:6312)
at android.view.View$PerformClick.run(View.java:24811)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6637)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:822)

**Comment by mikehardy** [comment]
If combined well with #1699 ("generic dictionary lookup support") where I was thinking we could have a list of pre-loaded dictionary providers but in general just have a URL editor with variable interpolation for the query to perform, then we could also send people out to "image dictionaries" (like google image search) and then with cut-n-paste working correctly they could paste the definition or they could paste an image back in

**Comment by ummmcam** [comment]
On AnkiDroid running on Chrome OS: creating a screenshot (ctrl+shift+[switch]) brings up dialogue to copy the captured image to the clipboard. Once copied it would be very helpful to be able to paste it into the add card dialogue. Right now on ChromeOS the add from gallery function is very cumbersome. This would be a profound enhancement.

**Comment by david-allison-1** [comment]
Hi @ummmcam, thanks for the suggestion, sounds good!

That feature wouldn't be implemented as part of this issue, could you create a new issue for the feature request?

Would you be willing to submit a pull request to implement this functionality?

**Comment by mikehardy** [comment]
Actually it might be, porting to the new ClipBoard API might get binary blob paste for free - or so close to it during the forward port that it is trivial to do at same time - by my memory of the API when I initially scanned it
