### ISSUE TITLE
Sharing exported collection not working

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5029]
###### Reproduction Steps

1. export collection from deck picker
2. answer yes to the popup about sending it to another application

###### Expected Result

Selection of applications is presented, or a dialog at least informing the user no suitable application is found

###### Actual Result

1- if no suitable application are installed, it silently fails with just a log message visible in adb
2- if there are applications, it appears to crash? (in Android 8.1 at least)
3- a third case (unknown reproduction or device) it appears to send an email but with no attachment

java.lang.SecurityException: UID 10272 does not have permission to content://com.ichi2.anki.apkgfileprovider/export-directory/collection.apkg [user 0]
at android.os.Parcel.readException(Parcel.java:2005)
at android.os.Parcel.readException(Parcel.java:1951)
at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:4390)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1797)
at android.app.Activity.startActivityForResult(Activity.java:4514)
at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
at android.app.Activity.startActivityForResult(Activity.java:4472)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:732)
at com.ichi2.anki.AnkiActivity.startActivityForResult(AnkiActivity.java:174)
at android.app.Activity.startActivity(Activity.java:4833)
at android.app.Activity.startActivity(Activity.java:4801)
at com.ichi2.anki.AnkiActivity.startActivityWithoutAnimation(AnkiActivity.java:159)
at com.ichi2.anki.DeckPicker.emailFile(DeckPicker.java:1665)
at com.ichi2.anki.dialogs.DeckPickerExportCompleteDialog.lambda$onCreateDialog$0(DeckPickerExportCompleteDialog.java:37)
at com.ichi2.anki.dialogs.-$$Lambda$DeckPickerExportCompleteDialog$R3-uh335MmJZJTJEVYXfKJSSy6E.onClick(Unknown Source:4)
at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:410)
at android.view.View.performClick(View.java:6367)
at android.view.View$PerformClick.run(View.java:25032)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6753)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by mikehardy** [comment]
@timrae - can you share collections at all? Curious if all my devices have gone bonkers or if there are a lot of problems here - this is unexpected

**Comment by mikehardy** [comment]
Good to hear it works somewhere, I'll API/device bisect and see what's going on. Thanks for checking that

**Comment by mikehardy** [comment]
#5054 would fix case 1 (attempt to export, but no handlers)

**Comment by david-allison-1** [comment]
I'd like to keep this open, but with a note that anyone looking at this will need to test the cases above and confirm the ones that are still problematic.

**Comment by Crewe** [comment]
I have tried to reproduce the error, but I don't see it. It is also a fresh of Android 9 on a Pixel 4.
Searched verbose log for 'export', and it says it was successful.
```
2021-05-18 21:02:17.991 1960-3633/? W/BroadcastQueue: Permission Denial: broadcasting Intent { act=com.google.android.checkin.CHECKIN_COMPLETE flg=0x1000010 (has extras) } from com.google.android.gms (pid=7533, uid=10014) is not exported from uid 10036 due to receiver com.android.vending/com.google.android.finsky.checkin.CheckinReceiver
2021-05-18 21:03:40.297 3736-3736/com.ichi2.anki I/DeckPicker: DeckPicker:: Export collection button pressed
2021-05-18 21:03:40.415 3736-3736/com.ichi2.anki D/UsageAnalytics: sendAnalyticsScreenView(): ExportDialog
2021-05-18 21:03:42.882 3736-9380/com.ichi2.anki D/CollectionTask$ExportApkg: doInBackgroundExportApkg
2021-05-18 21:03:42.882 3736-9380/com.ichi2.anki I/AnkiPackageExporter: Starting export into /storage/emulated/0/Android/data/com.ichi2.anki/cache/export/collection-20210518210342.colpkg
2021-05-18 21:03:44.769 3736-3736/com.ichi2.anki I/DeckPicker$ExportListener: Export successful
2021-05-18 21:03:44.791 3736-3736/com.ichi2.anki D/UsageAnalytics: sendAnalyticsScreenView(): DeckPickerExportCompleteDialog
```
![image](https://user-images.githubusercontent.com/140502/118742725-f7272700-b81e-11eb-890b-5adbbafdfee5.png)

**Comment by Crewe** [comment]
@mikehardy Any thoughts on this?

**Comment by mikehardy** [comment]
If it cannot be reproduced it is maybe fixed? I'll close it. We can open new issues needed
