### ISSUE TITLE
Media sync crashes

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5060]
###### Reproduction Steps

1. SSL error during sync (connection reset), or
2. Zip file corrupted during sync, or
3. download a large file?

###### Expected Result

Nice dialog message with error

###### Actual Result

Crashes:

```
java.lang.NullPointerException: magnitude == null
at java.math.BigInteger.<init>(BigInteger.java:271)
at com.ichi2.libanki.Utils.fileChecksum(Utils.java:564)
at com.ichi2.libanki.Media.addFilesFromZip(Media.java:896)
at com.ichi2.libanki.sync.MediaSyncer._downloadFiles(MediaSyncer.java:241)
at com.ichi2.libanki.sync.MediaSyncer.sync(MediaSyncer.java:167)
```

or
```
javax.net.ssl.SSLException: Read error: ssl=0x977cc3c0: I/O error during system call, Software caused connection abort
at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
at com.android.org.conscrypt.SslWrapper.read(SslWrapper.java:384)
at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:541)
at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:108)
at org.apache.http.impl.io.AbstractSessionInputBuffer.read(AbstractSessionInputBuffer.java:139)
at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:166)
at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:180)
at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:183)
at com.ichi2.libanki.sync.HttpSyncer.writeToFile(HttpSyncer.java:266)
at com.ichi2.libanki.sync.RemoteMediaServer.downloadFiles(RemoteMediaServer.java:119)
at com.ichi2.libanki.sync.MediaSyncer._downloadFiles(MediaSyncer.java:240)
at com.ichi2.libanki.sync.MediaSyncer.sync(MediaSyncer.java:167)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:397)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:197)
```

```
Caused by: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack available
java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack available
at com.ichi2.libanki.sync.MediaSyncer._downloadFiles(MediaSyncer.java:240)
at com.ichi2.libanki.sync.MediaSyncer.sync(MediaSyncer.java:167)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:397)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:197)
at com.ichi2.async.Connection.doInBackground(Connection.java:187)
at com.ichi2.async.Connection.doInBackground(Connection.java:53)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
```

**Comment by mikehardy** [comment]
```
java.io.IOException: No such file or directory
at java.io.UnixFileSystem.createFileExclusively0(Native Method)
at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
at java.io.File.createNewFile(File.java:1000)
at com.ichi2.libanki.Utils.writeToFile(Utils.java:697)
at com.ichi2.libanki.Media.addFilesFromZip(Media.java:895)
at com.ichi2.libanki.sync.MediaSyncer._downloadFiles(MediaSyncer.java:241)
at com.ichi2.libanki.sync.MediaSyncer.sync(MediaSyncer.java:167)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:388)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:188)
at com.ichi2.async.Connection.doInBackground(Connection.java:178)
at com.ichi2.async.Connection.doInBackground(Connection.java:50)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
```

**Comment by mikehardy** [comment]
Not sure how it comes out as a transaction too large, but:

```
android.os.TransactionTooLargeException: data parcel size 1136844 bytes
at android.os.BinderProxy.transactNative(Native Method)
at android.os.BinderProxy.transact(Binder.java:761)
at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:5157)
at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4146)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6938)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
at com.ichi2.libanki.sync.MediaSyncer._downloadFiles(MediaSyncer.java:240)
at com.ichi2.libanki.sync.MediaSyncer.sync(MediaSyncer.java:167)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:388)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:188)
at com.ichi2.async.Connection.doInBackground(Connection.java:178)
at com.ichi2.async.Connection.doInBackground(Connection.java:50)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
at java.util.zip.ZipFile.open(Native Method)
at java.util.zip.ZipFile.<init>(ZipFile.java:235)
at java.util.zip.ZipFile.<init>(ZipFile.java:149)
at com.ichi2.libanki.sync.RemoteMediaServer.downloadFiles(RemoteMediaServer.java:120)
at com.ichi2.libanki.sync.MediaSyncer.sync(MediaSyncer.java:167)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:388)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:188)
at com.ichi2.async.Connection.doInBackground(Connection.java:178)
at com.ichi2.async.Connection.doInBackground(Connection.java:50)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
at com.ichi2.libanki.Utils.writeToFile(Utils.java:725)
at com.ichi2.libanki.Media.addFilesFromZip(Media.java:895)
at com.ichi2.libanki.sync.MediaSyncer._downloadFiles(MediaSyncer.java:241)
Caused by: java.io.IOException: No such file or directory
at java.io.UnixFileSystem.createFileExclusively0(Native Method)
at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
at java.io.File.createNewFile(File.java:1000)
at com.ichi2.libanki.Utils.writeToFile(Utils.java:697)
... 13 more
at com.ichi2.libanki.Media.addFilesFromZip(Media.java:895)
at com.ichi2.libanki.sync.MediaSyncer._downloadFiles(MediaSyncer.java:241)
at com.ichi2.libanki.sync.MediaSyncer.sync(MediaSyncer.java:167)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:388)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:188)
```

**Comment by mikehardy** [comment]
This one is interesting because it's the same IOException, but this one has enough information it we could present it to the user and they could resolve it if we surfaced the message! File name too long

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/cac5463a-c27b-473f-9cdf-189aff28e167

```
java.io.IOException: Aussprache_von_海带凉拌菜做法超级简单，不过务必将海带多泡些时间，不然不易消化。_Wie_man_海带凉拌菜做法超级简单，不过务必将海带多泡些时间，不然不易消化。_auf_Chinesisch_ausspricht_5d8660bcd.mp3: File name too long
at com.ichi2.libanki.Utils.writeToFile(Utils.java:725)
at com.ichi2.libanki.Media.addFilesFromZip(Media.java:895)
at com.ichi2.libanki.sync.MediaSyncer._downloadFiles(MediaSyncer.java:241)
at com.ichi2.libanki.sync.MediaSyncer.sync(MediaSyncer.java:167)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:388)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:188)
at com.ichi2.async.Connection.doInBackground(Connection.java:178)
at com.ichi2.async.Connection.doInBackground(Connection.java:50)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.io.IOException: File name too long
at java.io.UnixFileSystem.createFileExclusively0(Native Method)
at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
at java.io.File.createNewFile(File.java:1008)
at com.ichi2.libanki.Utils.writeToFile(Utils.java:697)
... 13 more
java.io.IOException: File name too long
at java.io.UnixFileSystem.createFileExclusively0(Native Method)
at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
at java.io.File.createNewFile(File.java:1008)
at com.ichi2.libanki.Utils.writeToFile(Utils.java:697)
at com.ichi2.libanki.Media.addFilesFromZip(Media.java:895)
at com.ichi2.libanki.sync.MediaSyncer._downloadFiles(MediaSyncer.java:241)
at com.ichi2.libanki.sync.MediaSyncer.sync(MediaSyncer.java:167)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:388)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:188)
at com.ichi2.async.Connection.doInBackground(Connection.java:178)
at com.ichi2.async.Connection.doInBackground(Connection.java:50)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
```

**Comment by mikehardy** [comment]
I actually saw this on a Moto G Play yesterday from a friend and had a USB cable nearby in order to try debugging. I ran out of time, but basically it was just failing media sync for no reason that I could tell. It would write a few files then the OS would start rejecting it with permission errors. I used adb shell in order `chmod -R 777 /sdcard/AnkiDroid` (which was on internal storage, for what it's worth) and that would allow large sections of the media catalog to sync but then it would recur. No root cause yet. No real fix yet.

**Comment by david-allison-1** [comment]
Voting to keep this one open - probably needs to be split into separate issues, but there are lots of UX improvements that can be had here.

One of the common issues right now is stopping the sync due to AnkiWeb rejecting 0 byte files.

**Comment by dae** [comment]
Should be fixed with the backend switchover.
