### ISSUE TITLE
Error occurred while accessing your collection

### ISSUE THREAD

**Issue by dchurchward** [ankidroid/Anki-Android#5071]
###### Reproduction Steps

1. On Android device, download apkg file from shared Google Drive folder.
2. 
3. 

###### Expected Result
File normally imports fine, with a popup saying how many cards have been added. 

###### Actual Result
Popup appears, with no text - just the popup. Deck has not imported. The next time I open Anki, I get an error message: "an error occurred while accessing your collection" etc. Cannot run check database as popup suggests because there is no deck list; backups are not recognised as valid apkg files; full sync from server seems to download, but leads back to the same popup. Uninstalling and reinstalling Ankidroid does not fix issue.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.8.4

Android Version = 7.0

ACRA UUID = d850d5ed-6f08-4dd0-a923-094997fe86f5

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hi there! Sorry you've run into trouble, but thank you for including all the requested troubleshooting information. I can see 23 different crash dumps from you, indicating you have really been struggling with this.

Unfortunately, the crash indicates that the database had a serious problem. I'm not sure what caused it, but I'm reasonably certain it will be very hard to recover from using this database.

If you were in sync with AnkiWeb (or even reasonably in sync - not losing much review time), the quickest resolution is going to be uninstalling ankidroid, deleting /sdcard/AnkiDroid (wiping out the data on your phone! careful!) then reinstalling and syncing down from anki web.

If you are not in sync with ankiweb then the closest approximation is to delete /sdccard/AnkiDroid/collection*, then restart and import from the most recent backup - this will also reset the database.

I'll paste in the stack trace below, but "database is locked" is something I personally don't have experience recovering from other than to wipe and re-sync...

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.Preferences}: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6123)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
at io.requery.android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at io.requery.android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:921)
at io.requery.android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:658)
at io.requery.android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:342)
at io.requery.android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:315)
at io.requery.android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:232)
at io.requery.android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:207)
at io.requery.android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:467)
at io.requery.android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:188)
at io.requery.android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:180)
at io.requery.android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:851)
at io.requery.android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:820)
at io.requery.android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:697)
at com.ichi2.libanki.DB.<init>(DB.java:64)
at com.ichi2.libanki.Media.connect(Media.java:142)
at com.ichi2.libanki.Media.<init>(Media.java:129)
at com.ichi2.libanki.Collection.<init>(Collection.java:147)
at com.ichi2.libanki.Storage.Collection(Storage.java:63)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:99)
at com.ichi2.anki.Preferences.getCol(Preferences.java:133)
at com.ichi2.anki.Preferences.initPreference(Preferences.java:401)
at com.ichi2.anki.Preferences.initAllPreferences(Preferences.java:387)
at com.ichi2.anki.Preferences.access$200(Preferences.java:90)
at com.ichi2.anki.Preferences$SettingsFragment.onCreate(Preferences.java:793)
at android.app.Fragment.performCreate(Fragment.java:2335)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:949)
at android.app.BackStackRecord.setLastIn(BackStackRecord.java:857)
at android.app.BackStackRecord.calculateFragments(BackStackRecord.java:897)
at android.app.BackStackRecord.run(BackStackRecord.java:727)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1580)
at android.app.FragmentController.execPendingActions(FragmentController.java:371)
at android.app.Activity.performStart(Activity.java:6688)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2622)
... 9 more
android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
at io.requery.android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at io.requery.android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:921)
at io.requery.android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:658)
at io.requery.android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:342)
at io.requery.android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:315)
at io.requery.android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:232)
at io.requery.android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:207)
at io.requery.android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:467)
at io.requery.android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:188)
at io.requery.android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:180)
at io.requery.android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:851)
at io.requery.android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:820)
at io.requery.android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:697)
at com.ichi2.libanki.DB.<init>(DB.java:64)
at com.ichi2.libanki.Media.connect(Media.java:142)
at com.ichi2.libanki.Media.<init>(Media.java:129)
at com.ichi2.libanki.Collection.<init>(Collection.java:147)
at com.ichi2.libanki.Storage.Collection(Storage.java:63)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:99)
at com.ichi2.anki.Preferences.getCol(Preferences.java:133)
at com.ichi2.anki.Preferences.initPreference(Preferences.java:401)
at com.ichi2.anki.Preferences.initAllPreferences(Preferences.java:387)
at com.ichi2.anki.Preferences.access$200(Preferences.java:90)
at com.ichi2.anki.Preferences$SettingsFragment.onCreate(Preferences.java:793)
at android.app.Fragment.performCreate(Fragment.java:2335)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:949)
at android.app.BackStackRecord.setLastIn(BackStackRecord.java:857)
at android.app.BackStackRecord.calculateFragments(BackStackRecord.java:897)
at android.app.BackStackRecord.run(BackStackRecord.java:727)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1580)
at android.app.FragmentController.execPendingActions(FragmentController.java:371)
at android.app.Activity.performStart(Activity.java:6688)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2622)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6123)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by dchurchward** [comment]
Hi Mike,
Fortunately, I had quite a recent backup file. Just saved that to GDrive, deleted the collection, and re-downloaded everything. Only lost about an hour of review, I think; all seems to be working now.
Thanks for the prompt reply!

**Comment by mikehardy** [comment]
Really glad that was okay, any idea what on the devices could have done that? Out of space? Totally out of power while reviewing? Odd corruption

**Comment by mikehardy** [comment]
I'm going to close this, but if you have any supporting information that led to the corruption it may be useful for the future. Cheers
