### ISSUE TITLE
DialogHandler assumes it was started by DeckPicker, may crash otherwise

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5075]
###### Reproduction Steps

1. Open AnkiDroid via a Reviewer-first pathway?
2. request file import?
3. 

###### Expected Result

Import dialog is shown

###### Actual Result

ClassCastException because import dialog is spawned from Reviewer somehow, instead of DeckPicker?
```
java.lang.ClassCastException: com.ichi2.anki.Reviewer cannot be cast to com.ichi2.anki.DeckPicker
at com.ichi2.anki.dialogs.DialogHandler.handleMessage(DialogHandler.java:82)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6501)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by mikehardy** [comment]
These are all the uses of the constant that could hit that case in the switch statement:

```
mike@isabela:~/work/AnkiDroid/Anki-Android (master) % grep -r 'new DialogHandler' *
AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java:    private DialogHandler mHandler = new DialogHandler(this);
mike@isabela:~/work/AnkiDroid/Anki-Android (master) % grep -r DIALOG_IMPORT_ADD_CONFIRM
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.java:            ((DeckPicker) mActivity.get()).showImportDialog(ImportDialog.DIALOG_IMPORT_ADD_CONFIRM, msgData.getString("importPath"));
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.java:    public static final int DIALOG_IMPORT_ADD_CONFIRM = 2;
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.java:                                    ((ImportDialogListener) getActivity()).showImportDialog(DIALOG_IMPORT_ADD_CONFIRM, importPath);
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.java:            case DIALOG_IMPORT_ADD_CONFIRM: {
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:                || (id == ImportDialog.DIALOG_IMPORT_ADD_CONFIRM)

```

**Comment by mikehardy** [comment]
This just showed up with MyAccount cannot be cast to DeckPicker

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/3c387372-bba0-49c7-973a-33eb17237fc3

```
java.lang.ClassCastException: com.ichi2.anki.MyAccount cannot be cast to com.ichi2.anki.DeckPicker
at com.ichi2.anki.dialogs.DialogHandler.handleMessage(DialogHandler.java:6)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:176)
at android.app.ActivityThread.main(ActivityThread.java:6635)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Comment by david-allison-1** [comment]
<details> <summary> Theory: caused by a static in `DialogHandler` and `onResume()`</summary>

A new DialogHandler is spawned on each AnkiActivity: 

https://github.com/ankidroid/Anki-Android/blob/d3a6c61ac791d48fe2c684a6302640237968814a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java#L46

This references a static `sStoredMessage`

https://github.com/ankidroid/Anki-Android/blob/f297f3c06829442466e21103a112c3202652e410/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.java#L62

Which is read `onResume`.

https://github.com/ankidroid/Anki-Android/blob/d3a6c61ac791d48fe2c684a6302640237968814a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java#L81

So: Store Message -> Change Activity -> Pause -> Resume -> Handle message on incorrect activity.


</details>

**Comment by david-allison-1** [comment]
Managed to trigger this. Don't have the exact steps. Debug Stack (with a few Huawei specific entries removed):

Caused by selecting a file in a file manager while AnkiDroid is running

<details><summary>Stack Trace</summary>
```
2020-04-02 08:07:36.794 20682-20682/? I/com.ichi2.anki: Late-enabling -Xcheck:jni
2020-04-02 08:07:36.843 20682-20682/? I/com.ichi2.anki: Reinit property: dalvik.vm.checkjni= false
2020-04-02 08:07:37.006 20682-20698/? I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.ichi2.anki#10262#256
2020-04-02 08:07:37.008 20682-20698/? I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.ichi2.anki#10262#0
2020-04-02 08:07:37.714 20682-20698/com.ichi2.anki I/AwareBitmapCacher: init processName:com.ichi2.anki pid=20682 uid=10262
2020-04-02 08:07:37.969 20682-20682/com.ichi2.anki I/ACRA: ACRA is disabled for com.ichi2.anki, initializing...
2020-04-02 08:07:38.122 20682-20682/com.ichi2.anki I/AnkiDroid: initialize()
2020-04-02 08:07:38.214 20682-20682/com.ichi2.anki W/com.ichi2.anki: Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, reflection)
2020-04-02 08:07:38.214 20682-20682/com.ichi2.anki W/com.ichi2.anki: Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, reflection)
2020-04-02 08:07:38.214 20682-20682/com.ichi2.anki W/com.ichi2.anki: Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
2020-04-02 08:07:38.225 20682-20682/com.ichi2.anki I/GoogleAnalyticsImpl: Not participating in analytics sample (sample percentage vs random: 10 50)
2020-04-02 08:07:38.228 20682-20682/com.ichi2.anki I/UsageAnalytics: setOptIn(): from false to false
2020-04-02 08:07:38.228 20682-20682/com.ichi2.anki I/GoogleAnalyticsImpl: Not participating in analytics sample (sample percentage vs random: 10 97)
2020-04-02 08:07:38.232 20682-20682/com.ichi2.anki I/UsageAnalytics: setDryRun(): true, warning dryRun is experimental
2020-04-02 08:07:38.260 20682-20682/com.ichi2.anki I/CompatV26: Creating notification channel with id/name: General Notifications/AnkiDroid
2020-04-02 08:07:38.271 20682-20682/com.ichi2.anki I/CompatV26: Creating notification channel with id/name: Synchronization/同步
2020-04-02 08:07:38.456 20682-20682/com.ichi2.anki I/CompatV26: Creating notification channel with id/name: Global Reminders/卡片到期
2020-04-02 08:07:38.460 20682-20682/com.ichi2.anki I/CompatV26: Creating notification channel with id/name: Deck Reminders/提醒
2020-04-02 08:07:38.529 20682-20682/com.ichi2.anki I/WebViewFactory: Loading com.android.chrome version 80.0.3987.149 (code 398714932)
2020-04-02 08:07:38.661 20682-20682/com.ichi2.anki I/cr_LibraryLoader: Loaded native library version number "80.0.3987.149"
2020-04-02 08:07:38.738 20682-20682/com.ichi2.anki I/CollectionHelper: openCollection: /storage/emulated/0/2/collection.anki2
2020-04-02 08:07:39.101 20682-20698/com.ichi2.anki E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
2020-04-02 08:07:39.150 20682-20682/com.ichi2.anki I/HwApsImpl: APS: new HwApsImpl created
2020-04-02 08:07:39.168 20682-20682/com.ichi2.anki I/HwPhoneWindow: updateLayoutParamsColor false mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=0, mNavBarShow=false, mIsFloating=false
2020-04-02 08:07:39.170 20682-20682/com.ichi2.anki I/HwPhoneWindow: updateLayoutParamsColor true mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=ff000000, mNavBarShow=false, mIsFloating=false
2020-04-02 08:07:39.196 20682-20682/com.ichi2.anki I/ImportUtils: IntentHandler/ User requested to view a file
2020-04-02 08:07:39.214 20682-20682/com.ichi2.anki I/ImportUtils: Intent: Intent { act=android.intent.action.VIEW dat=content://com.huawei.hidisk.fileprovider/root/storage/emulated/0/Chinese_Sentences_and_audio_spoon_fed.apkg typ=application/* flg=0x13400003 cmp=com.ichi2.anki/.IntentHandler (has extras) }. Data: is_samba, open_type
2020-04-02 08:07:39.215 20682-20682/com.ichi2.anki I/ImportUtils: Attempting to read content from intent.
2020-04-02 08:07:42.179 20682-20781/com.ichi2.anki E/ZrHungImpl:  sendAppFreezeEvent failed!
2020-04-02 08:07:45.181 20682-20781/com.ichi2.anki E/ZrHungImpl:  sendAppFreezeEvent failed!
2020-04-02 08:07:48.128 20682-20682/com.ichi2.anki W/com.ichi2.anki: Accessing hidden method Landroid/graphics/drawable/Drawable;->getOpticalInsets()Landroid/graphics/Insets; (light greylist, linking)
2020-04-02 08:07:48.128 20682-20682/com.ichi2.anki W/com.ichi2.anki: Accessing hidden field Landroid/graphics/Insets;->left:I (light greylist, linking)
2020-04-02 08:07:48.128 20682-20682/com.ichi2.anki W/com.ichi2.anki: Accessing hidden field Landroid/graphics/Insets;->right:I (light greylist, linking)
2020-04-02 08:07:48.128 20682-20682/com.ichi2.anki W/com.ichi2.anki: Accessing hidden field Landroid/graphics/Insets;->top:I (light greylist, linking)
2020-04-02 08:07:48.128 20682-20682/com.ichi2.anki W/com.ichi2.anki: Accessing hidden field Landroid/graphics/Insets;->bottom:I (light greylist, linking)
2020-04-02 08:07:48.184 20682-20781/com.ichi2.anki E/ZrHungImpl:  sendAppFreezeEvent failed!
2020-04-02 08:07:48.480 20682-20682/com.ichi2.anki W/com.ichi2.anki: Accessing hidden method Landroid/widget/TextView;->getTextDirectionHeuristic()Landroid/text/TextDirectionHeuristic; (light greylist, linking)
2020-04-02 08:07:48.515 20682-20682/com.ichi2.anki W/com.ichi2.anki: Accessing hidden method Landroid/widget/PopupWindow;->setEpicenterBounds(Landroid/graphics/Rect;)V (light greylist, linking)
2020-04-02 08:07:48.518 20682-20682/com.ichi2.anki W/com.ichi2.anki: Accessing hidden method Landroid/widget/PopupWindow;->setClipToScreenEnabled(Z)V (light greylist, reflection)
2020-04-02 08:07:51.188 20682-20781/com.ichi2.anki E/ZrHungImpl:  sendAppFreezeEvent failed!
2020-04-02 08:07:52.184 20682-20682/com.ichi2.anki I/DeckTask: Cancelled task 30
2020-04-02 08:07:52.197 20682-20682/com.ichi2.anki I/DialogHandler: Dispatching persistent message: 2
2020-04-02 08:07:52.259 20682-20682/com.ichi2.anki I/Choreographer: Skipped 219 frames!  The application may be doing too much work on its main thread.
2020-04-02 08:07:52.296 20682-20682/com.ichi2.anki I/DeckTask: Cancelled task 30
2020-04-02 08:07:52.395 20682-20821/com.ichi2.anki I/Finder: _findCardsForCardBrowser() cancelled...
2020-04-02 08:07:52.723 20682-20682/com.ichi2.anki W/com.ichi2.anki: Accessing hidden method Landroid/graphics/drawable/DrawableContainer;->getOpticalInsets()Landroid/graphics/Insets; (light greylist, reflection)
2020-04-02 08:07:52.743 20682-20688/com.ichi2.anki I/com.ichi2.anki: Compiler allocated 4MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
2020-04-02 08:07:52.815 20682-20682/com.ichi2.anki I/Choreographer: Skipped 31 frames!  The application may be doing too much work on its main thread.
2020-04-02 08:07:52.930 20682-20682/com.ichi2.anki I/DeckTask: Cancelled task 30
2020-04-02 08:07:52.978 20682-20682/com.ichi2.anki I/DeckTask: Cancelled task 30
2020-04-02 08:07:53.032 20682-20682/com.ichi2.anki W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@432f1b
2020-04-02 08:07:53.061 20682-20682/com.ichi2.anki I/ViewRootImpl: jank_removeInvalidNode jank list is null
2020-04-02 08:07:53.447 20682-20682/com.ichi2.anki I/DialogHandler: Handling Message: ImportAddDialog
2020-04-02 08:07:53.484 20682-20682/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 20682
    java.lang.ClassCastException: com.ichi2.anki.CardBrowser cannot be cast to com.ichi2.anki.DeckPicker
        at com.ichi2.anki.dialogs.DialogHandler.handleMessage(DialogHandler.java:85)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```
</details>

**Comment by david-allison-1** [comment]
This is my white whale. I want to get a good reproduction case. I've added activity lifecycle logging to ACRA, so we can track this down

**Comment by david-allison** [comment]
DialogHandler needs to be rewritten to use modern mechanisms

Before this is done, we could trivially check whether `DeckPicker` is receiving the message, and if not, launching it.

https://github.com/ankidroid/Anki-Android/blob/be62538feb721b838c3fab2a10873404f0b0e6ad/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt#L37-L43

**Comment by lukstbit** [comment]
I think I might be able to fix this through a refactor but this is not going to come in any 2.17.x releases.

**Comment by mikehardy** [comment]
This is currently one of our hottest crash issues from the permissions dialog getting people that have revoked permissions:

```

Stacktrace (No mapping found)
java.lang.ClassCastException: com.ichi2.anki.ui.windows.permissions.PermissionsActivity cannot be cast to com.ichi2.anki.DeckPicker
	at com.ichi2.anki.dialogs.DatabaseErrorDialog$UninstallListItem$4.invoke(SourceFile:2)
	at com.ichi2.anki.dialogs.DatabaseErrorDialog$UninstallListItem$4.invoke(SourceFile:1)
	at com.ichi2.anki.ui.windows.permissions.AndroidPermanentlyRevokedPermissionsDialog$show$1$2.invoke(SourceFile:3)
	at com.ichi2.anki.ui.windows.permissions.AndroidPermanentlyRevokedPermissionsDialog$show$1$2.invoke(SourceFile:1)
	at com.afollestad.materialdialogs.internal.list.PlainListDialogAdapter.itemClicked(SourceFile:76)
	at com.afollestad.materialdialogs.internal.list.PlainListViewHolder.onClick(SourceFile:12)
	at android.view.View.performClick(View.java:8043)
	at android.view.View.performClickInternal(View.java:8020)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31850)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

https://ankidroid.org/acra/app/1/bug/144963/report/2d02dc66-dd59-44a3-82b2-3ed56270a86a

```
--------- beginning of main
05-27 09:46:39.432 I/AnkiDroid(27212): PermissionsActivity::onPause
05-27 09:46:39.432 I/AnkiDroid(27212): PermissionsActivity::PermissionsUntil29Fragment::onPause
05-27 09:46:39.434 I/AnkiDroid(27212): PermissionsActivity::onStop
05-27 09:46:39.436 I/AnkiDroid(27212): PermissionsActivity::PermissionsUntil29Fragment::onStop
05-27 09:46:39.439 I/AnkiDroid(27212): PermissionsActivity::onSaveInstanceState
05-27 09:46:39.440 I/AnkiDroid(27212): PermissionsActivity::PermissionsUntil29Fragment::onSaveInstanceState
05-27 09:46:39.440 I/AnkiDroid(27212): PermissionsActivity::onDestroy
05-27 09:46:39.441 I/AnkiDroid(27212): PermissionsActivity::PermissionsUntil29Fragment::onViewDestroyed
05-27 09:46:39.442 I/AnkiDroid(27212): PermissionsActivity::PermissionsUntil29Fragment::onDestroy
05-27 09:46:39.442 I/AnkiDroid(27212): PermissionsActivity::PermissionsUntil29Fragment::onDetach
05-27 09:46:39.487 I/AnkiDroid(27212): Setting theme to LIGHT
05-27 09:46:39.494 I/AnkiDroid(27212): PermissionsActivity::onCreate
05-27 09:46:39.494 I/AnkiDroid(27212): PermissionsActivity::PermissionsUntil29Fragment::onAttach
05-27 09:46:39.494 I/AnkiDroid(27212): PermissionsActivity::PermissionsUntil29Fragment::onCreate
05-27 09:46:39.495 I/AnkiDroid(27212): Setting theme to LIGHT
05-27 09:46:39.507 I/AnkiDroid(27212): PermissionsActivity::onStart
05-27 09:46:39.518 I/AnkiDroid(27212): PermissionsActivity::PermissionsUntil29Fragment::onViewCreated
05-27 09:46:39.518 I/AnkiDroid(27212): PermissionsActivity::PermissionsUntil29Fragment::onAttach
05-27 09:46:39.519 I/AnkiDroid(27212): PermissionsActivity::PermissionsUntil29Fragment::onCreate
05-27 09:46:39.523 I/AnkiDroid(27212): PermissionsActivity::PermissionsUntil29Fragment::onViewCreated
05-27 09:46:39.523 I/AnkiDroid(27212): PermissionsActivity::PermissionsUntil29Fragment::onViewDestroyed
05-27 09:46:39.523 I/AnkiDroid(27212): PermissionsActivity::PermissionsUntil29Fragment::onDestroy
05-27 09:46:39.523 I/AnkiDroid(27212): PermissionsActivity::PermissionsUntil29Fragment::onDetach
05-27 09:46:39.523 I/AnkiDroid(27212): PermissionsActivity::PermissionsUntil29Fragment::onStart
05-27 09:46:39.527 I/AnkiDroid(27212): PermissionsActivity::onResume
05-27 09:46:39.528 I/AnkiDroid(27212): PermissionsActivity::PermissionsUntil29Fragment::onResume
05-27 09:46:45.747 I/AnkiDroid(27212): permission switch pressed
05-27 09:47:00.007 W/AnkiDroid(27212): DayRolloverHandler/ could not check/update day rollover: collection not open
05-27 09:47:00.270 I/AnkiDroid(27212): PermissionsActivity::onPause
05-27 09:47:00.271 I/AnkiDroid(27212): PermissionsActivity::PermissionsUntil29Fragment::onPause
05-27 09:47:00.280 I/AnkiDroid(27212): PermissionsActivity::onStop
05-27 09:47:00.280 I/AnkiDroid(27212): PermissionsActivity::PermissionsUntil29Fragment::onStop
05-27 09:47:00.285 I/AnkiDroid(27212): PermissionsActivity::onSaveInstanceState
05-27 09:47:00.286 I/AnkiDroid(27212): PermissionsActivity::PermissionsUntil29Fragment::onSaveInstanceState
05-27 09:47:00.857 I/AnkiDroid(27212): DeckPicker::onDestroy
05-27 09:47:02.413 I/AnkiDroid(27753): Timber config: PRODUCTION
05-27 09:47:02.413 I/AnkiDroid(27753): initialize()
05-27 09:47:02.526 I/AnkiDroid(27753): Not participating in analytics sample (sample percentage vs random: 10 91)
05-27 09:47:02.526 I/AnkiDroid(27753): setOptIn(): from false to false
05-27 09:47:02.526 I/AnkiDroid(27753): Not participating in analytics sample (sample percentage vs random: 10 61)
05-27 09:47:02.585 I/AnkiDroid(27753): Creating notification channel with id/name: General Notifications/AnkiDroid
05-27 09:47:02.585 I/AnkiDroid(27753): Creating notification channel with id/name: Synchronization/Synchronisation
05-27 09:47:02.586 I/AnkiDroid(27753): Creating notification channel with id/name: Global Reminders/Fällige Karten
05-27 09:47:02.586 I/AnkiDroid(27753): Creating notification channel with id/name: Deck Reminders/Erinnerungen
05-27 09:47:02.587 I/AnkiDroid(27753): Creating notification channel with id/name: Scoped Storage/Datenmigration
05-27 09:47:02.589 I/AnkiDroid(27753): AnkiDroidApp: Starting Services
05-27 09:47:02.590 W/AnkiDroid(27753): AnkiDroidApp/ Boot Service did not execute - no permissions
05-27 09:47:02.604 I/AnkiDroid(27753): IntentHandler::onCreate
05-27 09:47:02.604 I/AnkiDroid(27753): Setting theme to LIGHT
05-27 09:47:02.632 I/AnkiDroid(27753): Launching DeckPicker
05-27 09:47:02.656 I/AnkiDroid(27753): AnkiDroid Version = 2.18.0 (464cf290cc77c3f2c562cb03b408b78a13be261b)
05-27 09:47:02.656 I/AnkiDroid(27753): 
05-27 09:47:02.656 I/AnkiDroid(27753): Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)
05-27 09:47:02.656 I/AnkiDroid(27753): 
05-27 09:47:02.656 I/AnkiDroid(27753): Android Version = 14 (SDK 34)
05-27 09:47:02.656 I/AnkiDroid(27753): 
05-27 09:47:02.656 I/AnkiDroid(27753): ProductFlavor = play
05-27 09:47:02.656 I/AnkiDroid(27753): 
05-27 09:47:02.656 I/AnkiDroid(27753): Manufacturer = samsung
05-27 09:47:02.656 I/AnkiDroid(27753): 
05-27 09:47:02.656 I/AnkiDroid(27753): Model = SM-A536B
05-27 09:47:02.656 I/AnkiDroid(27753): 
05-27 09:47:02.656 I/AnkiDroid(27753): Hardware = s5e8825
05-27 09:47:02.656 I/AnkiDroid(27753): 
05-27 09:47:02.656 I/AnkiDroid(27753): Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-A536B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.179 Mobile Safari/537.36
05-27 09:47:02.656 I/AnkiDroid(27753): 
05-27 09:47:02.656 I/AnkiDroid(27753): ACRA UUID = 80ee949d-2bc4-4fcc-888a-aa7962710854
05-27 09:47:02.656 I/AnkiDroid(27753): 
05-27 09:47:02.656 I/AnkiDroid(27753): FSRS Enabled = null
05-27 09:47:02.656 I/AnkiDroid(27753): 
05-27 09:47:02.656 I/AnkiDroid(27753): Crash Reports Enabled = true
05-27 09:47:02.682 I/AnkiDroid(27753): Setting theme to LIGHT
05-27 09:47:02.686 I/AnkiDroid(27753): DeckPicker::onCreate
05-27 09:47:02.740 I/AnkiDroid(27753): isLegacyStorage(): current dir: /storage/emulated/0/AnkiDroid
05-27 09:47:02.740 I/AnkiDroid(27753): scoped external dirs: /storage/emulated/0/Android/data/com.ichi2.anki/files
05-27 09:47:02.740 I/AnkiDroid(27753): scoped internal dir: /data/user/0/com.ichi2.anki/files
05-27 09:47:02.740 I/AnkiDroid(27753): isLegacyStorage(): true
05-27 09:47:02.741 I/AnkiDroid(27753): DeckPicker: postponing startup code - permission screen shown
05-27 09:47:02.760 I/AnkiDroid(27753): isLegacyStorage(): current dir: /storage/emulated/0/AnkiDroid
05-27 09:47:02.760 I/AnkiDroid(27753): scoped external dirs: /storage/emulated/0/Android/data/com.ichi2.anki/files
05-27 09:47:02.760 I/AnkiDroid(27753): scoped internal dir: /data/user/0/com.ichi2.anki/files
05-27 09:47:02.760 I/AnkiDroid(27753): isLegacyStorage(): true
05-27 09:47:02.762 W/AnkiDroid(27753): NavigationDrawerActivity/ No storage access, not enabling shortcuts
05-27 09:47:02.766 I/AnkiDroid(27753): DeckPicker::onStart
05-27 09:47:02.790 I/AnkiDroid(27753): DeckPicker::onResume
05-27 09:47:02.793 I/AnkiDroid(27753): isLegacyStorage(): current dir: /storage/emulated/0/AnkiDroid
05-27 09:47:02.793 I/AnkiDroid(27753): scoped external dirs: /storage/emulated/0/Android/data/com.ichi2.anki/files
05-27 09:47:02.793 I/AnkiDroid(27753): scoped internal dir: /data/user/0/com.ichi2.anki/files
05-27 09:47:02.794 I/AnkiDroid(27753): isLegacyStorage(): true
05-27 09:47:02.823 I/AnkiDroid(27753): DeckPicker::onPause
05-27 09:47:02.873 I/AnkiDroid(27753): Setting theme to LIGHT
05-27 09:47:02.874 I/AnkiDroid(27753): PermissionsActivity::onCreate
05-27 09:47:02.875 I/AnkiDroid(27753): Setting theme to LIGHT
05-27 09:47:02.891 I/AnkiDroid(27753): PermissionsActivity::onStart
05-27 09:47:02.892 I/AnkiDroid(27753): PermissionsActivity::PermissionsUntil29Fragment::onAttach
05-27 09:47:02.892 I/AnkiDroid(27753): PermissionsActivity::PermissionsUntil29Fragment::onCreate
05-27 09:47:02.905 I/AnkiDroid(27753): PermissionsActivity::PermissionsUntil29Fragment::onViewCreated
05-27 09:47:02.906 I/AnkiDroid(27753): PermissionsActivity::PermissionsUntil29Fragment::onStart
05-27 09:47:02.909 I/AnkiDroid(27753): PermissionsActivity::onResume
05-27 09:47:02.911 I/AnkiDroid(27753): PermissionsActivity::PermissionsUntil29Fragment::onResume
05-27 09:47:03.013 W/AnkiDroid(27753): Backend$checkMainThreadOp/ Op on UI thread: anki.i18n.GeneratedTranslations$DefaultImpls.exportingExport(SourceFile:9)
05-27 09:47:03.085 I/AnkiDroid(27753): IntentHandler::onDestroy
05-27 09:47:03.086 I/AnkiDroid(27753): DeckPicker::onStop
05-27 09:47:03.091 I/AnkiDroid(27753): DeckPicker::onSaveInstanceState
05-27 09:47:08.517 I/AnkiDroid(27753): permission switch pressed
05-27 09:47:28.001 I/AnkiDroid(27753): PermissionsActivity::onPause
05-27 09:47:28.001 I/AnkiDroid(27753): PermissionsActivity::PermissionsUntil29Fragment::onPause
05-27 09:47:28.691 I/AnkiDroid(27753): PermissionsActivity::onStop
05-27 09:47:28.692 I/AnkiDroid(27753): PermissionsActivity::PermissionsUntil29Fragment::onStop
05-27 09:47:28.696 I/AnkiDroid(27753): PermissionsActivity::onSaveInstanceState
05-27 09:47:28.697 I/AnkiDroid(27753): PermissionsActivity::PermissionsUntil29Fragment::onSaveInstanceState
05-27 09:47:43.914 I/AnkiDroid(27753): PermissionsActivity::onStart
05-27 09:47:43.914 I/AnkiDroid(27753): PermissionsActivity::PermissionsUntil29Fragment::onStart
05-27 09:47:43.920 I/AnkiDroid(27753): PermissionsActivity::onResume
05-27 09:47:43.923 I/AnkiDroid(27753): PermissionsActivity::PermissionsUntil29Fragment::onResume
05-27 09:47:44.823 I/AnkiDroid(27753): permission switch pressed
```

**Comment by mikehardy** [comment]
Has a few permutations

```
java.lang.ClassCastException: com.ichi2.anki.ui.windows.permissions.PermissionsActivity cannot be cast to com.ichi2.anki.DeckPicker
	at com.ichi2.anki.dialogs.DatabaseErrorDialog$UninstallListItem$4.invoke(SourceFile:2)
	at com.ichi2.anki.dialogs.DatabaseErrorDialog$UninstallListItem$4.invoke(SourceFile:1)
	at com.ichi2.anki.ui.windows.permissions.AndroidPermanentlyRevokedPermissionsDialog$show$1$2.invoke(SourceFile:3)
	at com.ichi2.anki.ui.windows.permissions.AndroidPermanentlyRevokedPermissionsDialog$show$1$2.invoke(SourceFile:1)
	at com.afollestad.materialdialogs.internal.list.PlainListDialogAdapter.itemClicked(SourceFile:76)
	at com.afollestad.materialdialogs.internal.list.PlainListViewHolder.onClick(SourceFile:12)
```

**Comment by mikehardy** [comment]
Tagging for a 2.18.3 release (2.18.2 is going out shortly) for at least the permanently revoked permissions dialog

**Comment by mikehardy** [comment]
@lukstbit thanks for taking a look at this - this has been such a problem for so long that literally anything that stops the crashing sensibly would be welcome
so as a first pass simply avoiding the possibility of popping a dialog when it isn't the deck picker sounds great

follow-on though, I suppose that means that dialogs will remain "unconsumed" and *will* eventually pop in the deck picker when that finally shows? That seems reasonable if so

**Comment by mixelas** [comment]
@lukstbit I'd like to work on this issue. Can I be assigned?

**Comment by lukstbit** [comment]
@mixelas How do you plan to fix this?

**Comment by mixelas** [comment]
@lukstbit For a proper fix, I propose:  Instead of casting to DeckPicker, check the type of activity and handle the dialog appropriately for that activity. Also, handle different dialog types in the correct activity. That means that ImportDialog stays with DeckPicker. Other dialogs get routed to the activity that triggered them. Instead of assuming which activity will handle it, have each activity register itself as a listener for dialogs it cares about.

**Comment by lukstbit** [comment]
These errors appear because we have asynchronous operations pushing ui changes(dialogs) after the calling activity is gone. The proper fix would be to handle those operations through a ViewModel so we can control when the ui changes are actually consumed.
But sure go ahead.

**Comment by david-allison** [comment]
Could we work on fixing this properly? 

This is a rare crash, and fixing this properly (even if on a case-by case basis) means: 

* We can handle syncing on other screens
* We can split out the complexity from DeckPicker
