### ISSUE TITLE
AnkiDroid API "Permission not granted"

### ISSUE THREAD

**Issue by snailp4el** [ankidroid/Anki-Android#5162]
###### Reproduction Steps

I am trying to use AnkiDroid API in my project.
I use the example https://github.com/ankidroid/apisample from Wiki
I try to do: `addCardsTo AnkiDroid(ListData);`

###### Expected Result

I want to add a card to my anki.

###### Actual Result
The program crashed with error:
```
12-13 10:29:48.720 26248-26260/? E/AnkiDroid: CardContentProvider/ Permission not granted for: CardContentProvider.query /decks (com.snailp4el.android.tatoeba)
12-13 10:29:48.721 26248-26260/? E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission not granted for: CardContentProvider.query /decks (com.snailp4el.android.tatoeba)
        at com.ichi2.anki.provider.CardContentProvider.throwSecurityException(CardContentProvider.java:1293)
        at com.ichi2.anki.provider.CardContentProvider.query(CardContentProvider.java:210)
        at android.content.ContentProvider.query(ContentProvider.java:1057)
        at android.content.ContentProvider.query(ContentProvider.java:1149)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:242)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
        at android.os.Binder.execTransact(Binder.java:674)
12-13 10:29:48.723 26585-26585/com.snailp4el.android.tatoeba E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.snailp4el.android.tatoeba, PID: 26585
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.snailp4el.android.tatoeba/com.snailp4el.android.tatoeba.MainActivity}: java.lang.SecurityException: Permission not granted for: CardContentProvider.query /decks (com.snailp4el.android.tatoeba)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.SecurityException: Permission not granted for: CardContentProvider.query /decks (com.snailp4el.android.tatoeba)
        at android.os.Parcel.readException(Parcel.java:1942)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
        at android.content.ContentResolver.query(ContentResolver.java:754)
        at android.content.ContentResolver.query(ContentResolver.java:704)
        at android.content.ContentResolver.query(ContentResolver.java:662)
        at com.ichi2.anki.api.AddContentApi.getDeckList(AddContentApi.java:504)
        at com.snailp4el.android.tatoeba.AnkiDroidHelper.getDeckId(AnkiDroidHelper.java:194)
        at com.snailp4el.android.tatoeba.AnkiDroidHelper.findDeckIdByName(AnkiDroidHelper.java:172)
        at com.snailp4el.android.tatoeba.MainActivity.getDeckId(MainActivity.java:204)
        at com.snailp4el.android.tatoeba.MainActivity.addCardsToAnkiDroid(MainActivity.java:231)
        at com.snailp4el.android.tatoeba.MainActivity.onCreate(MainActivity.java:175)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
```

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x] I have searched for similar existing issues here and on the user forum

**Comment by timrae** [comment]
The install order is not supposed to matter. What device are you observing this behaviour on and are you able to reproduce on an emulator?

**Comment by snailp4el** [comment]
I tried to reinstall Anki and my application, it did not help. I tried to run the application at an emulator API 26 and my phone API 25, it is not working on both devices (the error the same). I am sure the problem is in my code because in your example everything work fine. I think it's something to do with permissions, like this https://developer.android.com/training/permissions/requesting#kotlin but I do not know which permissions I need to get access to Anki.

**Comment by timrae** [comment]
You're saying the sample app works but your code doesn't? Then you need to go through your code carefully and figure out what you did differently.

**Comment by mikehardy** [comment]
For future reference, I was poking around [PackageManager documentation](https://developer.android.com/reference/android/content/pm/PackageManager.html#addPermission(android.content.pm.PermissionInfo)) today and I see this:

```
New permissions must be added before any .apks are installed that use those permissions
```

So I think order might not just matter, but actually be vital.

**Comment by timrae** [comment]
That was certainly true before Android 6, but I don't believe it's true anymore. If it is true then it should be trivial to make steps to reproduce.
