### ISSUE TITLE
Deleting first item with multi-select causes Ankidroid to crash

### ISSUE THREAD

**Issue by jgscherber** [ankidroid/Anki-Android#5287]
###### Reproduction Steps
Device: Moto E - Android 5.1

1. Using the new multi-select feature (#4839), select the first note in the card browser
2. Delete the note

###### Expected Result

The note deletes successfully

###### Actual Result

Ankidroid crashes

###### Debug info

Debugging on my device it appears to be a timing issue. If I break before the query in Card.load then the delete is successful. My suspicion is the UI is attempting to update the card after it's been deleted, but before the UI has been notified it's deleted.

Stack trace

> 04-21 16:15:02.547 21477-21542/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
    Process: com.ichi2.anki, PID: 21477
    java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.RuntimeException:  No card with id 1555877685688
        at com.ichi2.libanki.Card.load(Card.java:148)
        at com.ichi2.libanki.Card.<init>(Card.java:123)
        at com.ichi2.libanki.Collection.getCard(Collection.java:518)
        at com.ichi2.async.DeckTask.doInBackgroundRenderBrowserQA(DeckTask.java:883)
        at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:314)
        at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:70)
        at android.os.AsyncTask$2.call(AsyncTask.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
04-21 16:15:02.661 21477-21541/com.ichi2.anki E/DeckTask: previously running task failed with exception: 37
    java.util.concurrent.ExecutionException: java.lang.RuntimeException:  No card with id 1555877685688
        at java.util.concurrent.FutureTask.report(FutureTask.java:93)
        at java.util.concurrent.FutureTask.get(FutureTask.java:163)
        at android.os.AsyncTask.get(AsyncTask.java:487)
        at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:216)
        at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:70)
        at android.os.AsyncTask$2.call(AsyncTask.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.RuntimeException:  No card with id 1555877685688
        at com.ichi2.libanki.Card.load(Card.java:148)
        at com.ichi2.libanki.Card.<init>(Card.java:123)
        at com.ichi2.libanki.Collection.getCard(Collection.java:518)
        at com.ichi2.async.DeckTask.doInBackgroundRenderBrowserQA(DeckTask.java:883)
        at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:314)
        at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:70) 
        at android.os.AsyncTask$2.call(AsyncTask.java:292) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 

###### Research
[ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Well that's no good :-). Timing issues can be fiendish so maybe hard to nail down but the description seems pretty good, thanks for the report
