### ISSUE TITLE
Cannot login to AnkiWeb

### ISSUE THREAD

**Issue by micah** [ankidroid/Anki-Android#5297]
###### Reproduction Steps

1. Go to settings
2. Click Sync->AnkiWeb account (Not logged in)
3. Specify a valid AnkiWeb email address and password
4. Click Login

A pop-up box is shown that says "A network error has occured". It then says an AnkiDroid has encountered a problem; a report is being generated. It then brings up a "Feedback" dialog box where I can enter some text about the problem and then click "Report" -- I have done this.

I can login via the desktop app, or via the AnkiWeb website, just not through the Anki-Android app.

I've checked my email address and password a thousand times, I've made sure my password was correctly input by the keyboard, as well as my email address.

I've also attempted to change my password via the AnkiWeb site and then use that password in the app, but same result.

I have no firewall, or anything that restricts my connections.

###### Debug info
AnkiDroid Version = 2.8.4

Android Version = 7.1.2

ACRA UUID = Couldn't retrieve Installationid

###### Research

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum
I found some similar reports, but those were solved by "fixing the date/time" and by changing the password.

**Comment by mikehardy** [comment]
That's unexpected - can you try the alpha versions (they're stable and don't alter the collection in non-backwards-compatible ways, no worries) https://github.com/ankidroid/Anki-Android/wiki/Installation#beta--alpha-releases

**Comment by timrae** [comment]
Error message is pretty self explanatory, there's something on your network preventing AnkiDroid from connecting to ankiweb. If you're using wifi try using 4G or vice-versa.

**Comment by micah** [comment]
@timrae - I'm using a wifi-only tablet, that is connected to the wifi that all my other devices are connected to.

**Comment by micah** [comment]
@mikehardy - I install 2.8.5beta1, and reproduced the problem. Same issue.

It seems there is a report generated and sent, because the app encountered some kind of error condition, can someone have a look at that report? I suspect it will have more useful debugging information.

Also - I think this issue should be re-opened.

**Comment by mikehardy** [comment]
I still suggest the alpha version, you didn't include a UUID from ACRA, that makes it harder to locate reports

**Comment by mikehardy** [comment]
SSL abort in native functions. There is something wrong with the tablet's network, this looks device specific. 

```
java.lang.RuntimeException: javax.net.ssl.SSLException: Read error: ssl=0x7e67569000: I/O error during system call, Software caused connection abort
at com.ichi2.libanki.sync.RemoteMediaServer.downloadFiles(RemoteMediaServer.java:125)
at com.ichi2.libanki.sync.MediaSyncer._downloadFiles(MediaSyncer.java:240)
at com.ichi2.libanki.sync.MediaSyncer.sync(MediaSyncer.java:167)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:388)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:188)
at com.ichi2.async.Connection.doInBackground(Connection.java:178)
at com.ichi2.async.Connection.doInBackground(Connection.java:50)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: javax.net.ssl.SSLException: Read error: ssl=0x7e67569000: I/O error during system call, Software caused connection abort
at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:766)
at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:108)
at org.apache.http.impl.io.AbstractSessionInputBuffer.read(AbstractSessionInputBuffer.java:139)
at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:166)
at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:180)
at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:183)
at com.ichi2.libanki.sync.HttpSyncer.writeToFile(HttpSyncer.java:266)
at com.ichi2.libanki.sync.RemoteMediaServer.downloadFiles(RemoteMediaServer.java:119)
... 12 more
javax.net.ssl.SSLException: Read error: ssl=0x7e67569000: I/O error during system call, Software caused connection abort
at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:766)
at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:108)
at org.apache.http.impl.io.AbstractSessionInputBuffer.read(AbstractSessionInputBuffer.java:139)
at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:166)
at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:180)
at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:183)
at com.ichi2.libanki.sync.HttpSyncer.writeToFile(HttpSyncer.java:266)
at com.ichi2.libanki.sync.RemoteMediaServer.downloadFiles(RemoteMediaServer.java:119)
at com.ichi2.libanki.sync.MediaSyncer._downloadFiles(MediaSyncer.java:240)
at com.ichi2.libanki.sync.MediaSyncer.sync(MediaSyncer.java:167)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:388)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:188)
at com.ichi2.async.Connection.doInBackground(Connection.java:178)
at com.ichi2.async.Connection.doInBackground(Connection.java:50)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
```

**Comment by mikehardy** [comment]
Assuming this is you anyway - with no UUID, I'm only guessing based on version number and time of report (about 40mins ago)

```

MANUFACTURER | samsung
-- | --
MODEL | SM-G930P
PERMISSIONS_REVIEW_REQUIRED | FALSE
PRODUCT | heroqltespr


```

**Comment by micah** [comment]
@mikehardy - i installed the alpha version, as I mentioned in a previous comment.

I hooked up `adb` and I looked at logcat, and I found errors such as the following:

```05-06 08:30:33.719 12719 14683 W ContextImpl: Failed to ensure /data/user/0/com.ichi2.anki/cache: mkdir failed: EACCES (Permission denied)
```

I looked at the path and it was owned by the root user. I removed that directory (it was empty) and reinstalled anki, and it created it with the correct user/group ownership, and then the login worked fine.

So clearly, this was not a network error, but a permissions error.

**Comment by mikehardy** [comment]
You installed the beta, as mentioned in your previous comment. It's in the version. 2.8.5beta1. The alpha is 2.9.67-alpha or something right now

Weird about permissions - there is something going on with your device if that happened...ankidroid couldn't create things as root if it tried

**Comment by rage2050a** [comment]
I'm having the problem too.

I've experienced #4543, tried several things that didn't work, and uninstalled that version of AnkiDroid (also removed /sdcard/AnkiDroid directory).
Then I clean installed AnkiDroid 2.10.3, pressed "AnkiWeb account", and entered my AnkiWeb account and password (they are valid, because I can log in to AnkiWeb on my PC).

"A network error has occured" "SSLException while building HttpClient"

AnkiDroid version: 2.10.3
Android version: 5.0.2
Kernel version: 3.14.0 android@mec13 #1 Wed Feb 3 11:57:02 CST 2016
ASUS ZenPad 10 (P023)

**Comment by mikehardy** [comment]
The latest news I have is that there was an intermediate certificate in the AnkiWeb certificate bundle that expired earlier than the AnkiWeb cert did so it wasn't noticed until too late. Most clients can validate the AnkiWeb cert by itself but older ones with outdated certificate stores need the whole bundle to be up to date to validate, so it is affecting some people but not everyone. The bundle was updated to fix this today so it should work now, but I"m still hearing reports about it @dae - I don't know why?

**Comment by dae** [comment]
The new bundle looks to be fine, and works for me when testing with curl. SSL labs report looks fine too:

https://www.ssllabs.com/ssltest/analyze.html?d=ankiweb.net

Maybe the devices need a restart? Can any extra info be extracted from the SSLException?

**Comment by mikehardy** [comment]
@dae at present no, no way to get more info without a user willing to read adb logcat :-)

You've triple-checked here, I imagine it's got to just be as you imply - some sort of client caching that will wash out over time. The incidence report rate has certainly dropped off and as long the report rate seems to be an asymptotic curve to zero I'll consider it done even if a few more reports come in. THanks

**Comment by rage2050a** [comment]
AnkiDroid 2.10.4 (Workaround expired AnkiWeb SSL Root certificate) works.
Thank you.

**Comment by david-allison-1** [comment]
Great!!!

For any future posters: could any discussion about the current issue be made on: #6317

All the best,

David
