### ISSUE TITLE
ModuleNotFoundError: No module named 'decorator'

### ISSUE THREAD

**Issue by dubovski** [ankidroid/Anki-Android#5392]
###### Reproduction Steps

1. Set Fork
2. check out in my PyCharm https://github.com/dubovski/anki.git
3. Run 'runanki' [Python 3.7]

###### Expected Result

expect to see Anki Window

###### Actual Result
Traceback (most recent call last):
  File "C:/Work/Python Projects/anki/runanki", line 3, in <module>
    import aqt
  File "C:\Work\Python Projects\anki\aqt\__init__.py", line 4, in <module>
    from anki import version as _version
  File "C:\Work\Python Projects\anki\anki\__init__.py", line 14, in <module>
    from anki.storage import Collection
  File "C:\Work\Python Projects\anki\anki\storage.py", line 13, in <module>
    from anki.collection import _Collection
  File "C:\Work\Python Projects\anki\anki\collection.py", line 19, in <module>
    from anki.hooks import  runFilter, runHook
  File "C:\Work\Python Projects\anki\anki\hooks.py", line 16, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by adamwolf** [comment]
This repository is for the Anki Android app, not the Anki Desktop program.
