### ISSUE TITLE
App resetting frequently when reviewing

### ISSUE THREAD

**Issue by nicolas0p** [ankidroid/Anki-Android#5403]
###### Reproduction Steps

1. Get deck from https://www.mediafire.com/file/1svvsr7f9cnpwka/Matt%27s+Lazy+Kanji+1k.apkg
2. Increase new card per day count to about 50
3. Review them, cards will start to take more to load, eventually the app will reset.

This deck is from the Mass Immersion Approach website (https://massimmersionapproach.com/table-of-contents/stage-1/practice/lazy-kanji/)

###### Expected Result
Being able to review cards normally.

###### Actual Result
Cards take longer to load and eventually the app resets.
Sometimes, after resetting, the app forgets how many new cards I've reviewed and increases the new card amount back to the maximum per day.

###### Debug info
AnkiDroid Version = 2.8.4

Android Version = 8.1.0

ACRA UUID = cf45c2c9-d107-47cb-bd56-d553de783238

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
That sounds frustrating!

We're getting close to final release on 2.9, can you check the manual for beta install instructions and use the beta? The libraries in use are about 2 years fresher in the beta and that might help? If not we'll at least have a current base to reproduce from

**Comment by nicolas0p** [comment]
Sure, Mike. I'll try that in the next few days and report back if the bug persists.
Thanks!

**Comment by chickendude** [comment]
I've been having this same issue with that deck, it doesn't reset to max reviews each time but it does add a couple. I'll try loading up the beta tomorrow and see if that fixes anything.

**Comment by chickendude** [comment]
The issue still occurs on the beta version, it appears there's a native crash:
```
08-15 23:30:03.493  1550  4222 E WindowManager: win=Window{51a2fb5 u0 com.ichi2.anki/com.ichi2.anki.NoteEditor} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8 caller=com.android.server.wm.WindowManagerService.tryStartExitingAnimation:2737 com.android.server.wm.WindowManagerService.relayoutWindow:2435 com.android.server.wm.Session.relayoutForTranslate:287 android.view.IWindowSession$Stub.onTransact:432 com.android.server.wm.Session.onTransact:186 android.os.Binder.execTransact:739 <bottom of call stack> 
08-15 23:30:03.819  6745  6767 F chromium: [FATAL:memory_linux.cc(42)] Out of memory.
08-15 23:30:03.826  6745  6767 E libc    : failed to connect to tombstoned: Operation not permitted
08-15 23:30:04.582 12213 12213 E Zygote  : isWhitelistProcess - Process is Whitelisted
08-15 23:30:04.583 12213 12213 E Zygote  : isSdpEnabledProcess - SDP enabled
08-15 23:30:04.584 12213 12213 E Zygote  : accessInfo : 5
08-15 23:30:04.584 12213 12213 E Zygote  : isSdpEnabledProcess - SDP enabled
08-15 23:30:04.584 12213 12213 E Zygote  : setSDPgroupsIntarray[pid]: 0 / [gid]: 10075 / [uid]: 10075
08-15 23:30:04.611 12213 12213 E .email.provide: Not starting debugger since process cannot load the jdwp agent.
08-15 23:30:04.963  1550  1595 E libprocessgroup: Error encountered killing process cgroup uid 99554 pid 6745: No such file or directory
08-15 23:30:05.003 12213 12213 E Utility : isFBELocked status 4 isUserUnlocked true
08-15 23:30:05.010 14650 14650 E chromium: [ERROR:aw_browser_terminator.cc(125)] Renderer process (6745) crash detected (code 5).
08-15 23:30:05.020 14650 14650 F chromium: [FATAL:crashpad_client_linux.cc(494)] Render process (6745)'s crash wasn't handled by all associated  webviews, triggering application crash.
08-15 23:30:05.021 14650 14650 F libc    : Fatal signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0x794b1e0a38 in tid 14650 (com.ichi2.anki), pid 14650 (com.ichi2.anki)
08-15 23:30:05.187 12252 12252 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-15 23:30:05.187 12252 12252 F DEBUG   : Build fingerprint: 'samsung/greatqltesq/greatqlte:9/PPR1.180610.011/N950USQS6DSG4:user/release-keys'
08-15 23:30:05.187 12252 12252 F DEBUG   : Revision: '11'
08-15 23:30:05.187 12252 12252 F DEBUG   : ABI: 'arm64'
08-15 23:30:05.187 12252 12252 F DEBUG   : pid: 14650, tid: 14650, name: com.ichi2.anki  >>> com.ichi2.anki <<<
08-15 23:30:05.187 12252 12252 F DEBUG   : signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0x794b1e0a38
08-15 23:30:05.187 12252 12252 F DEBUG   : Abort message: '[FATAL:crashpad_client_linux.cc(494)] Render process (6745)'s crash wasn't handled by all associated  webviews, triggering application crash.
08-15 23:30:05.187 12252 12252 F DEBUG   : '
08-15 23:30:05.187 12252 12252 F DEBUG   :     x0  0000007fd9c1ae28  x1  00000079432eb380  x2  0000000000000400  x3  00000079e02313c8
08-15 23:30:05.187 12252 12252 F DEBUG   :     x4  0000000000000021  x5  75696d6f726863ff  x6  0000000000008000  x7  0080000000000000
08-15 23:30:05.187 12252 12252 F DEBUG   :     x8  0000000000000000  x9  0000000000000000  x10 0000007fd9c1ae28  x11 00000000ffffff80
08-15 23:30:05.187 12252 12252 F DEBUG   :     x12 00000079432eb380  x13 0000000000000008  x14 ffffffffffffffff  x15 000095485969b615
08-15 23:30:05.187 12252 12252 F DEBUG   :     x16 00000079e022f1b0  x17 00000079e01b2a48  x18 0000000000000010  x19 0000007fd9c1b2a0
08-15 23:30:05.187 12252 12252 F DEBUG   :     x20 0000007fd9c1b2a8  x21 0000007fd9c1b2b0  x22 000000000000008d  x23 00000079e02313c8
08-15 23:30:05.187 12252 12252 F DEBUG   :     x24 000000794ce8f000  x25 0000007949696ee5  x26 0000007949717068  x27 00000079e55195f8
08-15 23:30:05.187 12252 12252 F DEBUG   :     x28 00000079496f53de  x29 0000007fd9c1b290
08-15 23:30:05.187 12252 12252 F DEBUG   :     sp  0000007fd9c1ade0  lr  000000794b1e08fc  pc  000000794b1e0a38
08-15 23:30:05.190 12252 12252 F DEBUG   : 
08-15 23:30:05.190 12252 12252 F DEBUG   : backtrace:
08-15 23:30:05.190 12252 12252 F DEBUG   :     #00 pc 0000000001ddea38  /data/app/com.android.chrome-NbyIp2oIzySSi7fvcjYJ9Q==/base.apk (offset 0xc0f000)
08-15 23:30:05.934  1121  1121 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_08
08-15 23:30:06.041 12269 12269 E Zygote  : isWhitelistProcess - Process is Whitelisted
08-15 23:30:06.043 12269 12269 E Zygote  : accessInfo : 1
08-15 23:30:06.071 12269 12269 E android.dqagen: Not starting debugger since process cannot load the jdwp agent.
08-15 23:30:06.111  1550  2162 E InputDispatcher: channel '6b6edab com.ichi2.anki/com.ichi2.anki.Reviewer (server)' ~ Channel is unrecoverably broken and will be disposed!
08-15 23:30:06.111  1550  2162 E InputDispatcher: channel 'f5be4e9 com.ichi2.anki/com.ichi2.anki.DeckPicker (server)' ~ Channel is unrecoverably broken and will be disposed!
08-15 23:30:06.140  1032  1149 E storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
08-15 23:30:06.144  1550  1602 E WindowManager: RemoteException occurs on reporting focusChanged, w=Window{6b6edab u0 com.ichi2.anki/com.ichi2.anki.Reviewer EXITING}
08-15 23:30:06.144  1550  1602 E WindowManager: android.os.DeadObjectException
08-15 23:30:06.144  1550  1602 E WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
08-15 23:30:06.144  1550  1602 E WindowManager: 	at android.os.BinderProxy.transact(Binder.java:1143)
08-15 23:30:06.144  1550  1602 E WindowManager: 	at android.view.IWindow$Stub$Proxy.windowFocusChanged(IWindow.java:500)
08-15 23:30:06.144  1550  1602 E WindowManager: 	at com.android.server.wm.WindowState.reportFocusChangedSerialized(WindowState.java:3879)
08-15 23:30:06.144  1550  1602 E WindowManager: 	at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:5426)
08-15 23:30:06.144  1550  1602 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-15 23:30:06.144  1550  1602 E WindowManager: 	at android.os.Looper.loop(Looper.java:214)
08-15 23:30:06.144  1550  1602 E WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:65)
08-15 23:30:06.144  1550  1602 E WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
08-15 23:30:06.175  1550  5393 E WindowManager: win=Window{6b6edab u0 com.ichi2.anki/com.ichi2.anki.Reviewer EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:870 com.android.server.wm.AppWindowToken.destroySurfaces:851 com.android.server.wm.WindowState.onExitAnimationDone:5365 com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.AppWindowToken.onAnimationFinished:2403 com.android.server.wm.AppWindowToken.setVisibility:551 
08-15 23:30:06.231 30943  7345 E rs$DefaultThreadFactory: ===== Detect pool-thread leak =====
08-15 23:30:06.231 30943 31263 E rs$DefaultThreadFactory: ===== Detect pool-thread leak =====
```

And another crash:
```
08-15 23:53:44.321 16435 16464 F chromium: [FATAL:memory_linux.cc(42)] Out of memory.
08-15 23:53:44.334 16435 16464 E libc    : failed to connect to tombstoned: Operation not permitted
08-15 23:53:45.598  1550  1595 E libprocessgroup: Error encountered killing process cgroup uid 99555 pid 16435: No such file or directory
08-15 23:53:45.599  1550  4220 W ActivityManager: Scheduling restart of crashed service com.ichi2.anki/org.chromium.content.app.SandboxedProcessService0 in 1000ms
08-15 23:53:45.618 12287 12287 E chromium: [ERROR:aw_browser_terminator.cc(125)] Renderer process (16435) crash detected (code 5).
08-15 23:53:45.623 12287 12287 F chromium: [FATAL:crashpad_client_linux.cc(494)] Render process (16435)'s crash wasn't handled by all associated  webviews, triggering application crash.
08-15 23:53:45.623 12287 12287 F libc    : Fatal signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0x794b1e0a38 in tid 12287 (com.ichi2.anki), pid 12287 (com.ichi2.anki)
08-15 23:53:45.749 18715 18715 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-15 23:53:45.749 18715 18715 F DEBUG   : Build fingerprint: 'samsung/greatqltesq/greatqlte:9/PPR1.180610.011/N950USQS6DSG4:user/release-keys'
08-15 23:53:45.749 18715 18715 F DEBUG   : Revision: '11'
08-15 23:53:45.749 18715 18715 F DEBUG   : ABI: 'arm64'
08-15 23:53:45.749 18715 18715 F DEBUG   : pid: 12287, tid: 12287, name: com.ichi2.anki  >>> com.ichi2.anki <<<
08-15 23:53:45.749 18715 18715 F DEBUG   : signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0x794b1e0a38
08-15 23:53:45.749 18715 18715 F DEBUG   : Abort message: '[FATAL:crashpad_client_linux.cc(494)] Render process (16435)'s crash wasn't handled by all associated  webviews, triggering application crash.
08-15 23:53:45.749 18715 18715 F DEBUG   : '
08-15 23:53:45.749 18715 18715 F DEBUG   :     x0  0000007fd9c1ae28  x1  00000079408f0400  x2  0000000000000400  x3  00000079e02313c8
08-15 23:53:45.749 18715 18715 F DEBUG   :     x4  0000000000000021  x5  75696d6f726863ff  x6  0000000000008000  x7  0080000000000000
08-15 23:53:45.749 18715 18715 F DEBUG   :     x8  0000000000000000  x9  0000000000000000  x10 0000007fd9c1ae28  x11 00000000ffffff80
08-15 23:53:45.749 18715 18715 F DEBUG   :     x12 00000079408f0400  x13 0000000000000008  x14 ffffffffffffffff  x15 000054f7b57f74ca
08-15 23:53:45.749 18715 18715 F DEBUG   :     x16 00000079e022f1b0  x17 00000079e01b2a48  x18 0000000000000010  x19 0000007fd9c1b2a0
08-15 23:53:45.749 18715 18715 F DEBUG   :     x20 0000007fd9c1b2a8  x21 0000007fd9c1b2b0  x22 000000000000008e  x23 00000079e02313c8
08-15 23:53:45.749 18715 18715 F DEBUG   :     x24 000000794ce8f000  x25 0000007949696ee5  x26 0000007949717068  x27 00000079e55195f8
08-15 23:53:45.749 18715 18715 F DEBUG   :     x28 00000079496f53de  x29 0000007fd9c1b290
08-15 23:53:45.749 18715 18715 F DEBUG   :     sp  0000007fd9c1ade0  lr  000000794b1e08fc  pc  000000794b1e0a38
08-15 23:53:45.751 18715 18715 F DEBUG   : 
08-15 23:53:45.751 18715 18715 F DEBUG   : backtrace:
08-15 23:53:45.751 18715 18715 F DEBUG   :     #00 pc 0000000001ddea38  /data/app/com.android.chrome-NbyIp2oIzySSi7fvcjYJ9Q==/base.apk (offset 0xc0f000)
08-15 23:53:46.422  1121  1121 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_09
08-15 23:53:46.494 18722 18722 E Zygote  : isWhitelistProcess - Process is Whitelisted
08-15 23:53:46.499 18722 18722 E Zygote  : accessInfo : 1
08-15 23:53:46.533  1550  2162 E InputDispatcher: channel 'd77bc80 com.ichi2.anki/com.ichi2.anki.Reviewer (server)' ~ Channel is unrecoverably broken and will be disposed!
08-15 23:53:46.534 18722 18722 E ng.android.loo: Not starting debugger since process cannot load the jdwp agent.
08-15 23:53:46.539  1550  2162 E InputDispatcher: channel '1c98b83 com.ichi2.anki/com.ichi2.anki.DeckPicker (server)' ~ Channel is unrecoverably broken and will be disposed!
08-15 23:53:46.551 30943 15585 E rs$DefaultThreadFactory: ===== Detect pool-thread leak =====
08-15 23:53:46.551 30943 32170 E rs$DefaultThreadFactory: ===== Detect pool-thread leak =====
```

**Comment by mikehardy** [comment]
My hunch here is that the webview (which means: chrome app) is having indigestion here, and there is likely nothing we can do about it. I don't mean to sound fatalistic, but I have had zero percent success fixing something when it's chrome (used to render cards, while reviewing or editing) and it crashes, despite much effort. The unique success was just learning to mitigate a problem by using "lighter" fonts.

Specifically for this crash, unfortunately despite the fantastic amount of information (thank you!) I personally don't really know where to start since it's in the webview other than to advise altering the note template to lean it out bit by bit

**Comment by chickendude** [comment]
I'll see if i can find any other information as to what's going on with the webview, the cards themselves look pretty harmless, other than perhaps the "@font-face" rules in the CSS. There isn't any audio or pictures or things i would think take up much space, though it is loading four fonts which altogether take up about 50MB.

**Comment by mikehardy** [comment]
fonts are everything - look through our issue tracker for lag on display for japanese fonts! that was the one success we had, learning how important fonts were, and finding lighter weight ones. It might do the trick

**Comment by chickendude** [comment]
Ah great, i'll try commenting out two of the fonts and see if that improves the issue.

**Comment by chickendude** [comment]
Removing the fonts from the CSS seems to have fixed the issue, it's a bit unfortunate though but i'm not sure of ways around it apart from perhaps generating pictures for each font and loading those instead...

I'll also give the following a shot:

> Not sure if anyone has tried this, but apparently the fallback logic in chromium for ideographic languages has a tough time. You might try setting lang="ja" in the html element of the note (is that possible? may not be - you might have to hack card.html in our source code to test it...). Or lang="zh" as the case may be (for your card)
> 
> https://bugs.chromium.org/p/chromium/issues/detail?id=945117#c33
> 
> _Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/4856#issuecomment-487821866_

**Comment by mikehardy** [comment]
This is an upstream issue, fonts are discussed at length elsewhere but if you wanted to add to the wiki about using custom fonts noting that large fonts are problematic, that would be nice
