### ISSUE TITLE
Anki crashes when I open any deck and when I tap "about AnkiDroid"

### ISSUE THREAD

**Issue by james-bay** [ankidroid/Anki-Android#5436]
###### Reproduction Steps

1. When I open any deck and when I tap "about AnkiDroid"

###### Expected Result
Opening the deck.

###### Actual Result
It crashes. The first time AnkiDroid send you a error report and then it closes immediately without any messages. 
The problem appeared only on AnkiDroid 2.9beta 10. AnkiDroid 2.9beta 9 worked fine.

###### Debug info
AnkiDroid verison: 2.9beta 10
Android version: 5.1.1
Experimental scheduler: on.

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by timrae** [comment]
Please paste the actual debug info

**Comment by james-bay** [comment]
> Please paste the actual debug info

Unfortunately when I tap "about AnkiDroid" it crashes too. Is there any other way to get debug info?

**Comment by timrae** [comment]
Ugh right... No, unfortunately this isn't possible, at least not without a rooted device. However thankfully your combination of Android version and AnkiDroid version is relatively rare, so it should be easy to find your crash report if it got sent in properly. Is this your device version? `Jiayu Jiayu JY-S3`

The only difference between 2.9 beta9 and 2.9beta10 is some library updates. I guess the most likely culprit is this one: https://github.com/ankidroid/Anki-Android/commit/2cc4c46125223595edbab6c4a24877551dd620e2

**Comment by james-bay** [comment]
@timrae Yes, Jiayu JY-S3 is my device)

**Comment by timrae** [comment]
Thanks for the follow up. It seems that the crash is so far limited to your device:

```
android.content.res.Resources$NotFoundException: String resource ID #0x2040003
at android.content.res.Resources.getText(Resources.java:322)
at android.content.res.Resources.getString(Resources.java:420)
at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:684)
at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:674)
at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:823)
at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:662)
at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:597)
at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:319)
at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:104)
at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:271)
at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:131)
at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:118)
at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:115)
at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:268)
at android.webkit.WebView.<init>(WebView.java:591)
at android.webkit.WebView.<init>(WebView.java:526)
at android.webkit.WebView.<init>(WebView.java:509)
at android.webkit.WebView.<init>(WebView.java:496)
at android.webkit.WebView.<init>(WebView.java:486)
at com.ichi2.anki.AbstractFlashcardViewer$MyWebView.<init>(AbstractFlashcardViewer.java:2)
at com.ichi2.anki.AbstractFlashcardViewer.createWebView(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.setInterface(AbstractFlashcardViewer.java:3)
at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:3)
at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:2)
at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:11)
at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:1)
```

**Comment by timrae** [comment]
Also this one:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.Info}: android.view.InflateException: Binary XML file line #40: Error inflating class android.webkit.WebView
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2521)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595)
at android.app.ActivityThread.access$800(ActivityThread.java:178)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5624)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
Caused by: android.view.InflateException: Binary XML file line #40: Error inflating class android.webkit.WebView
at android.view.LayoutInflater.createView(LayoutInflater.java:633)
at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:9)
at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:1)
at com.ichi2.anki.Info.onCreate(Info.java:5)
```

**Comment by timrae** [comment]
In both cases, the problem seems to be caused by issues with the Webview. What version of Webview are you using? Does upgrading or downgrading it solve the problem?

**Comment by james-bay** [comment]
@timrae I just installed Android System WebView (v. 77.0.3865.73) from Google Play and AnkiDroid no longer crashes. Apparently, I did not have a WebView component at all. I don’t even know what to assume.

**Comment by timrae** [comment]
Great that it's working again!

**Comment by james-bay** [comment]
@timrae thank you!
