### ISSUE TITLE
[2.9 ACRA] Could not import apkg from ContentProvider

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5505]
The root cause of this one might be permissions or similar that we cannot solve, but it should probably be handled with a good user message if it is not already? And then if it has a good user message it should not be a crash report in ACRA

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/0b7b06d3-3274-44d7-a7f0-d636357e31e7

```
java.lang.RuntimeException: Could not import apkg from ContentProvider
at com.ichi2.utils.ImportUtils.handleFileImport(ImportUtils.java:11)
at com.ichi2.anki.IntentHandler.onCreate(IntentHandler.java:10)
at android.app.Activity.performCreate(Activity.java:7458)
at android.app.Activity.performCreate(Activity.java:7448)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
at android.os.Handler.dispatchMessage(Handler.java:112)
at android.os.Looper.loop(Looper.java:216)
at android.app.ActivityThread.main(ActivityThread.java:7625)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by mikehardy** [comment]
Fixed lots of package import issues here #5790 and this particular crash is actually a corrupt file so it's not 100% on target. This is/was a frequent problem though due to out of space with poor messaging
