### ISSUE TITLE
[2.9 ACRA] NullPointerException in StudioOptionsFragment.initAllContentViews

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5506]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/8392a87c-9f5a-4243-840d-7a921dfe3577

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
at com.ichi2.anki.StudyOptionsFragment.initAllContentViews(StudyOptionsFragment.java:3)
at com.ichi2.anki.StudyOptionsFragment.access$400(StudyOptionsFragment.java:1)
at com.ichi2.anki.StudyOptionsFragment$3.onPostExecute(StudyOptionsFragment.java:11)
at com.ichi2.async.DeckTask$TaskListener.onPostExecute(DeckTask.java:1)
at com.ichi2.async.DeckTask.onPostExecute(DeckTask.java:3)
at com.ichi2.async.DeckTask.onPostExecute(DeckTask.java:1)
at android.os.AsyncTask.finish(AsyncTask.java:695)
at android.os.AsyncTask.access$600(AsyncTask.java:180)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7080)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by david-allison-1** [comment]
Cause was splitscreen: https://groups.google.com/forum/#!topic/anki-android/UqgAd4Y1h1Q
