### ISSUE TITLE
[2.9 ACRA] Crash attempting to add media to card when no handlers installed

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5514]
Looks like we're not handling the case where there are no media pickers at all

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/82436c7f-b67a-43c9-9f22-1464b8000aaf

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.PICK dat=content://media/external/images/media flg=0x10000 }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2031)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1686)
at android.app.Activity.startActivityForResult(Activity.java:4506)
at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:6)
at android.app.Activity.startActivityForResult(Activity.java:4464)
at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:3)
at com.ichi2.anki.AnkiActivity.startActivityForResultWithoutAnimation(AnkiActivity.java:2)
at com.ichi2.anki.multimediacard.fields.BasicImageFieldController.a(BasicImageFieldController.java:2)
at com.ichi2.anki.multimediacard.fields.d.onClick(Unknown Source:2)
at android.view.View.performClick(View.java:6297)
at android.view.View$PerformClick.run(View.java:24797)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6626)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
``````

**Comment by divyansh-dxn** [comment]
This issue is still open, but I think this has already been handled. Although the method has been deprecated, I don't think this can cause a crash now.

```kotlin 
   @Deprecated
    @Override
    public void startActivityForResult(Intent intent, int requestCode) {
        try {
            super.startActivityForResult(intent, requestCode);
        } catch (ActivityNotFoundException e) {
            Timber.w(e);
            UIUtils.showSimpleSnackbar(this, R.string.activity_start_failed,true);
        }
    }
```
