### ISSUE TITLE
[2.9 ACRA] crash in DeckTask.doInBackgroundRenderBrowserQA

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5516]
This  might be data related?

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/79e230f5-d99c-4b9c-8518-9db2caaf9920

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:354)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IndexOutOfBoundsException: Index: 446, Size: 0
at java.util.ArrayList.get(ArrayList.java:437)
at com.ichi2.async.DeckTask.doInBackgroundRenderBrowserQA(DeckTask.java:9)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:29)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 4 more
``````

**Comment by mikehardy** [comment]
This should be fixed thoroughly at this point with #5578
