### ISSUE TITLE
[2.9 ACRA] - state handling crash - showStartupScreensAndDialogs permission result handling after onSaveInstanceState

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5517]
Possibly related to #5504 

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/9fb47844-a585-4a7c-99c7-c2abb034b0ea

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.ichi2.anki/com.ichi2.anki.DeckPicker}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.app.ActivityThread.deliverResults(ActivityThread.java:3720)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:3763)
at android.app.ActivityThread.-wrap16(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:2)
at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1)
at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:12)
at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:1)
at androidx.fragment.app.DialogFragment.show(DialogFragment.java:10)
at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:5)
at com.ichi2.anki.DeckPicker.showStartupScreensAndDialogs(DeckPicker.java:11)
at com.ichi2.anki.DeckPicker.onRequestPermissionsResult(DeckPicker.java:4)
at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6567)
at android.app.Activity.dispatchActivityResult(Activity.java:6446)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3716)
```

**Comment by mikehardy** [comment]
If the general solution here is implemented, it will fix this as well https://github.com/ankidroid/Anki-Android/issues/5504#issuecomment-542427471

**Comment by david-allison-1** [comment]
This is one of our bigger crashers and would be great to get sorted.

**Comment by dae** [comment]
@david-allison still the case?
