### ISSUE TITLE
[2.9 ACRA] Syncer crash on null DB object?

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5519]
Not sure how the app can get in this state but it crashes here:

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/ca0b7820-cad7-4e1c-9bde-07d68a7f31ab

```
java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.sqlite.db.SupportSQLiteDatabase com.ichi2.libanki.DB.getDatabase()' on a null object reference
at com.ichi2.libanki.sync.Syncer.sync(Syncer.java:7)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:15)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:2)
at com.ichi2.async.Connection.doInBackground(Connection.java:4)
at com.ichi2.async.Connection.doInBackground(Connection.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
```

logcat was 

```

0--------- beginning of main110-14 23:09:27.711 E/AnkiDroid(15289): Preferences/ Preferences: no preference found for the key: syncAccount210-14 23:11:15.323 I/AnkiDroid(15289): Sync - starting sync310-14 23:11:15.364 I/AnkiDroid(15289): closeCollection410-14 23:11:15.367 I/AnkiDroid(15289): Collection closed510-14 23:11:15.368 I/AnkiDroid(15289): AnkiActivity -- restartActivityInvalidateBackstack()610-14 23:11:15.502 I/AnkiDroid(15289): openCollection: /sdcard/AnkiDroid/collection.anki2710-14 23:11:16.970 E/AnkiDroid(15289): Connection/ doInBackgroundSync error8 | 0 | --------- beginning of main | 1 | 10-14 23:09:27.711 E/AnkiDroid(15289): Preferences/ Preferences: no preference found for the key: syncAccount | 2 | 10-14 23:11:15.323 I/AnkiDroid(15289): Sync - starting sync | 3 | 10-14 23:11:15.364 I/AnkiDroid(15289): closeCollection | 4 | 10-14 23:11:15.367 I/AnkiDroid(15289): Collection closed | 5 | 10-14 23:11:15.368 I/AnkiDroid(15289): AnkiActivity -- restartActivityInvalidateBackstack() | 6 | 10-14 23:11:15.502 I/AnkiDroid(15289): openCollection: /sdcard/AnkiDroid/collection.anki2 | 7 | 10-14 23:11:16.970 E/AnkiDroid(15289): Connection/ doInBackgroundSync error | 8
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

0 | --------- beginning of main
1 | 10-14 23:09:27.711 E/AnkiDroid(15289): Preferences/ Preferences: no preference found for the key: syncAccount
2 | 10-14 23:11:15.323 I/AnkiDroid(15289): Sync - starting sync
3 | 10-14 23:11:15.364 I/AnkiDroid(15289): closeCollection
4 | 10-14 23:11:15.367 I/AnkiDroid(15289): Collection closed
5 | 10-14 23:11:15.368 I/AnkiDroid(15289): AnkiActivity -- restartActivityInvalidateBackstack()
6 | 10-14 23:11:15.502 I/AnkiDroid(15289): openCollection: /sdcard/AnkiDroid/collection.anki2
7 | 10-14 23:11:16.970 E/AnkiDroid(15289): Connection/ doInBackgroundSync error
8


```

**Comment by Arthur-Milchior** [comment]
If you succeed in starting Syncer#Sync twice simultaneously (clicking fast enough ?) then I guess it could be expected; since the first will want to access the DB while the second will have closed the collection.
I kind of think that stating that this should be a synchronized method would make sens; you don't want two running in parallel. 

Seeing "restartActivityInvalidateBackstack" I kind of hoped that it meant that an activity such as syncing was restarted. But I guess it's not the case, since this can actually only restart the activity «drawer»
