### ISSUE TITLE
[2.9 ACRA] CardBrowser crash with sort settings

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5523]
Looks like a simple type conversion issue

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/cf53b2cf-7ed7-4185-85f5-abe5defe705b

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:325)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:762)
Caused by: java.lang.RuntimeException: org.json.JSONException: Value 0 at sortBackwards of type java.lang.Integer cannot be converted to boolean
at com.ichi2.libanki.Finder._order(Finder.java:20)
at com.ichi2.libanki.Finder._findCardsForCardBrowser(Finder.java:6)
at com.ichi2.libanki.Finder.findCardsForCardBrowser(Finder.java:1)
at com.ichi2.libanki.Collection.findCardsForCardBrowser(Collection.java:1)
at com.ichi2.async.DeckTask.doInBackgroundSearchCards(DeckTask.java:7)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:36)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
Caused by: org.json.JSONException: Value 0 at sortBackwards of type java.lang.Integer cannot be converted to boolean
at org.json.JSON.typeMismatch(JSON.java:100)
at org.json.JSONObject.getBoolean(JSONObject.java:413)
```

**Comment by Arthur-Milchior** [comment]
In Anki, sortBackward order is set in _onSortChanged
https://github.com/dae/anki/blob/0577157970c41d1bd5c6d2740c7b3e62eceed5c8/aqt/browser.py#L731
and 
https://github.com/dae/anki/blob/0577157970c41d1bd5c6d2740c7b3e62eceed5c8/aqt/browser.py#L727 . Which is called by onSortChanged. Which is connected to QT's sortIndicatorChanged in the browser ( https://doc.qt.io/qt-5/qheaderview.html#sortIndicatorChanged ), which gives as parameter of type SordOrder
https://doc.qt.io/qt-5/qt.html#SortOrder-enum which is in fact value 0 or 1 for ascending and descending order. 

However, if I got this right, it's strange this does not occur very often

**Comment by Arthur-Milchior** [comment]
Actually, there is an explanation for that. 
            mOrderAsc = Upgrade.upgradeJSONIfNecessary(getCol(), getCol().getConf(), "sortBackwards", false);
transforms the int into false

So the only question is how could it be that onCollectionLoaded was not properly executed

**Comment by Arthur-Milchior** [comment]
In https://github.com/dae/anki/pull/347 DAE did accept a PR I did, which ensure that sortBackwards is always set to a Boolean. So this should never occur anymore with the future version of Anki. 
Except if you have a lot of report with this kind of bug, I believe it's safe to ignore it, since 
```Java
mOrderAsc = Upgrade.upgradeJSONIfNecessary(getCol(), getCol().getConf(), "sortBackwards", false);
```
should already correct the bug most of the time. Unless the collection is changed while the browser is displayed and need to have access to the value of sortBackwards before the collection is corrected; which I guess is possible due to asynchrone computation but should be quite rare.

Ideally, the method to upgrade JSON should imitate Python's method bool(), and not systematically set the value to False. But I don't think it's really worth taking time to edit this code to do it. After all, once people upgrade to the future version of Anki, this won't occur again. And currently, the only loss is that Anki and Ankidroid display the sort column in a different order. Not really a trouble.

**Comment by timrae** [comment]
Damien noted in that other PR that

> (the fix) doesn't really solve the problem, as once the bad data is out there in the wild, the other clients need to be able to cope with it.

so I hesitate to close this issue, but agree it's very low priority

**Comment by Arthur-Milchior** [comment]
I know I'm going to repeat myself, but I must emphasize that the fix is already done in `upgradeJSONIfNecessary`. This means you don't even have to create a fix. At most, you have to ensure that no asynchrone process read the JSON between the time when it is downloaded and the time when it is upgraded. Which I guess could be done if you call this method before setting the configuration variable to its new value instead of calling it afterward.
