### ISSUE TITLE
Card browser can't be opened in API 16

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#5598]
###### Reproduction Steps

Open a VM with AP 16. Open  "master" version of ankidroid in it (currently 0cde80f3873b29abce522953b55a3752c28dc610 ). Try to open the browser.
«Unfortunately, AnkiDroid has stopped»

> E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.IndexOutOfBoundsException: Invalid index 13, size is 9
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
        at java.util.Arrays$ArrayList.get(Arrays.java:66)
        at android.widget.ArrayAdapter.getItem(ArrayAdapter.java:337)
        at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:390)
        at android.widget.ArrayAdapter.getView(ArrayAdapter.java:362)
        at android.widget.Spinner.makeAndAddView(Spinner.java:541)
        at android.widget.Spinner.layout(Spinner.java:492)
        at android.widget.Spinner.onLayout(Spinner.java:456)
        at android.view.View.layout(View.java:13754)
        at android.view.ViewGroup.layout(ViewGroup.java:4364)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
        at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1638)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1422)
        at android.view.View.layout(View.java:13754)
        at android.view.ViewGroup.layout(ViewGroup.java:4364)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
        at android.view.View.layout(View.java:13754)
        at android.view.ViewGroup.layout(ViewGroup.java:4364)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1183)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:870)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:889)
        at android.view.View.layout(View.java:13754)
        at android.view.ViewGroup.layout(ViewGroup.java:4364)
        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
        at android.view.View.layout(View.java:13754)
        at android.view.ViewGroup.layout(ViewGroup.java:4364)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
        at android.view.View.layout(View.java:13754)
        at android.view.ViewGroup.layout(ViewGroup.java:4364)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
        at android.view.View.layout(View.java:13754)
        at android.view.ViewGroup.layout(ViewGroup.java:4364)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
        at android.view.View.layout(View.java:13754)
        at android.view.ViewGroup.layout(ViewGroup.java:4364)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
        at android.view.View.layout(View.java:13754)
        at android.view.ViewGroup.layout(ViewGroup.java:4364)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
        at android.view.View.layout(View.java:13754)
        at android.view.ViewGroup.layout(ViewGroup.java:4364)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1868)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1689)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4214)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
        at android.view.Choreographer.doCallbacks(Choreographer.java:555)
        at android.view.Choreographer.doFrame(Choreographer.java:525)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
        at android.os.Handler.handleCallback(Handler.java:615)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4745)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)

I tried with API 22, and it still works. I would prefer to avoid trying to test all API between both; if someone has a way to make a dichotomy which would not require installing API 19, 17 and 18 (or whatever else the dichotomy finds) that would be wonderful. Or maybe even adding a test in anki for the function «open the card browser»

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
I attempted to set up UI tests but they were so flaky as to be net negative value even though their potential usefulness is great in theory https://github.com/ankidroid/Anki-Android/commit/4b6bdafb3a9d170170a800e4c67c3e9c3088929f#diff-fcd62bd77ff790036124b12a31946551

A lot of that had to do with timing issues and the slow emulator infrastructure in CI though. Perhaps as of the last couple days with hardware acceleration via nested virtualization enabled in CI to speed things up by orders of magnitude #5583, they are possible again 

Either way, I can't reproduce this with my test collection in API16 (I just tried it), so this is likely data specific. Or my test was invalid in some other way, but either way API16 is not completely broken so I don't think bisecting APIs is the right thing. Instrumenting display so you can examine the specific data it's on when it blows up is maybe the right track

This may also be something unclean in the build as it looks like it's setting up layouts etc and you have been playing with layout changes in your flag work. Maybe in git branch switching something was left behind, or you need to do `./gradlew clean installDebug` vs just `./gradlew installDebug`
