### ISSUE TITLE
crash when rating AnkiDroid

### ISSUE THREAD

**Issue by anlalalu** [ankidroid/Anki-Android#5653]
###### Reproduction Steps

1. A new Android emulator with no extra browser app.
2. Tap 'RATE ANKIDROID' button in 'About AnkiDroid'

###### Expected Result
Inform the user there is no browser app or other results

###### Actual Result
Crash:

FATAL EXCEPTION: main
                                                 Process: com.ichi2.anki, PID: 2638
                                                 android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=com.ichi2.anki }
                                                     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
                                                     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
                                                     at android.app.Activity.startActivityForResult(Activity.java:3424)
                                                     at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
                                                     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
                                                     at android.app.Activity.startActivityForResult(Activity.java:3385)
                                                     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:720)
                                                     at com.ichi2.anki.AnkiActivity.startActivityForResult(AnkiActivity.java:175)
                                                     at android.app.Activity.startActivity(Activity.java:3627)
                                                     at android.app.Activity.startActivity(Activity.java:3595)
                                                     at com.ichi2.anki.AnkiActivity.startActivity(AnkiActivity.java:154)
                                                     at com.ichi2.anki.Info$2.onClick(Info.java:96)
                                                     at android.view.View.performClick(View.java:4438)
                                                     at android.view.View$PerformClick.run(View.java:18422)
                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.9alpha25

Android Version = 4.4.4

ACRA UUID = aafe0f30-e91d-4478-9f8e-310ab576ea9b

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Looks like it good do with a check to see if there activities for that intent

If you have an emulator up and have built from source, could be a quick PR, like so: https://stackoverflow.com/a/29994483/9910298

**Comment by pablode** [comment]
I've just addressed this issue in PR #5671.
