### ISSUE TITLE
crash when there is no card to preview

### ISSUE THREAD

**Issue by anlalalu** [ankidroid/Anki-Android#5655]
###### Reproduction Steps

1. Tap 'card browser'
2. Tap 'more options'
3. Tap 'preview' when there is no card or when no card exists after filtering

###### Expected Result
Some information

###### Actual Result
Performing stop of activity that is not resumed: {com.ichi2.anki/com.ichi2.anki.CardBrowser}
                                                 java.lang.RuntimeException: Performing stop of activity that is not resumed: {com.ichi2.anki/com.ichi2.anki.CardBrowser}
                                                     at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3133)
                                                     at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3220)
                                                     at android.app.ActivityThread.access$1100(ActivityThread.java:135)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1223)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.9alpha25

Android Version = 4.4.4

ACRA UUID = aafe0f30-e91d-4478-9f8e-310ab576ea9b

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by anlalalu** [comment]
This issue can also be reproduced in Android 7.1.1.

Stack Trace:

E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.ichi2.anki, PID: 1537
                                                 java.lang.RuntimeException: Unable to destroy activity {com.ichi2.anki/com.ichi2.anki.Previewer}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeAllViews()' on a null object reference
                                                     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4203)
                                                     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4221)
                                                     at android.app.ActivityThread.-wrap6(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1538)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeAllViews()' on a null object reference
                                                     at com.ichi2.anki.AbstractFlashcardViewer.onDestroy(AbstractFlashcardViewer.java:924)
                                                     at android.app.Activity.performDestroy(Activity.java:6881)
                                                     at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1153)
                                                     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4190)

Screen Shot:

![image](https://user-images.githubusercontent.com/46981872/71582049-4f368e00-2b43-11ea-917e-d641b7b6fe01.png)

Do you consider this as a defect?

**Comment by mikehardy** [comment]
Definitely a defect, and crash bugs are my favorite things to fix, but I haven't been able to get to it with time available yet, and neither have others unfortunately.

I really appreciate the stack traces though, those are gold for fixing things

**Comment by chrisblue** [comment]
On v2.9.1 there is no option anymore to preview when there are no cards.

**Comment by david-allison-1** [comment]
@anlalalu, can you still reproduce this?

**Comment by anlalalu** [comment]
This has been fixed in later version. @david-allison-1
