### ISSUE TITLE
Can't start ankidroid from code anymore

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#5750]
###### Reproduction Steps

1. Clone github. Be sure to be on master or on v2.10 alpha
2. open android studio and sends ankidroid to a phone with a collection already existing
3. starts the app

###### Expected Result
Starting the app

###### Actual Result
It crashes

###### Debug info
Current master 97a1270bff57eb537944e6417a39b0ab5aa2904e

Message is E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 26030
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ichi2.anki-8I9s5k6YuIyjxxujrlvNEQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.ichi2.anki-8I9s5k6YuIyjxxujrlvNEQ==/lib/arm64, /system/lib64]]] couldn't find "libsqlite3x.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at io.requery.android.database.sqlite.SQLiteDatabase.<clinit>(SQLiteDatabase.java:87)
        at io.requery.android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
        at io.requery.android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:241)
        at io.requery.android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:174)
        at io.requery.android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:44)
        at com.ichi2.libanki.DB.<init>(DB.java:72)
        at com.ichi2.libanki.Storage.Collection(Storage.java:53)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:99)
        at com.ichi2.anki.services.BootService.onReceive(BootService.java:38)
        at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:251)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1158)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6283)
        at android.app.ActivityThread.access$1200(ActivityThread.java:240)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1806)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7124)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
D/UsageAnalytics: sendAnalyticsException() description/fatal: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ichi2.anki-8I9s5k6YuIyjxxujrlvNEQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.ichi2.anki-8I9s5k6YuIyjxxujrlvNEQ==/lib/arm64, /system/lib64]]] couldn't find "libsqlite3x.so"/true
I/ACRA: ACRA is disabled for com.ichi2.anki - forwarding uncaught Exception on to default ExceptionHandler

**Comment by Arthur-Milchior** [comment]
I tried to start from 2.9 and it works correctly.
I have currently no idea what this error message means

**Comment by mikehardy** [comment]
What system (OS Name,version) are you building on, and what device are you attempting to run on?

**Comment by Arthur-Milchior** [comment]
Ubuntu 19.04
Samsung a50
Andoid version 9
kernel version 4.14.62-16619022

**Comment by timrae** [comment]
Hmmm `couldn't find "libsqlite3x.so"`... Can you look for sqlite installation in the root filesystem?

**Comment by Arthur-Milchior** [comment]
I have no idea how to do this. Im totally new to android programming

**Comment by timrae** [comment]
It's not really anything Android specific, your device is just not able to find the sqlite library binary for some reason.

If you've done any Unix programming before you have probably come across .so files before. Mike can probably help you more, I'm just trying to help you understand what that message means and how you can start debugging.

**Comment by mikehardy** [comment]
I am using essentially the same things to reproduce (Ubuntu 19.04, a 64-bit ARM device plugged in - I checked, your phone is using Exynos 9610 chipset which is arm64), Android 9. I don't believe the linux kernel matters. I can't reproduce.

I would tell Android Studio via the File menu to "Invalidate Caches / Restart" and I would also do a `./gradlew clean` from the command line to (hopefully) clear things out. Something about the requery sqlite library isn't working correctly for you but it's definitely working from my machine on release builds and for debug builds plugged into the device

**Comment by mikehardy** [comment]
If you use Android Studio to look into the generated APK for debug after installing it on your device, you should see in the lib directory the library that's being referenced. This is what my APK looks like

**Comment by timrae** [comment]
Ahh I forgot we're using requery sqlite, not the Android system one.

**Comment by Arthur-Milchior** [comment]
Now it works again. And I didn't change anything in the way I installed ankidroid on my Android from git. I don't get it

**Comment by mikehardy** [comment]
I'm guessing local caching
