### ISSUE TITLE
Crash with no user warning when WebView updates Android 5.x

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5794]
###### Reproduction Steps

1. Remove Android System Webview updates on Samsung galaxy phone (mostly) Android 5.x
2. Open AnkiDroid
3. Run Play Store updates (to update the Android System WebView)

###### Expected Result

The App *should* reload (part of the webview update) and worst case notify the user the webview is not available

###### Actual Result

The App is reloaded but because it touches the WebView immediately on startup and the WebView is not there, it crashes

Explanation here:
https://bugs.chromium.org/p/chromium/issues/detail?id=506369#c3

Crashes here:
https://play.google.com/apps/publish/?account=5338425030304417978#AndroidMetricsErrorsPlace:p=com.ichi2.anki&appid=4973711737547064258&appVersion=20904300&lastReportedRange=LAST_14_DAYS&installSource=INSTALLED_FROM_ANYWHERE&clusterName=apps/com.ichi2.anki/clusters/d261ebbd&detailsAppVersion=20904300&detailsSpan=14&detailsInstallSource=INSTALLED_FROM_ANYWHERE

Normally I would say ignore it but we will support 5.x for a while longer and this crashes people a lot, 2-3/day so it makes our top-10 crash list.

Also, it should be an easy fix, with the proper fix being to catch this exception bubbling up, test if the webview is available ourselves, and if it is not then throw a dialog with a translated error message telling the user "AnkiDroid relies on the System WebView which is unavailable. This can happen if the system is installing updates. Please try again in a few minutes" and then an app close (since we can't work without a webview anyway)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
Do you have a stack trace? Google link 403s.

Repro steps: https://stackoverflow.com/questions/29575313/namenotfoundexception-webview

**Comment by mikehardy** [comment]
@david-allison-1 here is an example:

```
Mar 16, 8:00 AM on app version 20904300
Samsung Galaxy Note3 (hltespr), 3072MB RAM, Android 5.0
Report 1

java.lang.RuntimeException: 
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:5116)
  at android.app.ActivityThread.access$1600 (ActivityThread.java:177)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1509)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:145)
  at android.app.ActivityThread.main (ActivityThread.java:5942)
  at java.lang.reflect.Method.invoke (Method.java)
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1399)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1194)
Caused by: android.util.AndroidRuntimeException: 
  at android.webkit.WebViewFactory.getFactoryClass (WebViewFactory.java:161)
  at android.webkit.WebViewFactory.getProvider (WebViewFactory.java:101)
  at android.webkit.CookieManager.getInstance (CookieManager.java:46)
  at android.webkit.CookieManager.setAcceptFileSchemeCookies (CookieManager.java:309)
  at com.ichi2.anki.AnkiDroidApp.onCreate (AnkiDroidApp.java:220)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1020)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:5113)
  at android.app.ActivityThread.access$1600 (ActivityThread.java:177)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1509)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:145)
  at android.app.ActivityThread.main (ActivityThread.java:5942)
  at java.lang.reflect.Method.invoke (Method.java)
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1399)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1194)
Caused by: android.content.pm.PackageManager$NameNotFoundException: 
  at android.app.ApplicationPackageManager.getPackageInfo (ApplicationPackageManager.java:137)
  at android.webkit.WebViewFactory.getFactoryClass (WebViewFactory.java:133)
  at android.webkit.WebViewFactory.getProvider (WebViewFactory.java:101)
  at android.webkit.CookieManager.getInstance (CookieManager.java:46)
  at android.webkit.CookieManager.setAcceptFileSchemeCookies (CookieManager.java:309)
  at com.ichi2.anki.AnkiDroidApp.onCreate (AnkiDroidApp.java:220)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1020)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:5113)
  at android.app.ActivityThread.access$1600 (ActivityThread.java:177)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1509)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:145)
  at android.app.ActivityThread.main (ActivityThread.java:5942)
  at java.lang.reflect.Method.invoke (Method.java)
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1399)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1194)
```

**Comment by david-allison-1** [comment]
This can be replicated on an API 26 Nexus One Emulator

```
    android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
        at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:438)
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:211)
        at android.webkit.CookieManager.getInstance(CookieManager.java:39)
        at android.webkit.CookieManager.setAcceptFileSchemeCookies(CookieManager.java:265)
        at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:286)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
        at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:334)
        at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:398)
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:211) 
        at android.webkit.CookieManager.getInstance(CookieManager.java:39) 
        at android.webkit.CookieManager.setAcceptFileSchemeCookies(CookieManager.java:265) 
        at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:286) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

Let's get it fixed
