### ISSUE TITLE
[2.9 ACRA] Pre-Validate Custom Sync Server URL

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5843]
We should validate a custom sync URL on Preference save. This likely failed due to the trailing newline, which we can automatically fix.

Login appears to check the URL and shows a good message to the user.

----

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/5ca46dae-948e-4f38-8beb-0be79ed103e4

```
java.lang.IllegalArgumentException: Invalid URL port: "27708
"
at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:33)
at okhttp3.HttpUrl.get(HttpUrl.java:1)
at okhttp3.Request$Builder.url(Request.java:7)
at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:40)
at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:4)
at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:2)
at com.ichi2.libanki.sync.RemoteServer.meta(RemoteServer.java:9)
at com.ichi2.libanki.sync.Syncer.sync(Syncer.java:4)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:15)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:2)
at com.ichi2.async.Connection.doInBackground(Connection.java:4)
at com.ichi2.async.Connection.doInBackground(Connection.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:334)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:784)
```

<details><summary>Stack Trace 2</summary>

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/ae0fd7f6-7ea5-4f34-acc2-4f34073cce69

```
java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:46)
at okhttp3.HttpUrl.get(HttpUrl.java:1)
at okhttp3.Request$Builder.url(Request.java:7)
at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:35)
at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:4)
at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:2)
at com.ichi2.libanki.sync.RemoteServer.meta(RemoteServer.java:9)
at com.ichi2.libanki.sync.Syncer.sync(Syncer.java:4)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:16)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:2)
at com.ichi2.async.Connection.doInBackground(Connection.java:4)
at com.ichi2.async.Connection.doInBackground(Connection.java:1)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
```
</details>

**Comment by mikehardy** [comment]
Ironically, we didn't even see that error message until a bigger issue was fixed #5798 - this change is possible but the use of custom sync servers is so small as to be almost ignored (except to make sure they can work if properly configured), esp considering the people doing custom servers are by definition more savvy. They do see this exact message now on failure so they can probably puzzle it out pretty quickly themselves.

**Comment by david-allison-1** [comment]
Keeping alive with "Good First Issue"

**Comment by david-allison-1** [comment]
I believe: fixed in #6437

**Comment by david-allison-1** [comment]
Might need more work. User is currently using their email as the sync server URL and has problems.

Maybe because they've passed the validation and haven't tried again, maybe an email validates.

Needs further investigation

**Comment by david-allison-1** [comment]
First crash on 2.13beta, let's get this fixed now
