### ISSUE TITLE
[2.9 ACRA] NullPointerException: File Import

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5870]
First crash for 2.9.6beta4

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/fc81b2e6-c6bb-4807-8abc-b7adfb526c20

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.IntentHandler}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3516)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3668)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2193)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:7971)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
at com.ichi2.utils.ImportUtils.handleFileImport(ImportUtils.java:2)
at com.ichi2.anki.IntentHandler.onCreate(IntentHandler.java:10)
at android.app.Activity.performCreate(Activity.java:7957)
at android.app.Activity.performCreate(Activity.java:7946)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3491)
... 11 more
```

**Comment by mikehardy** [comment]
Interesting - that area of the code is such a common cause of failure, we should really log a lot more information about what we are doing as this only has stuff we can guess on.

It's always possible to import from a content provider that is virtual (say a google drive file) and those providers don't return all the data you would naively expect if you just ported code that expected a File to the content provider interfaces. Perhaps that's the root cause

Might be possible to reproduce by attempting to open an .apkg on a google drive via an android file browser

**Comment by david-allison-1** [comment]
> Interesting - that area of the code is such a common cause of failure, we should really log a lot more information about what we are doing as this only has stuff we can guess on.
> 
> It's always possible to import from a content provider that is virtual (say a google drive file) and those providers don't return all the data you would naively expect if you just ported code that expected a File to the content provider interfaces. Perhaps that's the root cause
> 
> Might be possible to reproduce by attempting to open an .apkg on a google drive via an android file browser

Tried a few file managers to repro. No luck so far. Looked through similar ACRA reports for hints and got a few leads, but couldn't get anything failing on my device. Better error information (with Intent data) is returned if the activity comes through the deckpicker.

For now, I'd like to log the intent and the extras. We can also obtain an error message which is displayed to the user.

Is there a way to extract this data from someone who has error reporting turned on, without using an exception? Otherwise, I'll make a custom exception type and log it on failure

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/b34c390b-004b-4a01-b61e-e3acb231d274 - "crash when launching from third party launcher"

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/ff05a09c-9f7a-4889-9668-5c289c9882ca - Mixplorer - tried and works on my device.

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/ca3e282c-3f5c-4d98-a7ba-f10c96bd0b32 - seems interesting
