### ISSUE TITLE
[ACRA 2.9] - deleteNotesWithWrongFieldCounts - Couldn't read row

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#5873]
Follow on from #5852 

I believe this is no longer a crashing issue as we're using `sendExceptionReport`, but we should stabilise the check.

Looks to be consistently from the same ACRA ID: https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/reports-browser/user/587e1d6b-1f93-4b4d-af94-6d50a351fc8e

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/c7c1c0e2-35ca-45c1-a7f1-874612f8e508

CustomData:
```
deleteNotesWithWrongFieldCounts row: 8281 col: 2
```

```
java.lang.IllegalStateException: Couldn't read row
at io.requery.android.database.CursorWindow.nativeGetString(Native Method)
at io.requery.android.database.CursorWindow.getString(CursorWindow.java:1)
at io.requery.android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:2)
at com.ichi2.libanki.Collection.deleteNotesWithWrongFieldCounts(Collection.java:8)
at com.ichi2.libanki.Collection.b(Collection.java:1)
at com.ichi2.libanki.n.apply(lambda)
at com.ichi2.libanki.Collection.a(Collection.java:3)
at com.ichi2.libanki.i.consume(lambda)
at com.ichi2.libanki.Collection.fixIntegrity(Collection.java:17)
at com.ichi2.async.DeckTask.doInBackgroundCheckDatabase(DeckTask.java:5)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:45)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
```

**Comment by mikehardy** [comment]
That sounds exactly like chunk-loading being a requirement to me then. A row deep in the process implying the machinery is working at a basic level, one user implying it's data-related. Error message identical to the previous need for chunk loading. All the data fits, to me. And there's an example implementation of same from the previous getString -> chunk load conversion

**Comment by dae** [comment]
Fixed by new backend.
