### ISSUE TITLE
[ACRA 2.9] BasicImageFieldController - Image Regex Failure

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5874]
Not a crash bug, but it triggers an exception handler added to diagnose the underlying cause of #5513 through an unexpected path.

This isn't the cause of #5513, but it'll add noise to ACRA, and it's a bug that we can fix

Repro steps:

1. Add a note with a field: `<img src='[validImage]' />'/>`
2. Save
3. Edit Note
4. Click Paperclip

----

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/72f0661e-6331-475f-8c0f-3c69ef456531

```
java.io.FileNotFoundException: /sdcard/AnkiDroid/collection.media/paste-12893491822593.jpg" /><div>&nbsp; &nbsp;-·-<span class="Apple-tab-span" style="white-space:pre: open failed: ENOENT (No such file or directory)
at libcore.io.IoBridge.open(IoBridge.java:496)
at java.io.FileInputStream.<init>(FileInputStream.java:159)
at com.ichi2.utils.BitmapUtil.decodeFile(BitmapUtil.java:3)
at com.ichi2.anki.multimediacard.fields.BasicImageFieldController.setPreviewImage(BasicImageFieldController.java:3)
at com.ichi2.anki.multimediacard.fields.BasicImageFieldController.createUI(BasicImageFieldController.java:3)
at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.recreateEditingUi(MultimediaEditFieldActivity.java:15)
at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.onCreate(MultimediaEditFieldActivity.java:11)
at android.app.Activity.performCreate(Activity.java:8086)
at android.app.Activity.performCreate(Activity.java:8074)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:213)
at android.app.ActivityThread.main(ActivityThread.java:8178)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
at libcore.io.Linux.open(Native Method)
at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8046)
at libcore.io.IoBridge.open(IoBridge.java:482)
... 21 more
```

<details><summary>Code Refs</summary>

Exception handler
https://github.com/ankidroid/Anki-Android/blob/2353c84b3a23c3f82c514b87c7314fb472aa38c0/AnkiDroid/src/main/java/com/ichi2/utils/BitmapUtil.java#L75-L78

Parsing code:
https://github.com/ankidroid/Anki-Android/blob/2353c84b3a23c3f82c514b87c7314fb472aa38c0/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.java#L143-L153

Assumption we have an image field:
https://github.com/ankidroid/Anki-Android/blob/2353c84b3a23c3f82c514b87c7314fb472aa38c0/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.java#L79-L80

No assumption that the file is invalid:
https://github.com/ankidroid/Anki-Android/blob/2353c84b3a23c3f82c514b87c7314fb472aa38c0/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java#L281-L290

</details>

**Comment by mikehardy** [comment]
insert "parsing html input" is hard reflexive reaction here... ;-)

**Comment by mikehardy** [comment]
out now in 2.10alpha58 as soon as google is finished processing it
