### ISSUE TITLE
[ACRA 2.9] WebViewRenderer Crash - Async NullPointerException

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5879]
Between the two lines, `cardFrame` is null, this is accessed by an AsyncTask on `blockControls`.

https://github.com/ankidroid/Anki-Android/blob/6e19f68fdc8088352e3ca8785d080e2a5f0a4276/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L1615-L1650

----

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/bbbb5b62-7867-412a-84dd-0fba1c518ff9

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.setEnabled(boolean)' on a null object reference
at com.ichi2.anki.AbstractFlashcardViewer.blockControls(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.access$1300(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer$9.onPreExecute(AbstractFlashcardViewer.java:1)
at com.ichi2.async.DeckTask$TaskListener.onPreExecute(DeckTask.java:1)
at com.ichi2.async.DeckTask.onPreExecute(DeckTask.java:2)
at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:708)
at android.os.AsyncTask.execute(AsyncTask.java:655)
at com.ichi2.async.DeckTask.launchDeckTask(DeckTask.java:2)
at com.ichi2.anki.AbstractFlashcardViewer.answerCard(AbstractFlashcardViewer.java:18)
at com.ichi2.anki.AbstractFlashcardViewer$5.onClick(AbstractFlashcardViewer.java:13)
at android.view.View.performClick(View.java:7870)
at com.ichi2.anki.AbstractFlashcardViewer$16.run(AbstractFlashcardViewer.java:2)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:7811)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

**Comment by david-allison-1** [comment]
Fixing the `cardFrame` should hopefully be easy as we can replace the variable, `mCard` will be much more of a challenge, due to implicit async state management in the card viewer.

----

I'll want to revisit #5780, now that I'm more familiar with the Viewer and concurrency issues with `AsyncTask`. I'm fairly sure we can still get PKILLed if another thread has a local reference to `mCard`
