### ISSUE TITLE
[ACRA 2.9] - Sync failure due to removal of temp files

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#5880]
Despite being in the "X bytes transferred" code, this indicates that the input file a sync HTTP request no longer exists.

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/761c2845-4c8e-4c1b-b8d3-dad7fd20fb5f

```
java.lang.RuntimeException: java.io.FileNotFoundException: /data/user/0/com.ichi2.anki/cache/syncer361883538.tmp (No such file or directory)
at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:62)
at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:4)
at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:2)
at com.ichi2.libanki.sync.RemoteServer._run(RemoteServer.java:1)
at com.ichi2.libanki.sync.RemoteServer.applyChanges(RemoteServer.java:1)
at com.ichi2.libanki.sync.Syncer.sync(Syncer.java:59)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:15)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:2)
at com.ichi2.async.Connection.doInBackground(Connection.java:4)
at com.ichi2.async.Connection.doInBackground(Connection.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
Caused by: java.io.FileNotFoundException: /data/user/0/com.ichi2.anki/cache/syncer361883538.tmp (No such file or directory)
at java.io.FileInputStream.open(Native Method)
at java.io.FileInputStream.<init>(FileInputStream.java:146)
at okio.Okio.source(Okio.java:5)
at com.ichi2.libanki.sync.CountingFileRequestBody.writeTo(CountingFileRequestBody.java:1)
at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:20)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
at com.ichi2.libanki.sync.HttpSyncer.a(HttpSyncer.java:7)
at com.ichi2.libanki.sync.a.intercept(lambda)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:7)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:22)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:22)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:9)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:13)
at okhttp3.RealCall.execute(RealCall.java:9)
at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:53)
... 15 more
```

----

<details><summary>Code</summary>

https://github.com/ankidroid/Anki-Android/blob/a91aead39315d4a0a856f2fc26417dacdd376111/AnkiDroid/src/main/java/com/ichi2/libanki/sync/CountingFileRequestBody.java#L61-L71

https://github.com/ankidroid/Anki-Android/blob/8f1e03d0332eb0cd07191cae6f1c744aca2b991a/AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java#L149

https://github.com/ankidroid/Anki-Android/blob/8f1e03d0332eb0cd07191cae6f1c744aca2b991a/AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java#L239-L243

https://github.com/ankidroid/Anki-Android/blob/8f1e03d0332eb0cd07191cae6f1c744aca2b991a/AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java#L198-L201
</details>

**Comment by david-allison-1** [comment]
I presume this is due to a cache clear during a sync, at some point between reading and writing, we lose the handle on the file.

**Comment by mikehardy** [comment]
Plausible - in my region (developing country ruled by the *cheapest* possible phones) no one has available storage and clearing cache and disk etc is practically reflexive. It's done multiple times a day, and apps are frequently uninstalled to make room for other apps which are then uninstalled to make room again for the first apps, as in the available storage is not even good enough for the true working set of apps people need. So I'm not shocked at all by the idea someone would do this, it might be standard operating procedure since they have a few minutes during the sync (poor bandwidth too)...

**Comment by dae** [comment]
Should be fixed by new backend.
