### ISSUE TITLE
[2.9 ACRA] - setAcraReportingMode crash - `Context.getResources()` was null

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5887]
This one is worrying, we could be failing to persist the "do not consent to crash logging"

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/8b41c411-30fa-4cbd-9167-bdda4b18c0c7

```
java.lang.RuntimeException: Unable to instantiate receiver com.ichi2.anki.services.ReminderService: java.lang.RuntimeException: Unable to create application com.ichi2.anki.AnkiDroidApp: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.res.Resources.getString(int)' on a null object reference
at android.app.ActivityThread.handleReceiver(ActivityThread.java:3376)
at android.app.ActivityThread.-wrap18(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.RuntimeException: Unable to create application com.ichi2.anki.AnkiDroidApp: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.res.Resources.getString(int)' on a null object reference
at android.app.LoadedApk.makeApplication(LoadedApk.java:993)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:3362)
... 8 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.res.Resources.getString(int)' on a null object reference
at android.content.Context.getString(Context.java:556)
at org.acra.config.DialogConfigurationBuilderImpl.<init>(DialogConfigurationBuilderImpl.java:8)
at org.acra.config.DialogConfigurationBuilderFactory.create(DialogConfigurationBuilderFactory.java:1)
at org.acra.config.BaseCoreConfigurationBuilder.configurationBuilders(BaseCoreConfigurationBuilder.java:5)
at org.acra.config.BaseCoreConfigurationBuilder.getPluginConfigurationBuilder(BaseCoreConfigurationBuilder.java:1)
at org.acra.config.CoreConfigurationBuilder.getPluginConfigurationBuilder(CoreConfigurationBuilder.java:1)
at com.ichi2.anki.AnkiDroidApp.setAcraReportingMode(AnkiDroidApp.java:7)
at com.ichi2.anki.AnkiDroidApp.setProductionACRAConfig(AnkiDroidApp.java:1)
at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:5)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
at android.app.LoadedApk.makeApplication(LoadedApk.java:989)
... 9 more
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
```

https://github.com/ACRA/acra/blob/master/acra-core/src/main/java/org/acra/config/BaseCoreConfigurationBuilder.java

The crashing class doesn't seem to exist in the latest version of the ACRA source.

**Comment by david-allison-1** [comment]
Good news: the path is not taken when ACRA is set to "never report".

---

After `super.onCreate()` has finished, `context.getResources()` is still null :japanese_ogre:. 

----

I presume we're getting this because the application is going through an (un)install event and the resources folder no longer exists.

It also seems that `Application.onCreate()` has been called a second time (given that ACRA logged, even though `.init()` wouldn't be called on the code path. We wouldn't get this error report if there are no resources and it's called for the first time.

I suppose our best course of action would be to detect if `onCreate()` is called a second time, with no resources, and if it is, return without performing any actions. 

@mikehardy Does this seem reasonable?

----

https://stackoverflow.com/questions/3947052/android-application-class-being-called-twice

https://stackoverflow.com/questions/17692891/getresources-returns-null

https://stackoverflow.com/questions/36763336/getstring-error-applicationoncreate-started-from-broadcastreceiver-for-actio

https://stackoverflow.com/questions/35055114/java-lang-runtimeexception-unable-to-start-receiver-com-org-app-gcm-gcmreceiver
