### ISSUE TITLE
[2.9 ACRA] CardBrowser cannot be cast to DeckPicker

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5895]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/f72b8e37-f4ff-49ab-acc5-9de181b1c8ba

```
java.lang.ClassCastException: com.ichi2.anki.CardBrowser cannot be cast to com.ichi2.anki.DeckPicker
at com.ichi2.anki.dialogs.DialogHandler.handleMessage(DialogHandler.java:6)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:201)
at android.app.ActivityThread.main(ActivityThread.java:6810)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by david-allison-1** [comment]
Theory:

DialogHandler stores the message as a static, and the underlying activity changes, but the static remains:

https://github.com/ankidroid/Anki-Android/blob/69b5925f4907829f6cd926be4399855e2d4d025b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.java#L62

I'll add logging and see if that helps pinpoint the issue

**Comment by mikehardy** [comment]
#5075

**Comment by david-allison-1** [comment]
> #5075

Closing as duplicate. Missed that in my search. Thanks!
