### ISSUE TITLE
[ACRA 2.10alpha] Card Browser - updateSearchItemQA - Template out of range

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5899]
2.10.alpha61, may be a regression

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/dba5416a-5a18-4f1c-bcf8-ef4d4f8002a1

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:354)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.RuntimeException: org.json.JSONException: Index 1 out of range [0..1)
at com.ichi2.libanki.Card.template(Card.java:5)
at com.ichi2.libanki.Card._getQA(Card.java:6)
at com.ichi2.anki.CardBrowser.updateSearchItemQA(CardBrowser.java:1)
at com.ichi2.async.DeckTask.doInBackgroundSearchCards(DeckTask.java:10)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:36)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 4 more
Caused by: org.json.JSONException: Index 1 out of range [0..1)
at org.json.JSONArray.get(JSONArray.java:293)
at org.json.JSONArray.getJSONObject(JSONArray.java:521)
at com.ichi2.libanki.Card.template(Card.java:3)
... 11 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.get(ArrayList.java:437)
at org.json.JSONArray.get(JSONArray.java:287)
... 13 more
```

**Comment by david-allison-1** [comment]
Design:

Let's assume this isn't a regression and that we have corrupt cards in the database.

We can't hide this data, as we then provide the user no control over deleting it (sans check database, which we can't assume will handle all cases), and it'll crash other aspects of the program.

Ideally, we should show that the data is corrupt, or invalid, and provide the user with the ability to delete it.

**Comment by mikehardy** [comment]
My guess is it's the template editing issue - #5151 - and I'll trigger a database check when I land it. Still hoping for 2.10 on that one I just have one bit of feedback to work through there, a complicated corner case, then it's set

**Comment by david-allison-1** [comment]
Ok, want me to close this now as a duplicate, or wait for 5151 to drop?

**Comment by mikehardy** [comment]
I think anything related to templates not existing when you expect them to be is an artifact of the data pollution that occurs in the current template editor and #5151 should fix, so yeah duplicate for now
