### ISSUE TITLE
[ACRA 2.9.6] Can not perform this action after onSaveInstanceState: REQUEST_PERMISSIONS

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#5919]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/3040620c-b10a-4bb7-81c0-2d04ae58d8ed

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.ichi2.anki/com.ichi2.anki.DeckPicker}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.app.ActivityThread.deliverResults(ActivityThread.java:3720)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:3763)
at android.app.ActivityThread.-wrap17(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5438)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:2)
at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1)
at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:12)
at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:1)
at com.ichi2.anki.DeckPicker.loadStudyOptionsFragment(DeckPicker.java:4)
at com.ichi2.anki.DeckPicker.onFinishedStartup(DeckPicker.java:15)
at com.ichi2.anki.DeckPicker.showStartupScreensAndDialogs(DeckPicker.java:8)
at com.ichi2.anki.DeckPicker.onRequestPermissionsResult(DeckPicker.java:4)
at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6597)
at android.app.Activity.dispatchActivityResult(Activity.java:6475)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3716)
... 9 more
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
```

**Comment by dae** [comment]
@david-allison is this still an issue?
