### ISSUE TITLE
[ACRA 2.9.6] - Crash: reportSizeConfigurations - ActivityRecord not found

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#5924]
Possible cause: Service ANR https://stackoverflow.com/questions/46309428/android-activitythread-reportsizeconfigurations-causes-app-to-freeze-with-black

Might be an Android bug: https://issuetracker.google.com/issues/62427912

But, since it happens on import, I'd like to assume it's our bug until proven otherwise.

----

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/4218953f-ce2b-4d2a-8d15-66fe978949dd

```
java.lang.IllegalArgumentException: reportSizeConfigurations: ActivityRecord not found for: Token{1f0291 ActivityRecord{8d7c4b8 u0 com.ichi2.anki/.IntentHandler t-1 f}}
at android.os.Parcel.createException(Parcel.java:1970)
at android.os.Parcel.readException(Parcel.java:1934)
at android.os.Parcel.readException(Parcel.java:1884)
at android.app.IActivityManager$Stub$Proxy.reportSizeConfigurations(IActivityManager.java:8636)
at android.app.ActivityThread.reportSizeConfigurations(ActivityThread.java:3309)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3268)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7091)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.am.ActivityManagerService.reportSizeConfigurations(ActivityManagerService.java:10597)
at android.app.IActivityManager$Stub.onTransact$reportSizeConfigurations$(IActivityManager.java:12574)
at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2385)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4167)
at android.os.Binder.execTransact(Binder.java:739)
```

**Comment by david-allison-1** [comment]
This is a major crasher and should be looked at. I presume it'll be fixed by showing a progress dialog from `IntentHandler` when importing

**Comment by Sofrosyn** [comment]
We can make it fancy😀😀😀

**Comment by Sofrosyn** [comment]
Definitely working on this

**Comment by Sofrosyn** [comment]
Please do assign me to this task

**Comment by mikehardy** [comment]
Great to hear @Sofrosyn ! Welcome

**Comment by dae** [comment]
@david-allison is this still happening?

**Comment by david-allison** [comment]
Haven't seen this one recently, presumed fixed
