### ISSUE TITLE
[ACRA 2.9.6] doInBackgroundSearchCards NullPointerException

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5927]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/041ac962-bf22-4519-8506-2f0ae2c63414

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:318)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:762)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
at com.ichi2.async.DeckTask.doInBackgroundSearchCards(DeckTask.java:8)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:36)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
```
```

**Comment by david-allison-1** [comment]
I converted this to a concurrent collection & I can't find a reference to it in any recent versions in ACRA
