### ISSUE TITLE
[ACRA 2.9.6] - Crash on Application Startup from Deck Browser

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5930]
###### Reproduction Steps

1. Remove permissions from AnkiDroid
2. Select text and click "Card Browser"
3. Opens Browser -> Crash -> Displays request for storage permissions

###### Expected Result

4. No Crash, likely show "welcome to AnkiDroid screen"

###### Actual Result

4. Crash

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/df680ed2-2cc9-43e0-abac-d9f10d2ff55e

```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.ichi2.libanki.Collection.getConf()' on a null object reference
at com.ichi2.anki.CardBrowser.onCreateOptionsMenu(CardBrowser.java:9)
at android.app.Activity.onCreatePanelMenu(Activity.java:3575)
at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:1)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:5)
at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:1)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7080)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by david-allison-1** [comment]
Will take this on. 6% of all ACRA crashes so far in 2.10.2
