### ISSUE TITLE
[ACRA 2.9] WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5934]
Should be an easy issue to solve, catch and check for the main exception, and show a message if this is the case.

----

AnkiDroid 2.9.5

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/cff7cc66-1b1a-4705-b677-0b1ed4f7e48e

```
java.lang.RuntimeException: Unable to create application com.ichi2.anki.AnkiDroidApp: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6065)
at android.app.ActivityThread.-wrap1(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6942)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:438)
at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:211)
at android.webkit.CookieManager.getInstance(CookieManager.java:39)
at android.webkit.CookieManager.setAcceptFileSchemeCookies(CookieManager.java:265)
at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:11)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1126)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6062)
... 8 more
Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:334)
at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:398)
... 14 more
```

**Comment by mikehardy** [comment]
Wow, with no WebView that's a hard fail for the app. Definitely should tell the user, not worry about logging (nothing we can do?) and exit

**Comment by david-allison-1** [comment]
Dupe of #5934
