### ISSUE TITLE
[ACRA 2.9.6] DecorView not attached to window manager

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#5937]
Probably going to be hard to debug. Possibly a screen rotation at the wrong time: (similar to #1146).

Might also be related to `getDelegate()`: https://stackoverflow.com/a/56195547

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/f769c958-83f4-461b-b971-b215377c9cbb

```
java.lang.IllegalArgumentException: View=DecorView@d996de0[] not attached to window manager
at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:485)
at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:380)
at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:101)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3717)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1641)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6518)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by dae** [comment]
@david-allison still happening?
