### ISSUE TITLE
[ACRA 2.9.6] AstractFlashcardViewer - Link Parsing Error - fails when typing percent sign in input

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5944]
Should be an easy one:

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/4751c711-f2ae-4b29-abef-fde2e8f4e581

```
java.lang.IllegalArgumentException: Invalid % sequence at 0: %
at libcore.net.UriCodec.decode(UriCodec.java:169)
at java.net.URLDecoder.decode(URLDecoder.java:60)
at com.ichi2.anki.AbstractFlashcardViewer$13.decodeUrl(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer$13.filterUrl(AbstractFlashcardViewer.java:11)
at com.ichi2.anki.AbstractFlashcardViewer$13.shouldOverrideUrlLoading(AbstractFlashcardViewer.java:3)
at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(PG:17)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:323)
at android.os.Looper.loop(Looper.java:143)
at android.app.ActivityThread.main(ActivityThread.java:7224)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
at android.content.ContextWrapper.startService(ContextWrapper.java:675)
```

**Comment by david-allison-1** [comment]
Repro; 

* Enable on-card input field
* Type `%`
* Crash

**Comment by david-allison-1** [comment]
This is easy to fix, but I don't understand /why/ the code is here in the first place, so I'm avoiding it for the moment.

https://github.com/ankidroid/Anki-Android/blob/371fd4719bd7768e1c8757cf410750f4f752bada/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L1541-L1548

https://github.com/ankidroid/Anki-Android/blob/371fd4719bd7768e1c8757cf410750f4f752bada/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L1644-L1652

The URLs don't seem to be encoded now, but if they are in certain versions then we're adding a regression. On my Android, a space is a space, and a percent is a percent.

**Comment by mikehardy** [comment]
via git blame it came in here, whole-cloth: https://github.com/ankidroid/Anki-Android/commit/805b923be6e141e15e83b3e5e87abad819ea2aff

I don't believe it's an ecosystem thing or an exposed API thing as I think we generate those links in the cards to implement the functionality? If I'm correct there it means we are unconstrained w.r.t. fix.

If there are no locale-related issues with handling the text coming in then maybe no need to decode?

**Comment by david-allison-1** [comment]
Looks like we have URL encoding as well. `你好` -> `typeblurtext:%E4%BD%A0%E5%A5%BD`

Got it sorted, will get in a PR after I've added tests.
