### ISSUE TITLE
[ACRA 2.9.6] Reviewer - dismissNoteAvailable - NullPointerException

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5948]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/b623afd3-2d64-4708-a3e8-3019bf8f2782

```
java.lang.NullPointerException
at com.ichi2.libanki.Note.cards(Note.java:2)
at com.ichi2.anki.Reviewer.dismissNoteAvailable(Reviewer.java:1)
at com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.java:38)
at android.app.Activity.onCreatePanelMenu(Activity.java:2490)
at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:1)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:5)
at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:1)
at android.os.Handler.handleCallback(Handler.java:725)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5041)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by david-allison-1** [comment]
Strange one, possibly a race condition.

https://github.com/ankidroid/Anki-Android/blob/06fba842013a64fd29a64a09ca4127060306d738/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java#L753-L755

**Comment by david-allison-1** [comment]
Actually... I think I fixed this via adding a reader/writer lock on `mCurrentCard`.
