### ISSUE TITLE
[ACRA 2.10alpha] Investigation: doInBackgroundAnswerCard - No result from query for note

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5951]
I feel I've seen this in our bug tracker, but I've searched and came up blank. It's fairly regular in the alpha

----

This isn't a crash bug, but we might be able to do better if we understand how it comes about. We don't have enough logging right now to diagnose the problem.

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/780066f7-66d6-44d8-be7a-84cb575eb8cd

```
java.lang.RuntimeException: Notes.load(): No result from query for note 1586324863939
at com.ichi2.libanki.Note.load(Note.java:17)
at com.ichi2.libanki.Note.<init>(Note.java:6)
at com.ichi2.libanki.Note.<init>(Note.java:1)
at com.ichi2.libanki.Collection.getNote(Collection.java:1)
at com.ichi2.libanki.Card.note(Card.java:3)
at com.ichi2.libanki.Card._getQA(Card.java:4)
at com.ichi2.libanki.Card._getQA(Card.java:2)
at com.ichi2.async.DeckTask.doInBackgroundAnswerCard(DeckTask.java:9)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:52)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
```

**Comment by david-allison-1** [comment]
Just had a useful report from @sudomain on this. I believe this will be fixed by #5151.

> unsure what happened. I was testing a cloze based note type (multiple cloze: fields and a type in the answer cloze field) when this occured. I had 5 cards, 4 of which were on the second learning step. The type in the answer field was not displaying correctly so I went from 'review mode' to 'edit note' mode, then the 'card types ' view and then preview. When I exited preview, it brought me to the decks screen and said there weren't any more cards to review. In the card browser it said that the test note I had just created wasn't in any deck. I'll see if I can reproduce it and open an issue if I can. --sudomain

**Comment by mikehardy** [comment]
Yeah, unfortunately my general assumption (based on knowing that the CardTemplateEditor used to save everything to the database while you were editing, then was unable to thoroughly revert changes or persist the correct ones) - if there is a bug in CardTemplateEditor I just assume it's based on that and am not interested in until 5151 goes in

**Comment by david-allison-1** [comment]
Haven't seen it in a while
