### ISSUE TITLE
AnkiDroid fails to run on Android R / API30 in CI (seems to work locally)

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5954]
###### Reproduction Steps

1. Use AndroidStudio to install an Android R emulator
2. Start the emulator
3. Run `./gradlew jacocoTestReport` from master as of Apr 8 2020 (at least)

###### Expected Result

Everything runs fine

###### Actual Result

There is a total failure to access the database. Probably related to scoped storage changes in the new API

This could be related to #5304 although there may be more targeted changes possible to allow successful execution on R devices

It may even just be test-related and run fine as a user-interactive application, no investigation has been performed

This was exposed by #5953

**Comment by mikehardy** [comment]
I'm investigating just a little bit, and I see inconsistent results.

The first time I started up the emulator and ran `./gradlew clean jacocoTestReport` I received failures on all the instrumented checks, with an error message mentioning database access.

So I added it to the test matrix, and I see that the APIR job fails, but on Travis it fails with this:

```
> Task :AnkiDroid:connectedDebugAndroidTest
Unable to install /home/travis/build/mikehardy/Anki-Android/AnkiDroid/build/outputs/apk/debug/AnkiDroid-debug.apk
com.android.ddmlib.InstallException: Unknown failure: cmd: Can't find service: package
	at com.android.ddmlib.Device.installRemotePackage(Device.java:1143)
	at com.android.ddmlib.Device.installPackage(Device.java:973)
	at com.android.ddmlib.Device.installPackage(Device.java:949)
	at com.android.ddmlib.Device.installPackage(Device.java:938)
	at com.android.builder.testing.ConnectedDevice.installPackage(ConnectedDevice.java:126)
	at com.android.builder.internal.testing.SimpleTestRunnable.run(SimpleTestRunnable.java:148)
	at com.android.ide.common.workers.ExecutorServiceAdapter$submit$submission$1.run(ExecutorServiceAdapter.kt:68)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Which is not something I see locally even though I am actually executing these in a similar linux environment as is used for our instrumented tests on Travis. Locally things are succeeding for me now, which is contrary to my original local experience!

Further, AnkiDroid does appear to run successfully in the APIR device when used as an actual application

Summary:
- the CI failure may be a toolchain issue, and I will need to look into the error pasted above
- AnkiDroid + APIR combo does appear to work as an application, and at least sometimes via `./gradlew jacocoTestReport` in local linux environments

To be done:
- investigate why CI fails on linux but Ubuntu 19.10 works
- test on macOS and windows as well
- check our robolectric test settings to see if they include R in their range yet

**Comment by mikehardy** [comment]
I see nothing in the release notes that indicate ongoing work in the area, and I've verified I'm using current stable of emulator and system images as is Travis, so this may be a performance/timing thing or not, but I can't find an easy root cause right now.

Since it runs as an app it won't affect users thus I'm going to put it at low priority for now, all todo tasks from previous comment are still extend

**Comment by mikehardy** [comment]
Okay, so my emulator had local corruption / issues with the sdcard mounting, and of course that led to the problems. So that was the issue that triggered investigation. Local test runs work on linux. Same experience in macOS where it works intermittently - because the sdcard sometimes does not mount correctly.

CI for R has now worked at least once, but was very slow, so this one might just be intermittent as the play store emulators are much slower than the default emulators but there is no default available yet.

Robolectric will run against the target SDK in AndroidManifest, which is 28 right now. Support for 29 comes with robolectric 4.3.1 which is pending as part of #5151 - in general moving target sdk to 29 is pending and should be done soon (deadline November 2 2020 per https://support.google.com/googleplay/android-developer/answer/113469#targetsdk) but targeting 29 for robolectric will require at least a Java9 runtime, so that's worth noting.

I'm going to resolve this one but the resolution is "flaky" with an unfortunate "waiting for upstream resolution" as they'll need to release more stable emulators I think.
