### ISSUE TITLE
[ACRA 2.10alpha64/65] - Sync Failure - Value false at dyn of type java.lang.Boolean cannot be converted to int

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5963]
@mikehardy This one looks serious.

It might be an Anki(Web) change, but since it appears to be only on the alphas, it's probably us. It doesn't look like we've modified the area from my current branch of master (maybe ec7b0356bdc6217212832bfd75a4853a6b476051, but it looks good to me). 

Changes: 
* https://github.com/ankidroid/Anki-Android/compare/v2.10alpha63...v2.10alpha64

Anything strike you as likely to have changed? I don't think I've been in this area (I didn't touch "dyn" when fixing the dynamic decks with "conf", and I haven't seen this on 2.9.6 yet).

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/ba5849de-b25d-4875-b293-0e5bc0d7f6d6

Comment(s):

> shet's broke yo

> still broken. had used a64 for days without such issue, maybe an ankiweb backend change today?

```
java.lang.RuntimeException: com.ichi2.utils.JSONException: org.json.JSONException: Value false at dyn of type java.lang.Boolean cannot be converted to int
at com.ichi2.libanki.sync.Syncer.sanityCheck(Syncer.java:53)
at com.ichi2.libanki.sync.Syncer.sync(Syncer.java:83)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:15)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:2)
at com.ichi2.async.Connection.doInBackground(Connection.java:4)
at com.ichi2.async.Connection.doInBackground(Connection.java:1)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
Caused by: com.ichi2.utils.JSONException: org.json.JSONException: Value false at dyn of type java.lang.Boolean cannot be converted to int
at com.ichi2.utils.JSONObject.getInt(JSONObject.java:2)
at com.ichi2.libanki.SchedV2._deckRevLimitSingle(SchedV2.java:2)
at com.ichi2.libanki.SchedV2._deckRevLimitSingle(SchedV2.java:1)
at com.ichi2.libanki.SchedV2._currentRevLimit(SchedV2.java:2)
at com.ichi2.libanki.SchedV2._resetRevCount(SchedV2.java:1)
at com.ichi2.libanki.SchedV2._resetRev(SchedV2.java:1)
at com.ichi2.libanki.SchedV2.reset(SchedV2.java:3)
at com.ichi2.libanki.sync.Syncer.sanityCheck(Syncer.java:36)
... 11 more
Caused by: org.json.JSONException: Value false at dyn of type java.lang.Boolean cannot be converted to int
at org.json.JSON.typeMismatch(JSON.java:101)
at org.json.JSONObject.getInt(JSONObject.java:491)
at com.ichi2.utils.JSONObject.getInt(JSONObject.java:1)
... 18 more
```

**Comment by dae** [comment]
My fault, sorry. The code was pushed to master but not yet bundled up into a beta or pushed to AnkiWeb, so it should not affect many users.

https://github.com/ankitects/anki/commit/6e6776aab2049660a4b3666cd3a9393410fbb423

**Comment by david-allison-1** [comment]
> My fault, sorry. The code was pushed to master but not yet bundled up into a beta or pushed to AnkiWeb, so it should not affect many users.
> 
> [ankitects/anki@6e6776a](https://github.com/ankitects/anki/commit/6e6776aab2049660a4b3666cd3a9393410fbb423)

Thanks! Saved me a ton of time.

**Comment by mikehardy** [comment]
Shet's broken yo! hahaha
