### ISSUE TITLE
[ACRA 2.10alpha69] - fixIntegrity/importNotes OutOfMemory: updateFieldCache

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#6012]
We currently run this over all notes in a model, or in an import. 

We should convert this to stream or batch the data. Maybe in a transaction if we're worried about integrity.

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/be4e3970-9225-4cf9-a297-cd21deff8e80

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$4.done(AsyncTask.java:399)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 89432 byte allocation with 27120 free bytes and 26KB until OOM, target footprint 536870912, growth limit 536870912
at io.requery.android.database.CursorWindow.nativeGetString(Native Method)
at io.requery.android.database.CursorWindow.getString(CursorWindow.java:1)
at io.requery.android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:2)
at com.ichi2.libanki.Collection._fieldData(Collection.java:4)
at com.ichi2.libanki.Collection.updateFieldCache(Collection.java:3)
at com.ichi2.libanki.importer.Anki2Importer._importNotes(Anki2Importer.java:65)
at com.ichi2.libanki.importer.Anki2Importer._import(Anki2Importer.java:9)
at com.ichi2.libanki.importer.Anki2Importer.run(Anki2Importer.java:3)
at com.ichi2.libanki.importer.AnkiPackageImporter.run(AnkiPackageImporter.java:39)
at com.ichi2.async.CollectionTask.doInBackgroundImportAdd(CollectionTask.java:7)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:38)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 5 more
```

**Comment by mikehardy** [comment]
#2649 #4481 #4864 #4622 - in general we handle memory poorly during import processing (where sync is a special slightly better version of import but maybe still susceptible)

This error is the classic though. It's a single string that's too large for the way requery works and you have to chunk load it, like the card templates in the model. I suspect there is at least one non-model/card templates column like this, and really any getString call on a column that contains user data should be converted to the loadColumn / chunk load style from #4744

**Comment by mikehardy** [comment]
Note for future people: AnkiDroid is migrating statistics and  libanki (which includes the scheduler) to a new style of use where instead of porting the original Python to Java, we are wrapping the Rust library that AnkiDesktop uses now. Resolution of this issue will require understanding the upstream issue in their Rust code (for scheduler/libanki) or upstream code in svelte/CSS, and fixing it there. PRs to AnkiDroid's java implementation of libanki or stats are not the desired fix at the moment unless they are extremely well-understood and targeted at fixing a small specific issue while the transition happens

**Comment by dae** [comment]
Fixed by backend update.
