### ISSUE TITLE
Fatal crash - RuntimeException: Notes.load(): No result from query for note 1586972548787

### ISSUE THREAD

**Issue by tingsu** [ankidroid/Anki-Android#6018]
###### Reproduction Steps

Now, I have not found the complete trace that leads to this crash. I will update the reproduction steps later when I have one.

###### Expected Result

No crash.

###### Actual Result

The last page where I encountered the crash.

<img src="https://user-images.githubusercontent.com/3156978/79383505-910a0980-7f65-11ea-9fab-c0f508f74c52.png" width="400" height="600" />

###### Debug info

The crash was found on the recent released version 2.9.6 on an Android 6.0 device. I searched the history issue, and found #5951 may be related to this issue. But #5951 said that was not a crash bug. But for this issue, it leads to a fatal crash. 

The crash stack:

```
 FATAL EXCEPTION: main
 Process: com.ichi2.anki, PID: 6966
 java.lang.RuntimeException: Notes.load(): No result from query for note 1586972548787
        at com.ichi2.libanki.Note.load(Note.java:17)
        at com.ichi2.libanki.Note.<init>(Note.java:6)
        at com.ichi2.libanki.Note.<init>(Note.java:1)
        at com.ichi2.libanki.Collection.getNote(Collection.java:1)
        at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment.onOptionsItemSelected(CardTemplateEditor.java:11)
        at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:3)
        at androidx.fragment.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManagerImpl.java:4)
        at androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:1)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:3)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:1)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:1)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:1)
        at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:1)
        at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:2)
        at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:2)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:1)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:2)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:4)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:1)
        at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:1)
        at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:2)
        at android.view.View.performClick(View.java:5198)
        at android.view.View$PerformClick.run(View.java:21147)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

###### Research
*Enter an [ x ] character to confirm the points below:*

[ X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ X ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ X ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hi there! I would love to know the steps to reproduce, if possible. This will need re-testing after landing #5151 as it changes everything in the area

**Comment by david-allison-1** [comment]
Reproduction Steps. 

@tingsu, I doubt this is likely to be the cause. Could you confirm whether this sounds reasonable.

1. Manage Note Types - Cards - Preview
2. Close Anki while in the previewer
3. Review the Card called "Front" which was created 
  * Theoretically, this card could be modified, but this works as long as it keeps the "DUMMY" tag.
4. Edit the note
5. Cards - Preview
7. Back
8. Preview

```
    Process: com.ichi2.anki, PID: 17571
    java.lang.RuntimeException: Notes.load(): No result from query for note 1586991657083
        at com.ichi2.libanki.Note.load(Note.java:94)
        at com.ichi2.libanki.Note.<init>(Note.java:72)
        at com.ichi2.libanki.Note.<init>(Note.java:58)
        at com.ichi2.libanki.Collection.getNote(Collection.java:487)
        at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment.onOptionsItemSelected(CardTemplateEditor.java:475)
        at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:2733)
        at androidx.fragment.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManagerImpl.java:2758)
        at androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:411)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:390)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:228)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
        at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
        at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:779)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
        at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
        at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
        at android.view.View.performClick(View.java:6659)
        at android.view.View.performClickInternal(View.java:6631)
        at android.view.View.access$3100(View.java:790)
        at android.view.View$PerformClick.run(View.java:26187)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by mikehardy** [comment]
That's the exact code that kicked off the #5151 odyssey - CardTemplateEditor currently creates a dummy card and can orphan it in the database in any of a wide range of circumstances (in addition to other shocking things it does while editing templates if you discard the edits or just quit the app without saving them)

**Comment by david-allison-1** [comment]
Probably not worth getting a copy of the collection due to the creation time of the note (15 April 2020 17:42:28.787 UTC). 

The only interesting thing to determine would be whether we have an orphaned card (which implies a different problem), or whether the card was deleted as well, and just kept in memory.

**Comment by tingsu** [comment]
@david-allison-1  Thanks a lot for coming up with the trace. I think the trace from my side is not that complicated. But the crash stack is exactly same. So, I think it hits the same issue. This issue was found by my testing tool so it is a little difficult for me to manually come up with a short enough trace, although I stored the whole long trace.

I can help to validate whether this issue still exists or not after fixing.

**Comment by tingsu** [comment]
Can I know the progress on this issue? Have it been fixed?

**Comment by mikehardy** [comment]
@tingsu have you proposed a pull request to fix it?

**Comment by tingsu** [comment]
No, I reported this issue and was not able to fix it by myself...

**Comment by mikehardy** [comment]
Then there is no status :-). It'll be here when/if it happens...
