### ISSUE TITLE
Out of memory exception

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#6066]
###### Reproduction Steps

1. Try to open AnkiDroid

It's on a really cheap tablet, digiland dl 1023 (2Gb of ram)

###### Expected Result
Anki opens

###### Actual Result
>     java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 75936992 byte allocation with 6291456 free bytes and 48MB until OOM, max allowed footprint 224039128, growth limit 268435456
        at java.lang.StringFactory.newStringFromChars(StringFactory.java:267)
        at java.lang.StringBuffer.toString(StringBuffer.java:671)
        at com.ichi2.libanki.Collection.loadColumn(Collection.java:294)
        at com.ichi2.libanki.Collection.getModels(Collection.java:2063)
        at com.ichi2.anki.CollectionHelper.loadLazyCollection(CollectionHelper.java:350)
        at com.ichi2.anki.DeckPicker.lambda$onResume$9$DeckPicker(DeckPicker.java:788)
        at com.ichi2.anki.-$$Lambda$DeckPicker$Yx-3CX3YjfS8d3nVK99cehs_1ck.run(Unknown Source:2)
        at com.ichi2.async.CollectionTask.doInBackgroundRunnable(CollectionTask.java:1580)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:357)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:73)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 

on Current master

and 
> 
2020-04-22 18:49:55.544 9944-9944/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 9944
    java.lang.OutOfMemoryError: Failed to allocate a 75936992 byte allocation with 6275072 free bytes and 53MB until OOM, max allowed footprint 219027152, growth limit 268435456
        at java.lang.StringFactory.newStringFromChars(StringFactory.java:267)
        at java.lang.StringBuffer.toString(StringBuffer.java:671)
        at com.ichi2.libanki.Collection.loadColumn(Collection.java:13)
        at com.ichi2.libanki.Collection.load(Collection.java:14)
        at com.ichi2.libanki.Collection.<init>(Collection.java:16)
        at com.ichi2.libanki.Storage.Collection(Storage.java:9)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:6)
        at com.ichi2.anki.services.BootService.onReceive(BootService.java:3)
        at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:24)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5902)
        at android.app.ActivityThread.access$1200(ActivityThread.java:206)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1678)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6702)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
2020-04-22 18:49:55.560 9944-9944/? E/ACRA: ACRA caught a OutOfMemoryError for com.ichi2.anki
    java.lang.OutOfMemoryError: Failed to allocate a 75936992 byte allocation with 6275072 free bytes and 53MB until OOM, max allowed footprint 219027152, growth limit 268435456
        at java.lang.StringFactory.newStringFromChars(StringFactory.java:267)
        at java.lang.StringBuffer.toString(StringBuffer.java:671)
        at com.ichi2.libanki.Collection.loadColumn(Collection.java:13)
        at com.ichi2.libanki.Collection.load(Collection.java:14)
        at com.ichi2.libanki.Collection.<init>(Collection.java:16)
        at com.ichi2.libanki.Storage.Collection(Storage.java:9)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:6)
        at com.ichi2.anki.services.BootService.onReceive(BootService.java:3)
        at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:24)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5902)
        at android.app.ActivityThread.access$1200(ActivityThread.java:206)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1678)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6702)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
2020-04-22 18:49:57.658 10323-10323/? I/AnkiDroid: openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
2020-04-22 18:49:59.167 10348-10348/? I/AnkiDroid: openCollection: /storage/emulated/0/AnkiDroid/collection.anki2

on current version from play store (no alpha nor beta)

Note that I can't open ankidroid so can't access debug info

###### Research
I assume the problem is that my note type is so big that the device can't have it fit in a string or a buffer.

Givne the kind of json it is, I could modify json parser to output it part by part, but I don't tihnk it would be a wise idea

**Comment by mikehardy** [comment]
You might be at the limits of your device
Or you might be to squeeze things in by applying the "growth/resize optimization" discussed here: https://www.captaincasademo.com/forum/posts/list/1503.page in loadColumn
