### ISSUE TITLE
[ACRA 2.10alpha71] - A locked database crashes "Check Database"

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6067]
We need a design for what to do if the database is locked. Presumably cancel the check.

But the UI shouldn't be working when the database is locked.

Nothing in logcat for the device aside from the stack trace.

----

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/reports-browser/user/fd9d9e7c-9e17-4df3-810e-43af4dc764e2

Sync:
```
android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
at io.requery.android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
at io.requery.android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:7)
at io.requery.android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:6)
at io.requery.android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:2)
at io.requery.android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:5)
at io.requery.android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:1)
at com.ichi2.libanki.sync.Syncer.sync(Syncer.java:6)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:16)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:2)
at com.ichi2.async.Connection.doInBackground(Connection.java:4)
at com.ichi2.async.Connection.doInBackground(Connection.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
```

Check Database:
```
android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
at io.requery.android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
at io.requery.android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:7)
at io.requery.android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:6)
at io.requery.android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:2)
at io.requery.android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:5)
at io.requery.android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:1)
at com.ichi2.libanki.Collection.fixIntegrity(Collection.java:7)
at com.ichi2.async.CollectionTask.doInBackgroundCheckDatabase(CollectionTask.java:5)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:45)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
```

Crash:
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:318)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
at io.requery.android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:2)
at io.requery.android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:1)
at io.requery.android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:2)
at com.ichi2.libanki.Collection.fixIntegrity(Collection.java:11)
at com.ichi2.async.CollectionTask.doInBackgroundCheckDatabase(CollectionTask.java:5)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:45)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
```

**Comment by david-allison-1** [comment]
Interesting... had a test and could only get this error when I `beginTransaction` from another process, doing it inside the same process would just wait forever.

This makes more sense. A locked database appears as corruption, and shows "check database" as a recovery option.

When selected, the database is still locked, and "Check Database" crashes the program.

Would be better to display a message stating that the user should close any other running instances of AnkiDroid if `Check Database` encounters this issue.

**Comment by mikehardy** [comment]
How could people have more than one? Android doesn't work that way.
Unless someone is playing around with the termux stuff and AnkiDesktop with multiple access.

Can't hurt to publicize it to the user and avoid crash but I'd say something like "your Anki collection appears to be locked by some other application, please close that application so AnkiDroid may access your collection"

or similar

**Comment by david-allison-1** [comment]
Potentially someone using the "Multiple Profile" APKs on the same collection with different settings... I couldn't begin to guess otherwise.

Already done before you posted. PR incoming

![image](https://user-images.githubusercontent.com/62114487/80917494-1f98cc00-8d57-11ea-9186-797da084c3d9.png)
