### ISSUE TITLE
[ACRA 2.10alpha71] - DeckOptions.buildLists NullPointerException

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6068]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/8fe55de8-1bbf-4854-b20c-24af21b4b1ce

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.DeckOptions}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.ListPreference.setEntries(java.lang.CharSequence[])' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.ListPreference.setEntries(java.lang.CharSequence[])' on a null object reference
at com.ichi2.anki.DeckOptions.buildLists(DeckOptions.java:10)
at com.ichi2.anki.DeckOptions$DeckPreferenceHack$Editor.commit(DeckOptions.java:130)
at com.ichi2.anki.DeckOptions$DeckPreferenceHack$Editor.apply(DeckOptions.java:1)
at android.preference.PreferenceManager.setNoCommit(PreferenceManager.java:729)
at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:347)
at android.preference.PreferenceActivity.addPreferencesFromResource(PreferenceActivity.java:1541)
at com.ichi2.anki.DeckOptions.onCreate(DeckOptions.java:15)
at android.app.Activity.performCreate(Activity.java:7824)
at android.app.Activity.performCreate(Activity.java:7813)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
... 11 more
```

**Comment by david-allison-1** [comment]
Marking as dupe: #6089
