### ISSUE TITLE
[2.9.7] Crash when collection path changed: Reviewer - Sched.eta - database was null

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#6110]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/215ff097-fbe5-407a-9d6a-8e56955006e5

Occurred when closing settings, not looking for bugs. "Don't Keep Activities" was not enabled. Sync was not enabled.

Can't replicate.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.sqlite.db.SupportSQLiteDatabase com.ichi2.libanki.DB.getDatabase()' on a null object reference
at com.ichi2.libanki.sched.Sched.eta(Sched.java:11)
at com.ichi2.anki.AbstractFlashcardViewer.updateScreenCounts(AbstractFlashcardViewer.java:7)
at com.ichi2.anki.AbstractFlashcardViewer.updateForNewCard(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.fillFlashcard(AbstractFlashcardViewer.java:10)
at com.ichi2.anki.Reviewer.fillFlashcard(Reviewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:34)
at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:14)
at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:2)
at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:10)
at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:1)
at com.ichi2.async.CollectionTask$TaskListener.onProgressUpdate(CollectionTask.java:1)
at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:4)
at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:1)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:716)
at android.os.Handler.dispatchMessage(Handler.java:112)
at android.os.Looper.loop(Looper.java:216)
at android.app.ActivityThread.main(ActivityThread.java:7625)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

logcat

```
0 | --------- beginning of main
-- | --
1 | --------- beginning of system
2 | 05-05 16:03:23.801 I/AnkiDroid(32095): Obtaining card
3 | 05-05 16:03:23.859 I/AnkiDroid(32095): Creating notification channel with id/name: General Notifications/AnkiDroid
4 | 05-05 16:03:23.861 I/AnkiDroid(32095): Creating notification channel with id/name: Synchronization/Synchronization
5 | 05-05 16:03:23.864 I/AnkiDroid(32095): Creating notification channel with id/name: Global Reminders/Cards due
6 | 05-05 16:03:24.016 I/AnkiDroid(32095): Creating notification channel with id/name: Deck Reminders/Reminders
7 | 05-05 16:03:24.018 I/AnkiDroid(32095): closeCollection: Preference Modification: collection path changed
8 | 05-05 16:03:24.022 I/AnkiDroid(32095): Collection closed
9 | 05-05 16:03:24.022 I/AnkiDroid(32095): AnkiActivity -- restartActivityInvalidateBackstack()
10 | 05-05 16:03:24.081 E/AnkiDroid(32095): Reviewer/ Could not set title in reviewer because collection closed
11 | 05-05 16:03:24.123 I/AnkiDroid(32095): openCollection: /storage/emulated/0/AnkiDroidTEST/collection.anki2
12 | --------- beginning of crash
```

**Comment by david-allison-1** [comment]
Also, while testing

```

2020-05-05 16:47:27.604 19353-19353/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 19353
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.ichi2.utils.JSONObject.has(java.lang.String)' on a null object reference
        at com.ichi2.libanki.Decks.confForDid(Decks.java:612)
        at com.ichi2.anki.AbstractFlashcardViewer.getConfigForCurrentCard(AbstractFlashcardViewer.java:2181)
        at com.ichi2.anki.AbstractFlashcardViewer.loadContentIntoCard(AbstractFlashcardViewer.java:2218)
        at com.ichi2.anki.AbstractFlashcardViewer.lambda$fillFlashcard$8$AbstractFlashcardViewer(AbstractFlashcardViewer.java:2206)
        at com.ichi2.anki.-$$Lambda$AbstractFlashcardViewer$8BjytBMw6ioa9YknPETK2LJcsts.consume(Unknown Source:6)
        at com.ichi2.anki.AbstractFlashcardViewer.lambda$processCardAction$0(AbstractFlashcardViewer.java:448)
        at com.ichi2.anki.-$$Lambda$AbstractFlashcardViewer$iGYhHuwUWNEvupUJDD5-611bphY.apply(Unknown Source:4)
        at com.ichi2.anki.AbstractFlashcardViewer.processCardFunction(AbstractFlashcardViewer.java:458)
        at com.ichi2.anki.AbstractFlashcardViewer.processCardAction(AbstractFlashcardViewer.java:447)
        at com.ichi2.anki.AbstractFlashcardViewer.fillFlashcard(AbstractFlashcardViewer.java:2206)
        at com.ichi2.anki.Reviewer.fillFlashcard(Reviewer.java:666)
        at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:2086)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1859)
        at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:677)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:563)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:540)
        at com.ichi2.async.CollectionTask$TaskListener.onProgressUpdate(CollectionTask.java:1655)
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:377)
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:73)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:716)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by david-allison-1** [comment]
Marking this as low priority as it's very rare that this will happen through normal use of the app. Will do a quick confirmation to ensure it's been present for a while

**Comment by david-allison-1** [comment]
Also in 2.9.7: https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/49dc4cbb-6650-4f17-98b6-d5e678f5111b

**Comment by dae** [comment]
Presumably fixed by new backend.
