### ISSUE TITLE
[2.10beta2] Couldn't Open Reviewer - Sched._updateCutoff: NullPointerException in println 

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6116]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/e4c5044b-5558-44d0-a4b5-7cc8a8e7095e

Sync failed due to CLEARTEXT on custom sync server.

Final log lines:

```
05-06 11:03:28.151 I/AnkiDroid( 4711): Collection closed
...
05-06 11:03:28.302 I/AnkiDroid( 4711): MetaDB:: Upgrading Internal Database finished. New version: 5
```

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.Reviewer}: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.PrintWriter.println(java.lang.String)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6718)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.PrintWriter.println(java.lang.String)' on a null object reference
at com.ichi2.libanki.Collection.log(Collection.java:9)
at com.ichi2.libanki.sched.Sched._updateCutoff(Sched.java:5)
at com.ichi2.libanki.sched.SchedV2.reset(SchedV2.java:1)
at com.ichi2.anki.Reviewer.onCollectionLoaded(Reviewer.java:7)
at com.ichi2.anki.AnkiActivity.startLoadingCollection(AnkiActivity.java:3)
at com.ichi2.anki.Reviewer.onCreate(Reviewer.java:8)
at android.app.Activity.performCreate(Activity.java:7144)
at android.app.Activity.performCreate(Activity.java:7135)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
... 11 more
```

**Comment by david-allison-1** [comment]
Also in 2.12 in a different place

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/9e89c5ba-4ed7-4c06-aa1c-6e9eaae92532

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.PrintWriter.println(java.lang.String)' on a null object referenceat com.ichi2.libanki.Collection.log(Collection.java:9)at com.ichi2.libanki.sched.SchedV2._updateCutoff(SchedV2.java:5)at com.ichi2.libanki.sched.SchedV2.reset(SchedV2.java:1)at com.ichi2.libanki.sched.SchedV2.counts(SchedV2.java:2)at com.ichi2.libanki.sched.SchedV2.counts(SchedV2.java:4)at com.ichi2.anki.AbstractFlashcardViewer.updateScreenCounts(AbstractFlashcardViewer.java:3)at com.ichi2.anki.AbstractFlashcardViewer.updateForNewCard(AbstractFlashcardViewer.java:1)at com.ichi2.anki.AbstractFlashcardViewer.fillFlashcard(AbstractFlashcardViewer.java:11)at com.ichi2.anki.Reviewer.fillFlashcard(Reviewer.java:1)at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:34)at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:15)at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1)at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:2)at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:10)at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:1)at com.ichi2.async.CollectionTask$TaskListener.onProgressUpdate(CollectionTask.java:1)at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:4)at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:1)at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:775)at android.os.Handler.dispatchMessage(Handler.java:107)at android.os.Looper.loop(Looper.java:237)at android.app.ActivityThread.main(ActivityThread.java:7811)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

**Comment by david-allison-1** [comment]
This was solved
