### ISSUE TITLE
Bug: Can't import many files with CJK filenames - filename too long

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6137]
Non-crash, but annoying

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/02a88253-f48e-4a3b-8119-c1e578ca495d

44 character Chinese filename gets expanded to 291 character URLEncoded filename which fails the import. Filename removed for user privacy.

```
ImportUtils/ Could not copy file to /data/user/0/com.ichi2.anki/cache/[FileName]
java.nio.file.FileSystemException: /data/user/0/com.ichi2.anki/cache/[FileName]: File name too long
at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
at java.nio.file.Files.deleteIfExists(Files.java:1165)
at java.nio.file.Files.copy(Files.java:3004)
at com.ichi2.compat.CompatV26.copyFile(CompatV26.java:3)
at com.ichi2.utils.ImportUtils.copyFileToCache(ImportUtils.java:2)
at com.ichi2.utils.ImportUtils.handleContentProviderFile(ImportUtils.java:15)
at com.ichi2.utils.ImportUtils.handleFileImportInternal(ImportUtils.java:11)
at com.ichi2.utils.ImportUtils.handleFileImport(ImportUtils.java:4)
at com.ichi2.anki.IntentHandler.onCreate(IntentHandler.java:11)
at android.app.Activity.performCreate(Activity.java:8066)
at android.app.Activity.performCreate(Activity.java:8054)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3733)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3939)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2373)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:213)
at android.app.ActivityThread.main(ActivityThread.java:8147)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

java.nio.file.FileSystemException: /data/user/0/com.ichi2.anki/cache/[FileName]: File name too long
at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
at java.nio.file.Files.deleteIfExists(Files.java:1165)
at java.nio.file.Files.copy(Files.java:3004)
at com.ichi2.compat.CompatV26.copyFile(CompatV26.java:3)
at com.ichi2.utils.ImportUtils.copyFileToCache(ImportUtils.java:2)
at com.ichi2.utils.ImportUtils.handleContentProviderFile(ImportUtils.java:15)
at com.ichi2.utils.ImportUtils.handleFileImportInternal(ImportUtils.java:11)
at com.ichi2.utils.ImportUtils.handleFileImport(ImportUtils.java:4)
at com.ichi2.anki.IntentHandler.onCreate(IntentHandler.java:11)
at android.app.Activity.performCreate(Activity.java:8066)
at android.app.Activity.performCreate(Activity.java:8054)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3733)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3939)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2373)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:213)
at android.app.ActivityThread.main(ActivityThread.java:8147)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

**Comment by david-allison-1** [comment]
Cause: ed06954c8c678024e2fce25c19bd6cdaf0120260

**Comment by david-allison-1** [comment]
Added to FAQ

**Comment by david-allison-1** [comment]
Reproduced with `好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好.apkg`
