### ISSUE TITLE
[ACRA 2.9.7] - SecurityException - CustomTabsClient Binder invocation to an incorrect interface

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6142]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/3b0d9894-307d-41d4-84e7-f45a898d33b0

```
java.lang.SecurityException: Binder invocation to an incorrect interface
at android.os.Parcel.readException(Parcel.java:2013)
at android.os.Parcel.readException(Parcel.java:1959)
at android.support.customtabs.ICustomTabsService$Stub$Proxy.warmup(ICustomTabsService.java:6)
at androidx.browser.customtabs.CustomTabsClient.warmup(CustomTabsClient.java:1)
at com.ichi2.compat.customtabs.CustomTabActivityHelper.onServiceConnected(CustomTabActivityHelper.java:2)
at com.ichi2.compat.customtabs.ServiceConnection.onCustomTabsServiceConnected(ServiceConnection.java:2)
at androidx.browser.customtabs.CustomTabsServiceConnection.onServiceConnected(CustomTabsServiceConnection.java:3)
at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1662)
at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1691)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6518)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by david-allison-1** [comment]
@mikehardy, this is likely an easy fix, but I don't understand: 6503e5dda718397a41de9c90e14a0a7ded0e0e37. (#5337)

Won't this method just continue a crash after calling `mClient.newSession`:

https://github.com/ankidroid/Anki-Android/blob/2733857b87384ff6391c01f953d38f93e2859cfe/AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.java#L79-L91

**Comment by mikehardy** [comment]
This appears to be slightly different than #5337 that was IllegalStateException because Tor was doing warmup wrong. The CustomTabs implementation still worked. This seems like a full CustomTabs fail. AnkiDroid does a fall back to a non-CustomTabs implementation and the code snippet you posted might crash before AnkiDroid realizes CustomTabs simply isn't available, so that's likely the issue to fix. And yes - some logging around that would be useful per #6143

**Comment by david-allison-1** [comment]
Thanks! That makes sense. Will see if I can get around to this tomorrow afternoon.
