### ISSUE TITLE
[2.10beta4] - Reviewer Crashes when rendering missing field

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6149]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/f39ff912-fba3-4445-aeb2-5f6701618067

```
java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
at java.util.regex.Matcher.reset(Matcher.java:280)
at java.util.regex.Matcher.<init>(Matcher.java:186)
at java.util.regex.Pattern.matcher(Pattern.java:1034)
at com.ichi2.libanki.Utils.stripHTMLMedia(Utils.java:1)
at com.ichi2.libanki.template.Template.render_some_sections(Template.java:8)
at com.ichi2.libanki.template.Template.render_sections(Template.java:1)
at com.ichi2.libanki.template.Template.render(Template.java:1)
at com.ichi2.libanki.Collection._renderQA(Collection.java:34)
at com.ichi2.libanki.Collection._renderQA(Collection.java:1)
at com.ichi2.libanki.Card._getQA(Card.java:12)
at com.ichi2.libanki.Card._getQA(Card.java:2)
at com.ichi2.async.CollectionTask.doInBackgroundAnswerCard(CollectionTask.java:11)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:52)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
```

**Comment by david-allison-1** [comment]
Cause (via git bisect): https://github.com/ankidroid/Anki-Android/commit/9250605808de0351e269db3e47885b60c88cf334 (#6135)

<details><summary>Test Case (merge in with another class when done)</summary>

```java
/*
 Copyright (c) 2020 David Allison <davidallisongithub@gmail.com>

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU General Public License as published by the Free Software
 Foundation; either version 3 of the License, or (at your option) any later
 version.

 This program is distributed in the hope that it will be useful, but WITHOUT ANY
 WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 PARTICULAR PURPOSE. See the GNU General Public License for more details.

 You should have received a copy of the GNU General Public License along with
 this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.ichi2.libanki.templatetest.tt;

import com.ichi2.libanki.template.Template;

import org.hamcrest.MatcherAssert;
import org.hamcrest.Matchers;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.HashMap;

import androidx.test.ext.junit.runners.AndroidJUnit4;

import static org.hamcrest.MatcherAssert.assertThat;

@RunWith(AndroidJUnit4.class)
public class TemplateTest {
    @Test
    public void testNotFoundWillRender() {
        String maybeBad = "{{#NotFound}}{{NotFound}}{{/NotFound}}";

        HashMap<String, String> context = new HashMap<>();

        Template template = new Template(maybeBad, context);
        String result = template.render();

        assertThat(result, Matchers.isEmptyString());
    }
}
```

</details>
