### ISSUE TITLE
[2.10beta3]: ViewPager - IllegalArgumentException: pointerIndex out of range : Native Method

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6153]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/3c7f31a8-4240-4dbd-a62a-06919e7d47db

```
java.lang.IllegalArgumentException: pointerIndex out of range
at android.view.MotionEvent.nativeGetAxisValue(Native Method)
at android.view.MotionEvent.getX(MotionEvent.java:2732)
at androidx.viewpager.widget.ViewPager.onInterceptTouchEvent(ViewPager.java:7)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3400)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:730)
at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1922)
at android.app.Activity.dispatchTouchEvent(Activity.java:4051)
at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:1)
at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:1)
at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:688)
at android.view.View.dispatchPointerEvent(View.java:14644)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6508)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6295)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5733)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5786)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5752)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5908)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5760)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5965)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5733)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5786)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5752)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5760)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5733)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8892)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8753)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8706)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9028)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:194)
at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:183)
at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8968)
at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9055)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
at android.view.Choreographer.doCallbacks(Choreographer.java:794)
at android.view.Choreographer.doFrame(Choreographer.java:722)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:7857)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

**Comment by david-allison-1** [comment]
Googling suggests extending `ViewPager`, catching the exception and ignoring it: https://stackoverflow.com/questions/16459196/java-lang-illegalargumentexception-pointerindex-out-of-range-exception-dispat

**Comment by mikehardy** [comment]
What the !? I'm about to do ViewPager2 though :)

**Comment by mikehardy** [comment]
ViewPager is out, long live ViewPager2
