### ISSUE TITLE
[2.10] Crash on Deck Import when no Storage Permissions Granted

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6157]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/f78c5475-7347-4f5f-a3dd-82c09631302d

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.ichi2.async.CollectionTask$TaskData.getBoolean()' on a null object reference
at com.ichi2.anki.DeckPicker$4.onPostExecute(DeckPicker.java:3)
at com.ichi2.async.CollectionTask$TaskListener.onPostExecute(CollectionTask.java:1)
at com.ichi2.async.CollectionTask.onPostExecute(CollectionTask.java:4)
at com.ichi2.async.CollectionTask.onPostExecute(CollectionTask.java:1)
at android.os.AsyncTask.finish(AsyncTask.java:755)
at android.os.AsyncTask.access$900(AsyncTask.java:192)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:7860)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Comment by david-allison-1** [comment]
Cause: null is returned from `doInBackground` if the collection could not be opened.

https://github.com/ankidroid/Anki-Android/blob/3858c3f02b8a992d121a51236ddcd4366096b214/AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java#L239-L243

**Comment by david-allison-1** [comment]
Reproduced. Explanation: https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/58ba7ddd-d1fc-4294-8df7-ba976bbca316

Regression caused by the welcome screen: #5848

If the application is loaded from the file picker, then the welcome screen is shown, rather than the permissions dialog.

But, the "Import" dialog is shown above the welcome screen. Pressing "Add" crashes the app.

**Comment by mikehardy** [comment]
No good deed unpunished in this codebase!
