### ISSUE TITLE
[2.10] Reviewer broken under language: "Thai" (th_TH)

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6160]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/e046af3a-e13a-407b-b2a2-6f9d800a3f68

```
java.util.MissingFormatArgumentException: Format specifier '%d'
at java.util.Formatter.format(Formatter.java:2522)
at java.util.Formatter.format(Formatter.java:2458)
at java.lang.String.format(String.java:2883)
at android.content.res.Resources.getQuantityString(Resources.java:514)
at com.ichi2.libanki.Utils.remainingTime(Utils.java:3)
at com.ichi2.anki.AbstractFlashcardViewer.updateScreenCounts(AbstractFlashcardViewer.java:8)
at com.ichi2.anki.AbstractFlashcardViewer.updateForNewCard(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.fillFlashcard(AbstractFlashcardViewer.java:10)
at com.ichi2.anki.Reviewer.fillFlashcard(Reviewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:34)
at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:14)
at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:2)
at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:10)
at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:1)
at com.ichi2.async.CollectionTask$TaskListener.onProgressUpdate(CollectionTask.java:1)
at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:4)
at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:1)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:715)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7078)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

**Comment by david-allison-1** [comment]
Cause: %d appears twice

https://github.com/ankidroid/Anki-Android/blob/98ee9361c5d4bea23487c05b2a3f2793d4158376/AnkiDroid/src/main/res/values-th/01-core.xml#L62-L65

**Comment by mikehardy** [comment]
This has happened before, if the translaters botch the format there is not a lot we can do unfortunately.  I'll patch it up on crowdin and re-sync language

**Comment by mikehardy** [comment]
Thai translation fixed, I took the opportunity to bring the Spanish translations to 100% :nerd_face:  and rebuilt onto master, picking now.
