### ISSUE TITLE
[ACRA 2.10] - NullPointerException: TagsDialogListener

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6174]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/32723929-52d0-44f1-8f43-27d74ba2bc0c

```
java.lang.NullPointerException: Attempt to invoke interface method 'void com.ichi2.anki.dialogs.TagsDialog$TagsDialogListener.onPositive(java.util.List, int)' on a null object reference
at com.ichi2.anki.dialogs.TagsDialog.a(TagsDialog.java:3)
at com.ichi2.anki.dialogs.p1.onClick(lambda)
at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:7)
at android.view.View.performClick(View.java:6257)
at android.widget.TextView.performClick(TextView.java:11149)
at android.view.View$PerformClick.run(View.java:23705)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6780)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1500)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1390)
```

**Comment by david-allison-1** [comment]
Reopening - change to be reverted due to use of the fragment constructor

**Comment by david-allison-1** [comment]
I'll get round to this on the next sweep: simple fix: make the activity implement the interface.

**Comment by almas33** [comment]
Hi @david-allison-1  I was looking in this issue and if I understood correctly :- implementing the for eg:
 ` AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java` this way is causing problems for `showDialogFragment(dialog)`

**Comment by david-allison-1** [comment]
This should be a simple one - move to an interface-based solution as used in our other fragments:

https://github.com/ankidroid/Anki-Android/blob/53944a2113a289541843c56e134c9c10fd459b56/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.java#L29-L35

**Comment by almas33** [comment]
That means we have to implement those functions in `TagsDialog.java` as `override` and  `nonNull` and make `interface` in  class of `activity` then we will call those functions.

**Comment by david-allison-1** [comment]
* Add the interface with relevant methods
* Have the activity implement the interface
* Add a method to get the activity, cast it to the interface
* Call the method on the interface
