### ISSUE TITLE
NullPointerException when pressing space bar

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6177]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/d167ecd1-4fb1-472f-9ff6-daa5df00158f

Judging from the LogCat, the `DeckPicker` was opened: `No startup screens required`

<details><summary>Logcat</summary>
	
```
--------- beginning of main
05-14 13:41:22.930 I/AnkiDroid(10562): AbstractFlashcardViewer:: Question successfully shown for card id 1561638421620
05-14 13:42:30.268 I/AnkiDroid(10562): AbstractFlashcardViewer:: EASE_2 pressed
05-14 13:42:30.273 I/AnkiDroid(10562): Answering card
05-14 13:42:30.275 I/AnkiDroid(10562): Answering card 1561638421620
05-14 13:42:30.302 I/AnkiDroid(10562): flush - Saving information to DB...
--------- beginning of system
05-14 13:42:30.403 I/AnkiDroid(10562): User has permissions to access collection
05-14 13:42:30.514 I/AnkiDroid(10562): colOpen: true
05-14 13:42:30.515 I/AnkiDroid(10562): No startup screens required
05-14 13:42:30.524 I/AnkiDroid(10562): Handling Activity Result: 901. Result: 52
05-14 13:42:30.526 I/AnkiDroid(10562): Creating notification channel with id/name: General Notifications/AnkiDroid
05-14 13:42:30.527 I/AnkiDroid(10562): Creating notification channel with id/name: Synchronization/Synchronisierung
05-14 13:42:30.529 I/AnkiDroid(10562): Creating notification channel with id/name: Global Reminders/Fällige Karten
05-14 13:42:30.530 I/AnkiDroid(10562): Creating notification channel with id/name: Deck Reminders/Erinnerungen
--------- beginning of crash
```

</details>

<details><summary>Stack Trace</summary>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.ichi2.libanki.Card.getODue()' on a null object reference
at com.ichi2.libanki.sched.Sched.answerButtons(Sched.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.getAnswerButtonCount(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.getDefaultEase(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.Reviewer.onKeyUp(Reviewer.java:5)
at android.view.KeyEvent.dispatch(KeyEvent.java:2772)
at android.app.Activity.dispatchKeyEvent(Activity.java:3559)
at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:1)
at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:2)
at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:3)
at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:4)
at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2)
at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:1)
at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:427)
at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5663)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5531)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5036)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5002)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5157)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5010)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5214)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5036)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5002)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5010)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5036)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5002)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5190)
at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5354)
at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2783)
at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2291)
at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2282)
at android.view.inputmethod.InputMethodManager$H.handleMessage(InputMethodManager.java:569)
at android.os.Handler.dispatchMessage(Handler.java:112)
at android.os.Looper.loop(Looper.java:216)
at android.app.ActivityThread.main(ActivityThread.java:7625)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

</details>

**Comment by david-allison-1** [comment]
This should be fixed in #6076
