### ISSUE TITLE
NoteEditor: NullPointerException on startup

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#6189]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/83ff0a52-d6a7-437e-8655-1c15705e06e2

Presumption: the provided model is null.

We use `assert` in the class, which does nothing. Might as well move to Arthur's assert method.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.NoteEditor}: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.ichi2.utils.JSONObject.getLong(java.lang.String)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2976)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3113)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1858)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:201)
at android.app.ActivityThread.main(ActivityThread.java:6820)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.ichi2.utils.JSONObject.getLong(java.lang.String)' on a null object reference
at com.ichi2.libanki.Note.<init>(Note.java:10)
at com.ichi2.libanki.Note.<init>(Note.java:2)
at com.ichi2.anki.NoteEditor.setNote(NoteEditor.java:5)
at com.ichi2.anki.NoteEditor.onCollectionLoaded(NoteEditor.java:61)
at com.ichi2.anki.AnkiActivity.startLoadingCollection(AnkiActivity.java:3)
at com.ichi2.anki.NoteEditor.onCreate(NoteEditor.java:14)
at android.app.Activity.performCreate(Activity.java:7224)
at android.app.Activity.performCreate(Activity.java:7213)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2956)
... 11 more
```

**Comment by david-allison-1** [comment]
If I'm correct, this means `models.current()` returned null, which is strange, we need more logging and assertions around this case to be sure.

**Comment by david-allison-1** [comment]
But this occurs for multiple users:

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/3197b5e3-5b0c-4401-b183-979c902c23bb

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/956787d5-8c37-4e6d-acf2-c0daa6a4a802

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/86c7af92-554d-4ee5-b08d-5a0bc5ef0336

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/7e2dc7d7-a771-4432-8196-908828891a98

**Comment by dae** [comment]
Assuming it's fixed by new backend; let's see.
