### ISSUE TITLE
Stats: Crash if database path changed during stats calculation

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6192]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/1dc1f32b-6fae-4d56-88fb-b54374aca6e6

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:309)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.sqlite.db.SupportSQLiteDatabase com.ichi2.libanki.DB.getDatabase()' on a null object reference
at com.ichi2.libanki.Stats.calculateIntervals(Stats.java:12)
at com.ichi2.anki.stats.ChartBuilder.calcStats(ChartBuilder.java:7)
at com.ichi2.anki.stats.ChartBuilder.renderChart(ChartBuilder.java:1)
at com.ichi2.anki.stats.AnkiStatsTaskHandler$CreateChartTask.doInBackground(AnkiStatsTaskHandler.java:11)
at com.ichi2.anki.stats.AnkiStatsTaskHandler$CreateChartTask.doInBackground(AnkiStatsTaskHandler.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
```

**Comment by david-allison-1** [comment]
This appears multiple times in the logs, generating a lot of noise. One of the few from the 2.9.6 era that I didn't get around to fixing
