### ISSUE TITLE
DeckPicker - Crash attempting to access unavailable deck 

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6208]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/f9318ffd-c743-43b3-8246-cbbb77eadf17

Definitely seen in 2.10.x, unknown if it was seen beforehand

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.ichi2.utils.JSONObject.getString(java.lang.String)' on a null object reference
at com.ichi2.libanki.Decks.select(Decks.java:1)
at com.ichi2.anki.DeckPicker.handleDeckSelection(DeckPicker.java:3)
at com.ichi2.anki.DeckPicker.access$100(DeckPicker.java:1)
at com.ichi2.anki.DeckPicker$1.onClick(DeckPicker.java:5)
at android.view.View.performClick(View.java:6312)
at android.view.View$PerformClick.run(View.java:24811)
at android.os.Handler.handleCallback(Handler.java:794)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:176)
at android.app.ActivityThread.main(ActivityThread.java:6651)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
```

<details><summary>Logcat</summary>

```
0	--------- beginning of main
1	05-18 00:31:32.039 I/AnkiDroid(21110): Creating notification channel with id/name: General Notifications/AnkiDroid
2	05-18 00:31:32.058 I/AnkiDroid(21110): Creating notification channel with id/name: Synchronization/Sincronización
3	05-18 00:31:32.064 I/AnkiDroid(21110): Creating notification channel with id/name: Global Reminders/Tarjetas pendientes
4	05-18 00:31:32.087 I/AnkiDroid(21110): Creating notification channel with id/name: Deck Reminders/Recordatorios
5	05-18 00:31:33.650 I/AnkiDroid(21110): Back key pressed
6	05-18 00:32:17.603 I/AnkiDroid(21110): Launching DeckPicker
7	05-18 00:32:17.914 I/AnkiDroid(21110): User has permissions to access collection
8	05-18 00:32:18.017 I/AnkiDroid(21110): colOpen: true
9	05-18 00:32:18.018 I/AnkiDroid(21110): No startup screens required
10	05-18 00:32:27.357 I/AnkiDroid(21110): DeckPicker:: Sync button pressed
11	05-18 00:32:27.371 W/AnkiDroid(21110): DeckPicker/ User not logged in
12	05-18 00:32:28.931 W/AnkiDroid(21110): AnkiActivity/ Couldn't preload url: https://ankiweb.net/account/register
13	05-18 00:33:11.296 E/AnkiDroid(21110): MyAccount/ Login failed, error code 403
14	05-18 00:33:31.080 I/AnkiDroid(21110): User successfully logged in!
15	05-18 00:33:31.212 I/AnkiDroid(21110): Handling Activity Result: 6. Result: -1
16	05-18 00:33:31.215 I/AnkiDroid(21110): Creating notification channel with id/name: General Notifications/AnkiDroid
17	05-18 00:33:31.216 I/AnkiDroid(21110): Creating notification channel with id/name: Synchronization/Sincronización
18	05-18 00:33:31.241 I/AnkiDroid(21110): Creating notification channel with id/name: Global Reminders/Tarjetas pendientes
19	05-18 00:33:31.246 I/AnkiDroid(21110): Creating notification channel with id/name: Deck Reminders/Recordatorios
20	05-18 00:33:31.285 I/AnkiDroid(21110): Performing Sync on Resume
21	05-18 00:33:31.314 I/AnkiDroid(21110): Sync - starting sync
22	05-18 00:33:31.707 I/AnkiDroid(21110): Sync: getting meta data from server
23	05-18 00:33:31.711 I/AnkiDroid(21110): Sync: building local meta data
24	05-18 00:33:31.711 I/AnkiDroid(21110): Sync: full sync necessary - returning
25	05-18 00:33:31.713 I/AnkiDroid(21110): Sync Finished - Closing Collection
26	05-18 00:33:31.718 I/AnkiDroid(21110): Collection closed
27	05-18 00:33:31.761 I/AnkiDroid(21110): openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
28	05-18 00:33:56.867 I/AnkiDroid(21110): Sync - fullsync - download collection
29	05-18 00:33:57.381 I/AnkiDroid(21110): Closing collection for full sync
30	05-18 00:33:57.383 I/AnkiDroid(21110): Collection closed
31	05-18 00:33:57.595 I/AnkiDroid(21110): Reopening Database
32	--------- beginning of system
33	05-18 00:38:59.575 I/AnkiDroid(21110): Sync Finished - Closing Collection
34	05-18 00:38:59.576 I/AnkiDroid(21110): Collection closed
35	05-18 00:38:59.577 I/AnkiDroid(21110): openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
36	05-18 00:42:04.330 I/AnkiDroid(21110): DeckPicker:: Sync button pressed
37	05-18 00:42:04.365 I/AnkiDroid(21110): Sync - starting sync
38	05-18 00:42:04.944 I/AnkiDroid(21110): Sync: getting meta data from server
39	05-18 00:42:04.945 I/AnkiDroid(21110): Sync: building local meta data
40	05-18 00:42:04.946 I/AnkiDroid(21110): Sync: no changes - returning
41	05-18 00:42:05.491 I/AnkiDroid(21110): Sync Finished - Closing Collection
42	05-18 00:42:05.492 I/AnkiDroid(21110): Collection closed
43	05-18 00:45:25.170 I/AnkiDroid(21110): User successfully logged in!
44	05-18 00:45:25.301 I/AnkiDroid(21110): Handling Activity Result: 6. Result: -1
45	05-18 00:45:25.314 I/AnkiDroid(21110): Creating notification channel with id/name: General Notifications/AnkiDroid
46	05-18 00:45:25.315 I/AnkiDroid(21110): Creating notification channel with id/name: Synchronization/Sincronización
47	05-18 00:45:25.341 I/AnkiDroid(21110): Creating notification channel with id/name: Global Reminders/Tarjetas pendientes
48	05-18 00:45:25.346 I/AnkiDroid(21110): Creating notification channel with id/name: Deck Reminders/Recordatorios
49	05-18 00:45:25.389 I/AnkiDroid(21110): Performing Sync on Resume
50	05-18 00:45:25.417 I/AnkiDroid(21110): openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
51	05-18 00:45:25.437 I/AnkiDroid(21110): Sync - starting sync
52	05-18 00:45:25.799 I/AnkiDroid(21110): Sync: getting meta data from server
53	05-18 00:45:25.801 I/AnkiDroid(21110): Sync: building local meta data
54	05-18 00:45:25.801 I/AnkiDroid(21110): Sync: no changes - returning
55	05-18 00:45:26.188 I/AnkiDroid(21110): Sync Finished - Closing Collection
56	05-18 00:45:26.190 I/AnkiDroid(21110): Collection closed
57	05-18 00:47:11.281 I/AnkiDroid(21110): DeckPicker:: Selected deck with id 1589750620648
58	05-18 00:47:11.281 I/AnkiDroid(21110): openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
59	--------- beginning of crash
60	
```

</details>

**Comment by david-allison-1** [comment]
I'll add some more logging around the issue, but this will likely be a tough one to solve - the implication is that the deck list wasn't refreshed after all of those syncs, which seems unlikely.

**Comment by david-allison-1** [comment]
Bad bot!

**Comment by david-allison-1** [comment]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/4d72b61c-30b1-444c-a89c-34ba94de1740

**Comment by david-allison-1** [comment]
Cause: deck no longer exists after a sync
```
0	--------- beginning of main
1	09-17 13:02:11.919 I/AnkiDroid( 959): AnkiActivity::onCreate - MyAccount
2	09-17 13:02:11.922 W/AnkiDroid( 959): AnkiActivity/ Couldn't preload url: https://ankiweb.net/account/register
3	09-17 13:02:11.971 I/AnkiDroid( 959): AnkiActivity::onStart - MyAccount
4	09-17 13:02:11.975 I/AnkiDroid( 959): AnkiActivity::onResume - MyAccount
5	09-17 13:02:26.671 I/AnkiDroid( 959): User successfully logged in!
6	09-17 13:02:28.229 I/AnkiDroid( 959): MyAccount - onBackPressed()
7	09-17 13:02:28.230 I/AnkiDroid( 959): finishWithAnimation 2
8	09-17 13:02:28.239 I/AnkiDroid( 959): AnkiActivity::onPause - MyAccount
9	09-17 13:02:28.268 E/AnkiDroid( 959): Preferences/ Preferences: no preference found for the key: custom_sync_server_link
10	09-17 13:02:28.269 E/AnkiDroid( 959): Preferences/ Preferences: no preference found for the key: advanced_statistics_link
11	09-17 13:02:28.889 I/AnkiDroid( 959): AnkiActivity::onStop - MyAccount
12	09-17 13:02:28.892 I/AnkiDroid( 959): AnkiActivity::onDestroy - MyAccount
13	09-17 13:02:30.965 I/AnkiDroid( 959): Handling Activity Result: 100. Result: 0
14	09-17 13:02:30.968 I/AnkiDroid( 959): AnkiActivity -- restartActivity()
15	09-17 13:02:30.983 I/AnkiDroid( 959): finishWithoutAnimation
16	09-17 13:02:31.027 I/AnkiDroid( 959): User has permissions to access collection
17	09-17 13:02:31.027 I/AnkiDroid( 959): AnkiActivity::onCreate - DeckPicker
18	09-17 13:02:31.061 I/AnkiDroid( 959): colOpen: true
19	09-17 13:02:31.061 I/AnkiDroid( 959): No startup screens required
20	09-17 13:02:31.065 I/AnkiDroid( 959): AnkiActivity::onStart - DeckPicker
21	09-17 13:02:31.068 I/AnkiDroid( 959): AnkiActivity::onResume - DeckPicker
22	09-17 13:02:31.149 I/AnkiDroid( 959): Updating deck list UI
23	09-17 13:02:31.237 I/AnkiDroid( 959): AnkiActivity::onDestroy - DeckPicker
24	09-17 13:02:31.272 I/AnkiDroid( 959): Updating deck list UI
25	09-17 13:02:31.944 I/AnkiDroid( 959): DeckPicker:: Sync button pressed
26	09-17 13:02:31.962 I/AnkiDroid( 959): Sync - starting sync
27	09-17 13:02:33.249 I/AnkiDroid( 959): Sync: getting meta data from server
28	09-17 13:02:33.251 I/AnkiDroid( 959): Sync: building local meta data
29	09-17 13:02:33.253 I/AnkiDroid( 959): Sync: no changes - returning
30	09-17 13:02:33.254 I/AnkiDroid( 959): Sync Finished - Closing Collection
31	09-17 13:02:33.257 E/SQLiteLog( 959): (28) file unlinked while open: /storage/emulated/0/AnkiDroid/collection.anki2
32	09-17 13:02:33.258 E/SQLiteLog( 959): (28) file unlinked while open: /storage/emulated/0/AnkiDroid/collection.media.ad.db2
33	09-17 13:02:33.258 I/AnkiDroid( 959): Closing Collection Log
34	09-17 13:02:33.259 I/AnkiDroid( 959): Collection closed
35	09-17 13:02:36.997 I/AnkiDroid( 959): DeckPicker:: Selected deck with id 1592924760565
36	09-17 13:02:37.000 I/AnkiDroid( 959): Begin openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
37	09-17 13:02:37.377 I/AnkiDroid( 959): Opening Collection Log
38	09-17 13:02:37.634 I/AnkiDroid( 959): flush - Saving information to DB...
39	09-17 13:02:37.650 I/AnkiDroid( 959): End openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
```

**Comment by dae** [comment]
Assuming this is fixed in new backend.
