### ISSUE TITLE
Reviewer - OnRenderProcessGone Crash - You cannot show a dialog before an Activity is created or after it's hidden

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6244]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/896af9d5-cb72-4c8e-8ba1-6e3e0f233819

```
com.afollestad.materialdialogs.MaterialDialog$DialogException: Bad window token, you cannot show a dialog before an Activity is created or after it's hidden.
at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:2)
at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:2)
at com.ichi2.anki.AbstractFlashcardViewer$CardViewerWebClient.displayRenderLoopDialog(AbstractFlashcardViewer.java:13)
at com.ichi2.anki.AbstractFlashcardViewer$CardViewerWebClient.onRenderProcessGone(AbstractFlashcardViewer.java:24)
at gk.a(PG:1)
at org.chromium.android_webview.AwContents.onRenderProcessGone(PG:9)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:326)
at android.os.Looper.loop(Looper.java:160)
at android.app.ActivityThread.main(ActivityThread.java:6898)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by jianersswlq** [comment]
I am a little confused that how to reproduce this bug? The link I open is with nothing to show. Could you give some tips to understand that bug? Thanks a lot.

**Comment by david-allison-1** [comment]
Thanks for the help!!

> I am a little confused that how to reproduce this bug? The link I open is with nothing to show. Could you give some tips to understand that bug? Thanks a lot.

This issue originally came about due to #5780. Users with really heavy fonts (typically Japanese) would cause the WebView Renderer to crash, this sent a `SIGKILL` to AnkiDroid, which meant we had no error logs or visibility over the issue.

I fixed this while fairly new to the project in #5820. 

----

RE: ACRAlyzer: ask @mikehardy. Reported on a OnePlus 5. Logcat is uninteresting (we should be logging lifecycle events - I'll get around to it today).
num | line
-- | --
43 | 05-21 22:23:14.145 I/AnkiDroid(21335): Answering card 1538960043376
44 | 05-21 22:23:14.174 I/AnkiDroid(21335): AbstractFlashcardViewer:: Question successfully shown for card id 1538960043372
45 | 05-21 22:23:19.951 I/AnkiDroid(21335): AbstractFlashcardViewer:: Show answer button pressed
46 | 05-21 22:23:22.941 I/AnkiDroid(21335): AbstractFlashcardViewer:: EASE_3 pressed
47 | 05-21 22:23:22.944 I/AnkiDroid(21335): Answering card
48 | 05-21 22:23:22.945 I/AnkiDroid(21335): Answering card 1538960043372
49 | 05-21 22:23:22.963 I/AnkiDroid(21335): AbstractFlashcardViewer:: Question successfully shown for card id 1538960043431
50 | 05-21 22:23:24.340 I/AnkiDroid(21335): Obtaining write lock for card
51 | 05-21 22:23:24.341 I/AnkiDroid(21335): Obtained write lock for card
52 | 05-21 22:23:24.341 E/AnkiDroid(21335): AbstractFlashcardViewer$CardViewerWebClient/ WebView Renderer process terminated. Crashed: true
53 | 05-21 22:23:24.390 E/AnkiDroid(21335): AbstractFlashcardViewer$CardViewerWebClient/ Web Renderer crash loop on card: 1538960043873
54 | --------- beginning of crash


----

Reproduction of the issue is still TBC. It's likely easier to reproduce with an automated test, or a temporary code change:

I'd go about it as:

* Call `crashWebViewRenderer();` in `displayAnswer()`
* Modify `webViewRendererLastCrashedOnCard` to return true
* Call `finishWithoutAnimation();` after `crashWebViewRenderer`

Unit Testing may also be possible.

----

If this can't be reproduced, I'd be fine with: 

* Using a technique listed on: https://stackoverflow.com/questions/34481525/bad-window-token-you-cannot-show-a-dialog-before-an-activity-is-created-or-afte to determine if we can display the dialog, and use `UIUtils.showThemedToast` otherwise
* Wrap the call in a try..catch... with `AnkiDroidApp.sendExceptionReport(e, "displayRenderLoopDialog"` in the catch block
* (Nice to have/optional) Returning the error message so the next screen can deal with it. Possibly as a notification, implementer's choice

**Comment by dae** [comment]
@david-allison still an issue?

**Comment by david-allison** [comment]
Still looks like it can happen, unconfirmed

**Comment by Boopana-M** [comment]
Hi, I’ve been studying this crash.
It looks like the dialog is being shown from onRenderProcessGone() while the Activity may already be paused or destroyed, which causes the BadTokenException.

I’m planning to investigate adding lifecycle safety checks before showing the dialog (e.g., checking isFinishing / isDestroyed or using lifecycle-aware dispatch).

I’m still learning the codebase, so I may need some guidance. Is it okay if I work on this issue?
