### ISSUE TITLE
A network error has occurred. SSLException while building HttpClient (2020-05-30)

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6317]
Reproduced on my API 16 emulator, hasn't used AnkiWeb before, so this probably isn't a caching issue

```
E/HttpSyncer: SSLException while building HttpClient
    javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:374)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
        at okhttp3.RealCall.execute(RealCall.java:93)
        at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:237)
        at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:171)
        at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:161)
        at com.ichi2.libanki.sync.RemoteServer.hostKey(RemoteServer.java:51)
        at com.ichi2.async.Connection.doInBackgroundLogin(Connection.java:210)
        at com.ichi2.async.Connection.doOneInBackground(Connection.java:192)
        at com.ichi2.async.Connection.doInBackground(Connection.java:185)
        at com.ichi2.async.Connection.doInBackground(Connection.java:51)
        at android.os.AsyncTask$2.call(AsyncTask.java:287)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:137)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
        at java.lang.Thread.run(Thread.java:856)
     Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:192)
        at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:163)
        at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:573)
        at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
        at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:371)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320) 
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284) 
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169) 
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258) 
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135) 
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) 
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257) 
        at okhttp3.RealCall.execute(RealCall.java:93) 
        at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:237) 
        at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:171) 
        at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:161) 
        at com.ichi2.libanki.sync.RemoteServer.hostKey(RemoteServer.java:51) 
        at com.ichi2.async.Connection.doInBackgroundLogin(Connection.java:210) 
        at com.ichi2.async.Connection.doOneInBackground(Connection.java:192) 
        at com.ichi2.async.Connection.doInBackground(Connection.java:185) 
        at com.ichi2.async.Connection.doInBackground(Connection.java:51) 
        at android.os.AsyncTask$2.call(AsyncTask.java:287) 
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:137) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
        at java.lang.Thread.run(Thread.java:856) 
     Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:192) 
        at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:163) 
        at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:573) 
        at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method) 
        at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:371) 
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320) 
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284) 
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169) 
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258) 
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135) 
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) 
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257) 
        at okhttp3.RealCall.execute(RealCall.java:93) 
        at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:237) 
        at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:171) 
        at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:161) 
        at com.ichi2.libanki.sync.RemoteServer.hostKey(RemoteServer.java:51) 
        at com.ichi2.async.Connection.doInBackgroundLogin(Connection.java:210) 
        at com.ichi2.async.Connection.doOneInBackground(Connection.java:192) 
        at com.ichi2.async.Connection.doInBackground(Connection.java:185) 
        at com.ichi2.async.Connection.doInBackground(Connection.java:51) 
        at android.os.AsyncTask$2.call(AsyncTask.java:287) 
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:137) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
        at java.lang.Thread.run(Thread.java:856) 
E/MyAccount: Login failed, error code 0
D/UsageAnalytics: sendAnalyticsScreenView(): SimpleMessageDialog
    getOptIn() status: false
D/EGL_emulation: eglMakeCurrent: 0xb8c59090: ver 2 0
```

Sample from a real user:

```
Debug information: AnkiDroid Version = 2.10.3

Android Version = 4.4.4

ACRA UUID = 6d464b95-d2d8-4c74-8402-00bd96cf28b8
```

Also reported on Android 5.0.2

**Comment by BlueGreenMagick** [comment]
I am also experiencing what I think is the same problem. Attempting to sync leads to a sync error of 
```
Connection timed out ...(skipped)... large file in your media folder. 
SSLException while building HttpClient
``` 
Clearing cache did not work. I think it synced fine the day before.

```
AnkiDroid Version = 2.10.3 (Updated Ankidroid after having sync issues. Not sure which version it was on before)
Android Version = 4.4.2
```

**Comment by david-allison-1** [comment]
Thrown: `sslSocket.startHandshake`. I assume this is an API < 22 issue:

https://github.com/ankidroid/Anki-Android/blob/dc0c5d37af51b268d434972bf02ed4596f03206c/AnkiDroid/src/main/java/com/ichi2/libanki/sync/Tls12SocketFactory.java

**Comment by david-allison-1** [comment]
@BlueGreenMagick, can you perform the tests listed: http://testsites.test.certificatetest.com/

**Comment by BlueGreenMagick** [comment]
@david-allison-1 Can you clarify what I am supposed to do on the webpage? - what shows up when I have a certificate vs when I don't?

All of the 3 links to the test loads with 'Certificate issued from ...'.

**Comment by david-allison-1** [comment]
@BlueGreenMagick, I get the same behaviour (scary warning) on the second link.

I've imported the certificate into AnkiDroid, and now it's slow to connect, but it sync fine.

**Comment by david-allison-1** [comment]
Cause: https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020

**Comment by mikehardy** [comment]
Version 2.10.4 is processing for release right now and should contain the fix


Version 2.10.4


== Version 2.10.4 (2020-05-31)
* Workaround expired AnkiWeb SSL Root certificate
* More details: https://github.com/ankidroid/Anki-Android/milestone/22?closed=1

**Comment by BlueGreenMagick** [comment]
Thank you for the quick fix! 2.10.4 works

**Comment by david-allison-1** [comment]
> Thank you for the quick fix! 2.10.4 works

No worries! Thanks for the issue confirmation/proof of the issue.

**Comment by adrianN** [comment]
See also #6315

**Comment by kodovanie** [comment]
Hi all, I just want to add that I am experiencing also the same or similar problem:

Sync error
Connection timed out. Either your internet connection is experiencing problems, or you have a very large file in your media folder.

SSLException while building HttpClient.

Android version: 4.1.2.
Ankidroid version: 2.10.2

After updating to Ankidroid 2.10.4 the synch was successful. Thank you very much.

Moreover I would like to ask in case I encounter synch problem in the future, is it possible to do manual synch via USB by simply copying certain files from Ankidroid to Anki desktop? Or is there a risk of corrupting my files by doing so?

**Comment by david-allison-1** [comment]
> Hi all, I just want to add that I am experiencing also the same or similar problem:
> 
> Sync error
> Connection timed out. Either your internet connection is experiencing problems, or you have a very large file in your media folder.
> 
> SSLException while building HttpClient.
> 
> Android version: 4.1.2.
> Ankidroid version: 2.10.2
> 
> After updating to Ankidroid 2.10.4 the synch was successful. Thank you very much.
> 
> Moreover I would like to ask in case I encounter synch problem in the future, is it possible to do manual synch via USB by simply copying certain files from Ankidroid to Anki desktop? Or is there a risk of corrupting my files by doing so?

Hi, @kodovanie. Please upgrade to 2.10.4. This should fix your issue.

**Comment by rafaelsb0** [comment]
Hi! Still not working for my 4.0.3 android tablet

**Comment by mikehardy** [comment]
@rafaelsb0 it will never work for Android 4.0, there is simply no support on those older devices for TLS1.2. Your only option is to upgrade your device so it has a newer Android OS, or install and use https://github.com/tsudoko/anki-sync-server where you can control the SSL support and thus use TLS1.1 or lower.

**Comment by rafaelsb0** [comment]
@mikehardy . Thanks. I defined my extSD card as database location for Ankidroid in my smartphone and the older tablet. So I can study on the older tablet and sync in the smartphone. It works. :)
