### ISSUE TITLE
Card Browser: onCreateOptionsMenu Crash

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#6371]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/f614ec95-6d6a-4fe9-9d21-c397f6afcb0e

I don't think this is caused by the permissions error now, but the collection did fail to load.

This feels like the first load ever - would be the first avenue for testing.

DeckPath: `/storage/emulated/0/AnkiDroid`.

<details><summary>Logcat</summary>

```
1 | 06-04 00:06:00.681 I/AnkiDroid( 4550): AnkiActivity::onStart
-- | --
2 | 06-04 00:06:00.683 E/AnkiDroid( 4550): CollectionHelper/ Could not initialize AnkiDroid directory
3 | 06-04 00:06:00.683 E/AnkiDroid( 4550): com.ichi2.anki.exception.StorageAccessException: Failed to create AnkiDroid directory
4 | 06-04 00:06:00.683 E/AnkiDroid( 4550): at com.ichi2.anki.CollectionHelper.initializeAnkiDroidDirectory(CollectionHelper.java:3)
5 | 06-04 00:06:00.683 E/AnkiDroid( 4550): at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:3)
6 | 06-04 00:06:00.683 E/AnkiDroid( 4550): at com.ichi2.async.CollectionLoader.doInBackground(CollectionLoader.java:5)
7 | 06-04 00:06:00.683 E/AnkiDroid( 4550): at com.ichi2.async.CollectionLoader.doInBackground(CollectionLoader.java:1)
8 | 06-04 00:06:00.683 E/AnkiDroid( 4550): at android.os.AsyncTask$2.call(AsyncTask.java:333)
9 | 06-04 00:06:00.683 E/AnkiDroid( 4550): at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10 | 06-04 00:06:00.683 E/AnkiDroid( 4550): at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
11 | 06-04 00:06:00.683 E/AnkiDroid( 4550): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
12 | 06-04 00:06:00.683 E/AnkiDroid( 4550): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
13 | 06-04 00:06:00.683 E/AnkiDroid( 4550): at java.lang.Thread.run(Thread.java:764)
14 | 06-04 00:06:00.683 E/AnkiDroid( 4550):
15 | 06-04 00:06:00.683 E/AnkiDroid( 4550): com.ichi2.anki.exception.StorageAccessException: Failed to create AnkiDroid directory
16 | 06-04 00:06:00.683 E/AnkiDroid( 4550): at com.ichi2.anki.CollectionHelper.initializeAnkiDroidDirectory(CollectionHelper.java:3)
17 | 06-04 00:06:00.683 E/AnkiDroid( 4550): at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:3)
18 | 06-04 00:06:00.683 E/AnkiDroid( 4550): at com.ichi2.async.CollectionLoader.doInBackground(CollectionLoader.java:5)
19 | 06-04 00:06:00.683 E/AnkiDroid( 4550): at com.ichi2.async.CollectionLoader.doInBackground(CollectionLoader.java:1)
20 | 06-04 00:06:00.683 E/AnkiDroid( 4550): at android.os.AsyncTask$2.call(AsyncTask.java:333)
21 | 06-04 00:06:00.683 E/AnkiDroid( 4550): at java.util.concurrent.FutureTask.run(FutureTask.java:266)
22 | 06-04 00:06:00.683 E/AnkiDroid( 4550): at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
23 | 06-04 00:06:00.683 E/AnkiDroid( 4550): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
24 | 06-04 00:06:00.683 E/AnkiDroid( 4550): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
25 | 06-04 00:06:00.683 E/AnkiDroid( 4550): at java.lang.Thread.run(Thread.java:764)
26 | 06-04 00:06:00.705 I/AnkiDroid( 4550): AnkiActivity::onResume
27 | 06-04 00:06:00.870 E/AnkiDroid( 4550): CollectionHelper/ Could not initialize AnkiDroid directory
28 | 06-04 00:06:00.870 E/AnkiDroid( 4550): com.ichi2.anki.exception.StorageAccessException: Failed to create AnkiDroid directory
29 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at com.ichi2.anki.CollectionHelper.initializeAnkiDroidDirectory(CollectionHelper.java:3)
30 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:3)
31 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at com.ichi2.anki.AnkiActivity.getCol(AnkiActivity.java:1)
32 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at com.ichi2.anki.CardBrowser.onCreateOptionsMenu(CardBrowser.java:9)
33 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at android.app.Activity.onCreatePanelMenu(Activity.java:3388)
34 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:1)
35 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
36 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2)
37 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
38 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:5)
39 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:1)
40 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at android.os.Handler.handleCallback(Handler.java:790)
41 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at android.os.Handler.dispatchMessage(Handler.java:99)
42 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at android.os.Looper.loop(Looper.java:164)
43 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at android.app.ActivityThread.main(ActivityThread.java:6494)
44 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at java.lang.reflect.Method.invoke(Native Method)
45 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
46 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
47 | 06-04 00:06:00.870 E/AnkiDroid( 4550):
48 | 06-04 00:06:00.870 E/AnkiDroid( 4550): com.ichi2.anki.exception.StorageAccessException: Failed to create AnkiDroid directory
49 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at com.ichi2.anki.CollectionHelper.initializeAnkiDroidDirectory(CollectionHelper.java:3)
50 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:3)
51 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at com.ichi2.anki.AnkiActivity.getCol(AnkiActivity.java:1)
52 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at com.ichi2.anki.CardBrowser.onCreateOptionsMenu(CardBrowser.java:9)
53 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at android.app.Activity.onCreatePanelMenu(Activity.java:3388)
54 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:1)
55 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
56 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2)
57 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
58 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:5)
59 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:1)
60 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at android.os.Handler.handleCallback(Handler.java:790)
61 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at android.os.Handler.dispatchMessage(Handler.java:99)
62 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at android.os.Looper.loop(Looper.java:164)
63 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at android.app.ActivityThread.main(ActivityThread.java:6494)
64 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at java.lang.reflect.Method.invoke(Native Method)
65 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
66 | 06-04 00:06:00.870 E/AnkiDroid( 4550): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

</details>

<details><summary>stack trace</summary>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.ichi2.utils.JSONObject com.ichi2.libanki.Collection.getConf()' on a null object reference
at com.ichi2.anki.CardBrowser.onCreateOptionsMenu(CardBrowser.java:9)
at android.app.Activity.onCreatePanelMenu(Activity.java:3388)
at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:1)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:5)
at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:1)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
</details>

**Comment by dae** [comment]
Tentatively closing; let's see if it comes back.
