### ISSUE TITLE
API Unusable - Model `did` was null

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6378]
Had a user report: API was no longer working.

<details><summary>Logcat</summary>

```
06-06 01:01:14.253 17345 17390 E AnkiDroid: CardContentProvider/ Error parsing JSONArray
06-06 01:01:14.253 17345 17390 E AnkiDroid: com.ichi2.utils.JSONException: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at com.ichi2.utils.JSONObject.getLong(JSONObject.java:2)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at com.ichi2.anki.provider.CardContentProvider.addModelToCursor(CardContentProvider.java:19)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at com.ichi2.anki.provider.CardContentProvider.query(CardContentProvider.java:84)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at android.content.ContentProvider.query(ContentProvider.java:1276)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at android.content.ContentProvider.query(ContentProvider.java:1369)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at android.content.ContentProvider$Transport.query(ContentProvider.java:275)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:114)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at android.os.Binder.execTransactInternal(Binder.java:1032)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at android.os.Binder.execTransact(Binder.java:1005)
06-06 01:01:14.253 17345 17390 E AnkiDroid: Caused by: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at org.json.JSON.typeMismatch(JSON.java:101)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at org.json.JSONObject.getLong(JSONObject.java:527)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at com.ichi2.utils.JSONObject.getLong(JSONObject.java:1)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     ... 8 more
06-06 01:01:14.253 17345 17390 E AnkiDroid: 
06-06 01:01:14.253 17345 17390 E AnkiDroid: com.ichi2.utils.JSONException: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at com.ichi2.utils.JSONObject.getLong(JSONObject.java:2)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at com.ichi2.anki.provider.CardContentProvider.addModelToCursor(CardContentProvider.java:19)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at com.ichi2.anki.provider.CardContentProvider.query(CardContentProvider.java:84)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at android.content.ContentProvider.query(ContentProvider.java:1276)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at android.content.ContentProvider.query(ContentProvider.java:1369)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at android.content.ContentProvider$Transport.query(ContentProvider.java:275)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:114)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at android.os.Binder.execTransactInternal(Binder.java:1032)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at android.os.Binder.execTransact(Binder.java:1005)
06-06 01:01:14.253 17345 17390 E AnkiDroid: Caused by: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at org.json.JSON.typeMismatch(JSON.java:101)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at org.json.JSONObject.getLong(JSONObject.java:527)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     at com.ichi2.utils.JSONObject.getLong(JSONObject.java:1)
06-06 01:01:14.253 17345 17390 E AnkiDroid:     ... 8 more
06-06 01:01:14.253 17345 17390 E ContentProviderNative: onTransact error from {P:14524;U:10105}
06-06 01:01:14.253 17345 17390 E DatabaseUtils: Writing exception to parcel
06-06 01:01:14.253 17345 17390 E DatabaseUtils: java.lang.IllegalArgumentException: Model 1342706442510 is malformed
06-06 01:01:14.253 17345 17390 E DatabaseUtils:         at com.ichi2.anki.provider.CardContentProvider.addModelToCursor(CardContentProvider.java:32)
06-06 01:01:14.253 17345 17390 E DatabaseUtils:         at com.ichi2.anki.provider.CardContentProvider.query(CardContentProvider.java:84)
06-06 01:01:14.253 17345 17390 E DatabaseUtils:         at android.content.ContentProvider.query(ContentProvider.java:1276)
06-06 01:01:14.253 17345 17390 E DatabaseUtils:         at android.content.ContentProvider.query(ContentProvider.java:1369)
06-06 01:01:14.253 17345 17390 E DatabaseUtils:         at android.content.ContentProvider$Transport.query(ContentProvider.java:275)
06-06 01:01:14.253 17345 17390 E DatabaseUtils:         at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:114)
06-06 01:01:14.253 17345 17390 E DatabaseUtils:         at android.os.Binder.execTransactInternal(Binder.java:1032)
06-06 01:01:14.253 17345 17390 E DatabaseUtils:         at android.os.Binder.execTransact(Binder.java:1005)
06-06 01:01:14.253 17345 17390 E DatabaseUtils: Caused by: com.ichi2.utils.JSONException: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long
06-06 01:01:14.253 17345 17390 E DatabaseUtils:         at com.ichi2.utils.JSONObject.getLong(JSONObject.java:2)
06-06 01:01:14.253 17345 17390 E DatabaseUtils:         at com.ichi2.anki.provider.CardContentProvider.addModelToCursor(CardContentProvider.java:19)
06-06 01:01:14.253 17345 17390 E DatabaseUtils:         ... 7 more
06-06 01:01:14.253 17345 17390 E DatabaseUtils: Caused by: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long
06-06 01:01:14.253 17345 17390 E DatabaseUtils:         at org.json.JSON.typeMismatch(JSON.java:101)
06-06 01:01:14.253 17345 17390 E DatabaseUtils:         at org.json.JSONObject.getLong(JSONObject.java:527)
06-06 01:01:14.253 17345 17390 E DatabaseUtils:         at com.ichi2.utils.JSONObject.getLong(JSONObject.java:1)
06-06 01:01:14.253 17345 17390 E DatabaseUtils:         ... 8 more
```
</details>

The cause was a model with a `null` did. Confirmed via inspection from the Anki Desktop Python console.

This could be an API issue on our end, or corruption on the Anki Desktop side.

We have one instance where we can store `null` for the `did` of a model (a string is used, rather than a long):

https://github.com/ankidroid/Anki-Android/blob/1e4953b7de30c603c2564623775d3a42632778ab/AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java#L545

We can fix this by providing a reasonable default value

**Comment by david-allison-1** [comment]
@dae We have received a model with a `null` did

Have any changes recently occurred in this area that could cause this? I feel it's unlikely to be on the AnkiDroid side.

**Comment by Arthur-Milchior** [comment]
You should ask the reporter whether they use addons if you can. That is what i'd be expecting

**Comment by david-allison-1** [comment]
![image](https://user-images.githubusercontent.com/62114487/83943778-80a03d80-a7f6-11ea-98c6-5bc10eb7406f.png)

**Comment by Arthur-Milchior** [comment]
I do not know AnkiConnect in details. Since it allows anything to connect to Anki and send it queries, I would not be surprised if it was related to the problem in the first place. At least, that makes the number of place to investigate quite bigger.

I guess you're right and just using a default value (e.g. 1, the id of the default deck) would be the action which makes more sens here

**Comment by dae** [comment]
Sorry, this is likely due to .26 applying static typing to the models - it expects "did" to be an integer, and will turn it into a null if it can't parse it. .28 will turn the nulls into an id of 0, but as the cat's already out of the bag, I'm afraid AD is probably best off handling the null case :-(

**Comment by david-allison-1** [comment]
> Sorry, this is likely due to .26 applying static typing to the models - it expects "did" to be an integer, and will turn it into a null if it can't parse it. .28 will turn the nulls into an id of 0, but as the cat's already out of the bag, I'm afraid AD is probably best off handling the null case :-(

Will get it fixed.

Was there a rationale for picking 0 over 1 (default did)?

**Comment by dae** [comment]
I don't think I gave it a great deal of thought - the end result should be the same in either case as it should be falling back on 1 if the provided ID is missing
