### ISSUE TITLE
Reviewer - Media Mounting - Not Allowed to Start Service Intent - App is in Background

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6379]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/reports-browser

<details><summary>logcat</summary>

```
1	06-05 16:50:11.276 I/AnkiDroid( 1318): initialize()
2	06-05 16:50:11.298 I/AnkiDroid( 1318): Not participating in analytics sample (sample percentage vs random: 10 78)
3	06-05 16:50:11.299 I/AnkiDroid( 1318): setOptIn(): from false to false
4	06-05 16:50:11.299 I/AnkiDroid( 1318): Not participating in analytics sample (sample percentage vs random: 10 50)
5	06-05 16:50:11.303 I/AnkiDroid( 1318): Creating notification channel with id/name: General Notifications/AnkiDroid
6	06-05 16:50:11.305 I/AnkiDroid( 1318): Creating notification channel with id/name: Synchronization/Synchronization
7	06-05 16:50:11.307 I/AnkiDroid( 1318): Creating notification channel with id/name: Global Reminders/Cards due
8	06-05 16:50:11.310 I/AnkiDroid( 1318): Creating notification channel with id/name: Deck Reminders/Reminders
9	06-05 16:50:11.406 I/AnkiDroid( 1318): AnkiDroidApp: Starting Services
10	06-05 16:50:11.407 I/AnkiDroid( 1318): Begin openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
11	06-05 16:50:11.498 I/AnkiDroid( 1318): End openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
12	06-05 16:50:11.498 I/AnkiDroid( 1318): Executing Boot Service
13	06-05 16:50:11.503 I/AnkiDroid( 1318): media mount detected - sending broadcast
```

 </details>

```
java.lang.RuntimeException: Unable to start receiver com.ichi2.anki.stage.MainBroadcastReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.ichi2.anki/.stage.MainService }: app is in background uid UidRecord{342585a u0a70 RCVR idle change:uncached procs:1 seq(0,0,0)}
at android.app.ActivityThread.handleReceiver(ActivityThread.java:3389)
at android.app.ActivityThread.access$1200(ActivityThread.java:200)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1662)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6680)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.ichi2.anki/.stage.MainService }: app is in background uid UidRecord{342585a u0a70 RCVR idle change:uncached procs:1 seq(0,0,0)}
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
at android.app.ContextImpl.startService(ContextImpl.java:1532)
at android.content.ContextWrapper.startService(ContextWrapper.java:664)
at com.ichi2.anki.stage.MainService.startService(Unknown Source:7)
at com.ichi2.anki.stage.MainBroadcastReceiver.onReceive(Unknown Source:12)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:3380)
... 8 more
```

**Comment by mikehardy** [comment]
Not allowed to start service Intent { cmp=com.ichi2.anki/.stage.MainService }:  ?

That is not a service I'm aware of, sometimes people hack on our stuff but leave ACRA reporting intact
