### ISSUE TITLE
Card Browser: IndexOutOfBoundsException - hasSelectedSingleNoteId

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6384]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/47c047ce-884c-4713-a981-4eb45a43ba6d

```
java.lang.IndexOutOfBoundsException: Index: 2, Size: 0
at java.util.ArrayList.get(ArrayList.java:437)
at com.ichi2.anki.CardBrowser.hasSelectedSingleNoteId(CardBrowser.java:5)
at com.ichi2.anki.CardBrowser.updateMultiselectMenu(CardBrowser.java:9)
at com.ichi2.anki.CardBrowser.onSelectionChanged(CardBrowser.java:11)
at com.ichi2.anki.CardBrowser.onCreateOptionsMenu(CardBrowser.java:31)
at android.app.Activity.onCreatePanelMenu(Activity.java:4208)
at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:1)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:5)
at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:1)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
at android.view.Choreographer.doCallbacks(Choreographer.java:875)
at android.view.Choreographer.doFrame(Choreographer.java:772)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
at android.os.Handler.handleCallback(Handler.java:888)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:213)
at android.app.ActivityThread.main(ActivityThread.java:8147)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

**Comment by david-allison-1** [comment]
https://github.com/ankidroid/Anki-Android/blob/d98f55f399b7e718f15623a8af1c566b6deb0bf6/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java#L392 - concurrent modification of `mCards`
