### ISSUE TITLE
Ankidroid stopped working / crashed (I do not remember exact error message) after accidently pressing two different buttons

### ISSUE THREAD

**Issue by kodovanie** [ankidroid/Anki-Android#6446]
On couple of occassions I came across a bug that resulted in app crashing/terminating. Before crashing there was this error message I put into the title (that I do not remember precisely).

The bug occured when I accidentally pressed "easy" button in the app while reviewing cards and "back" button on the phone, both at the same time (as highlighted in the picture).

However I am not able to reproduce this bug when I try to, so I guess it is not determined just by me pressing those two different buttons at the same time, but also by some randomness.

I am having a bit older smartphone - S3 mini and using the latest version of Ankidroid. However I have been coming across this issue for a very long time. First time maybe over one year ago, if not even earlier. In terms of periodicity, I would say this bug happens to me maybe once a week. Sorry for not bringing it up earlier, it did not cause me a lot of pain in life, but after having seen it already quite a lot of time (in total), I wanted to give a shout about it.

**Comment by kodovanie** [comment]
![anki_S3_mini](https://user-images.githubusercontent.com/66253775/84536689-ab0a6300-acee-11ea-942d-11ea667c40c3.PNG)

**Comment by mikehardy** [comment]
Can you have a look at https://docs.ankidroid.org/help.html#_support and send in the debug info? That can help us find the crash trace and hopefully nail your bug! Thanks for reporting it

**Comment by kodovanie** [comment]
AnkiDroid Version = 2.11.1

Android Version = 4.1.2

ACRA UUID = e920e920-d917-4b52-9f53-e465ff8cefa2

**Comment by mikehardy** [comment]
Odd :thinking: - I don't see anything recent. I see this in the past, but you noted it was while the screen was locked so perhaps your device disallowed filesystem access while locked, I dunno (https://sqlite.org/rescode.html#ioerr_fstat)

```

 
--
2 | 03-26 08:17:47.148 I/AnkiDroid(10672): Not participating in analytics sample (sample percentage vs random: 10 11)
3 | 03-26 08:17:47.148 I/AnkiDroid(10672): setOptIn(): from false to true
4 | 03-26 08:17:47.148 I/AnkiDroid(10672): Participating in analytics sample (sample percentage vs random: 10 10)
5 | 03-26 08:20:56.230 I/AnkiDroid(10672): openCollection: /sdcard/AnkiDroid/collection.anki2
6 | 03-26 08:22:50.070 E/AnkiDroid(10672): Storage/ Error opening collection; closing database
7 | 03-26 08:22:50.070 E/AnkiDroid(10672): android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802)
8 | 03-26  08:22:50.070 E/AnkiDroid(10672): 	at  io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native  Method)
9 | 03-26  08:22:50.070 E/AnkiDroid(10672): 	at  io.requery.android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:8)
10 | 03-26  08:22:50.070 E/AnkiDroid(10672): 	at  io.requery.android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:4)
11 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at io.requery.android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:5)
12 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at io.requery.android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:4)
13 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at io.requery.android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:2)
14 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at io.requery.android.database.AbstractCursor.moveToPosition(AbstractCursor.java:1)
15 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at io.requery.android.database.AbstractCursor.moveToFirst(AbstractCursor.java:1)
16 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at com.ichi2.libanki.Collection.load(Collection.java:2)
17 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at com.ichi2.libanki.Collection.<init>(Collection.java:16)
18 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at com.ichi2.libanki.Storage.Collection(Storage.java:9)
19 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:6)
20 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at com.ichi2.anki.services.BootService.onReceive(BootService.java:3)
21 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:24)
22 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
23 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4197)
24 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at android.app.ActivityThread.access$1400(ActivityThread.java:134)
25 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
26 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at android.os.Handler.dispatchMessage(Handler.java:99)
27 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at android.os.Looper.loop(Looper.java:137)
28 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at android.app.ActivityThread.main(ActivityThread.java:4867)
29 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at java.lang.reflect.Method.invokeNative(Native Method)
30 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at java.lang.reflect.Method.invoke(Method.java:511)
31 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
32 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
33 | 03-26 08:22:50.070 E/AnkiDroid(10672): 	at dalvik.system.NativeStart.main(Native Method)

```

**Comment by mikehardy** [comment]
This could be the crash you are seeing:

```
java.lang.NullPointerException
at android.webkit.WebViewClassic.loadDataWithBaseURL(WebViewClassic.java:3500)
at android.webkit.WebView.loadDataWithBaseURL(WebView.java:853)
at com.ichi2.anki.AbstractFlashcardViewer.loadContentIntoCard(AbstractFlashcardViewer.java:2)
at com.ichi2.anki.AbstractFlashcardViewer.a(AbstractFlashcardViewer.java:8)
at com.ichi2.anki.d.consume(lambda)
at com.ichi2.anki.AbstractFlashcardViewer.a(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.h.apply(lambda)
at com.ichi2.anki.AbstractFlashcardViewer.processCardFunction(AbstractFlashcardViewer.java:3)
at com.ichi2.anki.AbstractFlashcardViewer.processCardAction(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.fillFlashcard(AbstractFlashcardViewer.java:6)
at com.ichi2.anki.Reviewer.fillFlashcard(Reviewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:34)
at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:14)
at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:2)
at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:10)
at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:1)
at com.ichi2.async.CollectionTask$TaskListener.onProgressUpdate(CollectionTask.java:1)
at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:4)
at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:1)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:647)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4867)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by kodovanie** [comment]
Could the reason, for you not seeing anything recent, be that my wifi was off when this error occured? I usually have wifi off.

**Comment by david-allison-1** [comment]
Hi @kodovanie, thanks for the report!

I've added some more diagnostics to 2.11.0 for this sort of issue. I get the impression that it'll be due to the WebView being disposed 

https://stackoverflow.com/questions/28856883/java-nullpointer-exception-from-webview-in-android-webkit-webviewclassic-loaddat

There's a sensible solution: https://stackoverflow.com/a/34518070/13121290. I'll get a fix for this in in the next few minutes.
