### ISSUE TITLE
Ankidroid crash via Cloud Sync ("Collection Not Opened")

### ISSUE THREAD

**Issue by Nach18** [ankidroid/Anki-Android#6454]
###### Reproduction Steps

1. Sync on Ankidroid.
2. Error: Collection Not Opened. An error ocurred while accesssing your collection...
3. When use an possible option on "Error Handling" app not open or not sync.

collection.anki2.bak:
https://drive.google.com/file/d/13FDSaa18trXG-YMkSpxsDh9coQ_TJewa/view?usp=sharing
collection.anki (DESKTOP)
https://drive.google.com/file/d/1QXygK4yoJ7KXfgHFnBUuoFea2ULW_91e/view?usp=sharing

###### Expected Result

Sync correctly.

###### Actual Result

When I try to sync data on Ankidroid I get this error:

"Collection not opened, An error ocurred while accessing your collection. It may have been caused by a harmless bug, or there may be a problem whit it.

Try running check database, or restoring from backup by pressing the "options" button. If you continue to see this message, please file a bur report: https://docs/ankidroid.org/help.html"

Every time it shows me the failure of the collections I have 4 options in the "Error handling":
-Check database. (Nothings happen).
-Restore from Backup
-Full sync from server (Same result).
-Delete collection and create a new one. (Open but not sync)

I have tried to uninstall and clean the Ankidroid folder, have imported a security copy made with Anki Desktop, still crash.

I created the cards in Anky Desktop for Windows 2.1.26 (70784154) and I study them in AnkiDroid, everything was fine until after syncing the app show this error.
First sync ask me if i want to download or upload, I choose Upload on AnkiDesktop and Download on AnkiDroid.
I only remember create a new type of card with hints (html code included) I erased but nothings changes.

I know this problem has been discussed in other threads but I still haven't managed to solve it

What can I do? 
If the problem persists, is there an alternative so that I can continue studying cards from my mobile?

###### Debug info

AnkiDroid Version = 2.11.1

Android Version = 10

ACRA UUID = 7501521e-a2cc-44d4-a8d7-22e4c3817b48

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum (I can´t solve it...)
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Could you provide your `collection.anki2` file. 


Error:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.ichi2.utils.JSONObject com.ichi2.utils.JSONObject.put(java.lang.String, int)' on a null object reference
at com.ichi2.libanki.Decks.confForDid(Decks.java:4)
at com.ichi2.libanki.sched.SchedV2._deckNewLimitSingle(SchedV2.java:3)
at com.ichi2.libanki.sched.Sched.deckDueList(Sched.java:9)
at com.ichi2.libanki.sched.SchedV2.deckDueList(SchedV2.java:1)
at com.ichi2.libanki.sync.Syncer.sanityCheck(Syncer.java:36)
at com.ichi2.libanki.sync.Syncer.sync(Syncer.java:84)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:16)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:2)
at com.ichi2.async.Connection.doInBackground(Connection.java:4)
at com.ichi2.async.Connection.doInBackground(Connection.java:1)
at android.os.AsyncTask$3.call(Unknown Source:20)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(Unknown Source:2)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
```

**Comment by mikehardy** [comment]
Possibly incorrect file path to the AnkiDroid directory?

```

 
--
1 | 06-13 17:05:59.129 E/AnkiDroid(16626): 	at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:7)
2 | 06-13 17:05:59.129 E/AnkiDroid(16626): 	at android.view.View.performClick(Unknown Source:17)
3 | 06-13 17:05:59.129 E/AnkiDroid(16626): 	at android.view.View.performClickInternal(Unknown Source:3)
4 | 06-13 17:05:59.129 E/AnkiDroid(16626): 	at android.view.View.access$3500(Unknown Source:0)
5 | 06-13 17:05:59.129 E/AnkiDroid(16626): 	at android.view.View$PerformClick.run(Unknown Source:8)
6 | 06-13 17:05:59.129 E/AnkiDroid(16626): 	at android.os.Handler.handleCallback(Unknown Source:2)
7 | 06-13 17:05:59.129 E/AnkiDroid(16626): 	at android.os.Handler.dispatchMessage(Unknown Source:4)
8 | 06-13 17:05:59.129 E/AnkiDroid(16626): 	at android.os.Looper.loop(Unknown Source:242)
9 | 06-13 17:05:59.129 E/AnkiDroid(16626): 	at android.app.ActivityThread.main(Unknown Source:98)
10 | 06-13 17:05:59.129 E/AnkiDroid(16626): 	at java.lang.reflect.Method.invoke(Native Method)
11 | 06-13 17:05:59.129 E/AnkiDroid(16626): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
12 | 06-13 17:05:59.129 E/AnkiDroid(16626): 	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
13 | 06-13  17:05:59.129 E/AnkiDroid(16626): Caused by:  android.system.ErrnoException: statvfs failed: ENOENT (No such file or  directory)
14 | 06-13 17:05:59.129 E/AnkiDroid(16626): 	at libcore.io.Linux.statvfs(Native Method)
15 | 06-13 17:05:59.129 E/AnkiDroid(16626): 	at libcore.io.ForwardingOs.statvfs(ForwardingOs.java:224)
16 | 06-13 17:05:59.129 E/AnkiDroid(16626): 	at libcore.io.BlockGuardOs.statvfs(BlockGuardOs.java:396)
17 | 06-13 17:05:59.129 E/AnkiDroid(16626): 	at libcore.io.ForwardingOs.statvfs(ForwardingOs.java:224)
18 | 06-13 17:05:59.129 E/AnkiDroid(16626): 	at android.system.Os.statvfs(Os.java:660)
19 | 06-13 17:05:59.129 E/AnkiDroid(16626): 	at android.os.StatFs.doStat(Unknown Source:0)
20 | 06-13 17:05:59.129 E/AnkiDroid(16626): 	... 18 more
21 | 06-13  17:05:59.130 W/AnkiDroid(16626):  CollectionHelper$CollectionIntegrityStorageCheck/ Error obtaining free  space for '/storage/emulated/0/AnkiDroid/FALLO/collection.anki2'
22 | 06-13 17:06:07.712 I/AnkiDroid(16626): performIntegrityCheck()
23 | 06-13 17:06:07.764 I/AnkiDroid(16626): cursor size: 0
24 | 06-13 17:06:07.764 I/AnkiDroid(16626): deleteNotesWithWrongFieldCounts - completed successfully
25 | 06-13 17:06:07.765 E/SQLiteLog(16626): (284) automatic index on notes(mid)
26 | 06-13 17:06:07.766 I/AnkiDroid(16626): cursor size: 0
27 | 06-13 17:06:07.766 I/AnkiDroid(16626): deleteNotesWithWrongFieldCounts - completed successfully
28 | 06-13 17:06:07.767 E/SQLiteLog(16626): (284) automatic index on notes(mid)
29 | 06-13 17:06:07.768 I/AnkiDroid(16626): cursor size: 0
30 | 06-13 17:06:07.768 I/AnkiDroid(16626): deleteNotesWithWrongFieldCounts - completed successfully
31 | 06-13 17:06:07.769 I/AnkiDroid(16626): cursor size: 0
32 | 06-13 17:06:07.769 I/AnkiDroid(16626): deleteNotesWithWrongFieldCounts - completed successfully
33 | 06-13 17:06:07.771 I/AnkiDroid(16626): cursor size: 76
34 | 06-13 17:06:07.779 I/AnkiDroid(16626): deleteNotesWithWrongFieldCounts - completed successfully
35 | 06-13 17:06:07.782 I/AnkiDroid(16626): cursor size: 1
36 | 06-13 17:06:07.782 I/AnkiDroid(16626): deleteNotesWithWrongFieldCounts - completed successfully
37 | 06-13 17:06:07.785 I/AnkiDroid(16626): cursor size: 0
38 | 06-13 17:06:07.785 I/AnkiDroid(16626): deleteNotesWithWrongFieldCounts - completed successfully
39 | 06-13 17:06:07.786 I/AnkiDroid(16626): cursor size: 1
40 | 06-13 17:06:07.786 I/AnkiDroid(16626): deleteNotesWithWrongFieldCounts - completed successfully
41 | 06-13 17:06:07.787 I/AnkiDroid(16626): cursor size: 0
42 | 06-13 17:06:07.787 I/AnkiDroid(16626): deleteNotesWithWrongFieldCounts - completed successfully
43 | 06-13 17:06:07.788 I/AnkiDroid(16626): cursor size: 28
44 | 06-13 17:06:07.788 I/AnkiDroid(16626): deleteNotesWithWrongFieldCounts - completed successfully
45 | 06-13 17:06:07.789 I/AnkiDroid(16626): cursor size: 5
46 | 06-13 17:06:07.789 I/AnkiDroid(16626): deleteNotesWithWrongFieldCounts - completed successfully
47 | 06-13 17:06:07.790 I/AnkiDroid(16626): cursor size: 0
48 | 06-13 17:06:07.790 I/AnkiDroid(16626): deleteNotesWithWrongFieldCounts - completed successfully
49 | 06-13  17:06:07.810 E/SQLiteLog(16626): (1032) statement aborts at 28: [UPDATE  notes SET sfld=?, csum=? WHERE id=?] attempt to write a readonly  database
50 | 06-13 17:06:07.810 E/AnkiDroid(16626): Collection/ Failed to execute integrity check
51 | 06-13  17:06:07.810 E/AnkiDroid(16626):  android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to  write a readonly database (code 1032)
52 | 06-13  17:06:07.810 E/AnkiDroid(16626): 	at  io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native  Method)
53 | 06-13  17:06:07.810 E/AnkiDroid(16626): 	at  io.requery.android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:7)
54 | 06-13  17:06:07.810 E/AnkiDroid(16626): 	at  io.requery.android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:3)
55 | 06-13  17:06:07.810 E/AnkiDroid(16626): 	at  io.requery.android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:4)
56 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at io.requery.android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:3)
57 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at io.requery.android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2)
58 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.libanki.DB.executeMany(DB.java:4)
59 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.libanki.Collection.updateFieldCache(Collection.java:7)
60 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.libanki.Collection.updateFieldCache(Collection.java:11)
61 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.libanki.Collection.g(Unknown Source:0)
62 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.libanki.g.apply(Unknown Source:4)
63 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.libanki.Collection.m(Collection.java:2)
64 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.libanki.k.consume(Unknown Source:8)
65 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.libanki.Collection.fixIntegrity(Collection.java:26)
66 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.async.CollectionTask.doInBackgroundCheckDatabase(CollectionTask.java:5)
67 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:45)
68 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
69 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at android.os.AsyncTask$3.call(Unknown Source:20)
70 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
71 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at android.os.AsyncTask$SerialExecutor$1.run(Unknown Source:2)
72 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
73 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
74 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at java.lang.Thread.run(Thread.java:919)
75 | 06-13 17:06:07.810 E/AnkiDroid(16626):
76 | 06-13  17:06:07.810 E/AnkiDroid(16626):  android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to  write a readonly database (code 1032)
77 | 06-13  17:06:07.810 E/AnkiDroid(16626): 	at  io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native  Method)
78 | 06-13  17:06:07.810 E/AnkiDroid(16626): 	at  io.requery.android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:7)
79 | 06-13  17:06:07.810 E/AnkiDroid(16626): 	at  io.requery.android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:3)
80 | 06-13  17:06:07.810 E/AnkiDroid(16626): 	at  io.requery.android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:4)
81 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at io.requery.android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:3)
82 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at io.requery.android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2)
83 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.libanki.DB.executeMany(DB.java:4)
84 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.libanki.Collection.updateFieldCache(Collection.java:7)
85 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.libanki.Collection.updateFieldCache(Collection.java:11)
86 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.libanki.Collection.g(Unknown Source:0)
87 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.libanki.g.apply(Unknown Source:4)
88 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.libanki.Collection.m(Collection.java:2)
89 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.libanki.k.consume(Unknown Source:8)
90 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.libanki.Collection.fixIntegrity(Collection.java:26)
91 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.async.CollectionTask.doInBackgroundCheckDatabase(CollectionTask.java:5)
92 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:45)
93 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
94 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at android.os.AsyncTask$3.call(Unknown Source:20)
95 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
96 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at android.os.AsyncTask$SerialExecutor$1.run(Unknown Source:2)
97 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
98 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
99 | 06-13 17:06:07.810 E/AnkiDroid(16626): 	at java.lang.Thread.run(Thread.java:919)

```

also

```

6-13 17:58:49.686 I/AnkiDroid(32605): User successfully logged in!
--
13 | 06-13 17:58:49.687 I/AnkiDroid(32605): finishWithAnimation 2
14 | 06-13 17:58:49.703 I/AnkiDroid(32605): AnkiActivity::onPause
15 | 06-13 17:58:49.716 I/AnkiDroid(32605): Handling Activity Result: 6. Result: -1
16 | 06-13 17:58:49.716 I/AnkiDroid(32605): Creating notification channel with id/name: General Notifications/AnkiDroid
17 | 06-13 17:58:49.716 I/AnkiDroid(32605): Creating notification channel with id/name: Synchronization/Sincronización
18 | 06-13 17:58:49.717 I/AnkiDroid(32605): Creating notification channel with id/name: Global Reminders/Tarjetas pendientes
19 | 06-13 17:58:49.717 I/AnkiDroid(32605): Creating notification channel with id/name: Deck Reminders/Recordatorios
20 | 06-13 17:58:49.717 I/AnkiDroid(32605): AnkiActivity::onStart
21 | 06-13 17:58:49.728 I/AnkiDroid(32605): AnkiActivity::onResume
22 | 06-13 17:58:49.728 I/AnkiDroid(32605): Performing Sync on Resume
23 | 06-13 17:58:49.739 I/AnkiDroid(32605): Sync - starting sync
24 | 06-13 17:58:50.372 I/AnkiDroid(32605): Sync: getting meta data from server
25 | 06-13 17:58:50.375 I/AnkiDroid(32605): Sync: building local meta data
26 | 06-13 17:58:50.380 E/SQLiteLog(32605): (284) automatic index on notes(mid)
27 | 06-13 17:58:50.384 I/AnkiDroid(32605): Sync: collection removed data
28 | 06-13 17:58:50.385 I/AnkiDroid(32605): Sync: sending and receiving removed data
29 | 06-13 17:58:50.702 I/AnkiDroid(32605): Sync: applying removed data
30 | 06-13 17:58:50.702 I/AnkiDroid(32605): Sync: collection small changes
31 | 06-13 17:58:50.702 I/AnkiDroid(32605): Sync: sending and receiving small changes
32 | 06-13 17:58:50.824 I/AnkiDroid(32605): Sync: merging small changes
33 | 06-13 17:58:50.824 I/AnkiDroid(32605): Sync: downloading chunked data
34 | 06-13 17:58:50.975 I/AnkiDroid(32605): Sync: applying chunked data
35 | 06-13 17:58:50.977 I/AnkiDroid(32605): Sync: collecting chunked data
36 | 06-13 17:58:50.979 I/AnkiDroid(32605): Sync: sending chunked data
37 | 06-13 17:58:51.123 E/AnkiDroid(32605): Connection/ doInBackgroundSync error
38 | 06-13  17:58:51.123 E/AnkiDroid(32605): java.lang.NullPointerException:  Attempt to invoke virtual method 'com.ichi2.utils.JSONObject  com.ichi2.utils.JSONObject.put(java.lang.String, int)' on a null object  reference
39 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at com.ichi2.libanki.Decks.confForDid(Decks.java:4)
40 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at com.ichi2.libanki.sched.SchedV2._deckNewLimitSingle(SchedV2.java:3)
41 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at com.ichi2.libanki.sched.Sched.deckDueList(Sched.java:9)
42 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at com.ichi2.libanki.sched.SchedV2.deckDueList(SchedV2.java:1)
43 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at com.ichi2.libanki.sync.Syncer.sanityCheck(Syncer.java:36)
44 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at com.ichi2.libanki.sync.Syncer.sync(Syncer.java:84)
45 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:16)
46 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at com.ichi2.async.Connection.doOneInBackground(Connection.java:2)
47 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at com.ichi2.async.Connection.doInBackground(Connection.java:4)
48 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at com.ichi2.async.Connection.doInBackground(Connection.java:1)
49 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at android.os.AsyncTask$3.call(Unknown Source:20)
50 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
51 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at android.os.AsyncTask$SerialExecutor$1.run(Unknown Source:2)
52 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
53 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
54 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at java.lang.Thread.run(Thread.java:919)
55 | 06-13 17:58:51.123 E/AnkiDroid(32605):
56 | 06-13  17:58:51.123 E/AnkiDroid(32605): java.lang.NullPointerException:  Attempt to invoke virtual method 'com.ichi2.utils.JSONObject  com.ichi2.utils.JSONObject.put(java.lang.String, int)' on a null object  reference
57 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at com.ichi2.libanki.Decks.confForDid(Decks.java:4)
58 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at com.ichi2.libanki.sched.SchedV2._deckNewLimitSingle(SchedV2.java:3)
59 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at com.ichi2.libanki.sched.Sched.deckDueList(Sched.java:9)
60 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at com.ichi2.libanki.sched.SchedV2.deckDueList(SchedV2.java:1)
61 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at com.ichi2.libanki.sync.Syncer.sanityCheck(Syncer.java:36)
62 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at com.ichi2.libanki.sync.Syncer.sync(Syncer.java:84)
63 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:16)
64 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at com.ichi2.async.Connection.doOneInBackground(Connection.java:2)
65 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at com.ichi2.async.Connection.doInBackground(Connection.java:4)
66 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at com.ichi2.async.Connection.doInBackground(Connection.java:1)
67 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at android.os.AsyncTask$3.call(Unknown Source:20)
68 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
69 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at android.os.AsyncTask$SerialExecutor$1.run(Unknown Source:2)
70 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
71 | 06-13 17:58:51.123 E/AnkiDroid(32605): 	at java.util.concurrent.ThreadPoolExecutor$Work


```

**Comment by Nach18** [comment]
> Could you provide your `collection.anki2` file from Anki Desktop.

Of course, thanks.
Desktop:
https://drive.google.com/file/d/1QXygK4yoJ7KXfgHFnBUuoFea2ULW_91e/view?usp=sharing

The name of the copy is different due to my language. Is it necessary to change it?

**Comment by david-allison-1** [comment]
@Nach18 Perfect. No need for anything else

**Comment by Nach18** [comment]
> ```
>  '/storage/emulated/0/AnkiDroid/FALLO/collection.anki2'

Well, I did something pretty silly after the sync failed over and over, for not too long change directory (on Ankidroid) to:
/ storage / emulated / 0 / AnkiDroid / FAIL /

Nothing changed so I as the original path again:
storage / emulated / 0 / AnkiDroid /

**Comment by david-allison-1** [comment]
@Nach18 Could you edit the deck options of `BLOQUE III::B3/T2: Diseño de Bases de Datos (BBDD) (E/R + Relacional)` and select "Default" as the Deck Options Group in Anki Desktop, then try syncing again.

Could you explain anything that you were doing which would corrupt that piece of data?

**Comment by david-allison-1** [comment]
Explanation: The deck referred to a deck config ID (1592004822348) which did not exist in the database.

**Comment by Nach18** [comment]
> @Nach18 Could you edit the deck options of `BLOQUE III::B3/T2: Diseño de Bases de Datos (BBDD) (E/R + Relacional)` and select "Default" as the Deck Options Group in Anki Desktop, then try syncing again.
> 
> Could you explain anything that you were doing which would corrupt that piece of data, and whether you were using Anki Desktop, or AnkiDroid at the time that this was happening?

Ok, Do it for all Decks, now all decks are separate

Mainly I did 3 things:

1) Order older decks by adding them to higher decks.

For example: deck B3 / T4 inside deck III of the block (as in the previous example)

(This I remember that when synchronizing it showed the changes and gave no problems)

2) Create categories
(Basic, Difficult ...) and adding some existing cards to these categories.

(I remember this also accepted it)

3) And finally create a new type of cards that add a new field: suggestions. For a new deck.

According to this tutorial:
https://www.youtube.com/watch?v=Hv0IxQSYZiM&t=314s
with this code: https://pastebin.com/tqWNkeHV

I hung the name of the card fields in English.

I thought this might be the mistake, so I tried to remove these last cards in addition to some unused decks.

**Comment by Nach18** [comment]
> 1592004822348

This ID?

Thank you! What Can I Do now?
I try to find the id of this deck and I try to delete?

**Comment by david-allison-1** [comment]
@Nach18. Did my instructions not fix the problem? :/

![image](https://user-images.githubusercontent.com/62114487/84576328-d606bc80-adab-11ea-8a24-b9064bbe9a03.png) - click the options, then click "OK"

* Sync

* Full Sync (Download) from AnkiDroid

**Comment by Nach18** [comment]
WHAT?

IT WORK!!! I thought that already do and nothing changes.

Thank you thank you thank you so much David, this is very important to me.

Please, Can you tell me how to avoid this problem so that it doesn't happen again?
Should I disable the automatic update on the app?
Can i add the decks back into other decks?

**Comment by david-allison-1** [comment]
@Nach18, don't worry about it, act with confidence and do everything that you did previously. 

I'll investigate and get the root cause sorted.

**Comment by Nach18** [comment]
I really appreciate all of your time spent helping me.
I will try to contribute as I can for the good work you do.

Thank you much!.

**Comment by david-allison-1** [comment]
The root cause for this is sill unresolved
