### ISSUE TITLE
genCards - Collection was null

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6471]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/6fbc84a1-7b01-4617-bc05-3acafa848455

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$4.done(AsyncTask.java:399)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
at com.ichi2.libanki.Collection.genCards(Collection.java:39)
at com.ichi2.libanki.Models._syncTemplates(Models.java:1)
at com.ichi2.libanki.Models.save(Models.java:8)
at com.ichi2.async.CollectionTask.doInBackgroundSaveModel(CollectionTask.java:5)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:19)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 4 more
```

**Comment by david-allison-1** [comment]
Maybe fixed in #5151, leaving this open for tracking.

**Comment by mikehardy** [comment]
Whew - if that was on the alpha with 5151 committed I was going to be very concerned
Not sure how interesting any report on gencards will be from before that merge

I expect we will see something but it'll be in the 2.12alphas and different stacks
