### ISSUE TITLE
[2.12] Possible MultiDex Issue - Android Emulator - Couldn't load sqlite3x from loader 

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6483]
This has happened 3 times and needs investigation. Possibly user testing a fork (as they're likely running a non debug build in the emulator).

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/08fd7528-6c31-4822-99a9-52d744fe7e5d

```
java.lang.UnsatisfiedLinkError: Couldn't load sqlite3x from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ichi2.anki-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.ichi2.anki-1, /system/lib]]]: findLibrary returned null
at java.lang.Runtime.loadLibrary(Runtime.java:355)
at java.lang.System.loadLibrary(System.java:525)
at io.requery.android.database.sqlite.SQLiteDatabase.<clinit>(SQLiteDatabase.java:2)
at io.requery.android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:16)
at io.requery.android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:3)
at io.requery.android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:1)
at com.ichi2.libanki.DB.<init>(DB.java:8)
at com.ichi2.libanki.Storage.Collection(Storage.java:4)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:6)
at com.ichi2.anki.services.BootService.getColSafe(BootService.java:1)
at com.ichi2.anki.services.BootService.onReceive(BootService.java:5)
at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:31)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4444)
at android.app.ActivityThread.access$1300(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5103)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by mikehardy** [comment]
ARM emulators are used by no one, there is no point supporting them.
2.12alpha7 was specifically when I did library splits but before I made a universal APK
There's no point in keeping this open I think unless it becomes too much noise in acralyzer, at which point I'd consider altering the default universal-apk toggle from false to true and adjusting the release scripts appropriately, so that by default it was available

**Comment by mikehardy** [comment]
opening and assigning to myself to make sure my diagnosis + thinking on this is good
