### ISSUE TITLE
Don't show an exception report dialog when provided with known invalid zip files 

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6489]
Cause: Investigations into #6419

Assuming these do not imply a problem with the library, then these issues cause noise in ACRA, and will lead to a degraded user experience. 

But as we now have the report data, we can classify the exceptions based on the exception details to provide better information to help the user.

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/ab7bfc68-30d0-4129-a4d2-04427f4d3123

```
java.util.zip.ZipException: archive is not a ZIP archive
at org.apache.commons.compress.archivers.zip.ZipFile.positionAtEndOfCentralDirectoryRecord(ZipFile.java:2)
at org.apache.commons.compress.archivers.zip.ZipFile.positionAtCentralDirectory(ZipFile.java:1)
at org.apache.commons.compress.archivers.zip.ZipFile.populateFromCentralDirectory(ZipFile.java:2)
at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:19)
at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:4)
at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:1)
at com.ichi2.async.CollectionTask.doInBackgroundImportReplace(CollectionTask.java:9)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:37)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
```

**Comment by david-allison-1** [comment]
This exception logging line has existed since 2015, and from recollection was not throwing this amount of errors when using the original `java.util.ZipFile`

https://github.com/ankidroid/Anki-Android/blob/5cbac24f145f8b4b418ff5b64b502d0cf123ce8e/AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java#L1122

It would be very useful to have a file to confirm whether this is a regression from our change to `commons-compress`.

**Comment by david-allison-1** [comment]
There are a few cases of this previously (2.10.3): https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/81009b9d-d8fb-4fab-85f6-99c87dd7c121

**Comment by david-allison-1** [comment]
Maybe we need to validate inside `ImportUtils` after copying

**Comment by david-allison-1** [comment]
I can reproduce this error message with an empty apkg. 

We did not perform the "Check ZipInputStream" check as the extension matched

Corrupt zips produce the error: "central directory is empty, can't expand corrupt archive."
