### ISSUE TITLE
2.12a9+ can't be installed over a8

### ISSUE THREAD

**Issue by rathsky** [ankidroid/Anki-Android#6493]
Can't tell why exactly since the package installer only aborts with the ingeniously non-descriptive…

> App not installed.

… but guess it's the usual case of a different key being used for apk signing.

**Comment by david-allison-1** [comment]
Hi @rathsky,

Is this on an emulator or your phone? 

Could you confirm if related: #6483

**Comment by rathsky** [comment]
Phone (both of them) via the official alphas released here. No emulator involved.

**Comment by david-allison-1** [comment]
@mikehardy Probably related to #6474

https://github.com/ankidroid/Anki-Android/compare/v2.12alpha8...v2.12alpha9

**Comment by mikehardy** [comment]
Huh - same keys or I would not have even been able to generate the release (they come out of a fixed-location keystore that requires a password etc - basically it's not possible to use the wrong key)

I suspect David is correct and it has something to do with the binary split. I'll try to reproduce and see, but I've already successfully installed 2.12alpha11 over 2.11.2 in the .A version at least, and the alpha came out of the play store correctly for me.

@rathsky what phone model do you have? Are you able to get unfiltered logcat during the install (it usually will expose the root cause error during installer failures)

**Comment by rathsky** [comment]
@mikehardy It's an older Mi5s running Lineage / Android 10.

The logcat lines:

```
06-18 15:36:26.518  6420  6420 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3138 
06-18 15:36:26.519  6420  6420 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1808 
06-18 15:36:26.604  3762 24131 E SQLiteDatabase: Error inserting flex_time=0 job_id=-1 period=2000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=202115000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1592487386599 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0
06-18 15:36:26.604  3762 24131 E SQLiteDatabase: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
06-18 15:36:26.604  3762 24131 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
06-18 15:36:26.604  3762 24131 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:879)
06-18 15:36:26.604  3762 24131 E SQLiteDatabase:        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
06-18 15:36:26.604  3762 24131 E SQLiteDatabase:        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
06-18 15:36:26.604  3762 24131 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1599)
06-18 15:36:26.604  3762 24131 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1468)
06-18 15:36:26.604  3762 24131 E SQLiteDatabase:        at aqew.a(:com.google.android.gms@202115039@20.21.15 (120408-313409149):146)
06-18 15:36:26.604  3762 24131 E SQLiteDatabase:        at aqeg.a(:com.google.android.gms@202115039@20.21.15 (120408-313409149):190)
06-18 15:36:26.604  3762 24131 E SQLiteDatabase:        at aqeg.a(:com.google.android.gms@202115039@20.21.15 (120408-313409149):23)
06-18 15:36:26.604  3762 24131 E SQLiteDatabase:        at aqeg.a(:com.google.android.gms@202115039@20.21.15 (120408-313409149):185)
06-18 15:36:26.604  3762 24131 E SQLiteDatabase:        at aqaq.run(:com.google.android.gms@202115039@20.21.15 (120408-313409149):9)
06-18 15:36:26.604  3762 24131 E SQLiteDatabase:        at sjk.b(:com.google.android.gms@202115039@20.21.15 (120408-313409149):12)
06-18 15:36:26.604  3762 24131 E SQLiteDatabase:        at sjk.run(:com.google.android.gms@202115039@20.21.15 (120408-313409149):7)
06-18 15:36:26.604  3762 24131 E SQLiteDatabase:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-18 15:36:26.604  3762 24131 E SQLiteDatabase:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-18 15:36:26.604  3762 24131 E SQLiteDatabase:        at spg.run(:com.google.android.gms@202115039@20.21.15 (120408-313409149):0)
06-18 15:36:26.604  3762 24131 E SQLiteDatabase:        at java.lang.Thread.run(Thread.java:919)
06-18 15:36:27.233  3762  7503 E SQLiteDatabase: Error inserting flex_time=1809000 job_id=-1 period=3620000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=202115000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1592487387231 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0
06-18 15:36:27.233  3762  7503 E SQLiteDatabase: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
06-18 15:36:27.233  3762  7503 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
06-18 15:36:27.233  3762  7503 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:879)
06-18 15:36:27.233  3762  7503 E SQLiteDatabase:        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
06-18 15:36:27.233  3762  7503 E SQLiteDatabase:        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
06-18 15:36:27.233  3762  7503 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1599)
06-18 15:36:27.233  3762  7503 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1468)
06-18 15:36:27.233  3762  7503 E SQLiteDatabase:        at aqew.a(:com.google.android.gms@202115039@20.21.15 (120408-313409149):146)
06-18 15:36:27.233  3762  7503 E SQLiteDatabase:        at aqeg.a(:com.google.android.gms@202115039@20.21.15 (120408-313409149):190)
06-18 15:36:27.233  3762  7503 E SQLiteDatabase:        at aqeg.a(:com.google.android.gms@202115039@20.21.15 (120408-313409149):23)
06-18 15:36:27.233  3762  7503 E SQLiteDatabase:        at aqeg.a(:com.google.android.gms@202115039@20.21.15 (120408-313409149):185)
06-18 15:36:27.233  3762  7503 E SQLiteDatabase:        at aqaq.run(:com.google.android.gms@202115039@20.21.15 (120408-313409149):9)
06-18 15:36:27.233  3762  7503 E SQLiteDatabase:        at sjk.b(:com.google.android.gms@202115039@20.21.15 (120408-313409149):12)
06-18 15:36:27.233  3762  7503 E SQLiteDatabase:        at sjk.run(:com.google.android.gms@202115039@20.21.15 (120408-313409149):7)
06-18 15:36:27.233  3762  7503 E SQLiteDatabase:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-18 15:36:27.233  3762  7503 E SQLiteDatabase:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-18 15:36:27.233  3762  7503 E SQLiteDatabase:        at spg.run(:com.google.android.gms@202115039@20.21.15 (120408-313409149):0)
06-18 15:36:27.233  3762  7503 E SQLiteDatabase:        at java.lang.Thread.run(Thread.java:919)
06-18 15:36:27.348  1031  2872 I ActivityTaskManager: START u0 {act=android.intent.action.VIEW dat=content://pl.solidexplorer2.files/storage/emulated/0/Download/AnkiDroid-2.12alpha11.apk typ=application/vnd.android.package-archive flg=0x10000003 cmp=com.google.android.packageinstaller/com.android.packageinstaller.InstallStart (has extras)} from uid 10155
06-18 15:36:27.359   565   610 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 1]
06-18 15:36:27.359   565   610 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 1]
06-18 15:36:27.380  5948  5948 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@eb35d77
06-18 15:36:27.402  1031  1586 I ActivityTaskManager: START u0 {act=android.intent.action.VIEW dat=content://pl.solidexplorer2.files/storage/emulated/0/Download/AnkiDroid-2.12alpha11.apk typ=application/vnd.android.package-archive flg=0x2000000 cmp=com.google.android.packageinstaller/com.android.packageinstaller.InstallStaging (has extras)} from uid 10077
06-18 15:36:27.428  5948  5948 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@e765a13
06-18 15:36:27.446  3762  7503 E SQLiteDatabase: Error inserting flex_time=9000 job_id=-1 period=20000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=202115000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1592487387443 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0
06-18 15:36:27.446  3762  7503 E SQLiteDatabase: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
06-18 15:36:27.446  3762  7503 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
06-18 15:36:27.446  3762  7503 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:879)
06-18 15:36:27.446  3762  7503 E SQLiteDatabase:        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
06-18 15:36:27.446  3762  7503 E SQLiteDatabase:        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
06-18 15:36:27.446  3762  7503 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1599)
06-18 15:36:27.446  3762  7503 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1468)
06-18 15:36:27.446  3762  7503 E SQLiteDatabase:        at aqew.a(:com.google.android.gms@202115039@20.21.15 (120408-313409149):146)
06-18 15:36:27.446  3762  7503 E SQLiteDatabase:        at aqeg.a(:com.google.android.gms@202115039@20.21.15 (120408-313409149):190)
06-18 15:36:27.446  3762  7503 E SQLiteDatabase:        at aqeg.a(:com.google.android.gms@202115039@20.21.15 (120408-313409149):23)
06-18 15:36:27.446  3762  7503 E SQLiteDatabase:        at aqeg.a(:com.google.android.gms@202115039@20.21.15 (120408-313409149):185)
06-18 15:36:27.446  3762  7503 E SQLiteDatabase:        at aqaq.run(:com.google.android.gms@202115039@20.21.15 (120408-313409149):9)
06-18 15:36:27.446  3762  7503 E SQLiteDatabase:        at sjk.b(:com.google.android.gms@202115039@20.21.15 (120408-313409149):12)
06-18 15:36:27.446  3762  7503 E SQLiteDatabase:        at sjk.run(:com.google.android.gms@202115039@20.21.15 (120408-313409149):7)
06-18 15:36:27.446  3762  7503 E SQLiteDatabase:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-18 15:36:27.446  3762  7503 E SQLiteDatabase:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-18 15:36:27.446  3762  7503 E SQLiteDatabase:        at spg.run(:com.google.android.gms@202115039@20.21.15 (120408-313409149):0)
06-18 15:36:27.446  3762  7503 E SQLiteDatabase:        at java.lang.Thread.run(Thread.java:919)
06-18 15:36:27.498  1031  2872 I ActivityTaskManager: START u0 {act=android.intent.action.VIEW dat=file:///data/user_de/0/com.google.android.packageinstaller/no_backup/package3038597938313552374.apk flg=0x2010000 cmp=com.google.android.packageinstaller/com.android.packageinstaller.DeleteStagedFileOnResult (has extras)} from uid 10077
06-18 15:36:27.498  1031  1269 I ActivityTaskManager: Displayed com.google.android.packageinstaller/com.android.packageinstaller.InstallStaging: +145ms
06-18 15:36:27.520  5948  5948 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@dc6fa0f
06-18 15:36:27.531  1031  2872 I ActivityTaskManager: START u0 {act=android.intent.action.VIEW dat=file:///data/user_de/0/com.google.android.packageinstaller/no_backup/package3038597938313552374.apk flg=0x10000 cmp=com.google.android.packageinstaller/com.android.packageinstaller.PackageInstallerActivity (has extras)} from uid 10077
06-18 15:36:27.567  5948  5948 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@7aa1cd2
06-18 15:36:28.192  1031  1920 I ActivityTaskManager: START u0 {dat=file:///data/user_de/0/com.google.android.packageinstaller/no_backup/package3038597938313552374.apk flg=0x2000000 cmp=com.google.android.packageinstaller/com.android.packageinstaller.InstallInstalling (has extras)} from uid 10077
06-18 15:36:28.198   565   610 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 1]
06-18 15:36:28.198   565   610 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 1]
06-18 15:36:28.220  5948  5948 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@648d948
06-18 15:36:28.649  1031  1286 W PackageManager: Downgrade detected: Update version code 21200111 is older than current 121200108
06-18 15:36:28.662  1031  2872 I ActivityTaskManager: START u0 {dat=file:///data/user_de/0/com.google.android.packageinstaller/no_backup/package3038597938313552374.apk flg=0x2000000 cmp=com.google.android.packageinstaller/com.android.packageinstaller.InstallFailed (has extras)} from uid 10077
06-18 15:36:28.664   565   610 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 1]
06-18 15:36:28.664   565   610 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 1]
06-18 15:36:28.686  5948  5948 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@187a4a2
06-18 15:36:28.709  5948  5948 D InstallFailed: Installation status code: 1
```

**Comment by mikehardy** [comment]
Interesting. This is effectively intractable.
The version code series with ABI splits are now in separate ranges per-ABI


06-18 15:36:28.649  1031  1286 W PackageManager: Downgrade detected: Update version code 21200111 is older than current 121200108

It appears that you had the armv7 ABI installed and then went for the universal, that's not possible and won't be, and it's an unavoidable artifact of ABI splits (which are nevertheless the right thing to do)

I had been optimizing slightly for github resource usage by not publishing all the ABI splits for alphas, but if you intend to grab an alpha from github releases instead of having the play store install it, then you have to uninstall/reinstall or grab the correct ABI. I'll publish them all and a note on the releases about this need, with a pointer that most phones should try the armv8 one, and older models probably use the armv7 one

Can you confirm you attempted to install from the github releases section?

**Comment by rathsky** [comment]
Yes, I did grab your builds from github. Only place there is for the alphas anyway really: The Play Store only distributes betas and stables.

About that ABI issue: I can't "grab the correct" one or "[go] for the universal _[ABI]_" since a) there's always been only one such universal _APK_ (no such thing as universal ABI) in the github releases to pick from (ignoring the "parallel" issue) and b) the package installer doesn't offer any options whatsoever – it just auto-selects from the available ABIs.

But I see now that may indeed closer to the issue since there was some bug in the build scripts for a8 that deleted all ABIs except the armeabi-v7a one (they're back in a9).

So apparently the installer will merrily downgrade from arm64-v8a to armeabi-v7a but refuse to go back up again, even if the newer apk also carries a v7a build. Huh.

What's even odder though is that my other device is actually an old 32-bit one, ie. actually never ran anything but v7a, and likewise fails to move from a8.

**Comment by mikehardy** [comment]
Alphas will be delivered by play store if you follow the instructions for same, namely joining the google group that we use to flag users for alpha delivery, noted in the instructions: https://docs.ankidroid.org/#betaTesting

I believe you've mis-diagnosed, you should slow down.

The installer selects nothing, you simply feed it an APK and it is okay to install (same signature, higher version code == okay to install) or it is not.

The installer will never install an APK with same signature and lower version code.

The release script I use was under development for the ABI splits and did not post correctly for alpha7.
It posted the the armv7 APK for alpha8 (I thought this was reasonable as a start)
It posted the universal APK for alpha9 (I reconsidered and figured a universal APK would be safer)
It posted universal and one universal parallel build for alpha10 (adding the parallel build was an enhancement)
It posted universal and all universal parallels for alpha11 (that was actually a mistake)

Those are the facts as they happened.

What you report is essentially a bug, in that the Play Store (or anyone that installed alpha8) will have an ABI-split versionCode range and the universal APK from the releases page will never work for them, it will always appear as a downgrade. An unfortunate unexpected consequence

My proposed solution is still correct - publish the ABI splits on releases page along with user education on which to pick, so that even Play Store alpha consumers can successfully install them in they try.

**Comment by mikehardy** [comment]
This is by the way, alpha testing, I really appreciate the report, but with alphas there is always the chance something breaks.

**Comment by rathsky** [comment]
Oh, alright. Didn't know about the alpha group, that the versionCode changes with an ABI-split APK, nor notice that the v7-only apk for a8 (etc.) was intentional given it's not named differently yet.

Anyway, my last comment wasn't meant to be personal, I interpreted yours as ascribing intent to my actions (re. the ABIs) – which there wasn't – rather than just being descriptive. (Also, I misread _intractable_ for _untraceable_, ups.)

**Comment by mikehardy** [comment]
No worries, I've been moving really quickly on the source side of things lately and an unintended/unwanted side effect is that my text output is pretty robotic which is therefore easy to misread, because humans =/= robots

But at least on the robot side of things, we've got a fix that should be automated / persistent going forward, with a one-time education cost for people trying alphas direct from the releases page (since Play Store auto-selects the right one)

![AnkiDroid_Release_Example](https://user-images.githubusercontent.com/782704/85052406-779c5e00-b15e-11ea-9ac9-0046c73363cf.png)

And I really do appreciate the report, I wouldn't have noticed this otherwise and with any luck you'll be the only affected person total
