### ISSUE TITLE
UI can be accessed while syncing

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#6518]
Going to be replicated in a lot of stack traces where the database is null. Caused by pressing a deck and sync at the same time.

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/d8b3f32d-e3f4-4a92-94ab-219bab588927

```
0	--------- beginning of main
1	06-20 19:48:21.834 I/AnkiDroid( 8128): Sync: getting meta data from server
2	06-20 19:48:21.838 I/AnkiDroid( 8128): Sync: building local meta data
3	06-20 19:48:21.884 I/AnkiDroid( 8128): Sync: collection removed data
4	06-20 19:48:21.887 I/AnkiDroid( 8128): Sync: sending and receiving removed data
5	06-20 19:48:21.994 I/AnkiDroid( 8128): Sync: applying removed data
6	06-20 19:48:21.994 I/AnkiDroid( 8128): Sync: collection small changes
7	06-20 19:48:21.995 I/AnkiDroid( 8128): Sync: sending and receiving small changes
8	06-20 19:48:22.108 I/AnkiDroid( 8128): Sync: merging small changes
9	06-20 19:48:22.109 I/AnkiDroid( 8128): Sync: downloading chunked data
10	06-20 19:48:22.221 I/AnkiDroid( 8128): Sync: applying chunked data
11	06-20 19:48:22.225 I/AnkiDroid( 8128): Sync: collecting chunked data
12	06-20 19:48:22.301 I/AnkiDroid( 8128): Sync: sending chunked data
13	06-20 19:48:22.525 I/AnkiDroid( 8128): Sync: collecting chunked data
14	06-20 19:48:22.554 I/AnkiDroid( 8128): Sync: sending chunked data
15	06-20 19:48:22.863 I/AnkiDroid( 8128): Sync: sending finish command
16	06-20 19:48:23.021 I/AnkiDroid( 8128): Sync: finishing
17	06-20 19:48:23.033 I/AnkiDroid( 8128): flush - Saving information to DB...
18	06-20 19:48:23.060 I/AnkiDroid( 8128): Sync - Performing media sync
19	06-20 19:48:23.340 I/AnkiDroid( 8128): Sync Finished - Closing Collection
20	06-20 19:48:23.347 I/AnkiDroid( 8128): Collection closed
21	06-20 19:48:23.405 I/AnkiDroid( 8128): Sync was successful
22	06-20 19:48:23.406 I/AnkiDroid( 8128): Regular sync completed successfully
23	06-20 19:48:23.422 I/AnkiDroid( 8128): Begin openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
24	06-20 19:48:23.476 I/AnkiDroid( 8128): End openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
25	06-20 19:48:23.516 I/AnkiDroid( 8128): Updating deck list UI
26	06-20 19:48:24.813 I/AnkiDroid( 8128): Back key pressed
27	06-20 19:48:24.813 I/AnkiDroid( 8128): finishWithAnimation 4
28	06-20 19:48:24.823 I/AnkiDroid( 8128): AnkiActivity::onPause
29	06-20 19:48:24.841 I/AnkiDroid( 8128): AnkiActivity::onStart
30	06-20 19:48:24.843 I/AnkiDroid( 8128): AnkiActivity::onResume
31	06-20 19:48:25.246 I/AnkiDroid( 8128): AnkiActivity::onStop
32	06-20 19:48:25.249 I/AnkiDroid( 8128): AnkiActivity::onDestroy
33	06-20 19:48:30.709 I/AnkiDroid( 8128): AbstractFlashcardViewer:: Show answer button pressed
34	06-20 19:48:32.243 I/AnkiDroid( 8128): AbstractFlashcardViewer:: EASE_2 pressed
35	06-20 19:48:32.244 I/AnkiDroid( 8128): Answering card
36	06-20 19:48:32.245 I/AnkiDroid( 8128): Answering card 1419509796581
37	06-20 19:48:32.256 E/AnkiDroid( 8128): CollectionTask/ doInBackgroundAnswerCard - RuntimeException on answering card
---- crash
```

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.ichi2.libanki.DB.update(java.lang.String, android.content.ContentValues, java.lang.String, java.lang.String[])' on a null object reference
at com.ichi2.libanki.Card.flushSched(Card.java:17)
at com.ichi2.libanki.sched.Sched.answerCard(Sched.java:26)
at com.ichi2.async.CollectionTask.doInBackgroundAnswerCard(CollectionTask.java:9)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:52)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
```

**Comment by Arthur-Milchior** [comment]
The way I read the stack, it seems update is called on null. Which would mean the database object is null and not the card.

**Comment by david-allison-1** [comment]
Oh lord, you're right, thanks!

**Comment by Arthur-Milchior** [comment]
The real question to me, is how pressing the back key can lead to the reviewer.

The way I understand thing is: some sync did occur. The user pressed back (?) and this led them to the deck reviewer. Then they reviewed the card. The trouble is that the card object contains a collection element. This element was closed during sync, which implies that the database was set to null. Normally, when collection get closed, all objects disappear, so it should not be a problem.
If my intuition is right, https://github.com/ankidroid/Anki-Android/pull/6045 would have avoided this very problem, but that does not solve the biggest question which is: how did this occur. How can you get to reviewer by pressing the back button.

I just tried something: pressing on a deck with a lot of subdecks, and just after that, pressing the sync button. It fails and create an error. However, this is not the same error as this one. The difference could be because I use a version of ankidroid with all of my PR in it, and so the behavior here is different. I'll need to try with current master. However, that still interesting to know that clicking on a deck does not deactivate other buttons.

**Comment by Arthur-Milchior** [comment]
I just installed back 2.11.3 to check. I can reproduce similar trouble.
If I press on sync and on a deck at the same time, either :
* the reviewer opens, when I come back to deck picker, I see an error and ankidroid restart
* the sync start, then the start becomes dark and I get the following error

>   java.io.InterruptedIOException: interrupted
        at okio.Timeout.throwIfReached(Timeout.java:146)
        at okio.Okio$2.read(Okio.java:137)
        at com.ichi2.libanki.sync.CountingFileRequestBody.writeTo(CountingFileRequestBody.java:64)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.ichi2.libanki.sync.HttpSyncer.lambda$getHttpClientBuilder$0(HttpSyncer.java:108)
        at com.ichi2.libanki.sync.-$$Lambda$HttpSyncer$9vV6H9vlVfbLXrkXdxd76WTPq08.intercept(Unknown Source:0)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
        at okhttp3.RealCall.execute(RealCall.java:93)
        at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:237)
        at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:171)
        at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:161)
        at com.ichi2.libanki.sync.RemoteServer._run(RemoteServer.java:113)
        at com.ichi2.libanki.sync.RemoteServer.abort(RemoteServer.java:108)
        at com.ichi2.libanki.sync.Syncer.throwExceptionIfCancelled(Syncer.java:911)
        at com.ichi2.libanki.sync.Syncer.sync(Syncer.java:157)
        at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:304)
        at com.ichi2.async.Connection.doOneInBackground(Connection.java:195)
        at com.ichi2.async.Connection.doInBackground(Connection.java:185)
        at com.ichi2.async.Connection.doInBackground(Connection.java:51)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
E/Connection: doInBackgroundSync error
    java.lang.RuntimeException: java.io.InterruptedIOException: interrupted
        at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:255)
        at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:171)
        at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:161)
        at com.ichi2.libanki.sync.RemoteServer._run(RemoteServer.java:113)
        at com.ichi2.libanki.sync.RemoteServer.abort(RemoteServer.java:108)
        at com.ichi2.libanki.sync.Syncer.throwExceptionIfCancelled(Syncer.java:911)
        at com.ichi2.libanki.sync.Syncer.sync(Syncer.java:157)
        at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:304)
        at com.ichi2.async.Connection.doOneInBackground(Connection.java:195)
        at com.ichi2.async.Connection.doInBackground(Connection.java:185)
        at com.ichi2.async.Connection.doInBackground(Connection.java:51)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.InterruptedIOException: interrupted
        at okio.Timeout.throwIfReached(Timeout.java:146)
        at okio.Okio$2.read(Okio.java:137)
        at com.ichi2.libanki.sync.CountingFileRequestBody.writeTo(CountingFileRequestBody.java:64)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.ichi2.libanki.sync.HttpSyncer.lambda$getHttpClientBuilder$0(HttpSyncer.java:108)
        at com.ichi2.libanki.sync.-$$Lambda$HttpSyncer$9vV6H9vlVfbLXrkXdxd76WTPq08.intercept(Unknown Source:0)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
        at okhttp3.RealCall.execute(RealCall.java:93)
        at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:237)
        at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:171) 
        at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:161) 
        at com.ichi2.libanki.sync.RemoteServer._run(RemoteServer.java:113) 
        at com.ichi2.libanki.sync.RemoteServer.abort(RemoteServer.java:108) 
        at com.ichi2.libanki.sync.Syncer.throwExceptionIfCancelled(Syncer.java:911) 
        at com.ichi2.libanki.sync.Syncer.sync(Syncer.java:157) 
        at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:304) 
        at com.ichi2.async.Connection.doOneInBackground(Connection.java:195) 
        at com.ichi2.async.Connection.doInBackground(Connection.java:185) 
        at com.ichi2.async.Connection.doInBackground(Connection.java:51) 
        at android.os.AsyncTask$3.call(AsyncTask.java:378) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by david-allison-1** [comment]
> I just installed back 2.11.3 to check. I can reproduce similar trouble.
> If I press on sync and on a deck at the same time, either :
> 
> * the reviewer opens, when I come back to deck picker, I see an error and ankidroid restart
> * the sync start, then the start becomes dark and I get the following error

Is this a separate issue, or does it also trigger this stack trace?

**Comment by Arthur-Milchior** [comment]
My intuition is that it is partially related.

I.e. this seems to be a non-deterministic bug. I would expect that it could be related to the current bug, but I can't reproduce the exact same stack trace. However, I still found interesting to write down what I did try, so that you or other mainteneurs don't lose time trying for yourself.
It may be worth creating another issue for it. Especially since I don't know what is the usual way to deal with two simultaneous clicks

**Comment by david-allison-1** [comment]
Ah, got it

<details><summary></summary>

```
2020-06-21 17:12:36.292 24068-25570/com.ichi2.anki E/CollectionTask: doInBackgroundAnswerCard - RuntimeException on answering card
    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.ichi2.libanki.DB.update(java.lang.String, android.content.ContentValues, java.lang.String, java.lang.String[])' on a null object reference
        at com.ichi2.libanki.Card.flushSched(Card.java:236)
        at com.ichi2.libanki.sched.SchedV2.answerCard(SchedV2.java:185)
        at com.ichi2.async.CollectionTask.doInBackgroundAnswerCard(CollectionTask.java:527)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:268)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:76)
        at android.os.AsyncTask$2.call(AsyncTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
```
</details>

**Comment by Arthur-Milchior** [comment]
How did you get it ?

**Comment by Arthur-Milchior** [comment]
As a side note: this crash is actually a good thing. It would have been a bigger problem if the review was registered. At least if the card status (queue, type) was changed during the sync. So in a sens, this is what setting the DB to null is supposed to have as effect, avoiding corruption if something else goes wrong

**Comment by david-allison-1** [comment]
> How did you get it ?

Via your steps to reproduce it.

**Comment by david-allison-1** [comment]
This is one of our big crashers, manifesting in many different ways

**Comment by dae** [comment]
@david-allison Still the case?
