### ISSUE TITLE
[ACRA] OutOfMemoryError - applyDeckPickerBackground

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6608]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/0119ca5b-f0fc-47b8-b500-4cff02b866c2

```
java.lang.OutOfMemoryError: Failed to allocate a 103833612 byte allocation with 16766432 free bytes and 46MB until OOM
at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:646)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:622)
at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:402)
at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:428)
at android.graphics.drawable.Drawable.createFromPath(Drawable.java:1237)
at com.ichi2.anki.DeckPicker.applyDeckPickerBackground(DeckPicker.java:10)
at com.ichi2.anki.DeckPicker.onCreate(DeckPicker.java:38)
at android.app.Activity.performCreate(Activity.java:6757)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2703)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2811)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6316)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

**Comment by mikehardy** [comment]
This may be one of the very rare cases where catching an OOMError is valid! I think it's recoverable at that spot

**Comment by david-allison-1** [comment]
Agreed - I'll get on it

**Comment by mikehardy** [comment]
This popped up in a different spot somehow?

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/7e56c362-886d-4126-ba9d-89061597064f

```

ANDROID_VERSION | 8.1.0
-- | --
APP_VERSION_CODE | 321200206
APP_VERSION_NAME | 2.12.0beta6
AVAILABLE_MEM_SIZE | 51373887488
BRAND | SMARTISAN

```

```
java.lang.RuntimeException: Canvas: trying to draw too large(155293136bytes) bitmap.
at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
at android.view.View.getDrawableRenderNode(View.java:19903)
at android.view.View.drawBackground(View.java:19839)
at android.view.View.draw(View.java:19636)
at android.view.View.updateDisplayListIfDirty(View.java:18515)
at android.view.View.draw(View.java:19373)
at android.view.ViewGroup.drawChild(ViewGroup.java:4353)
at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:14)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4139)
at android.view.View.draw(View.java:19648)
at android.view.View.updateDisplayListIfDirty(View.java:18515)
at android.view.View.draw(View.java:19373)
at android.view.ViewGroup.drawChild(ViewGroup.java:4353)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4139)
at android.view.View.updateDisplayListIfDirty(View.java:18506)
at android.view.View.draw(View.java:19373)
at android.view.ViewGroup.drawChild(ViewGroup.java:4353)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4139)
at android.view.View.updateDisplayListIfDirty(View.java:18506)
at android.view.View.draw(View.java:19373)
at android.view.ViewGroup.drawChild(ViewGroup.java:4353)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4139)
at android.view.View.updateDisplayListIfDirty(View.java:18506)
at android.view.View.draw(View.java:19373)
at android.view.ViewGroup.drawChild(ViewGroup.java:4353)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4139)
at android.view.View.updateDisplayListIfDirty(View.java:18506)
at android.view.View.draw(View.java:19373)
at android.view.ViewGroup.drawChild(ViewGroup.java:4353)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4139)
at android.view.View.draw(View.java:19648)
at com.android.internal.policy.DecorView.draw(DecorView.java:1163)
at android.view.View.updateDisplayListIfDirty(View.java:18515)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:737)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:743)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:890)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:3453)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3247)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2796)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1758)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7866)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:975)
at android.view.Choreographer.doCallbacks(Choreographer.java:781)
at android.view.Choreographer.doFrame(Choreographer.java:716)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:961)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:167)
at android.app.ActivityThread.main(ActivityThread.java:7145)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)
```

**Comment by david-allison-1** [comment]
I believe this can no longer happen via the UI, and is just a remnant of the issue, or copying in a bad file to the AnkiDroid folder.

"Clear Data" will fix this.

**Comment by mikehardy** [comment]
works for me :-)
