### ISSUE TITLE
BasicImageFieldController - getUriForFile -  Failed to find configured root that contains /

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6628]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/dee25249-a86f-40f9-bce9-a038b518356c

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity}: java.lang.IllegalArgumentException: Failed to find configured root that contains /
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3448)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:7814)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
Caused by: java.lang.IllegalArgumentException: Failed to find configured root that contains /
at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:13)
at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:2)
at com.ichi2.anki.multimediacard.fields.BasicImageFieldController.getUriForFile(BasicImageFieldController.java:3)
at com.ichi2.anki.multimediacard.fields.BasicImageFieldController.createUI(BasicImageFieldController.java:5)
at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.recreateEditingUi(MultimediaEditFieldActivity.java:16)
at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.onCreate(MultimediaEditFieldActivity.java:17)
at android.app.Activity.performCreate(Activity.java:7955)
at android.app.Activity.performCreate(Activity.java:7944)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
... 11 more
```

**Comment by mikehardy** [comment]
Ahh, wish I had more info on that filename. I'll have to dig in on that.
Looks like we're going to get some test coverage in the area haha

**Comment by david-allison-1** [comment]
Had a second report: 

"java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/AnkiDroid/collection.media/20191007_165350_001_saved.jpg"

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/42165fe8-ff7d-4804-b594-c4d1c7b3730f

**Comment by mikehardy** [comment]
Thanks for grabbing these - I appreciate it - I'm going to prioritize release engineering by finishing current merges and get another beta out (plus an alpha since that channel is de-overlapped) but I'm neck deep in a big Day Job feature so it will be a little bit before I take up my individual-contribution stuff here (this bug, and any possible unique-name/rename stuff)
