### ISSUE TITLE
NoteEditor - CardTemplatePreviewer - ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6644]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/a01688a2-216f-4aa0-9af2-4d395f61fdc6

2.12.0beta3

```
0	--------- beginning of main
1	07-06 17:02:45.243 I/AnkiDroid(24389): CardBrowser:: Completed doInBackgroundSearchCards Successfully
2	07-06 17:02:45.382 I/AnkiDroid(24389): AnkiActivity::onStop - NoteEditor
3	07-06 17:02:45.386 I/AnkiDroid(24389): AnkiActivity::onDestroy - NoteEditor
4	07-06 17:02:45.937 I/AnkiDroid(24389): AnkiActivity::onPause - CardBrowser
5	07-06 17:02:45.953 I/AnkiDroid(24389): AnkiActivity::onCreate - NoteEditor
6	07-06 17:02:45.990 I/AnkiDroid(24389): onCollectionLoaded() Edit note activity successfully started with card id 1485680989833
7	07-06 17:02:45.997 I/AnkiDroid(24389): AnkiActivity::onStart - NoteEditor
8	07-06 17:02:46.001 I/AnkiDroid(24389): AnkiActivity::onResume - NoteEditor
9	07-06 17:02:46.011 I/AnkiDroid(24389): Disabling Extended Text UI
10	07-06 17:02:46.011 I/AnkiDroid(24389): Disabling Extended Text UI
11	07-06 17:02:46.288 I/AnkiDroid(24389): AnkiActivity::onStop - CardBrowser
12	07-06 17:02:46.291 I/AnkiDroid(24389): flush - Saving information to DB...
13	07-06 17:02:47.621 I/AnkiDroid(24389): Disabling Extended Text UI
14	07-06 17:02:47.631 I/AnkiDroid(24389): Disabling Extended Text UI
15	07-06 17:02:49.472 I/AnkiDroid(24389): NoteEditor:: Preview button pressed
16	07-06 17:02:49.474 I/AnkiDroid(24389): Saving instance
17	07-06 17:02:49.498 I/AnkiDroid(24389): AnkiActivity::onPause - NoteEditor
18	07-06 17:02:49.534 I/AnkiDroid(24389): AnkiActivity::onCreate - CardTemplatePreviewer
```

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.CardTemplatePreviewer}: java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3448)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:7814)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
at com.ichi2.libanki.Note.setField(Note.java:1)
at com.ichi2.anki.CardTemplatePreviewer.onCollectionLoaded(CardTemplatePreviewer.java:11)
at com.ichi2.anki.AnkiActivity.startLoadingCollection(AnkiActivity.java:4)
at com.ichi2.anki.CardTemplatePreviewer.onCreate(CardTemplatePreviewer.java:19)
at android.app.Activity.performCreate(Activity.java:7955)
at android.app.Activity.performCreate(Activity.java:7944)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
... 11 more
```

**Comment by mikehardy** [comment]
I have been sort of waiting for the first CardTemplateEditor bug!

**Comment by david-allison-1** [comment]
@mikehardy Repro steps:

* Create Note
* Change Note type (to something with different field counts)
* Preview

**Comment by mikehardy** [comment]
That was the first thing I tried and it didn't repro for me, I was certain that would be the case, it just didn't trigger for my card type switch. I'll try various combos again and see if I can get it.

**Comment by david-allison-1** [comment]
I couldn't repro with an unsaved note, but could with a saved note.
