### ISSUE TITLE
"Collection not opened" message after updating to v2.12 beta 4

### ISSUE THREAD

**Issue by mat4r** [ankidroid/Anki-Android#6647]
Immediately after updating to v2.12 beta 4 I started seeing the following message :

Collection not opened 

An error occurred while accessing your collection. It may 
have been caused by a harmless bug, or there may be a 
problem with it. 

Try running check database, or restoring from backup by 
pressing the "options" button. If you continue to see this 
message, please file a bug report: 
https://docs.ankidroid.org/help.html 

- "check the database" option did not solve the issue unfortunately.
* sorry for not using the format to report the issue 😅

**Comment by david-allison-1** [comment]
Thanks so much! This lets us reproduce #6383.

I'm going to close this as a duplicate, please follow the linked issue to track the resolution.

```
    java.lang.NullPointerException: Attempt to read from null array
        at com.ichi2.libanki.sched.Sched.deckDueList(Sched.java:230)
        at com.ichi2.libanki.sched.SchedV2.deckDueTree(SchedV2.java:469)
        at com.ichi2.async.CollectionTask.doInBackgroundLoadDeckCounts(CollectionTask.java:601)
        at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:304)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:265)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:77)
        at android.os.AsyncTask$2.call(AsyncTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
```

All the best,

David

**Comment by mikehardy** [comment]
I saw a lot of trim / name normalization discussion that made me think this was triaged already, but I don't see a PR yet? No pressure just super busy today (sorry 😓 ) and don't want to miss it if we have one, I'll put an alpha out as soon as the first 2.13alpha blowback issues are put out

**Comment by david-allison-1** [comment]
@mikehardy It's #6383. PR is: https://github.com/ankidroid/Anki-Android/pull/6648
