### ISSUE TITLE
_walkingCount - NullPointerException

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6650]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/6cd67d36-9604-4860-826c-6639ff5c0495

```
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.ichi2.utils.JSONObject.getLong(java.lang.String)' on a null object reference
at com.ichi2.libanki.sched.SchedV2._walkingCount(SchedV2.java:6)
at com.ichi2.libanki.sched.SchedV2._resetNewCount(SchedV2.java:1)
at com.ichi2.libanki.sched.SchedV2.recalculateCounts(SchedV2.java:3)
at com.ichi2.libanki.sync.Syncer.sanityCheck(Syncer.java:40)
at com.ichi2.libanki.sync.Syncer.sync(Syncer.java:84)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:16)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:2)
at com.ichi2.async.Connection.doInBackground(Connection.java:4)
at com.ichi2.async.Connection.doInBackground(Connection.java:1)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
```

**Comment by Arthur-Milchior** [comment]
I suspect it is still the buf with parents returning bull in the deck list

**Comment by pullreq1** [comment]
I found a similar issue https://github.com/ankidroid/Anki-Android/issues/6612 that has a similar stack trace.

Do you think that the issue helps either in (1) understanding more about the context of bug ( e.g. in which the bug occurs app version, library version, etc.), (2) finding the faulty program location, or (3) finding the fixes for the bugs?

**Comment by Arthur-Milchior** [comment]
@pullreq1 I don't understand what you say. You're referring to an issue opened 23 days ago, not to a new issue. It's not clear what occured. Can you just open a new issue ? This way, you'll also see how to give us all relevant information so that we can debug if required

**Comment by pullreq1** [comment]
Sorry, I forgot to explain the context. We are developing a Github issue/pull request recommendation system that will suggest relevant Github issue to help you resolve the open Github issue.

**Comment by mikehardy** [comment]
@pullreq1 please don't practice on our repo, it's noise to us. It sounds like an interesting project but we get notifications for all comments etc and if it's not working well I could do with less notifications. I love the avatar though :)
