### ISSUE TITLE
[ACRA] We looked for deck "Sketchy Pharm::8 Antineoplastics::3 Kinase Inhibitors & Monoclonal Antibodies " and instead got deck "Sketchy Pharm::8 Antineoplastics::3 Kinase Inhibitors & Monoclonal Antibodies".

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6651]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/c0c06b8c-1a2a-4aa7-b33d-c642c7314954

Likely due to newline

```
We looked for deck "Sketchy Pharm::8 Antineoplastics::3 Kinase Inhibitors & Monoclonal Antibodies
" and instead got deck "Sketchy Pharm::8 Antineoplastics::3 Kinase Inhibitors & Monoclonal Antibodies".
```

```
com.ichi2.anki.exception.ManuallyReportedException: We looked for deck "Sketchy Pharm::8 Antineoplastics::3 Kinase Inhibitors & Monoclonal Antibodies
" and instead got deck "Sketchy Pharm::8 Antineoplastics::3 Kinase Inhibitors & Monoclonal Antibodies".
at com.ichi2.anki.AnkiDroidApp.sendExceptionReport(AnkiDroidApp.java:1)
at com.ichi2.libanki.Decks$NameMap.get(Decks.java:6)
at com.ichi2.libanki.Decks.byName(Decks.java:1)
at com.ichi2.libanki.Decks._checkDeckTree(Decks.java:30)
at com.ichi2.libanki.Decks.checkIntegrity(Decks.java:3)
at com.ichi2.libanki.sched.Sched.deckDueList(Sched.java:2)
at com.ichi2.libanki.sched.SchedV2.deckDueTree(SchedV2.java:2)
at com.ichi2.async.CollectionTask.doInBackgroundLoadDeckCounts(CollectionTask.java:3)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:43)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
at com.ichi2.anki.widgets.DeckAdapter.processNodes(DeckAdapter.java:12)
at com.ichi2.anki.widgets.DeckAdapter.processNodes(DeckAdapter.java:12)
at com.ichi2.anki.widgets.DeckAdapter.processNodes(DeckAdapter.java:12)
at com.ichi2.anki.widgets.DeckAdapter.processNodes(DeckAdapter.java:12)
at com.ichi2.anki.widgets.DeckAdapter.processNodes(DeckAdapter.java:12)
at com.ichi2.anki.widgets.DeckAdapter.processNodes(DeckAdapter.java:12)
```

**Comment by david-allison-1** [comment]
I believe this is another example of #6647

**Comment by Arthur-Milchior** [comment]
Seems likely

**Comment by Arthur-Milchior** [comment]
But require my last pr, because the one who updated nameMap didn't take trimming into account
