### ISSUE TITLE
Deck Picker Task Cancellation: ConcurrentModificationException

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6653]
On my personal collection/device

Just after completing a deck, I was going through very quickly

[Anki-ConcurrentModificationLogcat.txt](https://github.com/ankidroid/Anki-Android/files/4887420/Anki-ConcurrentModificationLogcat.txt)

```
2020-07-07 23:22:07.143 12524-12524/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 12524
    java.lang.RuntimeException: Unable to pause activity {com.ichi2.anki/com.ichi2.anki.DeckPicker}: java.util.ConcurrentModificationException
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4742)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4691)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4626)
        at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.util.ConcurrentModificationException
        at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:967)
        at java.util.LinkedList$ListItr.next(LinkedList.java:889)
        at com.ichi2.async.CollectionTask.cancelAllTasks(CollectionTask.java:235)
        at com.ichi2.anki.DeckPicker.onPause(DeckPicker.java:867)
        at android.app.Activity.performPause(Activity.java:7663)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1536)
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4726)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4691) 
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4626) 
        at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
``

**Comment by Arthur-Milchior** [comment]
I'm quite surprised. I would have thought that, thanks to `Collections.synchronizedList` and the fact that the code synchronize on sTasks, it was impossible to get a concurrent modification.

**Comment by Arthur-Milchior** [comment]
I guess that the "good" news is that, if I'm right and that, with my recent PR, starting at sLatestCreatedInstance and running through all mPreviousTask is a list which contains all pending task, then we can run through all tasks without having to actually uses a list. 
However, it does not explain why this error occurred in the first place, and that still seems quite interesting

**Comment by mikehardy** [comment]
synchronization is hard :-), synchronizing on sTasks and having a synchronizedList will be working with unrelated locks, and certain Collections methods (like add) are not supported by the synchronizedList if you are iterating on it etc. I haven't investigated this but there are lots of opportunities for surprise

**Comment by Arthur-Milchior** [comment]
I really don't get it. https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#synchronizedList(java.util.List) only warn iteration should be in synchronized block, which is the case here.

**Comment by david-allison-1** [comment]
Also occurs in Card Browser

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/49eb684e-3c9e-49d6-be6e-9a84488f7614

**Comment by david-allison-1** [comment]
This would fail in a singlethreaded environment

https://github.com/ankidroid/Anki-Android/blob/4d4abb8e0736cf5f08ed38ee9278df677e24f057/AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java#L278-L287

https://github.com/ankidroid/Anki-Android/blob/4d4abb8e0736cf5f08ed38ee9278df677e24f057/AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java#L244-L258

We call `sTasks.remove` while iterating
