### ISSUE TITLE
Whiteboard Pen Color - Could not find icon

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6665]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/d571d955-61c6-4f0a-bcc9-9e89f40d52b5

2.12beta5

Ref: #6550

```
android.content.res.Resources$NotFoundException: File res/drawable/ic_color_lens_white_24dp.xml from drawable resource ID #0x7f0800a1. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
at android.content.res.Resources.loadDrawable(Resources.java:3451)
at android.content.res.Resources.getDrawable(Resources.java:1894)
at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:3)
at com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.java:28)
at android.app.Activity.onCreatePanelMenu(Activity.java:2608)
at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:1)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:5)
at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:1)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
at android.view.Choreographer.doCallbacks(Choreographer.java:574)
at android.view.Choreographer.doFrame(Choreographer.java:543)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5433)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
at dalvik.system.NativeStart.main(Native Method)
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag vector
at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:969)
at android.graphics.drawable.Drawable.createFromXml(Drawable.java:913)
at android.content.res.Resources.loadDrawable(Resources.java:3447)
... 23 more
```

**Comment by mikehardy** [comment]
Reproduced but you need an old emulator to do it,

1.  I used API16 emulator
1. set whiteboard pen color to always show in app bar buttons in reviewer preferences
1. start  reviewing 
1. open top right option mention to "enable whiteboard"


crash

I know SVG's can work on API16 but the way we're doing it must be wrong.

**Comment by mikehardy** [comment]
This PR branch (unfinished but eventually will be finished) has a massive conversion of PNG to SVG, so might be interesting https://github.com/mikehardy/Anki-Android/commits/convert-icons-to-vector-assets

**Comment by infinyte7** [comment]
Okay, I will look into this.
