### ISSUE TITLE
ReminderService - Collection was null

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6666]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/4d47e023-7d2e-454f-b6a4-a64aa0011d2a

2.12.beta5
```
java.lang.RuntimeException: Unable to start receiver com.ichi2.anki.services.ReminderService: java.lang.NullPointerException: Attempt to invoke virtual method 'com.ichi2.libanki.Decks com.ichi2.libanki.Collection.getDecks()' on a null object reference
at android.app.ActivityThread.handleReceiver(ActivityThread.java:4120)
at android.app.ActivityThread.access$1700(ActivityThread.java:272)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8016)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.ichi2.libanki.Decks com.ichi2.libanki.Collection.getDecks()' on a null object reference
at com.ichi2.anki.services.ReminderService.onReceive(ReminderService.java:3)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:4111)
... 8 more
```

**Comment by Arthur-Milchior** [comment]
This means `CollectionHelper.getInstance().getCol(context)` did return `null`. No idea what should occur in this case. I still have little understanding of what exactly is an instance

**Comment by mikehardy** [comment]
An "instance" is the actual object living in memory with state in the JVM. `getInstance()` is a "static factory method", and that is how you implement a "singleton pattern" in Java. A "singleton" is a software design where you say "look, it only makes sense to ever have a single one of these in the entire system, we never want more than one, and usually we want that one to live forever".

So you want one and only one of these things - a singleton - and that is how the decks collection is. Just one. Should be in memory at all times with state, except for just a few cases.

So to make that happen you don't just `new ...` the things all the time, you have a static method that you call to get "the singleton instance for this object", and the static method does a quick check to see if it exists yet - if it does you get the instance, if not then typically a static factory will fabricate the single instance for you (that's why you call it a factory: it makes the thing) and then it stores that instance as internal state and returns it to you. All future callers get that same instance.

et voila, static factory method implementing the singleton pattern.

The case where it might be null here is I suppose right after a synch or after some sanity check fail when the collection is no longer valid and all the state should be reconstructed.

In this case, Reminders are generally considered a low priority item versus crashing, so all exceptions or invalid state assumptions in the reminder class should be gracefully handled by logging them, and then just stopping with reminder construction, or perhaps sleeping and re-trying a bit later just in case it resolves itself
