### ISSUE TITLE
FlashCardViewer - resumeTimer - catch Exceptions and move to background thread

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6671]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/c630d5ca-2e79-4487-9d0c-784fa955b8f8

```
java.lang.RuntimeException: Unable to resume activity {com.ichi2.anki/com.ichi2.anki.CardTemplatePreviewer}: com.ichi2.utils.JSONException: org.json.JSONException: No value for maxTaken
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4410)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4442)
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2146)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:7770)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
Caused by: com.ichi2.utils.JSONException: org.json.JSONException: No value for maxTaken
at com.ichi2.utils.JSONObject.get(JSONObject.java:2)
at org.json.JSONObject.getInt(JSONObject.java:488)
at com.ichi2.utils.JSONObject.getInt(JSONObject.java:1)
at com.ichi2.libanki.Card.timeLimit(Card.java:2)
at com.ichi2.libanki.Card.timeTaken(Card.java:2)
at com.ichi2.anki.AbstractFlashcardViewer.resumeTimer(AbstractFlashcardViewer.java:3)
at com.ichi2.anki.AbstractFlashcardViewer.onResume(AbstractFlashcardViewer.java:2)
at com.ichi2.anki.CardTemplatePreviewer.onResume(CardTemplatePreviewer.java:1)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
at android.app.Activity.performResume(Activity.java:8129)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4400)
... 11 more
```

**Comment by david-allison-1** [comment]
`maxTaken` should be fixed in #5932
