### ISSUE TITLE
Note Preview - Crash if editing a card in a Dynamic Deck

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6685]
Thanks to anonymous beta tester f9852c31-9c99-4617-9d72-91e65ac40ef9 

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/f7d8edbb-1005-4a25-98e7-bfa10702e548

```
java.lang.RuntimeException: Unable to resume activity {com.ichi2.anki/com.ichi2.anki.CardTemplatePreviewer}: com.ichi2.utils.JSONException: org.json.JSONException: No value for maxTaken
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4430)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
at android.os.Handler.dispatchMessage(Handler.java:112)
at android.os.Looper.loop(Looper.java:216)
at android.app.ActivityThread.main(ActivityThread.java:7625)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: com.ichi2.utils.JSONException: org.json.JSONException: No value for maxTaken
at com.ichi2.utils.JSONObject.get(JSONObject.java:2)
at org.json.JSONObject.getInt(JSONObject.java:481)
at com.ichi2.utils.JSONObject.getInt(JSONObject.java:1)
at com.ichi2.libanki.Card.timeLimit(Card.java:2)
at com.ichi2.libanki.Card.timeTaken(Card.java:2)
at com.ichi2.anki.AbstractFlashcardViewer.resumeTimer(AbstractFlashcardViewer.java:3)
at com.ichi2.anki.AbstractFlashcardViewer.onResume(AbstractFlashcardViewer.java:2)
at com.ichi2.anki.CardTemplatePreviewer.onResume(CardTemplatePreviewer.java:1)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
at android.app.Activity.performResume(Activity.java:7614)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4412)
... 11 more
Caused by: org.json.JSONException: No value for maxTaken
at org.json.JSONObject.get(JSONObject.java:392)
at com.ichi2.utils.JSONObject.get(JSONObject.java:1)
... 21 more
```

**Comment by david-allison-1** [comment]
We handle it correctly inside the card, but we overwrite the value here:

https://github.com/ankidroid/Anki-Android/blob/184effd4d1c47fb3308b26bd308bcce36ccdb7e4/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java#L173

**Comment by mikehardy** [comment]
How strange. Perhaps it needs to persist odid or whatever is the other parts of dynamic deck cards? I don't use them myself much so that would explain it. This is probably somewhat easy to tickle with a robo-unit test then as well and would increase coverage tremendously as nothing in our unit tests works with dynamic decks yet.

I wish I had a solid memory of why I did this so I could at least tell you what I was thinking, in the area. Probably just that the card could be moved between decks so I needed to keep track of that, but if it's inside the card already...maybe was unnecessary to begin with

**Comment by david-allison-1** [comment]
Possibly because you can change the deck in the editor, and want to persist it?

**Comment by mikehardy** [comment]
Yes that is what I was thinking, but you said "We handle it correctly inside the card" which made me wonder if it was needed?

**Comment by david-allison-1** [comment]
Sorry for the imprecise language. We handle it such that it won't crash

https://github.com/ankidroid/Anki-Android/blob/0cb1d97ca9b5ca5ab5174629603655506f9ffad2/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L869-L875
