### ISSUE TITLE
Reviewer - confForDid - Attempt to invoke virtual method 'boolean org.json.JSONObject.has(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6702]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/572a1715-5ad4-4151-a792-01d6633c7569

2.12.0

```
java.lang.RuntimeException: Unable to resume activity {com.ichi2.anki/com.ichi2.anki.Reviewer}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.has(java.lang.String)' on a null object reference
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3828)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3860)
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:201)
at android.app.ActivityThread.main(ActivityThread.java:6810)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.has(java.lang.String)' on a null object reference
at com.ichi2.libanki.Decks.confForDid(Decks.java:2)
at com.ichi2.libanki.Card.timeLimit(Card.java:1)
at com.ichi2.libanki.Card.timeTaken(Card.java:2)
at com.ichi2.anki.AbstractFlashcardViewer.resumeTimer(AbstractFlashcardViewer.java:3)
at com.ichi2.anki.AbstractFlashcardViewer.onResume(AbstractFlashcardViewer.java:2)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
at android.app.Activity.performResume(Activity.java:7400)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3820)
... 11 more
```

**Comment by bejarane** [comment]
Having the same issue on Android app with an specific deck. Not sure what is making it to happen. I think those are the errors logged.

[1595451971] Syncer.java:sync(): client chunk,  {"done":true,"revlog":[],"cards":[],"notes":[]}
[1595451977] Collection.java:<init>(): /storage/2C67-15FC/AnkiDroid/collection.anki2,  2.12.1
[1595451977] Sched.java:_updateCutoff(): 662,  1595498400
[1595452331] Collection.java:<init>(): /storage/2C67-15FC/AnkiDroid/collection.anki2,  2.12.1
[1595452331] Sched.java:_updateCutoff(): 662,  1595498400

**Comment by david-allison-1** [comment]
@bejarane Thanks!!!

Would you be OK posting your `collection.anki2` publicly (you can upload it here as a `.zip`)

If not, could you email it to me: `gmail: davidallisongithub`

I'd love to get this one fixed.

**Comment by bejarane** [comment]
[collection.zip](https://github.com/ankidroid/Anki-Android/files/4962810/collection.zip)
Here is the collection zip, but I think it does not contains the faulty deck

**Comment by david-allison-1** [comment]
Thanks anyway, I'll take a look

If you can get something to reproduce the error (possibly on the desktop side), it'd be great.

**Comment by david-allison-1** [comment]
Nope - that did it

```
2020-07-22 22:58:15.073 17188-18224/com.ichi2.anki E/CollectionTask: doInBackgroundAnswerCard - RuntimeException on answering card
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.ichi2.utils.JSONArray com.ichi2.utils.JSONObject.getJSONArray(java.lang.String)' on a null object reference
        at com.ichi2.libanki.Models.fieldMap(Models.java:439)
        at com.ichi2.libanki.Note.load(Note.java:105)
        at com.ichi2.libanki.Note.<init>(Note.java:72)
        at com.ichi2.libanki.Note.<init>(Note.java:58)
        at com.ichi2.libanki.Collection.getNote(Collection.java:483)
        at com.ichi2.libanki.Card.note(Card.java:301)
        at com.ichi2.libanki.Card._getQA(Card.java:278)
        at com.ichi2.libanki.Card._getQA(Card.java:272)
        at com.ichi2.async.CollectionTask.doInBackgroundAnswerCard(CollectionTask.java:532)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:268)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:76)
        at android.os.AsyncTask$2.call(AsyncTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
```

**Comment by david-allison-1** [comment]
Nope - all seems OK (previously made a mistake importing)

**Comment by bejarane** [comment]
[collection.zip](https://github.com/ankidroid/Anki-Android/files/4962908/collection.zip)
my mistake. this is the faulty collection

**Comment by david-allison-1** [comment]
```
2020-07-22 23:09:13.650 19986-20078/com.ichi2.anki E/CollectionTask: doInBackgroundLoadDeckCounts - error
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.ichi2.utils.JSONObject com.ichi2.utils.JSONObject.put(java.lang.String, int)' on a null object reference
        at com.ichi2.libanki.Decks.confForDid(Decks.java:692)
        at com.ichi2.libanki.sched.SchedV2._deckNewLimitSingle(SchedV2.java:734)
        at com.ichi2.libanki.sched.Sched.deckDueList(Sched.java:225)
        at com.ichi2.libanki.sched.SchedV2.deckDueTree(SchedV2.java:444)
        at com.ichi2.async.CollectionTask.doInBackgroundLoadDeckCounts(CollectionTask.java:553)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:261)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:76)
        at android.os.AsyncTask$2.call(AsyncTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
```

**Comment by david-allison-1** [comment]
@bejarane Clicking "Check Database" should fix this in 2.12.X

Fix details: 4de7795 #6454 #6455

**Comment by bejarane** [comment]
Awesome. Thank you very much. I saw the "check database" working on the android app but never thought I had to do it on the desktop since that one was the faulty one.

**Comment by david-allison-1** [comment]
There's a problem "somewhere" which causes corrupted deck options, if you can reproduce it, please let us know!

Glad you got it sorted, happy reviewing!!

**Comment by bejarane** [comment]
My guess is that it is happening when creating new card fields with the computer app (Linux on my case). Before the error happened I was adding some new fields to my deck and filling them. If it happens again I will try to get some logs.
