### ISSUE TITLE
[2.12 ACRA] onFinishedStartup - NullPointerException - collection is null

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#6715]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/6c616278-ea2b-4160-a422-fe5837f37d74

Note: `deckPath` is `/storage/0403-0201/AnkiDroid`

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9, result=-1, data=null} to activity {com.ichi2.anki/com.ichi2.anki.DeckPicker}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.ichi2.libanki.Collection.getPath()' on a null object reference
at android.app.ActivityThread.deliverResults(ActivityThread.java:5324)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:5365)
at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8107)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.ichi2.libanki.Collection.getPath()' on a null object reference
at com.ichi2.anki.DeckPicker.onFinishedStartup(DeckPicker.java:1)
at com.ichi2.anki.DeckPicker.showStartupScreensAndDialogs(DeckPicker.java:72)
at com.ichi2.anki.DeckPicker.onActivityResult(DeckPicker.java:20)
at android.app.Activity.dispatchActivityResult(Activity.java:8294)
at android.app.ActivityThread.deliverResults(ActivityThread.java:5317)
... 11 more
```

**Comment by david-allison-1** [comment]
Heavily related to #7168

**Comment by dae** [comment]
Too old; closing until we get new reports.
