### ISSUE TITLE
Deck Import -Single Deck Export in Anki Desktop SchedV2 - Attempt to get length of null array

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6764]
https://drive.google.com/file/d/1xwwcF8qr8WPLpfHRblQtXZJBJMlrkEVq/view?usp=drivesdk

Reported in https://github.com/ankidroid/Anki-Android/issues/6383#issuecomment-665173746

```
2020-07-28 18:47:42.275 2127-2283/com.ichi2.anki E/Anki2Importer: _import() exception
    java.lang.NullPointerException: Attempt to get length of null array
        at com.ichi2.libanki.importer.Anki2Importer._importStaticMedia(Anki2Importer.java:698)
        at com.ichi2.libanki.importer.Anki2Importer._import(Anki2Importer.java:151)
        at com.ichi2.libanki.importer.Anki2Importer.run(Anki2Importer.java:103)
        at com.ichi2.libanki.importer.AnkiPackageImporter.run(AnkiPackageImporter.java:143)
        at com.ichi2.async.CollectionTask.doInBackgroundImportAdd(CollectionTask.java:1188)
        at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:393)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:304)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:83)
        at android.os.AsyncTask$2.call(AsyncTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
```

**Comment by david-allison-1** [comment]
https://github.com/ankidroid/Anki-Android/blob/c27f3907a6da9f6bf3dbe545a91a732ed5215352/AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java#L698

`new File(dir).listFiles()` is null

`dir` is `/storage/emulated/0/AnkiDroidAAA/tmpzip/collection.anki21`

**Comment by david-allison-1** [comment]
Reproduced at revision c629dce45e20e68cf0ee1331ca647c9a5b4252a1

**Comment by david-allison-1** [comment]
Dir should be `/storage/emulated/0/AnkiDroidAAA/tmpzip/collection.media`

The line is:

https://github.com/ankidroid/Anki-Android/blob/fdadd0f6ef21863c7d8318e089b3d92320cc84d6/AnkiDroid/src/main/java/com/ichi2/libanki/Media.java#L127

But, Anki 2.1.15 doesn't seem to perform the fix, yet it works.

https://github.com/ankitects/anki/blob/2.1.15/anki/media.py#L38

**Comment by david-allison-1** [comment]
Looks like: https://github.com/ankitects/anki/commit/b9280ca31e14336411cdf6269f8db97f18582d1d
