### ISSUE TITLE
Crash on import of large file

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#6852]
###### Reproduction Steps

1. Import a large file (how large? Larger than space available to import)
2. Crash
3. 

###### Expected Result

Import succeeded or at least a friendly error message

###### Actual Result

I believe this is crashing in 2.12.1 based on a play store review

I thought we handled most of these so they did not percolate but apparently not? Stated another way I believed these were non-fatal even if we got an exception report but it does not seem to be the case

Also I thought we were checking before import for some multiple of space required, but also apparently not :-/

```

08-08 15:33:20.127 E/AnkiDroid(23824): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691)
--
1 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at android.os.Handler.dispatchMessage(Handler.java:102)
2 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at android.os.Looper.loop(Looper.java:154)
3 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at android.app.ActivityThread.main(ActivityThread.java:6692)
4 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at java.lang.reflect.Method.invoke(Native Method)
5 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
6 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
7 | 08-08 15:33:20.127 E/AnkiDroid(23824): Caused by: android.system.ErrnoException: write failed: ENOSPC (No space left on device)
8 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at libcore.io.Posix.writeBytes(Native Method)
9 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at libcore.io.Posix.write(Posix.java:273)
10 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:319)
11 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at libcore.io.IoBridge.write(IoBridge.java:496)
12 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	... 20 more
13 | 08-08 15:33:20.127 E/AnkiDroid(23824):
14 | 08-08 15:33:20.127 E/AnkiDroid(23824): java.io.IOException: write failed: ENOSPC (No space left on device)
15 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at libcore.io.IoBridge.write(IoBridge.java:501)
16 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at java.io.FileOutputStream.write(FileOutputStream.java:316)
17 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at com.ichi2.compat.CompatV16.copyFile(CompatV16.java:23)
18 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at com.ichi2.compat.CompatV16.copyFile(CompatV16.java:16)
19 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at com.ichi2.utils.ImportUtils$FileImporter.copyFileToCache(ImportUtils.java:2)
20 | 08-08  15:33:20.127 E/AnkiDroid(23824): 	at  com.ichi2.utils.ImportUtils$FileImporter.handleContentProviderFile(ImportUtils.java:13)
21 | 08-08  15:33:20.127 E/AnkiDroid(23824): 	at  com.ichi2.utils.ImportUtils$FileImporter.handleFileImportInternal(ImportUtils.java:10)
22 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at com.ichi2.utils.ImportUtils$FileImporter.handleFileImport(ImportUtils.java:4)
23 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at com.ichi2.utils.ImportUtils.handleFileImport(ImportUtils.java:1)
24 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at com.ichi2.anki.DeckPicker.onActivityResult(DeckPicker.java:15)
25 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at android.app.Activity.dispatchActivityResult(Activity.java:7226)
26 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4477)
27 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4524)
28 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at android.app.ActivityThread.-wrap22(ActivityThread.java)
29 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691)
30 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at android.os.Handler.dispatchMessage(Handler.java:102)
31 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at android.os.Looper.loop(Looper.java:154)
32 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at android.app.ActivityThread.main(ActivityThread.java:6692)
33 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at java.lang.reflect.Method.invoke(Native Method)
34 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
35 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
36 | 08-08 15:33:20.127 E/AnkiDroid(23824): Caused by: android.system.ErrnoException: write failed: ENOSPC (No space left on device)
37 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at libcore.io.Posix.writeBytes(Native Method)
38 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at libcore.io.Posix.write(Posix.java:273)
39 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:319)
40 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	at libcore.io.IoBridge.write(IoBridge.java:496)
41 | 08-08 15:33:20.127 E/AnkiDroid(23824): 	... 20 more
42 | 08-08  15:33:20.135 E/AnkiDroid(23824): ImportUtils$FileImporter/ Could not  copy file to /data/user/0/com.ichi2.anki/cache/anking.colpkg
43 | 08-08 15:33:20.135 E/AnkiDroid(23824): java.io.IOException: write failed: ENOSPC (No space left on device)
44 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at libcore.io.IoBridge.write(IoBridge.java:501)
45 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at java.io.FileOutputStream.write(FileOutputStream.java:316)
46 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at com.ichi2.compat.CompatV16.copyFile(CompatV16.java:23)
47 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at com.ichi2.compat.CompatV16.copyFile(CompatV16.java:16)
48 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at com.ichi2.utils.ImportUtils$FileImporter.copyFileToCache(ImportUtils.java:2)
49 | 08-08  15:33:20.135 E/AnkiDroid(23824): 	at  com.ichi2.utils.ImportUtils$FileImporter.handleContentProviderFile(ImportUtils.java:13)
50 | 08-08  15:33:20.135 E/AnkiDroid(23824): 	at  com.ichi2.utils.ImportUtils$FileImporter.handleFileImportInternal(ImportUtils.java:10)
51 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at com.ichi2.utils.ImportUtils$FileImporter.handleFileImport(ImportUtils.java:4)
52 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at com.ichi2.utils.ImportUtils.handleFileImport(ImportUtils.java:1)
53 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at com.ichi2.anki.DeckPicker.onActivityResult(DeckPicker.java:15)
54 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at android.app.Activity.dispatchActivityResult(Activity.java:7226)
55 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4477)
56 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4524)
57 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at android.app.ActivityThread.-wrap22(ActivityThread.java)
58 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691)
59 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at android.os.Handler.dispatchMessage(Handler.java:102)
60 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at android.os.Looper.loop(Looper.java:154)
61 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at android.app.ActivityThread.main(ActivityThread.java:6692)
62 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at java.lang.reflect.Method.invoke(Native Method)
63 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
64 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
65 | 08-08 15:33:20.135 E/AnkiDroid(23824): Caused by: android.system.ErrnoException: write failed: ENOSPC (No space left on device)
66 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at libcore.io.Posix.writeBytes(Native Method)
67 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at libcore.io.Posix.write(Posix.java:273)
68 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:319)
69 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at libcore.io.IoBridge.write(IoBridge.java:496)
70 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	... 20 more
71 | 08-08 15:33:20.135 E/AnkiDroid(23824):
72 | 08-08 15:33:20.135 E/AnkiDroid(23824): java.io.IOException: write failed: ENOSPC (No space left on device)
73 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at libcore.io.IoBridge.write(IoBridge.java:501)
74 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at java.io.FileOutputStream.write(FileOutputStream.java:316)
75 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at com.ichi2.compat.CompatV16.copyFile(CompatV16.java:23)
76 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at com.ichi2.compat.CompatV16.copyFile(CompatV16.java:16)
77 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at com.ichi2.utils.ImportUtils$FileImporter.copyFileToCache(ImportUtils.java:2)
78 | 08-08  15:33:20.135 E/AnkiDroid(23824): 	at  com.ichi2.utils.ImportUtils$FileImporter.handleContentProviderFile(ImportUtils.java:13)
79 | 08-08  15:33:20.135 E/AnkiDroid(23824): 	at  com.ichi2.utils.ImportUtils$FileImporter.handleFileImportInternal(ImportUtils.java:10)
80 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at com.ichi2.utils.ImportUtils$FileImporter.handleFileImport(ImportUtils.java:4)
81 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at com.ichi2.utils.ImportUtils.handleFileImport(ImportUtils.java:1)
82 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at com.ichi2.anki.DeckPicker.onActivityResult(DeckPicker.java:15)
83 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at android.app.Activity.dispatchActivityResult(Activity.java:7226)
84 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4477)
85 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4524)
86 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at android.app.ActivityThread.-wrap22(ActivityThread.java)
87 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691)
88 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at android.os.Handler.dispatchMessage(Handler.java:102)
89 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at android.os.Looper.loop(Looper.java:154)
90 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at android.app.ActivityThread.main(ActivityThread.java:6692)
91 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at java.lang.reflect.Method.invoke(Native Method)
92 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
93 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
94 | 08-08 15:33:20.135 E/AnkiDroid(23824): Caused by: android.system.ErrnoException: write failed: ENOSPC (No space left on device)
95 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at libcore.io.Posix.writeBytes(Native Method)
96 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at libcore.io.Posix.write(Posix.java:273)
97 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:319)
98 | 08-08 15:33:20.135 E/AnkiDroid(23824): 	at libcore.io.IoBridge.write(IoBridge.java:496)


```

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
ACRA link?

**Comment by mikehardy** [comment]
There were a few all the same but it was Android 7 and 8, they are actually fairly easy to find in current stacks of 2.12.1, the top frame that shows in the listing is import failure, I'd be surprised if it was a FAT32 limit

**Comment by Birukzex** [comment]
Here is my installation ID

AnkiDroid Version = 2.12.1

Android Version = 7.0

ACRA UUID = 84b44dde-ad78-440e-9cea-7e283780a02c

**Comment by david-allison-1** [comment]
Link: https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/dcc8d7d3-ff8c-4287-ad2a-e9ca3d555427
