### ISSUE TITLE
Flaky test from 'Upstream Test' PR

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#6867]
###### Reproduction Steps

1. Run CI, a lot
2. At least once you'll see a test failure
3. 

###### Expected Result

Clean reproducible CI

###### Actual Result

Apparently some of the tests can flake, but it's rare! Took about a week for one of these to come out. So it's almost theoretical, but it can happen

```
com.ichi2.libanki.UndoTest > test_review FAILED

    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.

        at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:470)

        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:548)

        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)

        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)

        at java.util.concurrent.FutureTask.run(FutureTask.java:266)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

        at java.lang.Thread.run(Thread.java:748)

        Caused by:

        arrays first differed at element [1]; expected:<1> but was:<0>

            at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:78)

            at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:28)

            at org.junit.Assert.internalArrayEquals(Assert.java:534)

            at org.junit.Assert.assertArrayEquals(Assert.java:418)

            at org.junit.Assert.assertArrayEquals(Assert.java:429)

            at com.ichi2.libanki.UndoTest.test_review(UndoTest.java:91)

            Caused by:

            java.lang.AssertionError: expected:<1> but was:<0>

                at org.junit.Assert.fail(Assert.java:89)

                at org.junit.Assert.failNotEquals(Assert.java:835)

                at org.junit.Assert.assertEquals(Assert.java:120)

                at org.junit.Assert.assertEquals(Assert.java:146)

                at org.junit.internal.ExactComparisonCriteria.assertElementsEqual(ExactComparisonCriteria.java:8)

                at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:76)

                ... 5 more

com.ichi2.libanki.sched.SchedTest > test_repCountsV1 FAILED

    arrays first differed at element [1]; expected:<2> but was:<1>

        at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:78)

        at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:28)

        at org.junit.Assert.internalArrayEquals(Assert.java:534)

        at org.junit.Assert.assertArrayEquals(Assert.java:418)

        at org.junit.Assert.assertArrayEquals(Assert.java:429)

        at com.ichi2.libanki.sched.SchedTest.test_repCountsV1(SchedTest.java:1097)

        Caused by:

        java.lang.AssertionError: expected:<2> but was:<1>

            at org.junit.Assert.fail(Assert.java:89)

            at org.junit.Assert.failNotEquals(Assert.java:835)

            at org.junit.Assert.assertEquals(Assert.java:120)

            at org.junit.Assert.assertEquals(Assert.java:146)

            at org.junit.internal.ExactComparisonCriteria.assertElementsEqual(ExactComparisonCriteria.java:8)

            at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:76)

            ... 5 more

com.ichi2.libanki.sched.SchedTest > test_suspendV1 FAILED

    java.lang.AssertionError

        at org.junit.Assert.fail(Assert.java:87)

        at org.junit.Assert.assertTrue(Assert.java:42)

        at org.junit.Assert.assertTrue(Assert.java:53)

        at com.ichi2.libanki.sched.SchedTest.test_suspendV1(SchedTest.java:754)

com.ichi2.libanki.sched.SchedTest > test_learnV1 FAILED

    java.lang.AssertionError: expected:<3> but was:<2>

        at org.junit.Assert.fail(Assert.java:89)

        at org.junit.Assert.failNotEquals(Assert.java:835)

        at org.junit.Assert.assertEquals(Assert.java:647)

        at org.junit.Assert.assertEquals(Assert.java:633)

        at com.ichi2.libanki.sched.SchedTest.test_learnV1(SchedTest.java:320)

com.ichi2.libanki.sched.SchedTest > test_cram FAILED

    java.lang.AssertionError: expected:<1> but was:<3>

        at org.junit.Assert.fail(Assert.java:89)

        at org.junit.Assert.failNotEquals(Assert.java:835)

        at org.junit.Assert.assertEquals(Assert.java:647)

        at org.junit.Assert.assertEquals(Assert.java:633)

        at com.ichi2.libanki.sched.SchedTest.test_cram(SchedTest.java:823)

com.ichi2.libanki.sched.SchedTest > test_learn_collapsedV1 FAILED

    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.

        at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:470)

        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:548)

        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)

        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)

        at java.util.concurrent.FutureTask.run(FutureTask.java:266)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

        at java.lang.Thread.run(Thread.java:748)

        Caused by:

        java.lang.AssertionError

            at org.junit.Assert.fail(Assert.java:87)

            at org.junit.Assert.assertTrue(Assert.java:42)

            at org.junit.Assert.assertFalse(Assert.java:65)

            at org.junit.Assert.assertFalse(Assert.java:75)

            at com.ichi2.libanki.sched.SchedTest.test_learn_collapsedV1(SchedTest.java:405)

com.ichi2.libanki.sched.SchedTest > test_learn_dayV1 FAILED

    arrays first differed at element [1]; expected:<1> but was:<0>

        at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:78)

        at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:28)

        at org.junit.Assert.internalArrayEquals(Assert.java:534)

        at org.junit.Assert.assertArrayEquals(Assert.java:418)

        at org.junit.Assert.assertArrayEquals(Assert.java:429)

        at com.ichi2.libanki.sched.SchedTest.test_learn_dayV1(SchedTest.java:426)

        Caused by:

        java.lang.AssertionError: expected:<1> but was:<0>

            at org.junit.Assert.fail(Assert.java:89)

            at org.junit.Assert.failNotEquals(Assert.java:835)

            at org.junit.Assert.assertEquals(Assert.java:120)

            at org.junit.Assert.assertEquals(Assert.java:146)

            at org.junit.internal.ExactComparisonCriteria.assertElementsEqual(ExactComparisonCriteria.java:8)

            at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:76)

            ... 5 more

com.ichi2.libanki.sched.SchedTest > test_overdue_lapseV1 SKIPPED

com.ichi2.libanki.sched.SchedTest > test_cram_rem FAILED

    java.lang.AssertionError: expected:<1> but was:<3>

        at org.junit.Assert.fail(Assert.java:89)

        at org.junit.Assert.failNotEquals(Assert.java:835)

        at org.junit.Assert.assertEquals(Assert.java:647)

        at org.junit.Assert.assertEquals(Assert.java:633)

        at com.ichi2.libanki.sched.SchedTest.test_cram_rem(SchedTest.java:902)

com.ichi2.libanki.sched.SchedTest > test_counts_idxV1 FAILED

    arrays first differed at element [1]; expected:<2> but was:<1>

        at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:78)

        at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:28)

        at org.junit.Assert.internalArrayEquals(Assert.java:534)

        at org.junit.Assert.assertArrayEquals(Assert.java:418)

        at org.junit.Assert.assertArrayEquals(Assert.java:429)

        at com.ichi2.libanki.sched.SchedTest.test_counts_idxV1(SchedTest.java:1076)

        Caused by:

        java.lang.AssertionError: expected:<2> but was:<1>

            at org.junit.Assert.fail(Assert.java:89)

            at org.junit.Assert.failNotEquals(Assert.java:835)

            at org.junit.Assert.assertEquals(Assert.java:120)

            at org.junit.Assert.assertEquals(Assert.java:146)

            at org.junit.internal.ExactComparisonCriteria.assertElementsEqual(ExactComparisonCriteria.java:8)

            at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:76)

            ... 5 more
```

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Do you have a link, or time of failure? Hypothesis would be that the SchedV1 tests can also be flaky due to time dependencies, but this wasn't detected upstream

**Comment by mikehardy** [comment]
Hmmm - I erased the history by re-running that failed build. Dang. Fishing details out of the email notification:

```
X-Received: by 2002:a25:db49:: with SMTP id g70mr32858083ybf.155.1597032104427;
        Sun, 09 Aug 2020 21:01:44 -0700 (PDT)
Received: from [35.196.58.112] by mandrillapp.com id 4290c5a4ccf1450f9ff3718f407be656; Mon, 10 Aug 2020 04:01:43 +0000
Date: Mon, 10 Aug 2020 04:01:43 +0000

Build Update for ankidroid/Anki-Android
-------------------------------------

Build: #8448
Status: Failed

Duration: 14 mins and 56 secs
Commit: d3edeb3 (v2.13alpha13)
Author: Mike Hardy
Message: Bumped version to 2.13alpha13
@branch-specific

View the changeset: https://github.com/ankidroid/Anki-Android/compare/v2.13alpha13

View the full build log and details: https://travis-ci.org/github/ankidroid/Anki-Android/builds/716421573?utm_medium=notification&utm_source=email
```

I'm not sure what the default day cutoff is, but this happened at the times indicated above
