### ISSUE TITLE
2.12alpha16/17 crash in test lab pre-launch report

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#6923]
```
FATAL EXCEPTION: main
Process: com.ichi2.anki, PID: 31772
java.lang.RuntimeException: Unable to pause activity {com.ichi2.anki/com.ichi2.anki.NoteEditor}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4124)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4556)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4621)
	at android.app.ActivityThread.-wrap5(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:2)
	at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1)
	at androidx.fragment.app.FragmentManagerImpl.popBackStack(FragmentManagerImpl.java:2)
	at com.ichi2.anki.AnkiActivity.dismissAllDialogFragments(AnkiActivity.java:1)
	at com.ichi2.anki.NoteEditor.onPause(NoteEditor.java:1)
	at android.app.Activity.performPause(Activity.java:7391)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1414)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnPause(MonitoringInstrumentation.java:17)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4113)
	... 10 more
```

Device logcat - [logcat.txt](https://github.com/ankidroid/Anki-Android/files/5099833/logcat.txt)

Device screen recording - https://youtu.be/XrEPQDy395c

**Comment by mikehardy** [comment]
No idea what's happening here and I don't have time to triage it right now but we went from 0 crashes in the test lab on 2.12alpha15 to just about every device blowing up here, so it's important enough I ferried the info into an issue...

**Comment by david-allison-1** [comment]
Note editor crashes when preview is selected. I'll take this on tomorrow.

**Comment by david-allison-1** [comment]
Cause: https://github.com/ankidroid/Anki-Android/commit/8c51f74dbbe138e3c2f2d0e7cda08262035739ba#diff-dae57b84b54c26dfe59f24aa91d21e45

Also requires a regression test for the interaction

**Comment by mikehardy** [comment]
Thank you for checking this out! I appreciate it. I'll still kick an alpha out tonight since a new alpha won't be a regression, we already have some change queued up and I'm testing the new auto-alpha-publisher github action

**Comment by david-allison-1** [comment]
Cause: we call `onSaveInstanceState` outside of the normal lifecycle.

https://github.com/ankidroid/Anki-Android/blob/8c51f74dbbe138e3c2f2d0e7cda08262035739ba/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java#L1001-L1014

**Comment by mikehardy** [comment]
Oh yuck, I'm sorry about that. I was just attempting to re-use Bundle persistence machinery there, and crashed you with the side effect. Dang
