### ISSUE TITLE
2.12.1 - Scheduler behavior differs from Anki Desktop - bury related cards

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6967]
* Have 1 note with 3 related cards steps: (1, 10, 60, 720)
* Enable Bury Related Cards
* 3 0 0
* Review

AnkiDroid 2.12.1 : (0 2 0)

Anki Desktop 2.1.30 : (2 2 0)

This leads to unexpected undo behavior, as AnkiDroid's undo will add the 2 back at the wrong instant.

https://github.com/david-allison-1/Anki-Android/commit/07c1063c7f449538d68a93c86b3afa91ac61f4c5

----

```
java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.

	at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:470)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:548)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: 
Expected: is "[2, 2, 0]"
     but: was "[0, 2, 0]"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at com.ichi2.anki.ReviewerTest.assertCounts(ReviewerTest.java:197)
	at com.ichi2.anki.ReviewerTest.testBuryRelatedCardsUndo(ReviewerTest.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	... 6 more


```

```
java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.

	at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:470)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:548)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: 
Expected: is "[2, 2, 0]"
     but: was "[0, 2, 0]"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at com.ichi2.anki.ReviewerTest.assertCounts(ReviewerTest.java:197)
	at com.ichi2.anki.ReviewerTest.testBuryRelatedCardsNoUndo(ReviewerTest.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	... 6 more


```

More assertions should be made after this - we already deviate from Anki Desktop and I deemed it not to be worth the effort to add additional test cases

**Comment by Arthur-Milchior** [comment]
Probably not relevant to compare to anki 2.1.30 since ankidroid follow an older version of the code base. If you compare to 2.1.15 where there was no rust, you get same behaviour as ankidroid here
By the way, @dae, did you know that there was a difference introduced in anki at some point in time. There is no new time, but the count of new card does not go to 0.

@david-allison-1 do you want us to port rust change into ankidroid ? Because otherwise, this should not be considered a bug.

**Comment by Arthur-Milchior** [comment]
I can't figure out how to get a wrong undo while running your version of the code on https://github.com/david-allison-1/Anki-Android/commit/07c1063c7f449538d68a93c86b3afa91ac61f4c5

**Comment by david-allison-1** [comment]
All I care about with this is capturing and diagnosing the scheduling regressions that have been reported in 2.12.x. 

We'll be moving to the rust codebase, but for now we need to ensure that any regressions in our code are removed so we can confidently release 2.13.x

**Comment by Arthur-Milchior** [comment]
I also care very much about finding and correcting the regressions. I just don't see how to do it when the test does not actually cover regressions. This is why I explain that actually I believe they are not and more search is needed.

In `testBuryRelatedCardsUndo`, `testBuryRelatedCardsNoUndo` the assertions are incorrect. You're comparing to a version of anki which is not the one we copied in AnkiDroid. The behavior changed in anki, but it's not a regression that 
we kept the old behavior. I also want to correct the regression if I can find them, and I'm still looking at your other commit.  


In `testBuryRelatedCardsUndoMultiStep` I see `assumeThat("Unknown what assertions to make", false, is(true));` so I assume it's expected to fail at this point. 

`jsTime4ShouldBeBlankIfButtonUnavailable` also fails, it leads to `Caused by: java.lang.ClassNotFoundException: org.bitbucket.cowwoc.diffmatchpatch.DiffMatchPatch` which does not seems related to the kind of regression we are looking for.

**Comment by david-allison-1** [comment]
Sure, let's shelve this for a couple versions then.

**Comment by Arthur-Milchior** [comment]
I'd state to at least wait for Damien's feedback, because it seems you found a regression in upstream. If it's the case, would be a shame to port it

**Comment by dae** [comment]
I'm guessing it's the result of using deck_due_tree() for the scheduler counts. I wouldn't worry about matching the behaviour for the sake of matching the behaviour, as the queue building code is due for a rewrite soon anyway.
