### ISSUE TITLE
CardBrowser - CardCache: Crash attempting to get sfld of missing note

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6970]
```
android.database.SQLException: No result for query: SELECT sfld FROM notes WHERE id = ?
at com.ichi2.libanki.DB.queryString(DB.java:5)
at com.ichi2.libanki.Note.getSFld(Note.java:1)
at com.ichi2.anki.CardBrowser$CardCache.getColumnHeaderText(CardBrowser.java:23)
at com.ichi2.anki.CardBrowser$MultiColumnListAdapter.bindView(CardBrowser.java:6)
at com.ichi2.anki.CardBrowser$MultiColumnListAdapter.getView(CardBrowser.java:6)
at android.widget.AbsListView.obtainView(AbsListView.java:3271)
at android.widget.ListView.makeAndAddView(ListView.java:2238)
at android.widget.ListView.fillDown(ListView.java:838)
at android.widget.ListView.fillSpecific(ListView.java:1551)
at android.widget.ListView.layoutChildren(ListView.java:1936)
at android.widget.AbsListView.onLayout(AbsListView.java:3041)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:18)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:7)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:8)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:10)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at com.android.internal.policy.DecorView.onLayout(DecorView.java:1062)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3679)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3139)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2200)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9065)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
at android.view.Choreographer.doCallbacks(Choreographer.java:797)
at android.view.Choreographer.doFrame(Choreographer.java:732)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8016)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
```

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/24a517b0-effa-495c-b447-3f908fd624a5

**Comment by Arthur-Milchior** [comment]
Seems @mikehardy was more right than I expected in https://github.com/ankidroid/Anki-Android/pull/6611#issuecomment-653815157

**Comment by david-allison-1** [comment]
@Arthur-Milchior Still in 2.13.0 https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/4360db95-6ad2-42e8-83d3-f35801689f8f

**Comment by Arthur-Milchior** [comment]
There is no Timber for this user ?
I don't see how it is possible unless they used CardContentProvider.

The only solution I can imagine here would be to restart the search if some card or note disappeared.

**Comment by david-allison-1** [comment]
Some phones don't provide logs :/
