### ISSUE TITLE
[2.13alpha25] Card Browser does not refresh after edit/crashes

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7017]
###### Reproduction Steps

1. Card Browser with Deck selected, no search
2. Select a card
3. Press "Back" button on device

###### Expected Result

4. Results are shown

###### Actual Result

4. No results are shown

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Crash:

* Preview
* Back
* Tap the card list

```
2020-09-03 04:42:58.338 31317-31317/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 31317
    java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131296440, class android.widget.ListView) with Adapter(class com.ichi2.anki.CardBrowser$MultiColumnListAdapter)]
        at android.widget.ListView.layoutChildren(ListView.java:1723)
        at android.widget.AbsListView.onTouchUp(AbsListView.java:4188)
        at android.widget.AbsListView.onTouchUpEx(AbsListView.java:4143)
        at android.widget.HwAbsListView.onTouchUpEx(HwAbsListView.java:554)
        at android.widget.AbsListView.onTouchEvent(AbsListView.java:3948)
        at android.view.View.dispatchTouchEvent(View.java:12628)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3035)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2714)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:565)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1929)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3594)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:514)
        at android.view.View.dispatchPointerEvent(View.java:12873)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5771)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5535)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5036)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5002)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5157)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5010)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5214)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5036)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5002)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5010)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7803)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7768)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7726)
2020-09-03 04:42:58.339 31317-31317/com.ichi2.anki E/AndroidRuntime:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8007)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:202)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:386)
        at android.os.Looper.loop(Looper.java:175)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
2020-09-03 04:43:00.400 31704-31725/com.ichi2.anki E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
```

**Comment by mikehardy** [comment]
This was recent https://github.com/ankidroid/Anki-Android/pull/7004

**Comment by david-allison-1** [comment]
@Arthur-Milchior Want me to take this one on?

**Comment by Arthur-Milchior** [comment]
I can take it this week end. But if you need it sooner and it's not hard, go. Otherwise I'll clean my own mess

**Comment by david-allison-1** [comment]
I was planning to do it over the weekend - will leave it then, but feel free to throw it back to me

**Comment by Arthur-Milchior** [comment]
I don't understand how you get the crash in the second message. If the list is empty, it seems impossible to click in it

**Comment by Arthur-Milchior** [comment]
This was already solved in https://github.com/ankidroid/Anki-Android/pull/6611 , which ensure that list is invalidated/not computed on destroy, but onStop keep all list processing which may still be useful

**Comment by david-allison-1** [comment]
> I don't understand how you get the crash in the second message. If the list is empty, it seems impossible to click in it

Sometimes the list is not empty, clicking crashes it.

**Comment by Arthur-Milchior** [comment]
Do you have any idea how to reproduce it ? I fear I don't know list view well enough to understand what it means here... And I have no idea whether this is also solved

**Comment by david-allison-1** [comment]
@Arthur-Milchior Seems to be fixed as well - I can't repro after the change has gone in
