### ISSUE TITLE
Export fails if missing media

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7023]
###### Reproduction Steps

1. Add an image to a note
2. Delete from `collection.media`
3. Export Deck

###### Expected Result

4. Export occurs, with warning that some files could not be found

###### Actual Result

4. Export fails with "Error exporting apkg file"

###### Debug info

```
2020-09-04 07:33:06.222 23541-23852/com.ichi2.anki E/CollectionTask: FileNotFoundException in doInBackgroundExportApkg
    java.io.FileNotFoundException: /storage/emulated/0/AnkiDroidThree/collection.media/img_202009021920498931922221469823880.jpg (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:231)
        at java.io.FileInputStream.<init>(FileInputStream.java:165)
        at java.io.FileInputStream.<init>(FileInputStream.java:112)
        at com.ichi2.libanki.ZipFile.write(AnkiPackageExporter.java:467)
        at com.ichi2.libanki.AnkiPackageExporter._exportMedia(AnkiPackageExporter.java:388)
        at com.ichi2.libanki.AnkiPackageExporter._exportMedia(AnkiPackageExporter.java:380)
        at com.ichi2.libanki.AnkiPackageExporter.exportFiltered(AnkiPackageExporter.java:408)
        at com.ichi2.libanki.AnkiPackageExporter.exportInto(AnkiPackageExporter.java:340)
        at com.ichi2.async.CollectionTask.doInBackgroundExportApkg(CollectionTask.java:1535)
        at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:403)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:308)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:89)
        at android.os.AsyncTask$2.call(AsyncTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
```

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Cause: 

https://github.com/ankidroid/Anki-Android/blob/711b2be380d95400ff194f05362cd9111cc3312f/src/com/ichi2/libanki/AnkiPackageExporter.java#L302-L316

was changed to 

https://github.com/ankidroid/Anki-Android/blob/4b6d202ebeff322e4eaae0bc365dd88317dfe572/AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java#L387-L394

I question the original logic, as that seemed to add an entry even if the media was not found.

**Comment by david-allison-1** [comment]
Confirmed: no file or entry in media if a file is missing.
