### ISSUE TITLE
sCursorWindowSize not found in emulator

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#7031]
I got no error on master when I opened the "phone.zip" version.
When I tried to opened the other file, I got an error which is worrysome but seems unrelated

```
W/Collection: Unable to get window size from requery cursor.
    java.lang.NoSuchFieldException: No field sCursorWindowSize in class Lio/requery/android/database/CursorWindow; (declaration of 'io.requery.android.database.CursorWindow' appears in /data/app/com.ichi2.anki-Iwraig6P2ye9T686I-zoUA==/base.apk)
        at java.lang.Class.getDeclaredField(Native Method)
        at com.ichi2.libanki.Collection.getChunk(Collection.java:313)
        at com.ichi2.libanki.Collection.loadColumn(Collection.java:332)
        at com.ichi2.libanki.Collection.load(Collection.java:289)
        at com.ichi2.libanki.Collection.<init>(Collection.java:187)
        at com.ichi2.libanki.Storage.Collection(Storage.java:68)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:122)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:106)
        at com.ichi2.anki.services.BootService.getColSafe(BootService.java:87)
        at com.ichi2.anki.services.BootService.onReceive(BootService.java:50)
        at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:274)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

_Originally posted by @Arthur-Milchior in https://github.com/ankidroid/Anki-Android/issues/6383#issuecomment-687906437_

**Comment by david-allison-1** [comment]
Also getting this as a warning in Timber on my Android, have been getting it for some time - presumed it was normal as the exception was caught. 

Just looked into it.

`android.database.CursorWindow` contains `sCursorWindowSize`, but this is initialized to -1, which isn't checked for in the above code.

`io.requery.android.database.CursorWindow` contains `sDefaultCursorWindowSize`.

**Comment by mikehardy** [comment]
I could have sworn I personally saw this one work before, but we wouldn't be getting stacks if it wasn't wrong somehow. I can look at this one, I perversely like the database infra stuff
