### ISSUE TITLE
[2.13alpha28] Card Template Editor Preview Crash: sched.counts - ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7039]
* SchedV1, new profile
* Add a new Basic Note
* Bury Card
* Card Browser - Edit Note - Edit Card Template - Preview

Crash:

```
 FATAL EXCEPTION: Thread-6
Process: com.ichi2.anki, PID: 19157
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.CardTemplatePreviewer}: java.lang.ArrayIndexOutOfBoundsException: length=3; index=-2
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:31)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:130)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:124)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:40)
	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:68)
	at androidx.test.espresso.action.Tap.a(Tap.java:13)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:2)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:9)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:6)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:140)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:4)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=3; index=-2
	at com.ichi2.libanki.sched.Sched.counts(Sched.java:142)
	at com.ichi2.anki.AbstractFlashcardViewer.updateScreenCounts(AbstractFlashcardViewer.java:1879)
	at com.ichi2.anki.AbstractFlashcardViewer.updateForNewCard(AbstractFlashcardViewer.java:1863)
	at com.ichi2.anki.AbstractFlashcardViewer.fillFlashcard(AbstractFlashcardViewer.java:2397)
	at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:2264)
	at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:2034)
	at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1996)
	at com.ichi2.anki.CardTemplatePreviewer.displayCardQuestion(CardTemplatePreviewer.java:157)
	at com.ichi2.anki.CardTemplatePreviewer.onCollectionLoaded(CardTemplatePreviewer.java:246)
	at com.ichi2.anki.AnkiActivity.startLoadingCollection(AnkiActivity.java:325)
	at com.ichi2.anki.CardTemplatePreviewer.onCreate(CardTemplatePreviewer.java:91)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:13)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	... 25 more
```

**Comment by Arthur-Milchior** [comment]
One more reason to state the current way we count cards makes no sens at all...

When you do a review, the counts saved in the scheduler does not count the card in the reviewer. This means that the reviewer need to send back the current card to the scheduler so that it increments the correct counter. This works only because it assumes that the card sent to the scheduler belong to one of the three queue. If the card is in burying/suspended queue, the method `counts(Card card)` fails as there is no queue to increment. 
If you accept it, I'd love to change it so that `counts()` returns the actual number of card the user has to review, the actual number that is displayed to the user. This will reduce the useless complexity of this method and simplify the code.
The trouble is that it would lead us to being further away from upstream.


This is even more non-sensical, because in the previewer, we don't even display counts to the user. So the obvious solution is simply to stop requiring this number. I guess that updateScreenCounts should be in Reviewer and not in AbstractFlashCard, since we don't need it in the Previewer. I should note that `counts()` takes time because it needs to actually do some computation if it does not have the value saved since the last reset. So removing a call to `counts()` will also save time.

Related: when you preview a card, you will see some ETA. This makes no sens here, we should also hide it.

**Comment by Arthur-Milchior** [comment]
One thing I did not take into account: what to send to javascript when they request access to the numbers and we are previewing ? I'd suggest returning `null` so that it's clear it's not a value that is expected to be used; but js may not expect it

**Comment by david-allison-1** [comment]
@infinyte7 Any opinion on the above?

**Comment by Arthur-Milchior** [comment]
Currently, https://github.com/ankidroid/Anki-Android/pull/7040 returns 0 and empty string. Less risk of JS crash. That can be easily changed to either returning null, or returning a ressource string which state something such as "NB of new card" (Probably not a wise idea, since this string will be quite longer than what JS expects)

**Comment by infinyte7** [comment]
The card counts is used to show the progress bar in webview. If that counts removed then what will be alternative for getting card counts?

**Comment by Arthur-Milchior** [comment]
@infinyte7 what is "card counts" in previewer ? If you are creating a new card, or editing a card from the browser, it seems there exists nothing that makes sens and can be called a "card counts". However, the user may still want to preview the card and see how it will be displayed in the reviewer later.

This means that there is no "alternative for getting card counts", because there is no "card counts". Or I misunderstood what "card counts" is, in which case I need you to explain what you want, so that we can allow access to it

**Comment by mikehardy** [comment]
In my experience with react-native-device-info, it is best to define "valid" but known "undefined" values for those situations. What worked well for me and the similarly sized library consumer community there was -1 for undefined numbers, "unknown" for undefined strings, false for booleans, and the empty list/array for those. The bar to entry for JS API consumers will be similarly low - we *want* novices to use the API - and this leads to safe / non-crashing results for everyone, while checking for those values is as simple as a null/undefined.

That's a tangent point, but I feel pretty strongly about it based on my experience. I hate null and undefined values and do not want to propagate them in new APIs.

**Comment by Arthur-Milchior** [comment]
This lead to an interesting question. Should we localize `"undefined"` ?
On the one hand, users may see it if JS does not deal with it. On the other hand, JS will be quite harder to write if they must test for localized version of the word to check if the value is valid.

I force pushed a version with localized "Undefine".
I believe I'd prefer to see crash, so that it's clear something is wrong/unexpected, instead of showing values which seems to make sens but actually not. I would expect that it's nice to novice if they get a clear sign that something is breaking instead of trying to have them guess why suddenly we tell them -1 seconds remains in reviewing.

But I don't currently plan to use this feature, and anyway, it's only related to previewer, not to actually reviewing, so I don't care enough to argue more than that and just try to push whatever you want here so that this bug is resolved.

**Comment by mikehardy** [comment]
> This lead to an interesting question. Should we localize `"undefined"` ?

No. It is a developer interface, our development is 100% english. If undefined "escapes" an API, it's a bug and should be fixed by the javascript API code author, it's not an internationalization issue.

**Comment by infinyte7** [comment]
There is no need for card counts in previewer.
 Is card counts available when accessed using JS api while reviewing?

**Comment by Arthur-Milchior** [comment]
I understand there is no need for those counts. However, the same card template is going to be used for reviewing and for previewing. So any javascript method used in template is going to also be called in the previewer. This means we still need to send it value so that it does not crash.

**Comment by infinyte7** [comment]
Okay, understood.

**Comment by mikehardy** [comment]
@infinyte7 there might be a need for a `@JavascriptAPI` that publicizes what mode we are in, "preview", "review", "cardTemplateEditPreview" or similar? I just put in the policy that we will always return values that are type-compatible to javascript API consumers, so that novice programmers are reasonably safe, but for skilled ones we can give them the information needed to adapt the UI (if they want) based on their mode

This is not a personal interest of mine so I won't propose a PR but if it was interesting to you, I'd merge one

**Comment by infinyte7** [comment]
It is nice idea. I will implement and create PR for this.
