### ISSUE TITLE
[2.13beta] _deckNewLimitSingle stackoverflow

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7066]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/663437b4-40fc-44c2-9061-6decb6890c1f

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$4.done(AsyncTask.java:399)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.StackOverflowError: stack size 1039KB
at com.ichi2.utils.JSONObject.getInt(JSONObject.java:1)
at com.ichi2.libanki.sched.SchedV2._deckNewLimitSingle(SchedV2.java:1)
at com.ichi2.libanki.sched.SchedV2.a(SchedV2.java:1)
at com.ichi2.libanki.sched.f.operation(Unknown Source:2)
at com.ichi2.libanki.sched.SchedV2._deckNewLimit(SchedV2.java:6)
at com.ichi2.libanki.sched.SchedV2._deckNewLimit(SchedV2.java:1)
at com.ichi2.libanki.sched.SchedV2._fillNew(SchedV2.java:6)
at com.ichi2.libanki.sched.SchedV2._fillNew(SchedV2.java:6)
at com.ichi2.libanki.sched.SchedV2._fillNew(SchedV2.java:6)
```

**Comment by Arthur-Milchior** [comment]
I guess I have it. I'll write a regression test and a correction, hopefully this week-end.
