### ISSUE TITLE
Add downgrade suggestion if database version too high

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7072]
We'll be upgrading the database to v15 (likely in AnkiDroid 2.14 or 2.15), we should have a warning if the database version is too high to open with the current version of AnkiDroid

**Comment by Arthur-Milchior** [comment]
If the app can't open, then I assume it's more than just a warning. It should be an error message explaining that they should upgrade and kill the app.

Does switching to a new db version force a full sync ?

**Comment by Arthur-Milchior** [comment]
I'm surprised by this message, because we can't even be sure that all software will have a downgrade option. The version of AnkiDroid showing this message can't downgrade. Do we want to offer in next AnkiDroid an extra option to downgrade ? Seems less useful than just asking them to upgrade ankidroid

**Comment by mikehardy** [comment]
I mentioned in DIscord I don't think this should block any stable release, but as soon as it's concrete as a change, it could be a cherry-picked point release on as many stable releases as needed to cover as much minSdkVersion as possible that would be release-2.10 if we can still build it (unsure?) as it was the last minSdkVersion 15 we even have a chance of building, and then whatever the next stable branch is)

**Comment by david-allison-1** [comment]
Current error:

```
2020-09-13 01:59:09.474 6493-6493/com.ichi2.anki E/Storage: Error opening collection; closing database
    com.ichi2.utils.JSONException: org.json.JSONException: A JSONObject text must begin with '{' at character 0 of 
        at com.ichi2.utils.JSONObject.<init>(JSONObject.java:129)
        at com.ichi2.utils.JSONObject.<init>(JSONObject.java:134)
        at com.ichi2.libanki.Collection.load(Collection.java:276)
        at com.ichi2.libanki.Collection.<init>(Collection.java:187)
        at com.ichi2.libanki.Storage.Collection(Storage.java:68)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:122)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:106)
        at com.ichi2.anki.CollectionHelper.getColSafe(CollectionHelper.java:145)
        at com.ichi2.anki.DeckPicker.onPrepareOptionsMenu(DeckPicker.java:630)
        at android.app.Activity.onPreparePanel(Activity.java:3698)
        at androidx.fragment.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:501)
        at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:487)
        at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3097)
        at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
        at androidx.appcompat.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:523)
        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:457)
        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: org.json.JSONException: A JSONObject text must begin with '{' at character 0 of 
        at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
        at com.ichi2.utils.JSONObject.<init>(JSONObject.java:76)
        at com.ichi2.utils.JSONObject.<init>(JSONObject.java:134) 
        at com.ichi2.libanki.Collection.load(Collection.java:276) 
        at com.ichi2.libanki.Collection.<init>(Collection.java:187) 
        at com.ichi2.libanki.Storage.Collection(Storage.java:68) 
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:122) 
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:106) 
        at com.ichi2.anki.CollectionHelper.getColSafe(CollectionHelper.java:145) 
        at com.ichi2.anki.DeckPicker.onPrepareOptionsMenu(DeckPicker.java:630) 
        at android.app.Activity.onPreparePanel(Activity.java:3698) 
        at androidx.fragment.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:501) 
        at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:487) 
        at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99) 
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3097) 
        at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99) 
        at androidx.appcompat.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:523) 
        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:457) 
        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57) 
        at android.os.Handler.handleCallback(Handler.java:907) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
```
