### ISSUE TITLE
API 22: Crash on typed answer diff

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7091]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 4979
    java.lang.NoClassDefFoundError: com.github.difflib.text.-$$Lambda$e0ga_0L_lFvrq6qfKsY2Lr1yK8U
        at com.github.difflib.text.DiffRowGenerator.<clinit>(DiffRowGenerator.java:47)
        at com.ichi2.utils.DiffEngine.diffedHtmlStrings(DiffEngine.java:46)
        at com.ichi2.anki.AbstractFlashcardViewer.typeAnsAnswerFilter(AbstractFlashcardViewer.java:791)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardAnswer(AbstractFlashcardViewer.java:2058)
        at com.ichi2.anki.AbstractFlashcardViewer$4.onClick(AbstractFlashcardViewer.java:430)
        at android.view.View.performClick(View.java:4780)
        at android.view.View$PerformClick.run(View.java:19866)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
```

**Comment by david-allison-1** [comment]
@mikehardy Related: 1cadef9806879ba02581f3ff59e37651a8a24d30 and #6858. 

Would you support a revert?

**Comment by mikehardy** [comment]
WTHeck? I do not support a revert, I want to get to the bottom of that one. I will have time to look at it later
