### ISSUE TITLE
Pre-launch report crash 2.14alpha6

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#7148]
###### Reproduction Steps

1. https://youtu.be/TSCFM1zuemk
2. 
3. 

###### Expected Result

did not appear to crash but play store says it crashed? what?

###### Actual Result

```
FATAL EXCEPTION: Thread-6
Process: com.ichi2.anki, PID: 18963
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.HashMap.size()' on a null object reference
	at com.ichi2.anki.NoteEditor.saveNote(NoteEditor.java:22)
	at com.ichi2.anki.NoteEditor.onOptionsItemSelected(NoteEditor.java:4)
	at android.app.Activity.onMenuItemSelected(Activity.java:4156)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:1)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:1)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:1)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:1)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:1)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:2)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:2)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:1)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:2)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:4)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:1)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:1)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:2)
	at android.view.View.performClick(View.java:7259)
	at android.view.View.performClickInternal(View.java:7236)
	at android.view.View.access$3600(View.java:801)
	at android.view.View$PerformClick.run(View.java:27892)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:31)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:130)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:124)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:40)
	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:68)
	at androidx.test.espresso.action.Tap.a(Unknown Source:13)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:2)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:9)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:6)
	at androidx.test.espresso.ViewInteraction.a(Unknown Source:140)
	at androidx.test.espresso.ViewInteraction$1.call(Unknown Source:4)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

[logcat.txt](https://github.com/ankidroid/Anki-Android/files/5248476/logcat.txt)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Are you sure the logcat and video correspond to the crash - the error doesn't appear in the logcat

**Comment by mikehardy** [comment]
The whole thing is confusing, I'm not sure of any of it. I think the pre-launch reports got crossed up some how. Maybe you have better luck finding it? I went to the one they flagged and that had the exception (which I pasted, so I'm not crazy) but nothing made sense after that
