### ISSUE TITLE
Hard crash on first time init & collection is corrupt

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7168]
* delete col table
* remove permissions
* Open
* Accept permissions
* Crash

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.ichi2.anki/com.ichi2.anki.DeckPicker}: android.database.sqlite.SQLiteException: no such table: col (code 1): , while compiling: SELECT ver FROM col
at android.app.ActivityThread.deliverResults(ActivityThread.java:4710)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:4752)
at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1993)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:216)
at android.app.ActivityThread.main(ActivityThread.java:7266)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
Caused by: android.database.sqlite.SQLiteException: no such table: col (code 1): , while compiling: SELECT ver FROM col
at io.requery.android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at io.requery.android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:3)
at io.requery.android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:2)
at io.requery.android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:3)
at io.requery.android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:8)
at io.requery.android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:1)
at io.requery.android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:1)
at io.requery.android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:4)
at io.requery.android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:6)
at com.ichi2.utils.DatabaseChangeDecorator.query(DatabaseChangeDecorator.java:2)
at com.ichi2.libanki.DB.queryScalar(DB.java:1)
at com.ichi2.libanki.Storage._upgradeSchema(Storage.java:1)
at com.ichi2.libanki.Storage.Collection(Storage.java:7)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:7)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:1)
at com.ichi2.anki.AnkiActivity.getCol(AnkiActivity.java:1)
at com.ichi2.anki.DeckPicker.onFinishedStartup(DeckPicker.java:1)
at com.ichi2.anki.DeckPicker.showStartupScreensAndDialogs(DeckPicker.java:11)
at com.ichi2.anki.DeckPicker.onRequestPermissionsResult(DeckPicker.java:4)
at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7991)
at android.app.Activity.dispatchActivityResult(Activity.java:7813)
at android.app.ActivityThread.deliverResults(ActivityThread.java:4703)
... 11 more
at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:1)
at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:1)
at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:1)
at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:1)
``

**Comment by david-allison-1** [comment]
But, deleting col is handled in normal startup. User has had this problem for a while, but hasn't taken any action
