### ISSUE TITLE
AOSP Issue: Can't use SubMenus on TV

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7227]
Placeholder - I'd like to either report this to Google, or fix it myself, but the Google tools for AOSP don't officially support Windows, and WSL's given up on me.

This is not in AnkiDroid yet, but will be, and causes issues for #1643, and I'd like an issue reference

Steps to Repro:

* Open Reviewer
* Open Menu
* Use Keyboard to navigate to a submenu (flags)
* Press "Left" to close submenu

```
java.lang.ClassCastException: android.widget.HeaderViewListAdapter cannot be cast to androidx.appcompat.view.menu.MenuAdapter
        at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onKeyDown(MenuPopupWindow.java:184)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2800)
        at android.view.View.dispatchKeyEvent(View.java:13374)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1917)
        at android.widget.ListView.dispatchKeyEvent(ListView.java:2348)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
        at android.widget.PopupWindow$PopupDecorView.dispatchKeyEvent(PopupWindow.java:2545)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5413)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5281)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4947)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5004)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4947)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5004)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4947)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5004)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7505)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7474)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7435)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7630)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by david-allison-1** [comment]
The fix is trivial:

https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/widget/MenuPopupWindow.java#141

```java
                ((MenuAdapter) getAdapter()).getAdapterMenu().close(false /* closeAllMenus */);
```

needs to be changed to:

```java
                final ListAdapter adapter = getAdapter();
                MenuAdapter menuAdapter = adapter instanceof HeaderViewListAdapter ? ((HeaderViewListAdapter) adapter).getWrappedAdapter()  : ((MenuAdapter) getAdapter());
                menuAdapter.getAdapterMenu().close(false /* closeAllMenus */);
```
