### ISSUE TITLE
CI Failure: CompatCopyFileTest

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7236]
```
com.ichi2.compat.CompatCopyFileTest > testCopyErrors FAILED
    java.lang.RuntimeException: Method getLocales in android.content.res.Configuration not mocked. See http://g.co/androidstudio/not-mocked for details.
        at android.content.res.Configuration.getLocales(Configuration.java)
        at org.robolectric.android.DeviceConfig.getLocale(DeviceConfig.java:397)
        at org.robolectric.android.DeviceConfig.applyRules(DeviceConfig.java:244)
        at org.robolectric.android.Bootstrap.applyQualifiers(Bootstrap.java:50)
        at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:151)
        at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:301)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:243)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
com.ichi2.compat.CompatCopyFileTest > testCopyFileToStream FAILED
    java.lang.RuntimeException: Method getLocales in android.content.res.Configuration not mocked. See http://g.co/androidstudio/not-mocked for details.
        at android.content.res.Configuration.getLocales(Configuration.java)
        at org.robolectric.android.DeviceConfig.getLocale(DeviceConfig.java:397)
        at org.robolectric.android.DeviceConfig.applyRules(DeviceConfig.java:244)
        at org.robolectric.android.Bootstrap.applyQualifiers(Bootstrap.java:50)
        at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:151)
        at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:301)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:243)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
com.ichi2.compat.CompatCopyFileTest > testCopyStreamToFile FAILED
    java.lang.RuntimeException: Method getLocales in android.content.res.Configuration not mocked. See http://g.co/androidstudio/not-mocked for details.
        at android.content.res.Configuration.getLocales(Configuration.java)
        at org.robolectric.android.DeviceConfig.getLocale(DeviceConfig.java:397)
        at org.robolectric.android.DeviceConfig.applyRules(DeviceConfig.java:244)
        at org.robolectric.android.Bootstrap.applyQualifiers(Bootstrap.java:50)
        at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:151)
        at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:301)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:243)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by david-allison-1** [comment]
https://travis-ci.org/github/ankidroid/Anki-Android/jobs/729455758 - restarted the job before I got a full trace (sorry), might be non-actionable without this

**Comment by mikehardy** [comment]
I have seen something similar in my attempt to update robolectric 4.4 and API targets to 29 and JDK1.9+ etc and stalled out there. Something about robolectric's classloader isn't loading the robolectric jar and is hitting the "stub" android.jar instead, haven't had time to dig as of yet
