### ISSUE TITLE
_fillRev: StackOverflow

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7261]
2.14alpha1 - might have been fixed already

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/b40de982-f998-476e-9b5b-371d2d971311

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$4.done(AsyncTask.java:415)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.StackOverflowError: stack size 1043KB
at io.requery.android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:2)
at io.requery.android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:4)
at io.requery.android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:6)
at com.ichi2.utils.DatabaseChangeDecorator.query(DatabaseChangeDecorator.java:2)
at com.ichi2.libanki.DB.queryScalar(DB.java:1)
at com.ichi2.libanki.sched.Sched._cntFnRev(Sched.java:3)
at com.ichi2.libanki.sched.Sched.f(Sched.java:1)
at com.ichi2.libanki.sched.c.operation(Unknown Source:2)
at com.ichi2.libanki.sched.SchedV2._walkingCount(SchedV2.java:10)
at com.ichi2.libanki.sched.Sched._resetRevCount(Sched.java:1)
at com.ichi2.libanki.sched.SchedV2._resetRev(SchedV2.java:4)
at com.ichi2.libanki.sched.SchedV2._resetRev(SchedV2.java:1)
at com.ichi2.libanki.sched.Sched._fillRev(Sched.java:27)
at com.ichi2.libanki.sched.Sched._fillRev(Sched.java:28)
```

**Comment by david-allison-1** [comment]
@Arthur-Milchior Was this fixed in https://github.com/ankidroid/Anki-Android/pull/7069/files

**Comment by Arthur-Milchior** [comment]
If it is followed by many other many fillRev, it seems very credible
