### ISSUE TITLE
Crash: TagsDialog not attached to a context

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7263]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/87572c2c-bd2f-4fa2-a0b6-69fb67f504b9

* Add Note screen
* Tap Preview, then tags before Preview Opens
* Exit Preview
* Tags Appears
* Click "OK"

```
java.lang.IllegalStateException: Fragment TagsDialog{9c9bf6 (479dc3e3-ee36-4cab-9296-fa8e3b13154f)} not attached to a context.
at androidx.fragment.app.Fragment.requireContext(Fragment.java:2)
at androidx.fragment.app.Fragment.getResources(Fragment.java:1)
at androidx.fragment.app.Fragment.getString(Fragment.java:2)
at com.ichi2.anki.dialogs.TagsDialog.addTag(TagsDialog.java:8)
at com.ichi2.anki.dialogs.TagsDialog.d(TagsDialog.java:1)
at com.ichi2.anki.dialogs.u1.onInput(Unknown Source:2)
at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:13)
at android.view.View.performClick(View.java:6608)
at android.view.View.performClickInternal(View.java:6585)
at android.view.View.access$3100(View.java:785)
at android.view.View$PerformClick.run(View.java:25921)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:201)
at android.app.ActivityThread.main(ActivityThread.java:6810)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by david-allison-1** [comment]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/54cc18e4-dfc2-4b37-afb3-158913cedfa0

**Comment by david-allison-1** [comment]
Pretty sure this one's been fixed by Tarekk

**Comment by mikehardy** [comment]
No, it was @prateek-singh-3212 :-), and I inadvertently duplicated that issue :facepalm: #8973 - should close with #9011 in review now

**Comment by david-allison-1** [comment]
Oh, no, team effort! With the fragment work from Tarekk allowing it to run after pause without closing the dialog, and prateek with stopping them being dismissed.

**Comment by mikehardy** [comment]
quite true!
