### ISSUE TITLE
Cannot rollback - no transaction is active 

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7265]
This is a common bug with many code paths that can cause it. see: https://github.com/ankidroid/Anki-Android/blob/55f45d78c62b272dca282e53b0dc251a26567186/AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java#L156-L164

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/1ba8eb6c-3bdc-4ec5-a52b-a389130ef77f

```
android.database.sqlite.SQLiteException: cannot rollback - no transaction is active (code 1)
at io.requery.android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
at io.requery.android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:7)
at io.requery.android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:12)
at io.requery.android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:2)
at io.requery.android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:2)
at com.ichi2.utils.DatabaseChangeDecorator.endTransaction(DatabaseChangeDecorator.java:1)
at com.ichi2.async.CollectionTask.doInBackgroundAnswerCard(CollectionTask.java:16)
at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:49)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:2)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
```

**Comment by david-allison-1** [comment]
Normally caused when the disk is full - fixing this exception won't solve the root cause, but it will mean the exception points to the correct issue (disk full) so we can handle it better later on
