### ISSUE TITLE
Check Media Crash: magnitude == null

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7297]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/ba1f723c-2f2a-44e1-a662-492642eb0c98

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$4.done(AsyncTask.java:399)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NullPointerException: magnitude == null
at java.math.BigInteger.<init>(BigInteger.java:273)
at com.ichi2.libanki.Utils.fileChecksum(Utils.java:10)
at com.ichi2.libanki.Media._checksum(Media.java:1)
at com.ichi2.libanki.Media._logChanges(Media.java:8)
at com.ichi2.libanki.Media.findChanges(Media.java:3)
at com.ichi2.async.CollectionTask.doInBackgroundCheckMedia(CollectionTask.java:3)
at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:27)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:2)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 4 more

```

**Comment by david-allison-1** [comment]
Cause: `Utils/ Utils.fileChecksum: File not found.`

https://github.com/ankidroid/Anki-Android/blob/4935ac517deb2d784bba0a9f7793fd2e65f99712/AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java#L608-L637

**Comment by david-allison-1** [comment]
This is going to be a strange one to solve - bubbling the FileNotFound might be the right move, it's an exceptional case and it needs to be considered - we can't continue if we can't use the checksum
