### ISSUE TITLE
NoteEditor: "This should never be reached" was reached, and crashes

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7393]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/0943efc6-9e48-425d-8be3-f1c5bd32af6d

https://github.com/ankidroid/Anki-Android/blob/a7a4aa033fd78902f9da97be35990426f365eec9/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java#L937-L942

```
java.lang.RuntimeException: com.ichi2.anki.exception.ConfirmModSchemaException
at com.ichi2.anki.NoteEditor.c(NoteEditor.java:3)
at com.ichi2.anki.h3.run(Unknown Source:6)
at com.ichi2.anki.dialogs.ConfirmationDialog.c(ConfirmationDialog.java:1)
at com.ichi2.anki.dialogs.e.onClick(Unknown Source:2)
at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:7)
at android.view.View.performClick(View.java:7341)
at android.widget.TextView.performClick(TextView.java:14215)
at android.view.View.performClickInternal(View.java:7307)
at android.view.View.access$3200(View.java:846)
at android.view.View$PerformClick.run(View.java:27796)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7156)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
Caused by: com.ichi2.anki.exception.ConfirmModSchemaException
at com.ichi2.libanki.Collection.modSchema(Collection.java:3)
at com.ichi2.libanki.Models.change(Models.java:1)
at com.ichi2.anki.NoteEditor.changeNoteType(NoteEditor.java:2)
at com.ichi2.anki.NoteEditor.c(NoteEditor.java:2)
... 16 more
```

**Comment by mikehardy** [comment]
"Inconceivable"

https://giphy.com/gifs/disneyplus-the-princess-bride-theprincessbride-J1vUzqdZJlh5AqBWxt?utm_source=media-link&utm_medium=landing&utm_campaign=Media%20Links&utm_term=

**Comment by david-allison-1** [comment]
I genuinely don't see how this could be reached. This should be an easy try-catch + show error to fix.
