### ISSUE TITLE
Media: can't be synced - missing meta table

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7421]
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:354)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
Caused by: android.database.sqlite.SQLiteException: no such table: meta (code 1): , while compiling: update meta set dirMod = ?
at io.requery.android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at io.requery.android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:3)
at io.requery.android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:2)
at io.requery.android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:3)
at io.requery.android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:8)
at io.requery.android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:1)
at io.requery.android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2)
at io.requery.android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2)
at com.ichi2.utils.DatabaseChangeDecorator.execSQL(DatabaseChangeDecorator.java:3)
at com.ichi2.libanki.DB.execute(DB.java:6)
at com.ichi2.libanki.Media._logChanges(Media.java:12)
at com.ichi2.libanki.Media.findChanges(Media.java:3)
at com.ichi2.async.CollectionTask.doInBackgroundCheckMedia(CollectionTask.java:3)
at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:27)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:2)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 4 more
```

**Comment by mikehardy** [comment]
interesting - the only case I can think of that happening is a complete failure to access (or initialize correctly) the media database for reasons of total disk / file access failure or deleting while syncing or some logic bomb in meda db init sequence

**Comment by david-allison-1** [comment]
I got this report from a PM, user should be uploading the corrupt file here. Completely blocked media sync.

**Comment by david-allison-1** [comment]
ACRA ID: 64487aac-9237-43cc-b858-38002c813e99

Table with schema

```
create table android_metadata
(
	locale TEXT
);

create table media
(
	fname text not null
		primary key,
	csum text,
	mtime int not null,
	dirty int not null
);

create index idx_media_dirty
	on media (dirty);

```

No clue how this happened
