### ISSUE TITLE
Doesn't work import on Android

### ISSUE THREAD

**Issue by djeck1432** [ankidroid/Anki-Android#7614]
###### Reproduction Steps

1. I created .apkg file
2. It works on desktop
3. It doesn't work on Android

## Error description:
```Attempt to invoke virtual method 'com.ichi2.utils.JSONObject com.ichi2.utils.JSONObject.put(java.lang.String, int)' on a null object reference```

## Versions

1) `AnkiDesktop`: Version 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
2) `AnkiDroid FlashCards` : Version 2.1.35(2020-10-03)

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @djeck1432, could you rename the upload to `.zip` and upload it here.

Thanks

**Comment by djeck1432** [comment]
Hi @david-allison-1, I tried import from zip but it didn't work for me.

**Comment by david-allison-1** [comment]
https://github.com/ankidroid/Anki-Android/blob/61950d713500c0ce812ced7bc7a08f2bf02f0e41/AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java#L461-L468

```
2020-11-06 16:57:04.666 13331-14579/com.ichi2.anki E/Anki2Importer: _import() exception
    java.lang.NullPointerException: Attempt to invoke virtual method 'long com.ichi2.libanki.DeckConfig.getLong(java.lang.String)' on a null object reference
        at com.ichi2.libanki.Decks.updateConf(Decks.java:714)
        at com.ichi2.libanki.importer.Anki2Importer._did(Anki2Importer.java:464)
        at com.ichi2.libanki.importer.Anki2Importer._did(Anki2Importer.java:456)
        at com.ichi2.libanki.importer.Anki2Importer._importCards(Anki2Importer.java:577)
        at com.ichi2.libanki.importer.Anki2Importer._import(Anki2Importer.java:146)
        at com.ichi2.libanki.importer.Anki2Importer.run(Anki2Importer.java:102)
        at com.ichi2.libanki.importer.AnkiPackageImporter.run(AnkiPackageImporter.java:148)
        at com.ichi2.async.CollectionTask.doInBackgroundImportAdd(CollectionTask.java:1363)
        at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:404)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:312)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:92)
        at android.os.AsyncTask$2.call(AsyncTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
```

**Comment by david-allison-1** [comment]
`g.getLong("conf") == -1`

@djeck1432 how was this deck created?

**Comment by david-allison-1** [comment]
@djeck1432 Following up on the above
