### ISSUE TITLE
DeckPicker: confirmDeckDeletion - UnsupportedOperationException

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7649]
2.14alpha29

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/11a16545-b0ab-4a81-bcad-3be2ed9bc9d7

```
java.lang.UnsupportedOperationException
at java.util.AbstractCollection.add(AbstractCollection.java:262)
at com.ichi2.anki.DeckPicker.confirmDeckDeletion(DeckPicker.java:7)
at com.ichi2.anki.DeckPicker.confirmDeckDeletion(DeckPicker.java:1)
at com.ichi2.anki.dialogs.DeckPickerContextMenu.a(DeckPickerContextMenu.java:21)
at com.ichi2.anki.dialogs.j0.onSelection(Unknown Source:2)
at com.afollestad.materialdialogs.MaterialDialog.onItemSelected(MaterialDialog.java:38)
at com.afollestad.materialdialogs.DefaultRvAdapter$DefaultVH.onClick(DefaultRvAdapter.java:5)
at android.view.View.performClick(View.java:7201)
at android.view.View.performClickInternal(View.java:7170)
at android.view.View.access$3500(View.java:806)
at android.view.View$PerformClick.run(View.java:27562)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7697)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by mikehardy** [comment]
Android 10 (worth noting as this is not some sort of API skew issue) - needs a unit test and a fix I guess

**Comment by david-allison-1** [comment]
Cause: 2d96e47e9e3f7d72c019d1231aa3df7fe060f9c1

https://github.com/ankidroid/Anki-Android/blob/cbd99ed7687c87860bd06dd0fdde2c6e65d1e823/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java#L2643-L2645

`TreeMap.values()` does not support `.add()`: https://docs.oracle.com/javase/7/docs/api/java/util/TreeMap.html#values()
