### ISSUE TITLE
Flaky unit tests showing up on windows runner

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#7654]
Strange, windows unit test took this in CI, but the other unit test runs worked:

```
com.ichi2.anki.DeckPickerTest > limitAppliedAfterReview FAILED

    java.lang.UnsupportedOperationException
        at com.ichi2.libanki.sched.AbstractDeckTreeNode.getNewCount(AbstractDeckTreeNode.java:176)
        at com.ichi2.anki.DeckPickerTest.lambda$limitAppliedAfterReview$6(DeckPickerTest.java:180)
        at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$ActivityScenario(ActivityScenario.java:660)
        at androidx.test.core.app.ActivityScenario$$Lambda$4.run(Unknown Source)
        at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:670)
        at com.ichi2.anki.DeckPickerTest.limitAppliedAfterReview(DeckPickerTest.java:178)
```

Likewise on my fork (plus in main repo for i18n sync PR) windows unit test took this, while other unit tests passed:

```
com.ichi2.anki.DeckPickerTest > confirmDeckDeletionDeletesEmptyDeck FAILED

    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
        at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        java.lang.AssertionError: deck was deleted

        Expected: is <1>
             but: was <2>
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
            at com.ichi2.anki.DeckPickerTest.confirmDeckDeletionDeletesEmptyDeck(DeckPickerTest.java:197)
```

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/pull/7652#issuecomment-725568056_

**Comment by david-allison-1** [comment]
limitAppliedAfterReview: #7565 and pending PR: #7635 

`confirmDeckDeletionDeletesEmptyDeck` was a new test, and will take a look

**Comment by mikehardy** [comment]
LimitAppliedAfterReview can also NPE? (only on windows! 😠 )
 
```
com.ichi2.anki.DeckPickerTest > limitAppliedAfterReview FAILED

    java.lang.NullPointerException
        at com.ichi2.anki.DeckPickerTest.lambda$limitAppliedAfterReview$6(DeckPickerTest.java:180)
        at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$ActivityScenario(ActivityScenario.java:660)
        at androidx.test.core.app.ActivityScenario$$Lambda$4.run(Unknown Source)
        at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:670)
        at com.ichi2.anki.DeckPickerTest.limitAppliedAfterReview(DeckPickerTest.java:178)
```

**Comment by mikehardy** [comment]
I think your fix is just the NPE, not OperationNotSupported

**Comment by david-allison-1** [comment]
I suspect it should fix them both - we need to wait for the task to calculate the counts to finish as well
