### ISSUE TITLE
SyncError: Can't add 0 byte file.

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7662]
I swear I added this as an issue, but can't find it.

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/19747509-69a5-45f2-b92f-6b83bcde03cc

```
com.ichi2.anki.exception.MediaSyncException: SyncError:Can't add 0 byte file.
at com.ichi2.libanki.sync.RemoteMediaServer._dataOnly(RemoteMediaServer.java:11)
at com.ichi2.libanki.sync.RemoteMediaServer.uploadChanges(RemoteMediaServer.java:3)
at com.ichi2.libanki.sync.MediaSyncer.sync(MediaSyncer.java:30)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:78)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:2)
at com.ichi2.async.Connection.doInBackground(Connection.java:4)
at com.ichi2.async.Connection.doInBackground(Connection.java:1)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:929)
```

We allow 0 byte files into the media collection (unknown how - presumably from the Add Note screen), and these are rejected by the sync server.

`Check Media` fixes this, but we'd be better to reject the files in the first place.

Maybe also check that the error message shown is sensible, so a user knows to check media.

**Comment by david-allison-1** [comment]
Related: #3782
