### ISSUE TITLE
Reviewer: NullPointerException: Undoable.getDismissType()

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7723]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/4d36be1a-aacc-43a9-87ef-39851a318056

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.ichi2.libanki.Collection$DismissType com.ichi2.libanki.Undoable.getDismissType()' on a null object reference
at com.ichi2.libanki.Collection.undoType(Collection.java:2)
at com.ichi2.libanki.Collection.undoName(Collection.java:1)
at com.ichi2.anki.Reviewer.onCreateOptionsMenu(Reviewer.java:27)
at android.app.Activity.onCreatePanelMenu(Activity.java:4085)
at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:1)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:5)
at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:1)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
at android.view.Choreographer.doCallbacks(Choreographer.java:790)
at android.view.Choreographer.doFrame(Choreographer.java:721)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:241)
at android.app.ActivityThread.main(ActivityThread.java:7617)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

**Comment by david-allison-1** [comment]
@Arthur-Milchior It seems that `mUndo` contains a null - `getLast()` will throw if there are no elements.

Any clue?

https://github.com/ankidroid/Anki-Android/blob/bff7c6a40bc8cb5181c6883bc5967e64bae5187a/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L1349-L1354

**Comment by Arthur-Milchior** [comment]
`mUndo` adds element only in `markUndo`, so that's what should be investigated.

`markReview` is either called with object created immediately before or with `revertToProvidedState`, and this directly return a new object. So this seems to be impossible.

I know that there is theoretically a risk of asynchronicity here. However, `getLast` always return an element of a node of the linked list, and in LinkedList implementation, `last` is either null or a node with its value already set. So, unless there is a huge difference between master and V2.14 (I doubt it, I've not seen anything touching undo recently) or there is a difference between linked list's in this motorola device and AOSP's implementation, this seems to be logically impossible.

**Comment by david-allison-1** [comment]
Had a look through the code, looks like `unlinkFirst` has a race condition.
