### ISSUE TITLE
Note: Inconsistent Schema Assertion failure

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#7747]
Don't know how this happened, was on an emulator

```
2020-11-21 21:09:06.777 32064-32094/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.ichi2.anki, PID: 32064
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:325)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.AssertionError
        at com.ichi2.libanki.Note.flush(Note.java:128)
        at com.ichi2.libanki.Note.flush(Note.java:124)
        at com.ichi2.libanki.Note.flush(Note.java:120)
        at com.ichi2.libanki.Collection.addNote(Collection.java:661)
        at com.ichi2.async.CollectionTask.lambda$doInBackgroundAddNote$0$CollectionTask(CollectionTask.java:544)
        at com.ichi2.async.-$$Lambda$CollectionTask$_y4R9CYdH0CaOM1uiHATTH2Gb1A.run(lambda)
        at com.ichi2.libanki.DB.executeInTransaction(DB.java:338)
        at com.ichi2.async.CollectionTask.doInBackgroundAddNote(CollectionTask.java:543)
        at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:387)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:335)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:93)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
```

**Comment by david-allison-1** [comment]
Repro Steps:

* Add Note screen
* Edit Card Template
* Add New Card Template
* First Field: "Hello"
* Confirm

**Comment by mikehardy** [comment]
Noted - thanks for the repro steps, I can check this one out

**Comment by dae** [comment]
@david-allison can you still repro?
