### ISSUE TITLE
Pasting Images: Fails if can't get filename

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7748]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/3453b92e-3a46-4a22-86b2-fc930f50e1d3

Not sure how to get the extension, but this can easily be caught: https://github.com/ankidroid/Anki-Android/blob/97d779b94069540a4799badfef4a0b8c0a35daaa/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java#L1544-L1548
```
android.database.sqlite.SQLiteException: no such column: _display_name (code 1 SQLITE_ERROR[1]): , while compiling: SELECT _display_name FROM ClipboardImageTable WHERE (id=855) ORDER BY _data
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
at android.content.ContentResolver.query(ContentResolver.java:809)
at android.content.ContentResolver.query(ContentResolver.java:759)
at android.content.ContentResolver.query(ContentResolver.java:717)
at com.ichi2.anki.NoteEditor.loadImageIntoCollection(NoteEditor.java:1)
at com.ichi2.anki.NoteEditor.onImagePaste(NoteEditor.java:2)
at com.ichi2.anki.NoteEditor.v(Unknown Source:0)
at com.ichi2.anki.e5.onImagePaste(Unknown Source:2)
at com.ichi2.anki.FieldEditText.onImagePaste(FieldEditText.java:1)
at com.ichi2.anki.FieldEditText.a(FieldEditText.java:6)
at com.ichi2.anki.x2.onCommitContent(Unknown Source:9)
at androidx.core.view.inputmethod.InputConnectionCompat$1.commitContent(InputConnectionCompat.java:1)
at android.widget.TextView.commitImage(TextView.java:17342)
at android.widget.TextView.pasteClipBoardData(TextView.java:16748)
at android.widget.TextView.access$4300(TextView.java:438)
at android.widget.TextView$TextViewClipboardEventListener$1.run(TextView.java:16676)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7094)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

**Comment by mikehardy** [comment]
I saw that! SQLiteException really!?!

**Comment by mikehardy** [comment]
This was still happening and PR #7754 was keeping it from crashing but was not allowing the paste as implemented

**Comment by mikehardy** [comment]
Even with 2.15.1 which tries extra hard to paste, users complain. Maybe there is something more we can do here on presentation. Typically it's a file that has no extension (an example "something_or_other_mp3" - note no period!) and I assume the mime type is not set from the sending content provider. What can we do at that point? It might be device specific as the pixel emulator detects mime type correctly so it always sets it.

I suppose we could say "this file has no extension and no MIME type set, it may not be a valid media file. Are you sure you want to attach it?" or similar? 

```
java.lang.IllegalStateException: Couldn't read row 0, col 2 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it.
at android.database.CursorWindow.nativeGetString(Native Method)
at android.database.CursorWindow.getString(CursorWindow.java:469)
at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
at android.database.CursorWrapper.getString(CursorWrapper.java:141)
at com.ichi2.anki.multimediacard.fields.BasicAudioClipFieldController.handleAudioSelection(BasicAudioClipFieldController.java:14)
at com.ichi2.anki.multimediacard.fields.BasicAudioClipFieldController.onActivityResult(BasicAudioClipFieldController.java:1)
at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.onActivityResult(MultimediaEditFieldActivity.java:3)
at android.app.Activity.dispatchActivityResult(Activity.java:8274)
at android.app.ActivityThread.deliverResults(ActivityThread.java:4933)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:4981)
at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2046)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:225)
at android.app.ActivityThread.main(ActivityThread.java:7564)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

```

&nbsp;
--
35 | 05-26 14:31:36.145 I/AnkiDroid( 5188): Saving instance
36 | 05-26 14:31:37.014 I/AnkiDroid( 5188): AnkiActivity::onPause - MultimediaEditFieldActivity
37 | 05-26 14:31:38.320 I/AnkiDroid( 5188): AnkiActivity::onStop - MultimediaEditFieldActivity
38 | 05-26 14:31:48.071 I/AnkiDroid( 5188): Audio clip name does not have extension, using second half of mime type
39 | 05-26  14:31:48.082 W/AnkiDroid( 5188): BasicAudioClipFieldController/  java.lang.IllegalStateException: Couldn't read row 0, col 2 from  CursorWindow.  Make sure the Cursor is initialized correctly before  accessing data from it.
40 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.database.CursorWindow.nativeGetString(Native Method)
41 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.database.CursorWindow.getString(CursorWindow.java:469)
42 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
43 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.database.CursorWrapper.getString(CursorWrapper.java:141)
44 | 05-26  14:31:48.082 W/AnkiDroid( 5188): 	at  com.ichi2.anki.multimediacard.fields.BasicAudioClipFieldController.handleAudioSelection(BasicAudioClipFieldController.java:14)
45 | 05-26  14:31:48.082 W/AnkiDroid( 5188): 	at  com.ichi2.anki.multimediacard.fields.BasicAudioClipFieldController.onActivityResult(BasicAudioClipFieldController.java:1)
46 | 05-26  14:31:48.082 W/AnkiDroid( 5188): 	at  com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.onActivityResult(MultimediaEditFieldActivity.java:3)
47 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.app.Activity.dispatchActivityResult(Activity.java:8274)
48 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4933)
49 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4981)
50 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
51 | 05-26  14:31:48.082 W/AnkiDroid( 5188): 	at  android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
52 | 05-26  14:31:48.082 W/AnkiDroid( 5188): 	at  android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
53 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2046)
54 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.os.Handler.dispatchMessage(Handler.java:107)
55 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.os.Looper.loop(Looper.java:225)
56 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.app.ActivityThread.main(ActivityThread.java:7564)
57 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at java.lang.reflect.Method.invoke(Native Method)
58 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
59 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
60 | 05-26 14:31:48.082 W/AnkiDroid( 5188):
61 | 05-26  14:31:48.082 W/AnkiDroid( 5188): java.lang.IllegalStateException:  Couldn't read row 0, col 2 from CursorWindow.  Make sure the Cursor is  initialized correctly before accessing data from it.
62 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.database.CursorWindow.nativeGetString(Native Method)
63 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.database.CursorWindow.getString(CursorWindow.java:469)
64 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
65 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.database.CursorWrapper.getString(CursorWrapper.java:141)
66 | 05-26  14:31:48.082 W/AnkiDroid( 5188): 	at  com.ichi2.anki.multimediacard.fields.BasicAudioClipFieldController.handleAudioSelection(BasicAudioClipFieldController.java:14)
67 | 05-26  14:31:48.082 W/AnkiDroid( 5188): 	at  com.ichi2.anki.multimediacard.fields.BasicAudioClipFieldController.onActivityResult(BasicAudioClipFieldController.java:1)
68 | 05-26  14:31:48.082 W/AnkiDroid( 5188): 	at  com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.onActivityResult(MultimediaEditFieldActivity.java:3)
69 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.app.Activity.dispatchActivityResult(Activity.java:8274)
70 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4933)
71 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4981)
72 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
73 | 05-26  14:31:48.082 W/AnkiDroid( 5188): 	at  android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
74 | 05-26  14:31:48.082 W/AnkiDroid( 5188): 	at  android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
75 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2046)
76 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.os.Handler.dispatchMessage(Handler.java:107)
77 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.os.Looper.loop(Looper.java:225)
78 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at android.app.ActivityThread.main(ActivityThread.java:7564)
79 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at java.lang.reflect.Method.invoke(Native Method)
80 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
81 | 05-26 14:31:48.082 W/AnkiDroid( 5188): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)


```

**Comment by mikehardy** [comment]
I believe @david-allison-1 finally fixed the last puzzling (to me) part of this with #9025
