### ISSUE TITLE
[Android 8] onPrepareOptionsMenu NullPointerExceptions

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7755]
Seems to mostly be Android 8.0.0. Presumably due to the addition of the deck picker search

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/38d24f11-e7f8-4af3-b771-5a2879b4d541

```
java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setVisible(boolean)' on a null object reference
at com.ichi2.anki.DeckPicker.onPrepareOptionsMenu(DeckPicker.java:4)
at android.app.Activity.onPreparePanel(Activity.java:3483)
at androidx.fragment.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:1)
at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:1)
at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3)
at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:1)
at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:6)
at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:1)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
at android.view.Choreographer.doCallbacks(Choreographer.java:723)
at android.view.Choreographer.doFrame(Choreographer.java:655)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:1)
```

**Comment by david-allison-1** [comment]
Samsung Galaxy J5 Prime
Samsung Galaxy A5 2017 
Asus Zenfone 3
Motorola Moto e5

All Android 8.0.0

**Comment by david-allison-1** [comment]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/1122acf9-b03f-40b8-a2ef-2f0f839b3b3d

```
java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setChecked(boolean)' on a null object reference
at com.ichi2.anki.Statistics.onPrepareOptionsMenu(Statistics.java:8)
at android.app.Activity.onPreparePanel(Activity.java:3483)
at androidx.fragment.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:1)
at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:1)
at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3)
at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:1)
at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:6)
at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:1)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
at android.view.Choreographer.doCallbacks(Choreographer.java:723)
at android.view.Choreographer.doFrame(Choreographer.java:655)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6942)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
