### ISSUE TITLE
Can't open ankidroid without permission access

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#7846]
###### Reproduction Steps

1. Try to open fresh ankidroid without access to data 

###### Expected Result
It opens and ask permission

###### Actual Result

>     Process: com.ichi2.anki, PID: 1417
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.ichi2.libanki.Decks com.ichi2.libanki.Collection.getDecks()' on a null object reference
        at com.ichi2.anki.DeckPicker.onCreateOptionsMenu(DeckPicker.java:735)
        at android.app.Activity.onCreatePanelMenu(Activity.java:4132)
        at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:324)
        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3070)
        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7948)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

###### Debug info
On master, i.e. e70f17175de28d14b05f70faffed37d82615eeb0

###### Research

Probably was introduced by 389bf4c31272350ff45fd92c129524cdec126090. Solution is probably to put this line in a if that gets executed only if the collection is loaded. @david-allison-1 will you deal with it, or do you want me to take care of it?

**Comment by Arthur-Milchior** [comment]
I can start ankidroid on e5da78e94d5a4671aa4c31e90595662a25238a4f, the commit before e70f171 so I believe I was right

**Comment by david-allison-1** [comment]
@Arthur-Milchior I'm busy this morning, can do it this afternoon.

Also needs a follow-up issue to get a unit test in, or a drive to get the instrumented tests working on a clean/safe collection

**Comment by Arthur-Milchior** [comment]
No emergency. I doubt we get that many new alpha tester in a day or two that it creates problem.

Entirely agree about test
