### ISSUE TITLE
Sync error using Ankiweb

### ISSUE THREAD

**Issue by hugomarins** [ankidroid/Anki-Android#7861]
Since about 1 1/2 hours ago, I'm not able to sync my ankidroid devices anymore, even though Ankiweb is working for syncing the desktop version.

I don't know if it is a temporary error, but I think it is not a bad idea to report it here.

If it is happening only to me, I did a full upload to server from desktop earlier, and so I don't know if it is part of the problem. If someone could help me...

The message I got is:

"Sync error
An error has occurred. Try again later."

Debug info:
AnkiDroid Version = 2.15alpha13

Android Version = 10

ACRA UUID = 38f97252-6295-4be3-b0f4-864eaa211b02

Scheduler = std2

Crash Reports Enabled = true

**Comment by hugomarins** [comment]
I was able to sync Ankidroid now using the parallel last stable version (2.14.2). Probably there is some conflict involving the last alpha releases (when the problem first appeared, I was in 2.15alpha12; updated to alpha 13 and the problem was still there).

**Comment by Arthur-Milchior** [comment]
That’s the point of alpha indeed, thanks a lot.
I’ll look at whether we got any log on our side.
Do you know how to get log? It would be quite helpful to access them. Since it’s related to your account it’s harder to reproduce

**Comment by hugomarins** [comment]
@Arthur-Milchior I don't know how to get log. If you direct me some instructions (I could not find on a rapid search on the web), I could do it.

**Comment by Arthur-Milchior** [comment]
It will depend on what system you have. Mac, windows, linux.
You can search for "logcat", to get more specific information. 

I didn't find anything logged on our side. I fear it was not logged as a crash.

**Comment by hugomarins** [comment]
@mikehardy I had posted the debug info (I'll repeat the debug info below). 

I use scheduler version 2. I had problems after 2.15alpha12. I noted that many times when I pressed Sync the app crased and closed, especially [I don't know why] when there was nothing to update, that is, when I forgot I've already pressured the Sync button, and a few time later pressed it again in the same device, without having used Anki and synced from other devices. Constantly use 3 devices: Ankidroid 2.15alpha in my phone and tablet (Samsung Note 9 and Samsung Tab S6), and Anki Desktop (2.1.36beta3) on my PC (windows 10).

But today I have had a bigger problem. After editing some notes on PC, specifically changing note type, a full sync was made from my PC to the server. After that, I could not sync AnkiDroid anymore (I was using 2.15alpha12), nor in my phone, nor in the tablet. I received always the message "Sync error - An error has occurred. Try again later." I thought it might be a temporary unavailability of the sync server. Trying for about 1 1/2 hours, and receiving the same message, I checked for updates in Play Store and saw that the version 2.15alpha13 have been releases. I then updated my phone and tablet apps, but nothing changed.

Later I could do the sync using the parallel 2.14.2 release in both the phone & tablet.

@Arthur-Milchior I even tried, but the "logcat" is beyond my present ability. Sorry!

####Debug info:####
AnkiDroid Version = 2.15alpha13

Android Version = 10

ACRA UUID = 38f97252-6295-4be3-b0f4-864eaa211b02

Scheduler = std2

Crash Reports Enabled = true

**Comment by telotortium** [comment]
I've also encountered this issue on 2.15alpha13. I'm on the v1 scheduler, but I also require a full sync due to changing my note's fields on desktop Anki. Here's my debug info:

```
AnkiDroid Version = 2.15alpha13

Android Version = 11

ACRA UUID = 11426076-d03a-44a2-8a94-4448cc3ac5d5

Scheduler = std

Crash Reports Enabled = true
```

I took a logcat and saw the following logged by AnkiDroid:

```
12-11 15:13:48.175 26828 26828 I AnkiDroid: DeckPicker:: Sync button pressed
12-11 15:13:48.230 26828 27240 I AnkiDroid: Locked Collection - Collection Loading should fail
12-11 15:13:48.232 26828 27240 I AnkiDroid: Sync - starting sync
12-11 15:13:50.726 26828 27240 I AnkiDroid: Sync: getting meta data from server
12-11 15:13:50.735 26828 27240 I AnkiDroid: Sync: building local meta data
12-11 15:13:50.736 26828 27240 I AnkiDroid: Sync: full sync necessary - returning
12-11 15:13:50.737 26828 27240 I AnkiDroid: Sync Finished - Closing Collection
12-11 15:13:50.738 26828 27240 W AnkiDroid: DB/ Not in a transaction. Cannot end transaction.
12-11 15:13:50.745 26828 27240 I AnkiDroid: Closing Collection Log
12-11 15:13:50.746 26828 27240 I AnkiDroid: Collection closed
12-11 15:13:50.746 26828 27240 I AnkiDroid: Unlocked Collection
12-11 15:13:53.863 26828 26938 D OpenGLRenderer: endAllActiveAnimators on 0x76ade557a0 (RippleDrawable) with handle 0x75cdd2cb50
12-11 15:13:53.868 26828 26828 I AnkiDroid: AnkiActivity::onPause - DeckPicker
12-11 15:13:53.883 26828 26828 I AnkiDroid: User has permissions to access collection
12-11 15:13:53.888 26828 26828 I AnkiDroid: Begin openCollection: /sdcard/AnkiDroid/collection.anki2
12-11 15:13:53.895 26828 26828 I AnkiDroid: Opening Collection Log
12-11 15:13:53.915 26828 26828 I AnkiDroid: End openCollection: /sdcard/AnkiDroid/collection.anki2
12-11 15:13:53.915 26828 26828 I AnkiDroid: AnkiActivity::onCreate - DeckPicker
12-11 15:13:53.957 26828 26828 I AnkiDroid: colOpen: true
12-11 15:13:53.958 26828 26828 I AnkiDroid: No startup screens required
12-11 15:13:53.965 26828 26828 I AnkiDroid: AnkiActivity::onStart - DeckPicker
12-11 15:13:53.966 26828 26828 I AnkiDroid: AnkiActivity::onResume - DeckPicker
12-11 15:13:53.972 26828 26828 I AnkiDroid: Updating deck list UI
12-11 15:13:54.113 26828 26828 I AnkiDroid: Updating deck list UI
12-11 15:13:54.132 26828 26847 W System  : A resource failed to call release.
12-11 15:13:54.160 26828 26828 I AnkiDroid: AnkiActivity::onStop - DeckPicker
12-11 15:13:54.162 26828 26828 I AnkiDroid: AnkiActivity::onDestroy - DeckPicker
```

By the way, is there a way to install the stable and alpha at the same time?

**Comment by hugomarins** [comment]
@telotortium You can install the stable in parallel.

Follow these instructions:

https://github.com/ankidroid/Anki-Android/issues/7848#issuecomment-741924070

**Comment by Arthur-Milchior** [comment]
Can you please let me know if sync really failed. I would suspect that sync actually synced collection even if it showed an error message.

**Comment by telotortium** [comment]
Yes, it really failed.

**Comment by telotortium** [comment]
@hugomarins Thanks!

I installed AnkiDroid.A 2.14.1 on my device and was able to complete the full sync. Interestingly, after completing the full sync using AnkiDroid.A, I opened the same collection using my AnkiDroid 2.15alpha13 install. Initially I had tried forcing a full sync in the alpha from the settings, so the sync icon displayed an exclamation mark indicating a full sync is needed. I tried syncing and got the same error message as before one time, but then AnkiDroid recognized that a full sync was not needed. So I tried syncing again and now I see that AnkiDroid is immediately crashing. AnkiDroid.A still works. Here's the logcat for the AnkiDroid alpha:

```
12-12 11:21:00.197 30395 30395 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
12-12 11:21:00.215 30395 30395 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
12-12 11:21:00.216 30395 30395 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
12-12 11:21:00.255 30395 30395 I ACRA    : ACRA is enabled for com.ichi2.anki, initializing...
12-12 11:21:00.265 30395 30395 I AnkiDroid: initialize()
12-12 11:21:00.272 30395 30395 I WebViewFactory: Loading com.google.android.webview version 87.0.4280.101 (code 428010133)
12-12 11:21:00.341 30395 30422 I cr_VariationsUtils: Failed reading seed file "/data/user/0/com.ichi2.anki/app_webview/variations_seed_new"
12-12 11:21:00.342 30395 30395 I cr_LibraryLoader: Loaded native library version number "87.0.4280.101"
12-12 11:21:00.343 30395 30395 I cr_CachingUmaRecorder: Flushed 5 samples from 5 histograms.
12-12 11:21:00.345 30395 30395 I TetheringManager: registerTetheringEventCallback:com.ichi2.anki
12-12 11:21:00.350 30395 30395 I cr_VariationsUtils: Loaded seed with age 12954s
12-12 11:21:00.413 30395 30395 I AnkiDroid: Not participating in analytics sample (sample percentage vs random: 10 98)
12-12 11:21:00.413 30395 30395 I AnkiDroid: setOptIn(): from false to true
12-12 11:21:00.413 30395 30395 I AnkiDroid: Not participating in analytics sample (sample percentage vs random: 10 56)
12-12 11:21:00.416 30395 30395 I AnkiDroid: Creating notification channel with id/name: General Notifications/AnkiDroid
12-12 11:21:00.416 30395 30395 I AnkiDroid: Creating notification channel with id/name: Synchronization/Synchronization
12-12 11:21:00.417 30395 30395 I AnkiDroid: Creating notification channel with id/name: Global Reminders/Cards due
12-12 11:21:00.417 30395 30395 I AnkiDroid: Creating notification channel with id/name: Deck Reminders/Reminders
12-12 11:21:00.421 30395 30395 I AnkiDroid: AnkiDroidApp: Starting Services
12-12 11:21:00.422 30395 30395 I AnkiDroid: Begin openCollection: /sdcard/AnkiDroid/collection.anki2
12-12 11:21:00.432 30395 30395 I AnkiDroid: Opening Collection Log
12-12 11:21:00.445 30395 30395 I AnkiDroid: End openCollection: /sdcard/AnkiDroid/collection.anki2
12-12 11:21:00.445 30395 30395 I AnkiDroid: Executing Boot Service
12-12 11:21:00.467 30395 30395 I AnkiDroid: Launching DeckPicker
12-12 11:21:00.487 30395 30395 I AnkiDroid: User has permissions to access collection
12-12 11:21:00.487 30395 30395 I AnkiDroid: AnkiActivity::onCreate - DeckPicker
12-12 11:21:00.545 30395 30395 I AnkiDroid: colOpen: true
12-12 11:21:00.545 30395 30395 I AnkiDroid: No startup screens required
12-12 11:21:00.552 30395 30395 I AnkiDroid: AnkiActivity::onStart - DeckPicker
12-12 11:21:00.580 30395 30395 I AnkiDroid: AnkiActivity::onResume - DeckPicker
12-12 11:21:00.599 30395 30395 I AnkiDroid: Updating deck list UI
12-12 11:21:00.647 30395 30466 I AdrenoGLES-0: QUALCOMM build                   : e883189, Ia11ce2d146
12-12 11:21:00.647 30395 30466 I AdrenoGLES-0: Build Date                       : 09/02/20
12-12 11:21:00.647 30395 30466 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.31.04.00
12-12 11:21:00.647 30395 30466 I AdrenoGLES-0: Local Branch                     : gfx-adreno.lnx.2.0
12-12 11:21:00.647 30395 30466 I AdrenoGLES-0: Remote Branch                    : quic/gfx-adreno.lnx.2.0
12-12 11:21:00.647 30395 30466 I AdrenoGLES-0: Remote Branch                    : NONE
12-12 11:21:00.647 30395 30466 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
12-12 11:21:00.647 30395 30466 I AdrenoGLES-0: Build Config                     : S L 10.0.5 AArch64
12-12 11:21:00.647 30395 30466 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
12-12 11:21:00.660 30395 30466 I AdrenoGLES-0: PFP: 0x005ff113, ME: 0x005ff066
12-12 11:21:00.661 30395 30466 W AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
12-12 11:21:00.661 30395 30466 W AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
12-12 11:21:00.682 30395 30466 I Gralloc4: mapper 4.x is not supported
12-12 11:21:00.682 30395 30466 W Gralloc3: mapper 3.x is not supported
12-12 11:21:00.752 30395 30395 I AnkiDroid: Updating deck list UI
12-12 11:21:06.118 30395 30395 I AnkiDroid: DeckPicker:: Sync button pressed
12-12 11:21:06.138 30395 30472 I AnkiDroid: Locked Collection - Collection Loading should fail
12-12 11:21:06.139 30395 30472 I AnkiDroid: Sync - starting sync
12-12 11:21:07.321 30395 30472 I AnkiDroid: Sync: getting meta data from server
12-12 11:21:07.323 30395 30472 I AnkiDroid: Sync: building local meta data
12-12 11:21:07.323 30395 30472 I AnkiDroid: Sync: no changes - returning
12-12 11:21:07.327 30395 30472 I AnkiDroid: Sync - Performing media sync
12-12 11:21:08.569 30395 30472 I AnkiDroid: Sync Finished - Closing Collection
12-12 11:21:08.576 30395 30472 W AnkiDroid: DB/ Not in a transaction. Cannot end transaction.
12-12 11:21:08.588 30395 30472 I AnkiDroid: Closing Collection Log
12-12 11:21:08.589 30395 30472 I AnkiDroid: Collection closed
12-12 11:21:08.590 30395 30472 I AnkiDroid: Unlocked Collection
12-12 11:21:08.615 30395 30395 D AndroidRuntime: Shutting down VM
12-12 11:21:08.617 30395 30395 E AndroidRuntime: FATAL EXCEPTION: main
12-12 11:21:08.617 30395 30395 E AndroidRuntime: Process: com.ichi2.anki, PID: 30395
12-12 11:21:08.617 30395 30395 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from null array
12-12 11:21:08.617 30395 30395 E AndroidRuntime: 	at com.ichi2.anki.DeckPicker$3.onPostExecute(DeckPicker.java:11)
12-12 11:21:08.617 30395 30395 E AndroidRuntime: 	at com.ichi2.async.Connection.onPostExecute(Connection.java:6)
12-12 11:21:08.617 30395 30395 E AndroidRuntime: 	at com.ichi2.async.Connection.onPostExecute(Connection.java:1)
12-12 11:21:08.617 30395 30395 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:771)
12-12 11:21:08.617 30395 30395 E AndroidRuntime: 	at android.os.AsyncTask.access$900(AsyncTask.java:199)
12-12 11:21:08.617 30395 30395 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
12-12 11:21:08.617 30395 30395 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-12 11:21:08.617 30395 30395 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
12-12 11:21:08.617 30395 30395 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
12-12 11:21:08.617 30395 30395 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-12 11:21:08.617 30395 30395 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
12-12 11:21:08.617 30395 30395 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
12-12 11:21:08.636 30395 30395 E ACRA    : ACRA caught a NullPointerException for com.ichi2.anki
12-12 11:21:08.636 30395 30395 E ACRA    : java.lang.NullPointerException: Attempt to read from null array
12-12 11:21:08.636 30395 30395 E ACRA    : 	at com.ichi2.anki.DeckPicker$3.onPostExecute(DeckPicker.java:11)
12-12 11:21:08.636 30395 30395 E ACRA    : 	at com.ichi2.async.Connection.onPostExecute(Connection.java:6)
12-12 11:21:08.636 30395 30395 E ACRA    : 	at com.ichi2.async.Connection.onPostExecute(Connection.java:1)
12-12 11:21:08.636 30395 30395 E ACRA    : 	at android.os.AsyncTask.finish(AsyncTask.java:771)
12-12 11:21:08.636 30395 30395 E ACRA    : 	at android.os.AsyncTask.access$900(AsyncTask.java:199)
12-12 11:21:08.636 30395 30395 E ACRA    : 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
12-12 11:21:08.636 30395 30395 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-12 11:21:08.636 30395 30395 E ACRA    : 	at android.os.Looper.loop(Looper.java:223)
12-12 11:21:08.636 30395 30395 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:7656)
12-12 11:21:08.636 30395 30395 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
12-12 11:21:08.636 30395 30395 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
12-12 11:21:08.636 30395 30395 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
12-12 11:21:08.665 30395 30514 D CompatibilityChangeReporter: Compat change id reported: 149924527; UID 10376; state: ENABLED
12-12 11:21:08.665 30395 30514 D CompatibilityChangeReporter: Compat change id reported: 132649864; UID 10376; state: DISABLED
12-12 11:21:08.690 30395 30520 W VideoCapabilities: Unrecognized profile 2130706433 for video/avc
12-12 11:21:08.690 30395 30520 W VideoCapabilities: Unrecognized profile 2130706434 for video/avc
12-12 11:21:08.690 30395 30520 W VideoCapabilities: Unrecognized profile 2130706433 for video/avc
12-12 11:21:08.690 30395 30520 W VideoCapabilities: Unrecognized profile 2130706434 for video/avc
12-12 11:21:08.692 30395 30520 W VideoCapabilities: Unrecognized profile 2130706433 for video/avc
12-12 11:21:08.692 30395 30520 W VideoCapabilities: Unrecognized profile 2130706434 for video/avc
12-12 11:21:08.754 30395 30395 I Process : Sending signal. PID: 30395 SIG: 9
```

**Comment by mikehardy** [comment]
@telotortium / @hugomarins I think we have the same stack covered here #7863 with a PR pending in #7873 that should fix it, I'm working through the PR queue shortly and will issue another alpha that should sort this out. This is unfortunate of course but alpha 11 and 12 were both quite large - they will likely be the majority of the change in this release series kind of all at once so I'm not surprised this was a hiccup but I'm sorry it bit you! Thanks a bunch for helping us out all the way to a stack trace, and we'll see how this goes with alpha14 once it's out

**Comment by mikehardy** [comment]
This should be fixed at this point I hope, if anyone pulls the new alpha and checks it to make sure I'd appreciate the confirmation. Alpha is for testing but in general we have so much automated testing that breaks of any kind in existing features should be rare and we want to know we've fixed them 😁. Cheers
