### ISSUE TITLE
Card Browser - UpdateCard: PairWithCard cannot be cast to android.util.Pair

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7862]
2.15alpha13

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/07ad67cd-aba4-4215-97ef-ab069069167d

```
java.lang.ClassCastException: com.ichi2.utils.PairWithCard cannot be cast to android.util.Pair
at com.ichi2.anki.CardBrowser$UpdateCardHandler.actualOnProgressUpdate(CardBrowser.java:1)
at com.ichi2.async.TaskListenerWithContext.onProgressUpdate(TaskListenerWithContext.java:2)
at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:3)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:687)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:186)
at android.app.ActivityThread.main(ActivityThread.java:6537)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)
```

**Comment by Arthur-Milchior** [comment]
I’ll look at it. I’m surprised

**Comment by Arthur-Milchior** [comment]
Okay, it seems there was one case where I forgot to put a type parameter, and so I didn't get a warning at all that types were not compatible.
I'll correct it immediately
