### ISSUE TITLE
Deck Picker: Attempt to read from null array

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7863]
2.15alpha12

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/965af3d2-6cb5-461c-a0dc-947715b4f416

```
java.lang.NullPointerException: Attempt to read from null array
at com.ichi2.anki.DeckPicker$3.onPostExecute(DeckPicker.java:11)
at com.ichi2.async.Connection.onPostExecute(Connection.java:6)
at com.ichi2.async.Connection.onPostExecute(Connection.java:1)
at android.os.AsyncTask.finish(AsyncTask.java:755)
at android.os.AsyncTask.access$900(AsyncTask.java:192)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:213)
at android.app.ActivityThread.main(ActivityThread.java:8178)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

**Comment by Arthur-Milchior** [comment]
Was able to reproduce.

**Comment by Arthur-Milchior** [comment]
It seems that, when https://github.com/ankidroid/Anki-Android/pull/7150/files#diff-bc9854cf8afc1ab02dad530aa214fdd7d2d9b3e35352bc63d2eb822861912f6d was rebased over 
47dd6596f3e4a3da45d145365f739b241c83d1ed
I did a bad job, and so the enums were not used there. 
The original PR was correct https://github.com/ankidroid/Anki-Android/commit/f8512af52fcae210a92f34c360f9ecb4db33c8ac however the rebasing was not
