### ISSUE TITLE
[Bug] Imports of > 1000 notes fail

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8055]
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$4.done(AsyncTask.java:399)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:929)
Caused by: net.ankiweb.rsdroid.BackendFatalError: panic with no info
at net.ankiweb.rsdroid.RustBackendImpl.validateResult(RustBackendImpl.java:2)
at net.ankiweb.rsdroid.BackendV1Impl.getPage(BackendV1Impl.java:6)
at net.ankiweb.rsdroid.BackendMutex.getPage(BackendMutex.java:2)
at net.ankiweb.rsdroid.database.Session.getPage(Session.java:1)
at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.getNextPage(StreamingProtobufSQLiteCursor.java:3)
at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.moveToNext(StreamingProtobufSQLiteCursor.java:2)
at com.ichi2.libanki.Collection._fieldData(Collection.java:3)
at com.ichi2.libanki.Collection.updateFieldCache(Collection.java:5)
at com.ichi2.libanki.Collection.updateFieldCache(Collection.java:2)
at com.ichi2.libanki.importer.Anki2Importer._importNotes(Anki2Importer.java:69)
at com.ichi2.libanki.importer.Anki2Importer._import(Anki2Importer.java:11)
at com.ichi2.libanki.importer.Anki2Importer.run(Anki2Importer.java:3)
at com.ichi2.libanki.importer.AnkiPackageImporter.run(AnkiPackageImporter.java:58)
at com.ichi2.async.CollectionTask$ImportAdd.task(CollectionTask.java:6)
at com.ichi2.async.CollectionTask$ImportAdd.task(CollectionTask.java:1)
at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:14)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:2)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 5 more
```

https://github.com/david-allison-1/Anki-Android-Backend/blob/edbac00d3c3992796400b68f81ef4bef8c1a2a15/rslib-bridge/src/lib.rs#L448-L458

Logs:

```
IntentHandler/ User requested to view a file
Intent: Intent { dat=[REDACTED] flg=0x43 }. Data: none
Attempting to read content from intent.
AnkiActivity::onStart - DeckPicker
AnkiActivity::onResume - DeckPicker
Dispatching persistent message: 2
Handling Message: ImportAddDialog
Updating deck list UI
uncompress collection.anki2
uncompress media
Opening rust backend. Server: false. Langs: 'en', path:
Opening Collection: '/storage/emulated/0/AnkiDroid/tmpzip/collection.anki2' '' '' ''
Opening Collection Log
Rust: transaction begin
flush - Saving information to DB...
Rust: executeGetRowsAffected UPDATE col SET ls=?,crt=?,dty=?,mod=?,scm=?,usn=?,conf=?
Rust: transaction commit
ExecuteCommand: closeCollection
Closing Collection Log
Collection closed
Opening rust backend. Server: false. Langs: 'en', path:
Opening Collection: '/storage/emulated/0/AnkiDroid/tmpzip/collection.anki2' '' '' ''
Opening Collection Log
Rust: transaction begin
Preparing Import
Importing notes
Rust: transaction rollback
DB/ Not in a transaction. Cannot end transaction.
ExecuteCommand: closeCollection
Closing Collection Log
Collection closed
```

**Comment by david-allison-1** [comment]
https://github.com/ankidroid/Anki-Android/blob/90233c432d19ce1ea3a7a93954c3aa7db5010b8b/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L1068-L1076

<details><summary>SQL Query</summary>

```
SELECT id, mid, flds FROM notes WHERE id IN (1506258814642, 1506258814643, 1506258814644, 1506258814645, 1506258814646, 1506258814647, 1506258814648, 1506258814649, 1506258814650, 1506258814651, 1506258814652, 1506258814653, 1506258814654, 1506258814655, 1506258814656, 1506258814657, 1506258814658, 1506258814659, 1506258814660, 1506258814661, 1506258814662, 1506258814663, 1506258814664, 1506258814665, 1506258814666, 1506258814667, 1506258814668, 1506258814669, 1506258814670, 1506258814671, 1506258814672, 1506258814673, 1506258814674, 1506258814675, 1506258814676, 1506258814677, 1506258814678, 1506258814679, 1506258814680, 1506258814681, 1506258814682, 1506258814683, 1506258814684, 1506258814685, 1506258814686, 1506258814687, 1506258814688, 1506258814689, 1506258814690, 1506258814691, 1506258814692, 1506258814693, 1506258814694, 1506258814695, 1506258814696, 1506258814697, 1506258814698, 1506258814699, 1506258814700, 1506258814701, 1506258814702, 1506258814703, 1506258814704, 1506258814705, 1506258814706, 1506258814707, 1506258814708, 1506258814709, 1506258814710, 1506258814711, 1506258814712, 1506258814713, 1506258814714, 1506258814715, 1506258814716, 1506258814717, 1506258814718, 1506258814719, 1506258814720, 1506258814721, 1506258814722, 1506258814723, 1506258814724, 1506258814725, 1506258814726, 1506258814727, 1506258814728, 1506258814729, 1506258814730, 1506258814731, 1506258814732, 1506258814733, 1506258814734, 1506258814735, 1506258814736, 1506258814737, 1506258814738, 1506258814739, 1506258814740, 1506258814741, 1506258814742, 1506258814743, 1506258814744, 1506258814745, 1506258814746, 1506258814747, 1506258814748, 1506258814749, 1506258814750, 1506258814751, 1506258814752, 1506258814753, 1506258814754, 1506258814755, 1506258814756, 1506258814757, 1506258814758, 1506258814759, 1506258814760, 1506258814761, 1506258814762, 1506258814763, 1506258814764, 1506258814765, 1506258814766, 1506258814767, 1506258814768, 1506258814769, 1506258814770, 1506258814771, 1506258814772, 1506258814773, 1506258814774, 1506258814775, 1506258814776, 1506258814777, 1506258814778, 1506258814779, 1506258814780, 1506258814781, 1506258814782, 1506258814783, 1506258814784, 1506258814785, 1506258814786, 1506258814787, 1506258814788, 1506258814789, 1506258814790, 1506258814791, 1506258814792, 1506258814793, 1506258814794, 1506258814795, 1506258814796, 1506258814797, 1506258814798, 1506258814799, 1506258814800, 1506258814801, 1506258814802, 1506258814803, 1506258814804, 1506258814805, 1506258814806, 1506258814807, 1506258814808, 1506258814809, 1506258814810, 1506258814811, 1506258814812, 1506258814813, 1506258814814, 1506258814815, 1506258814816, 1506258814817, 1506258814818, 1506258814819, 1506258814820, 1506258814821, 1506258814822, 1506258814823, 1506258814824, 1506258814825, 1506258814826, 1506258814827, 1506258814828, 1506258814829, 1506258814830, 1506258814831, 1506258814832, 1506258814833, 1506258814834, 1506258814835, 1506258814836, 1506258814837, 1506258814838, 1506258814839, 1506258814840, 1506258814841, 1506258814842, 1506258814843, 1506258814844, 1506258814845, 1506258814846, 1506258814847, 1506258814848, 1506258814849, 1506258814850, 1506258814851, 1506258814852, 1506258814853, 1506258814854, 1506258814855, 1506258814856, 1506258814857, 1506258814858, 1506258814859, 1506258814860, 1506258814861, 1506258814862, 1506258814863, 1506258814864, 1506258814865, 1506258814866, 1506258814867, 1506258814868, 1506258814869, 1506258814870, 1506258814871, 1506258814872, 1506258814873, 1506258814874, 1506258814875, 1506258814876, 1506258814877, 1506258814878, 1506258814879, 1506258814880, 1506258814881, 1506258814882, 1506258814883, 1506258814884, 1506258814885, 1506258814886, 1506258814887, 1506258814888, 1506258814889, 1506258814890, 1506258814891, 1506258814892, 1506258814893, 1506258814894, 1506258814895, 1506258814896, 1506258814897, 1506258814898, 1506258814899, 1506258814900, 1506258814901, 1506258814902, 1506258814903, 1506258814904, 1506258814905, 1506258814906, 1506258814907, 1506258814908, 1506258814909, 1506258814910, 1506258814911, 1506258814912, 1506258814913, 1506258814914, 1506258814915, 1506258814916, 1506258814917, 1506258814918, 1506258814919, 1506258814920, 1506258814921, 1506258814922, 1506258814923, 1506258814924, 1506258814925, 1506258814926, 1506258814927, 1506258814928, 1506258814929, 1506258814930, 1506258814931, 1506258814932, 1506258814933, 1506258814934, 1506258814935, 1506258814936, 1506258814937, 1506258814938, 1506258814939, 1506258814940, 1506258814941, 1506258814942, 1506258814943, 1506258814944, 1506258814945, 1506258814946, 1506258814947, 1506258814948, 1506258814949, 1506258814950, 1506258814951, 1506258814952, 1506258814953, 1506258814954, 1506258814955, 1506258814956, 1506258814957, 1506258814958, 1506258814959, 1506258814960, 1506258814961, 1506258814962, 1506258814963, 1506258814964, 1506258814965, 1506258814966, 1506258814967, 1506258814968, 1506258814969, 1506258814970, 1506258814971, 1506258814972, 1506258814973, 1506258814974, 1506258814975, 1506258814976, 1506258814977, 1506258814978, 1506258814979, 1506258814980, 1506258814981, 1506258814982, 1506258814983, 1506258814984, 1506258814985, 1506258814986, 1506258814987, 1506258814988, 1506258814989, 1506258814990, 1506258814991, 1506258814992, 1506258814993, 1506258814994, 1506258814995, 1506258814996, 1506258814997, 1506258814998, 1506258814999, 1506258815000, 1506258815001, 1506258815002, 1506258815003, 1506258815004, 1506258815005, 1506258815006, 1506258815007, 1506258815008, 1506258815009, 1506258815010, 1506258815011, 1506258815012, 1506258815013, 1506258815014, 1506258815015, 1506258815016, 1506258815017, 1506258815018, 1506258815019, 1506258815020, 1506258815021, 1506258815022, 1506258815023, 1506258815024, 1506258815025, 1506258815026, 1506258815027, 1506258815028, 1506258815029, 1506258815030, 1506258815031, 1506258815032, 1506258815033, 1506258815034, 1506258815035, 1506258815036, 1506258815037, 1506258815038, 1506258815039, 1506258815040, 1506258815041, 1506258815042, 1506258815043, 1506258815044, 1506258815045, 1506258815046, 1506258815047, 1506258815048, 1506258815049, 1506258815050, 1506258815051, 1506258815052, 1506258815053, 1506258815054, 1506258815055, 1506258815056, 1506258815057, 1506258815058, 1506258815059, 1506258815060, 1506258815061, 1506258815062, 1506258815063, 1506258815064, 1506258815065, 1506258815066, 1506258815067, 1506258815068, 1506258815069, 1506258815070, 1506258815071, 1506258815072, 1506258815073, 1506258815074, 1506258815075, 1506258815076, 1506258815077, 1506258815078, 1506258815079, 1506258815080, 1506258815081, 1506258815082, 1506258815083, 1506258815084, 1506258815085, 1506258815086, 1506258815087, 1506258815088, 1506258815089, 1506258815090, 1506258815091, 1506258815092, 1506258815093, 1506258815094, 1506258815095, 1506258815096, 1506258815097, 1506258815098, 1506258815099, 1506258815100, 1506258815101, 1506258815102, 1506258815103, 1506258815104, 1506258815105, 1506258815106, 1506258815107, 1506258815108, 1506258815109, 1506258815110, 1506258815111, 1506258815112, 1506258815113, 1506258815114, 1506258815115, 1506258815116, 1506258815117, 1506258815118, 1506258815119, 1506258815120, 1506258815121, 1506258815122, 1506258815123, 1506258815124, 1506258815125, 1506258815126, 1506258815127, 1506258815128, 1506258815129, 1506258815130, 1506258815131, 1506258815132, 1506258815133, 1506258815134, 1506258815135, 1506258815136, 1506258815137, 1506258815138, 1506258815139, 1506258815140, 1506258815141, 1506258815142, 1506258815143, 1506258815144, 1506258815145, 1506258815146, 1506258815147, 1506258815148, 1506258815149, 1506258815150, 1506258815151, 1506258815152, 1506258815153, 1506258815154, 1506258815155, 1506258815156, 1506258815157, 1506258815158, 1506258815159, 1506258815160, 1506258815161, 1506258815162, 1506258815163, 1506258815164, 1506258815165, 1506258815166, 1506258815167, 1506258815168, 1506258815169, 1506258815170, 1506258815171, 1506258815172, 1506258815173, 1506258815174, 1506258815175, 1506258815176, 1506258815177, 1506258815178, 1506258815179, 1506258815180, 1506258815181, 1506258815182, 1506258815183, 1506258815184, 1506258815185, 1506258815186, 1506258815187, 1506258815188, 1506258815189, 1506258815190, 1506258815191, 1506258815192, 1506258815193, 1506258815194, 1506258815195, 1506258815196, 1506258815197, 1506258815198, 1506258815199, 1506258815200, 1506258815201, 1506258815202, 1506258815203, 1506258815204, 1506258815205, 1506258815206, 1506258815207, 1506258815208, 1506258815209, 1506258815210, 1506258815211, 1506258815212, 1506258815213, 1506258815214, 1506258815215, 1506258815216, 1506258815217, 1506258815218, 1506258815219, 1506258815220, 1506258815221, 1506258815222, 1506258815223, 1506258815224, 1506258815225, 1506258815226, 1506258815227, 1506258815228, 1506258815229, 1506258815230, 1506258815231, 1506258815232, 1506258815233, 1506258815234, 1506258815235, 1506258815236, 1506258815237, 1506258815238, 1506258815239, 1506258815240, 1506258815241, 1506258815242, 1506258815243, 1506258815244, 1506258815245, 1506258815246, 1506258815247, 1506258815248, 1506258815249, 1506258815250, 1506258815251, 1506258815252, 1506258815253, 1506258815254, 1506258815255, 1506258815256, 1506258815257, 1506258815258, 1506258815259, 1506258815260, 1506258815261, 1506258815262, 1506258815263, 1506258815264, 1506258815265, 1506258815266, 1506258815267, 1506258815268, 1506258815269, 1506258815270, 1506258815271, 1506258815272, 1506258815273, 1506258815274, 1506258815275, 1506258815276, 1506258815277, 1506258815278, 1506258815279, 1506258815280, 1506258815281, 1506258815282, 1506258815283, 1506258815284, 1506258815285, 1506258815286, 1506258815287, 1506258815288, 1506258815289, 1506258815290, 1506258815291, 1506258815292, 1506258815293, 1506258815294, 1506258815295, 1506258815296, 1506258815297, 1506258815298, 1506258815299, 1506258815300, 1506258815301, 1506258815302, 1506258815303, 1506258815304, 1506258815305, 1506258815306, 1506258815307, 1506258815308, 1506258815309, 1506258815310, 1506258815311, 1506258815312, 1506258815313, 1506258815314, 1506258815315, 1506258815316, 1506258815317, 1506258815318, 1506258815319, 1506258815320, 1506258815321, 1506258815322, 1506258815323, 1506258815324, 1506258815325, 1506258815326, 1506258815327, 1506258815328, 1506258815329, 1506258815330, 1506258815331, 1506258815332, 1506258815333, 1506258815334, 1506258815335, 1506258815336, 1506258815337, 1506258815338, 1506258815339, 1506258815340, 1506258815341, 1506258815342, 1506258815343, 1506258815344, 1506258815345, 1506258815346, 1506258815347, 1506258815348, 1506258815349, 1506258815350, 1506258815351, 1506258815352, 1506258815353, 1506258815354, 1506258815355, 1506258815356, 1506258815357, 1506258815358, 1506258815359, 1506258815360, 1506258815361, 1506258815362, 1506258815363, 1506258815364, 1506258815365, 1506258815366, 1506258815367, 1506258815368, 1506258815369, 1506258815370, 1506258815371, 1506258815372, 1506258815373, 1506258815374, 1506258815375, 1506258815376, 1506258815377, 1506258815378, 1506258815379, 1506258815380, 1506258815381, 1506258815382, 1506258815383, 1506258815384, 1506258815385, 1506258815386, 1506258815387, 1506258815388, 1506258815389, 1506258815390, 1506258815391, 1506258815392, 1506258815393, 1506258815394, 1506258815395, 1506258815396, 1506258815397, 1506258815398, 1506258815399, 1506258815400, 1506258815401, 1506258815402, 1506258815403, 1506258815404, 1506258815405, 1506258815406, 1506258815407, 1506258815408, 1506258815409, 1506258815410, 1506258815411, 1506258815412, 1506258815413, 1506258815414, 1506258815415, 1506258815416, 1506258815417, 1506258815418, 1506258815419, 1506258815420, 1506258815421, 1506258815422, 1506258815423, 1506258815424, 1506258815425, 1506258815426, 1506258815427, 1506258815428, 1506258815429, 1506258815430, 1506258815431, 1506258815432, 1506258815433, 1506258815434, 1506258815435, 1506258815436, 1506258815437, 1506258815438, 1506258815439, 1506258815440, 1506258815441, 1506258815442, 1506258815443, 1506258815444, 1506258815445, 1506258815446, 1506258815447, 1506258815448, 1506258815449, 1506258815450, 1506258815451, 1506258815452, 1506258815453, 1506258815454, 1506258815455, 1506258815456, 1506258815457, 1506258815458, 1506258815459, 1506258815460, 1506258815461, 1506258815462, 1506258815463, 1506258815464, 1506258815465, 1506258815466, 1506258815467, 1506258815468, 1506258815469, 1506258815470, 1506258815471, 1506258815472, 1506258815473, 1506258815474, 1506258815475, 1506258815476, 1506258815477, 1506258815478, 1506258815479, 1506258815480, 1506258815481, 1506258815482, 1506258815483, 1506258815484, 1506258815485, 1506258815486, 1506258815487, 1506258815488, 1506258815489, 1506258815490, 1506258815491, 1506258815492, 1506258815493, 1506258815494, 1506258815495, 1506258815496, 1506258815497, 1506258815498, 1506258815499, 1506258815500, 1506258815501, 1506258815502, 1506258815503, 1506258815504, 1506258815505, 1506258815506, 1506258815507, 1506258815508, 1506258815509, 1506258815510, 1506258815511, 1506258815512, 1506258815513, 1506258815514, 1506258815515, 1506258815516, 1506258815517, 1506258815518, 1506258815519, 1506258815520, 1506258815521, 1506258815522, 1506258815523, 1506258815524, 1506258815525, 1506258815526, 1506258815527, 1506258815528, 1506258815529, 1506258815530, 1506258815531, 1506258815532, 1506258815533, 1506258815534, 1506258815535, 1506258815536, 1506258815537, 1506258815538, 1506258815539, 1506258815540, 1506258815541, 1506258815542, 1506258815543, 1506258815544, 1506258815545, 1506258815546, 1506258815547, 1506258815548, 1506258815549, 1506258815550, 1506258815551, 1506258815552, 1506258815553, 1506258815554, 1506258815555, 1506258815556, 1506258815557, 1506258815558, 1506258815559, 1506258815560, 1506258815561, 1506258815562, 1506258815563, 1506258815564, 1506258815565, 1506258815566, 1506258815567, 1506258815568, 1506258815569, 1506258815570, 1506258815571, 1506258815572, 1506258815573, 1506258815574, 1506258815575, 1506258815576, 1506258815577, 1506258815578, 1506258815579, 1506258815580, 1506258815581, 1506258815582, 1506258815583, 1506258815584, 1506258815585, 1506258815586, 1506258815587, 1506258815588, 1506258815589, 1506258815590, 1506258815591, 1506258815592, 1506258815593, 1506258815594, 1506258815595, 1506258815596, 1506258815597, 1506258815598, 1506258815599, 1506258815600, 1506258815601, 1506258815602, 1506258815603, 1506258815604, 1506258815605, 1506258815606, 1506258815607, 1506258815608, 1506258815609, 1506258815610, 1506258815611, 1506258815612, 1506258815613, 1506258815614, 1506258815615, 1506258815616, 1506258815617, 1506258815618, 1506258815619, 1506258815620, 1506258815621, 1506258815622, 1506258815623, 1506258815624, 1506258815625, 1506258815626, 1506258815627, 1506258815628, 1506258815629, 1506258815630, 1506258815631, 1506258815632, 1506258815633, 1506258815634, 1506258815635, 1506258815636, 1506258815637, 1506258815638, 1506258815639, 1506258815640, 1506258815641)
```
</details>

**Comment by david-allison-1** [comment]
Cause: exactly 1000 rows in the output breaks the database paging mechanism with this query

**Comment by david-allison-1** [comment]
```
2021-01-26 14:42:16.860 31526-31924/com.ichi2.anki E/com.ichi2.anki: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
2021-01-26 14:42:16.869 31526-31924/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
    Process: com.ichi2.anki, PID: 31526
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:355)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: net.ankiweb.rsdroid.BackendFatalError: panic with no info
        at net.ankiweb.rsdroid.RustBackendImpl.validateResult(RustBackendImpl.java:35)
        at net.ankiweb.rsdroid.BackendV1Impl.getPage(BackendV1Impl.java:284)
        at net.ankiweb.rsdroid.BackendMutex.getPage(BackendMutex.java:145)
        at net.ankiweb.rsdroid.database.Session.getPage(Session.java:90)
        at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.getNextPage(StreamingProtobufSQLiteCursor.java:66)
        at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.moveToNext(StreamingProtobufSQLiteCursor.java:97)
        at com.ichi2.libanki.importer.Anki2Importer._importCards(Anki2Importer.java:557)
        at com.ichi2.libanki.importer.Anki2Importer._import(Anki2Importer.java:159)
        at com.ichi2.libanki.importer.Anki2Importer.run(Anki2Importer.java:115)
        at com.ichi2.libanki.importer.AnkiPackageImporter.run(AnkiPackageImporter.java:148)
        at com.ichi2.async.CollectionTask$ImportAdd.task(CollectionTask.java:1314)
        at com.ichi2.async.CollectionTask$ImportAdd.task(CollectionTask.java:1299)
        at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:222)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:185)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:108)
        at android.os.AsyncTask$2.call(AsyncTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246) 
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:784) 
2021-01-26 14:42:16.870 31526-31924/com.ichi2.anki D/UsageAnalytics: sendAnalyticsException() description/fatal: net.ankiweb.rsdroid.BackendFatalError: panic with no info/true
2021-01-26 14:42:16.956 31526-31924/com.ichi2.anki I/ACRA: ACRA is disabled for com.ichi2.anki - forwarding uncaught Exception on to default ExceptionHandler
2021-01-26 14:42:16.980 31526-31924/com.ichi2.anki I/Process: Sending signal. PID: 31526 SIG: 9
```

Second cause: importing uses nested SQL cursors, which are not supported yet: https://github.com/david-allison-1/Anki-Android-Backend/issues/23
