### ISSUE TITLE
[Bug] Flaky unit tests (including test SchedV2Test:regression_test_preview)

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8064]
```
com.ichi2.libanki.sched.SchedV2Test > regression_test_preview FAILED
    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
        at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        java.util.NoSuchElementException
            at java.util.LinkedList.getFirst(LinkedList.java:244)
            at com.ichi2.libanki.sched.LrnCardQueue.getFirstDue(LrnCardQueue.java:25)
            at com.ichi2.libanki.sched.SchedV2._getLrnCard(SchedV2.java:1108)
            at com.ichi2.libanki.sched.SchedV2._getCard(SchedV2.java:674)
            at com.ichi2.libanki.sched.SchedV2.getCard(SchedV2.java:172)
            at com.ichi2.libanki.sched.SchedV2Test.regression_test_preview(SchedV2Test.java:1719)
```

**Comment by mikehardy** [comment]
I just tried to fix this one but it still popped up after adding advanceRobolectricLooper
may need to advance with sleep

Here's another one 

```
com.ichi2.libanki.sched.AbstractSchedTest > undoAndRedoNoPreload[SchedV1] FAILED
    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
        at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        java.lang.AssertionError
            at org.junit.Assert.fail(Assert.java:87)
            at org.junit.Assert.assertTrue(Assert.java:42)
            at org.junit.Assert.assertNotNull(Assert.java:713)
            at org.junit.Assert.assertNotNull(Assert.java:723)
            at com.ichi2.libanki.sched.AbstractSchedTest.undoAndRedo(AbstractSchedTest.java:333)
            at com.ichi2.libanki.sched.AbstractSchedTest.undoAndRedoNoPreload(AbstractSchedTest.java:378)
```

**Comment by mikehardy** [comment]
```
com.ichi2.libanki.sched.AbstractSchedTest > siblingCorrectlyBuried[SchedV2] FAILED
    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
        at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        java.lang.AssertionError: 
        Expected: is a value greater than <1>
             but: <1> was equal to <1>
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
            at com.ichi2.libanki.sched.AbstractSchedTest.siblingCorrectlyBuried(AbstractSchedTest.java:182)
```

**Comment by mikehardy** [comment]
```
com.ichi2.libanki.sched.AbstractSchedTest > undoAndRedoNoPreload[SchedV1] FAILED
    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
        at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        java.lang.AssertionError
            at org.junit.Assert.fail(Assert.java:87)
            at org.junit.Assert.assertTrue(Assert.java:42)
            at org.junit.Assert.assertNotNull(Assert.java:713)
            at org.junit.Assert.assertNotNull(Assert.java:723)
            at com.ichi2.libanki.sched.AbstractSchedTest.undoAndRedo(AbstractSchedTest.java:343)
            at com.ichi2.libanki.sched.AbstractSchedTest.undoAndRedoNoPreload(AbstractSchedTest.java:378)
```

**Comment by mikehardy** [comment]
```

com.ichi2.libanki.sched.SchedV2Test > regression_test_preview FAILED
    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
        at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        java.util.NoSuchElementException
            at java.util.LinkedList.getFirst(LinkedList.java:244)
            at com.ichi2.libanki.sched.LrnCardQueue.getFirstDue(LrnCardQueue.java:25)
            at com.ichi2.libanki.sched.SchedV2._getLrnCard(SchedV2.java:1112)
            at com.ichi2.libanki.sched.SchedV2._getCard(SchedV2.java:678)
            at com.ichi2.libanki.sched.SchedV2.getCard(SchedV2.java:176)
            at com.ichi2.libanki.sched.SchedV2Test.regression_test_preview(SchedV2Test.java:1750)

```

**Comment by mikehardy** [comment]
```

com.ichi2.libanki.FinderTest > test_deckNameContainingWildcardCanBeSearched FAILED
    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
        at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        java.lang.NullPointerException
            at com.ichi2.anki.CardBrowser.getDeckId(CardBrowser.java:492)
            at com.ichi2.anki.CardBrowser.onCollectionLoaded(CardBrowser.java:695)
            at com.ichi2.anki.AnkiActivity.startLoadingCollection(AnkiActivity.java:331)
            at com.ichi2.anki.CardBrowser.onCreate(CardBrowser.java:533)
            at android.app.Activity.performCreate(Activity.java:7136)
            at android.app.Activity.performCreate(Activity.java:7127)
```

**Comment by mikehardy** [comment]
I think these are somewhat new

```

com.ichi2.libanki.sched.AbstractSchedTest > undoAndRedoPreload[SchedV1] FAILED
    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
        at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

        Caused by:
        java.lang.AssertionError: expected:<com.ichi2.libanki.sched.Counts@7461> but was:<com.ichi2.libanki.sched.Counts@7462>
            at org.junit.Assert.fail(Assert.java:89)
            at org.junit.Assert.failNotEquals(Assert.java:835)
            at org.junit.Assert.assertEquals(Assert.java:120)
            at org.junit.Assert.assertEquals(Assert.java:146)
            at com.ichi2.libanki.sched.AbstractSchedTest.undoAndRedo(AbstractSchedTest.java:344)
            at com.ichi2.libanki.sched.AbstractSchedTest.undoAndRedoPreload(AbstractSchedTest.java:373)

```

**Comment by mikehardy** [comment]
We are starting to get a lot of "process crashed" errors from the instrumented tests running on the emulator. These are difficult to handle but much of the necessary infrastructure is already in place from a separate project where I had to handle similar things.

1- for any run where the process crashed, turn on timestamps in the github actions so you can see what time approximately the process crashed, and remember the time. An example: https://github.com/ankidroid/Anki-Android/runs/2302781924?check_suite_focus=true#step:14:120

2- I enabled adb logging to a file in the github emulator test workflow, and I post that file as an artifact so you can download it and see the logcat, here is the log from that example, in the "Artifacts" section on that run: https://github.com/ankidroid/Anki-Android/actions/runs/731787161#artifacts

3- open the logcat and seek down to approximately the same time - usually just before - the github action said it crashed (note, sometimes timezone offsets skew the time by some whole number of hours, but I think I also handled that by force-setting emulator timezone, at least I tried to)

The relevant lines appear to be an attempt by BackendV1Impl to open a collection, some GC action, then it takes a signal 9 which is from the scheduler and may not be handled (SIGKILL, my favorite ;-) )

```
04-09 04:01:12.188  3220  3292 I BackendV1Impl: Opening Collection: '/storage/emulated/0/AnkiDroid/collection.anki2' '' '' ''
04-09 04:01:12.197  5479  5497 I droid.dynsyste: Waiting for a blocking GC ProfileSaver
04-09 04:01:12.223  5514  5535 I gedprovisionin: Waiting for a blocking GC ProfileSaver
04-09 04:01:12.181   312   312 D goldfish-address-space: allocate: Ask for block of size 0x8d180
04-09 04:01:12.246   312   312 D goldfish-address-space: allocate: ioctl allocate returned offset 0x3fe296000 size 0x8f000
04-09 04:01:12.249   312   330 D goldfish-address-space: allocate: Ask for block of size 0x8d180
04-09 04:01:12.249   312   330 D goldfish-address-space: allocate: ioctl allocate returned offset 0x3fe207000 size 0x8f000
04-09 04:01:12.275  5479  5497 I droid.dynsyste: WaitForGcToComplete blocked ProfileSaver on ClassLinker for 77.448ms
(some display-related lines deleted here)
04-09 04:01:12.320   525  4367 W ActivityManager: Slow operation: 61ms so far, now at attachApplicationLocked: after mServices.attachApplicationLocked
04-09 04:01:12.384  3220  3877 I OpenGLRenderer: Davey! duration=1470ms; Flags=1, IntendedVsync=499007926237, Vsync=499391259555, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=499407699000, AnimationStart=499407797000, PerformTraversalsStart=499407935000, DrawStart=499741369000, SyncQueued=500290634000, SyncStart=500294069000, IssueDrawCommandsStart=500294918000, SwapBuffers=500466513000, FrameCompleted=500481760000, DequeueBufferDuration=727000, QueueBufferDuration=1732000, GpuCompleted=0, 
04-09 04:01:12.387   525  2238 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 2000; state: DISABLED
04-09 04:01:12.394   525   525 W Looper  : Drained
04-09 04:01:12.401  3220  5561 I Choreographer: Skipped 58 frames!  The application may be doing too much work on its main thread.
04-09 04:01:12.544  2669  2754 I MediaProvider: Deleted 1 items on external_primary due to com.ichi2.anki
04-09 04:01:12.705  5514  5535 I gedprovisionin: WaitForGcToComplete blocked ProfileSaver on ClassLinker for 481.304ms
04-09 04:01:12.754  5514  5527 I gedprovisionin: WaitForGcToComplete blocked RunEmptyCheckpoint on ProfileSaver for 47.477ms
04-09 04:01:12.825  3220  3234 I com.ichi2.anki: WaitForGcToComplete blocked HeapTrim on None for 1.453s
04-09 04:01:12.872  3220  5400 I Process : Sending signal. PID: 3220 SIG: 9
04-09 04:01:12.986   525   709 W InputDispatcher: channel '91da63b Toast (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
04-09 04:01:12.987   525   709 E InputDispatcher: channel '91da63b Toast (server)' ~ Channel is unrecoverably broken and will be disposed!
04-09 04:01:12.992   525  4367 I ActivityManager: Process com.ichi2.anki (pid 3220) has died: fg  FGS 
```

There was something in there about dying while trying to close a custom toast, and also ACRA started up but of course we don't get a crash report in debug.

So I'm not sure we have information to do anything on this one but it points out what information we might need

- we might need more information from Rust about what it thinks it's memory situation is?
- we might need more memory information from the emulator - not sure it's possible - like turning on verbosegc flag in a regular JVM would get you
- we might need a change to ACRA in debug mode where it does not send the crash report but it dumps it into logcat with native stacks if possible (no idea if it's possible)


This is becoming frequent though, I believe it's our top CI crash at the moment.

**Comment by mikehardy** [comment]
New one

```

        Caused by:
        java.util.ConcurrentModificationException
            at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
            at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
            at org.json.JSONArray.writeTo(JSONArray.java:612)
            at org.json.JSONStringer.value(JSONStringer.java:233)
            at org.json.JSONObject.writeTo(JSONObject.java:723)
            at org.json.JSONObject.toString(JSONObject.java:692)
            at com.ichi2.anki.RobolectricTest.getCurrentDatabaseModelCopy(RobolectricTest.java:306)
            at com.ichi2.anki.ModelFieldEditorTest.testForIllegalCharacters(ModelFieldEditorTest.java:88)
            at com.ichi2.anki.ModelFieldEditorTest.testIllegalCharactersInFieldName_addField(ModelFieldEditorTest.java:67)
```
