### ISSUE TITLE
[Bug] Rust: error while compiling: "openAnkiDroidCollection": Anki already open, or media currently syncing.

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8075]
```
android.database.sqlite.SQLiteException: error while compiling: "openAnkiDroidCollection": Anki already open, or media currently syncing.
at net.ankiweb.rsdroid.BackendV1Impl.openAnkiDroidCollection(BackendV1Impl.java:10)
at net.ankiweb.rsdroid.BackendMutex.openAnkiDroidCollection(BackendMutex.java:2)
at net.ankiweb.rsdroid.BackendUtils.openAnkiDroidCollection(BackendUtils.java:1)
at net.ankiweb.rsdroid.database.RustSupportSQLiteOpenHelper.createRustSupportSQLiteDatabase(RustSupportSQLiteOpenHelper.java:4)
at net.ankiweb.rsdroid.database.RustSupportSQLiteOpenHelper.getWritableDatabase(RustSupportSQLiteOpenHelper.java:2)
at com.ichi2.libanki.DB.<init>(DB.java:9)
at com.ichi2.libanki.backend.RustDroidBackend.openCollectionDatabase(RustDroidBackend.java:1)
at com.ichi2.libanki.Storage.Collection(Storage.java:6)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:8)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:3)
at com.ichi2.anki.CollectionHelper.getColSafe(CollectionHelper.java:1)
at com.ichi2.anki.DeckPicker.firstCollectionOpen(DeckPicker.java:11)
at com.ichi2.anki.DeckPicker.onCreate(DeckPicker.java:5)
at android.app.Activity.performCreate(Activity.java:7963)
at android.app.Activity.performCreate(Activity.java:7952)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8167)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: net.ankiweb.rsdroid.BackendException$BackendDbException: Anki already open, or media currently syncing.
at net.ankiweb.rsdroid.RustBackendImpl.validateMessage(RustBackendImpl.java:3)
at net.ankiweb.rsdroid.BackendV1Impl.openAnkiDroidCollection(BackendV1Impl.java:6)
... 27 more
```

**Comment by dae** [comment]
The underlying code is probably SQLITE_BUSY - it seems as if something else had the DB open already. Was this in a unit test, or on a user device?

**Comment by david-allison-1** [comment]
1 user devices on an alpha. Originally with `AnkiDroid.B`, then with `AnkiDroid`

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/reports-browser/user/6add35e9-27cd-45a9-8126-cc21c16ffd73

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/reports-browser/user/35a2c3e0-66c5-4162-88bf-ca3a7f68e5ee

<details><summary>Java Exception</summary>

```
android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
at io.requery.android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at io.requery.android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:3)
at io.requery.android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:2)
at io.requery.android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:1)
at io.requery.android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:5)
at io.requery.android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:11)
at io.requery.android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:2)
at io.requery.android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:2)
at io.requery.android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:4)
at io.requery.android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:2)
at io.requery.android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:2)
at io.requery.android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:3)
at io.requery.android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:6)
at io.requery.android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:16)
at io.requery.android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:3)
at io.requery.android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:1)
at com.ichi2.libanki.DB.<init>(DB.java:8)
at com.ichi2.libanki.Storage.Collection(Storage.java:5)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:8)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:3)
at com.ichi2.anki.CollectionHelper.getColSafe(CollectionHelper.java:1)
at com.ichi2.anki.DeckPicker.firstCollectionOpen(DeckPicker.java:11)
at com.ichi2.anki.DeckPicker.onCreate(DeckPicker.java:5)
at android.app.Activity.performCreate(Activity.java:7963)
at android.app.Activity.performCreate(Activity.java:7952)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8167)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

</details>

Personal TODO:
* [ ] Investigate cause of exception
    * [ ] Check logs/stack traces to see if any of these were caused by a close of the collection due to either a collection path change or a sync
   * [ ] Likely caused by running two instances of AnkiDroid pointed at the same collection (`AnkiDroid.B` and `AnkiDroid`). I don't believe the Java DB code took out an exclusive lock
   * [ ] (hopefully not) Potentially by an Anki process not being killed
   * [ ] (hopefully not) Potentially ACRA/multiprocess related.

* [ ] Improve the error flow programmatically
  * [ ] Specific exception class for `CollectionNotOpen` (and other errors - inherit from `BackendException`)
  * [ ] Handle the error and explain the problem to the user in the UI
* [ ] Consider whether we want to fall back to the Java implementation in this case
  * Probably not - we don't want to keep the Java backend around longer than we have to.
  * Probably better to no longer support the use case for an alpha and add an "AnkiDroid is already running on this collection".

**Comment by mikehardy** [comment]
If the user was parallel I'd also go with the parallel build hunch and test that first, then agree with direction of disallowing. Java should have taken an exclusive lock I suppose. Exposing the underlying sqlite error/message would be helpful in future as well I think?

**Comment by mikehardy** [comment]
tangent thought: I know some alpha testers use termux and access the collection from ankidesktop-running-on-android somehow, plus via ankidroid, could be that use case? Not sure how the use case goes where AnkiDroid API is used (say: adding a note from a dictionary app that has us integrated, or using the Ankidroid API Sample for same) while AnkiDroid is open

Mostly I'm here to tag this for milestone 2.15 though, as I noticed there were no Rust-related issues set as blockers for 2.15 but last I probed on the subject I remember a list of 3? If they could all be tagged as 2.15 release so they gate it (as they were mentioned as gating it...) that would help me

**Comment by david-allison-1** [comment]
Definitely caused by `AnkiDroid.A` and `AnkiDroid` pointing to the same collection

Added changes to next version of backend to allow narrowing down the exception,


New Exception (`BackendDbLockedException`) and stack trace(s)
```
2021-03-29 18:31:53.371 7542-7542/com.ichi2.anki E/BootService: Failed to get collection for boot service - possibly media ejecting
    net.ankiweb.rsdroid.BackendException$BackendDbException$BackendDbLockedException: Anki already open, or media currently syncing.
        at net.ankiweb.rsdroid.RustBackendImpl.validateMessage(RustBackendImpl.java:25)
        at net.ankiweb.rsdroid.BackendV1Impl.openAnkiDroidCollection(BackendV1Impl.java:130)
        at net.ankiweb.rsdroid.BackendMutex.openAnkiDroidCollection(BackendMutex.java:967)
        at net.ankiweb.rsdroid.BackendUtils.openAnkiDroidCollection(BackendUtils.java:27)
        at net.ankiweb.rsdroid.database.RustSupportSQLiteOpenHelper.createRustSupportSQLiteDatabase(RustSupportSQLiteOpenHelper.java:91)
        at net.ankiweb.rsdroid.database.RustSupportSQLiteOpenHelper.getWritableDatabase(RustSupportSQLiteOpenHelper.java:72)
        at com.ichi2.libanki.DB.<init>(DB.java:83)
        at com.ichi2.libanki.backend.RustDroidBackend.openCollectionDatabase(RustDroidBackend.java:42)
        at com.ichi2.libanki.Storage.Collection(Storage.java:76)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:129)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:111)
        at com.ichi2.anki.services.BootService.getColSafe(BootService.java:89)
        at com.ichi2.anki.services.BootService.onReceive(BootService.java:50)
        at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:355)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6715)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-03-29 18:32:04.326 7542-7542/com.ichi2.anki E/SQLiteLog: (5) database is locked in "PRAGMA journal_mode"
2021-03-29 18:32:04.412 7542-7542/com.ichi2.anki E/SQLiteDatabase: Failed to open database '/storage/emulated/0/AnkiDroidA/collection.anki2'.
    android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
        at io.requery.android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at io.requery.android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:937)
        at io.requery.android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:674)
        at io.requery.android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:353)
        at io.requery.android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:326)
        at io.requery.android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:236)
        at io.requery.android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
        at io.requery.android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:467)
        at io.requery.android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:188)
        at io.requery.android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:180)
        at io.requery.android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:850)
        at io.requery.android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:817)
        at io.requery.android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:719)
        at io.requery.android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:241)
        at io.requery.android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:174)
        at io.requery.android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:44)
        at com.ichi2.libanki.DB.<init>(DB.java:83)
        at com.ichi2.libanki.DB.<init>(DB.java:69)
        at com.ichi2.libanki.Storage.getDatabaseVersion(Storage.java:60)
        at com.ichi2.anki.CollectionHelper.getDatabaseVersion(CollectionHelper.java:394)
        at com.ichi2.anki.CollectionHelper.isFutureAnkiDroidVersion(CollectionHelper.java:383)
        at com.ichi2.anki.DeckPicker.isFutureAnkiDroidVersion(DeckPicker.java:557)
        at com.ichi2.anki.DeckPicker.onCreate(DeckPicker.java:541)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
