### ISSUE TITLE
[Bug] Can't sync

### ISSUE THREAD

**Issue by ghost** [ankidroid/Anki-Android#8117]
###### Reproduction Steps

1. Press the synch button

###### Expected Result
To synch

###### Actual Result
Error message: "
Collection synchronized
Error syncing media data
disk I/O error (code 1034)"

###### Debug info
AnkiDroid Version = 2.14.3

Android Version = 10

ACRA UUID = d44dfaee-da8e-41af-8e45-12779e0f1655

Scheduler = std2

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @ChrisPalko, please fill in the debug information so we can help you.

Best,

David

**Comment by ChrisPalko** [comment]
I included the debug info

**Comment by david-allison-1** [comment]
```
com.ichi2.utils.JSONException: org.json.JSONException: A JSONObject text must begin with '{' at character 1 of 403 Forbidden
Access was denied to this resource.
at com.ichi2.utils.JSONObject.<init>(JSONObject.java:20)
at com.ichi2.utils.JSONObject.<init>(JSONObject.java:21)
at com.ichi2.libanki.sync.RemoteServer.parseDict(RemoteServer.java:2)
at com.ichi2.libanki.sync.RemoteServer.chunk(RemoteServer.java:2)
at com.ichi2.libanki.sync.Syncer.sync(Syncer.java:69)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:16)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:2)
at com.ichi2.async.Connection.doInBackground(Connection.java:4)
at com.ichi2.async.Connection.doInBackground(Connection.java:1)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
Caused by: org.json.JSONException: A JSONObject text must begin with '{' at character 1 of 403 Forbidden
Access was denied to this resource.
at org.json.JSONTokener.syntaxError(JSONTokener.java:460)
at com.ichi2.utils.JSONObject.<init>(JSONObject.java:19)
... 14 more
```
