### ISSUE TITLE
[Bug] Cannot sync: "The downloaded file cannot be saved to the SD card"

### ISSUE THREAD

**Issue by twisp007** [ankidroid/Anki-Android#8126]
###### Reproduction Steps

1. Give the app all permissions.
2. Ensure 10+ GB of space is available on "the SD Card". 
3. Hit the sync button.
4. Wait for the files to be downloaded
5. Error: "The downloaded file cannot be saved to the SD card. Either is the card is mounted read-only or there isn't enough space."

###### Expected Result

1. Actually sync without any errors. 

###### Actual Result

1. Does not sync. 
2. Happens with google play version and also alpha version obtained from Github.

![Screenshot_20210223-203211_AnkiDroid](https://user-images.githubusercontent.com/28303082/108863886-ae911080-7617-11eb-9037-12e4a6576a2a.jpg)

###### Debug info

AnkiDroid Version = 2.15alpha27
Android Version = 10
ACRA UUID = 23a3a63b-e6d6-41dc-bcc6-5ce6442254a9
Scheduler = std
Crash Reports Enabled = true
DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
That's unexpected! Would it be possible for you to access the device log while this was happening?
I recognize that's potentially a large ask - the easiest way to do it is to [install Android Studio](https://developer.android.com/studio/), then plug your device into your computer, then use Android Studio to watch the device log while AnkiDroid is running. It would give us a great deal more insight in to why this is happening though

**Comment by twisp007** [comment]
Are you asking me to include a logcat?

Anyway AnkiDroid is syncing without issue now. I don't even know why...

**Comment by danishjamal104** [comment]
> Are you asking me to include a logcat?
> 
> Anyway AnkiDroid is syncing without issue now. I don't even know why... What should I do if the issue arises in the future?

@twisp007 try using debugger in Android Studio to see what caused that error.

**Comment by RasmusRendal** [comment]
I get the same issue, on what is a pretty unstable internet connection:
```
09-09 17:09:46.312  3305  5805 I MediaProvider: Deleted 1 0 0 0 0 0 0 items on external_primary due to com.ichi2.anki
09-09 17:09:46.323  4870  1155 E AnkiDroid: FullSyncer/ Full sync failed to download collection.
09-09 17:09:46.323  4870  1155 E AnkiDroid: okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:4)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:2)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:18)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at java.io.InputStream.read(InputStream.java:205)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at com.ichi2.libanki.sync.HttpSyncer.writeToFile(HttpSyncer.java:4)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at com.ichi2.libanki.sync.FullSyncer.download(FullSyncer.java:13)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:35)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at com.ichi2.async.Connection.doOneInBackground(Connection.java:2)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at com.ichi2.async.Connection.doInBackground(Connection.java:4)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at com.ichi2.async.Connection.doInBackground(Connection.java:1)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at java.lang.Thread.run(Thread.java:1012)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 
09-09 17:09:46.323  4870  1155 E AnkiDroid: okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:4)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:2)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:18)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at java.io.InputStream.read(InputStream.java:205)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at com.ichi2.libanki.sync.HttpSyncer.writeToFile(HttpSyncer.java:4)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at com.ichi2.libanki.sync.FullSyncer.download(FullSyncer.java:13)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:35)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at com.ichi2.async.Connection.doOneInBackground(Connection.java:2)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at com.ichi2.async.Connection.doInBackground(Connection.java:4)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at com.ichi2.async.Connection.doInBackground(Connection.java:1)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
09-09 17:09:46.323  4870  1155 E AnkiDroid: 	at java.lang.Thread.run(Thread.java:1012)
09-09 17:09:46.323  4870  1155 W AnkiDroid: Connection/ Sync - fullsync - download failed
09-09 17:09:46.324  4870  1155 I AnkiDroid: Reopening Database
09-09 17:09:46.324  4870  1155 I AnkiDroid: Opening Collection: '/storage/emulated/0/AnkiDroid2/collection.anki2' '' '' ''
09-09 17:09:46.368  3305  3737 I MediaProvider: Deleted 1 0 0 0 0 0 0 items on external_primary due to com.ichi2.anki
09-09 17:09:46.373  3305  3738 I MediaProvider: Observed non-standard /storage/emulated/0/AnkiDroid2/.nomedia
09-09 17:09:46.373  3305  3738 W MediaProvider: isAppCloneUserPair for user 0: false
09-09 17:09:46.374  3305  3738 V MediaProvider: Inserted id:1000000402 less than next row id backup:1000001000.
09-09 17:09:46.385  3305  3697 E StorageManager: Failed to open /storage/emulated/0/AnkiDroid2/collection.anki2-wal to set project id.: No such file or directory
09-09 17:09:46.385  3305  3697 W MediaProvider: Failed to update quota type for /storage/emulated/0/AnkiDroid2/collection.anki2-wal
09-09 17:09:46.385  3305  3697 W MediaProvider: java.io.IOException: Failed to update quota type for /storage/emulated/0/AnkiDroid2/collection.anki2-wal
09-09 17:09:46.385  3305  3697 W MediaProvider: 	at android.os.storage.StorageManager.updateExternalStorageFileQuotaType(StorageManager.java:2609)
09-09 17:09:46.385  3305  3697 W MediaProvider: 	at com.android.providers.media.MediaProvider.updateQuotaTypeForFileInternal(MediaProvider.java:717)
09-09 17:09:46.385  3305  3697 W MediaProvider: 	at com.android.providers.media.MediaProvider.lambda$onFileCreatedForFuse$17(MediaProvider.java:1724)
09-09 17:09:46.385  3305  3697 W MediaProvider: 	at com.android.providers.media.MediaProvider.$r8$lambda$RwX1jyw0H1CYPm6NAX9_DxGu3Co(Unknown Source:0)
09-09 17:09:46.385  3305  3697 W MediaProvider: 	at com.android.providers.media.MediaProvider$$ExternalSyntheticLambda7.run(Unknown Source:4)
09-09 17:09:46.385  3305  3697 W MediaProvider: 	at android.os.Handler.handleCallback(Handler.java:942)
09-09 17:09:46.385  3305  3697 W MediaProvider: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-09 17:09:46.385  3305  3697 W MediaProvider: 	at android.os.Looper.loopOnce(Looper.java:201)
09-09 17:09:46.385  3305  3697 W MediaProvider: 	at android.os.Looper.loop(Looper.java:288)
09-09 17:09:46.385  3305  3697 W MediaProvider: 	at android.os.HandlerThread.run(HandlerThread.java:67)
09-09 17:09:46.393  3305  5805 I MediaProvider: Deleted 1 0 0 0 0 0 0 items on external_primary due to com.ichi2.anki
09-09 17:09:46.403  3305  3738 I MediaProvider: Observed non-standard /storage/emulated/0/AnkiDroid2/.nomedia
09-09 17:09:46.404  3305  3738 W MediaProvider: isAppCloneUserPair for user 0: false
09-09 17:09:46.406  3305  3738 V MediaProvider: Inserted id:1000000401 less than next row id backup:1000001000.
09-09 17:09:46.422  4870  4870 W com.ichi2.anki: type=1400 audit(0.0:2642): avc: denied { ioctl } for comm=4173796E635461736B20233130 path="/storage/emulated/0/AnkiDroid2/collection.media.ad.db2" dev="fuse" ino=307365 ioctlcmd=0xf50c scontext=u:r:untrusted_app_29:s0:c155,c256,c512,c768 tcontext=u:object_r:fuse:s0 tclass=file permissive=0 app=com.ichi2.anki
09-09 17:09:46.431  4870  1155 I AnkiDroid: Opening Collection Log
09-09 17:09:46.440  4870  1155 I AnkiDroid: Sync Finished - Closing Collection
09-09 17:09:46.440  4870  1155 W AnkiDroid: DB/ Not in a transaction. Cannot end transaction.
09-09 17:09:46.441  4870  1155 I AnkiDroid: ExecuteCommand: closeCollection
09-09 17:09:46.445  4870  1155 I AnkiDroid: Closing Collection Log
09-09 17:09:46.445  4870  1155 I AnkiDroid: Collection closed
09-09 17:09:46.445  4870  1155 I AnkiDroid: Unlocked Collection
09-09 17:09:46.457  1693  2326 D CoreBackPreview: Window{19a47e3 u0 com.ichi2.anki/com.ichi2.anki.DeckPicker}: Setting back callback null
09-09 17:09:46.467  1693  2326 W InputManager-JNI: Input channel object '19a47e3 com.ichi2.anki/com.ichi2.anki.DeckPicker (client)' was disposed without first being removed with the input manager!
09-09 17:09:46.481  4870  4870 I AnkiDroid: Sync Listener: onPostExecute: Data: Payload{mTaskType=1, data=[yx4mGVWjlfEzYBNh, true, download, com.ichi2.anki.web.PreferenceBackedHostNum@a5d0162], resultType=sdAccessError, result=null, success=false, returnType=0, exception=null, message='null'}
```
