### ISSUE TITLE
[Bug] Rust - Check Database OOM

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8178]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/2811a70b-bccf-4ad4-9b94-3386ac6d4196

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$4.done(AsyncTask.java:399)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 169408 byte allocation with 118096 free bytes and 115KB until OOM, target footprint 536870912, growth limit 536870912
at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
at com.google.protobuf.Utf8$SafeProcessor.decodeUtf8(Utf8.java:20)
at com.google.protobuf.Utf8.decodeUtf8(Utf8.java:2)
at com.google.protobuf.CodedInputStream$ArrayDecoder.readStringRequireUtf8(CodedInputStream.java:3)
at BackendProto.Sqlite$SqlValue.<init>(Sqlite.java:20)
at BackendProto.Sqlite$SqlValue.<init>(Sqlite.java:1)
at BackendProto.Sqlite$SqlValue$1.parsePartialFrom(Sqlite.java:2)
at BackendProto.Sqlite$SqlValue$1.parsePartialFrom(Sqlite.java:1)
at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:14)
at BackendProto.Sqlite$Row.<init>(Sqlite.java:15)
at BackendProto.Sqlite$Row.<init>(Sqlite.java:1)
at BackendProto.Sqlite$Row$1.parsePartialFrom(Sqlite.java:2)
at BackendProto.Sqlite$Row$1.parsePartialFrom(Sqlite.java:1)
at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:14)
at BackendProto.Sqlite$DBResult.<init>(Sqlite.java:15)
at BackendProto.Sqlite$DBResult.<init>(Sqlite.java:1)
at BackendProto.Sqlite$DBResult$1.parsePartialFrom(Sqlite.java:2)
at BackendProto.Sqlite$DBResult$1.parsePartialFrom(Sqlite.java:1)
at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:14)
at BackendProto.Sqlite$DBResponse.<init>(Sqlite.java:16)
at BackendProto.Sqlite$DBResponse.<init>(Sqlite.java:1)
at BackendProto.Sqlite$DBResponse$1.parsePartialFrom(Sqlite.java:2)
at BackendProto.Sqlite$DBResponse$1.parsePartialFrom(Sqlite.java:1)
at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:18)
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:24)
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:26)
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:27)
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:9)
at BackendProto.Sqlite$DBResponse.parseFrom(Sqlite.java:5)
at net.ankiweb.rsdroid.BackendV1Impl.getPage(BackendV1Impl.java:4)
at net.ankiweb.rsdroid.BackendMutex.getPage(BackendMutex.java:2)
at net.ankiweb.rsdroid.database.Session.getPage(Session.java:1)
at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.getNextPage(StreamingProtobufSQLiteCursor.java:3)
at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.moveToNext(StreamingProtobufSQLiteCursor.java:2)
at com.ichi2.libanki.Collection._fieldData(Collection.java:3)
at com.ichi2.libanki.Collection.updateFieldCache(Collection.java:5)
at com.ichi2.libanki.Collection.updateFieldCache(Collection.java:2)
at com.ichi2.libanki.Collection.updateFieldCache(Collection.java:16)
at com.ichi2.libanki.Collection.q(Unknown Source:0)
at com.ichi2.libanki.q.apply(Unknown Source:4)
at com.ichi2.libanki.Collection.lambda$fixIntegrity$1(Collection.java:2)
at com.ichi2.libanki.Collection.j(Unknown Source:0)
at com.ichi2.libanki.g.consume(Unknown Source:8)
at com.ichi2.libanki.Collection.fixIntegrity(Collection.java:27)
at com.ichi2.async.CollectionTask$CheckDatabase.task(CollectionTask.java:5)
at com.ichi2.async.CollectionTask$CheckDatabase.task(CollectionTask.java:1)
at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:14)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:2)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 4 more
```

Initial Thoughts

* Better handling of Rust DB Streaming 
  * Maybe: instead of 1000 rows, determine how to count the size of a protobuf as we stream it into a byte array, and stop at a certain point
   * Or vary the number of rows: since we're getting FieldData, rows can be arbitrarily large
   * Maybe this isn't a blocker if we can "fail forward" and move this to Rust in V2.16.X.
* https://github.com/david-allison-1/Anki-Android-Backend/issues/14 - provide a lambda to the backend which contains "Are we low on/OOM"
* Maybe catch the OOM here and use a fallback which won't fail? This will be slow but better than crashing.

**Comment by david-allison-1** [comment]
Also to note: I was expecting that this was likely to be a blocker, it's only happened once this month,

**Comment by mikehardy** [comment]
for any user-provided data I think we must be able to provably constrain the size of data in flight, even if it is inside a given arbitrary-sized user-provided data element

I don't like the idea of fallbacks: multiple implementations to manage, and difficult to probe correctness as you can't even see the second implementation exercised in the wild until the first implementation fails

Handling an OOM is interesting in that it can provide user feedback on why (so maybe they can self-help) but there's really no action to take programmatically unless there's a fallback, which I already don't like

So fixing streaming across the layers is a thing to tackle I think. Same will happen with card templates no (or is that where this already is?)

**Comment by david-allison-1** [comment]
Card templates are a single string (until we move to Schema V16 - they get their own table). The string itself is split via `.substring()` which implicitly limits the length of the result.

Right now, I'll say that I don't know how I'd handle setting a "take a collection of DBRows (variable sized), and send 1MB of data, where 1MB is the size after protobuf compression"

I wouldn't feel confident about implementing the functionality efficiently if it doesn't exist (intuition says it likely won't), it'll be a hard problem and I won't have the spare time to do the appropriate research. 

I'll take the lazy approach of calculating XMB of in-memory data, then assuming that Protobuf will compress that further.

**Comment by mikehardy** [comment]
agreed no need to get fiddly with pre-compressed / post-compressed sizes even if the data is perfectly *uncompressable* resulting in a slight expansion as a pathological case it would not be much so just basing on pre-compressed size seems perfectly fine by me

even when templates get their own table there will be parts of the template that are unbounded so this will never go away I think (the general problem of a single data element maybe OOM'ing)

**Comment by david-allison-1** [comment]
Little too soon - needs a new version of the backend jar
