### ISSUE TITLE
[Bug] Random crashes in "Add note" screen

### ISSUE THREAD

**Issue by Andrej-Adamenko** [ankidroid/Anki-Android#8221]
###### Reproduction Steps

1. Click "+" and then "Add +" in Decks screen to open "Add note" screen.
2. Select my custom note type "ParentingCloze" with many fields and custom card templates with custom Javascript in it.
3. Enter the content of the fields and make some clozes.
4. One time it crashed in this screen, when I was doing some editing or previewing, I do not remember what exactly i did before the crash. The second time it crashed after I clicked the prereview button.

I spent 5 minutes trying to  reproduce the problem, but I was not able to. It worked this time. 

I lost in total about 40 minutes of my work because of the crashes, since the data I already entered were lost.

###### Expected Result
No crash

###### Actual Result
Crash

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.14.6

Android Version = 10

ACRA UUID = 1b392f85-2b0c-4491-b153-fdb7fb7b8d34

Scheduler = std2

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by bhatushar** [comment]
Can you share the template for **ParentingCloze**?

**Comment by david-allison-1** [comment]
Stack trace:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.CardTemplatePreviewer}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.has(java.lang.String)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3488)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3635)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2175)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:7860)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.has(java.lang.String)' on a null object reference
at com.ichi2.libanki.Decks.confForDid(Decks.java:2)
at com.ichi2.anki.AbstractFlashcardViewer.getConfigForCurrentCard(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.loadContentIntoCard(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.k(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.w.consume(Unknown Source:6)
at com.ichi2.anki.AbstractFlashcardViewer.u(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.c0.apply(Unknown Source:4)
at com.ichi2.anki.AbstractFlashcardViewer.processCardFunction(AbstractFlashcardViewer.java:3)
at com.ichi2.anki.AbstractFlashcardViewer.processCardAction(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.fillFlashcard(AbstractFlashcardViewer.java:5)
at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:34)
at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:10)
at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.CardTemplatePreviewer.displayCardQuestion(CardTemplatePreviewer.java:1)
at com.ichi2.anki.CardTemplatePreviewer.onCollectionLoaded(CardTemplatePreviewer.java:20)
at com.ichi2.anki.AnkiActivity.startLoadingCollection(AnkiActivity.java:4)
at com.ichi2.anki.CardTemplatePreviewer.onCreate(CardTemplatePreviewer.java:22)
at android.app.Activity.performCreate(Activity.java:7955)
at android.app.Activity.performCreate(Activity.java:7944)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3463)
... 11 more
```

**Comment by david-allison-1** [comment]
@Andrej-Adamenko Could you please share your `collection.anki2` file. This is the Anki database which contains all Anki information except media. It is located in `AnkiDroid/collection.anki2` on your phone.

You should be able to rename it to .zip and upload it here, or upload it to cloud storage so you can control who accesses this file.

If this contains sensitive information, please let us know and we'll discuss alternate methods to obtain this file from you.

**Comment by Andrej-Adamenko** [comment]
> @Andrej-Adamenko Could you please share your `collection.anki2` file. 

I uploaded my `collection.anki2` file from Anki Desktop for Windows which is synchronized with AnkiDroid. Would it be Ok, or you need the one from my phone?
[collection.zip](https://github.com/ankidroid/Anki-Android/files/6142892/collection.zip)

**Comment by Andrej-Adamenko** [comment]
> Can you share the template for **ParentingCloze**?

I am afraid, I have changed the templates since the bug occurred last time.
This is my current Front Template:

```
<!-- <div id="front"> is needed for "Insert Randomized Lists (multiple choice)" addon --!>

<div id="front">

{{#details_before_question}}
<details>
    {{#details_summary}}
        <summary>
            {{details_summary}}
        </summary>
    {{/details_summary}}    
    {{details_before_question}}
</details>
<br>
{{/details_before_question}}

<div id="clozetext">{{cloze:Text1}}{{cloze:Text2}}{{cloze:Text3}}{{cloze:Text4}}{{cloze:Text5}}{{cloze:Text6}}{{cloze:Text7}}{{cloze:Text8}}{{cloze:Text9}}</div>
<div class="age_note">(возраст ребёнка: 
   {{#Age.from}}от <span class="age">{{Age.from}}</span>{{/Age.from}} 
   {{#Age.to}}  до <span class="age">{{Age.to}}</span>  {{/Age.to}}
   {{#Age.from}}{{^Age.to}}лет{{/Age.to}}{{/Age.from}}
   {{^Age.from}}{{#Age.to}}лет{{/Age.to}}{{/Age.from}}
   {{^Age.from}}{{^Age.to}}<span class="age">любой</span>{{/Age.to}}{{/Age.from}}
).</div>

<div class="important_note">
<br>Примечание: 
<li> знак "<span class="answer_type_sign">=</span>" означает, что нужно дать ответ точно, слово в слово;
<li> знак "<span class="answer_type_sign">~</span>" означает, что ответ своими словами, совпадающий по смыслу считается правильным.
</div>

<div class="reference">
  <p>
  {{#ref.Authors}}
  {{ref.Authors}}<br>
  {{/ref.Authors}}
  {{#ref.URL}}<a href="{{text:ref.URL}}">{{/ref.URL}}
    {{#ref.Title}}{{text:ref.Title}}{{#ref.Year}}, {{/ref.Year}}{{/ref.Title}}
    {{^ref.Title}}{{^ref.Year}}{{text:ref.URL}}{{/ref.Year}}{{/ref.Title}}
    {{ref.Year}}
{{#ref.URL}}</a>{{/ref.URL}}
</div>

<div class="important_note">
Что-то не так с этим вопросом? <A href="javascript: sendFeedback();">Нажми сюда, чтобы отправить замечание автору вопроса</A>

<div style="display:none">
  <div id="noteid">{{note_id}}</div>
</div>

<tts service="android" />

<div id="anki-am" data-name="Assets by ASSET MANAGER" data-version="2.1">
    <script data-name="Prevent reinclusion" data-version="v0.1">
        var ankiAms = document.querySelectorAll('#anki-am')
          if (ankiAms.length > 1) {
            for (const am of Array.from(ankiAms).slice(0, -1)) {
              am.outerHTML = ''
          }
        }
    </script>
    <script data-name="sendFeedback" data-version="v0.2">
        function sendFeedback()
        {
            const yourMessage = "Пишите свои комментарии здесь, под этой строкой:\n\n\nТекст вопроса: " + document.getElementById("clozetext").innerHTML;
            const subject = "comment to note nid:" + document.getElementById("noteid").textContent;
            document.location.href = "mailto:andr.adamenko@gmail.com?subject="
                + encodeURIComponent(subject)
                + "&body=" + encodeURIComponent(yourMessage);
        }

    </script>
</div>
</div>

<div id="type" class="hidden">{{Type}}</div>
<div id="card" class="hidden">{{Card}}</div>
<script>

    const elementId = "front"; // <= change here !!!!!!!!!!!!!!!!!!!!!

    var injectScript = (src) => {
        return new Promise((resolve, reject) => {
            const script = document.createElement('script');
            script.src = src;
            script.async = true;
            script.onload = resolve;
            script.onerror = reject;
            document.head.appendChild(script);
        });
    };
    (async () => {
        // Check if the function defined in the script already exists
        // in order to prevent duplicate loading of the script
        if (typeof AnkiCardElement === 'undefined') {
            await injectScript(
                '_0card.js');
        }
        AnkiCardElement(elementId).buildHtml();  
    })();
</script>


```

This is my back template:
```
<div id="back">

{{#details_before_question}}
<details>
    {{#details_summary}}
        <summary>
            {{details_summary}}
        </summary>
    {{/details_summary}}    
    {{details_before_question}}
</details>
<br>
{{/details_before_question}}

<div id="clozetext">{{cloze:Text1}}{{cloze:Text2}}{{cloze:Text3}}{{cloze:Text4}}{{cloze:Text5}}{{cloze:Text6}}{{cloze:Text7}}{{cloze:Text8}}{{cloze:Text9}}</div>
<div class="age_note">(возраст ребёнка: 
   {{#Age.from}}от <span class="age">{{Age.from}}</span>{{/Age.from}} 
   {{#Age.to}}до <span class="age">{{Age.to}}</span> {{/Age.to}}
   {{#Age.from}}{{^Age.to}}лет{{/Age.to}}{{/Age.from}}
   {{^Age.from}}{{#Age.to}}лет{{/Age.to}}{{/Age.from}}
   {{^Age.from}}{{^Age.to}}<span class="age">любой</span>{{/Age.to}}{{/Age.from}}
).</div>

<div class="reference">
  <p>
  {{#ref.Authors}}
  {{ref.Authors}}<br>
  {{/ref.Authors}}
  {{#ref.URL}}<a href="{{text:ref.URL}}">{{/ref.URL}}
    {{#ref.Title}}{{text:ref.Title}}{{#ref.Year}}, {{/ref.Year}}{{/ref.Title}}
    {{^ref.Title}}{{^ref.Year}}{{text:ref.URL}}{{/ref.Year}}{{/ref.Title}}
    {{ref.Year}}
{{#ref.URL}}</a>{{/ref.URL}}
</div>

<div class="important_note">
Что-то не так с этим вопросом? <A href="javascript: sendFeedback();">Нажми сюда, чтобы отправить замечание автору вопроса</A>

<div style="display:none">
  <div id="noteid">{{note_id}}</div>
</div>

<tts service="android" />

<div id="anki-am" data-name="Assets by ASSET MANAGER" data-version="2.1">
    <script data-name="sendFeedback" data-version="v0.2">
        function sendFeedback()
        {
            const yourMessage = "Пишите свои комментарии здесь, под этой строкой:\n\n\nТекст вопроса: " + document.getElementById("clozetext").innerHTML;
            const subject = "comment to note nid:" + document.getElementById("noteid").textContent;
            document.location.href = "mailto:andr.adamenko@gmail.com?subject="
                + encodeURIComponent(subject)
                + "&body=" + encodeURIComponent(yourMessage);
        }

    </script>
</div>
</div>

<div id="type" class="hidden">{{Type}}</div>
<div id="card" class="hidden">{{Card}}</div>
<script>

    const elementId = "back"; // <= change here !!!!!!!!!!!!!!!!!!!!!

    var injectScript = (src) => {
        return new Promise((resolve, reject) => {
            const script = document.createElement('script');
            script.src = src;
            script.async = true;
            script.onload = resolve;
            script.onerror = reject;
            document.head.appendChild(script);
        });
    };
    (async () => {
        // Check if the function defined in the script already exists
        // in order to prevent duplicate loading of the script
        if (typeof AnkiCardElement === 'undefined') {
            await injectScript(
                '_0card.js');
        }
        AnkiCardElement(elementId).buildHtml();  
    })();
</script>

```
This is my external scripts from collection.media folder, that the templates refer to.
[external scripts.zip](https://github.com/ankidroid/Anki-Android/files/6143674/external.scripts.zip)

**Comment by david-allison-1** [comment]
> > @Andrej-Adamenko Could you please share your `collection.anki2` file.
> 
> I uploaded my `collection.anki2` file from Anki Desktop for Windows which is synchronized with AnkiDroid. Would it be Ok, or you need the one from my phone?
> [collection.zip](https://github.com/ankidroid/Anki-Android/files/6142892/collection.zip)

Very likely need the one from your phone. Thanks

**Comment by Andrej-Adamenko** [comment]
> Very likely need the one from your phone. Thanks
@david-allison-1 
Here it is:
https://drive.google.com/file/d/1WQoFZhW-ivjjopB0D_Hj7oVb-ja22BtV/view?usp=drivesdk
Thanks you.
