### ISSUE TITLE
CI Broken - no such column: allow_empty

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8311]
This appears to have broken CI:

```
com.ichi2.anki.tests.ContentProviderTest > testMoveCardsToOtherDeck[0][TestingAVD(AVD) - 11] FAILED 
	android.database.sqlite.SQLiteException: error while compiling: "SELECT id as _id, guid, mid, allow_empty, mod, usn, tags, flds, sfld, csum, flags, data FROM notes WHERE id in (1616393828073,1616393828277,1616393828506,1616393828883,1616393829171,1616393829514,1616393829727,1616393830070)": DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such column: allow_empty\"))", kind: Other }
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.java:57)

com.ichi2.anki.tests.ContentProviderTest > testQueryNoteIds[0][TestingAVD(AVD) - 11] FAILED 
	android.database.sqlite.SQLiteException: error while compiling: "SELECT id as _id, guid, mid, allow_empty, mod, usn, tags, flds, sfld, csum, flags, data FROM notes WHERE id in (1616393842541,1616393843186,1616393843458,1616393843638,1616393843858,1616393844115,1616393844324,1616393844822)": DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such column: allow_empty\"))", kind: Other }
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.java:57)

com.ichi2.anki.tests.ContentProviderTest > testUpdateNoteFields[0][TestingAVD(AVD) - 11] FAILED 
	android.database.sqlite.SQLiteException: error while compiling: "SELECT id as _id, guid, mid, allow_empty, mod, usn, tags, flds, sfld, csum, flags, data FROM notes WHERE id=?": DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such column: allow_empty\"))", kind: Other }
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.java:57)

com.ichi2.anki.tests.ContentProviderTest > testQueryNotesProjection[0][TestingAVD(AVD) - 11] FAILED 
	android.database.sqlite.SQLiteException: error while compiling: "SELECT guid, mid, allow_empty, mod, usn, tags, flds, sfld, csum, flags, data FROM notes WHERE id in (1616393878268,1616393878819,1616393879184,1616393879491,1616393879961,1616393880460,1616393880768,1616393880969)": DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such column: allow_empty\"))", kind: Other }
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.java:57)

com.ichi2.anki.tests.ContentProviderTest > testQueryDirectSqlQuery[0][TestingAVD(AVD) - 11] FAILED 
	android.database.sqlite.SQLiteException: error while compiling: "SELECT id as _id, guid, mid, allow_empty, mod, usn, tags, flds, sfld, csum, flags, data FROM notes WHERE mid=1616393888238": DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such column: allow_empty\"))", kind: Other }
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.java:57)

com.ichi2.anki.tests.ContentProviderTest > testMoveCardsToOtherDeck[1][TestingAVD(AVD) - 11] FAILED 
	android.database.sqlite.SQLiteException: error while compiling: "SELECT id as _id, guid, mid, allow_empty, mod, usn, tags, flds, sfld, csum, flags, data FROM notes WHERE id in (1616393956534,1616393956767,1616393956995,1616393957134,1616393957271,1616393957625,1616393957917,1616393958127)": DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such column: allow_empty\"))", kind: Other }
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.java:57)

com.ichi2.anki.tests.ContentProviderTest > testQueryNoteIds[1][TestingAVD(AVD) - 11] FAILED 
	android.database.sqlite.SQLiteException: error while compiling: "SELECT id as _id, guid, mid, allow_empty, mod, usn, tags, flds, sfld, csum, flags, data FROM notes WHERE id in (1616393967759,1616393967957,1616393968257,1616393968552,1616393969115,1616393969404,1616393969680,1616393969874)": DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such column: allow_empty\"))", kind: Other }
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.java:57)

com.ichi2.anki.tests.ContentProviderTest > testUpdateNoteFields[1][TestingAVD(AVD) - 11] FAILED 
	android.database.sqlite.SQLiteException: error while compiling: "SELECT id as _id, guid, mid, allow_empty, mod, usn, tags, flds, sfld, csum, flags, data FROM notes WHERE id=?": DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such column: allow_empty\"))", kind: Other }
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.java:57)

com.ichi2.anki.tests.ContentProviderTest > testQueryNotesProjection[1][TestingAVD(AVD) - 11] FAILED 
	android.database.sqlite.SQLiteException: error while compiling: "SELECT guid, mid, allow_empty, mod, usn, tags, flds, sfld, csum, flags, data FROM notes WHERE id in (1616394000267,1616394000643,1616394002353,1616394002709,1616394003437,1616394003955,1616394004681,1616394005692)": DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such column: allow_empty\"))", kind: Other }
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.java:57)

com.ichi2.anki.tests.ContentProviderTest > testQueryDirectSqlQuery[1][TestingAVD(AVD) - 11] FAILED 
	android.database.sqlite.SQLiteException: error while compiling: "SELECT id as _id, guid, mid, allow_empty, mod, usn, tags, flds, sfld, csum, flags, data FROM notes WHERE mid=1616394016904": DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such column: allow_empty\"))", kind: Other }
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.java:57)
```

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/7271#issuecomment-803837881_

**Comment by Arthur-Milchior** [comment]
I'll look at it.
