### ISSUE TITLE
[Bug]  Don't Keep Activities - Crash on viewing Settings from Reviewer 

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8422]
###### Reproduction Steps

1. Reviewer
2. Settings
3. Reviewer

```
2021-04-01 06:19:17.118 20515-20515/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 20515
    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.ichi2.libanki.DB.queryScalar(java.lang.String, java.lang.Object[])' on a null object reference
        at com.ichi2.libanki.sched.SchedV2._resetLrnCount(SchedV2.java:1042)
        at com.ichi2.libanki.sched.SchedV2.resetCounts(SchedV2.java:247)
        at com.ichi2.libanki.sched.SchedV2.resetCounts(SchedV2.java:227)
        at com.ichi2.libanki.sched.SchedV2.counts(SchedV2.java:361)
        at com.ichi2.libanki.sched.SchedV2.counts(SchedV2.java:357)
        at com.ichi2.libanki.sched.SchedV2.counts(SchedV2.java:373)
        at com.ichi2.anki.Reviewer.updateScreenCounts(Reviewer.java:931)
        at com.ichi2.anki.Reviewer.updateActionBar(Reviewer.java:924)
        at com.ichi2.anki.AbstractFlashcardViewer.updateForNewCard(AbstractFlashcardViewer.java:1894)
        at com.ichi2.anki.AbstractFlashcardViewer.fillFlashcard(AbstractFlashcardViewer.java:2421)
        at com.ichi2.anki.Reviewer.fillFlashcard(Reviewer.java:970)
        at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:2268)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:2038)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1997)
        at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:982)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:626)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:603)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:591)
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:241)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:791)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

###### Expected Result

No Crash

###### Actual Result

Crash

###### Debug info

```
AnkiDroid Version = 2.15alpha37

Android Version = 11

Manufacturer = Google

Model = Pixel 3a

Hardware = sargo

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 3a Build/RQ2A.210305.006; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.105 Mobile Safari/537.36

ACRA UUID = 501642ec-39d9-4276-97a3-59a4acbfd30e

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Brief (unsure) Diagnosis: It seems that `mOldColPath` may no longer be set correctly, causing the app to think the collection path has changed.

May be many factors involved

**Comment by david-allison-1** [comment]
Introduced between alpha 34 and 36

**Comment by david-allison-1** [comment]
(likely) cause: c7cb9b2dd6f2f2c361c825b8e31e424b0e4812d5 @Arthur-Milchior - could you confirm it's this commit which introduces the problem. This crash happens often in the latest alpha, and rarely in the commit after this one.

I think there's two issues going on: Firstly, there is a bug, in that the collection is closed after returning from settings due to a bug in setting `mOldColPath`

Secondly: 
  * some tasks are not being cancelled on exit to settings, 
  * tasks seem to run for much longer than they should (in the current alpha, a crash occurs a long time after opening settings).

(Thirdly)? Maybe this gets worse as time passes - possibly another call to start a task before the collection is reopened.

A regression test would be very useful here, this took an age to track down (and I may not be correct)

**Comment by david-allison-1** [comment]
Ah - had "don't keep activities" on. This isn't ideal, but makes the bug much less likely to occur.

**Comment by Arthur-Milchior** [comment]
> (likely) cause: [c7cb9b2](https://github.com/ankidroid/Anki-Android/commit/c7cb9b2dd6f2f2c361c825b8e31e424b0e4812d5) @Arthur-Milchior - could you confirm it's this commit which introduces the problem. This crash happens often in the latest alpha, and rarely in the commit after this one.

I suspect you used a wrong link. This added a task RESET and don't introduce any call to it.  It seems unrelated to `mOldColPath` you mention

> I think there's two issues going on: Firstly, there is a bug, in that the collection is closed after returning from settings due to a bug in setting `mOldColPath`

Seems entirely unrelated to the commit you linked

Why do we close the collection when leaving settings ?


> Secondly:
> 
> * some tasks are not being cancelled on exit to settings,

Do you know which ones?

> * tasks seem to run for much longer than they should (in the current alpha, a crash occurs a long time after opening settings).

Is it especially related to settings ? I could imagine that the same problem would occur when moving to deck picker again or to card browser. 

I believe a nice way to deal with this general behaviour of tasks running when they are not needed anymore would be to extend activity to get a list of tasks that are only important while the activity is alive and cancel those tasks when leaving. As an example in the reviewer, the `getCard` activity can be cancelled, while the activity which save a card should not be cancelled.

**Comment by david-allison-1** [comment]
We close the collection when leaving settings due to a bug in persisting `mColPath`. It's likely been a bug forever. But it wasn't noticeable until 2.15, as it now crashes

The commit was diagnosed manually on my phone, hence asking for verification/confirmation from a second person/phone.

My theory is that it's caused by adding a second task, but this needs to be confirmed, along with whether I've got the correct commit hash.

I'm on my phone and will aim to follow up with further thoughts & a proposed solution tomorrow

**Comment by david-allison-1** [comment]
Most of that post was prefaced with speculation on how things were working rather than certainty. Fixing `mColPath` would mask the bug, rather than solve it.

I was hoping for confirmation via checkout that the commit was correct, as I was unsure and the crash was flaky. 

I've re-checked and it seems that:

* `git checkout bc5dd52dde2358fe396fc464217c9a3b06770e5e` - does not compile, crashes when fixed
* `git checkout 0efd8ec714b0a96488292519911e3a5682bebec3` - couldn't repro a crash
* `git checkout c7cb9b2dd6f2f2c361c825b8e31e424b0e4812d5` - couldn't repro a crash

**Comment by david-allison-1** [comment]
<details><summary>Logcat</summary>

```
2021-04-14 14:33:13.606 28210-28210/com.ichi2.anki D/Collection: undoAvailable() undo size: 0
2021-04-14 14:33:15.224 28210-28210/com.ichi2.anki D/Collection: undoAvailable() undo size: 0
2021-04-14 14:33:15.302 28210-28210/com.ichi2.anki I/NavigationDrawerActivity: Navigating to settings
2021-04-14 14:33:15.320 28210-28210/com.ichi2.anki I/AnkiActivity: AnkiActivity::onPause - Reviewer
2021-04-14 14:33:15.321 28210-28210/com.ichi2.anki D/AbstractFlashcardViewer: onPause()
2021-04-14 14:33:15.345 28210-28210/com.ichi2.anki D/AnkiDroidApp: AnkiDroidApp::getLanguageConfig - setting locale to en_GB
2021-04-14 14:33:15.817 28210-28210/com.ichi2.anki I/AnkiActivity: AnkiActivity::onStop - Reviewer
2021-04-14 14:33:15.824 28210-28210/com.ichi2.anki D/WidgetStatus: WidgetStatus.update(): already running or not enabled
2021-04-14 14:33:15.825 28210-28210/com.ichi2.anki D/UIUtils: saveCollectionInBackground: start
2021-04-14 14:33:15.825 28210-28284/com.ichi2.anki D/CollectionTask$SaveCollection: doInBackgroundSaveCollection
2021-04-14 14:33:15.831 28210-28210/com.ichi2.anki D/UIUtils: saveCollectionInBackground: finished
2021-04-14 14:33:15.831 28210-28210/com.ichi2.anki D/CollectionTask: enabling garbage collection of mPreviousTask...
2021-04-14 14:33:15.856 28210-28210/com.ichi2.anki I/AnkiActivity: AnkiActivity::onDestroy - Reviewer
2021-04-14 14:33:15.857 28210-28210/com.ichi2.anki D/AbstractFlashcardViewer: onDestroy()
2021-04-14 14:33:51.370 28210-28226/com.ichi2.anki W/System: A resource failed to call release. 
2021-04-14 14:33:51.370 28210-28226/com.ichi2.anki I/chatty: uid=10312(com.ichi2.anki) FinalizerDaemon identical 1 line
2021-04-14 14:33:51.370 28210-28226/com.ichi2.anki W/System: A resource failed to call release. 
---- Close settings
2021-04-14 14:40:58.918 28210-28210/com.ichi2.anki D/AnkiDroidApp: AnkiDroidApp::getLanguageConfig - setting locale to en_GB
2021-04-14 14:41:26.180 28210-28210/com.ichi2.anki D/AnkiDroidApp: AnkiDroidApp::getLanguageConfig - setting locale to en_GB
2021-04-14 14:41:26.195 28210-28210/com.ichi2.anki D/Reviewer: onCreate()
2021-04-14 14:41:26.195 28210-28210/com.ichi2.anki D/AbstractFlashcardViewer: onCreate()
2021-04-14 14:41:26.262 28210-28210/com.ichi2.anki I/AnkiActivity: AnkiActivity::onCreate - Reviewer
2021-04-14 14:41:26.428 28210-28210/com.ichi2.anki D/AnkiActivity: AnkiActivity.startLoadingCollection()
2021-04-14 14:41:26.428 28210-28210/com.ichi2.anki D/AnkiActivity: Synchronously calling onCollectionLoaded
2021-04-14 14:41:26.443 28210-28284/com.ichi2.anki I/CollectionTask$GetCard: Obtaining card
2021-04-14 14:41:26.443 28210-28210/com.ichi2.anki I/ViewGroupUtils: ViewGroupUtils::setRenderWorkaround - using default / hardware rendering
2021-04-14 14:41:26.449 28210-28210/com.ichi2.anki I/AnkiActivity: AnkiActivity::onStart - Reviewer
2021-04-14 14:41:26.465 28210-28210/com.ichi2.anki I/NavigationDrawerActivity: Handling Activity Result: 100. Result: 0
2021-04-14 14:41:26.466 28210-28210/com.ichi2.anki I/CompatV26: Creating notification channel with id/name: General Notifications/AnkiDroid
2021-04-14 14:41:26.466 28210-28284/com.ichi2.anki D/Collection: [1618407686] SchedV2.java:getCard(): 'mData': ,  'mDid': 1617114046583,  'mDue': 1618279473,  'mElapsedTime': 0,  'mFactor': 0,  'mFlags': 2,  'mId': 1617720581027,  'mIvl': 0,  'mLapses': 0,  'mLastIvl': 0,  'mLeft': 2003,  'mMod': 1618279403,  'mNid': 1617720579651,  'mODid': 0,  'mODue': 0,  'mOrd': 0,  'mQueue': 1,  'mReps': 5,  'mType': 1,  'mUsn': -1,  'mWasNew': false
2021-04-14 14:41:26.468 28210-28210/com.ichi2.anki I/CompatV26: Creating notification channel with id/name: Synchronization/Synchronization
2021-04-14 14:41:26.468 28210-28284/com.ichi2.anki E/Threads: must be called on the main thread instead of Thread[AsyncTask #2,5,main]
2021-04-14 14:41:26.468 28210-28284/com.ichi2.anki E/Threads: must be called on the main thread instead of Thread[AsyncTask #2,5,main]
2021-04-14 14:41:26.468 28210-28284/com.ichi2.anki D/Note: load()
2021-04-14 14:41:26.469 28210-28210/com.ichi2.anki I/CompatV26: Creating notification channel with id/name: Global Reminders/Cards due
2021-04-14 14:41:26.470 28210-28210/com.ichi2.anki I/CompatV26: Creating notification channel with id/name: Deck Reminders/Reminders
2021-04-14 14:41:26.471 28210-28210/com.ichi2.anki I/CollectionHelper: closeCollection: Preference Modification: collection path changed
2021-04-14 14:41:26.474 28210-28648/com.ichi2.anki D/CollectionTask: Waiting for com.ichi2.async.CollectionTask$GetCard@66df8ec to finish before starting class com.ichi2.async.CollectionTask$Reset
2021-04-14 14:41:26.475 28210-28648/com.ichi2.anki D/CollectionTask: Finished waiting for com.ichi2.async.CollectionTask$GetCard@66df8ec to finish. Status= RUNNING
2021-04-14 14:41:26.477 28210-28210/com.ichi2.anki I/NativeMethods: ExecuteCommand: closeCollection
2021-04-14 14:41:26.482 28210-28210/com.ichi2.anki D/DB: Database /storage/emulated/0/AnkiDroidA/collection.anki2 closed = true
2021-04-14 14:41:26.484 28210-28210/com.ichi2.anki D/DB: Database /storage/emulated/0/AnkiDroidA/collection.media.ad.db2 closed = true
2021-04-14 14:41:26.484 28210-28210/com.ichi2.anki I/Collection: Closing Collection Log
2021-04-14 14:41:26.487 28210-28210/com.ichi2.anki I/Collection: Collection closed
2021-04-14 14:41:26.487 28210-28210/com.ichi2.anki I/NavigationDrawerActivity: AnkiActivity -- restartActivityInvalidateBackstack()
2021-04-14 14:41:26.493 28210-28648/com.ichi2.anki I/CollectionHelper: Begin openCollection: /storage/emulated/0/AnkiDroidA/collection.anki2
2021-04-14 14:41:26.494 28210-28648/com.ichi2.anki D/RustSupportSQLiteOpenHelper: createRustSupportSQLiteDatabase
2021-04-14 14:41:26.519 28210-28210/com.ichi2.anki I/AnkiActivity: finishWithoutAnimation
2021-04-14 14:41:26.522 28210-28210/com.ichi2.anki I/AnkiActivity: AnkiActivity::onResume - Reviewer
2021-04-14 14:41:26.523 28210-28210/com.ichi2.anki D/UsageAnalytics: sendAnalyticsScreenView(): Reviewer
2021-04-14 14:41:26.523 28210-28210/com.ichi2.anki D/UsageAnalytics: getOptIn() status: false
2021-04-14 14:41:26.524 28210-28210/com.ichi2.anki D/DialogHandler: Reading persistent message
2021-04-14 14:41:26.524 28210-28210/com.ichi2.anki E/Reviewer: Could not set title in reviewer because collection closed
2021-04-14 14:41:26.536 28210-28210/com.ichi2.anki D/Reviewer: Fullscreen delayed hide in 100ms
2021-04-14 14:41:26.536 28210-28210/com.ichi2.anki D/AbstractFlashcardViewer: displayCardQuestion()
2021-04-14 14:41:26.561 28210-28210/com.ichi2.anki D/AbstractFlashcardViewer: Focusable = true, Focusable in touch mode = false
2021-04-14 14:41:26.563 28210-28210/com.ichi2.anki I/ViewGroupUtils: ViewGroupUtils::setRenderWorkaround - using default / hardware rendering
2021-04-14 14:41:26.697 28210-28648/com.ichi2.anki I/Collection: Opening Collection Log
2021-04-14 14:41:26.700 28210-28648/com.ichi2.anki D/Collection: [1618407686] Collection.java:<init>(): /storage/emulated/0/AnkiDroidA/collection.anki2,  2.15alpha40
2021-04-14 14:41:26.716 28210-28648/com.ichi2.anki I/NativeMethods: ExecuteCommand: localMinutesWest
2021-04-14 14:41:26.718 28210-28648/com.ichi2.anki D/Collection: [1618407686] SchedV2.java:_updateCutoff(): 32,  1618455600
2021-04-14 14:41:26.719 28210-28648/com.ichi2.anki I/NativeMethods: ExecuteCommand: localMinutesWest
2021-04-14 14:41:26.720 28210-28648/com.ichi2.anki I/CollectionHelper: End openCollection: /storage/emulated/0/AnkiDroidA/collection.anki2
2021-04-14 14:41:26.720 28210-28648/com.ichi2.anki I/NativeMethods: ExecuteCommand: localMinutesWest
2021-04-14 14:41:26.720 28210-28210/com.ichi2.anki D/AbstractFlashcardViewer: updateCard()
2021-04-14 14:41:26.721 28210-28210/com.ichi2.anki D/Sound: expandSounds
2021-04-14 14:41:26.722 28210-28210/com.ichi2.anki D/AbstractFlashcardViewer: base url = file:///storage/emulated/0/AnkiDroidA/collection.media/
2021-04-14 14:41:26.722 28210-28210/com.ichi2.anki D/AbstractFlashcardViewer: fillFlashcard()
2021-04-14 14:41:26.722 28210-28210/com.ichi2.anki D/AbstractFlashcardViewer: base url = file:///storage/emulated/0/AnkiDroidA/collection.media/
2021-04-14 14:41:26.737 28210-28210/com.ichi2.anki I/NativeMethods: ExecuteCommand: localMinutesWest
2021-04-14 14:41:26.739 28210-28210/com.ichi2.anki D/AndroidRuntime: Shutting down VM
2021-04-14 14:41:26.742 28210-28210/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 28210
    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.ichi2.libanki.DB.queryScalar(java.lang.String, java.lang.Object[])' on a null object reference
        at com.ichi2.libanki.sched.SchedV2._resetLrnCount(SchedV2.java:1042)
        at com.ichi2.libanki.sched.SchedV2.resetCounts(SchedV2.java:247)
        at com.ichi2.libanki.sched.SchedV2.resetCounts(SchedV2.java:227)
        at com.ichi2.libanki.sched.SchedV2.counts(SchedV2.java:361)
        at com.ichi2.libanki.sched.SchedV2.counts(SchedV2.java:357)
        at com.ichi2.libanki.sched.SchedV2.counts(SchedV2.java:373)
        at com.ichi2.anki.Reviewer.updateScreenCounts(Reviewer.java:939)
        at com.ichi2.anki.Reviewer.updateActionBar(Reviewer.java:932)
        at com.ichi2.anki.AbstractFlashcardViewer.updateForNewCard(AbstractFlashcardViewer.java:1914)
        at com.ichi2.anki.AbstractFlashcardViewer.fillFlashcard(AbstractFlashcardViewer.java:2441)
        at com.ichi2.anki.Reviewer.fillFlashcard(Reviewer.java:978)
        at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:2288)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:2058)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:2017)
        at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:990)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:637)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:616)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:604)
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:213)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:791)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

</details>

The issue is:

* onCreate -> startLoadingCollection -> collection is open -> onCollectionLoaded
* onActivityResult -> collection is changed -> close collection -> crash due to `onCollectionLoaded` still executing in the background
