### ISSUE TITLE
Adding leak canary 

### ISSUE THREAD

**Issue by mrudultora** [ankidroid/Anki-Android#8436]
**Is your feature request related to a problem? Please describe.**
We don't know if there are any memory leaks in the app.

**Describe the solution you'd like**
Integrating [LeakCanary](https://github.com/square/leakcanary) library to detect any memory leaks if present.

**Describe alternatives you've considered**
None

**Comment by mrudultora** [comment]
As discussed on discord, I am taking this up, if maintainers agree.

**Comment by mikehardy** [comment]
I like this idea - but can you make sure you implement this part as well:

https://square.github.io/leakcanary/recipes/#matching-known-library-leaks

It does not need to have any entries that we already know about but:

1. if the leak detection is noisy, people will turn it off, so it should only flag *new things*
2. in order to only flag new things we need to match things we already know about (even if not fixed yet!) and not show notifications for them
3. similar to the deprecation issues here in the issues list already, then we can add a matcher for a known leak with a reference to an issue created here for it (labeled as "LeakCanary" I guess?) and then we can prioritize and triage these things in a systematic way

Does that make sense? Would probably be best to add a section about LeakCanary outlining the same in the Development Guide so future people know how to handle it

Definitely only in debug builds - their warnings about including it in release were important - definitely not recommended

**Comment by mrudultora** [comment]
I will try to implement in this way.

**Comment by david-allison-1** [comment]
I tried to do this a while ago. It'll be useful

**Comment by mrudultora** [comment]
I tried it on the day I commented on this thread, but was unable to do it in the way Mike suggested😅. Apologies, as I didn't mentioned that here.

**Comment by mikehardy** [comment]
I am shocked my vague descriptions, including no actual code or even pseudo-code, do not work immediately! :laughing:

**Comment by david-allison-1** [comment]
Had a failure notification:

```
java.io.FileNotFoundException: /storage/emulated/0/Download/leakcanary-com.ichi2.anki/2022-01-04_16-56-29_809.hprof: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:492)
		at java.io.FileInputStream.<init>(FileInputStream.java:160)
			at shark.FileSourceProvider.openStreamingSource(FileSourceProvider.kt:10)
				at shark.ConstantMemoryMetricsDualSourceProvider.openStreamingSource(ConstantMemoryMetricsDualSourceProvider.kt:48)
					at shark.HprofHeapGraph$Companion.openHeapGraph(HprofHeapGraph.kt:396)
						at shark.HprofHeapGraph$Companion.openHeapGraph$default(HprofHeapGraph.kt:394)
							at shark.HeapAnalyzer.analyze(HeapAnalyzer.kt:98)
								at leakcanary.internal.HeapAnalyzerService.analyzeHeap(HeapAnalyzerService.kt:87)
									at leakcanary.internal.HeapAnalyzerService.onHandleIntentInForeground(HeapAnalyzerService.kt:61)
										at leakcanary.internal.ForegroundService.onHandleIntent(ForegroundService.kt:55)
											at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:77)
												at android.os.Handler.dispatchMessage(Handler.java:106)
													at android.os.Looper.loop(Looper.java:223)
														at android.os.HandlerThread.run(HandlerThread.java:67)
														Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
															at libcore.io.Linux.open(Native Method)
																at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
																	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
																		at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
																			at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7550)
																				at libcore.io.IoBridge.open(IoBridge.java:478)
																					... 13 more
Build.VERSION.SDK_INT: 30
Build.MANUFACTURER: Google
LeakCanary version: 2.7
Analysis duration: 21 ms
Heap dump file path: /storage/emulated/0/Download/leakcanary-com.ichi2.anki/2022-01-04_16-56-29_809.hprof
Heap dump timestamp: 1641315395089
```

**Comment by mikehardy** [comment]
@david-allison-1 check out this and most importantly the 1801 referenced from it https://github.com/square/leakcanary/issues/2174 - what a mess! And it's exactly around what you are doing (moving target sdk versions with existing installs etc) - I'm not sure exactly how to mitigate this :-/ - it appears difficult to reproduce (involving specific local device state) and possibly depends on a combination of emulator/device android image version + target sdk ?

Seems it should be a new issue

**Comment by david-allison-1** [comment]
I'll fill in their report so they can debug.

I'm also getting a "Leaks" app installed, we'll need to confirm that this doesn't occur on a release build
