### ISSUE TITLE
Unit test debugging failing - java.lang.NoClassDefFoundError: kotlin/Result

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8476]
Running tests for Robolectric works, debugging now fails. Only one relevant Google result, so posting here to consolidate discussion

```
"C:\Program Files\Android\Android Studio\jre\bin\java.exe" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:53857,suspend=y,server=n -ea -javaagent:C:\Users\David\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\kotlinx-coroutines-core-jvm\1.4.1\936067d1e0195f638396f60e71da745bb14a35ca\kotlinx-coroutines-core-jvm-1.4.1.jar -Didea.test.cyclic.buffer.size=1048576 -javaagent:C:\Users\David\AppData\Local\Google\AndroidStudio4.1\groovyHotSwap\gragent.jar -javaagent:C:\Users\David\AppData\Local\Google\AndroidStudio4.1\captureAgent\debugger-agent.jar=file:/C:/Users/David/AppData/Local/Temp/capture74280.props -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Android\Android Studio\lib\idea_rt.jar" com.intellij.rt.execution.CommandLineWrapper C:\Users\David\AppData\Local\Temp\idea_classpath1343004246 com.intellij.rt.junit.JUnitStarter -ideVersion5 -junit4 com.ichi2.anki.BackendEmulatingOpenConflictTest
Connected to the target VM, address: '127.0.0.1:53857', transport: 'socket'
java.lang.NoClassDefFoundError: kotlin/Result
	at kotlinx.coroutines.debug.AgentPremain.<clinit>(AgentPremain.kt:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
FATAL ERROR in native method: processing of -javaagent failed
Disconnected from the target VM, address: '127.0.0.1:53857', transport: 'socket'

Process finished with exit code 1
Exception in thread "main" 
```

**Comment by david-allison-1** [comment]
```
PS C:\Program Files\Android\Android Studio\jre\bin> java --version
java 11.0.8 2020-07-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)
PS C:\Program Files\Android\Android Studio\jre\bin>
```

**Comment by david-allison-1** [comment]
Fixed

* Downloaded JDK 11.0.10
* Switched
* Switched Back
* Changed commandline handling from `classpath file` (likely fix):
![image](https://user-images.githubusercontent.com/62114487/113524476-db393000-95a6-11eb-8a25-b8a803b9ef1a.png)
