### ISSUE TITLE
[Bug] BackendException$BackendDbException$BackendDbLockedException

### ISSUE THREAD

**Issue by TarekkMA** [ankidroid/Anki-Android#8494]
`net.ankiweb.rsdroid.BackendException$BackendDbException$BackendDbLockedException` did start to show up in CI and locally after I rebased with master.

Some of the tests that was running with no issue are now failing because of this.

<details>

<summary> Logs </summary>

```
com.ichi2.anki.DeckPickerTest > databaseLockedNoPermissionIntegrationTest FAILED
    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
        at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

        Caused by:
        net.ankiweb.rsdroid.BackendException$BackendDbException$BackendDbLockedException
            at com.ichi2.testutils.BackendEmulatingOpenConflict.openCollectionDatabase(BackendEmulatingOpenConflict.java:58)
            at com.ichi2.libanki.Storage.Collection(Storage.java:76)
            at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:131)
            at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:113)
            at com.ichi2.anki.AnkiActivity.getCol(AnkiActivity.java:156)
            at com.ichi2.anki.DeckPicker.onCreate(DeckPicker.java:453)
            at android.app.Activity.performCreate(Activity.java:7136)
            at android.app.Activity.performCreate(Activity.java:7127)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
            at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:711)
            at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:106)
            at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:200)
            at org.robolectric.android.controller.ActivityController.create(ActivityController.java:106)
            at org.robolectric.android.controller.ActivityController.create(ActivityController.java:111)
            at com.ichi2.anki.RobolectricTest.startActivityNormallyOpenCollectionWithIntent(RobolectricTest.java:311)
            at com.ichi2.anki.RobolectricTest.startActivityNormallyOpenCollectionWithIntent(RobolectricTest.java:319)
            at com.ichi2.anki.DeckPickerTest.databaseLockedNoPermissionIntegrationTest(DeckPickerTest.java:235)

com.ichi2.anki.DeckPickerTest > databaseLockedWithPermissionIntegrationTest FAILED
    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
        at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

        Caused by:
        net.ankiweb.rsdroid.BackendException$BackendDbException$BackendDbLockedException
            at com.ichi2.testutils.BackendEmulatingOpenConflict.openCollectionDatabase(BackendEmulatingOpenConflict.java:58)
            at com.ichi2.libanki.Storage.Collection(Storage.java:76)
            at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:131)
            at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:113)
            at com.ichi2.anki.AnkiActivity.getCol(AnkiActivity.java:156)
            at com.ichi2.anki.DeckPicker.onCreate(DeckPicker.java:453)
            at android.app.Activity.performCreate(Activity.java:7136)
            at android.app.Activity.performCreate(Activity.java:7127)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
            at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:711)
            at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:106)
            at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:200)
            at org.robolectric.android.controller.ActivityController.create(ActivityController.java:106)
            at org.robolectric.android.controller.ActivityController.create(ActivityController.java:111)
            at com.ichi2.anki.RobolectricTest.startActivityNormallyOpenCollectionWithIntent(RobolectricTest.java:311)
            at com.ichi2.anki.RobolectricTest.startActivityNormallyOpenCollectionWithIntent(RobolectricTest.java:319)
            at com.ichi2.anki.DeckPickerTest.databaseLockedWithPermissionIntegrationTest(DeckPickerTest.java:217)
```

</details>

**Comment by david-allison-1** [comment]
Answered in discord: 

> You're calling `getCol` before `onCollectionLoaded` (I believe use `onFinishedStartup` in `DeckPicker`).
