### ISSUE TITLE
[Bug] StorageAccessExceptions on first-time startup in DeckPicker

### ISSUE THREAD

**Issue by farjadilyas** [ankidroid/Anki-Android#8618]
###### Reproduction Steps

1. Clear App data
2. Open the app

###### Expected Result
No exceptions are thrown

###### Actual Result
Three StorageAccess Exceptions are thrown & caught in the following methods in DeckPicker:
- onPause()
- onPrepareOptionsMenu()
- onCreateOptionsMenu()

###### Debug info

Log:
```
2021-04-15 00:26:32.232 28331-28331/com.ichi2.anki D/DeckPicker: No DeckPicker background preference
2021-04-15 00:26:32.242 28331-28331/com.ichi2.anki I/AnkiActivity: AnkiActivity::onStart - DeckPicker
2021-04-15 00:26:32.382 28331-28331/com.ichi2.anki I/ViewRootImpl@e8af28d[DeckPicker]: stopped(false) old=false
2021-04-15 00:26:32.382 28331-28331/com.ichi2.anki D/DeckPicker: onResume()
2021-04-15 00:26:32.382 28331-28331/com.ichi2.anki I/AnkiActivity: AnkiActivity::onResume - DeckPicker
2021-04-15 00:26:32.383 28331-28331/com.ichi2.anki D/UsageAnalytics: sendAnalyticsScreenView(): DeckPicker
2021-04-15 00:26:32.383 28331-28331/com.ichi2.anki D/UsageAnalytics: getOptIn() status: false
2021-04-15 00:26:32.385 28331-28331/com.ichi2.anki D/DialogHandler: Reading persistent message
2021-04-15 00:26:32.399 28331-28331/com.ichi2.anki D/InputTransport: Input channel constructed: 'c50fbc5', fd=77
2021-04-15 00:26:32.400 28331-28331/com.ichi2.anki I/ViewRootImpl@823f486[DeckPicker]: setView = com.android.internal.policy.DecorView@4818251 TM=true
2021-04-15 00:26:32.423 28331-28331/com.ichi2.anki I/Choreographer: Skipped 36 frames!  The application may be doing too much work on its main thread.
2021-04-15 00:26:32.482 28331-30468/com.ichi2.anki E/CollectionHelper: Could not initialize AnkiDroid directory
    com.ichi2.anki.exception.StorageAccessException: No write access to AnkiDroid directory /storage/emulated/0/AnkiDroid
        at com.ichi2.anki.CollectionHelper.initializeAnkiDroidDirectory(CollectionHelper.java:208)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:124)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:114)
        at com.ichi2.anki.CollectionHelper.getColSafe(CollectionHelper.java:156)
        at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:189)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:157)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:102)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2021-04-15 00:26:32.483 28331-30468/com.ichi2.anki E/CollectionTask: CollectionTask CollectionTask class com.ichi2.async.CollectionTask$LoadCollectionComplete as Collection could not be opened
2021-04-15 00:26:32.487 28331-28331/com.ichi2.anki I/SurfaceControl: assignNativeObject: nativeObject = 0 Surface(name=null)/@0x889870c / android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1820 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9965 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
2021-04-15 00:26:32.490 28331-28331/com.ichi2.anki I/ViewRootImpl@e8af28d[DeckPicker]: Relayout returned: old=(0,63,1080,2361) new=(74,737,1006,1686) req=(932,949)0 dur=10 res=0x7 s={true 516396981488} ch=true fn=-1
2021-04-15 00:26:32.493 28331-28331/com.ichi2.anki D/ScrollView:  onsize change changed 
2021-04-15 00:26:32.554 28331-30397/com.ichi2.anki I/OpenGLRenderer: Davey! duration=731ms; Flags=1, IntendedVsync=248675695351427, Vsync=248676295351403, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=248676297528624, AnimationStart=248676297541385, PerformTraversalsStart=248676297547374, DrawStart=248676373009510, SyncQueued=248676384008520, SyncStart=248676385522999, IssueDrawCommandsStart=248676386248989, SwapBuffers=248676427466593, FrameCompleted=248676428375708, DequeueBufferDuration=209896, QueueBufferDuration=547656, GpuCompleted=0, 
2021-04-15 00:26:32.587 28331-28331/com.ichi2.anki I/SurfaceControl: assignNativeObject: nativeObject = 0 Surface(name=null)/@0x2f83d0d / android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1820 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9965 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
2021-04-15 00:26:32.588 28331-28331/com.ichi2.anki I/ViewRootImpl@823f486[DeckPicker]: Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) req=(1080,2400)0 dur=10 res=0x7 s={true 516396998928} ch=true fn=-1
2021-04-15 00:26:32.766 28331-30397/com.ichi2.anki I/OpenGLRenderer: Davey! duration=943ms; Flags=1, IntendedVsync=248675695351427, Vsync=248676295351403, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=248676297528624, AnimationStart=248676297541385, PerformTraversalsStart=248676297547374, DrawStart=248676583869978, SyncQueued=248676590816853, SyncStart=248676591273937, IssueDrawCommandsStart=248676591497843, SwapBuffers=248676639122582, FrameCompleted=248676639773051, DequeueBufferDuration=117396, QueueBufferDuration=320521, GpuCompleted=0, 
2021-04-15 00:26:32.771 28331-28331/com.ichi2.anki I/SurfaceControl: release : mNativeObject = 512102085552 - Surface(name=Surface(name=c14d39c NavigationBar0)/@0xea2faf4 - animation-leash)/@0x72856b3 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833 
2021-04-15 00:26:32.771 28331-28331/com.ichi2.anki I/SurfaceControl: nativeRelease nativeObject s[512102085552]
2021-04-15 00:26:32.771 28331-28331/com.ichi2.anki I/SurfaceControl: nativeRelease nativeObject e[512102085552]
2021-04-15 00:26:32.772 28331-28331/com.ichi2.anki I/SurfaceControl: release : mNativeObject = 512102084672 - Surface(name=Surface(name=5d7d691 StatusBar)/@0xf9f18e1 - animation-leash)/@0x809a470 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833 
2021-04-15 00:26:32.772 28331-28331/com.ichi2.anki I/SurfaceControl: nativeRelease nativeObject s[512102084672]
2021-04-15 00:26:32.772 28331-28331/com.ichi2.anki I/SurfaceControl: nativeRelease nativeObject e[512102084672]
2021-04-15 00:26:32.804 28331-28331/com.ichi2.anki I/SurfaceControl: release : mNativeObject = 512102062496 - Surface(name=com.ichi2.anki/com.ichi2.anki.DeckPicker$_28331)/@0x8a645a5 / android.view.SurfaceControl.assignNativeObject:567 android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1810 android.view.ViewRootImpl.relayoutWindow:9005 
2021-04-15 00:26:32.804 28331-28331/com.ichi2.anki I/SurfaceControl: nativeRelease nativeObject s[512102062496]
2021-04-15 00:26:32.804 28331-28331/com.ichi2.anki I/SurfaceControl: nativeRelease nativeObject e[512102062496]
2021-04-15 00:26:32.805 28331-28331/com.ichi2.anki I/SurfaceControl: assignNativeObject: nativeObject = 0 Surface(name=null)/@0x2f83d0d / android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1820 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9965 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
2021-04-15 00:26:32.806 28331-28331/com.ichi2.anki I/ViewRootImpl@823f486[DeckPicker]: Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) req=(1080,2400)0 dur=9 res=0x1 s={true 516396998928} ch=false fn=3
2021-04-15 00:26:32.811 28331-28331/com.ichi2.anki D/CollectionTask: enabling garbage collection of mPreviousTask...
2021-04-15 00:26:32.822 28331-28331/com.ichi2.anki D/DeckPicker: onCreateOptionsMenu()
2021-04-15 00:26:32.885 28331-28331/com.ichi2.anki E/CollectionHelper: Could not initialize AnkiDroid directory
    com.ichi2.anki.exception.StorageAccessException: No write access to AnkiDroid directory /storage/emulated/0/AnkiDroid
        at com.ichi2.anki.CollectionHelper.initializeAnkiDroidDirectory(CollectionHelper.java:208)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:124)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:114)
        at com.ichi2.anki.AnkiActivity.getCol(AnkiActivity.java:156)
        at com.ichi2.anki.-$$Lambda$NTwMYMQYtVCa70hV6wZWdM4H02Q.get(Unknown Source:2)
        at com.ichi2.utils.SyncStatus.getSyncStatus(SyncStatus.java:44)
        at com.ichi2.anki.DeckPicker.displaySyncBadge(DeckPicker.java:733)
        at com.ichi2.anki.DeckPicker.onCreateOptionsMenu(DeckPicker.java:687)
        at android.app.Activity.onCreatePanelMenu(Activity.java:4263)
        at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:287)
        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3084)
        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
2021-04-15 00:26:32.890 28331-28331/com.ichi2.anki D/BadgeDrawableBuilder: Adding badge
2021-04-15 00:26:32.908 28331-28331/com.ichi2.anki E/CollectionHelper: Could not initialize AnkiDroid directory
    com.ichi2.anki.exception.StorageAccessException: No write access to AnkiDroid directory /storage/emulated/0/AnkiDroid
        at com.ichi2.anki.CollectionHelper.initializeAnkiDroidDirectory(CollectionHelper.java:208)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:124)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:114)
        at com.ichi2.anki.CollectionHelper.getColSafe(CollectionHelper.java:156)
        at com.ichi2.anki.DeckPicker.onPrepareOptionsMenu(DeckPicker.java:668)
        at android.app.Activity.onPreparePanel(Activity.java:4281)
        at androidx.fragment.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:485)
        at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:470)
        at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3111)
        at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
        at androidx.appcompat.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:523)
        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:457)
        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
```

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum

###### Additional Comments
This has been present for a while but due to the DeckPicker startup flow being improved by #8561, this can now easily be handled

**Comment by farjadilyas** [comment]
I'd like to work on this if it's accepted

**Comment by david-allison-1** [comment]
Sounds good! Unit test to ensure that the code path isn't hit would be fantastic

**Comment by farjadilyas** [comment]
@david-allison-1 Roboelectric Tests are failing due to the [dependent libraries issue](https://github.com/david-allison-1/Anki-Android-Backend/issues/46). I tried installing gcc using MinGW but it didn't help. Any ideas?

**Comment by david-allison-1** [comment]
> @david-allison-1 Roboelectric Tests are failing due to the [dependent libraries issue](https://github.com/david-allison-1/Anki-Android-Backend/issues/46). I tried installing gcc using MinGW but it didn't help. Any ideas?

What happens if you run the attached powershell script?

I'll look into this closely tomorrow. This needs to be sorted

**Comment by farjadilyas** [comment]
@david-allison-1 Yes, it says ```libgcc_s_seh-1.dll``` is missing. Didn't get fixed after installing gcc though. I've switched to macOS for now to work on tests.

**Comment by mikehardy** [comment]
@farjadilyas this isn't something you just want to change quickly, but as a multi-platform mobile developer I do Ubuntu on the bare metal then windows VM and https://github.com/kholia/OSX-KVM for most work. When I have to use a real iOS device (some things do require it of course) I have a real (but crappy) macOS laptop. But pretty much all the time it's the Ubuntu rig with VMs. VSCode has a pretty cool remote dev experience that lets you run VSCode natively on Ubuntu but it ssh's in to the OSX VM for that work.

Probably not useful in this case, or even if so not immediately, but I've been doing it this way for a year now and it's been quite nice.

**Comment by farjadilyas** [comment]
@mikehardy That's cool! especially the macOS KVM. At the moment I've got the opposite setup :D Windows & macOS dual boot w/two disks & ubuntu VM on Windows.
