### ISSUE TITLE
[Bug] Crash selecting "All Decks"

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8770]
* Card Browser - Select "All Decks" - Crash
*
```
2021-05-04 16:39:39.398 4698-4862/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.ichi2.anki, PID: 4698
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:415)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.ichi2.utils.JSONArray com.ichi2.libanki.Model.getJSONArray(java.lang.String)' on a null object reference
        at com.ichi2.libanki.Models.fieldMap(Models.java:438)
        at com.ichi2.libanki.Note.load(Note.java:99)
        at com.ichi2.libanki.Note.<init>(Note.java:63)
        at com.ichi2.libanki.Collection.getNote(Collection.java:513)
        at com.ichi2.libanki.Card.note(Card.java:314)
        at com.ichi2.libanki.Card.note(Card.java:308)
        at com.ichi2.anki.CardBrowser$CardCache.load(CardBrowser.java:2608)
        at com.ichi2.async.CollectionTask$SearchCards.task(CollectionTask.java:1167)
        at com.ichi2.async.CollectionTask$SearchCards.task(CollectionTask.java:1130)
        at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:198)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:161)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:102)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
```

**Comment by david-allison-1** [comment]
`SELECT guid, mid, mod, usn, tags, flds, flags, data FROM notes WHERE id = ?`

````
0 = {Sqlite$SqlValue@18881} "stringValue: "k$N$C"\n"
1 = {Sqlite$SqlValue@18882} "longValue: 1616858015048\n"
2 = {Sqlite$SqlValue@18883} "longValue: 1616858015\n"
3 = {Sqlite$SqlValue@18884} "longValue: -1\n"
4 = {Sqlite$SqlValue@18885} "stringValue: " aldskfhewjklhfczmxkjshf "\n"
5 = {Sqlite$SqlValue@18886} "stringValue: "Front\037Back"\n"
6 = {Sqlite$SqlValue@18887} "longValue: 0\n"
7 = {Sqlite$SqlValue@18888} "stringValue: ""\n"
````

aldskfhewjklhfczmxkjshf  looks like it comes from `ContentProviderTest.java` :/

**Comment by david-allison-1** [comment]
Card was associated with a model that no longer existed

**Comment by mikehardy** [comment]
I suppose that would best be handled by the corrupt database / run check database dialog path, I believe check database will detect notes with missing models?

**Comment by mikehardy** [comment]
Should be ...sort of easy to produce in a test case by direct manipulation of the model objects to create the invalid structure then attempt to load the activity via robolectric

**Comment by david-allison-1** [comment]
I'm fairly sure we can close this - it should be fixed by check database
