### ISSUE TITLE
Crash 2.15alpha49 Tags list editor

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8807]
###### Reproduction Steps

@TarekkMA I think this might be your area? :thinking: 

Here's the logcat from the crash report showing user path roughly

```


05-10 19:24:31.948 I/AnkiDroid(22524): AnkiActivity::onStop - DeckPicker
--
2 | 05-10 19:24:31.965 I/AnkiDroid(22524): Rust: executeGetRowsAffected UPDATE col SET decks=?,dconf=?
3 | 05-10 19:24:31.980 I/AnkiDroid(22524): flush - Saving information to DB...
4 | 05-10 19:24:31.981 I/AnkiDroid(22524): Rust: executeGetRowsAffected UPDATE col SET mod=?,scm=?,crt=?,dty=?,conf=?,usn=?,ls=?
5 | 05-10 19:24:35.994 I/AnkiDroid(22524): AbstractFlashcardViewer:: EASE_4 pressed
6 | 05-10 19:24:36.010 I/AnkiDroid(22524): Answering card 1620057434432
7 | 05-10  19:24:36.033 I/AnkiDroid(22524): Rust: executeGetRowsAffected UPDATE  cards SET  mod=?,due=?,queue=?,ivl=?,factor=?,reps=?,did=?,left=?,lapses=?,usn=?,type=?,odid=?,odue=?  WHERE id = ?
8 | 05-10 19:24:36.069 I/AnkiDroid(22524): Obtaining card
9 | 05-10 19:24:36.162 I/AnkiDroid(22524): ViewGroupUtils::setRenderWorkaround - software render requested, altering Views...
10 | 05-10 19:24:36.181 I/AnkiDroid(22524): AbstractFlashcardViewer:: Question successfully shown for card id 1620630770452
11 | 05-10 19:24:46.528 I/AnkiDroid(22524): AbstractFlashcardViewer:: EASE_1 pressed
12 | 05-10 19:24:46.543 I/AnkiDroid(22524): Answering card 1620630770452
13 | 05-10  19:24:46.565 I/AnkiDroid(22524): Rust: executeGetRowsAffected UPDATE  cards SET  mod=?,due=?,queue=?,ivl=?,factor=?,reps=?,did=?,left=?,lapses=?,usn=?,type=?,odid=?,odue=?  WHERE id = ?
14 | 05-10 19:24:46.578 I/AnkiDroid(22524): Obtaining card
15 | 05-10 19:24:46.679 I/AnkiDroid(22524): ViewGroupUtils::setRenderWorkaround - software render requested, altering Views...
16 | 05-10 19:24:46.695 I/AnkiDroid(22524): AbstractFlashcardViewer:: Question successfully shown for card id 1620631842916
17 | 05-10 19:24:54.434 I/AnkiDroid(22524): AbstractFlashcardViewer:: Show answer button pressed
18 | 05-10 19:24:59.289 I/AnkiDroid(22524): Reviewer:: Edit note button pressed
19 | 05-10 19:24:59.344 I/AnkiDroid(22524): AnkiActivity::onPause - Reviewer
20 | 05-10 19:24:59.399 I/AnkiDroid(22524): AnkiActivity::onCreate - NoteEditor
21 | 05-10 19:24:59.474 E/AnkiDroid(22524): DeckSpinnerSelection/ updateDeckPosition() error :: mCurrentDid=0, position=-1
22 | 05-10 19:24:59.507 I/AnkiDroid(22524): onCollectionLoaded() Edit note activity successfully started with card id 1620631842916
23 | 05-10 19:24:59.509 I/AnkiDroid(22524): AnkiActivity::onStart - NoteEditor
24 | 05-10 19:24:59.516 I/AnkiDroid(22524): AnkiActivity::onResume - NoteEditor
25 | 05-10 19:24:59.530 I/AnkiDroid(22524): Disabling Extended Text UI
26 | 05-10 19:24:59.533 I/AnkiDroid(22524): Disabling Extended Text UI
27 | 05-10 19:24:59.724 I/AnkiDroid(22524): Disabling Extended Text UI
28 | 05-10 19:24:59.727 I/AnkiDroid(22524): Disabling Extended Text UI
29 | 05-10 19:24:59.823 I/AnkiDroid(22524): AnkiActivity::onStop - Reviewer
30 | 05-10 19:24:59.838 I/AnkiDroid(22524): Rust: executeGetRowsAffected UPDATE col SET decks=?,dconf=?
31 | 05-10 19:24:59.853 I/AnkiDroid(22524): flush - Saving information to DB...
32 | 05-10 19:24:59.854 I/AnkiDroid(22524): Rust: executeGetRowsAffected UPDATE col SET mod=?,scm=?,crt=?,dty=?,conf=?,usn=?,ls=?
33 | 05-10 19:25:32.163 I/AnkiDroid(22524): NoteEditor:: Tags button pressed... opening tags editor


```

###### Expected Result

display tags list editor

###### Actual Result

```
java.lang.UnsupportedOperationException: ListIterator does not support set
at org.apache.commons.collections4.list.SetUniqueList$SetListListIterator.set(SetUniqueList.java:1)
at java.util.Collections.sort(Collections.java:247)
at com.ichi2.anki.dialogs.tags.TagsList.sort(TagsList.java:1)
at com.ichi2.anki.dialogs.tags.TagsArrayAdapter.sortData(TagsArrayAdapter.java:1)
at com.ichi2.anki.dialogs.tags.TagsArrayAdapter.<init>(TagsArrayAdapter.java:4)
at com.ichi2.anki.dialogs.tags.TagsDialog.onCreateDialog(TagsDialog.java:6)
at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:4)
at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:3)
at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:4)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:20)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:34)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:4)
at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:1)
at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:8)
at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:1)
at com.ichi2.anki.NoteEditor.showTagsDialog(NoteEditor.java:6)
at com.ichi2.anki.NoteEditor.lambda$onCollectionLoaded$2(NoteEditor.java:2)
at com.ichi2.anki.NoteEditor.l(NoteEditor.java)
at com.ichi2.anki.s5.onClick(lambda)
at android.view.View.performClick(View.java:5706)
at android.view.View$PerformClick.run(View.java:22834)
at android.os.Handler.handleCallback(Handler.java:836)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:203)
at android.app.ActivityThread.main(ActivityThread.java:6339)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
```

###### Debug info

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/572f850e-643d-4aff-8c41-3621744286e7

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
You can make the robolectric runner run a test against multiple versions if you have SDK skew in the logic - it's a neat trick:

https://github.com/ankidroid/Anki-Android/blob/eb85b0dcc44c9c60e8f04c8461f5c334ec438068/AnkiDroid/src/test/java/com/ichi2/compat/CompatCopyFileTest.java#L39

Right now it uses 28 if unspecified but we'll be able to bump that up soon now that we are using Java 11 in most places and have our toolchain default expectations working with gradle 7 / android studio 4.2

https://github.com/ankidroid/Anki-Android/blob/eb85b0dcc44c9c60e8f04c8461f5c334ec438068/AnkiDroid/src/test/resources/robolectric.properties#L3
