### ISSUE TITLE
Crash 2.15.0beta1 CardBrowser DeckSelectionDialog

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8815]
###### Reproduction Steps

Logcat from ACRA crash

```


-------- beginning of main
--
1 | 05-13 03:34:42.170 I/AnkiDroid(22906): Updating deck list UI
2 | 05-13 03:34:42.415 I/AnkiDroid(22906): Updating deck list UI
3 | 05-13 03:34:44.124 I/AnkiDroid(22906): Pull to Sync: Syncing
4 | --------- beginning of system
5 | 05-13 03:34:44.153 I/AnkiDroid(22906): Locked Collection - Collection Loading should fail
6 | 05-13 03:34:44.154 I/AnkiDroid(22906): Sync - starting sync
7 | 05-13 03:34:44.155 I/AnkiDroid(22906): ExecuteCommand: localMinutesWest
8 | 05-13 03:34:50.899 I/AnkiDroid(22906): Rust: transaction begin
9 | 05-13 03:34:50.900 I/AnkiDroid(22906): Sync: getting meta data from server
10 | 05-13 03:34:50.904 I/AnkiDroid(22906): Sync: building local meta data
11 | 05-13 03:34:52.096 I/AnkiDroid(22906): Sync: collection removed data
12 | 05-13 03:34:52.097 I/AnkiDroid(22906): Sync: sending and receiving removed data
13 | 05-13 03:34:55.189 I/AnkiDroid(22906): Sync: applying removed data
14 | 05-13 03:34:55.189 I/AnkiDroid(22906): Sync: collection small changes
15 | 05-13 03:34:55.203 I/AnkiDroid(22906): Sync: sending and receiving small changes
16 | 05-13 03:34:59.298 I/AnkiDroid(22906): Sync: merging small changes
17 | 05-13 03:34:59.321 I/AnkiDroid(22906): Sync: downloading chunked data
18 | 05-13 03:35:02.258 I/AnkiDroid(22906): Sync: applying chunked data
19 | 05-13 03:35:02.296 I/AnkiDroid(22906): Sync: collecting chunked data
20 | 05-13 03:35:02.298 I/AnkiDroid(22906): Sync: sending chunked data
21 | 05-13 03:35:05.520 I/AnkiDroid(22906): ExecuteCommand: localMinutesWest
22 | 05-13 03:35:05.522 I/AnkiDroid(22906): ExecuteCommand: localMinutesWest
23 | 05-13 03:35:08.249 I/AnkiDroid(22906): Sync: sending finish command
24 | 05-13 03:35:11.255 I/AnkiDroid(22906): Sync: finishing
25 | 05-13 03:35:11.284 I/AnkiDroid(22906): Rust: executeGetRowsAffected UPDATE col SET models=?
26 | 05-13 03:35:11.326 I/AnkiDroid(22906): Rust: executeGetRowsAffected UPDATE col SET dconf=?,decks=?
27 | 05-13 03:35:11.371 I/AnkiDroid(22906): Rust: executeGetRowsAffected UPDATE col SET tags=?
28 | 05-13 03:35:11.408 I/AnkiDroid(22906): flush - Saving information to DB...
29 | 05-13 03:35:11.409 I/AnkiDroid(22906): Rust: executeGetRowsAffected UPDATE col SET ls=?,crt=?,dty=?,mod=?,scm=?,usn=?,conf=?
30 | 05-13 03:35:11.418 I/AnkiDroid(22906): Rust: transaction commit
31 | 05-13 03:35:11.528 I/AnkiDroid(22906): Sync - Performing media sync
32 | 05-13 03:35:17.121 I/AnkiDroid(22906): Sync Finished - Closing Collection
33 | 05-13 03:35:17.122 W/AnkiDroid(22906): DB/ Not in a transaction. Cannot end transaction.
34 | 05-13 03:35:17.122 I/AnkiDroid(22906): ExecuteCommand: closeCollection
35 | 05-13 03:35:17.151 I/AnkiDroid(22906): Closing Collection Log
36 | 05-13 03:35:17.152 I/AnkiDroid(22906): Collection closed
37 | 05-13 03:35:17.152 I/AnkiDroid(22906): Unlocked Collection
38 | 05-13 03:35:17.174 I/AnkiDroid(22906): Sync was successful
39 | 05-13 03:35:17.174 I/AnkiDroid(22906): Regular sync completed successfully
40 | 05-13 03:35:17.184 I/AnkiDroid(22906): Begin openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
41 | 05-13 03:35:17.185 I/AnkiDroid(22906): Opening rust backend. Server: false. Langs: 'en', path:
42 | 05-13 03:35:17.186 I/AnkiDroid(22906): Opening Collection: '/storage/emulated/0/AnkiDroid/collection.anki2' '' '' ''
43 | 05-13 03:35:18.308 I/AnkiDroid(22906): Opening Collection Log
44 | 05-13 03:35:18.371 I/AnkiDroid(22906): ExecuteCommand: localMinutesWest
45 | 05-13 03:35:18.372 I/AnkiDroid(22906): ExecuteCommand: localMinutesWest
46 | 05-13 03:35:18.372 I/AnkiDroid(22906): End openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
47 | 05-13 03:35:18.562 I/AnkiDroid(22906): Updating deck list UI
48 | 05-13 03:35:18.756 I/AnkiDroid(22906): MetaDB:: Upgrading Internal Database..
49 | 05-13 03:35:18.756 I/AnkiDroid(22906): MetaDB:: Applying changes for version: 0
50 | 05-13 03:35:18.763 I/AnkiDroid(22906): Added 'lightpencolor' column to whiteboardState
51 | 05-13 03:35:18.768 I/AnkiDroid(22906): Added 'darkpencolor' column to whiteboardState
52 | 05-13 03:35:18.772 I/AnkiDroid(22906): MetaDB:: Upgrading Internal Database finished. New version: 6
53 | 05-13 03:35:18.780 I/AnkiDroid(22906): NotificationService: OnStartCommand
54 | 05-13 03:35:27.183 I/AnkiDroid(22906): Navigating to card browser
55 | 05-13 03:35:27.199 I/AnkiDroid(22906): AnkiActivity::onPause - DeckPicker
56 | 05-13 03:35:27.212 I/AnkiDroid(22906): AnkiActivity::onCreate - CardBrowser
57 | 05-13 03:35:27.242 I/AnkiDroid(22906): AnkiActivity::onStart - CardBrowser
58 | 05-13 03:35:27.245 I/AnkiDroid(22906): AnkiActivity::onResume - CardBrowser
59 | 05-13 03:35:27.554 I/AnkiDroid(22906): AnkiActivity::onStop - DeckPicker
60 | 05-13 03:35:27.873 I/AnkiDroid(22906): CardBrowser:: Completed doInBackgroundSearchCards Successfully
61 | 05-13 03:35:28.092 I/AnkiDroid(22906): NotificationService: OnStartCommand
62 | --------- beginning of crash


```

###### Actual Result

```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
at java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:866)
at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:483)
at java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:422)
at java.util.ComparableTimSort.sort(ComparableTimSort.java:222)
at java.util.Arrays.sort(Arrays.java:1302)
at java.util.Arrays.sort(Arrays.java:1485)
at java.util.ArrayList.sort(ArrayList.java:1470)
at java.util.Collections.sort(Collections.java:206)
at java.util.Collections.sort(Collections.java:159)
at com.ichi2.anki.dialogs.DeckSelectionDialog$DecksArrayAdapter.<init>(DeckSelectionDialog.java:6)
at com.ichi2.anki.dialogs.DeckSelectionDialog.onCreateDialog(DeckSelectionDialog.java:16)
at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:4)
at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:3)
at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:4)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:20)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:34)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:4)
at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:1)
at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:8)
at com.ichi2.anki.DeckSpinnerSelection.displayDeckOverrideDialog(DeckSpinnerSelection.java:6)
at com.ichi2.anki.DeckSpinnerSelection.lambda$setSpinnerListner$0(DeckSpinnerSelection.java:2)
at com.ichi2.anki.DeckSpinnerSelection.a(Unknown Source:0)
at com.ichi2.anki.m3.onTouch(Unknown Source:2)
```

###### Debug info

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/7a21ce36-693b-4912-8466-051741fe1d0d

```


 
--
ANDROID_VERSION | 11
APP_VERSION_CODE | 321500201
APP_VERSION_NAME | 2.15.0beta1
AVAILABLE_MEM_SIZE | 64426663936
BRAND | OnePlus
BUILD | BOARDmsmnileBOOTLOADERunknownBRANDOnePlusCPU_ABIarm64-v8aCPU_ABI2DEVICEOnePlus7TPro | BOARD | msmnile | BOOTLOADER | unknown | BRAND | OnePlus | CPU_ABI | arm64-v8a | CPU_ABI2 |   | DEVICE | OnePlus7TPro
BOARD | msmnile
BOOTLOADER | unknown
BRAND | OnePlus
CPU_ABI | arm64-v8a
CPU_ABI2 |  
DEVICE | OnePlus7TPro


```

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Last line of our code before it goes into the Collections stack frames is 

https://github.com/ankidroid/Anki-Android/blob/aa1c65121804bc9440dd2a0ccd7f9d34af9f4abe/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java#L270

Strangely this is a @david-allison-1 but has existed far longer then this recent crash, @Arthur-Milchior has been in there, I recently went in and did a fast (possibly too fast...) forward port on a library upgrade and @Akshay0701 was in there, but...it doesn't seem obvious to me on first glance. I fear it might be my forward port that is a likely cause, but just don't know until I have time to inspect it.

This is officially our first (and currently only) crash on 2.15.0beta1 :-)

**Comment by Arthur-Milchior** [comment]
I'll deal with it

**Comment by Arthur-Milchior** [comment]
«Comparison method violates its general contract!».
The comparison sort is easily not reflexive on ALL_DECKS. 
In practice ALL_DECKS < A < B < ALL_DECKS would be true, I don't expect there is more to search here. Thanks for your investigation Mike, but I fear this is over the top here

**Comment by Akshay0701** [comment]
I admit it's my mistake, Thank you so much @Arthur-Milchior.

**Comment by Arthur-Milchior** [comment]
You're welcome. No trouble. I clearly did worse
