### ISSUE TITLE
Crash 2.15alpha49 / 2.15.0beta1 - CardBrowser render

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8821]
@Arthur-Milchior - I think CardCollection is usually your area? Not sure what happened here, looks like the CardBrowser was shutting down prior to the crash, but it still failed in render somehow

The stack trace line numbers are of course problematic (not correct) but hopefully the stack frame method names are enough to locate?

###### Reproduction Steps

logcat from crash report

```


 
--
LOGCAT | 0--------- beginning of main105-13 12:01:08.170 I/AnkiDroid( 6503): AbstractFlashcardViewer:: EASE_3 pressed205-13 12:01:08.171 I/AnkiDroid( 6503): Answering card 1612815015767305-13  12:01:08.177 I/AnkiDroid( 6503): Rust: executeGetRowsAffected UPDATE  cards SET  factor=?,lapses=?,did=?,due=?,ivl=?,mod=?,usn=?,left=?,odid=?,odue=?,reps=?,type=?,queue=?  WHERE id = ?405-13 12:01:08.179 I/AnkiDroid( 6503): Obtaining card505-13 12:01:08.195 I/AnkiDroid( 6503): ViewGroupUtils::setRenderWorkaround - using default / hardware rendering605-13 12:01:08.197 I/AnkiDroid( 6503): AbstractFlashcardViewer:: Question successfully shown for card id 1523919409004705-13 12:01:09.305 I/AnkiDroid( 6503): Back key pressed805-13 12:01:09.305 I/AnkiDroid( 6503): finishWithAnimation END905-13 12:01:09.311 I/AnkiDroid( 6503): AnkiActivity::onPause - Reviewer1005-13 12:01:09.320 I/AnkiDroid( 6503): Handling Activity Result: 901. Result: 501105-13 12:01:09.320 I/AnkiDroid( 6503): Creating notification channel with id/name: General Notifications/AnkiDroid1205-13 12:01:09.320 I/AnkiDroid( 6503): Creating notification channel with id/name: Synchronization/同步1305-13 12:01:09.320 I/AnkiDroid( 6503): Creating notification channel with id/name: Global Reminders/卡片到期1405-13 12:01:09.321 I/AnkiDroid( 6503): Creating notification channel with id/name: Deck Reminders/提醒1505-13 12:01:09.323 I/AnkiDroid( 6503): AnkiActivity::onStart - DeckPicker1605-13 12:01:09.326 I/AnkiDroid( 6503): AnkiActivity::onResume - DeckPicker1705-13 12:01:09.355 I/AnkiDroid( 6503): Updating deck list UI1805-13 12:01:09.416 I/AnkiDroid( 6503): AnkiActivity::onStop - Reviewer1905-13 12:01:09.418 I/AnkiDroid( 6503): AnkiActivity::onDestroy - Reviewer2005-13 12:01:09.419 I/AnkiDroid( 6503): Rust: executeGetRowsAffected UPDATE col SET dconf=?,decks=?21--------- beginning of system2205-13 12:01:09.423 I/AnkiDroid( 6503): flush - Saving information to DB...2305-13 12:01:09.423 I/AnkiDroid( 6503): Rust: executeGetRowsAffected UPDATE col SET ls=?,crt=?,dty=?,mod=?,scm=?,usn=?,conf=?2405-13 12:01:10.795 I/AnkiDroid( 6503): Navigating to card browser2505-13 12:01:10.813 I/AnkiDroid( 6503): AnkiActivity::onPause - DeckPicker2605-13 12:01:10.824 I/AnkiDroid( 6503): AnkiActivity::onCreate - CardBrowser2705-13 12:01:10.847 I/AnkiDroid( 6503): AnkiActivity::onStart - CardBrowser2805-13 12:01:10.849 I/AnkiDroid( 6503): AnkiActivity::onResume - CardBrowser2905-13 12:01:10.897 I/AnkiDroid( 6503): CardBrowser:: Completed doInBackgroundSearchCards Successfully3005-13 12:01:10.944 I/AnkiDroid( 6503): AnkiActivity::onStop - DeckPicker31--------- beginning of crash | 0 | --------- beginning of main | 1 | 05-13 12:01:08.170 I/AnkiDroid( 6503): AbstractFlashcardViewer:: EASE_3 pressed | 2 | 05-13 12:01:08.171 I/AnkiDroid( 6503): Answering card 1612815015767 | 3 | 05-13  12:01:08.177 I/AnkiDroid( 6503): Rust: executeGetRowsAffected UPDATE  cards SET  factor=?,lapses=?,did=?,due=?,ivl=?,mod=?,usn=?,left=?,odid=?,odue=?,reps=?,type=?,queue=?  WHERE id = ? | 4 | 05-13 12:01:08.179 I/AnkiDroid( 6503): Obtaining card | 5 | 05-13 12:01:08.195 I/AnkiDroid( 6503): ViewGroupUtils::setRenderWorkaround - using default / hardware rendering | 6 | 05-13 12:01:08.197 I/AnkiDroid( 6503): AbstractFlashcardViewer:: Question successfully shown for card id 1523919409004 | 7 | 05-13 12:01:09.305 I/AnkiDroid( 6503): Back key pressed | 8 | 05-13 12:01:09.305 I/AnkiDroid( 6503): finishWithAnimation END | 9 | 05-13 12:01:09.311 I/AnkiDroid( 6503): AnkiActivity::onPause - Reviewer | 10 | 05-13 12:01:09.320 I/AnkiDroid( 6503): Handling Activity Result: 901. Result: 50 | 11 | 05-13 12:01:09.320 I/AnkiDroid( 6503): Creating notification channel with id/name: General Notifications/AnkiDroid | 12 | 05-13 12:01:09.320 I/AnkiDroid( 6503): Creating notification channel with id/name: Synchronization/同步 | 13 | 05-13 12:01:09.320 I/AnkiDroid( 6503): Creating notification channel with id/name: Global Reminders/卡片到期 | 14 | 05-13 12:01:09.321 I/AnkiDroid( 6503): Creating notification channel with id/name: Deck Reminders/提醒 | 15 | 05-13 12:01:09.323 I/AnkiDroid( 6503): AnkiActivity::onStart - DeckPicker | 16 | 05-13 12:01:09.326 I/AnkiDroid( 6503): AnkiActivity::onResume - DeckPicker | 17 | 05-13 12:01:09.355 I/AnkiDroid( 6503): Updating deck list UI | 18 | 05-13 12:01:09.416 I/AnkiDroid( 6503): AnkiActivity::onStop - Reviewer | 19 | 05-13 12:01:09.418 I/AnkiDroid( 6503): AnkiActivity::onDestroy - Reviewer | 20 | 05-13 12:01:09.419 I/AnkiDroid( 6503): Rust: executeGetRowsAffected UPDATE col SET dconf=?,decks=? | 21 | --------- beginning of system | 22 | 05-13 12:01:09.423 I/AnkiDroid( 6503): flush - Saving information to DB... | 23 | 05-13 12:01:09.423 I/AnkiDroid( 6503): Rust: executeGetRowsAffected UPDATE col SET ls=?,crt=?,dty=?,mod=?,scm=?,usn=?,conf=? | 24 | 05-13 12:01:10.795 I/AnkiDroid( 6503): Navigating to card browser | 25 | 05-13 12:01:10.813 I/AnkiDroid( 6503): AnkiActivity::onPause - DeckPicker | 26 | 05-13 12:01:10.824 I/AnkiDroid( 6503): AnkiActivity::onCreate - CardBrowser | 27 | 05-13 12:01:10.847 I/AnkiDroid( 6503): AnkiActivity::onStart - CardBrowser | 28 | 05-13 12:01:10.849 I/AnkiDroid( 6503): AnkiActivity::onResume - CardBrowser | 29 | 05-13 12:01:10.897 I/AnkiDroid( 6503): CardBrowser:: Completed doInBackgroundSearchCards Successfully | 30 | 05-13 12:01:10.944 I/AnkiDroid( 6503): AnkiActivity::onStop - DeckPicker | 31 | --------- beginning of crash
0 | --------- beginning of main
1 | 05-13 12:01:08.170 I/AnkiDroid( 6503): AbstractFlashcardViewer:: EASE_3 pressed
2 | 05-13 12:01:08.171 I/AnkiDroid( 6503): Answering card 1612815015767
3 | 05-13  12:01:08.177 I/AnkiDroid( 6503): Rust: executeGetRowsAffected UPDATE  cards SET  factor=?,lapses=?,did=?,due=?,ivl=?,mod=?,usn=?,left=?,odid=?,odue=?,reps=?,type=?,queue=?  WHERE id = ?
4 | 05-13 12:01:08.179 I/AnkiDroid( 6503): Obtaining card
5 | 05-13 12:01:08.195 I/AnkiDroid( 6503): ViewGroupUtils::setRenderWorkaround - using default / hardware rendering
6 | 05-13 12:01:08.197 I/AnkiDroid( 6503): AbstractFlashcardViewer:: Question successfully shown for card id 1523919409004
7 | 05-13 12:01:09.305 I/AnkiDroid( 6503): Back key pressed
8 | 05-13 12:01:09.305 I/AnkiDroid( 6503): finishWithAnimation END
9 | 05-13 12:01:09.311 I/AnkiDroid( 6503): AnkiActivity::onPause - Reviewer
10 | 05-13 12:01:09.320 I/AnkiDroid( 6503): Handling Activity Result: 901. Result: 50
11 | 05-13 12:01:09.320 I/AnkiDroid( 6503): Creating notification channel with id/name: General Notifications/AnkiDroid
12 | 05-13 12:01:09.320 I/AnkiDroid( 6503): Creating notification channel with id/name: Synchronization/同步
13 | 05-13 12:01:09.320 I/AnkiDroid( 6503): Creating notification channel with id/name: Global Reminders/卡片到期
14 | 05-13 12:01:09.321 I/AnkiDroid( 6503): Creating notification channel with id/name: Deck Reminders/提醒
15 | 05-13 12:01:09.323 I/AnkiDroid( 6503): AnkiActivity::onStart - DeckPicker
16 | 05-13 12:01:09.326 I/AnkiDroid( 6503): AnkiActivity::onResume - DeckPicker
17 | 05-13 12:01:09.355 I/AnkiDroid( 6503): Updating deck list UI
18 | 05-13 12:01:09.416 I/AnkiDroid( 6503): AnkiActivity::onStop - Reviewer
19 | 05-13 12:01:09.418 I/AnkiDroid( 6503): AnkiActivity::onDestroy - Reviewer
20 | 05-13 12:01:09.419 I/AnkiDroid( 6503): Rust: executeGetRowsAffected UPDATE col SET dconf=?,decks=?
21 | --------- beginning of system
22 | 05-13 12:01:09.423 I/AnkiDroid( 6503): flush - Saving information to DB...
23 | 05-13 12:01:09.423 I/AnkiDroid( 6503): Rust: executeGetRowsAffected UPDATE col SET ls=?,crt=?,dty=?,mod=?,scm=?,usn=?,conf=?
24 | 05-13 12:01:10.795 I/AnkiDroid( 6503): Navigating to card browser
25 | 05-13 12:01:10.813 I/AnkiDroid( 6503): AnkiActivity::onPause - DeckPicker
26 | 05-13 12:01:10.824 I/AnkiDroid( 6503): AnkiActivity::onCreate - CardBrowser
27 | 05-13 12:01:10.847 I/AnkiDroid( 6503): AnkiActivity::onStart - CardBrowser
28 | 05-13 12:01:10.849 I/AnkiDroid( 6503): AnkiActivity::onResume - CardBrowser
29 | 05-13 12:01:10.897 I/AnkiDroid( 6503): CardBrowser:: Completed doInBackgroundSearchCards Successfully
30 | 05-13 12:01:10.944 I/AnkiDroid( 6503): AnkiActivity::onStop - DeckPicker
31 | --------- beginning of crash

```

###### Expected Result

No crash

###### Actual Result

```
java.lang.ArrayIndexOutOfBoundsException: length=5; index=-1
at java.util.ArrayList.get(ArrayList.java:439)
at com.ichi2.anki.CardBrowser$CardCollection.get(CardBrowser.java:1)
at com.ichi2.anki.CardBrowser$RenderOnScroll.onScroll(CardBrowser.java:4)
at android.widget.AbsListView.invokeOnItemScrollListener(AbsListView.java:1707)
at android.widget.ListView.layoutChildren(ListView.java:2053)
at android.widget.AbsListView.onLayout(AbsListView.java:2416)
at android.widget.HwAbsListView.onLayout(HwAbsListView.java:466)
at android.view.View.layout(View.java:22244)
at android.view.ViewGroup.layout(ViewGroup.java:6494)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
at android.view.View.layout(View.java:22244)
at android.view.ViewGroup.layout(ViewGroup.java:6494)
at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:18)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:7)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:8)
at android.view.View.layout(View.java:22244)
at android.view.ViewGroup.layout(ViewGroup.java:6494)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:22244)
at android.view.ViewGroup.layout(ViewGroup.java:6494)
at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:10)
at android.view.View.layout(View.java:22244)
at android.view.ViewGroup.layout(ViewGroup.java:6494)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:22244)
at android.view.ViewGroup.layout(ViewGroup.java:6494)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:22244)
at android.view.ViewGroup.layout(ViewGroup.java:6494)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:22244)
at android.view.ViewGroup.layout(ViewGroup.java:6494)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
at android.view.View.layout(View.java:22244)
at android.view.ViewGroup.layout(ViewGroup.java:6494)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at com.android.internal.policy.DecorView.onLayout(DecorView.java:1084)
at android.view.View.layout(View.java:22244)
at android.view.ViewGroup.layout(ViewGroup.java:6494)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3633)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3113)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2111)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8577)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1256)
at android.view.Choreographer.doCallbacks(Choreographer.java:995)
at android.view.Choreographer.doFrame(Choreographer.java:887)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1224)
at android.os.Handler.handleCallback(Handler.java:900)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:219)
at android.app.ActivityThread.main(ActivityThread.java:8393)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

###### Debug info

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/696335b5-712e-4e07-a445-0f4f7cd47f53

```
--
ANDROID_VERSION | 10
APP_VERSION_CODE | 321500149
APP_VERSION_NAME | 2.15alpha49
AVAILABLE_MEM_SIZE | 177545961472
BRAND | HUAWEI
BUILD | BOARDTASBOOTLOADERunknownBRANDHUAWEICPU_ABIarm64-v8aCPU_ABI2DEVICEHWTAS | BOARD | TAS | BOOTLOADER | unknown | BRAND | HUAWEI | CPU_ABI | arm64-v8a | CPU_ABI2 |   | DEVICE | HWTAS
BOARD | TAS
BOOTLOADER | unknown
BRAND | HUAWEI
CPU_ABI | arm64-v8a
CPU_ABI2 |  
DEVICE | HWTAS

```
###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Likely unrelated, but in the area - might be better as a separate issue

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Iterable com.ichi2.utils.JSONArray.stringIterable()' on a null object reference
at com.ichi2.libanki.Decks.load(Decks.java:4)
at com.ichi2.libanki.Collection.load(Collection.java:14)
at com.ichi2.libanki.Collection.<init>(Collection.java:15)
at com.ichi2.libanki.Storage.Collection(Storage.java:10)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:8)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:3)
at com.ichi2.anki.CollectionHelper.getColSafe(CollectionHelper.java:1)
at com.ichi2.anki.DeckPicker.onPrepareOptionsMenu(DeckPicker.java:1)
```

**Comment by Arthur-Milchior** [comment]
Second one is not yet corrected. I understand what is happening at a local level, but I've no idea how a user could get the application in this state.

Essentially, there were no deck for some reason. And in this case, the method names return null instead of an empty array

**Comment by mikehardy** [comment]
:-) - we have so few crashes (a good thing) that just about all the crashes are ... intellectually stimulating (because they are pretty bizarre yes)

**Comment by Arthur-Milchior** [comment]
Second issue is unrelated to first. New issue created, and this issue is now officially not concerned with the last crash reported by Mike

**Comment by mikehardy** [comment]
Thanks for doing that and sorry for the hassle I was attempting to move fast, but I have a saying (that I should followed!) "fast is slow, and slow is fast" - ended up wasting more time than it saved for sure

**Comment by mikehardy** [comment]
> In a search result of 4 cards, with totalItemCount = 4, somehow we got 0 elements to display.

```
com.ichi2.anki.exception.ManuallyReportedException: CardBrowser Scroll Issue 8821
at com.ichi2.anki.AnkiDroidApp.sendExceptionReport(AnkiDroidApp.java:1)
at com.ichi2.anki.CardBrowser$RenderOnScroll.onScroll(CardBrowser.java:3)
at android.widget.AbsListView.invokeOnItemScrollListener(AbsListView.java:2256)
at android.widget.ListView.layoutChildren(ListView.java:2141)
at android.widget.AbsListView.onLayout(AbsListView.java:3041)
at android.view.View.layout(View.java:23754)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:23754)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayou
```

```

-------- beginning of main
--
1 | 05-18 17:29:31.667 I/AnkiDroid(12321): AnkiActivity::onStart - NoteEditor
2 | 05-18 17:29:31.694 I/AnkiDroid(12321): AnkiActivity::onResume - NoteEditor
3 | 05-18 17:29:33.875 I/AnkiDroid(12321): NoteEditor:: Home button pressed
4 | 05-18 17:29:33.878 I/AnkiDroid(12321): finishWithAnimation END
5 | 05-18 17:29:33.893 I/AnkiDroid(12321): AnkiActivity::onPause - NoteEditor
6 | 05-18 17:29:33.924 I/AnkiDroid(12321): AnkiActivity::onDestroy - CardBrowser
7 | 05-18 17:29:33.995 I/AnkiDroid(12321): AnkiActivity::onCreate - CardBrowser
8 | 05-18 17:29:34.229 I/AnkiDroid(12321): AnkiActivity::onStart - CardBrowser
9 | 05-18 17:29:34.254 I/AnkiDroid(12321): Cancelled 1 instances of task class com.ichi2.async.CollectionTask$SearchCards
10 | 05-18 17:29:34.256 I/AnkiDroid(12321): Handling Activity Result: 1188336856. Result: -1
11 | 05-18 17:29:34.257 I/AnkiDroid(12321): Creating notification channel with id/name: General Notifications/AnkiDroid
12 | 05-18 17:29:34.263 I/AnkiDroid(12321): Creating notification channel with id/name: Synchronization/Sincronização
13 | 05-18 17:29:34.265 I/AnkiDroid(12321): Creating notification channel with id/name: Global Reminders/Cards pendentes
14 | 05-18 17:29:34.268 I/AnkiDroid(12321): Creating notification channel with id/name: Deck Reminders/Lembretes
15 | 05-18 17:29:34.284 W/AnkiDroid(12321): CardBrowser/ Note was added from browser and on return mSearchView == null
16 | 05-18 17:29:34.285 I/AnkiDroid(12321): AnkiActivity::onResume - CardBrowser
17 | 05-18 17:29:34.613 I/AnkiDroid(12321): CardBrowser:: Completed doInBackgroundSearchCards Successfully


```

**Comment by mikehardy** [comment]
Great error message on that one! I was able to connect back to this issue immediately

**Comment by Arthur-Milchior** [comment]
Was there any crash/bug from the user perspective?
Did you get this single report, or is it something that occurred often?

Given the logs, it seems the cardbrowesr was closed and replaced by the note editor. 

It seems that sometime, when the card browser gets closed, the viewer asks to see 0 elements instead of just not asking anything. I guess it's technically true, if the view list is deleted, there is 0 elements seen. It's strange it's get called, but given that it's async front end library, I guess it's expected that sometime correct but useless code is called. I find nothing to worry about here.

If no other window were shown instead of the card browser, it would become frightening, because it would mean that the card browser gets shown but no content is shown in it. But if it gets closed, the worst that is occuring is that there is a useless function call, and that's fine

**Comment by mikehardy** [comment]
I'm not sure what the user saw, I doubt it crashed now as the code was executing in the block where we handle these things and make it not crash - this was just evidence from your new log message and I wanted to close the loop with you by giving the info from your new error message

I don't think the analysis is right though, my read of the logcat is that there is nothing showing here but the CardBrowser - it's in RESUME state of Activity lifecycle, which means it is visible + active for the user

**Comment by mikehardy** [comment]
I am moving this to the 2.16 as it won't block 2.15 release anymore. This is now more of a background analysis "what exactly is happening here" task.
