### ISSUE TITLE
Crash 2.15beta - NumberFormatException on IncrementNumberRangePreference

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8843]
stack trace

```
java.lang.NumberFormatException: For input string: ""
at java.lang.Integer.parseInt(Integer.java:620)
at java.lang.Integer.parseInt(Integer.java:643)
at com.ichi2.preferences.IncrementerNumberRangePreference.updateEditText(IncrementerNumberRangePreference.java:1)
at com.ichi2.preferences.IncrementerNumberRangePreference.lambda$initialize$1(IncrementerNumberRangePreference.java:1)
at com.ichi2.preferences.IncrementerNumberRangePreference.b(Unknown Source:0)
at com.ichi2.preferences.a.onClick(Unknown Source:2)
at android.view.View.performClick(View.java:6897)
at android.widget.TextView.performClick(TextView.java:12693)
at android.view.View$PerformClick.run(View.java:26101)
at android.os.Handler.handleCallback(Handler.java:789)
```

logcat was empty

How can it happen? No idea but it can happen - can't call parseInt without catching NumberFormatException and using a sensible default...

**Comment by yasin459** [comment]
i would like to work on this issue :)

**Comment by mikehardy** [comment]
@yasin459 Please be my guest! I'm merging things and preparing for a new release 2.15.0beta4 right now, do you think you'll have time now or is this for later today/ this week? Just curious as I would like to get it quickly if possible, but there are plenty of other issues if you meant for later :-)

**Comment by yasin459** [comment]
@mikehardy i made a pr for this issue, I think it must be solved now
