### ISSUE TITLE
2.15beta4 crash on image paste

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8880]
Submitter entered crash comment "can't paste image into note"

```
java.lang.IllegalArgumentException: Prefix string too short
at java.io.File.createTempFile(File.java:1991)
at java.io.File.createTempFile(File.java:2064)
at com.ichi2.anki.NoteEditor.loadImageIntoCollection(NoteEditor.java:4)
at com.ichi2.anki.NoteEditor.onImagePaste(NoteEditor.java:2)
at com.ichi2.anki.NoteEditor.c(Unknown Source:0)
at com.ichi2.anki.k5.onImagePaste(Unknown Source:2)
at com.ichi2.anki.FieldEditText.onImagePaste(FieldEditText.java:1)
at com.ichi2.anki.FieldEditText.lambda$onCreateInputConnection$0(FieldEditText.java:6)
at com.ichi2.anki.FieldEditText.a(Unknown Source:0)
at com.ichi2.anki.o3.onCommitContent(Unknown Source:9)
at androidx.core.view.inputmethod.InputConnectionCompat$1.commitContent(InputConnectionCompat.java:1)
at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:567)
at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:93)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8506)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by mikehardy** [comment]
Another image paste issue, unique stack:

```
java.lang.IllegalStateException: Unable to obtain valid filename from uri: content://com.sec.android.semclipboardprovider/images/179
at com.ichi2.utils.ContentResolverUtil.getFileName(ContentResolverUtil.java:4)
at com.ichi2.anki.NoteEditor.loadImageIntoCollection(NoteEditor.java:1)
at com.ichi2.anki.NoteEditor.onImagePaste(NoteEditor.java:2)
at com.ichi2.anki.NoteEditor.c(Unknown Source:0)
at com.ichi2.anki.k5.onImagePaste(Unknown Source:2)
at com.ichi2.anki.FieldEditText.onImagePaste(FieldEditText.java:1)
at com.ichi2.anki.FieldEditText.lambda$onCreateInputConnection$0(FieldEditText.java:6)
at com.ichi2.anki.FieldEditText.a(Unknown Source:0)
at com.ichi2.anki.o3.onCommitContent(Unknown Source:9)
at androidx.core.view.inputmethod.InputConnectionCompat$1.commitContent(InputConnectionCompat.java:1)
at android.widget.TextView.commitImage(TextView.java:17338)
at android.widget.TextView.pasteClipBoardData(TextView.java:16744)
at android.widget.TextView.access$4300(TextView.java:438)
at android.widget.TextView$TextViewClipboardEventListener$1.run(TextView.java:16672)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7078)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

**Comment by prateek-singh-3212** [comment]
I would like to work on this issue.

**Comment by mikehardy** [comment]
Please be my guest ❤️

**Comment by prateek-singh-3212** [comment]
> java.lang.IllegalStateException: Unable to obtain valid filename from uri: content://com.sec.android.semclipboardprovider/images/179
at com.ichi2.utils.ContentResolverUtil.getFileName(ContentResolverUtil.java:4)
at com.ichi2.anki.NoteEditor.loadImageIntoCollection(NoteEditor.java:1)
at com.ichi2.anki.NoteEditor.onImagePaste(NoteEditor.java:2)
at com.ichi2.anki.NoteEditor.c(Unknown Source:0)
at com.ichi2.anki.k5.onImagePaste(Unknown Source:2)
at com.ichi2.anki.FieldEditText.onImagePaste(FieldEditText.java:1)
at com.ichi2.anki.FieldEditText.lambda$onCreateInputConnection$0(FieldEditText.java:6)
at com.ichi2.anki.FieldEditText.a(Unknown Source:0)
at com.ichi2.anki.o3.onCommitContent(Unknown Source:9)
at androidx.core.view.inputmethod.InputConnectionCompat$1.commitContent(InputConnectionCompat.java:1)
at android.widget.TextView.commitImage(TextView.java:17338)
at android.widget.TextView.pasteClipBoardData(TextView.java:16744)
at android.widget.TextView.access$4300(TextView.java:438)
at android.widget.TextView$TextViewClipboardEventListener$1.run(TextView.java:16672)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7078)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)



@mikehardy In this it is already handled. What do you want me to do. Should I implement a Toast whenever this exception occurs?
