### ISSUE TITLE
2.15beta4 crash on file selection - illegal characters

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8881]
origin was media selection user flow

```
java.io.IOException: Unable to create temporary file, /storage/emulated/0/AnkiDroid/collection.media/ankidroid_audioclip_There's a good film on the day <b>after</b> tomorrow.1255403766517369886.mp3
at java.io.File$TempDirectory.generateFile(File.java:1911)
at java.io.File.createTempFile(File.java:2001)
at com.ichi2.anki.multimediacard.fields.BasicAudioClipFieldController.handleAudioSelection(BasicAudioClipFieldController.java:20)
at com.ichi2.anki.multimediacard.fields.BasicAudioClipFieldController.onActivityResult(BasicAudioClipFieldController.java:1)
at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.onActivityResult(MultimediaEditFieldActivity.java:3)
at android.app.Activity.dispatchActivityResult(Activity.java:8145)
at android.app.ActivityThread.deliverResults(ActivityThread.java:4986)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:5034)
at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2065)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7631)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:12)
```

**Comment by prateek-singh-3212** [comment]
I would like to work on this issue

**Comment by mikehardy** [comment]
Please feel free! Thank you

**Comment by mikehardy** [comment]
Thank you for taking these on @prateek-singh-3212 - much appreciated!
