### ISSUE TITLE
2.15.0beta4 crash on custom sync server URL bad hostname

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8883]
Looks like this just wasn't bubbled up to the user? it crashed?

```
com.ichi2.libanki.sync.CustomSyncServerUrlException: customSyncServerUrl
at com.ichi2.libanki.sync.HttpSyncer.parseUrl(HttpSyncer.java:3)
at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:33)
at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:2)
at com.ichi2.libanki.sync.RemoteServer.hostKey(RemoteServer.java:5)
at com.ichi2.async.Connection.doInBackgroundLogin(Connection.java:5)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:3)
at com.ichi2.async.Connection.doInBackground(Connection.java:4)
at com.ichi2.async.Connection.doInBackground(Connection.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:48)
at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1)
at okhttp3.HttpUrl.get(Unknown Source:2)
at com.ichi2.libanki.sync.HttpSyncer.parseUrl(HttpSyncer.java:1)
```

**Comment by vinishhub** [comment]
I would like to work on it can you ellaborate more

**Comment by mikehardy** [comment]
Nope. With crash traces you get what you see. Be creative with the information provided and try to reproduce

**Comment by mikehardy** [comment]
I am fixing this now.
