### ISSUE TITLE
2.15.0beta4 crash updating screen counts?

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8884]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.ichi2.libanki.DB.queryScalar(java.lang.String, java.lang.Object[])' on a null object reference
at com.ichi2.libanki.sched.SchedV2._resetLrnCount(SchedV2.java:6)
at com.ichi2.libanki.sched.SchedV2.resetCounts(SchedV2.java:6)
at com.ichi2.libanki.sched.SchedV2.resetCounts(SchedV2.java:1)
at com.ichi2.libanki.sched.SchedV2.counts(SchedV2.java:3)
at com.ichi2.libanki.sched.SchedV2.counts(SchedV2.java:1)
at com.ichi2.libanki.sched.SchedV2.counts(SchedV2.java:5)
at com.ichi2.anki.Reviewer.updateScreenCounts(Reviewer.java:4)
at com.ichi2.anki.Reviewer.updateActionBar(Reviewer.java:2)
at com.ichi2.anki.AbstractFlashcardViewer.updateForNewCard(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.fillFlashcard(AbstractFlashcardViewer.java:10)
at com.ichi2.anki.Reviewer.fillFlashcard(Reviewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:31)
at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:10)
at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:3)
at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:10)
at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:1)
at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:3)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:775)
at android.os.Handler.dispatchMessage(Handler.java:107)
```

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/a9654f35-1d8b-4178-ab96-93da193ecbf4

```

-------- beginning of main
--
1 | 05-18 18:19:03.475 I/AnkiDroid(18265): AnkiActivity::onPause - Reviewer
2 | 05-18 18:19:03.495 I/AnkiDroid(18265): Sync: merging small changes
3 | 05-18 18:19:03.495 I/AnkiDroid(18265): Sync: downloading chunked data
4 | 05-18 18:19:03.501 I/AnkiDroid(18265): AnkiActivity::onStart - DeckPicker
5 | 05-18 18:19:03.509 I/AnkiDroid(18265): AnkiActivity::onResume - DeckPicker
6 | 05-18 18:19:03.896 I/AnkiDroid(18265): Sync: applying chunked data
7 | 05-18 18:19:03.896 I/AnkiDroid(18265): Sync: collecting chunked data
8 | 05-18 18:19:03.898 I/AnkiDroid(18265): Sync: sending chunked data
9 | 05-18 18:19:04.333 I/AnkiDroid(18265): ExecuteCommand: localMinutesWest
10 | 05-18 18:19:04.333 I/AnkiDroid(18265): ExecuteCommand: localMinutesWest
11 | 05-18 18:19:04.860 I/AnkiDroid(18265): Sync: sending finish command
12 | 05-18 18:19:05.371 I/AnkiDroid(18265): Sync: finishing
13 | 05-18 18:19:05.394 I/AnkiDroid(18265): Rust: executeGetRowsAffected UPDATE col SET models=?
14 | 05-18 18:19:05.414 I/AnkiDroid(18265): Rust: executeGetRowsAffected UPDATE col SET dconf=?,decks=?
15 | 05-18 18:19:05.419 I/AnkiDroid(18265): Rust: executeGetRowsAffected UPDATE col SET tags=?
16 | 05-18 18:19:05.421 I/AnkiDroid(18265): flush - Saving information to DB...
17 | 05-18 18:19:05.422 I/AnkiDroid(18265): Rust: executeGetRowsAffected UPDATE col SET ls=?,crt=?,dty=?,mod=?,scm=?,usn=?,conf=?
18 | 05-18 18:19:05.424 I/AnkiDroid(18265): Rust: transaction commit
19 | 05-18 18:19:05.446 I/AnkiDroid(18265): Sync - Performing media sync
20 | 05-18 18:19:06.284 I/AnkiDroid(18265): Sync Finished - Closing Collection
21 | 05-18 18:19:06.284 W/AnkiDroid(18265): DB/ Not in a transaction. Cannot end transaction.
22 | 05-18 18:19:06.286 I/AnkiDroid(18265): ExecuteCommand: closeCollection
23 | 05-18 18:19:06.295 I/AnkiDroid(18265): Closing Collection Log
24 | 05-18 18:19:06.295 I/AnkiDroid(18265): Collection closed
25 | 05-18 18:19:06.295 I/AnkiDroid(18265): Unlocked Collection
26 | 05-18 18:19:06.297 I/AnkiDroid(18265): Begin openCollection: /sdcard/AnkiDroid/collection.anki2
27 | 05-18 18:19:06.297 I/AnkiDroid(18265): Opening rust backend. Server: false. Langs: 'en', path:
28 | 05-18 18:19:06.300 I/AnkiDroid(18265): Opening Collection: '/sdcard/AnkiDroid/collection.anki2' '' '' ''
29 | 05-18 18:19:06.338 I/AnkiDroid(18265): Sync was successful
30 | 05-18 18:19:06.338 I/AnkiDroid(18265): Regular sync completed successfully
31 | 05-18 18:19:06.339 I/AnkiDroid(18265): Opening Collection Log
32 | 05-18 18:19:06.360 I/AnkiDroid(18265): ExecuteCommand: localMinutesWest
33 | 05-18 18:19:06.361 I/AnkiDroid(18265): ExecuteCommand: localMinutesWest
34 | 05-18 18:19:06.361 I/AnkiDroid(18265): End openCollection: /sdcard/AnkiDroid/collection.anki2
35 | 05-18 18:19:06.363 I/AnkiDroid(18265): Updating deck list UI
36 | 05-18 18:19:06.368 I/AnkiDroid(18265): Obtaining card
37 | 05-18 18:19:06.375 E/AnkiDroid(18265): Threads/ must be called on the main thread instead of Thread[AsyncTask #1,5,main]
38 | 05-18 18:19:06.375 E/AnkiDroid(18265): Threads/ must be called on the main thread instead of Thread[AsyncTask #1,5,main]
39 | 05-18 18:19:06.415 I/AnkiDroid(18265): ExecuteCommand: localMinutesWest
40 | 05-18 18:19:06.483 I/AnkiDroid(18265): ViewGroupUtils::setRenderWorkaround - using default / hardware rendering
41 | 05-18 18:19:06.519 I/AnkiDroid(18265): ExecuteCommand: localMinutesWest
42 | --------- beginning of crash


```

**Comment by mikehardy** [comment]
I'm going to move this from 2.15 - this appears to be a collision between sync and other activity based on logcat
we have a few of those issues, none are regressions they are just difficult.
