### ISSUE TITLE
2.15.0beta4 ClassCastException crash

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8885]
```
java.lang.ClassCastException: java.lang.Object[] cannot be cast to java.lang.Long
at com.ichi2.anki.DeckPicker$3.onPostExecute(DeckPicker.java:54)
at com.ichi2.async.Connection.onPostExecute(Connection.java:6)
at com.ichi2.async.Connection.onPostExecute(Connection.java:1)
at android.os.AsyncTask.finish(AsyncTask.java:771)
at android.os.AsyncTask.access$900(AsyncTask.java:199)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7660)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at android.view.View.layout(View.java:23754)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:23754)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.view.View.layout(View.java:23754)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
```

```

--------- beginning of main
--
1 | 05-18 10:08:00.870 I/AnkiDroid(28814): AnkiActivity::onStart - DeckPicker
2 | 05-18 10:08:00.881 I/AnkiDroid(28814): AnkiActivity::onResume - DeckPicker
3 | 05-18 10:08:00.888 I/AnkiDroid(28814): Cancelled 1 instances of task class com.ichi2.async.CollectionTask$LoadDeckCounts
4 | 05-18 10:08:00.888 I/AnkiDroid(28814): AnkiActivity::onPause - DeckPicker
5 | 05-18 10:08:00.902 I/AnkiDroid(28814): Updating deck list UI
6 | 05-18 10:08:05.205 I/AnkiDroid(28814): AnkiActivity::onResume - DeckPicker
7 | 05-18 10:08:05.236 I/AnkiDroid(28814): Updating deck list UI
8 | 05-18 10:08:06.977 I/AnkiDroid(28814): DeckPicker:: Sync button pressed
9 | 05-18 10:08:06.998 I/AnkiDroid(28814): Locked Collection - Collection Loading should fail
10 | 05-18 10:08:06.999 I/AnkiDroid(28814): Sync - starting sync
11 | 05-18 10:08:06.999 I/AnkiDroid(28814): ExecuteCommand: localMinutesWest
12 | 05-18 10:08:09.927 I/AnkiDroid(28814): Rust: transaction begin
13 | 05-18 10:08:09.928 I/AnkiDroid(28814): Sync: getting meta data from server
14 | 05-18 10:08:09.929 I/AnkiDroid(28814): Sync: building local meta data
15 | 05-18 10:08:09.930 I/AnkiDroid(28814): Rust: transaction rollback
16 | 05-18 10:08:09.930 I/AnkiDroid(28814): Sync Finished - Closing Collection
17 | 05-18 10:08:09.930 W/AnkiDroid(28814): DB/ Not in a transaction. Cannot end transaction.
18 | 05-18 10:08:09.931 I/AnkiDroid(28814): ExecuteCommand: closeCollection
19 | 05-18 10:08:09.933 I/AnkiDroid(28814): Closing Collection Log
20 | 05-18 10:08:09.935 I/AnkiDroid(28814): Collection closed
21 | 05-18 10:08:09.935 I/AnkiDroid(28814): Unlocked Collection
22 | --------- beginning of crash
23 | 05-18 10:08:10.028 E/AnkiDroid(28814): AcraAnalyticsInteraction/ ACRA handling crash, sending analytics exception report
24 | 05-18 10:08:42.583 I/AnkiDroid(29230): initialize()
25 | 05-18 10:08:42.685 I/AnkiDroid(29230): Participating in analytics sample (sample percentage vs random: 10 2)
26 | 05-18 10:08:42.685 I/AnkiDroid(29230): setOptIn(): from false to false
27 | 05-18 10:08:42.685 I/AnkiDroid(29230): Not participating in analytics sample (sample percentage vs random: 10 48)
28 | 05-18 10:08:42.688 I/AnkiDroid(29230): Creating notification channel with id/name: General Notifications/AnkiDroid
29 | 05-18 10:08:42.688 I/AnkiDroid(29230): Creating notification channel with id/name: Synchronization/同步
30 | 05-18 10:08:42.689 I/AnkiDroid(29230): Creating notification channel with id/name: Global Reminders/卡片到期
31 | 05-18 10:08:42.689 I/AnkiDroid(29230): Creating notification channel with id/name: Deck Reminders/提醒
32 | 05-18 10:08:42.694 I/AnkiDroid(29230): AnkiDroidApp: Starting Services
33 | 05-18 10:08:42.696 I/AnkiDroid(29230): Begin openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
34 | 05-18 10:08:42.702 I/AnkiDroid(29230): Opening rust backend. Server: false. Langs: 'en', path:
35 | 05-18 10:08:42.707 I/AnkiDroid(29230): Opening Collection: '/storage/emulated/0/AnkiDroid/collection.anki2' '' '' ''
36 | 05-18 10:08:42.746 I/AnkiDroid(29230): Opening Collection Log
37 | 05-18 10:08:42.756 I/AnkiDroid(29230): ExecuteCommand: localMinutesWest
38 | 05-18 10:08:42.757 I/AnkiDroid(29230): ExecuteCommand: localMinutesWest
39 | 05-18 10:08:42.757 I/AnkiDroid(29230): End openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
40 | 05-18 10:08:42.757 I/AnkiDroid(29230): Executing Boot Service
41 | 05-18 10:08:42.770 I/AnkiDroid(29230): Launching DeckPicker
42 | 05-18 10:08:42.802 I/AnkiDroid(29230): AnkiActivity::onCreate - DeckPicker
43 | 05-18 10:08:42.808 I/AnkiDroid(29230): No startup screens required
44 | 05-18 10:08:42.891 I/AnkiDroid(29230): AnkiActivity::onStart - DeckPicker
45 | 05-18 10:08:42.909 I/AnkiDroid(29230): AnkiActivity::onResume - DeckPicker
46 | 05-18 10:08:42.921 I/AnkiDroid(29230): Updating deck list UI
47 | 05-18 10:08:42.926 I/AnkiDroid(29230): Updating deck list UI
48 | 05-18 10:08:44.314 I/AnkiDroid(29230): DeckPicker:: Sync button pressed
49 | 05-18 10:08:44.335 I/AnkiDroid(29230): Locked Collection - Collection Loading should fail
50 | 05-18 10:08:44.336 I/AnkiDroid(29230): Sync - starting sync
51 | 05-18 10:08:44.336 I/AnkiDroid(29230): ExecuteCommand: localMinutesWest
52 | 05-18 10:08:45.856 I/AnkiDroid(29230): Rust: transaction begin
53 | 05-18 10:08:45.856 I/AnkiDroid(29230): Sync: getting meta data from server
54 | 05-18 10:08:45.857 I/AnkiDroid(29230): Sync: building local meta data
55 | 05-18 10:08:45.858 I/AnkiDroid(29230): Rust: transaction rollback
56 | 05-18 10:08:45.858 I/AnkiDroid(29230): Sync Finished - Closing Collection
57 | 05-18 10:08:45.858 W/AnkiDroid(29230): DB/ Not in a transaction. Cannot end transaction.
58 | 05-18 10:08:45.859 I/AnkiDroid(29230): ExecuteCommand: closeCollection
59 | 05-18 10:08:45.860 I/AnkiDroid(29230): Closing Collection Log
60 | 05-18 10:08:45.861 I/AnkiDroid(29230): Collection closed
61 | 05-18 10:08:45.861 I/AnkiDroid(29230): Unlocked Collection


```

**Comment by TarekkMA** [comment]
I think I found the issue. The `Syncer#sync` method should return `Pair<ConnectionResultType, Object>`

https://github.com/ankidroid/Anki-Android/blob/60476b8331c63f42050d0142342b5c410aaeb11d/AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java#L182-L186

Here the `new Object[] {diff}` is wrapped yet again in another `Object[]`, `data.result = new Object[]{ret.second};`

https://github.com/ankidroid/Anki-Android/blob/60476b8331c63f42050d0142342b5c410aaeb11d/AnkiDroid/src/main/java/com/ichi2/async/Connection.java#L371-L382

And in `DeckPicker` we expect it to be of type `Long`, so we get `Object[] cannot be cast to Long`

https://github.com/ankidroid/Anki-Android/blob/60476b8331c63f42050d0142342b5c410aaeb11d/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java#L1890-L1891

**Comment by TarekkMA** [comment]
Adding the following snipped will give the crash reporting more context. The `onPostExecute` method is huge, and it will be nice to pinpoint which section will run.
```java
Timber.i("Sync Listener: onPostExecute: %s",data.resultType.toString());
```
