### ISSUE TITLE
2.15.0beta4 - crash getting Decks.current().optLong("id") on freshly installed app / fresh collection

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8886]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'long org.json.JSONObject.optLong(java.lang.String)' on a null object reference
at com.ichi2.anki.DeckPicker.__renderPage(DeckPicker.java:32)
at com.ichi2.anki.DeckPicker$UpdateDeckListListener.actualOnPostExecute(DeckPicker.java:9)
at com.ichi2.anki.DeckPicker$UpdateDeckListListener.actualOnPostExecute(DeckPicker.java:1)
at com.ichi2.async.TaskListenerWithContext.onPostExecute(TaskListenerWithContext.java:2)
at com.ichi2.async.CollectionTask.onPostExecute(CollectionTask.java:3)
at android.os.AsyncTask.finish(AsyncTask.java:755)
at android.os.AsyncTask.access$900(AsyncTask.java:192)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:221)
at android.app.ActivityThread.main(ActivityThread.java:7584)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at android.view.View.layout(View.java:23754)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:23754)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.view.View.layout(View.java:23754)
```

```

5-17  13:52:58.534 E/AnkiDroid(21476): 	at  android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
--
1 | 05-17  13:52:58.534 E/AnkiDroid(21476): 	at  android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
3 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.os.Handler.dispatchMessage(Handler.java:107)
4 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.os.Looper.loop(Looper.java:221)
5 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.app.ActivityThread.main(ActivityThread.java:7584)
6 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at java.lang.reflect.Method.invoke(Native Method)
7 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
8 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
9 | 05-17 13:52:58.534 E/AnkiDroid(21476):
10 | 05-17  13:52:58.534 E/AnkiDroid(21476):  com.ichi2.anki.exception.StorageAccessException: Failed to create  AnkiDroid directory /storage/emulated/0/AnkiDroid
11 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.ichi2.anki.CollectionHelper.initializeAnkiDroidDirectory(CollectionHelper.java:3)
12 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:6)
13 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:3)
14 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.ichi2.anki.CollectionHelper.getColSafe(CollectionHelper.java:1)
15 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.ichi2.anki.DeckPicker.firstCollectionOpen(DeckPicker.java:9)
16 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.ichi2.anki.DeckPicker.handleStartup(DeckPicker.java:2)
17 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.ichi2.anki.DeckPicker.onRequestPermissionsResult(DeckPicker.java:5)
18 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8408)
19 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.app.Activity.dispatchActivityResult(Activity.java:8253)
20 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4953)
21 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5001)
22 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
23 | 05-17  13:52:58.534 E/AnkiDroid(21476): 	at  android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
24 | 05-17  13:52:58.534 E/AnkiDroid(21476): 	at  android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
25 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
26 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.os.Handler.dispatchMessage(Handler.java:107)
27 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.os.Looper.loop(Looper.java:221)
28 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.app.ActivityThread.main(ActivityThread.java:7584)
29 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at java.lang.reflect.Method.invoke(Native Method)
30 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
31 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
32 | 05-17  13:52:58.539 W/AnkiDroid(21476): CollectionHelper/  com.ichi2.anki.exception.StorageAccessException: Failed to create  AnkiDroid directory /storage/emulated/0/AnkiDroid
33 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.ichi2.anki.CollectionHelper.initializeAnkiDroidDirectory(CollectionHelper.java:3)
34 | 05-17  13:52:58.539 W/AnkiDroid(21476): 	at  com.ichi2.anki.CollectionHelper.isCurrentAnkiDroidDirAccessible(CollectionHelper.java:1)
35 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.ichi2.anki.InitialActivity.getStartupFailureType(InitialActivity.java:3)
36 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.ichi2.anki.DeckPicker.handleStartup(DeckPicker.java:5)
37 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.ichi2.anki.DeckPicker.onRequestPermissionsResult(DeckPicker.java:5)
38 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8408)
39 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.Activity.dispatchActivityResult(Activity.java:8253)
40 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4953)
41 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5001)
42 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
43 | 05-17  13:52:58.539 W/AnkiDroid(21476): 	at  android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
44 | 05-17  13:52:58.539 W/AnkiDroid(21476): 	at  android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
45 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
46 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.os.Handler.dispatchMessage(Handler.java:107)
47 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.os.Looper.loop(Looper.java:221)
48 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.ActivityThread.main(ActivityThread.java:7584)
49 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at java.lang.reflect.Method.invoke(Native Method)
50 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
51 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
52 | 05-17 13:52:58.539 W/AnkiDroid(21476):
53 | 05-17  13:52:58.539 W/AnkiDroid(21476):  com.ichi2.anki.exception.StorageAccessException: Failed to create  AnkiDroid directory /storage/emulated/0/AnkiDroid
54 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.ichi2.anki.CollectionHelper.initializeAnkiDroidDirectory(CollectionHelper.java:3)
55 | 05-17  13:52:58.539 W/AnkiDroid(21476): 	at  com.ichi2.anki.CollectionHelper.isCurrentAnkiDroidDirAccessible(CollectionHelper.java:1)
56 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.ichi2.anki.InitialActivity.getStartupFailureType(InitialActivity.java:3)
57 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.ichi2.anki.DeckPicker.handleStartup(DeckPicker.java:5)
58 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.ichi2.anki.DeckPicker.onRequestPermissionsResult(DeckPicker.java:5)
59 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8408)
60 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.Activity.dispatchActivityResult(Activity.java:8253)
61 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4953)
62 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5001)
63 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
64 | 05-17  13:52:58.539 W/AnkiDroid(21476): 	at  android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
65 | 05-17  13:52:58.539 W/AnkiDroid(21476): 	at  android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
66 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
67 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.os.Handler.dispatchMessage(Handler.java:107)
68 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.os.Looper.loop(Looper.java:221)
69 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.ActivityThread.main(ActivityThread.java:7584)
70 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at java.lang.reflect.Method.invoke(Native Method)
71 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
72 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
73 | 05-17 13:52:58.545 I/AnkiDroid(21476): AnkiDroid directory inaccessible
74 | 05-17 13:52:58.579 I/AnkiDroid(21476): AnkiActivity::onResume - DeckPicker
75 | 05-17 13:52:58.604 I/AnkiDroid(21476): AnkiActivity::onPause - DeckPicker
76 | 05-17 13:52:58.704 I/AnkiDroid(21476): Adding open changelog
77 | 05-17 13:52:58.709 I/AnkiDroid(21476): Begin openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
78 | 05-17 13:52:58.719 I/AnkiDroid(21476): Opening rust backend. Server: false. Langs: 'en', path:
79 | 05-17 13:52:58.729 I/AnkiDroid(21476): Opening Collection: '/storage/emulated/0/AnkiDroid/collection.anki2' '' '' ''
80 | 05-17 13:52:58.758 I/AnkiDroid(21476): Opening Collection Log
81 | 05-17 13:52:58.771 I/AnkiDroid(21476): End openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
82 | 05-17 13:52:58.787 E/AnkiDroid(21476): Preferences/ Preferences: no preference found for the key: syncAccount
83 | 05-17 13:52:58.943 I/AnkiDroid(21476): AnkiActivity::onStop - DeckPicker
84 | 05-17 13:52:58.948 I/AnkiDroid(21476): flush - Saving information to DB...
85 | 05-17 13:52:58.949 I/AnkiDroid(21476): Rust: executeGetRowsAffected UPDATE col SET ls=?,crt=?,dty=?,mod=?,scm=?,usn=?,conf=?
86 | 05-17 13:53:06.390 I/AnkiDroid(21476): Handling Activity Result: 1. Result: 0
87 | 05-17 13:53:06.390 I/AnkiDroid(21476): Creating notification channel with id/name: General Notifications/AnkiDroid
88 | 05-17 13:53:06.394 I/AnkiDroid(21476): Creating notification channel with id/name: Synchronization/同步
89 | 05-17 13:53:06.396 I/AnkiDroid(21476): Creating notification channel with id/name: Global Reminders/卡片到期
90 | 05-17 13:53:06.397 I/AnkiDroid(21476): Creating notification channel with id/name: Deck Reminders/提醒
91 | 05-17 13:53:06.399 I/AnkiDroid(21476): finishWithoutAnimation
92 | 05-17 13:53:06.529 I/AnkiDroid(21476): AnkiActivity::onDestroy - DeckPicker
93 | 05-17 13:53:07.369 I/AnkiDroid(21476): Launching DeckPicker
94 | 05-17 13:53:07.398 I/AnkiDroid(21476): AnkiActivity::onCreate - DeckPicker
95 | 05-17 13:53:07.404 I/AnkiDroid(21476): Fresh install
96 | 05-17 13:53:07.465 I/AnkiDroid(21476): AnkiActivity::onStart - DeckPicker
97 | 05-17 13:53:07.470 I/AnkiDroid(21476): AnkiActivity::onResume - DeckPicker
98 | 05-17 13:53:07.477 I/AnkiDroid(21476): Updating deck list UI

```
```

**Comment by ShridharGoel** [comment]
I'll check and fix this.
