### ISSUE TITLE
V2.15.0. Causes Akebi to crash when trying to add word to Ankidroid. 

### ISSUE THREAD

**Issue by i-sy** [ankidroid/Anki-Android#8931]
Reproduction Steps

1. Find word in Akebi that is already in Anki database
2. Use Akebi function to send to Ankidroid
3. 

I have not tested if the same problem occurs with a word that is not yet in the Anki database

###### Expected Result
Akebi reports duplicate found or that word has been added.

###### Actual Result
No message. Akebi reloads at home page.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Logs aren't helpful

```
2021-05-25 14:42:22.586 5222-5242/com.ichi2.anki D/CardContentProvider: CardContentProvider.query /models/current (com.craxic.akebifree)
2021-05-25 14:42:22.597 5222-5304/com.ichi2.anki D/Collection: [1621950142] CardContentProvider.java:insert(): CardContentProvider.insert /models (com.craxic.akebifree)
2021-05-25 14:42:22.630 5222-5304/com.ichi2.anki I/Collection: flush - Saving information to DB...
2021-05-25 14:42:22.649 5222-5304/com.ichi2.anki D/Collection: [1621950142] CardContentProvider.java:update(): CardContentProvider.update /models/1621950142600/templates/0 (com.craxic.akebifree)
2021-05-25 14:42:22.665 5222-5304/com.ichi2.anki W/DB: Query INSERT INTO cards VALUES (?,?,?,?,?,?,0,0,?,0,0,0,0,0,0,0,0,"") called with a list of at most one element. Usually that's not expected.
2021-05-25 14:42:22.688 5222-5304/com.ichi2.anki I/Collection: flush - Saving information to DB...
2021-05-25 14:42:22.707 5222-5304/com.ichi2.anki D/CardContentProvider: CardContentProvider.query /models/1621950142600 (com.craxic.akebifree)
2021-05-25 14:42:22.721 5222-5242/com.ichi2.anki D/CardContentProvider: CardContentProvider.query /notes_v2 (com.craxic.akebifree)
2021-05-25 14:42:22.725 5222-5242/com.ichi2.anki E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    net.ankiweb.rsdroid.database.NotImplementedException
        at net.ankiweb.rsdroid.database.AnkiDatabaseCursor.registerContentObserver(AnkiDatabaseCursor.java:161)
        at android.database.CursorWrapper.registerContentObserver(CursorWrapper.java:221)
        at android.database.CursorToBulkCursorAdaptor.createAndRegisterObserverProxyLocked(CursorToBulkCursorAdaptor.java:269)
        at android.database.CursorToBulkCursorAdaptor.<init>(CursorToBulkCursorAdaptor.java:114)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:113)
        at android.os.Binder.execTransactInternal(Binder.java:1154)
        at android.os.Binder.execTransact(Binder.java:1123)
    
    
    --------- beginning of crash
```

**Comment by mikehardy** [comment]
There was some work with the API to better handle (we thought) internalization of resources etc - it seemed like a good way to get the API set up for scoped storage - and I believe that may have shipped first time with 2.15 - I think it will pay to get the API sample working against a 2.15 instance to see how it's going now as it appears we have multiple API consumers with issues, I'll look into that.

**Comment by david-allison-1** [comment]
This is on me: 

```
    net.ankiweb.rsdroid.database.NotImplementedException
        at net.ankiweb.rsdroid.database.AnkiDatabaseCursor.registerContentObserver(AnkiDatabaseCursor.java:161)
```

**Comment by mikehardy** [comment]
Ah ok - I'm opportunistically doing an I18N sync right now as I prep for 2.15.1. Need to do the changelog too. No pressure ever but you're clearly looking at this stuff now. Your opinion then: I can issue a 2.15.1 as soon as I have I18N+changelog, or I can async/await on you for this (with either try or catch blocks being fine based on what you find ;-) )

**Comment by david-allison-1** [comment]
> Likely that #8928 is duplicate then + same root cause?

Pleco works fine for me, but this is the underlying `ContentProvider`, so I presume they're related.

I can get a fix out in a couple of hours. I'm on the fence: whether we should wait, or go with the scheduler fix and follow up with this in 2.15.2

**Comment by mikehardy** [comment]
Okay - I'll troll for other crashes and see if I can get anything else in opportunistically. It's 9am my time, 12noon I'll check in and we can decide :muscle: :crossed_fingers:

**Comment by david-allison-1** [comment]
@mikehardy This might take a while, I don't want to hold up 2.15.1

Version numbers are free, so go for it, possibly with a "we're aware of a problem, and 2.15.2 will be out soon"

**Comment by mikehardy** [comment]
Roger!

**Comment by hanpingchinese** [comment]
Perhaps related: https://github.com/ankidroid/Anki-Android/issues/8957

My issue is also related to duplicates (i.e. my app queries anki to find out if a note has already been added, but the query returns a false negative and so we end up with a duplicate note). However, I'm not seeing any of those exceptions (presumably because I've already updated to 2.15.1).

**Comment by mikehardy** [comment]
@hanpingchinese - are you still seeing false negatives even after updating to 2.15.1? If so can you share any details of the code you use to query for duplicates? If it's failing for some reason we can add it to the automated test harness so that a) we can fix it and b) it never happens again :-)

It appears not a single one of our alpha our beta testers actually use the API from external dictionaries, which is surprising but explains how this slipped through on this release

**Comment by david-allison-1** [comment]
Perfect, thanks for the reply!

**Comment by lucwastiaux** [comment]
I'm seeing some occasional errors on AnkiReview with Ankidroid 2.15.2 (Attempt to invoke interface method 'boolean android.database.Cursor.moveToFirst()' on a null object reference), is this a known issue with the API ? I can try to put together a repro but doesn't seem to happen systematically.

**Comment by david-allison-1** [comment]
Not known, moving to a new issue. Sorry for the inconvenience.
