### ISSUE TITLE
[Bug] Collection created in 2.15 can't be opened in 2.14.6

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8945]
###### Reproduction Steps

1. Create collection in 2.15
2. Create Note
3. Open in 2.14.6
4. Review

###### Expected Result

Works

###### Actual Result

```
2021-05-25 20:33:47.416 9612-9612/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki.e, PID: 9612
    com.ichi2.utils.JSONException: org.json.JSONException: No value for req
        at com.ichi2.utils.JSONObject.get(JSONObject.java:2)
        at org.json.JSONObject.getJSONArray(JSONObject.java:595)
        at com.ichi2.utils.JSONObject.getJSONArray(JSONObject.java:2)
        at com.ichi2.libanki.Models.emptyCard(Models.java:3)
        at com.ichi2.libanki.Card.isEmpty(Card.java:1)
        at com.ichi2.anki.AbstractFlashcardViewer.displayString(AbstractFlashcardViewer.java:1)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:6)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1)
        at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:2)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:10)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:1)
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:4)
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:1)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:791)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: org.json.JSONException: No value for req
        at org.json.JSONObject.get(JSONObject.java:400)
        at com.ichi2.utils.JSONObject.get(JSONObject.java:1)
        at org.json.JSONObject.getJSONArray(JSONObject.java:595) 
        at com.ichi2.utils.JSONObject.getJSONArray(JSONObject.java:2) 
        at com.ichi2.libanki.Models.emptyCard(Models.java:3) 
        at com.ichi2.libanki.Card.isEmpty(Card.java:1) 
        at com.ichi2.anki.AbstractFlashcardViewer.displayString(AbstractFlashcardViewer.java:1) 
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:6) 
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1) 
        at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:2) 
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:10) 
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:1) 
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:4) 
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:1) 
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:791) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7660) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2021-05-25 20:33:47.418 9612-9612/? E/ACRA: ACRA caught a JSONException for com.ichi2.anki.e
    com.ichi2.utils.JSONException: org.json.JSONException: No value for req
        at com.ichi2.utils.JSONObject.get(JSONObject.java:2)
        at org.json.JSONObject.getJSONArray(JSONObject.java:595)
        at com.ichi2.utils.JSONObject.getJSONArray(JSONObject.java:2)
        at com.ichi2.libanki.Models.emptyCard(Models.java:3)
        at com.ichi2.libanki.Card.isEmpty(Card.java:1)
        at com.ichi2.anki.AbstractFlashcardViewer.displayString(AbstractFlashcardViewer.java:1)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:6)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1)
        at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:2)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:10)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:1)
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:4)
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:1)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:791)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: org.json.JSONException: No value for req
        at org.json.JSONObject.get(JSONObject.java:400)
        at com.ichi2.utils.JSONObject.get(JSONObject.java:1)
        at org.json.JSONObject.getJSONArray(JSONObject.java:595) 
        at com.ichi2.utils.JSONObject.getJSONArray(JSONObject.java:2) 
        at com.ichi2.libanki.Models.emptyCard(Models.java:3) 
        at com.ichi2.libanki.Card.isEmpty(Card.java:1) 
        at com.ichi2.anki.AbstractFlashcardViewer.displayString(AbstractFlashcardViewer.java:1) 
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:6) 
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1) 
        at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:2) 
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:10) 
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:1) 
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:4) 
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:1) 
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:791) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7660) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

**Comment by david-allison-1** [comment]
@Arthur-Milchior What does Anki Desktop do here?

**Comment by mikehardy** [comment]
I've read through database structure to learn what this chunk means.

Instrumented 2.14.6 and this is what is created on clean install for `req` for the default set of models in the default collection

```json

2021-05-25 15:25:46.987 14691-14691/com.ichi2.anki W/Models: Adding req for template: [
      [
        0,
        "all",
        [
          0
        ]
      ],
      [
        1,
        "all",
        [
          1,
          2
        ]
      ]
    ]
2021-05-25 15:25:46.993 14691-14691/com.ichi2.anki W/Models: Adding req for template: [
      [
        0,
        "all",
        [
          0
        ]
      ],
      [
        1,
        "all",
        [
          1
        ]
      ]
    ]
2021-05-25 15:25:46.997 14691-14691/com.ichi2.anki W/Models: Adding req for template: [
      [
        0,
        "all",
        [
          0
        ]
      ]
    ]
2021-05-25 15:25:47.004 14691-14691/com.ichi2.anki W/Models: Adding req for template: [
      [
        0,
        "all",
        [
          0
        ]
      ]
    ]
```

checking 2.15 now to see what it generates

**Comment by david-allison-1** [comment]
Likely related: https://github.com/ankidroid/Anki-Android/pull/7980/files#diff-c2ee46815a9845cdfdca8896c0676ea0f7e503cfe7203418b4b3b482fa49b94dL960

**Comment by mikehardy** [comment]
2.15 does not seem to generate a `req` JSON entry ever.

**Comment by dae** [comment]
https://forums.ankiweb.net/t/is-req-still-used-or-present/9977

**Comment by mikehardy** [comment]
@dae exactly the conclusion I just came to as the solution here, @david-allison-1 I'm restoring `_updateRequired` (which calls `_reqForTemplate` which still existed) and hooking it in where it used to be in `Models.save`

I've leave a note there with the link from Damien indicating we should be able to remove it in 2048 or so ;-) (I kid, maybe a year)
