### ISSUE TITLE
[Bug] 2.15 Crash TagsDialog not attached to a Context

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8973]
###### Reproduction Steps

* Add Note
* Tap Tags
* Tap Add
* Type in text box
* Leave AnkiDroid
* Restore AnkiDroid
* TextBox is still there, Tags Dialog has been removed
* Press "OK"
* Crash

###### Actual Result

On Android 11 AnkiDroid 2.15.1:

```
java.lang.IllegalStateException: Fragment TagsDialog{c83353f} (4c0ff020-c55f-4c86-8ad9-9748aa4e36f8) not attached to a context.
at androidx.fragment.app.Fragment.requireContext(Fragment.java:2)
at androidx.fragment.app.Fragment.getResources(Fragment.java:1)
at androidx.fragment.app.Fragment.getString(Fragment.java:2)
at com.ichi2.anki.dialogs.tags.TagsDialog.addTag(TagsDialog.java:7)
at com.ichi2.anki.dialogs.tags.TagsDialog.lambda$null$3(TagsDialog.java:1)
at com.ichi2.anki.dialogs.tags.TagsDialog.c(Unknown Source:0)
at com.ichi2.anki.dialogs.tags.d.onInput(Unknown Source:2)
at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:13)
at android.view.View.performClick(View.java:8160)
at android.widget.TextView.performClick(TextView.java:16220)
at android.view.View.performClickInternal(View.java:8137)
at android.view.View.access$3700(View.java:888)
at android.view.View$PerformClick.run(View.java:30236)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8512)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeI
```

```
no logcat :-(
```

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by prateek-singh-3212** [comment]
@mikehardy I have started working on this. Without logcat, I figured out that this issue is caused due to unhandled `requireActivity()` in the code. If possible, can you please share the logcat? should I make a PR after handling this exception?

https://github.com/ankidroid/Anki-Android/blob/cf53ad406da0afdd0c257a0623e2586e9271276a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.java#L208

**Comment by mikehardy** [comment]
There was no logcat in the crash report, sorry. I posted everything I had. It could be similar to the one near it #8972 ?

**Comment by david-allison-1** [comment]
Repro steps

* Add Note
* Tap Tags
* Tap Add
* Type in text box
* Leave AnkiDroid
* Open AnkiDroid
* TextBox is still there, Tags Dialog has been removed
* Press "OK"

```
2021-05-29 04:06:50.675 24418-24418/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 24418
    java.lang.IllegalStateException: Fragment TagsDialog{7759d21} (aeab739e-ca79-4735-9352-dab8bac8d1b6) not attached to a context.
        at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
        at androidx.fragment.app.Fragment.getResources(Fragment.java:964)
        at androidx.fragment.app.Fragment.getString(Fragment.java:999)
        at com.ichi2.anki.dialogs.tags.TagsDialog.addTag(TagsDialog.java:283)
        at com.ichi2.anki.dialogs.tags.TagsDialog.lambda$adjustToolbar$3$TagsDialog(TagsDialog.java:213)
        at com.ichi2.anki.dialogs.tags.-$$Lambda$TagsDialog$6PhrrCr6C3X737UarQIRq71QhIk.onInput(Unknown Source:2)
        at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:419)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by prateek-singh-3212** [comment]
Sorry! My bad. I didn't read the reproduction steps correctly.

**Comment by david-allison-1** [comment]
> Sorry! My bad. I didn't read the reproduction steps correctly. 🙇

I added it in when I made the comment. Not your fault! Thanks for the help
