### ISSUE TITLE
[RustV2] Handle upgrade to Database Schema v16

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8988]
Most of `rsdroid` requires that the database schema is upgraded to schema v16 from v11 before use.

Schema v16 splits a lot of the JSON columns in `col` into separate tables, and requires work to handle this

This is performed by the `openCollection` method.

Before this works, the "big 5" collection fields must handle an upgrade to v16, this means moving the classes to match the `.py` files in the fork of Anki that the backend uses: https://github.com/david-allison-1/anki/tree/ankidroid-2-1-34/pylib . 

- [ ] Decks
- [ ] Deck Config
- [ ] Config
- [ ] Models
- [ ] Tags

This should be a simple forward-conversion, but AnkiDroid-specific features and optimisations have been added to `libAnki`, which complicate matters

The schema upgrade should **not** be performed by default. As a first step the upgrade should be performed as an explicit operation in the settings.

This issue tracks working on the above, it should be closed when :

- [ ] We can upgrade a collection on v11 from the Advanced Settings
- [ ] We can load a v16 collection without crashing and without downgrading
- [ ] The documentation on https://github.com/ankidroid/Anki-Android/wiki/Database-Structure is updated

Next stage after this issue: 
* Ask the user if they want a new collection as v16 for testing
* A regression framework to perform tests on both v16 and v11

**Comment by david-allison-1** [comment]
I will be working on this in an iterative fashion:

* Convert a class (disregard compatibility with current code): DecksV16.kt
* define common abstract class defining the public API surface (AbstractDecks.kt)
* Make `Collection` expose said abstract class
* Convert `Decks.java` and `DecksV16.kt` to use the combined abstract class
* Define a `CollectionV16`, using the V16 implementations of the classes
* Test heavily

**Comment by david-allison-1** [comment]
Issues (personal checklist):

```
pp(mw.col.decks.new_filtered("aa"))
conf = mw.col.decks.confForDid(1631679468187)
pp(conf)
mw.col.decks.updateConf(conf)

Traceback (most recent call last):
  File "aqt\main.py", line 1524, in onDebugRet
  File "<string>", line 4, in <module>
  File "anki\decks.py", line 329, in update_config
  File "anki\_backend\generated.py", line 644, in add_or_update_deck_config_legacy
  File "anki\_backend\__init__.py", line 131, in _run_command
anki.errors.LocalizedError: JsonError("missing field `maxTaken` at line 1 column 270")
```

----

`get("a")` returns null in the Python, I converted to `jsonObject.getLong("a")`, which crashes

**Comment by david-allison-1** [comment]
Need a test: "update from V11 with an invalid template and see what happens in the note editor"

Previously, we were allowed invalid templates, now they can't be created
