### ISSUE TITLE
[Bug] 2.15.3 crashes when i try to open any deck

### ISSUE THREAD

**Issue by burbilog** [ankidroid/Anki-Android#9052]
###### Reproduction Steps

1. update to 2.15.3 from googe play
2. try to open any deck

###### Expected Result

daily routine with that deck

###### Actual Result

crash

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.15.3

Android Version = 8.1.0

Manufacturer = asus

Model = ZB602KL

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 8.1.0; ZB602KL Build/OPM1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

ACRA UUID = 4dfdc298-daf5-40b2-b282-348c9d00c870

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by burbilog** [comment]
Logcat:

~~~
06-02 22:17:35.643  9538  9538 E AndroidRuntime: Process: com.ichi2.anki, PID: 9538
06-02 22:17:35.643  9538  9538 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.StudyOptionsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.drawerlayout.widget.DrawerLayout.setDrawerShadow(int, int)' on a null object reference
06-02 22:17:35.643  9538  9538 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2781)
06-02 22:17:35.643  9538  9538 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
06-02 22:17:35.643  9538  9538 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
06-02 22:17:35.643  9538  9538 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
06-02 22:17:35.643  9538  9538 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
06-02 22:17:35.643  9538  9538 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
06-02 22:17:35.643  9538  9538 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6518)
06-02 22:17:35.643  9538  9538 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-02 22:17:35.643  9538  9538 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
06-02 22:17:35.643  9538  9538 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
06-02 22:17:35.643  9538  9538 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.drawerlayout.widget.DrawerLayout.setDrawerShadow(int, int)' on a null object reference
06-02 22:17:35.643  9538  9538 E AndroidRuntime:        at com.ichi2.anki.NavigationDrawerActivity.initNavigationDrawer(NavigationDrawerActivity.java:2)
06-02 22:17:35.643  9538  9538 E AndroidRuntime:        at com.ichi2.anki.StudyOptionsActivity.onCreate(StudyOptionsActivity.java:7)
06-02 22:17:35.643  9538  9538 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7013)
06-02 22:17:35.643  9538  9538 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7004)
06-02 22:17:35.643  9538  9538 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
06-02 22:17:35.643  9538  9538 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2734)
06-02 22:17:35.643  9538  9538 E AndroidRuntime:        ... 9 more
06-02 22:17:35.649  9538  9538 E ACRA    : ACRA caught a RuntimeException for com.ichi2.anki
06-02 22:17:35.649  9538  9538 E ACRA    : java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.StudyOptionsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.drawerlayout.widget.DrawerLayout.setDrawerShadow(int, int)' on a null object reference
06-02 22:17:35.649  9538  9538 E ACRA    :      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2781)
06-02 22:17:35.649  9538  9538 E ACRA    :      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
06-02 22:17:35.649  9538  9538 E ACRA    :      at android.app.ActivityThread.-wrap11(Unknown Source:0)
06-02 22:17:35.649  9538  9538 E ACRA    :      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
06-02 22:17:35.649  9538  9538 E ACRA    :      at android.os.Handler.dispatchMessage(Handler.java:106)
06-02 22:17:35.649  9538  9538 E ACRA    :      at android.os.Looper.loop(Looper.java:164)
06-02 22:17:35.649  9538  9538 E ACRA    :      at android.app.ActivityThread.main(ActivityThread.java:6518)
06-02 22:17:35.649  9538  9538 E ACRA    :      at java.lang.reflect.Method.invoke(Native Method)
06-02 22:17:35.649  9538  9538 E ACRA    :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
06-02 22:17:35.649  9538  9538 E ACRA    :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
06-02 22:17:35.649  9538  9538 E ACRA    : Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.drawerlayout.widget.DrawerLayout.setDrawerShadow(int, int)' on a null object reference
06-02 22:17:35.649  9538  9538 E ACRA    :      at com.ichi2.anki.NavigationDrawerActivity.initNavigationDrawer(NavigationDrawerActivity.java:2)
06-02 22:17:35.649  9538  9538 E ACRA    :      at com.ichi2.anki.StudyOptionsActivity.onCreate(StudyOptionsActivity.java:7)
06-02 22:17:35.649  9538  9538 E ACRA    :      at android.app.Activity.performCreate(Activity.java:7013)
06-02 22:17:35.649  9538  9538 E ACRA    :      at android.app.Activity.performCreate(Activity.java:7004)
06-02 22:17:35.649  9538  9538 E ACRA    :      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
06-02 22:17:35.649  9538  9538 E ACRA    :      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2734)
06-02 22:17:35.649  9538  9538 E ACRA    :      ... 9 more
~~~

**Comment by burbilog** [comment]
This problem began with 2.15.3, previous version from play market worked ok.

**Comment by mikehardy** [comment]
Thanks a bunch for the report! Looking into this now, it just launched minutes / 1 hour ago or so, this is most unexpected...

**Comment by mikehardy** [comment]
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3894)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:4077)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:91)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:149)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:103)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2458)
  at android.os.Handler.dispatchMessage (Handler.java:110)
  at android.os.Looper.loop (Looper.java:219)
  at android.app.ActivityThread.main (ActivityThread.java:8387)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1055)
Caused by: java.lang.NullPointerException: 
  at com.ichi2.anki.NavigationDrawerActivity.initNavigationDrawer (NavigationDrawerActivity.java:114)
  at com.ichi2.anki.StudyOptionsActivity.onCreate (StudyOptionsActivity.java:51)
  at android.app.Activity.performCreate (Activity.java:8121)
  at android.app.Activity.performCreate (Activity.java:8109)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1320)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3867)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:4077)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:91)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:149)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:103)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2458)
  at android.os.Handler.dispatchMessage (Handler.java:110)
  at android.os.Looper.loop (Looper.java:219)
  at android.app.ActivityThread.main (ActivityThread.java:8387)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1055)
```

**Comment by mikehardy** [comment]
Affected devices so far 

Huawei P30 Pro
Huawei HUAWEI Y9 2019
Realme realme 8
Huawei HUAWEI P30

**Comment by burbilog** [comment]
> appears from logcat it is a fragmented layout, this is likely tablet only

Ugh, it happens on my phone, not tablet.

**Comment by mikehardy** [comment]
@burbilog fragmented layout though? As in large phone and normally (when not crashing) the deck list layout has a panel next to it with details of the currently highlighted deck? That's the path I'm pursuing at the moment. All of the devices I listed above are "phones" as well, but not in the sense "phones" were phones in 2015, they're all large devices / phablets / near tablets from a layout perspective.

**Comment by mikehardy** [comment]
(all to say: technically I don't actually care what you call it: the fragmented layout part is the technical key to it)

**Comment by mikehardy** [comment]
Reproduced.
Fragmented layout is not the actual reproduction. It's the StudyOptions dialog in non-fragment mode. Quite odd - surprising so many people use that! There must be a more common pathway to that fragment then I'm used to.

@burbilog - just don't touch the three numbers on the right side of the deck list to start your review. Touch the name of the deck instead, and you'll be happily reviewing along.

**Comment by david-allison-1** [comment]
Tap the numbers on the deck to get there

**Comment by mikehardy** [comment]
@david-allison-1 exactly the opposite: tap the numbers on the deck to crash if that's what you want. Tap the deck name to study

**Comment by mikehardy** [comment]
Proximate cause #9015 - reverting that and releasing, it will need more work before adding the feature in again.

**Comment by mikehardy** [comment]
2.15.4 is rolling out now and is already available here @burbilog please confirm it works for you? It should - if not there is something else going on: https://github.com/ankidroid/Anki-Android/releases/tag/v2.15.4

Action plan for 2.15.5 on this one:

- There must be a test that fails on 2.15.3 (and it should fail on master as well?) via starting the study options fragment from deck picker via the review counts (to prove this can't happen again - this has been problematic in the past
- then fix the navigation drawer preference PR on master and enable the test
- merge that fix PR
- cherry-pick the navigation drawer gesture preference back to release-2.15 and the fix PR for it as well

Sound about right @david-allison-1 ?

**Comment by david-allison-1** [comment]
Sounds good to me - had a few planned tests in this area around the time of GSoC, but they didn't pan out with the candidates

**Comment by burbilog** [comment]
yes, 2.15.4 works ok

**Comment by mikehardy** [comment]
Fantastic thanks for the success report, sorry for the hassle, and huge thanks for the original error report. You were the first one in the tracker and that brought it to my attention so quickly most people will probably never know it happened! whew.
