### ISSUE TITLE
[Bug] RustBackendFailedException: .dynamic section header was not found

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#9064]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/6db5613a-2e8e-4bdc-9a62-7ee379eef696

AnkiDroid 2.15.2

```	
net.ankiweb.rsdroid.RustBackendFailedException: java.lang.UnsatisfiedLinkError: dlopen failed: "/mnt/expand/777b117c-5b78-4a6f-9f07-8bc8aec53e07/app/com.ichi2.anki-Ny8WxsXlSTf8p-R08CevQA==/lib/arm64/librsdroid.so" .dynamic section header was not found
at net.ankiweb.rsdroid.NativeMethods.ensureSetup(NativeMethods.java:9)
at net.ankiweb.rsdroid.BackendFactory.createInstance(BackendFactory.java:1)
at com.ichi2.libanki.backend.DroidBackendFactory.getInstance(DroidBackendFactory.java:2)
at com.ichi2.libanki.Storage.Collection(Storage.java:5)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:8)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:3)
at com.ichi2.anki.services.BootService.getColSafe(BootService.java:1)
at com.ichi2.anki.services.BootService.onReceive(BootService.java:5)
at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:37)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5906)
at android.app.ActivityThread.access$1100(ActivityThread.java:200)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1660)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6762)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/mnt/expand/777b117c-5b78-4a6f-9f07-8bc8aec53e07/app/com.ichi2.anki-Ny8WxsXlSTf8p-R08CevQA==/lib/arm64/librsdroid.so" .dynamic section header was not found
at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
at java.lang.System.loadLibrary(System.java:1669)
at net.ankiweb.rsdroid.NativeMethods.ensureSetup(NativeMethods.java:5)
... 18 more
```

**Comment by mikehardy** [comment]
Similar to the grouped error with unable to resolve version `""` from DT_NEEDED block, I think `readelf` might be used to conclusively show that the `.dynamic` header section was present in the build output, and then this exception should fall in the category of "delivery or unpack" error.

I *did* see one tiny mention somewhere of race conditions in the native library loader, with a suggested fix of using class static initializer to do the native library load, but I haven't investigated here - you may already be doing this?

**Comment by david-allison-1** [comment]
> I did see one tiny mention somewhere of race conditions in the native library loader, with a suggested fix of using class static initializer to do the native library load, but I haven't investigated here - you may already be doing this?

I'm not a fan of static initializers for things like that - it adds a lot of nondeterminism into the mix, and allows an exception from a few more places in the codebase. 

I'd like to hold off until we've investigated other possibilities (but do say the word and I'll change it).

**Comment by mikehardy** [comment]
> it adds a lot of nondeterminism into the mix

I thought - if done well - it made things exactly deterministic? Like, we make a ContentProvider that is set up for nothing but init with the highest priority load order (a common strategy, in practice) and in that ContentProvider we carefully load libraries while holding a static class lock or similar?

I'm not saying "the word" - I'm not sure that's exactly what we need to do - just saying if I hear some strategy to create determinism is deemed technically non-deterministic I don't understand, and I think it's an implementation detail issue

**Comment by dae** [comment]
Assuming this is rare, I guess it can be closed?
