### ISSUE TITLE
[Bug] RustBackendFailedException: dlopen failed: cannot find "" from verneed[0] in DT_NEEDED list

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#9065]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/15366710-1c54-466d-9e92-38b72461a1bf
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/38769600-79b4-4631-a2a6-d86475cdebab

```
net.ankiweb.rsdroid.RustBackendFailedException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot find "" from verneed[0] in DT_NEEDED list for "/data/app/~~U6kDiFxMXVRvvREzyUeQfg==/com.ichi2.anki.c-tj2D5f8psdlhEFmNNbJgOw==/lib/arm64/librsdroid.so"
at net.ankiweb.rsdroid.NativeMethods.ensureSetup(NativeMethods.java:9)
at net.ankiweb.rsdroid.BackendFactory.createInstance(BackendFactory.java:1)
at com.ichi2.libanki.backend.DroidBackendFactory.getInstance(DroidBackendFactory.java:2)
at com.ichi2.libanki.Storage.Collection(Storage.java:5)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:8)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:3)
at com.ichi2.anki.services.BootService.getColSafe(BootService.java:1)
at com.ichi2.anki.services.BootService.onReceive(BootService.java:5)
at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:37)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7507)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7446)
at android.app.ActivityThread.access$1500(ActivityThread.java:301)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2148)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8512)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot find "" from verneed[0] in DT_NEEDED list for "/data/app/~~U6kDiFxMXVRvvREzyUeQfg==/com.ichi2.anki.c-tj2D5f8psdlhEFmNNbJgOw==/lib/arm64/librsdroid.so"
at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
at java.lang.System.loadLibrary(System.java:1664)
at net.ankiweb.rsdroid.NativeMethods.ensureSetup(NativeMethods.java:5)
... 19 more
#################################################################
```

**Comment by mikehardy** [comment]
This appears to be an invalid DT_NEEDED entry based on my limited knowledge. There is a `readelf` tool with examples here https://android-developers.googleblog.com/2016/06/android-changes-for-ndk-developers.html - perhaps some investigation of the NDK build product (devices here are 64-bit, so ...the armv8-64 product?)  to verify that DT_NEEDED entries do have versions would indicate that this is an unpack error and thus out of our control really?

If so then transition to pure-Rust backend with no fallback seems to need a dialog indicating that a really rare, really low-level error happened and we think first a restart then if not working perhaps an uninstall/reinstall will fix it but feel free to get in touch or similar?

**Comment by david-allison-1** [comment]
Extracted the universal apk for 2.15.2 and looked in `lib/arm64-v8a`

```
readelf --dynamic librsdroid.so | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so]
```

I'm out of my depth here, but from the article above, looks good to me

**Comment by mikehardy** [comment]
How to inspect the "verneed" array so that we have the other side of the pointer? I'm 99.999% sure the compilation product produced by build chain here is valid FWIW, this is really just educational in my mind. Always "fun" to learn about .so structure etc and (re-)learn how the machine is actually working under all the abstraction

**Comment by david-allison-1** [comment]
`verneed` is C++ code: 

https://android.googlesource.com/platform/bionic/+/o-preview/linker/linker.cpp#2232

```cpp
    const ElfW(Verneed)* verneed = reinterpret_cast<ElfW(Verneed)*>(verneed_ptr + offset);
    size_t vernaux_offset = offset + verneed->vn_aux;
    offset += verneed->vn_next;
    if (verneed->vn_version != 1) {
      DL_ERR("unsupported verneed[%zd] vn_version: %d (expected 1)", i, verneed->vn_version);
      return false;
    }
    const char* target_soname = si_from->get_string(verneed->vn_file);
    // find it in dependencies
    soinfo* target_si = si_from->get_children().find_if([&](const soinfo* si) {
      return si->get_soname() != nullptr && strcmp(si->get_soname(), target_soname) == 0;
    });
    if (target_si == nullptr) {
      DL_ERR("cannot find \"%s\" from verneed[%zd] in DT_NEEDED list for \"%s\"",
          target_soname, i, si_from->get_realpath());
      return false;
    }
```

From the error message, target_soname` is blank (or null?).

Verneed appears to be:

```cpp
typedef struct {
  Elf32_Half vn_version;
  Elf32_Half vn_cnt;
  Elf32_Word vn_file;
  Elf32_Word vn_aux;
  Elf32_Word vn_next;
} Elf32_Verneed;
```

https://android.googlesource.com/platform/bionic/+/master/libc/include/elf.h#163

**Comment by mikehardy** [comment]
So the error seems to be in advance of the first C++ chunk there, 

```c++
    const ElfW(Verneed)* verneed = reinterpret_cast<ElfW(Verneed)*>(verneed_ptr + offset);
```

is somehow returning a verneed struct with a bogus vn_file. 

It does not appear to make sense in the context of nearly every device working unless it is some kind of rare loader race, but then it should show up at other apps that have more scale than us? And even playing around with search terms I get effectively a zero when looking. I dunno. Obviously a show stopper for the affected user on that start of the app at minimum but still doesn't feel like a show stopper at this incidence frequency. Would be nice to know (via proposed analytics either here or in some other issue, sorry I forget) if it self-heals on app restart, or if that user is hosed for that install or for that device.

**Comment by dae** [comment]
Assuming this is rare, I guess it can be closed?
