### ISSUE TITLE
[Bug] RustBackendFailedException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList] couldn't find "librsdroid.so"

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#9067]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/79dd3de0-7379-4b3b-9cb7-5878e5e0169f
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/f52f635d-c3a4-4717-a00d-eb926fc1385a

```
net.ankiweb.rsdroid.RustBackendFailedException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ichi2.anki-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ichi2.anki-1/lib/arm, /data/app/com.ichi2.anki-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "librsdroid.so"
at net.ankiweb.rsdroid.NativeMethods.ensureSetup(NativeMethods.java:9)
at net.ankiweb.rsdroid.BackendFactory.createInstance(BackendFactory.java:1)
at com.ichi2.libanki.backend.DroidBackendFactory.getInstance(DroidBackendFactory.java:2)
at com.ichi2.libanki.Storage.Collection(Storage.java:5)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:8)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:3)
at com.ichi2.anki.services.BootService.getColSafe(BootService.java:1)
at com.ichi2.anki.services.BootService.onReceive(BootService.java:5)
at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:37)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5578)
at android.app.ActivityThread.-wrap2(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1596)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6313)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ichi2.anki-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ichi2.anki-1/lib/arm, /data/app/com.ichi2.anki-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "librsdroid.so"
at java.lang.Runtime.loadLibrary0(Runtime.java:972)
at java.lang.System.loadLibrary(System.java:1530)
at net.ankiweb.rsdroid.NativeMethods.ensureSetup(NativeMethods.java:5)
... 18 more
```

**Comment by mikehardy** [comment]
Hmm - of interest - the two you mention are Android 7/7.1... an Android 7 thing? One LG one Huawei though.

```

$resolved | TRUE
-- | --
ANDROID_VERSION | 7.0
APP_VERSION_CODE | 121501300
APP_VERSION_NAME | 2.15.1
AVAILABLE_MEM_SIZE | 8714366976
BRAND | lge
BUILD | BOARDmsm8937_32BOOTLOADERunknownBRANDlgeCPU_ABIarmeabi-v7aCPU_ABI2armeabiDEVICEsf317DISPLAYNRD90UFINGERPRINTlge/sf317_trf_us_vzw/sf317:7.0/NRD90U/173191700b287:user/release-keysHARDWAREsf317HOSTLGEACI6R6IDNRD90UIS_DEBUGGABLEFALSEIS_EMULATORFALSEMANUFACTURERLGEMODELLGL84VL | BOARD | msm8937_32 | BOOTLOADER | unknown | BRAND | lge | CPU_ABI | armeabi-v7a | CPU_ABI2 | armeabi | DEVICE | sf317 | DISPLAY | NRD90U | FINGERPRINT | lge/sf317_trf_us_vzw/sf317:7.0/NRD90U/173191700b287:user/release-keys | HARDWARE | sf317 | HOST | LGEACI6R6 | ID | NRD90U | IS_DEBUGGABLE | FALSE | IS_EMULATOR | FALSE | MANUFACTURER | LGE | MODEL | LGL84VL
BOARD | msm8937_32
BOOTLOADER | unknown
BRAND | lge
CPU_ABI | armeabi-v7a
CPU_ABI2 | armeabi
DEVICE | sf317
DISPLAY | NRD90U
FINGERPRINT | lge/sf317_trf_us_vzw/sf317:7.0/NRD90U/173191700b287:user/release-keys
HARDWARE | sf317
HOST | LGEACI6R6
ID | NRD90U
IS_DEBUGGABLE | FALSE
IS_EMULATOR | FALSE
MANUFACTURER | LGE
MODEL | LGL84VL
PERMISSIONS_REVIEW_REQUIRED | FALSE
PRODUCT | sf317_trf_us_vzw


```


```

$resolved | TRUE
-- | --
ANDROID_VERSION | 7.1.2
APP_VERSION_CODE | 321500206
APP_VERSION_NAME | 2.15.0beta6
AVAILABLE_MEM_SIZE | 11533942784
BRAND | HUAWEI
BUILD | BOARDLYA-AL10BOOTLOADERunknownBRANDHUAWEICPU_ABIx86CPU_ABI2armeabi-v7aDEVICEaospDISPLAYN2G47HFINGERPRINTgoogle/android_x86/x86:7.1.2/N2G47H/G955FXXU1AQJ5:/release-keysHARDWAREandroid_x86HOSTubuntuIDN2G47HIS_DEBUGGABLETRUEIS_EMULATORFALSEMANUFACTURERHUAWEIMODELLYA-AL10PERMISSIONS_REVIEW_REQUIREDFALSEPRODUCTLYA-AL10 | BOARD | LYA-AL10 | BOOTLOADER | unknown | BRAND | HUAWEI | CPU_ABI | x86 | CPU_ABI2 | armeabi-v7a | DEVICE | aosp | DISPLAY | N2G47H | FINGERPRINT | google/android_x86/x86:7.1.2/N2G47H/G955FXXU1AQJ5:/release-keys | HARDWARE | android_x86 | HOST | ubuntu | ID | N2G47H | IS_DEBUGGABLE | TRUE | IS_EMULATOR | FALSE | MANUFACTURER | HUAWEI | MODEL | LYA-AL10 | PERMISSIONS_REVIEW_REQUIRED | FALSE | PRODUCT | LYA-AL10
BOARD | LYA-AL10
BOOTLOADER | unknown
BRAND | HUAWEI
CPU_ABI | x86
CPU_ABI2 | armeabi-v7a
DEVICE | aosp
DISPLAY | N2G47H
FINGERPRINT | google/android_x86/x86:7.1.2/N2G47H/G955FXXU1AQJ5:/release-keys
HARDWARE | android_x86
HOST | ubuntu
ID | N2G47H
IS_DEBUGGABLE | TRUE
IS_EMULATOR | FALSE
MANUFACTURER | HUAWEI
MODEL | LYA-AL10
PERMISSIONS_REVIEW_REQUIRED | FALSE
PRODUCT | LYA-AL10


```

Vanishingly rare in practice it seems, 2 devices out of the while 2.15.x release series? Could do with more analytics perhaps but this is more rare than "IO failure" / disk is full (and in practice might actually be that - failed unpack or something - we don't track disk free in crashes but could perhaps...)

**Comment by dae** [comment]
Assuming this is rare, I guess it can be closed?

**Comment by mikehardy** [comment]
Yes - there is only one item left that I really want, and that is to add space free/used as I think even the ones that couldn't load it are probably trace-able to lack of disk space for APK unpack, and it would help show that as the exception is reported (when it is, which is rare) - it's tracked #9097
