### ISSUE TITLE
[Bug] crash after return from custom study 

### ISSUE THREAD

**Issue by Akshay0701** [ankidroid/Anki-Android#9078]
###### Reproduction Steps

1. open custom study activity 
2. back to deck Picker (using phone back button)

###### Expected Result
no Crash 

###### Actual Result
Crash on Navigation isDrawerOpen method 
```2021-06-05 19:49:51.708 8250-8250/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 8250
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.drawerlayout.widget.DrawerLayout.isDrawerOpen(int)' on a null object reference
        at com.ichi2.anki.NavigationDrawerActivity.isDrawerOpen(NavigationDrawerActivity.java:452)
        at com.ichi2.anki.NavigationDrawerActivity.onKeyDown(NavigationDrawerActivity.java:496)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2842)
        at android.app.Activity.dispatchKeyEvent(Activity.java:4096)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:599)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3068)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:412)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6397)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6265)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5735)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5792)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5758)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5910)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5766)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5967)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5739)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5792)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5758)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5766)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5739)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5792)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5758)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5943)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6101)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3241)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2783)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2774)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3218)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:183)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
likely duplicate o the whole mess off #9052 - @Akshay0701 please stop logging crashes related to drawer layout until this is fully resolved, just a couple more days
