### ISSUE TITLE
[Bug] Error opening collectin on Android 12 Beta

### ISSUE THREAD

**Issue by mots** [ankidroid/Anki-Android#9107]
###### Reproduction Steps

1. Install Android 12 beta
2. Open Ankidroid
3. See error opening collection.

###### Expected Result
App opens

###### Actual Result
App doesnt open, cites an error opening collection

###### Debug info

Here's the logcat output:
	```
12:50:09.765	AnkiDroid		CollectionHelper/ Failed to query version
com.ichi2.libanki.exception.UnknownDatabaseVersionException: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.ichi2.libanki.DB.queryScalar(java.lang.String, java.lang.Object[])' on a null object reference
	at com.ichi2.libanki.Collection.queryVer(Collection.java:2)
	at com.ichi2.anki.CollectionHelper.getDatabaseVersion(CollectionHelper.java:2)
	at com.ichi2.anki.CollectionHelper.isFutureAnkiDroidVersion(CollectionHelper.java:1)
	at com.ichi2.anki.InitialActivity.isFutureAnkiDroidVersion(InitialActivity.java:1)
	at com.ichi2.anki.InitialActivity.getStartupFailureType(InitialActivity.java:5)
	at com.ichi2.anki.DeckPicker.handleStartup(DeckPicker.java:5)
	at com.ichi2.anki.DeckPicker.onCreate(DeckPicker.java:6)
	at android.app.Activity.performCreate(Activity.java:8036)
	at android.app.Activity.performCreate(Activity.java:8016)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3581)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3765)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:102)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2193)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7796)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.ichi2.libanki.DB.queryScalar(java.lang.String, java.lang.Object[])' on a null object reference
	at com.ichi2.libanki.Collection.queryVer(Collection.java:1)
	... 22 more

com.ichi2.libanki.exception.UnknownDatabaseVersionException: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.ichi2.libanki.DB.queryScalar(java.lang.String, java.lang.Object[])' on a null object reference
	at com.ichi2.libanki.Collection.queryVer(Collection.java:2)
	at com.ichi2.anki.CollectionHelper.getDatabaseVersion(CollectionHelper.java:2)
	at com.ichi2.anki.CollectionHelper.isFutureAnkiDroidVersion(CollectionHelper.java:1)
	at com.ichi2.anki.InitialActivity.isFutureAnkiDroidVersion(InitialActivity.java:1)
	at com.ichi2.anki.InitialActivity.getStartupFailureType(InitialActivity.java:5)
	at com.ichi2.anki.DeckPicker.handleStartup(DeckPicker.java:5)
	at com.ichi2.anki.DeckPicker.onCreate(DeckPicker.java:6)
	at android.app.Activity.performCreate(Activity.java:8036)
	at android.app.Activity.performCreate(Activity.java:8016)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3581)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3765)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:102)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2193)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7796)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
```
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
This is a known issue and it will result in a total cannot-be-worked-around failure on Android 12 unfortunately

Related issue where we track the need to migrate to "Scoped Storage" - https://github.com/ankidroid/Anki-Android/issues/5304

It's actually the subject of work for one of our two Google Summer of Code slots, it's being worked on already, but it won't be ready for quite some time.

Until that issue is resolved you cannot use Android 12 beta

**Comment by mots** [comment]
Oh snap, I should've figured this is related to scoped storage being enforced on SDK30. Wonder if I can just hack it to use `getExternalStorage` instead of whatever path it tries to open right now and compile that for myself so I have a working version while y'all figure out a "proper" design...

I work on Android myself and would help out with that myself if I had the bandwidth and nobody was working on it yet, heh

**Comment by mots** [comment]
Alright, that worked, yay.

If anyone else  wants to unblock themselves in a hacky way for now - changing `CollectionHelper#getCurrentAnkiDroidDirectory` to `return context.getExternalFilesDir(null).getAbsolutePath();` will make the app work again. Of course, that means you'll start again with an empty collection, but if you're using ankiweb, you can just resync your collection into the new path :)

**Comment by mikehardy** [comment]
Yes - the actual code change is tiny. The hard part is migrating 2 million users precious data - we're taking that seriously
Glad you go that working! 
If you wanted to post a PR with your change I could compile a parallel release APK for other people that aren't Android-savvy and everyone would benefit from the stopgap if they happened to be playing with the beta for whatever reason

**Comment by mikehardy** [comment]
It's something I will note in **GREAT BIG LETTERS** to be careful with data, I don't imagine a lot of people will use any parallel APK I generate for the case but I'm also certain there will be some :-). I'm not sure how many use AnkiWeb actually, I want to say "most" but I have not inspected our usage data to see if we even collect that actually, much less what the number is :sweat_smile:
