### ISSUE TITLE
[Bug] 2.16alpha2: App crashes if phone volume is changed while reviewing

### ISSUE THREAD

**Issue by guimcaballero** [ankidroid/Anki-Android#9164]
###### Reproduction Steps

1. Enter any deck and start reviewing a card
2. Change the phone's volume using the physical buttons on the side

###### Expected Result

App shouldn't crash

###### Actual Result

App crashes (volume does change)

###### Other info

Doesn't seem to happen on any other screen, just on review. Happens both for cards with and without audio. 

###### Debug info

```
AnkiDroid Version = 2.16alpha2

Android Version = 10

Manufacturer = OnePlus

Model = ONEPLUS A6013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; ONEPLUS A6013 Build/QKQ1.190716.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.120 Mobile Safari/537.36

ACRA UUID = 72fe91db-f17e-4605-93af-7e4b52efffbd

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
There was a gesture mapping change integrated recently #9021 that is the likely culprit

> App crashes (volume does change)

Well, at least we didn't break the volume button itself :sweat_smile: 

The debug info was a big help, it allowed me to pull the crash trace, thank you!

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/2a82f67a-a431-41d7-8901-8da36864a220


```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Enum.ordinal()' on a null object reference
at com.ichi2.anki.AbstractFlashcardViewer.executeCommand(AbstractFlashcardViewer.java:2)
at com.ichi2.anki.AbstractFlashcardViewer.dispatchKeyEvent(AbstractFlashcardViewer.java:6)
at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2)
at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:1)
at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:374)
at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5763)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5631)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5131)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5184)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5150)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5290)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5158)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5347)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5131)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5184)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5150)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5158)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5131)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5184)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5150)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5323)
at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5484)
at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3089)
at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2632)
at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2623)
at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3066)
at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:336)
at android.os.Looper.loop(Looper.java:174)
at android.app.ActivityThread.main(ActivityThread.java:7682)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

logcat
```


0 | --------- beginning of main
-- | --
1 | 06-29 21:09:07.835 I/AnkiDroid( 2124): Sync: applying chunked data
2 | 06-29 21:09:07.835 I/AnkiDroid( 2124): Sync: collecting chunked data
3 | 06-29 21:09:07.843 I/AnkiDroid( 2124): Sync: sending chunked data
4 | 06-29 21:09:08.083 I/AnkiDroid( 2124): ExecuteCommand: localMinutesWest
5 | 06-29 21:09:08.085 I/AnkiDroid( 2124): ExecuteCommand: localMinutesWest
6 | 06-29 21:09:08.237 I/AnkiDroid( 2124): Sync: sending finish command
7 | 06-29 21:09:08.366 I/AnkiDroid( 2124): Sync: finishing
8 | 06-29 21:09:08.382 I/AnkiDroid( 2124): Rust: executeGetRowsAffected UPDATE col SET models=?
9 | 06-29 21:09:08.395 I/AnkiDroid( 2124): Rust: executeGetRowsAffected UPDATE col SET dconf=?,decks=?
10 | 06-29 21:09:08.402 I/AnkiDroid( 2124): Rust: executeGetRowsAffected UPDATE col SET tags=?
11 | 06-29 21:09:08.405 I/AnkiDroid( 2124): flush - Saving information to DB...
12 | 06-29 21:09:08.405 I/AnkiDroid( 2124): Rust: executeGetRowsAffected UPDATE col SET ls=?,crt=?,dty=?,mod=?,scm=?,usn=?,conf=?
13 | 06-29 21:09:08.406 I/AnkiDroid( 2124): Rust: transaction commit
14 | 06-29 21:09:08.419 I/AnkiDroid( 2124): Sync - Performing media sync
15 | 06-29 21:09:08.682 I/AnkiDroid( 2124): Sync Finished - Closing Collection
16 | 06-29 21:09:08.682 W/AnkiDroid( 2124): DB/ Not in a transaction. Cannot end transaction.
17 | 06-29 21:09:08.683 I/AnkiDroid( 2124): ExecuteCommand: closeCollection
18 | 06-29 21:09:08.697 I/AnkiDroid( 2124): Closing Collection Log
19 | 06-29 21:09:08.697 I/AnkiDroid( 2124): Collection closed
20 | 06-29 21:09:08.697 I/AnkiDroid( 2124): Unlocked Collection
21 | 06-29  21:09:08.734 I/AnkiDroid( 2124): Sync Listener: onPostExecute: Data:  Payload{mTaskType=1, data=[null, com.ichi2.libanki.Collection@630ca50,  null], resultType=null, result=null, success=true, returnType=0,  exception=null, message=''}
22 | 06-29 21:09:08.734 I/AnkiDroid( 2124): Sync was successful
23 | 06-29 21:09:08.734 I/AnkiDroid( 2124): Regular sync completed successfully
24 | 06-29 21:09:08.746 I/AnkiDroid( 2124): Begin openCollection: /sdcard/AnkiDroid/collection.anki2
25 | 06-29 21:09:08.746 I/AnkiDroid( 2124): Opening rust backend. Server: false. Langs: 'en', path:
26 | 06-29 21:09:08.749 I/AnkiDroid( 2124): Opening Collection: '/sdcard/AnkiDroid/collection.anki2' '' '' ''
27 | 06-29 21:09:08.773 I/AnkiDroid( 2124): Opening Collection Log
28 | 06-29 21:09:08.795 I/AnkiDroid( 2124): ExecuteCommand: localMinutesWest
29 | 06-29 21:09:08.796 I/AnkiDroid( 2124): ExecuteCommand: localMinutesWest
30 | 06-29 21:09:08.796 I/AnkiDroid( 2124): End openCollection: /sdcard/AnkiDroid/collection.anki2
31 | 06-29 21:09:08.862 I/AnkiDroid( 2124): Updating deck list UI
32 | 06-29 21:09:08.914 I/AnkiDroid( 2124): NotificationService: OnStartCommand
33 | 06-29 21:09:11.695 I/AnkiDroid( 2124): Pull to Sync: Syncing
34 | 06-29 21:09:11.721 I/AnkiDroid( 2124): Locked Collection - Collection Loading should fail
35 | 06-29 21:09:11.722 I/AnkiDroid( 2124): Sync - starting sync
36 | 06-29 21:09:11.722 I/AnkiDroid( 2124): ExecuteCommand: localMinutesWest
37 | 06-29 21:09:12.010 I/AnkiDroid( 2124): Rust: transaction begin
38 | 06-29 21:09:12.011 I/AnkiDroid( 2124): Sync: getting meta data from server
39 | 06-29 21:09:12.013 I/AnkiDroid( 2124): Sync: building local meta data
40 | 06-29 21:09:12.013 I/AnkiDroid( 2124): Sync: no changes - returning
41 | 06-29 21:09:12.014 I/AnkiDroid( 2124): Rust: transaction rollback
42 | 06-29 21:09:12.015 I/AnkiDroid( 2124): Sync - Performing media sync
43 | 06-29 21:09:12.238 I/AnkiDroid( 2124): Sync Finished - Closing Collection
44 | 06-29 21:09:12.238 W/AnkiDroid( 2124): DB/ Not in a transaction. Cannot end transaction.
45 | 06-29 21:09:12.238 I/AnkiDroid( 2124): ExecuteCommand: closeCollection
46 | 06-29 21:09:12.244 I/AnkiDroid( 2124): Closing Collection Log
47 | 06-29 21:09:12.244 I/AnkiDroid( 2124): Collection closed
48 | 06-29 21:09:12.244 I/AnkiDroid( 2124): Unlocked Collection
49 | 06-29  21:09:12.271 I/AnkiDroid( 2124): Sync Listener: onPostExecute: Data:  Payload{mTaskType=1, data=[qmxyHDPtk8RY4buA, true, null,  com.ichi2.anki.web.PreferenceBackedHostNum@856b46c],  resultType=noChanges, result=[], success=false, returnType=0,  exception=null, message=''}
50 | 06-29 21:09:24.400 I/AnkiDroid( 2124): DeckPicker:: Selected deck with id 1560590443009
51 | 06-29 21:09:24.401 I/AnkiDroid( 2124): Begin openCollection: /sdcard/AnkiDroid/collection.anki2
52 | 06-29 21:09:24.402 I/AnkiDroid( 2124): Opening rust backend. Server: false. Langs: 'en', path:
53 | 06-29 21:09:24.405 I/AnkiDroid( 2124): Opening Collection: '/sdcard/AnkiDroid/collection.anki2' '' '' ''
54 | 06-29 21:09:24.440 I/AnkiDroid( 2124): Opening Collection Log
55 | 06-29 21:09:24.450 I/AnkiDroid( 2124): ExecuteCommand: localMinutesWest
56 | 06-29 21:09:24.451 I/AnkiDroid( 2124): ExecuteCommand: localMinutesWest
57 | 06-29 21:09:24.451 I/AnkiDroid( 2124): End openCollection: /sdcard/AnkiDroid/collection.anki2
58 | 06-29 21:09:24.463 I/AnkiDroid( 2124): AnkiActivity::onPause - DeckPicker
59 | 06-29 21:09:24.495 I/AnkiDroid( 2124): AnkiActivity::onCreate - Reviewer
60 | 06-29 21:09:24.560 I/AnkiDroid( 2124): Obtaining card
61 | 06-29 21:09:24.561 I/AnkiDroid( 2124): ViewGroupUtils::setRenderWorkaround - using default / hardware rendering
62 | 06-29 21:09:24.562 I/AnkiDroid( 2124): AnkiActivity::onStart - Reviewer
63 | 06-29 21:09:24.567 I/AnkiDroid( 2124): AnkiActivity::onResume - Reviewer
64 | 06-29 21:09:24.567 E/AnkiDroid( 2124): Threads/ must be called on the main thread instead of Thread[AsyncTask #3,5,main]
65 | 06-29 21:09:24.567 E/AnkiDroid( 2124): Threads/ must be called on the main thread instead of Thread[AsyncTask #3,5,main]
66 | 06-29 21:09:24.577 I/AnkiDroid( 2124): ExecuteCommand: localMinutesWest
67 | 06-29 21:09:24.657 I/AnkiDroid( 2124): ViewGroupUtils::setRenderWorkaround - using default / hardware rendering
68 | 06-29 21:09:24.732 I/AnkiDroid( 2124): AbstractFlashcardViewer:: Question successfully shown for card id 1352726743147
69 | 06-29 21:09:24.860 I/AnkiDroid( 2124): AnkiActivity::onStop - DeckPicker
70 | 06-29 21:09:24.924 I/AnkiDroid( 2124): flush - Saving information to DB...
71 | 06-29 21:09:24.924 I/AnkiDroid( 2124): Rust: executeGetRowsAffected UPDATE col SET ls=?,crt=?,dty=?,mod=?,scm=?,usn=?,conf=?
72 | 06-29 21:09:24.932 I/AnkiDroid( 2124): NotificationService: OnStartCommand
73 | 06-29 21:09:25.715 I/AnkiDroid( 2124): Play all: Completed - releasing sound
74 | --------- beginning of crash


```

**Comment by guimcaballero** [comment]
Some more testing I've done: while previewing a card through the Card Browser, it doesn't crash but the volume does not change. Not sure if this is intentional and/or related.

**Comment by david-allison-1** [comment]
That's on me. I'll get on it ASAP. Thanks!
