### ISSUE TITLE
[Bug] Crash on opening deck - Media Missing

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#9401]
```
2021-08-12 14:09:05.570 3485-3485/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 3485
    java.lang.IllegalArgumentException: Illegal null AudioFocusRequest
        at android.media.AudioManager.abandonAudioFocusRequest(AudioManager.java:3144)
        at com.ichi2.compat.CompatV26.abandonAudioFocus(CompatV26.java:154)
        at com.ichi2.libanki.Sound.releaseSound(Sound.java:523)
        at com.ichi2.libanki.Sound.playSoundInternal(Sound.java:400)
        at com.ichi2.libanki.Sound.playSounds(Sound.java:255)
        at com.ichi2.anki.AbstractFlashcardViewer.playSounds(AbstractFlashcardViewer.java:2447)
        at com.ichi2.anki.AbstractFlashcardViewer.playSounds(AbstractFlashcardViewer.java:2424)
        at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:2397)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:2161)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:2119)
        at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:1051)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:672)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:644)
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:217)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:791)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by david-allison-1** [comment]
```
2021-08-12 14:08:58.862 3485-3485/com.ichi2.anki I/ACRA: ACRA is disabled for com.ichi2.anki, initializing...
2021-08-12 14:08:58.905 3485-3485/com.ichi2.anki I/UsageAnalytics: initialize()
2021-08-12 14:08:58.951 3485-3485/com.ichi2.anki I/WebViewFactory: Loading com.google.android.webview version 92.0.4515.131 (code 451513133)
2021-08-12 14:08:59.023 3485-3485/com.ichi2.anki W/com.ichi2.anki: Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (greylist, reflection, allowed)
2021-08-12 14:08:59.023 3485-3485/com.ichi2.anki W/com.ichi2.anki: Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (greylist, reflection, allowed)
2021-08-12 14:08:59.023 3485-3485/com.ichi2.anki W/com.ichi2.anki: Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (greylist, reflection, allowed)
2021-08-12 14:08:59.023 3485-3485/com.ichi2.anki W/com.ichi2.anki: Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (greylist, reflection, allowed)
2021-08-12 14:08:59.023 3485-3485/com.ichi2.anki W/com.ichi2.anki: Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)
2021-08-12 14:08:59.029 3485-3485/com.ichi2.anki I/cr_WVCFactoryProvider: Loaded version=92.0.4515.131 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
2021-08-12 14:08:59.053 3485-3485/com.ichi2.anki I/cr_LibraryLoader: Successfully loaded native library
2021-08-12 14:08:59.054 3485-3485/com.ichi2.anki I/cr_CachingUmaRecorder: Flushed 8 samples from 8 histograms.
2021-08-12 14:08:59.059 3485-3485/com.ichi2.anki I/TetheringManager: registerTetheringEventCallback:com.ichi2.anki
2021-08-12 14:08:59.352 3485-3485/com.ichi2.anki I/GoogleAnalyticsImpl: Not participating in analytics sample (sample percentage vs random: 10 11)
2021-08-12 14:08:59.353 3485-3485/com.ichi2.anki I/UsageAnalytics: setOptIn(): from false to false
2021-08-12 14:08:59.353 3485-3485/com.ichi2.anki I/GoogleAnalyticsImpl: Not participating in analytics sample (sample percentage vs random: 10 52)
2021-08-12 14:08:59.354 3485-3485/com.ichi2.anki I/UsageAnalytics: setDryRun(): true, warning dryRun is experimental
2021-08-12 14:08:59.366 3485-3485/com.ichi2.anki I/CompatV26: Creating notification channel with id/name: General Notifications/AnkiDroid
2021-08-12 14:08:59.368 3485-3485/com.ichi2.anki I/CompatV26: Creating notification channel with id/name: Synchronization/Synchronization
2021-08-12 14:08:59.370 3485-3485/com.ichi2.anki I/CompatV26: Creating notification channel with id/name: Global Reminders/Cards due
2021-08-12 14:08:59.371 3485-3485/com.ichi2.anki I/CompatV26: Creating notification channel with id/name: Deck Reminders/Reminders
2021-08-12 14:08:59.413 3485-3485/com.ichi2.anki I/AnkiDroidApp: AnkiDroidApp: Starting Services
2021-08-12 14:08:59.417 3485-3485/com.ichi2.anki I/CollectionHelper: Begin openCollection: /storage/emulated/0/AnkiDroid (1)/collection.anki2
2021-08-12 14:09:00.483 3485-3485/com.ichi2.anki I/Collection: Opening Collection Log
2021-08-12 14:09:00.615 3485-3485/com.ichi2.anki I/NativeMethods: ExecuteCommand: localMinutesWest
2021-08-12 14:09:00.632 3485-3485/com.ichi2.anki I/NativeMethods: ExecuteCommand: localMinutesWest
2021-08-12 14:09:00.632 3485-3485/com.ichi2.anki I/CollectionHelper: End openCollection: /storage/emulated/0/AnkiDroid (1)/collection.anki2
2021-08-12 14:09:00.633 3485-3485/com.ichi2.anki I/BootService: Executing Boot Service
2021-08-12 14:09:00.663 3485-3485/com.ichi2.anki E/com.ichi2.anki: Invalid ID 0x00000000.
2021-08-12 14:09:00.684 3485-3485/com.ichi2.anki I/IntentHandler: Launching DeckPicker
2021-08-12 14:09:00.771 3485-3485/com.ichi2.anki I/AnkiActivity: AnkiActivity::onCreate - DeckPicker
2021-08-12 14:09:00.788 3485-3485/com.ichi2.anki I/DeckPicker: No startup screens required
2021-08-12 14:09:00.807 3485-3485/com.ichi2.anki E/com.ichi2.anki: Invalid ID 0x00000000.
2021-08-12 14:09:01.076 3485-3485/com.ichi2.anki W/com.ichi2.anki: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2021-08-12 14:09:01.076 3485-3485/com.ichi2.anki W/com.ichi2.anki: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2021-08-12 14:09:01.109 3485-3485/com.ichi2.anki I/AnkiActivity: AnkiActivity::onStart - DeckPicker
2021-08-12 14:09:01.136 3485-3485/com.ichi2.anki I/AnkiActivity: AnkiActivity::onResume - DeckPicker
2021-08-12 14:09:01.224 3485-3599/com.ichi2.anki I/AdrenoGLES-0: QUALCOMM build                   : 781e7d0, I46ff5fc46f
    Build Date                       : 12/01/20
    OpenGL ES Shader Compiler Version: EV031.31.04.01
    Local Branch                     : QPR1
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
2021-08-12 14:09:01.224 3485-3599/com.ichi2.anki I/AdrenoGLES-0: Build Config                     : C P 11.0.1 AArch64
2021-08-12 14:09:01.224 3485-3599/com.ichi2.anki I/AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
2021-08-12 14:09:01.229 3485-3599/com.ichi2.anki I/AdrenoGLES-0: PFP: 0x016ee189, ME: 0x00000000
2021-08-12 14:09:01.237 3485-3599/com.ichi2.anki W/AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
2021-08-12 14:09:01.237 3485-3599/com.ichi2.anki W/AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
2021-08-12 14:09:01.341 3485-3599/com.ichi2.anki I/Gralloc4: mapper 4.x is not supported
2021-08-12 14:09:01.342 3485-3599/com.ichi2.anki W/Gralloc3: mapper 3.x is not supported
2021-08-12 14:09:01.516 3485-3485/com.ichi2.anki I/DeckPicker$UpdateDeckListListener: Updating deck list UI
2021-08-12 14:09:03.318 3485-3485/com.ichi2.anki I/DeckPicker$UpdateDeckListListener: Updating deck list UI
2021-08-12 14:09:03.760 3485-3500/com.ichi2.anki I/com.ichi2.anki: WaitForGcToComplete blocked RunEmptyCheckpoint on ProfileSaver for 17.619ms
2021-08-12 14:09:04.921 3485-3485/com.ichi2.anki I/DeckPicker: DeckPicker:: Selected deck with id 1609155951022
2021-08-12 14:09:04.936 3485-3485/com.ichi2.anki I/AnkiActivity: AnkiActivity::onPause - DeckPicker
2021-08-12 14:09:05.041 3485-3485/com.ichi2.anki I/AnkiActivity: AnkiActivity::onCreate - Reviewer
2021-08-12 14:09:05.183 3485-3612/com.ichi2.anki I/CollectionTask$GetCard: Obtaining card
2021-08-12 14:09:05.183 3485-3485/com.ichi2.anki I/ViewGroupUtils: ViewGroupUtils::setRenderWorkaround - using default / hardware rendering
2021-08-12 14:09:05.188 3485-3485/com.ichi2.anki I/AnkiActivity: AnkiActivity::onStart - Reviewer
2021-08-12 14:09:05.192 3485-3485/com.ichi2.anki I/AnkiActivity: AnkiActivity::onResume - Reviewer
2021-08-12 14:09:05.196 3485-3612/com.ichi2.anki E/Threads: must be called on the main thread instead of Thread[AsyncTask #1,5,main]
2021-08-12 14:09:05.197 3485-3612/com.ichi2.anki E/Threads: must be called on the main thread instead of Thread[AsyncTask #1,5,main]
2021-08-12 14:09:05.210 3485-3616/com.ichi2.anki I/NativeMethods: ExecuteCommand: localMinutesWest
2021-08-12 14:09:05.337 3485-3485/com.ichi2.anki E/com.ichi2.anki: Invalid ID 0x00000000.
2021-08-12 14:09:05.440 3485-3485/com.ichi2.anki I/ViewGroupUtils: ViewGroupUtils::setRenderWorkaround - using default / hardware rendering
2021-08-12 14:09:05.468 3485-3541/com.ichi2.anki W/com.ichi2.anki: Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
2021-08-12 14:09:05.482 3485-3541/com.ichi2.anki W/cr_media: Requires BLUETOOTH permission
2021-08-12 14:09:05.568 3485-3485/com.ichi2.anki E/Sound: playSounds - Error reproducing sound file:///storage/emulated/0/AnkiDroid%20(1)/collection.media/ankidroid_audiorec1148895069.3gp
    java.io.FileNotFoundException: /storage/emulated/0/AnkiDroid (1)/collection.media/ankidroid_audiorec1148895069.3gp: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:492)
        at java.io.FileInputStream.<init>(FileInputStream.java:160)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1185)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1163)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1128)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1059)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1005)
        at com.ichi2.libanki.Sound.playSoundInternal(Sound.java:375)
        at com.ichi2.libanki.Sound.playSounds(Sound.java:255)
        at com.ichi2.anki.AbstractFlashcardViewer.playSounds(AbstractFlashcardViewer.java:2447)
        at com.ichi2.anki.AbstractFlashcardViewer.playSounds(AbstractFlashcardViewer.java:2424)
        at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:2397)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:2161)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:2119)
        at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:1051)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:672)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:644)
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:217)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:791)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7550)
        at libcore.io.IoBridge.open(IoBridge.java:478)
        at java.io.FileInputStream.<init>(FileInputStream.java:160) 
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1185) 
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1163) 
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1128) 
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1059) 
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1005) 
        at com.ichi2.libanki.Sound.playSoundInternal(Sound.java:375) 
        at com.ichi2.libanki.Sound.playSounds(Sound.java:255) 
        at com.ichi2.anki.AbstractFlashcardViewer.playSounds(AbstractFlashcardViewer.java:2447) 
        at com.ichi2.anki.AbstractFlashcardViewer.playSounds(AbstractFlashcardViewer.java:2424) 
        at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:2397) 
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:2161) 
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:2119) 
        at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:1051) 
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:672) 
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:644) 
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:217) 
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:791) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7664) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2021-08-12 14:09:05.570 3485-3485/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 3485
    java.lang.IllegalArgumentException: Illegal null AudioFocusRequest
        at android.media.AudioManager.abandonAudioFocusRequest(AudioManager.java:3144)
        at com.ichi2.compat.CompatV26.abandonAudioFocus(CompatV26.java:154)
        at com.ichi2.libanki.Sound.releaseSound(Sound.java:523)
        at com.ichi2.libanki.Sound.playSoundInternal(Sound.java:400)
        at com.ichi2.libanki.Sound.playSounds(Sound.java:255)
        at com.ichi2.anki.AbstractFlashcardViewer.playSounds(AbstractFlashcardViewer.java:2447)
        at com.ichi2.anki.AbstractFlashcardViewer.playSounds(AbstractFlashcardViewer.java:2424)
        at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:2397)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:2161)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:2119)
        at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:1051)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:672)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:644)
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:217)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:791)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-08-12 14:09:05.574 3485-3485/com.ichi2.anki I/ACRA: ACRA is disabled for com.ichi2.anki - forwarding uncaught Exception on to default ExceptionHandler
2021-08-12 14:09:05.594 3485-3485/com.ichi2.anki I/Process: Sending signal. PID: 3485 SIG: 9
```
