### ISSUE TITLE
[Bug] Unit test failure locally: testInitialActivityResult 

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9419]
```
com.ichi2.anki.InitialActivityWithConflictTest > testInitialActivityResult FAILED
    java.lang.NullPointerException
        at com.ichi2.anki.AnkiDroidApp.webViewFailedToLoad(AnkiDroidApp.java:626)
        at com.ichi2.anki.InitialActivity.getStartupFailureType(InitialActivity.java:50)
        at com.ichi2.anki.InitialActivityWithConflictTest.testInitialActivityResult(InitialActivityWithConflictTest.java:63)
```

**Comment by david-allison-1** [comment]
The test relied on `Application`, using `EmptyApplication` worked because the static variable was previously set
