### ISSUE TITLE
[Bug] CardTemplateEditor crash

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#9442]
###### Reproduction Steps

The google auto-testing robots crashed in CardTemplateEditor as they spam-click-tested the latest release.

Some combination of field editing then touch field add button and boom

https://youtu.be/1ad0dNNI2Cs

###### Expected Result

No crash ever

###### Actual Result

```
FATAL EXCEPTION: Thread-6
Process: com.ichi2.anki, PID: 9983
java.lang.NullPointerException: Attempt to invoke direct method 'void com.ichi2.anki.CardTemplateEditor$CardTemplateFragment.insertField(java.lang.String)' on a null object reference
	at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment.access$1300(CardTemplateEditor.java:1)
	at com.ichi2.anki.CardTemplateEditor.lambda$onCreate$0(CardTemplateEditor.java:1)
	at com.ichi2.anki.CardTemplateEditor.f(Unknown Source:0)
	at com.ichi2.anki.z1.insertField(Unknown Source:2)
	at com.ichi2.anki.dialogs.InsertFieldDialog.selectFieldAndClose(InsertFieldDialog.java:1)
	at com.ichi2.anki.dialogs.InsertFieldDialog.access$100(InsertFieldDialog.java:1)
	at com.ichi2.anki.dialogs.InsertFieldDialog$1.lambda$onBindViewHolder$0(InsertFieldDialog.java:1)
	at com.ichi2.anki.dialogs.InsertFieldDialog$1.a(Unknown Source:0)
	at com.ichi2.anki.dialogs.g1.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7448)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28305)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:6)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:6)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:1)
	at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:5)
	at androidx.test.espresso.action.Tap.-$$Nest$smsendSingleTap(Unknown Source:0)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:21)
	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(Unknown Source:0)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

###### Debug info

Last alpha build 

Not sure which PR did it - there needs to be a unit test that reproduces it, then you may git bisect based on that if the issue isn't obvious, but the history is full of no one but @Akshay0701 in the file recently so Akshay - you are probably most familiar? https://github.com/ankidroid/Anki-Android/commits/master/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Akshay0701** [comment]
Crash steps
1 open editor 
2 open preview 
3 back to editor 
4 open insert field dialog 
5 select field name and boom we crashed.


I am looking into it ...
