### ISSUE TITLE
Info.java: needs a regression test for all languages

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9555]
Info.java: needs a regression test for each language - it currently crashes due to https://github.com/ankidroid/Anki-Android/issues/9550#issuecomment-926827683

This is the info obtained via `Settings - Advanced - About AnkiDroid`

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/9550#issuecomment-926829062_

**Comment by david-allison-1** [comment]
```
 Process: com.ichi2.anki, PID: 24159
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.Info}: java.util.MissingFormatArgumentException: Format specifier '%3$s'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.util.MissingFormatArgumentException: Format specifier '%3$s'
        at java.util.Formatter.format(Formatter.java:2529)
        at java.util.Formatter.format(Formatter.java:2459)
        at java.lang.String.format(String.java:2870)
        at com.ichi2.anki.Info.onCreate(Info.java:126)
        at android.app.Activity.performCreate(Activity.java:7994)
        at android.app.Activity.performCreate(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7664) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

**Comment by prateek-singh-3212** [comment]
Yes, Go ahead 🚀

**Comment by adarrssh** [comment]
Hey i tried to make anki-droid in android studio .
I changed the language to Sardinian and then went to setting ->advanced setting ->about Ankidroid but didn't face any crash,
what can i do next?

![image](https://user-images.githubusercontent.com/85433137/136316974-db17dd84-5985-4d7f-97ec-d309fca3ce9d.png)

**Comment by david-allison-1** [comment]
What's the result of `git rev-parse HEAD`

**Comment by adarrssh** [comment]
1.I just forked the anki-droid repo from GitHub and  2.tried run on my device and then 
3.I changed language in app and then went to 'about ankidroid' section but didn't get a crash  .


Where wrong steps did I take ?

**Comment by david-allison-1** [comment]
You need to check it out at a specific commit. It's not broken on `master`

> Checkout AnkiDroid at f961eb7

https://github.com/ankidroid/Anki-Android/issues/9555#issuecomment-936734994

**Comment by david-allison-1** [comment]
I've explained in the bullet points above.

You're in a detached HEAD state. That's correct. Make a branch and commit at the point of failure

Once you get a failing test, cherry pick the commit to a branch off master
