### ISSUE TITLE
[Bug] Value null at creationOffset of type org.json.JSONObject$1 cannot be converted to int

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9557]
```
com.ichi2.utils.JSONException: org.json.JSONException: Value null at creationOffset of type org.json.JSONObject$1 cannot be converted to int
at com.ichi2.utils.JSONObject.getInt(JSONObject.java:2)
at com.ichi2.libanki.Config.getInt(Config.kt:1)
at com.ichi2.libanki.Collection.get_config(Collection.java:6)
at com.ichi2.libanki.sched.SchedV2._creation_timezone_offset(SchedV2.java:1)
at com.ichi2.libanki.sched.SchedV2._timingToday(SchedV2.java:3)
at com.ichi2.libanki.sched.SchedV2._updateCutoff(SchedV2.java:2)
at com.ichi2.libanki.sched.SchedV2.<init>(SchedV2.java:18)
at com.ichi2.libanki.Collection._loadScheduler(Collection.java:3)
at com.ichi2.libanki.Collection.<init>(Collection.java:20)
at com.ichi2.libanki.Storage.Collection(Storage.java:10)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:8)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:3)
at com.ichi2.anki.CollectionHelper.getColSafe(CollectionHelper.java:1)
at com.ichi2.anki.DeckPicker.onPrepareOptionsMenu(DeckPicker.java:1)
at android.app.Activity.onPreparePanel(Activity.java:4325)
at androidx.fragment.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:1)
at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:1)
at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3)
at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:1)
at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:6)
at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:1)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1076)
at android.view.Choreographer.doCallbacks(Choreographer.java:897)
at android.view.Choreographer.doFrame(Choreographer.java:822)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1061)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:236)
at android.app.ActivityThread.main(ActivityThread.java:8061)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: org.json.JSONException: Value null at creationOffset of type org.json.JSONObject$1 cannot be converted to int
at org.json.JSON.typeMismatch(JSON.java:101)
at org.json.JSONObject.getInt(JSONObject.java:492)
at com.ichi2.utils.JSONObject.getInt(JSONObject.java:1)
... 33 more
at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:1)
```

**Comment by david-allison-1** [comment]
Issue with 

`getCol().get_config("creationOffset", 0)` - throws if the value is null

**Comment by pratik2315** [comment]
Is there any way I can reproduce this bug?

**Comment by david-allison-1** [comment]
The above call in a test should be all that's required. I'll get it fixed.
