### ISSUE TITLE
[Bug] CI - Broken test: resetResetAllElementsFromOnboarding

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9597]
Works on my machine.

The following returns 4 on my machine. 5 on CI
```kotlin
val featuresAvailableForReset = OnboardingUtils.featureConstants.size
```

```
com.ichi2.anki.OnboardingUtilsTest > resetResetAllElementsFromOnboarding FAILED
    java.lang.AssertionError: All onboarding identifiers are available for reset
    Expected: <5>
         but: was <4>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at com.ichi2.anki.OnboardingUtilsTest.resetResetAllElementsFromOnboarding(OnboardingUtilsTest.kt:37)
```

**Comment by david-allison-1** [comment]
Improved output:

```
com.ichi2.anki.OnboardingUtilsTest > resetResetAllElementsFromOnboarding FAILED
    java.lang.AssertionError: All onboarding identifiers are available for reset
    Expected: iterable over ["CardBrowserOnboarding", "ReviewerOnboarding", "NoteEditorOnboarding", "FirstEnum", "DeckPickerOnboarding"] in any order
         but: No item matches: "FirstEnum" in ["CardBrowserOnboarding", "DeckPickerOnboarding", "NoteEditorOnboarding", "ReviewerOnboarding"]
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at com.ichi2.anki.OnboardingUtilsTest.resetResetAllElementsFromOnboarding(OnboardingUtilsTest.kt:39)
```

> No item matches: "FirstEnum" in

Caused by interference from https://github.com/ankidroid/Anki-Android/blob/efed27bbb15e48de435caef5252d9a341c6d36d9/AnkiDroid/src/test/java/com/ichi2/anki/OnboardingFlagTest.kt#L33
