### ISSUE TITLE
[Bug] Crash - Card Template Editor - can't add new template if "full sync" dialog appears

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#9688]
###### Reproduction Steps

1. Perform a full sync if necessary 
2. Make a new note type
3. Add a template

###### Expected Result

4. Crash

###### Actual Result

5. No Crash

###### Debug info
2.16 alpha 19
###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

```
    Process: com.ichi2.anki, PID: 13757
    java.lang.IllegalStateException: Fragment CardTemplateFragment{f5305ee} (3cc26b70-e5d3-4e01-ad27-1ee1c27ff9bd) not attached to a context.
        at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
        at androidx.fragment.app.Fragment.getResources(Fragment.java:964)
        at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment.newCardName(CardTemplateEditor.java:1056)
        at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment.addNewTemplate(CardTemplateEditor.java:1010)
        at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment.addNewTemplateWithCheck(CardTemplateEditor.java:986)
        at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment.lambda$confirmAddCards$6$com-ichi2-anki-CardTemplateEditor$CardTemplateFragment(CardTemplateEditor.java:920)
        at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment$$ExternalSyntheticLambda8.run(Unknown Source:4)
        at com.ichi2.anki.dialogs.ConfirmationDialog.lambda$onCreateDialog$2$com-ichi2-anki-dialogs-ConfirmationDialog(ConfirmationDialog.java:66)
        at com.ichi2.anki.dialogs.ConfirmationDialog$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
        at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:410)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by david-allison-1** [comment]
The ordering of "add 0 new cards? Proceed" seems to be different

**Comment by s-deepak-kumar** [comment]
Can I Work On It?

**Comment by david-allison** [comment]
> Can I Work On It?

sure!

**Comment by n1snt** [comment]
@s-deepak-kumar are you still working on it?
