### ISSUE TITLE
[Bug] v2.16alpha33 crashes when changing Decks in Card Browser and Statistics 

### ISSUE THREAD

**Issue by ThoreBor** [ankidroid/Anki-Android#9914]
###### Reproduction Steps

1.  Open Card Browser or Statistics
2.  Tap on the deck on top to change it

###### Expected Result
Deck selector pops up

###### Actual Result
App crashes

###### Debug info
AnkiDroid Version = 2.16alpha33
Android Version = 11
Manufacturer = Xiaomi
Model = Redmi Note 8 Pro
Hardware = mt6785
Webview User Agent = Mozilla/5.0 (Linux; Android 11; Redmi Note 8 Pro Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.45 Mobile Safari/537.36
ACRA UUID = 748a0c66-d316-44d1-b35d-89891a69b2bf
Scheduler = std2
Crash Reports Enabled = true
DatabaseV2 Enabled = true

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Thanks!

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/df4d5354-da4b-4cdf-a3d4-880a0d185c03

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.widget.Spinner.getSelectedItem()' on a null object reference
at com.ichi2.anki.dialogs.DeckSelectionDialog$DecksArrayAdapter.onBindViewHolder(DeckSelectionDialog.kt:4)
at com.ichi2.anki.dialogs.DeckSelectionDialog$DecksArrayAdapter.onBindViewHolder(DeckSelectionDialog.kt:1)
at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:1)
at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:8)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:7)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:55)
at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:2)
at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:3)
at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:9)
at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:65)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:13)
at android.view.View.measure(View.java:26057)
at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
at android.view.View.measure(View.java:26057)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7105)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:26057)
at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(MDRootLayout.java:35)
at android.view.View.measure(View.java:26057)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7105)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:26057)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7105)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
at android.view.View.measure(View.java:26057)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7105)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at com.android.internal.policy.DecorView.onMeasure(DecorView.java:767)
at android.view.View.measure(View.java:26057)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3633)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2411)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2677)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2135)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8622)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:975)
at android.view.Choreographer.doCallbacks(Choreographer.java:799)
at android.view.Choreographer.doFrame(Choreographer.java:734)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:960)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:236)
at android.app.ActivityThread.main(ActivityThread.java:8057)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```

**Comment by david-allison-1** [comment]
Introduced in f96bdfbc1f756e6e7b61d404e50c3acd3f3d7716. #9755

https://github.com/ankidroid/Anki-Android/blob/f96bdfbc1f756e6e7b61d404e50c3acd3f3d7716/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java#L343

This spinner only exists in `NoteEditor`

**Comment by ThoreBor** [comment]
I'm not completely sure, but I think it worked in 2.16beta20 and earlier. I didn't test any betas between 20 and 33 though.

**Comment by ThoreBor** [comment]
> Introduced in [f96bdfb](https://github.com/ankidroid/Anki-Android/commit/f96bdfbc1f756e6e7b61d404e50c3acd3f3d7716). #9755
> 
> https://github.com/ankidroid/Anki-Android/blob/f96bdfbc1f756e6e7b61d404e50c3acd3f3d7716/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java#L343
> 
> This spinner only exists in `NoteEditor`

Alright, great!

**Comment by david-allison-1** [comment]
Will get this sorted today. My thoughts are that alpha feedback is invaluable to us, and in return we should keep alpha users as happy as possible

**Comment by mikehardy** [comment]
> Will get this sorted today. My thoughts are that alpha feedback is invaluable to us, and in return we should keep alpha users as happy as possible

:100: on that - merged and I'm sorting the rest of the days PRs right now, will do a new alpha afterwards. Note @ThoreBor that we are blocked from uploading to the play store alpha channel until we finish scoped storage migration work and can increase our target API, but they will be on the releases page

**Comment by ThoreBor** [comment]
Thank you guys for the fast fix. I always download from the releases page.
